export type CapabilityId='auth'|'world-memory'|'money-engine'|'movie-box'|'holo-credits'|'accessibility'|'jacobie-vision'|'agency'|'university'|'holoarena'
export type CapabilityContract={id:CapabilityId;owner:string;backend:string;adapters:string[];truth:string}
export const CAPABILITY_REGISTRY:Record<CapabilityId,CapabilityContract>={
 auth:{id:'auth',owner:'Supabase Auth/session boundary',backend:'shared authenticated Supabase/API boundary',adapters:['GameVerse','Immersive','University','Agency','HoloArena','Movie Box'],truth:'No feature creates a second identity/session system.'},
 'world-memory':{id:'world-memory',owner:'StreetVerse life/biography persistence',backend:'streetverse life + checkpoint/World Memory persistence',adapters:['GameVerse','Immersive Library','University evidence','HoloArena sessions','Movie Box projects'],truth:'Worlds write through shared persistence; they do not invent separate save systems.'},
 'money-engine':{id:'money-engine',owner:'TRYAMM Money Engine',backend:'shared server-authoritative financial journal/payout/provider boundary',adapters:['creator earnings','agency commissions','game prizes','Pastor Kofi service share','sponsor beneficiary allocation','commerce'],truth:'No UI or game module mints payable money.'},
 'movie-box':{id:'movie-box',owner:'TRYAMM Movie Box',backend:'shared project/provenance/export contract',adapters:['GameVerse','HoloArena','HoloMusic','Immersive','University portfolio'],truth:'One movie project model; verticals only pass source scenes/assets/rights.'},
 'holo-credits':{id:'holo-credits',owner:'Holo Credit wallet/ledger',backend:'server-authoritative HC wallet + entitlement ledger',adapters:['Movie Box','games','digital store','University digital labs'],truth:'Closed-loop digital credits remain separate from creator earnings and cash prizes.'},
 accessibility:{id:'accessibility',owner:'Accessibility Passport',backend:'shared accessibility preference/profile contract',adapters:['all interactive surfaces'],truth:'Accessibility is never paywalled and verticals consume one preference model.'},
 'jacobie-vision':{id:'jacobie-vision',owner:'Jacobie Vision Security',backend:'shared risk/security/incident policy',adapters:['Auth','Mobile','Agency','Money Engine','HoloArena','HoloFon'],truth:'Security signals feed one policy layer rather than separate fraud engines.'},
 agency:{id:'agency',owner:'Agency Growth + Founder Priority',backend:'shared agencies/memberships/invites/attribution RLS',adapters:['Mobile','Creators','LIVE/PK','University recruiting','HoloArena creator teams'],truth:'One agency identity and attribution graph.'},
 university:{id:'university',owner:'All American University runtime',backend:'shared student/program/course/evidence/credential tables',adapters:['Immersive missions','GameVerse missions','HoloArena XR lab','Movie Box portfolio'],truth:'Learning adapters do not create parallel student/credential stores.'},
 holoarena:{id:'holoarena',owner:'TRYAMM HoloArena',backend:'shared venue/room/session/member/safety/highlight runtime',adapters:['four launch games','World Memory','Movie Box','University XR lab','store/membership'],truth:'One venue session runtime; games plug into it as experiences.'},
}
export const CONVERGENCE_RULES=['STOP DUPLICATING FEATURES','REUSE EXISTING SYSTEMS','ONE CONTRACT PER CAPABILITY','THIN UI ADAPTERS','SHARED BACKEND','AUTOMATED SMOKE','PARALLEL CI','MERGE ONLY GREEN LANES'] as const
export const assertCapabilityRegistry=()=>{const ids=Object.keys(CAPABILITY_REGISTRY);if(new Set(ids).size!==ids.length)throw new Error('duplicate capability id');for(const c of Object.values(CAPABILITY_REGISTRY)){if(!c.owner||!c.backend||!c.truth)throw new Error(`incomplete capability ${c.id}`)}return true}
