export type ExpansionGate='build-now'|'provider-rights'|'regulated-research'|'needs-verification'
export type ExpansionModule={id:string;name:string;gate:ExpansionGate;purpose:string;integrates:string[];notes:string[]}

export const TRYAMM_EXPANSION_EPIC:ExpansionModule[]=[
 {id:'ott-marketplace',name:'All American OTT + Streaming Marketplace',gate:'build-now',purpose:'Multi-platform creator/channel publishing, subscriptions, FAST/OTT discovery and marketplace conversion.',integrates:['All American Network','Movie Box','HoloMusic','Creator Economy','Holo Credits','Conversion OS'],notes:['Use authorized distribution APIs/feeds only','Do not rebroadcast unlicensed channels/content']},
 {id:'simulcast',name:'Multi-Platform Simulcast Router',gate:'provider-rights',purpose:'Publish an authorized creator stream to multiple connected services from one control plane.',integrates:['LIVE','Movie Box','Creator Agency','Analytics'],notes:['Per-platform OAuth/API credentials required','Respect platform rate limits and terms']},
 {id:'assumable-housing',name:'Assumable Mortgage / Housing Discovery',gate:'regulated-research',purpose:'Search and education workflows for potentially assumable loans/properties with lender/servicer verification.',integrates:['PropertyVerse','Marketplace','AI Call Center'],notes:['Never represent a mortgage as assumable without lender/servicer evidence','Licensing/disclosure rules vary by jurisdiction']},
 {id:'neuro-suit',name:'Neuromuscular Assistive Suit Research Lane',gate:'regulated-research',purpose:'Accessibility R&D for non-invasive assistive wearables, rehab interfaces and controller mappings.',integrates:['HoloArena','Accessibility Passport','University XR Lab'],notes:['Medical claims require clinical/regulatory evidence','No autonomous therapy or treatment claims']},
 {id:'lung-cooling',name:'Respiratory/Lung Cooling Research Lane',gate:'regulated-research',purpose:'Research registry for thermal/respiratory support concepts and evidence review.',integrates:['All American University','Health Research'],notes:['No device design or treatment claims without clinical engineering, medical oversight and regulatory pathway']},
 {id:'dante-game',name:'Dante Inferno: Escape from Hell — Set Apart Edition',gate:'build-now',purpose:'Original symbolic/literary faith adventure inspired by public-domain/lawful source material, with accessibility and World Memory.',integrates:['GameVerse','Immersive Library','Bible/Metaverse Bible','Movie Box'],notes:['Use original art/dialogue and public-domain/rights-cleared source material','Avoid copying modern game/movie adaptations']},
 {id:'mind-control',name:'Hands-Free / Intent Control Lab',gate:'regulated-research',purpose:'Accessibility control via gaze, switch, voice, EMG/EEG vendor adapters and calibration—not claims of literal mind reading.',integrates:['GameVerse','HoloArena','Accessibility Passport'],notes:['BCI/medical hardware requires approved vendor APIs and safety testing','Fallback controls always available']},
 {id:'subscription-retention',name:'Subscription Retention Engine',gate:'build-now',purpose:'Optimize long-term value, accessibility, churn prevention and customer satisfaction instead of manipulative lock-in.',integrates:['Conversion OS','AI Call Center','Creator Economy','University','Mobile'],notes:['No dark patterns','Easy cancellation and transparent billing']},
 {id:'quarantine-world',name:'Warren Quarantine Zone',gate:'build-now',purpose:'Original survival/story world with missions, factions, evacuation, rebuilding and World Memory.',integrates:['StreetVerse','GameVerse','Movie Box'],notes:['Original fictional setting unless a documented existing TRYAMM canon source is recovered']},
 {id:'bible-world',name:'Bible + Metaverse Bible Experience',gate:'build-now',purpose:'Searchable scripture study, immersive maps/timelines, missions, learning and discussion.',integrates:['Immersive Library','All American University','GameVerse'],notes:['Track translation/source provenance','Separate scripture text, commentary and player-created interpretation']},
 {id:'security-research',name:'Jacobie Vision Public Security Research',gate:'provider-rights',purpose:'Lawful public security research, hardening and defensive training.',integrates:['Jacobie Vision','University','Agent OS'],notes:['Do not ingest stolen/leaked private materials','Use public lawful research and authorized test environments only']},
 {id:'record-academy',name:'Christian Record Label + Academy + Streaming Academy',gate:'build-now',purpose:'Rights-first music creation, publishing, education, sample clearance, distribution and creator business training.',integrates:['Aniyah 64-Track','HoloMusic','Sample Rights','All American University','StarVerse'],notes:['10,000-bps split checks','Sample/rights release gate']},
 {id:'godot-holo',name:'TRYAMM HoloForge Engine',gate:'build-now',purpose:'AI-assisted 3D world/scene editor inspired by open game-engine workflows without cloning a third-party product.',integrates:['GameVerse','HoloArena','Movie Box','Asset Forge','Lottie 2.0'],notes:['Prefer open standards: glTF/GLB, WebXR/OpenXR adapters, reusable scene graphs','Can interoperate with Godot/Blender assets rather than copying their code/brand']},
 {id:'workstation',name:'Connected Workstation / OmniDesk',gate:'build-now',purpose:'One authorized control surface for the user’s own linked devices, sessions, files and production tools.',integrates:['HoloGPT','Agent OS','Movie Box','University','GitHub'],notes:['Device enrollment + explicit authorization','No covert remote access']},
 {id:'black-business-growth',name:'Black-Owned Business Growth Engine',gate:'build-now',purpose:'Permission-based directory outreach, claim-your-business, storefront creation, campaigns and 50-state expansion.',integrates:['All American Marketplace','Conversion OS','AI Call Center','Mobile','SEO'],notes:['Use public/business-contact data lawfully','Opt-out/DNC/contact preference controls','No spam blasting']},
 {id:'open-agent-router',name:'Open Agent Router',gate:'build-now',purpose:'Route tasks across hosted and local models/tools with provider health, cost, capability and privacy policy.',integrates:['HoloGPT','Ollama','Hugging Face','OpenRouter-style adapters','GitHub','n8n'],notes:['Free/local routes when available','Provider credentials/terms remain required where applicable']},
 {id:'chat-bridges',name:'Messaging Bridge Layer',gate:'provider-rights',purpose:'Authorized integration adapters for Discord, Telegram, WhatsApp, LINE and other supported channels.',integrates:['AI Call Center','Agency OS','Support'],notes:['OAuth/API approval per service','No scraping private chats']},
 {id:'automation',name:'Automation + Virtual Agent Fabric',gate:'build-now',purpose:'Workflow/event automation for email, CRM, support, deployment and operations.',integrates:['n8n-style workflows','AI Call Center','AWS API Gateway adapters','CRM adapters'],notes:['Human approval gates for financial/legal/high-impact actions','Audit every agent action']},
 {id:'rag-memory',name:'RAG + Git Evidence Memory',gate:'build-now',purpose:'Source-backed memory using documents, embeddings, commits, tests and state history rather than hidden reasoning logs.',integrates:['HoloGPT','GitHub','World Memory','Immersive Library'],notes:['Record decisions/evidence/outputs, not private chain-of-thought','Deterministic provenance for important actions']},
 {id:'synthetic-media',name:'Consent-Based Synthetic Media Studio',gate:'provider-rights',purpose:'Image/video generation, avatars, dubbing and character performance with identity/rights controls.',integrates:['Movie Box','StarVerse','HoloMusic','Creator Economy'],notes:['No impersonation/deepfake of real people without permission','Label synthetic media where appropriate']},
 {id:'trend-engine',name:'TRYAMM Trend Intelligence',gate:'build-now',purpose:'Original trend research/creator opportunity engine using lawful public signals and first-party analytics.',integrates:['Creator Economy','SEO','All American Network','Agency OS'],notes:['Do not clone another company’s proprietary dataset/UI','Build our own scoring, provenance and recommendations']},
 {id:'external-ai-builders',name:'External AI Builder Adapters',gate:'provider-rights',purpose:'Optional connectors to current AI app/image/video services when APIs/terms allow.',integrates:['Asset Forge','Movie Box','Agent OS'],notes:['Floot appears to be an AI app builder but needs verified API/terms before integration','Kling/Seedance/other providers require official credentials or authorized endpoints']},
 {id:'lawsuit-legal-memory',name:'Legal Case / Lawsuit Research Library',gate:'needs-verification',purpose:'Source-backed legal research cards and lessons learned where relevant to product design.',integrates:['Immersive Library','University','Compliance'],notes:['“LA tack two lawsuit” and “Ray Reynolds method” were not reliably identified from the provided wording','Do not encode claims until exact source is verified']},
]

export const EXPANSION_RELEASE_RULES=[
 'ONE MODULE -> ONE OWNER -> ONE ROUTE -> ONE AUTH CONTRACT -> ONE DATA CONTRACT -> ONE SMOKE TEST',
 'Every provider integration has a feature flag and health check.',
 'Every regulated/medical system stays research-only until expert/regulatory proof exists.',
 'Every real-person likeness/voice/biography requires permission or a rights-safe public-information treatment.',
 'Every external-source fact stores provenance; leaked/stolen/private data is rejected.',
 'Every new public page gets SEO metadata, CTA, accessibility and AI Call Center routing.',
] as const
