const SUPPORTED_SIGN_LANGUAGES = ['asl', 'bsl', 'lsf', 'dgs', 'auslan', 'isl', 'jls']
const MODES = ['gloss', 'fingerspell', 'avatar']
const PROVIDER_URL = (process.env.SIGN_LANGUAGE_PROVIDER_URL || '').replace(/\/$/, '')
const PROVIDER_KEY = process.env.SIGN_LANGUAGE_PROVIDER_KEY || ''
function cleanText(value){return String(value||'').trim().replace(/\s+/g,' ').slice(0,4000)}
function normalizeLanguage(value){const code=String(value||'asl').toLowerCase();return SUPPORTED_SIGN_LANGUAGES.includes(code)?code:'asl'}
function normalizeMode(value){const mode=String(value||'gloss').toLowerCase();return MODES.includes(mode)?mode:'gloss'}
function localGloss(text){return cleanText(text).replace(/[^\p{L}\p{N}'\-\s]/gu,'').split(/\s+/).filter(Boolean).map(token=>token.toUpperCase())}
function fingerspell(gloss){return gloss.map(token=>[...token].filter(char=>/[A-Z0-9]/.test(char)))}
async function providerRequest(path,payload){if(!PROVIDER_URL)return null;const response=await fetch(`${PROVIDER_URL}${path}`,{method:'POST',headers:{'Content-Type':'application/json',...(PROVIDER_KEY?{Authorization:`Bearer ${PROVIDER_KEY}`}:{})},body:JSON.stringify(payload),signal:AbortSignal.timeout(12000)});if(!response.ok)throw new Error(`Sign provider returned ${response.status}`);return response.json()}
function capabilities(){const providerConfigured=Boolean(PROVIDER_URL);return{version:'1.0.0',providerConfigured,supportedSignLanguages:SUPPORTED_SIGN_LANGUAGES,modes:MODES,features:{textToSign:true,speechToSign:true,signToText:providerConfigured,signToSpeech:providerConfigured,liveCaptions:true,offlineFingerspelling:true,avatarReady:providerConfigured}}}
async function translate({text,signLanguage,mode}){const input=cleanText(text);if(!input)throw Object.assign(new Error('text is required'),{statusCode:400});const language=normalizeLanguage(signLanguage),outputMode=normalizeMode(mode);try{const remote=await providerRequest('/translate',{text:input,signLanguage:language,mode:outputMode});if(remote)return{input,signLanguage:language,mode:outputMode,gloss:Array.isArray(remote.gloss)?remote.gloss:localGloss(input),fingerspelling:remote.fingerspelling,avatarSequence:remote.avatarSequence,provider:'configured',warnings:remote.warnings||[]}}catch(error){console.warn('Sign translation provider unavailable:',error.message)}const gloss=localGloss(input);return{input,signLanguage:language,mode:outputMode,gloss,fingerspelling:outputMode==='fingerspell'?fingerspell(gloss):undefined,avatarSequence:outputMode==='avatar'?gloss.map(token=>({token})):undefined,provider:'local-fallback',warnings:['Fallback output preserves words but is not a complete grammatical sign-language translation.','Connect a Deaf-community-validated translation/recognition model before calling this production-complete ASL.']}}
async function recognize({signLanguage,landmarks,videoUrl}){if(!PROVIDER_URL)throw Object.assign(new Error('Sign-recognition provider is not configured'),{statusCode:503});if((!Array.isArray(landmarks)||landmarks.length===0)&&!videoUrl)throw Object.assign(new Error('landmarks or videoUrl is required'),{statusCode:400});const language=normalizeLanguage(signLanguage);const remote=await providerRequest('/recognize',{signLanguage:language,landmarks,videoUrl});return{text:String(remote?.text||''),confidence:Number(remote?.confidence||0),provider:'configured'}}
module.exports={capabilities,translate,recognize}
