'use strict';
const assert=require('assert');
const fs=require('fs');
for(const file of ['server.js','music-api.js','public/index.html','public/app.js','public/styles.css','public/music-hub.html','public/music-hub.js','public/music-hub.css','public/community-rules.html']) assert(fs.existsSync(file),`${file} missing`);
const server=fs.readFileSync('server.js','utf8');
for(const route of ['/api/health','/api/auth/register','/api/rooms','/api/checkout','/api/admin/summary','music-api']) assert(server.includes(route),`${route} missing`);
const music=fs.readFileSync('music-api.js','utf8');
for(const route of ['/api/music/tracks','/api/music/charts/global-creators','/api/music/creator/ledger','/api/rooms/:roomId/status']) assert(music.includes(route),`${route} missing`);
const html=fs.readFileSync('public/index.html','utf8');
for(const feature of ['Open Music Hub','AMM Global Creator Chart','rulesAccepted','bathroom-break','Built for trust']) assert(html.includes(feature),`${feature} missing`);
const hub=fs.readFileSync('public/music-hub.html','utf8');
for(const feature of ['CREATOR-OWNED MUSIC','Music video URL','AR experience URL','VR concert URL','Mixed reality URL','AMM GLOBAL CREATOR CHART']) assert(hub.includes(feature),`${feature} missing`);
const rules=fs.readFileSync('public/community-rules.html','utf8');
for(const feature of ['Lawful adult substance content','BRB and Bathroom Break privacy','No fake activity','Protect minors']) assert(rules.includes(feature),`${feature} missing`);
console.log('TryAMM live, music, immersive media, creator chart and safety smoke checks passed');
