'use strict';
const assert=require('assert');
const fs=require('fs');
for(const file of ['server.js','public/index.html','public/app.js','public/styles.css','public/living-worlds.html','public/living-worlds-runtime.js','public/data/worlds.json','public/vocal-studio.html','public/vocal-studio.js','public/vocal-studio.css','public/studio-cloud-client.js','public/xr-vocal-studio.html','public/xr-vocal-studio.js','public/xr-vocal-studio.css','public/xr-studio-features.js','public/xr-cloud-controls.js']) assert(fs.existsSync(file),`${file} missing`);
const server=fs.readFileSync('server.js','utf8');
for(const route of ['/api/health','/api/auth/register','/api/rooms','/api/checkout','/api/admin/summary','/api/studio/projects','/api/studio/rooms']) assert(server.includes(route),`${route} missing`);
for(const contract of ['STUDIO_PROJECT_LIMIT','STUDIO_PROJECT_BYTES','ownerId === req.user.id','studio:join','xr_studio_state','track-position','room-anchor']) assert(server.includes(contract),`${contract} studio backend contract missing`);
const html=fs.readFileSync('public/index.html','utf8');
for(const feature of ['Go live','Virtual gifts','Ticketed livestreams','Built for trust']) assert(html.includes(feature),`${feature} missing`);
const registry=JSON.parse(fs.readFileSync('public/data/worlds.json','utf8')).worlds;
assert.strictEqual(registry.length,13,'13 worlds required');
const bySlug=new Map(registry.map(w=>[w.slug,w]));
for(const slug of ['faith-hub','lion-kingdom-gate']) assert.strictEqual(bySlug.get(slug)?.status,'live',`${slug} must be live`);
for(const world of registry.filter(w=>w.status==='live')){
  assert(world.spawn&&world.budget&&world.environment&&Array.isArray(world.portals),`${world.slug} runtime metadata missing`);
  for(const portal of world.portals) assert.strictEqual(bySlug.get(portal.toSlug)?.status,'live',`${portal.id} target is not enterable`);
}
const runtime=fs.readFileSync('public/living-worlds-runtime.js','utf8');
for(const feature of ['class WorldRegistry','class WorldRuntime','enforceBudget','disposeObject','async transition','renderer.info.memory','SoloAmbientPresence']) assert(runtime.includes(feature),`${feature} missing`);
const studioHtml=fs.readFileSync('public/vocal-studio.html','utf8');
for(const feature of ['Record microphone','Vocal Coach','Save on this device','Save to cloud','Export finished song','Export stems','studio-cloud-client.js']) assert(studioHtml.includes(feature),`${feature} studio control missing`);
const studio=fs.readFileSync('public/vocal-studio.js','utf8');
for(const feature of ['MediaRecorder','autoCorrelate','autoTuneTrack','createDynamicsCompressor','indexedDB.open','OfflineAudioContext','encodeWav','exportStems']) assert(studio.includes(feature),`${feature} studio engine missing`);
const cloud=fs.readFileSync('public/studio-cloud-client.js','utf8');
for(const feature of ['tryamm_token','Authorization','saveCurrentProject','listProjects','createStudioRoom','connectStudioRoom']) assert(cloud.includes(feature),`${feature} studio cloud client missing`);
const xrHtml=fs.readFileSync('public/xr-vocal-studio.html','utf8');
for(const feature of ['2D Studio','3D Spatial','Holographic','Enter VR','Enter AR / MR','Four-view pyramid','Parallax display','Connect positional audio','Add reverb zone','Add performer','Connect lip sync','Restore room placement','Save XR layout to cloud','Create collaboration room','Join collaboration room','XR quality']) assert(xrHtml.includes(feature),`${feature} XR control missing`);
const xr=fs.readFileSync('public/xr-vocal-studio.js','utf8');
for(const feature of ['immersive-vr','immersive-ar','setMode','renderPyramid','parallax','renderer.xr.enabled','hand-tracking','hit-test','XRStudioFeatures','prepareARPlacement','enableGestures']) assert(xr.includes(feature),`${feature} XR runtime missing`);
const xrFeatures=fs.readFileSync('public/xr-studio-features.js','utf8');
for(const feature of ['THREE.PositionalAudio','addReverbZone','createPerformer','connectLipSync','prepareARPlacement','placePersistentAnchor','BroadcastChannel','xr_studio_state','setQuality','monitorPerformance','dispose']) assert(xrFeatures.includes(feature),`${feature} advanced XR feature missing`);
const xrCloud=fs.readFileSync('public/xr-cloud-controls.js','utf8');
for(const feature of ['saveXRCloud','createStudioRoom','joinStudioRoom','studioPresence','tryammStudioSocket']) assert(xrCloud.includes(feature),`${feature} XR cloud control missing`);
console.log('TryAMM, Living Worlds, advanced Vocal Studio, cloud projects and authenticated XR collaboration smoke checks passed');
