export type WorldTravelMode='walk'|'bike'|'car'|'bus'|'metro'|'rail'|'high-speed-rail'|'plane'|'boat'|'ferry'|'river'|'holo-portal'
export interface LivingWorldRegion {id:string;name:string;group:string;languages:string[];hubs:string[];travel:WorldTravelMode[];sports:string[];gameplay:string[];teenTakeover:boolean;secretMissionSeeds:string[]}

export const atlanticAmericasExpansion:LivingWorldRegion[]=[
{id:'uk',name:'United Kingdom',group:'Europe',languages:['English','Welsh','Scottish Gaelic','Irish','translation-layer'],hubs:['London','Manchester','Birmingham','Liverpool','Edinburgh','Glasgow','Cardiff','Belfast'],travel:['walk','bike','car','bus','metro','rail','plane','ferry','holo-portal'],sports:['football/soccer','boxing','rugby','cricket','tennis','basketball','motorsport'],gameplay:['Premier-style original football universe','music and creator districts','film/AI-TV production','rail quests','business ownership','street racing circuits','historic exploration','sports academies'],teenTakeover:true,secretMissionSeeds:['Underground Frequency','Midnight Stadium','Highland Signal']},
{id:'canada',name:'Canada',group:'North America',languages:['English','French','Indigenous-language localization hooks','translation-layer'],hubs:['Toronto','Montreal','Vancouver','Ottawa','Calgary','Edmonton','Winnipeg','Halifax','Quebec City','Northern/Arctic hubs'],travel:['walk','bike','car','bus','metro','rail','plane','boat','ferry','holo-portal'],sports:['ice hockey','basketball','football','soccer','baseball','winter sports','track'],gameplay:['winter driving','hockey universe','creator/music districts','film production','mountain/coastal exploration','business missions','cross-border travel','northern expeditions'],teenTakeover:true,secretMissionSeeds:['Frozen Relay','Northern Lights Signal','Harbor Echo']},
{id:'mexico',name:'Mexico',group:'North America/Latin America',languages:['Spanish','Indigenous-language localization hooks','English fallback','translation-layer'],hubs:['Mexico City','Guadalajara','Monterrey','Tijuana','Cancun','Merida','Oaxaca','Puebla'],travel:['walk','bike','car','bus','metro','rail','plane','boat','ferry','holo-portal'],sports:['football/soccer','boxing','baseball','basketball','motorsport','wrestling-inspired fictional sport'],gameplay:['city/open-world missions','boxing careers','football tournaments','creator/music careers','food and marketplace businesses','coastal exploration','archaeology/history education','Volcano Racers routes'],teenTakeover:true,secretMissionSeeds:['Desert Frequency','Hidden Arena','Coastal Beacon']},
{id:'brazil',name:'Brazil',group:'South America',languages:['Portuguese','Indigenous-language localization hooks','translation-layer'],hubs:['Sao Paulo','Rio de Janeiro','Brasilia','Salvador','Recife','Belo Horizonte','Manaus','Porto Alegre'],travel:['walk','bike','car','bus','metro','rail','plane','boat','river','holo-portal'],sports:['football/soccer','basketball','volleyball','MMA','motorsport','surfing','track'],gameplay:['football universe','music/creator festivals','Amazon river exploration','motorsport','business districts','beach/coastal activities','rescue and conservation fiction'],teenTakeover:true,secretMissionSeeds:['Amazon Echo','Midnight Pitch','River Portal']},
{id:'argentina',name:'Argentina',group:'South America',languages:['Spanish','regional localization hooks','translation-layer'],hubs:['Buenos Aires','Cordoba','Rosario','Mendoza','Patagonia hubs'],travel:['walk','bike','car','bus','metro','rail','plane','boat','holo-portal'],sports:['football/soccer','basketball','rugby','tennis','motorsport','boxing'],gameplay:['football careers','city creator culture','mountain routes','Patagonia exploration','business missions','racing'],teenTakeover:true,secretMissionSeeds:['Patagonia Signal','Stadium After Dark']},
{id:'andean',name:'Andean Living Worlds',group:'South America',languages:['Spanish','Quechua hooks','Aymara hooks','translation-layer'],hubs:['Bogota','Medellin','Quito','Guayaquil','Lima','Cusco','La Paz','Santa Cruz','Santiago','Valparaiso'],travel:['walk','bike','car','bus','metro','rail','plane','boat','holo-portal'],sports:['football/soccer','cycling','boxing','basketball','surfing','motorsport','track'],gameplay:['mountain traversal','cycling competitions','football','creator/music routes','coastal gameplay','history/education','business networks','Volcano Racers mountain routes'],teenTakeover:true,secretMissionSeeds:['Andes Relay','Cloud City Frequency','Pacific Beacon']},
{id:'north-south-america',name:'Northern South America',group:'South America',languages:['Spanish','English','Dutch','regional localization hooks','translation-layer'],hubs:['Caracas','Georgetown','Paramaribo','Cayenne regional connector'],travel:['walk','bike','car','bus','plane','boat','river','holo-portal'],sports:['football/soccer','cricket','basketball','boxing','track'],gameplay:['Caribbean-mainland connections','river/rainforest routes','creator economy','sports circuit','business and marketplace missions'],teenTakeover:true,secretMissionSeeds:['Guiana Shield Signal','Orinoco Echo']},
{id:'southern-cone',name:'Southern Cone Network',group:'South America',languages:['Spanish','Portuguese','regional localization hooks','translation-layer'],hubs:['Santiago','Buenos Aires','Montevideo','Asuncion','southern Brazil connectors'],travel:['walk','bike','car','bus','rail','plane','boat','ferry','holo-portal'],sports:['football/soccer','basketball','rugby','motorsport','tennis'],gameplay:['continental championships','road trips','racing','creator tours','business routes','cross-border missions'],teenTakeover:true,secretMissionSeeds:['Southern Cross Signal','River Plate Mystery']}
]

export const southAmericaCountryCoverage=['Argentina','Bolivia','Brazil','Chile','Colombia','Ecuador','Guyana','Paraguay','Peru','Suriname','Uruguay','Venezuela'] as const
export const sharedWorldSystems=['Copy Smart NPC','Dynamic Mission Director','secret missions','persistent world save','cross-world avatar','sports careers','creator careers','business/property ownership','Teen Takeover','accessibility','all-language translation','multiplayer','OmniPlayer/AI TV','HoloGPT','Quantum Beat','Holographic Overlay','AR/VR/MR','Holo Portal','Unreal','Unity','Godot','Web/Holo'] as const

export const atlanticAmericasCampaigns=[
 {id:'atlantic-loop',name:'Atlantic Living Worlds Loop',route:['UK','Canada','USA','Mexico','Caribbean','northern South America','Brazil','Southern Cone','Andes','Caribbean','USA','UK']},
 {id:'americas-champions',name:'Champions of the Americas',systems:['football','basketball','boxing','baseball','hockey','MMA','motorsport','track','surfing']},
 {id:'pan-american-road',name:'Pan-American Living Road',systems:['cars','buses','rail where available','planes','boats','Holo Portals','regional secret missions']},
 {id:'world-creator-tour',name:'All American World Creator Tour',systems:['music','film','AI TV','live streaming','podcasts','fashion','food','marketplace','concerts']}
] as const
