'use strict';
const express=require('express'),http=require('http'),path=require('path'),fs=require('fs'),crypto=require('crypto');
const {Server}=require('socket.io');
const sessionSecurity=require('./lib/session-security');
const PORT=Number(process.env.PORT||10000),APP_URL=process.env.APP_URL||`http://localhost:${PORT}`;
const ADMIN_EMAIL=(process.env.ADMIN_EMAIL||'theammonmiverse@gmail.com').toLowerCase();
const DATA_FILE=process.env.DATA_FILE||path.join(__dirname,'data','store.json');
const PLATFORM_FEE_BPS=Number(process.env.PLATFORM_FEE_BPS||2500),PROD=process.env.NODE_ENV==='production';
const COOKIE_NAME=PROD?'__Host-tryamm_session':'tryamm_session';
const app=express(),server=http.createServer(app),io=new Server(server,{cors:{origin:true,credentials:true}});
app.disable('x-powered-by');app.use(express.json({limit:'2mb'}));app.use(express.urlencoded({extended:false}));
app.use((req,res,next)=>{res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('X-Frame-Options','SAMEORIGIN');res.setHeader('Referrer-Policy','strict-origin-when-cross-origin');res.setHeader('Permissions-Policy','camera=(self), microphone=(self), geolocation=()');next()});
app.use(express.static(path.join(__dirname,'public'),{extensions:['html']}));
function initialStore(){return{users:[],sessions:[],rooms:[],purchases:[],reports:[],events:[],tracks:[],streamEvents:[],creatorLedger:[],chartSnapshots:[]}}
function readStore(){try{fs.mkdirSync(path.dirname(DATA_FILE),{recursive:true});if(!fs.existsSync(DATA_FILE)){const fresh=initialStore();fs.writeFileSync(DATA_FILE,JSON.stringify(fresh,null,2));return fresh}return{...initialStore(),...JSON.parse(fs.readFileSync(DATA_FILE,'utf8'))}}catch(error){console.error('Store read failed:',error);return initialStore()}}
let store=readStore(),writeQueue=Promise.resolve();
function saveStore(){writeQueue=writeQueue.then(async()=>{const temp=`${DATA_FILE}.tmp`;await fs.promises.writeFile(temp,JSON.stringify(store,null,2));await fs.promises.rename(temp,DATA_FILE)}).catch(error=>console.error('Store write failed:',error));return writeQueue}
const id=prefix=>`${prefix}_${crypto.randomBytes(12).toString('hex')}`,clean=(value,max=120)=>String(value||'').trim().slice(0,max);
const publicUser=user=>user&&({id:user.id,email:user.email,displayName:user.displayName,role:user.role,isCreator:user.isCreator,balanceCents:user.balanceCents||0,createdAt:user.createdAt});
function passwordHash(password,salt=crypto.randomBytes(16).toString('hex')){return`${salt}:${crypto.scryptSync(password,salt,64).toString('hex')}`}
function passwordValid(password,stored){try{const[salt,hash]=stored.split(':');return crypto.timingSafeEqual(Buffer.from(hash,'hex'),Buffer.from(passwordHash(password,salt).split(':')[1],'hex'))}catch{return false}}
function bearer(req){const value=req.headers.authorization||'';return value.startsWith('Bearer ')?value.slice(7):''}
function parseCookies(header=''){const out={};for(const part of String(header).split(';')){const i=part.indexOf('=');if(i<1)continue;const k=part.slice(0,i).trim(),v=part.slice(i+1).trim();try{out[k]=decodeURIComponent(v)}catch{out[k]=v}}return out}
function cookieToken(req){return parseCookies(req.headers?.cookie||'')[COOKIE_NAME]||''}
function requestToken(req){return cookieToken(req)||bearer(req)}
function setSessionCookie(res,token,maxAgeMs=sessionSecurity.SESSION_TTL_MS){const attrs=[`${COOKIE_NAME}=${encodeURIComponent(token)}`,'Path=/','HttpOnly','SameSite=Strict',`Max-Age=${Math.max(0,Math.floor(maxAgeMs/1000))}`];if(PROD)attrs.push('Secure');res.append('Set-Cookie',attrs.join('; '))}
function clearSessionCookie(res){const attrs=[`${COOKIE_NAME}=`,'Path=/','HttpOnly','SameSite=Strict','Max-Age=0'];if(PROD)attrs.push('Secure');res.append('Set-Cookie',attrs.join('; '))}
function exposeBearer(token){return !PROD||String(process.env.ALLOW_LEGACY_BEARER_SESSION||'').toLowerCase()==='true'?token:undefined}
function sessionMeta(req){return sessionSecurity.metaFromRequest(req)}
function resolveSession(token,meta={}){store.sessions=sessionSecurity.prune(store.sessions||[]);const result=sessionSecurity.verify(store.sessions,token,meta);if(!result.ok)return result;const user=store.users.find(u=>u.id===result.session.userId);if(!user)return {ok:false,reason:'user_missing'};return {...result,user};}
function auth(req,res,next){const token=requestToken(req),result=resolveSession(token,sessionMeta(req));if(!result.ok){if(result.session&&!result.session.revokedAt&&['fingerprint_mismatch','idle_expired','expired'].includes(result.reason)){result.session.revokedAt=Date.now();result.session.revokedReason=`security_${result.reason}`;saveStore();}clearSessionCookie(res);return res.status(401).json({error:'Sign in required',code:'SESSION_INVALID',reason:result.reason});}req.user=result.user;req.session=result.session;req.sessionToken=token;next()}
function admin(req,res,next){if(req.user.role!=='admin')return res.status(403).json({error:'Admin access required'});next()}
function createSession(userId,req){store.sessions=sessionSecurity.prune(store.sessions||[]);const created=sessionSecurity.create(userId,sessionMeta(req));store.sessions.push(created.record);return created}
app.get('/api/health',(_req,res)=>res.json({ok:true,service:'TryAMM Creator Live + Music',version:'5.5.1',users:store.users.length,rooms:store.rooms.filter(r=>r.status==='live').length,tracks:store.tracks.length,stripeConfigured:Boolean(process.env.STRIPE_SECRET_KEY),secureCookieSessions:PROD,time:new Date().toISOString()}));
app.post('/api/auth/register',async(req,res)=>{const email=clean(req.body.email,200).toLowerCase(),displayName=clean(req.body.displayName,60),password=String(req.body.password||'');if(!/^\S+@\S+\.\S+$/.test(email))return res.status(400).json({error:'Enter a valid email'});if(displayName.length<2)return res.status(400).json({error:'Display name is required'});if(password.length<10)return res.status(400).json({error:'Password must be at least 10 characters'});if(store.users.some(u=>u.email===email))return res.status(409).json({error:'Account already exists'});const user={id:id('usr'),email,displayName,passwordHash:passwordHash(password),role:email===ADMIN_EMAIL?'admin':'member',isCreator:false,balanceCents:0,createdAt:new Date().toISOString()};store.users.push(user);let created;try{created=createSession(user.id,req)}catch(e){return res.status(503).json({error:'Secure session service is not configured',code:e.code||'SESSION_CONFIG_ERROR'})}setSessionCookie(res,created.token);await saveStore();const token=exposeBearer(created.token);res.status(201).json({...(token?{token}:{}),user:publicUser(user),session:{id:created.record.id,expiresAt:created.record.expiresAt,idleExpiresAt:created.record.idleExpiresAt,transport:PROD?'httpOnlyCookie':'cookie+developmentBearer'}})});
app.post('/api/auth/login',async(req,res)=>{const email=clean(req.body.email,200).toLowerCase(),user=store.users.find(u=>u.email===email);if(!user||!passwordValid(String(req.body.password||''),user.passwordHash))return res.status(401).json({error:'Invalid email or password'});let created;try{created=createSession(user.id,req)}catch(e){return res.status(503).json({error:'Secure session service is not configured',code:e.code||'SESSION_CONFIG_ERROR'})}setSessionCookie(res,created.token);await saveStore();const token=exposeBearer(created.token);res.json({...(token?{token}:{}),user:publicUser(user),session:{id:created.record.id,expiresAt:created.record.expiresAt,idleExpiresAt:created.record.idleExpiresAt,transport:PROD?'httpOnlyCookie':'cookie+developmentBearer'}})});
app.get('/api/me',auth,(req,res)=>res.json({user:publicUser(req.user),session:{id:req.session.id,createdAt:req.session.createdAt,lastSeenAt:req.session.lastSeenAt,expiresAt:req.session.expiresAt,idleExpiresAt:req.session.idleExpiresAt}}));
app.get('/api/auth/sessions',auth,(req,res)=>res.json({sessions:(store.sessions||[]).filter(s=>s.userId===req.user.id&&!s.revokedAt).map(s=>({id:s.id,createdAt:s.createdAt,lastSeenAt:s.lastSeenAt,expiresAt:s.expiresAt,idleExpiresAt:s.idleExpiresAt,current:s.id===req.session.id}))}));
app.post('/api/auth/logout',auth,async(req,res)=>{sessionSecurity.revoke(store.sessions,req.sessionToken,'logout');clearSessionCookie(res);await saveStore();res.json({ok:true})});
app.post('/api/auth/logout-all',auth,async(req,res)=>{const revoked=sessionSecurity.revokeUser(store.sessions,req.user.id,'logout_all');clearSessionCookie(res);await saveStore();res.json({ok:true,revoked})});
app.post('/api/auth/sessions/:sessionId/revoke',auth,async(req,res)=>{const target=(store.sessions||[]).find(s=>s.id===req.params.sessionId&&s.userId===req.user.id);if(!target)return res.status(404).json({error:'Session not found'});target.revokedAt=Date.now();target.revokedReason='user_revoked';if(target.id===req.session.id)clearSessionCookie(res);await saveStore();res.json({ok:true})});
app.post('/api/creator/apply',auth,async(req,res)=>{req.user.isCreator=true;req.user.creatorBio=clean(req.body.bio,500);req.user.creatorCategory=clean(req.body.category,80)||'Creator';req.user.creatorApprovedAt=new Date().toISOString();await saveStore();res.json({user:publicUser(req.user),message:'Creator tools activated'})});
app.get('/api/rooms',(_req,res)=>res.json({rooms:store.rooms.filter(r=>r.status==='live').map(r=>({id:r.id,title:r.title,category:r.category,hostName:r.hostName,hostId:r.hostId,hostStatus:r.hostStatus||'live',breakEndsAt:r.breakEndsAt||null,viewerCount:io.sockets.adapter.rooms.get(`room:${r.id}`)?.size||0,ticketPriceCents:r.ticketPriceCents,startedAt:r.startedAt}))}));
app.post('/api/rooms',auth,async(req,res)=>{if(!req.user.isCreator&&req.user.role!=='admin')return res.status(403).json({error:'Activate creator tools first'});if(!req.body.rulesAccepted)return res.status(400).json({error:'Accept the Community Rules before going live'});const room={id:id('room'),hostId:req.user.id,hostName:req.user.displayName,title:clean(req.body.title,100)||`${req.user.displayName} Live`,category:clean(req.body.category,60)||'Community',ticketPriceCents:Math.max(0,Math.min(100000,Number(req.body.ticketPriceCents||0))),audience:clean(req.body.audience,30)||'general',status:'live',hostStatus:'live',breakEndsAt:null,startedAt:new Date().toISOString(),endedAt:null,hearts:0,giftsCents:0};store.rooms.push(room);await saveStore();io.emit('rooms:changed');res.status(201).json({room})});
app.post('/api/rooms/:roomId/end',auth,async(req,res)=>{const room=store.rooms.find(r=>r.id===req.params.roomId);if(!room)return res.status(404).json({error:'Room not found'});if(room.hostId!==req.user.id&&req.user.role!=='admin')return res.status(403).json({error:'Not permitted'});room.status='ended';room.endedAt=new Date().toISOString();await saveStore();io.to(`room:${room.id}`).emit('room:ended');io.emit('rooms:changed');res.json({ok:true})});
app.post('/api/rooms/:roomId/heart',auth,async(req,res)=>{const room=store.rooms.find(r=>r.id===req.params.roomId&&r.status==='live');if(!room)return res.status(404).json({error:'Live room not found'});room.hearts+=1;await saveStore();io.to(`room:${room.id}`).emit('heart',room.hearts);res.json({hearts:room.hearts})});
const GIFT_CATALOG={applause:99,rose:199,crown:499,lion:999,kingdom:2499};app.get('/api/gifts',(_req,res)=>res.json({gifts:GIFT_CATALOG}));
app.post('/api/rooms/:roomId/gifts',auth,async(req,res)=>{const room=store.rooms.find(r=>r.id===req.params.roomId&&r.status==='live');if(!room)return res.status(404).json({error:'Live room not found'});const gift=clean(req.body.gift,30).toLowerCase(),amountCents=GIFT_CATALOG[gift];if(!amountCents)return res.status(400).json({error:'Unknown gift'});const host=store.users.find(u=>u.id===room.hostId),platformFeeCents=Math.round(amountCents*PLATFORM_FEE_BPS/10000),creatorCents=amountCents-platformFeeCents;if(host)host.balanceCents=(host.balanceCents||0)+creatorCents;room.giftsCents+=amountCents;const purchase={id:id('pay'),kind:'gift',status:'recorded',buyerId:req.user.id,creatorId:room.hostId,roomId:room.id,item:gift,amountCents,platformFeeCents,creatorCents,createdAt:new Date().toISOString()};store.purchases.push(purchase);await saveStore();io.to(`room:${room.id}`).emit('gift',{gift,from:req.user.displayName,amountCents,total:room.giftsCents});res.status(201).json({purchase})});
app.post('/api/checkout',auth,async(req,res)=>{if(!process.env.STRIPE_SECRET_KEY)return res.status(503).json({error:'Stripe is not configured yet',code:'STRIPE_NOT_CONFIGURED',required:['STRIPE_SECRET_KEY','STRIPE_WEBHOOK_SECRET','APP_URL']});const Stripe=require('stripe'),stripe=new Stripe(process.env.STRIPE_SECRET_KEY),room=store.rooms.find(r=>r.id===clean(req.body.roomId,80));if(!room)return res.status(404).json({error:'Room not found'});const amount=room.ticketPriceCents||1000,checkout=await stripe.checkout.sessions.create({mode:'payment',customer_email:req.user.email,line_items:[{quantity:1,price_data:{currency:'usd',unit_amount:amount,product_data:{name:`TryAMM: ${room.title}`}}}],metadata:{roomId:room.id,buyerId:req.user.id,creatorId:room.hostId},success_url:`${APP_URL}/?payment=success`,cancel_url:`${APP_URL}/?payment=cancelled`});res.json({url:checkout.url})});
app.get('/api/admin/summary',auth,admin,(_req,res)=>{const gross=store.purchases.reduce((s,p)=>s+p.amountCents,0),fees=store.purchases.reduce((s,p)=>s+p.platformFeeCents,0);res.json({users:store.users.length,creators:store.users.filter(u=>u.isCreator).length,liveRooms:store.rooms.filter(r=>r.status==='live').length,tracks:store.tracks.length,purchases:store.purchases.length,grossCents:gross,platformRevenueCents:fees,reports:store.reports.filter(r=>r.status==='open').length})});
app.post('/api/reports',auth,async(req,res)=>{const report={id:id('rpt'),reporterId:req.user.id,roomId:clean(req.body.roomId,80),reason:clean(req.body.reason,300),status:'open',createdAt:new Date().toISOString()};if(!report.reason)return res.status(400).json({error:'Reason is required'});store.reports.push(report);await saveStore();res.status(201).json({report})});
require('./music-api')({app,auth,clean,id,getStore:()=>store,saveStore,io});
io.use((socket,next)=>{const cookies=parseCookies(socket.request.headers.cookie||''),token=cookies[COOKIE_NAME]||socket.handshake.auth?.token||'';const meta={userAgent:socket.request.headers['user-agent']||'',acceptLanguage:socket.request.headers['accept-language']||'',deviceId:socket.handshake.auth?.deviceId||''};const result=resolveSession(token,meta);if(!result.ok){if(result.session&&!result.session.revokedAt&&result.reason==='fingerprint_mismatch'){result.session.revokedAt=Date.now();result.session.revokedReason='security_socket_fingerprint_mismatch';saveStore();}return next(new Error('unauthorized'));}socket.user=result.user;socket.sessionId=result.session.id;next()});
io.on('connection',socket=>{socket.on('room:join',({roomId})=>{const room=store.rooms.find(r=>r.id===roomId&&r.status==='live');if(!room)return socket.emit('error:message','Room is unavailable');socket.join(`room:${roomId}`);socket.data.roomId=roomId;socket.to(`room:${roomId}`).emit('peer:joined',{socketId:socket.id,name:socket.user.displayName});io.to(`room:${roomId}`).emit('viewer:count',io.sockets.adapter.rooms.get(`room:${roomId}`)?.size||0)});socket.on('chat',({roomId,message})=>{const text=clean(message,500);if(text)io.to(`room:${roomId}`).emit('chat',{id:id('msg'),from:socket.user.displayName,text,at:Date.now()})});socket.on('webrtc:offer',({to,offer})=>io.to(to).emit('webrtc:offer',{from:socket.id,offer}));socket.on('webrtc:answer',({to,answer})=>io.to(to).emit('webrtc:answer',{from:socket.id,answer}));socket.on('webrtc:ice',({to,candidate})=>io.to(to).emit('webrtc:ice',{from:socket.id,candidate}));socket.on('disconnect',()=>{const roomId=socket.data.roomId;if(roomId)io.to(`room:${roomId}`).emit('viewer:count',io.sockets.adapter.rooms.get(`room:${roomId}`)?.size||0)})});
app.use('/api',(_req,res)=>res.status(404).json({error:'API route not found'}));app.get('*',(_req,res)=>res.sendFile(path.join(__dirname,'public','index.html')));app.use((error,_req,res,_next)=>{console.error(error);res.status(error.status||500).json({error:error.message||'Server error'})});server.listen(PORT,()=>console.log(`TryAMM running on port ${PORT}`));
