export type AgentStatus='idle'|'queued'|'working'|'review'|'blocked'|'done';
export type CafeAgent={id:string;name:string;role:string;workstream:string;status:AgentStatus;capabilities:string[];lastTask?:string};
export type CafeTask={id:string;title:string;workstream:string;priority:'critical'|'high'|'normal';status:AgentStatus;agentId?:string;createdAt:string};
const KEY='tryamm_ai_cafe_v1';let installed=false;
const AGENTS:CafeAgent[]=[
{id:'streetverse-director',name:'StreetVerse Director',role:'living-world/gameplay',workstream:'streetverse',status:'idle',capabilities:['missions','cities','NPC plans','multiplayer plans','progression','performance']},
{id:'world-builder',name:'World Builder',role:'3D/world systems',workstream:'streetverse',status:'idle',capabilities:['district packs','mission markers','vehicles','environment briefs','asset manifests']},
{id:'npc-director',name:'NPC Director',role:'NPC/character systems',workstream:'streetverse',status:'idle',capabilities:['NPC roles','dialogue briefs','squad behaviors','artist missions']},
{id:'creator-producer',name:'Creator Producer',role:'creator/media',workstream:'creator',status:'idle',capabilities:['reels','broadcast','highlights','publishing checklists']},
{id:'harmony-producer',name:'Harmony Producer',role:'music intelligence',workstream:'music',status:'idle',capabilities:['music projects','rights checks','tour missions','collaboration plans']},
{id:'business-builder',name:'Business Builder',role:'website/business launch',workstream:'business',status:'idle',capabilities:['site briefs','launch checklist','commerce','ownership/export']},
{id:'sourcing-agent',name:'Quantum Sourcing Agent',role:'supplier/procurement',workstream:'commerce',status:'idle',capabilities:['RFQ briefs','supplier scoring','MOQ','provenance']},
{id:'guardian-dispatch',name:'Guardian Dispatch',role:'mission operations',workstream:'guardian',status:'idle',capabilities:['dispatch','squad loadout','extraction','after-action']},
{id:'accessibility-agent',name:'Access Guardian',role:'accessibility QA',workstream:'quality',status:'idle',capabilities:['keyboard','screen reader','captions','motor access','language']},
{id:'release-guardian',name:'Release Guardian',role:'release/reliability',workstream:'release',status:'idle',capabilities:['health gates','crash recovery','rollback','smoke-test plans']}
];
function load(){try{return JSON.parse(localStorage.getItem(KEY)||'null')||{agents:AGENTS,tasks:[]}}catch{return{agents:AGENTS,tasks:[]}}}
function save(state:any){try{localStorage.setItem(KEY,JSON.stringify(state))}catch{};window.dispatchEvent(new CustomEvent('tryamm:ai-cafe-state',{detail:{schema:'tryamm.ai.cafe.v1',...state,policy:{autonomy:'Agents coordinate plans and platform events; privileged deploy/payment/legal actions remain gated.',parallelism:'Independent workstreams may run concurrently; release changes converge through Release Guardian.'}}}))}
function pickAgent(state:any,workstream:string){return state.agents.find((a:CafeAgent)=>a.workstream===workstream)||state.agents.find((a:CafeAgent)=>a.status==='idle')}
export function installAICafeMultiAgentRuntime(){if(installed||typeof window==='undefined')return;installed=true;let state=load();queueMicrotask(()=>save(state));window.addEventListener('tryamm:ai-cafe-task',(e:Event)=>{const d=(e as CustomEvent<any>).detail||{};const agent=pickAgent(state,String(d.workstream||'release'));const task:CafeTask={id:`cafe-${Date.now()}`,title:String(d.title||'Platform task'),workstream:String(d.workstream||agent?.workstream||'release'),priority:d.priority||'normal',status:'queued',agentId:agent?.id,createdAt:new Date().toISOString()};state={...state,tasks:[task,...state.tasks].slice(0,100),agents:state.agents.map((a:CafeAgent)=>a.id===agent?.id?{...a,status:'working',lastTask:task.title}:a)};save(state);window.dispatchEvent(new CustomEvent('tryamm:ai-cafe-assigned',{detail:{task,agent}}))});window.addEventListener('tryamm:ai-cafe-task-status',(e:Event)=>{const d=(e as CustomEvent<any>).detail||{};state={...state,tasks:state.tasks.map((t:CafeTask)=>t.id===d.id?{...t,status:d.status||t.status}:t),agents:state.agents.map((a:CafeAgent)=>a.id===d.agentId?{...a,status:d.status==='done'?'idle':d.status||a.status}:a)};save(state)});window.addEventListener('tryamm:ai-cafe-sprint',()=>{const defaults=[['streetverse','Deepen playable city missions'],['streetverse','NPC squad and world interaction pass'],['creator','Verify mission-to-Reel pipeline'],['business','Advance AI website generation/export'],['music','Advance Stubbs Harmony AI studio flow'],['quality','Accessibility and multilingual regression'],['release','Run release health and rollback gates']];defaults.forEach(([workstream,title])=>window.dispatchEvent(new CustomEvent('tryamm:ai-cafe-task',{detail:{workstream,title,priority:workstream==='release'?'critical':'high'}})))})}
