export type BennyOverlayMode='guide'|'mission'|'scan'|'creator'|'accessibility'|'construct'
export type BennyOverlayState={enabled:boolean;mode:BennyOverlayMode;opacity:number;scanlines:boolean;depthCue:boolean;worldAnchored:boolean;physicalProjection:false}

let state:BennyOverlayState={enabled:true,mode:'guide',opacity:.9,scanlines:true,depthCue:true,worldAnchored:true,physicalProjection:false}
const emit=(name:string,detail:unknown)=>{if(typeof window!=='undefined')window.dispatchEvent(new CustomEvent(name,{detail}))}
export function getBennyConstructOverlay(){return {...state}}
export function setBennyConstructOverlay(patch:Partial<BennyOverlayState>){state={...state,...patch,physicalProjection:false};emit('tryamm:benny:construct-overlay-state',{...state,softwareOverlay:true,requiresCompatibleDisplayForPhysicalHologram:true,createdAt:new Date().toISOString()});return getBennyConstructOverlay()}
export function pulseBennyConstructOverlay(context:string){emit('tryamm:benny:construct-pulse',{context,state:getBennyConstructOverlay(),layers:['volumetric-rim','depth-grid','scanline-shell','world-anchor','caption-panel','mission-pointer'],createdAt:new Date().toISOString()})}
let installed=false
export function installBennyConstructHolographicOverlay(){if(installed||typeof window==='undefined')return;installed=true;window.addEventListener('tryamm:benny:overlay-request',(event:Event)=>{const detail=(event as CustomEvent<Record<string,unknown>>).detail||{};setBennyConstructOverlay({enabled:true,mode:String(detail.context||'').includes('creator')?'creator':'construct'});pulseBennyConstructOverlay(String(detail.context||'streetverse'))});window.addEventListener('tryamm:mission:discovered',()=>{setBennyConstructOverlay({mode:'mission'});pulseBennyConstructOverlay('mission')});window.addEventListener('tryamm:media-studio-open',()=>setBennyConstructOverlay({mode:'creator'}));emit('tryamm:benny:construct-overlay-ready',{software:true,physicalProjection:false,layers:['volumetric-rim','depth-grid','scanline-shell','world-anchor','caption-panel','mission-pointer'],accessibility:['captions','high-contrast','reduced-motion-compatible','audio-description-hooks']})}
