export type BusinessTemplateId='yahavah-grocery'|'all-american-store'|'black-hair-wigs'|'phone-tote'|'multi-franchise';
export type BusinessTemplate={id:BusinessTemplateId;name:string;category:string;defaultProducts:string[];services:string[];channels:string[];cityReady:boolean;franchiseReady:boolean;notes:string[]};
export type BusinessLocation={id:string;templateId:BusinessTemplateId;name:string;city:string;country:string;status:'planning'|'launching'|'open';websiteId?:string;streetverseLocationId?:string;manager?:string};
const KEY='tryamm_business_templates_v1';let installed=false;
export const BUSINESS_TEMPLATES:BusinessTemplate[]=[
{id:'yahavah-grocery',name:'Yahavah Grocery',category:'grocery',defaultProducts:['fresh produce','pantry staples','household essentials','prepared foods','local vendor products'],services:['pickup','local delivery','subscriptions','community food boxes'],channels:['website','marketplace','StreetVerse','creator LIVE shopping'],cityReady:true,franchiseReady:true,notes:['food safety and local retail requirements apply','support local/verified vendors','inventory freshness tracking recommended']},
{id:'all-american-store',name:'All American Store',category:'general retail',defaultProducts:['apparel','home goods','electronics accessories','creator merchandise','local brands'],services:['pickup','shipping','gift registry','creator storefronts'],channels:['website','marketplace','StreetVerse','broadcast shopping'],cityReady:true,franchiseReady:true,notes:['seller verification','returns policy','brand/IP checks']},
{id:'black-hair-wigs',name:'African American Wigs & Hair Supply',category:'beauty/hair retail',defaultProducts:['wigs','bundles','braiding hair','extensions','bonnets','combs/brushes','hair care','barber/beauty accessories'],services:['virtual try-on','stylist booking','creator tutorials','beauty LIVE shopping'],channels:['website','marketplace','StreetVerse salon/beauty district','creator'],cityReady:true,franchiseReady:true,notes:['product authenticity','ingredient/label checks where applicable','licensed professional services kept separate from retail']},
{id:'phone-tote',name:'Phone & Tote Business',category:'accessories',defaultProducts:['phone cases','chargers','cables','screen protectors','tote bags','custom printed totes','creator-branded accessories'],services:['customization','bundles','creator drops','pickup/shipping'],channels:['website','marketplace','StreetVerse kiosk','creator'],cityReady:true,franchiseReady:true,notes:['device compatibility catalog','print/design rights verification','supplier QC']},
{id:'multi-franchise',name:'TRYAMM Multi-Location Franchise Builder',category:'franchise/multi-location',defaultProducts:[],services:['location launch','operator onboarding','training','brand standards','inventory templates','analytics','local marketing'],channels:['website','StreetVerse','Middleverse workforce','OmniBI'],cityReady:true,franchiseReady:true,notes:['real-world franchise disclosure/registration laws vary by jurisdiction','in-game franchise status is not a legal franchise filing','local taxes/licenses/leases remain external requirements']}
];
function load(){try{return JSON.parse(localStorage.getItem(KEY)||'null')||{locations:[]}}catch{return{locations:[]}}}
function save(state:any){try{localStorage.setItem(KEY,JSON.stringify(state))}catch{};window.dispatchEvent(new CustomEvent('tryamm:business-template-state',{detail:{schema:'tryamm.business.templates.v1',templates:BUSINESS_TEMPLATES,...state}}))}
function template(id:BusinessTemplateId){return BUSINESS_TEMPLATES.find(t=>t.id===id)!}
export function installBusinessTemplateFranchiseRuntime(){if(installed||typeof window==='undefined')return;installed=true;let state=load();queueMicrotask(()=>save(state));window.addEventListener('tryamm:business-template-launch',(e:Event)=>{const d=(e as CustomEvent<any>).detail||{},t=template(d.templateId);if(!t)return;const loc:BusinessLocation={id:`loc-${Date.now()}`,templateId:t.id,name:String(d.name||t.name),city:String(d.city||'Chicago'),country:String(d.country||'United States'),status:'planning'};state={...state,locations:[loc,...state.locations]};save(state);window.dispatchEvent(new CustomEvent('tryamm:ai-site-create',{detail:{name:loc.name,industry:t.category,city:loc.city}}));window.dispatchEvent(new CustomEvent('tryamm:quantum-sourcing-request',{detail:{business:loc.name,category:t.category,products:t.defaultProducts}}));window.dispatchEvent(new CustomEvent('tryamm:ai-cafe-task',{detail:{workstream:'business',title:`Launch ${loc.name} in ${loc.city}`,priority:'high'}}));window.dispatchEvent(new CustomEvent('tryamm:regional-opportunities-request',{detail:{city:loc.city,businessTemplate:t.id}}))});window.addEventListener('tryamm:business-location-open',(e:Event)=>{const d=(e as CustomEvent<any>).detail||{};state={...state,locations:state.locations.map((l:BusinessLocation)=>l.id===d.id?{...l,status:'open',websiteId:d.websiteId||l.websiteId,streetverseLocationId:d.streetverseLocationId||l.streetverseLocationId,manager:d.manager||l.manager}:l)};save(state);window.dispatchEvent(new CustomEvent('tryamm:creator-commerce-launch',{detail:{locationId:d.id}}))});window.addEventListener('tryamm:business-franchise-expand',(e:Event)=>{const d=(e as CustomEvent<any>).detail||{},source=state.locations.find((l:BusinessLocation)=>l.id===d.sourceLocationId);if(!source)return;const copy:BusinessLocation={...source,id:`loc-${Date.now()}`,city:String(d.city||source.city),country:String(d.country||source.country),status:'planning',websiteId:undefined,streetverseLocationId:undefined,manager:undefined};state={...state,locations:[copy,...state.locations]};save(state);window.dispatchEvent(new CustomEvent('tryamm:ai-cafe-task',{detail:{workstream:'business',title:`Franchise ${copy.name} into ${copy.city}`,priority:'high'}}));window.dispatchEvent(new CustomEvent('tryamm:middleverse-remote-work-request',{detail:{business:copy.name,city:copy.city,needs:['manager','customer-support','creator','commerce']}}))})}
