export type WarpMode='wormhole'|'warp'
export type WarpTarget={id:string;label:string;kind:'chrono-checkpoint'|'space-destination'|'streetverse-portal';metadata?:Record<string,unknown>}
export type WarpState={active:boolean;mode:WarpMode;target?:WarpTarget;progress:number;startedAt?:string;physicalFtl:false}
const KEY='tryamm_chrono_warp_v1';let installed=false
const now=()=>new Date().toISOString()
function write(s:WarpState){localStorage.setItem(KEY,JSON.stringify(s));window.dispatchEvent(new CustomEvent('tryamm:chrono-warp-state',{detail:s}));return s}
function read():WarpState{try{return JSON.parse(localStorage.getItem(KEY)||'null')||{active:false,mode:'wormhole',progress:0,physicalFtl:false}}catch{return{active:false,mode:'wormhole',progress:0,physicalFtl:false}}}
function speak(title:string,message:string){window.dispatchEvent(new CustomEvent('tryamm:benny-utterance',{detail:{mode:'guide',title,message}}));window.dispatchEvent(new CustomEvent('tryamm:construct:context',{detail:{agent:'Chronicle',title,message,actions:['warp-status','destination-context']}}))}
export function startChronoWarp(mode:WarpMode,target:WarpTarget){const s:WarpState={active:true,mode,target,progress:0,startedAt:now(),physicalFtl:false};write(s);window.dispatchEvent(new CustomEvent('tryamm:chrono-warp-visual',{detail:{...s,effect:mode==='wormhole'?'woodworm-tunnel':'warp-streaks',layers:['radial-tunnel','star-streaks','depth-rings','destination-lock']}}));speak(mode==='wormhole'?'WORMHOLE LOCKED':'WARP DRIVE SIMULATION',`${target.label} locked. This is a simulated travel effect, not physical faster-than-light travel.`);let p=0;const timer=window.setInterval(()=>{p=Math.min(100,p+10);const n={...read(),active:p<100,progress:p,physicalFtl:false as const};write(n);if(p>=100){window.clearInterval(timer);window.dispatchEvent(new CustomEvent('tryamm:chrono-warp-arrived',{detail:{mode,target}}));if(target.kind==='chrono-checkpoint')window.dispatchEvent(new CustomEvent('tryamm:chrono-next-checkpoint'));if(target.kind==='streetverse-portal')window.dispatchEvent(new CustomEvent('tryamm:chrono-return-request'));speak('DESTINATION REACHED',`${target.label} reached in simulation.`)}},80);return s}
export function installChronoWarpRuntime(){if(installed||typeof window==='undefined')return;installed=true;window.addEventListener('tryamm:chrono-warp-request',(e:Event)=>{const d=(e as CustomEvent<{mode?:WarpMode;target?:WarpTarget}>).detail||{};if(d.target)startChronoWarp(d.mode||'wormhole',d.target)});window.addEventListener('tryamm:chrono-wormhole-next',()=>startChronoWarp('wormhole',{id:'next-checkpoint',label:'Next Chrono Checkpoint',kind:'chrono-checkpoint'}));window.addEventListener('tryamm:chrono-warp-home',()=>startChronoWarp('warp',{id:'streetverse-return',label:'StreetVerse Return Portal',kind:'streetverse-portal'}));window.dispatchEvent(new CustomEvent('tryamm:chrono-warp-ready',{detail:{wormhole:true,warpSpeed:true,spaceVerseTargets:true,chronoTargets:true,physicalFtl:false}}))}
