export type TrainingTrack='marketplace-associate'|'warehouse-picker'|'inventory-specialist'|'cold-chain-associate'|'delivery-operator'|'live-commerce-host'|'franchise-manager';
export type TrainingRecord={track:TrainingTrack;level:number;modules:{id:string;title:string;done:boolean}[];status:'not-started'|'training'|'assessment'|'completed';gameCertificate?:string;completedAt?:string};
const KEY='tryamm_commerce_job_training_v1';let installed=false;
const MODULES:Record<TrainingTrack,string[]>={
 'marketplace-associate':['Customer service basics','Store inventory navigation','Margin-floor awareness','Returns and escalation'],
 'warehouse-picker':['SKU/lot verification','Pick/pack accuracy','Available-to-promise checks','Order handoff'],
 'inventory-specialist':['Cycle counts','Reorder points','Supplier timestamps','Shrink/damage reporting'],
 'cold-chain-associate':['Storage requirements','Temperature/lot logs','Spoilage prevention','Cold-chain handoff'],
 'delivery-operator':['Pickup verification','Accessible route planning','Proof of delivery','Issue escalation'],
 'live-commerce-host':['Product verification','Rights-cleared presentation','Live moderation','Order-to-fulfillment handoff'],
 'franchise-manager':['Site launch checklist','Local hiring/training','Warehouse rail setup','Store KPI review']
};
function initial(track:TrainingTrack):TrainingRecord{return{track,level:1,status:'training',modules:MODULES[track].map((title,i)=>({id:`m${i+1}`,title,done:false}))}}
function load():Record<string,TrainingRecord>{try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch{return{}}}
function save(state:Record<string,TrainingRecord>){try{localStorage.setItem(KEY,JSON.stringify(state))}catch{};window.dispatchEvent(new CustomEvent('tryamm:commerce-training-state',{detail:{schema:'tryamm.commerce.training.v1',records:state,disclaimer:'TRYAMM certificates are in-game/platform training records and are not real-world occupational licenses or government certifications.'}}))}
export function installCommerceJobTrainingRuntime(){if(installed||typeof window==='undefined')return;installed=true;let state=load();queueMicrotask(()=>save(state));window.addEventListener('tryamm:commerce-training-start',(e:Event)=>{const track=(e as CustomEvent<any>).detail?.track as TrainingTrack;if(!MODULES[track])return;state={...state,[track]:state[track]||initial(track)};save(state)});window.addEventListener('tryamm:commerce-training-module-complete',(e:Event)=>{const d=(e as CustomEvent<any>).detail||{},track=d.track as TrainingTrack,rec=state[track];if(!rec)return;const modules=rec.modules.map(m=>m.id===d.moduleId?{...m,done:true}:m);state={...state,[track]:{...rec,modules,status:modules.every(m=>m.done)?'assessment':'training'}};save(state)});window.addEventListener('tryamm:commerce-training-assessment-pass',(e:Event)=>{const track=(e as CustomEvent<any>).detail?.track as TrainingTrack,rec=state[track];if(!rec||!rec.modules.every(m=>m.done))return;const gameCertificate=`TRYAMM-${track.toUpperCase()}-L${rec.level}`;state={...state,[track]:{...rec,status:'completed',gameCertificate,completedAt:new Date().toISOString()}};save(state);window.dispatchEvent(new CustomEvent('tryamm:middleverse-career-credit',{detail:{branchId:track,credits:1}}));window.dispatchEvent(new CustomEvent('tryamm:streetverse-reward',{detail:{xp:250,reputation:8}}))});window.addEventListener('tryamm:commerce-job-eligibility-request',(e:Event)=>{const d=(e as CustomEvent<any>).detail||{},track=d.track as TrainingTrack,rec=state[track];window.dispatchEvent(new CustomEvent('tryamm:commerce-job-eligibility-result',{detail:{track,eligible:rec?.status==='completed',record:rec||null}}))})}
