export type TravelMode='airport'|'rail'|'road'|'ferry'|'port'|'border'
export type WorldPack={continent:string;country:string;region?:string;city:string;languages:string[];travelModes:TravelMode[];architecture:string[];npcCulture:string[];jobTags:string[];businessTags:string[];faithCommunityTags:string[];guardianTags:string[]}
const KEY='tryamm_global_travel_v1';let installed=false
const PACKS:Record<string,Partial<WorldPack>>={
 'New York':{continent:'North America',country:'United States',languages:['en','es'],travelModes:['airport','rail','road','ferry'],architecture:['vertical skyline','brownstones','bridges','parks'],npcCulture:['hip-hop','theater','fashion','diaspora food'],jobTags:['media','finance','creator','hospitality'],businessTags:['fashion','food','media','retail'],faithCommunityTags:['community service','youth mentorship'],guardianTags:['transit safety','event support']},
 'Hollywood':{continent:'North America',country:'United States',region:'California',languages:['en','es'],travelModes:['airport','road','rail'],architecture:['studios','boulevards','hills','sound stages'],npcCulture:['film','television','music','creator economy'],jobTags:['production','broadcast','editing','creator'],businessTags:['studio','fashion','media','tourism'],faithCommunityTags:['artist wellness','community outreach'],guardianTags:['production safety','event safety']},
 'San Diego':{continent:'North America',country:'United States',region:'California',languages:['en','es'],travelModes:['airport','road','rail','port','border'],architecture:['coastal districts','marina','historic neighborhoods'],npcCulture:['coastal','cross-border','sports','music'],jobTags:['tourism','tech','maritime','creator'],businessTags:['food','tourism','trade','retail'],faithCommunityTags:['family support','community service'],guardianTags:['safe passage','cross-border resource support']},
 'Mexico City':{continent:'North America',country:'Mexico',languages:['es','en'],travelModes:['airport','road','rail'],architecture:['historic center','modern towers','markets','parks'],npcCulture:['art','music','food','football'],jobTags:['media','tourism','commerce','creator'],businessTags:['food','art','retail','trade'],faithCommunityTags:['family support','community service'],guardianTags:['transit safety','family routes']},
 'Tijuana':{continent:'North America',country:'Mexico',languages:['es','en'],travelModes:['airport','road','border'],architecture:['border metropolis','markets','coastal corridors'],npcCulture:['cross-border','music','food','art'],jobTags:['trade','tourism','logistics','creator'],businessTags:['cross-border commerce','food','retail'],faithCommunityTags:['family resources','community outreach'],guardianTags:['safe passage','resource navigation']},
 'London':{continent:'Europe',country:'United Kingdom',languages:['en'],travelModes:['airport','rail','road','ferry'],architecture:['historic core','modern towers','markets'],npcCulture:['Black British','African diaspora','Caribbean diaspora','grime','football'],jobTags:['media','finance','fashion','tech'],businessTags:['fashion','food','media','retail'],faithCommunityTags:['community service','youth mentorship'],guardianTags:['night travel','event safety']},
 'Lagos':{continent:'Africa',country:'Nigeria',languages:['en','yo'],travelModes:['airport','road','ferry','port'],architecture:['coastal metropolis','markets','creative districts'],npcCulture:['Afrobeats','Nollywood','fashion','tech'],jobTags:['film','music','tech','commerce'],businessTags:['fashion','food','media','trade'],faithCommunityTags:['community service','youth opportunity'],guardianTags:['safe transit','event support']},
 'Accra':{continent:'Africa',country:'Ghana',languages:['en','ak'],travelModes:['airport','road','port'],architecture:['coastal city','markets','arts districts'],npcCulture:['Highlife','Afrobeats','diaspora return','fashion'],jobTags:['tourism','creator','commerce','tech'],businessTags:['tourism','fashion','food','trade'],faithCommunityTags:['diaspora welcome','community service'],guardianTags:['visitor safety','event support']},
 'Kingston':{continent:'Caribbean',country:'Jamaica',languages:['en'],travelModes:['airport','road','port'],architecture:['hills','music districts','waterfront'],npcCulture:['reggae','dancehall','Caribbean diaspora','food'],jobTags:['music','tourism','creator'],businessTags:['music','food','tourism'],faithCommunityTags:['community outreach','youth arts'],guardianTags:['event safety','safe routes']}
}
function pack(city:string,country?:string,region?:string):WorldPack{const p=PACKS[city]||{};return{continent:p.continent||'Global',country:p.country||country||'Unknown',region:p.region||region,city,languages:p.languages||['en'],travelModes:p.travelModes||['airport','road'],architecture:p.architecture||['local landmarks','city center','market district'],npcCulture:p.npcCulture||['local culture','music','food','history'],jobTags:p.jobTags||['creator','commerce','services'],businessTags:p.businessTags||['retail','food','services'],faithCommunityTags:p.faithCommunityTags||['community service','mentorship'],guardianTags:p.guardianTags||['safe routes','community support']}}
function publish(p:WorldPack){try{localStorage.setItem(KEY,JSON.stringify(p))}catch{};window.dispatchEvent(new CustomEvent('tryamm:global-travel-state',{detail:{schema:'tryamm.global.travel.v1',pack:p,flow:'CONTINENT → COUNTRY → REGION → CITY → DISTRICT',transition:{modes:p.travelModes,requiresRealWorldEligibility:false},translation:{languages:p.languages,autoTranslate:true},world:{architecture:p.architecture,npcCulture:p.npcCulture},economy:{jobs:p.jobTags,businesses:p.businessTags},faithCommunity:p.faithCommunityTags,guardian:p.guardianTags}}));window.dispatchEvent(new CustomEvent('tryamm:regional-opportunities-request',{detail:p}));window.dispatchEvent(new CustomEvent('tryamm:world-art-pack-request',{detail:p}))}
export function installGlobalTravelExperienceRuntime(){if(installed||typeof window==='undefined')return;installed=true;window.addEventListener('tryamm:global-city-state',(e:Event)=>{const d=(e as CustomEvent<any>).detail||{};publish(pack(String(d.city||'Chicago'),d.country,d.region))});window.addEventListener('tryamm:global-travel-request',()=>{try{const x=JSON.parse(localStorage.getItem(KEY)||'null');if(x)publish(x)}catch{}})}
