export type CityProfile={city:string;country:string;region?:string;theme:string;districts:string[];landmarks:string[];transit:string[];cultureTags:string[];creatorTags:string[];safetyFocus:string[];diasporaTags?:string[]}
const CITY_KEY='tryamm_global_city_profile_v2'
const CURATED:Record<string,CityProfile>={
'chicago|united states':{city:'Chicago',country:'United States',region:'Illinois',theme:'lakefront-neon',districts:['Downtown','South Side','West Side','North Side','Lakefront'],landmarks:['Lake Michigan','downtown skyline','community arts corridors'],transit:['rail','bus','bike','rideshare'],cultureTags:['house','blues','gospel','hip-hop','architecture','food'],creatorTags:['music','film','fashion','sports','tech'],safetyFocus:['safe passage','youth mentorship','community events'],diasporaTags:['African American','Caribbean','African diaspora']},
'new york|united states':{city:'New York',country:'United States',region:'New York',theme:'vertical-metropolis',districts:['Manhattan','Brooklyn','Queens','Bronx','Staten Island'],landmarks:['skyline','parks','bridges','arts districts'],transit:['subway','bus','rail','ferry','bike'],cultureTags:['hip-hop','fashion','theater','finance','food'],creatorTags:['music','film','fashion','media'],safetyFocus:['safe transit','youth activities','public-space support'],diasporaTags:['African American','Caribbean','African','Latino']},
'hollywood|united states':{city:'Hollywood',country:'United States',region:'California',theme:'studio-neon',districts:['Hollywood','East Hollywood','Sunset','Studio District','Hills'],landmarks:['studio lots','boulevards','theaters','hills'],transit:['metro','bus','rideshare','car'],cultureTags:['film','television','music','fashion','entertainment'],creatorTags:['film','tv','acting','music','broadcast'],safetyFocus:['creator safety','event safety','night travel','youth arts'],diasporaTags:['African American','Latino','Caribbean','African diaspora']},
'los angeles|united states':{city:'Los Angeles',country:'United States',region:'California',theme:'sunset-cinematic',districts:['Downtown','South LA','Hollywood','Westside','Valley'],landmarks:['hills','studios','beaches','boulevards'],transit:['rail','bus','rideshare','car'],cultureTags:['film','music','streetwear','food'],creatorTags:['film','music','video','fashion'],safetyFocus:['safe events','youth arts','neighborhood support'],diasporaTags:['African American','Latino','Caribbean','African diaspora']},
'san diego|united states':{city:'San Diego',country:'United States',region:'California',theme:'pacific-future',districts:['Downtown','Southeast San Diego','North Park','La Jolla','Harbor'],landmarks:['Pacific coast','harbor','parks','creative districts'],transit:['trolley','bus','bike','rideshare'],cultureTags:['surf','military','biotech','music','food'],creatorTags:['film','music','sports','tech','tourism'],safetyFocus:['coastal safety','safe transit','youth mentorship','event support'],diasporaTags:['African American','Latino','Pacific diaspora']},
'atlanta|united states':{city:'Atlanta',country:'United States',region:'Georgia',theme:'southern-future',districts:['Downtown','Midtown','West End','Eastside','Arts District'],landmarks:['city skyline','music corridors','historic neighborhoods'],transit:['rail','bus','rideshare'],cultureTags:['hip-hop','film','black business','food'],creatorTags:['music','film','fashion','entrepreneurship'],safetyFocus:['mentorship','event safety','community building'],diasporaTags:['African American','Caribbean','African diaspora']},
'mexico city|mexico':{city:'Mexico City',country:'Mexico',theme:'historic-neon',districts:['Centro','Roma','Condesa','Coyoacán','Polanco'],landmarks:['historic center','parks','markets','arts corridors'],transit:['metro','bus','bike','rideshare'],cultureTags:['music','art','food','football','history'],creatorTags:['music','film','art','food'],safetyFocus:['safe transit','family routes','community events'],diasporaTags:['Mexican','Afro-Mexican','Latin American']},
'tijuana|mexico':{city:'Tijuana',country:'Mexico',region:'Baja California',theme:'border-future',districts:['Centro','Zona Río','Playas','Otay','Creative District'],landmarks:['border gateway','coast','markets','arts corridors'],transit:['bus','rideshare','walking'],cultureTags:['border culture','music','food','art','entrepreneurship'],creatorTags:['music','film','food','cross-border business'],safetyFocus:['safe transit','family reunification','cross-border resource navigation'],diasporaTags:['Mexican','Afro-Mexican','US-Mexico diaspora']},
'guadalajara|mexico':{city:'Guadalajara',country:'Mexico',region:'Jalisco',theme:'jalisco-future',districts:['Centro','Americana','Zapopan','Tlaquepaque','Tech District'],landmarks:['historic core','markets','creative corridors','tech hubs'],transit:['rail','bus','bike','rideshare'],cultureTags:['music','film','food','technology','heritage'],creatorTags:['music','film','tech','design'],safetyFocus:['youth opportunity','safe events','community routes'],diasporaTags:['Mexican','Afro-Mexican','Latin American']},
'london|united kingdom':{city:'London',country:'United Kingdom',theme:'royal-future',districts:['Central','East','South','West','North'],landmarks:['river','historic core','markets','arts districts'],transit:['tube','rail','bus','bike'],cultureTags:['grime','fashion','football','theater'],creatorTags:['music','fashion','film','design'],safetyFocus:['night travel','youth mentorship','event safety'],diasporaTags:['Black British','Caribbean','African','South Asian']},
'birmingham|united kingdom':{city:'Birmingham',country:'United Kingdom',region:'England',theme:'midlands-future',districts:['City Centre','Handsworth','Digbeth','Jewellery Quarter','Aston'],landmarks:['canals','markets','music venues','creative districts'],transit:['rail','tram','bus','bike'],cultureTags:['music','football','food','manufacturing','arts'],creatorTags:['music','film','fashion','business'],safetyFocus:['youth mentorship','night travel','community events'],diasporaTags:['Black British','Caribbean','African','South Asian']},
'manchester|united kingdom':{city:'Manchester',country:'United Kingdom',region:'England',theme:'northern-future',districts:['City Centre','Moss Side','Northern Quarter','Salford','Sports District'],landmarks:['music venues','stadiums','canals','media district'],transit:['tram','rail','bus','bike'],cultureTags:['music','football','media','fashion'],creatorTags:['music','sports','broadcast','film'],safetyFocus:['event safety','night travel','youth activities'],diasporaTags:['Black British','Caribbean','African']},
'toronto|canada':{city:'Toronto',country:'Canada',region:'Ontario',theme:'lake-city-future',districts:['Downtown','Scarborough','North York','Etobicoke','Waterfront'],landmarks:['waterfront','tower','arts districts','markets'],transit:['subway','streetcar','bus','bike'],cultureTags:['music','film','sports','food','multicultural'],creatorTags:['music','film','tech','sports'],safetyFocus:['safe transit','youth activities','event safety'],diasporaTags:['Black Canadian','Caribbean','African','South Asian']},
'montreal|canada':{city:'Montreal',country:'Canada',region:'Quebec',theme:'bilingual-neon',districts:['Downtown','Little Burgundy','Plateau','Old Montreal','Creative District'],landmarks:['river','historic core','festivals','arts venues'],transit:['metro','bus','bike'],cultureTags:['music','film','fashion','food','bilingual culture'],creatorTags:['music','film','games','design'],safetyFocus:['festival safety','safe transit','youth opportunity'],diasporaTags:['Black Canadian','Haitian','Caribbean','African']},
'vancouver|canada':{city:'Vancouver',country:'Canada',region:'British Columbia',theme:'pacific-glass',districts:['Downtown','East Vancouver','Richmond','Burnaby','Waterfront'],landmarks:['mountains','harbor','film districts','parks'],transit:['skytrain','bus','ferry','bike'],cultureTags:['film','tech','music','outdoors'],creatorTags:['film','games','tech','music'],safetyFocus:['safe transit','event safety','community support'],diasporaTags:['Black Canadian','African','Caribbean','Pacific diaspora']},
'lagos|nigeria':{city:'Lagos',country:'Nigeria',theme:'afrofuture-coast',districts:['Island','Mainland','Lekki','Yaba','Surulere'],landmarks:['lagoon','markets','creative districts','coast'],transit:['bus','ferry','rideshare'],cultureTags:['afrobeats','fashion','film','food','tech'],creatorTags:['music','film','fashion','startup'],safetyFocus:['safe transit','youth opportunity','community events'],diasporaTags:['West African','global African diaspora']},
'accra|ghana':{city:'Accra',country:'Ghana',theme:'gold-coast-future',districts:['Osu','Jamestown','Airport','East Legon','Arts Centre'],landmarks:['coast','markets','historic districts','creative venues'],transit:['bus','rideshare','walking'],cultureTags:['highlife','afrobeats','fashion','food','heritage'],creatorTags:['music','fashion','film','tourism'],safetyFocus:['safe events','community routes','youth opportunity'],diasporaTags:['West African','returning diaspora','Caribbean connections']},
'kingston|jamaica':{city:'Kingston',country:'Jamaica',theme:'island-sound-system',districts:['Downtown','New Kingston','Trench Town','Half Way Tree','Waterfront'],landmarks:['harbor','music landmarks','markets','hills'],transit:['bus','taxi','rideshare'],cultureTags:['reggae','dancehall','food','sports','history'],creatorTags:['music','film','fashion','sports'],safetyFocus:['youth mentorship','event safety','safe routes'],diasporaTags:['Caribbean','African diaspora']},
'port of spain|trinidad and tobago':{city:'Port of Spain',country:'Trinidad and Tobago',theme:'carnival-future',districts:['Downtown','Woodbrook','St James','Savannah','Waterfront'],landmarks:['savannah','waterfront','carnival corridors','markets'],transit:['bus','taxi','rideshare'],cultureTags:['soca','calypso','carnival','food','steelpan'],creatorTags:['music','fashion','events','film'],safetyFocus:['festival safety','crowd safety','safe routes'],diasporaTags:['Caribbean','African diaspora','Indian diaspora']},
'johannesburg|south africa':{city:'Johannesburg',country:'South Africa',region:'Gauteng',theme:'afropolitan-future',districts:['CBD','Soweto','Braamfontein','Sandton','Maboneng'],landmarks:['skyline','township heritage','arts districts','business hubs'],transit:['rail','bus','rideshare'],cultureTags:['amapiano','fashion','business','art','history'],creatorTags:['music','film','fashion','tech'],safetyFocus:['safe transit','youth opportunity','community events'],diasporaTags:['Southern African','continental African diaspora']},
'nairobi|kenya':{city:'Nairobi',country:'Kenya',theme:'savanna-tech',districts:['CBD','Westlands','Kibera','Kilimani','Tech District'],landmarks:['city skyline','markets','parks','innovation hubs'],transit:['bus','rideshare','walking'],cultureTags:['music','tech','fashion','food','wildlife'],creatorTags:['tech','film','music','business'],safetyFocus:['safe transit','youth opportunity','community support'],diasporaTags:['East African','global African diaspora']},
'tokyo|japan':{city:'Tokyo',country:'Japan',theme:'precision-neon',districts:['Shibuya','Shinjuku','Akihabara','Ginza','Asakusa'],landmarks:['crossings','towers','temples','creative districts'],transit:['rail','metro','bus','bike'],cultureTags:['anime','games','fashion','music','food'],creatorTags:['games','animation','music','fashion'],safetyFocus:['safe transit','crowd safety','youth activities']}
}
function key(city:string,country:string){return `${city.trim().toLowerCase()}|${country.trim().toLowerCase()}`}
function generic(city:string,country:string,region?:string):CityProfile{return{city,country,region,theme:'global-living-city',districts:['City Center','Arts District','Market District','Residential District','Transit District'],landmarks:['local landmarks','community spaces','creator venues'],transit:['public transit','walking','bike','rideshare'],cultureTags:['local culture','food','music','history'],creatorTags:['music','film','art','business'],safetyFocus:['safe routes','community support','youth mentorship'],diasporaTags:['local diaspora communities']}}
function save(profile:CityProfile){try{localStorage.setItem(CITY_KEY,JSON.stringify(profile))}catch{}}
function publish(profile:CityProfile){save(profile);document.documentElement.dataset.streetverseCity=profile.city;document.documentElement.dataset.streetverseCityTheme=profile.theme;window.dispatchEvent(new CustomEvent('tryamm:global-city-state',{detail:profile}));window.dispatchEvent(new CustomEvent('tryamm:world-city-changed',{detail:profile}));window.dispatchEvent(new CustomEvent('tryamm:world-location-changed',{detail:{city:profile.city,country:profile.country,region:profile.region,theme:profile.theme}}))}
let installed=false
export function installGlobalCityVerseRuntime(){if(installed||typeof window==='undefined')return;installed=true;let initial:CityProfile|null=null;try{initial=JSON.parse(localStorage.getItem(CITY_KEY)||'null')}catch{};const start=(initial&&typeof initial.city==='string'&&typeof initial.country==='string')?initial:CURATED['chicago|united states'];queueMicrotask(()=>publish(start));window.addEventListener('tryamm:global-city-select',(event:Event)=>{const d=(event as CustomEvent<any>).detail||{},city=String(d.city||'Chicago').trim(),country=String(d.country||'United States').trim(),region=d.region?String(d.region):undefined;publish(CURATED[key(city,country)]||generic(city,country,region))});window.addEventListener('tryamm:global-city-request',()=>publish(start))}
