type Objective={id:string;label:string;done:boolean;requiresVerification?:boolean}
type ActiveMission={id:string;title:string;city:string;rewardXP:number;rewardReputation:number;selectedAt:number;objectives:Objective[];status:'active'|'verification'|'completed'}
type GuardianState={rank:'Recruit'|'Guardian'|'Senior Guardian'|'City Captain'|'Global Guardian';xp:number;reputation:number;completed:number;active:ActiveMission|null}
const KEY='tryamm_guardian_progress_v1';let installed=false
const ranks=(rep:number):GuardianState['rank']=>rep>=1000?'Global Guardian':rep>=500?'City Captain':rep>=250?'Senior Guardian':rep>=100?'Guardian':'Recruit'
const templates:Record<string,string[]>={
 'guardian-watch':['Check assigned safe locations','Confirm community contact points','Complete de-escalation briefing','Submit incident-free patrol report'],
 'safe-passage':['Map safe route','Confirm accessibility path','Identify reunification point','Complete escort without confrontation'],
 'conflict-cooldown':['Identify trusted mediator','Open dialogue channel','Move participants to safe neutral area','Record peaceful resolution'],
 'global-guardian-network':['Confirm vetted local partners','Map emergency and accessibility resources','Verify safe locations','Publish city Guardian readiness summary'],
 'peace-corridor':['Define corridor and exits','Confirm medical/reunification points','Brief volunteers on de-escalation','Close corridor safely'],
 'missing-person-support':['Verify reporting contact','Prepare privacy-safe notice','Coordinate approved search logistics','Document handoff to guardian/authority'],
 'disaster-relief':['Identify verified shelter/resources','Coordinate accessibility and transport needs','Complete welfare checks','Close with verified resource update'],
 'safe-event-command':['Plan entrances and exits','Confirm medical and accessibility routes','Set reunification/lost-child plan','Complete peaceful event closeout'],
 'anti-trafficking-awareness':['Complete awareness briefing','Identify lawful reporting channels','Protect victim privacy','Submit protect-and-report completion'],
 'cyber-safety-relay':['Secure affected account','Preserve lawful evidence','Protect victim privacy','Escalate to Jacobie Vision/moderation/authority as appropriate']
}
function load():GuardianState{try{return JSON.parse(localStorage.getItem(KEY)||'null')||{rank:'Recruit',xp:0,reputation:0,completed:0,active:null}}catch{return{rank:'Recruit',xp:0,reputation:0,completed:0,active:null}}}
function save(s:GuardianState){localStorage.setItem(KEY,JSON.stringify(s));window.dispatchEvent(new CustomEvent('tryamm:guardian-progress-state',{detail:s}))}
export function installGuardianMissionProgressRuntime(){if(installed||typeof window==='undefined')return;installed=true;let state=load();queueMicrotask(()=>save(state));window.addEventListener('tryamm:guardian-progress-request',()=>save(state));window.addEventListener('tryamm:streetverse-mission-select',(e:Event)=>{const d=(e as CustomEvent<any>).detail||{},m=d.mission;if(!m||!(m.assignedTo||[]).some((x:string)=>x==='al-b'||x==='global-security-force'))return;const labels=templates[m.id]||['Review mission briefing','Complete safe objective','Verify outcome','Submit closeout'];state={...state,active:{id:m.id,title:m.title,city:String(d.city||m.city||'Chicago'),rewardXP:Number(m.rewardXP||0),rewardReputation:Math.max(5,Math.round(Number(m.rewardXP||0)/50)),selectedAt:Date.now(),objectives:labels.map((label,i)=>({id:`${m.id}-${i+1}`,label,done:false,requiresVerification:i===labels.length-1})),status:'active'}};save(state)});window.addEventListener('tryamm:guardian-objective-complete',(e:Event)=>{if(!state.active)return;const id=(e as CustomEvent<any>).detail?.id;if(!id)return;state={...state,active:{...state.active,objectives:state.active.objectives.map(o=>o.id===id?{...o,done:true}:o)}};const all=state.active.objectives.every(o=>o.done||o.id===id);if(all)state={...state,active:{...state.active,status:'verification'}};save(state)});window.addEventListener('tryamm:guardian-mission-verify',(e:Event)=>{if(!state.active||state.active.status!=='verification')return;const approved=(e as CustomEvent<any>).detail?.approved===true;if(!approved)return;const xp=state.xp+state.active.rewardXP,rep=state.reputation+state.active.rewardReputation;window.dispatchEvent(new CustomEvent('tryamm:streetverse-reward',{detail:{xp:state.active.rewardXP,reputation:state.active.rewardReputation,source:'guardian-mission',missionId:state.active.id}}));state={rank:ranks(rep),xp,reputation:rep,completed:state.completed+1,active:null};save(state)});window.addEventListener('tryamm:world-location-changed',()=>{if(state.active)save(state)})}
