export type AccessibilityProfile={
  mobility:'standard'|'seated'|'one-hand'|'switch'|'voice';
  vision:'standard'|'large-text'|'high-contrast'|'screen-reader'|'low-vision';
  hearing:'standard'|'captions'|'visual-alerts'|'captions-visual-alerts';
  cognitive:'standard'|'simplified'|'guided'|'reduced-stimulation';
  speech:'standard'|'text-to-speech'|'aac';
  motion:'standard'|'reduced'|'teleport-only';
  handedness:'right'|'left'|'either';
  language:string;
  autoTranslate:boolean;
  captions:boolean;
  spatialAudioCues:boolean;
}

const KEY='tryamm_accessibility_global_v1';let installed=false
const DEFAULT:AccessibilityProfile={mobility:'standard',vision:'standard',hearing:'standard',cognitive:'standard',speech:'standard',motion:'standard',handedness:'either',language:(typeof navigator!=='undefined'&&navigator.language)||'en',autoTranslate:true,captions:true,spatialAudioCues:true}
function read():AccessibilityProfile{try{return {...DEFAULT,...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{return {...DEFAULT}}}
function write(p:AccessibilityProfile){try{localStorage.setItem(KEY,JSON.stringify(p))}catch{};window.dispatchEvent(new CustomEvent('tryamm:accessibility-profile',{detail:p}))}
function announce(text:string){let node=document.getElementById('tryamm-a11y-live');if(!node){node=document.createElement('div');node.id='tryamm-a11y-live';node.setAttribute('role','status');node.setAttribute('aria-live','polite');Object.assign(node.style,{position:'fixed',width:'1px',height:'1px',overflow:'hidden',clip:'rect(0 0 0 0)'});document.body.appendChild(node)}node.textContent=text}
function apply(p:AccessibilityProfile){const root=document.documentElement;root.dataset.tryammMobility=p.mobility;root.dataset.tryammVision=p.vision;root.dataset.tryammHearing=p.hearing;root.dataset.tryammCognitive=p.cognitive;root.dataset.tryammMotion=p.motion;root.lang=p.language.split('-')[0]||'en';root.style.setProperty('--tryamm-ui-scale',p.vision==='large-text'||p.vision==='low-vision'?'1.25':'1');if(p.vision==='high-contrast')root.style.setProperty('--tryamm-contrast','1.35');else root.style.removeProperty('--tryamm-contrast');window.dispatchEvent(new CustomEvent('tryamm:accessibility-apply',{detail:p}))}
function speech(text:string,lang:string){if(!('speechSynthesis'in window))return;const u=new SpeechSynthesisUtterance(text);u.lang=lang;window.speechSynthesis.cancel();window.speechSynthesis.speak(u)}
export function installOmniAccessibilityGlobalRuntime(){if(installed||typeof window==='undefined')return;installed=true;let profile=read();apply(profile);queueMicrotask(()=>write(profile));window.addEventListener('tryamm:accessibility-update',(e:Event)=>{profile={...profile,...((e as CustomEvent<Partial<AccessibilityProfile>>).detail||{})};write(profile);apply(profile);announce('Accessibility settings updated')});window.addEventListener('tryamm:accessibility-announce',(e:Event)=>{const d=(e as CustomEvent<{text?:string}>).detail;const text=String(d?.text||'');if(text)announce(text)});window.addEventListener('tryamm:accessibility-speak',(e:Event)=>{const d=(e as CustomEvent<{text?:string;lang?:string}>).detail;const text=String(d?.text||'');if(text)speech(text,d?.lang||profile.language)});window.addEventListener('tryamm:translate-request',(e:Event)=>{const d=(e as CustomEvent<{text?:string;sourceLanguage?:string;targetLanguage?:string;requestId?:string}>).detail||{};const target=d.targetLanguage||profile.language;window.dispatchEvent(new CustomEvent('tryamm:translation-route',{detail:{...d,targetLanguage:target,mode:'provider-required',status:'adapter-ready'}}))});window.addEventListener('tryamm:quest-input',(e:Event)=>{const d=(e as CustomEvent<Record<string,unknown>>).detail||{};if(profile.mobility==='one-hand'||profile.handedness!=='either')window.dispatchEvent(new CustomEvent('tryamm:accessible-input',{detail:{...d,profile,remap:'single-controller'}}))});window.addEventListener('tryamm:quest-locomotion',(e:Event)=>{const d=(e as CustomEvent<Record<string,unknown>>).detail||{};if(profile.motion==='teleport-only'||profile.motion==='reduced')window.dispatchEvent(new CustomEvent('tryamm:accessible-locomotion',{detail:{...d,mode:profile.motion==='teleport-only'?'teleport':'comfort'}}))});window.addEventListener('tryamm:omni-message',(e:Event)=>{const d=(e as CustomEvent<{text?:string;language?:string}>).detail||{};if(profile.captions&&d.text)window.dispatchEvent(new CustomEvent('tryamm:caption',{detail:{text:d.text,language:d.language||profile.language}}));if(profile.autoTranslate&&d.text&&d.language&&d.language!==profile.language)window.dispatchEvent(new CustomEvent('tryamm:translate-request',{detail:{text:d.text,sourceLanguage:d.language,targetLanguage:profile.language}}))});window.dispatchEvent(new CustomEvent('tryamm:accessibility-ready',{detail:{profile,features:['one-hand-controller-remap','seated-mode','switch-and-voice-routing','teleport-and-reduced-motion','captions','visual-alert-routing','screen-reader-live-region','large-text','high-contrast','simplified-guided-ui','text-to-speech','aac-routing','language-profile','translation-adapter-routing','spatial-audio-cues']}}))}