export type TruthStage='CONCEPT'|'CODED'|'TESTED'|'PERSISTENT'|'INTEGRATED'|'PRODUCTION'|'REAL_WORLD_VERIFIED'
export type TruthEvidence={kind:'code'|'test'|'persistence'|'integration'|'deployment'|'real-world';label:string;verified:boolean;at?:string}
export type FeatureTruth={id:string;name:string;stage:TruthStage;claims:string[];evidence:TruthEvidence[];blockers:string[];moneySensitive?:boolean;physicalClaim?:boolean}
const KEY='tryamm_production_truth_v1';let installed=false
const ORDER:TruthStage[]=['CONCEPT','CODED','TESTED','PERSISTENT','INTEGRATED','PRODUCTION','REAL_WORLD_VERIFIED']
function read():Record<string,FeatureTruth>{try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch{return {}}}
function write(v:Record<string,FeatureTruth>){localStorage.setItem(KEY,JSON.stringify(v));window.dispatchEvent(new CustomEvent('tryamm:production-truth-state',{detail:v}));return v}
function allowedStage(f:FeatureTruth){let n=0;const has=(k:TruthEvidence['kind'])=>f.evidence.some(e=>e.kind===k&&e.verified);if(has('code'))n=1;if(n>=1&&has('test'))n=2;if(n>=2&&has('persistence'))n=3;if(n>=3&&has('integration'))n=4;if(n>=4&&has('deployment'))n=5;if(n>=5&&has('real-world'))n=6;if(f.moneySensitive&&!has('test'))n=Math.min(n,1);if(f.physicalClaim&&!has('real-world'))n=Math.min(n,5);return ORDER[n]}
export function registerFeatureTruth(input:Omit<FeatureTruth,'stage'> & {stage?:TruthStage}){const all=read();const next:FeatureTruth={...input,stage:'CONCEPT'};next.stage=allowedStage(next);all[next.id]=next;write(all);return next}
export function getFeatureTruth(id:string){return read()[id]}
export function getTruthReport(){const all=Object.values(read());return {features:all,counts:ORDER.reduce((a,s)=>({...a,[s]:all.filter(f=>f.stage===s).length}),{} as Record<string,number>),generatedAt:new Date().toISOString()}}
export function installProductionTruthRuntime(){if(installed||typeof window==='undefined')return;installed=true;window.addEventListener('tryamm:truth-register',(e:Event)=>{const d=(e as CustomEvent<any>).detail;if(d?.id&&d?.name)registerFeatureTruth(d)});window.addEventListener('tryamm:truth-report',()=>window.dispatchEvent(new CustomEvent('tryamm:production-truth-report',{detail:getTruthReport()})));registerFeatureTruth({id:'streetverse',name:'StreetVerse',claims:['Playable living-world production slice'],evidence:[{kind:'code',label:'StreetVerse world code',verified:true},{kind:'test',label:'Production build gates',verified:true},{kind:'persistence',label:'Local world save',verified:true},{kind:'integration',label:'Omniverse event fabric',verified:true},{kind:'deployment',label:'Production deployment',verified:true}],blockers:['Server-authoritative world persistence','full mobile visual QA','final rights-cleared photoreal asset pack']});registerFeatureTruth({id:'time-machine',name:'Time Machine / Chrono',claims:['Historical/future simulation experience','wormhole and warp visual simulation'],evidence:[{kind:'code',label:'Chrono runtime',verified:true},{kind:'test',label:'Production build',verified:true},{kind:'persistence',label:'Supabase chrono runs plus saved return state',verified:true},{kind:'integration',label:'Immersive corridor, Benny, Chronicle and portals',verified:true},{kind:'deployment',label:'Production deployment',verified:true}],blockers:['Scenario-specific reconstructed environments','source provenance expansion'],physicalClaim:true});registerFeatureTruth({id:'propertyverse',name:'PropertyVerse',claims:['Global stays, housing assistance navigation, farmland and land-bank discovery'],evidence:[{kind:'code',label:'Property registry/runtime/UI',verified:true},{kind:'test',label:'Production build',verified:true},{kind:'persistence',label:'Listing persistence layer',verified:true},{kind:'integration',label:'Omniverse event fabric',verified:true},{kind:'deployment',label:'Production deployment',verified:true}],blockers:['Live agency/source integrations','transaction and application verification']});window.dispatchEvent(new CustomEvent('tryamm:production-truth-ready',{detail:getTruthReport()}))}