export type ServiceBranch='maritime-guard'|'naval-response'|'ground-service'|'air-rescue'|'federal-investigations'|'county-sheriff-partner'|'fire-ems'|'emergency-management'|'cyber-defense'|'search-rescue'|'transit-safety'|'parks-wildlife'|'humanitarian-diplomatic'
export type ServiceProfile={id:ServiceBranch;label:string;inspiredBy:string;missionTags:string[];training:string[];disclaimer:string}
const KEY='tryamm_public_service_career_v1';let installed=false
export const SERVICE_BRANCHES:ServiceProfile[]=[
 {id:'maritime-guard',label:'Guardian Maritime Service',inspiredBy:'coast guard-style public safety',missionTags:['water rescue','port safety','storm response','missing boater support','marine environmental response'],training:['water safety','first aid','navigation basics','radio procedure'],disclaimer:'Fictional TRYAMM game organization; not affiliated with any real coast guard or government agency.'},
 {id:'naval-response',label:'Guardian Naval Response',inspiredBy:'navy-style logistics and humanitarian response',missionTags:['sea logistics','evacuation support','humanitarian transport','disaster supply chain'],training:['team coordination','logistics','communications','maritime safety'],disclaimer:'Fictional game branch; no military affiliation or authority.'},
 {id:'ground-service',label:'Guardian Ground Service',inspiredBy:'army-style logistics, engineering and relief support',missionTags:['disaster logistics','temporary shelter','infrastructure support','community relief'],training:['logistics','field safety','first aid','team leadership'],disclaimer:'Fictional game branch; no military affiliation or combat authority.'},
 {id:'air-rescue',label:'Guardian Air Rescue',inspiredBy:'air-force-style rescue and airlift support',missionTags:['air rescue coordination','medical transport support','disaster airlift','weather response'],training:['aviation safety','dispatch','weather awareness','rescue coordination'],disclaimer:'Fictional game branch; no military affiliation or flight authority.'},
 {id:'federal-investigations',label:'Guardian Investigations Bureau',inspiredBy:'federal investigative public-safety work',missionTags:['fraud awareness','missing-person support','cyber incident coordination','evidence preservation','victim support'],training:['lawful evidence handling','privacy','reporting','cyber hygiene'],disclaimer:'Fictional game bureau; not affiliated with the FBI or any law-enforcement agency and grants no police powers.'},
 {id:'county-sheriff-partner',label:'County Guardian Services',inspiredBy:'county sheriff/community public-safety coordination',missionTags:['event safety','safe routes','community service','resource navigation','reunification support'],training:['de-escalation','community engagement','first aid','incident reporting'],disclaimer:'Fictional game service; not affiliated with any sheriff department and grants no law-enforcement authority.'},
 {id:'fire-ems',label:'Guardian Fire & EMS',inspiredBy:'fire rescue and emergency medical services',missionTags:['fire prevention','evacuation','medical escalation','welfare checks'],training:['fire safety','CPR awareness','emergency communications','evacuation planning'],disclaimer:'Game simulation only; not a substitute for trained emergency services.'},
 {id:'emergency-management',label:'Guardian Emergency Management',inspiredBy:'civil emergency management',missionTags:['shelters','resource coordination','outage response','disaster communications'],training:['incident command basics','resource mapping','accessibility planning','public information'],disclaimer:'Fictional game service; coordinates simulated missions only.'},
 {id:'cyber-defense',label:'Guardian Cyber Defense',inspiredBy:'public-sector cyber defense and incident response',missionTags:['account security','doxxing response','fraud prevention','incident triage'],training:['MFA','evidence preservation','privacy','phishing awareness'],disclaimer:'Defensive cyber-safety simulation only; no unauthorized access or offensive hacking.'},
 {id:'search-rescue',label:'Guardian Search & Rescue',inspiredBy:'civilian search and rescue',missionTags:['missing-person support','wilderness safety','urban search coordination','reunification'],training:['search safety','navigation awareness','first aid','communications'],disclaimer:'Game simulation; real rescues require qualified responders.'},
 {id:'transit-safety',label:'Guardian Transit Safety',inspiredBy:'public transit safety teams',missionTags:['safe commute','station assistance','crowd flow','accessibility support'],training:['de-escalation','accessibility','crowd safety','reporting'],disclaimer:'Fictional game service; no transit enforcement authority.'},
 {id:'parks-wildlife',label:'Guardian Parks & Wildlife',inspiredBy:'park rangers and wildlife protection',missionTags:['trail safety','lost visitor support','wildlife education','environmental stewardship'],training:['outdoor safety','wildlife awareness','first aid','leave-no-trace'],disclaimer:'Fictional game service; no ranger or conservation enforcement authority.'},
 {id:'humanitarian-diplomatic',label:'Guardian Humanitarian & Diplomatic Corps',inspiredBy:'humanitarian relief and diplomatic community outreach',missionTags:['refugee support','family reunification resources','cultural liaison','disaster relief'],training:['cultural awareness','language support','resource referral','conflict de-escalation'],disclaimer:'Fictional game corps; no diplomatic status or government authority.'},
]
function publish(branch?:ServiceBranch){window.dispatchEvent(new CustomEvent('tryamm:public-service-state',{detail:{schema:'tryamm.public-service.v1',branch,branches:SERVICE_BRANCHES,commander:'al-b',doctrine:['service','prevention','rescue','de-escalation','lawful reporting','no-vigilantism','no-real-world-authority'],allLanguages:true}}))}
export function installPublicServiceCareerRuntime(){if(installed||typeof window==='undefined')return;installed=true;let active:ServiceBranch|undefined;try{active=localStorage.getItem(KEY) as ServiceBranch||undefined}catch{};queueMicrotask(()=>publish(active));window.addEventListener('tryamm:public-service-request',()=>publish(active));window.addEventListener('tryamm:public-service-select',(e:Event)=>{const id=(e as CustomEvent<any>).detail?.branch as ServiceBranch;if(!SERVICE_BRANCHES.some(x=>x.id===id))return;active=id;try{localStorage.setItem(KEY,id)}catch{};publish(active);window.dispatchEvent(new CustomEvent('tryamm:streetverse-local-missions-request',{detail:{serviceBranch:id,commander:'al-b'}}))})}
