export type Regulation='open'|'registration'|'licensed-professional'|'regulated-operator';
export type BusinessVertical={id:string;name:string;regulation:Regulation;services:string[];training:string[];realWorldGate?:string;streetverseMissions:string[]};
const KEY='tryamm_business_verticals_v1';let installed=false;
export const VERTICALS:BusinessVertical[]=[
{id:'telehealth',name:'OmniCare 360 / Telehealth Operations',regulation:'licensed-professional',services:['provider directory','appointment scheduling','accessible intake','translation','care reminders','patient support operations'],training:['privacy basics','accessible intake','customer support','telehealth operations'],realWorldGate:'Diagnosis, treatment and prescribing require appropriately licensed healthcare professionals and compliant providers.',streetverseMissions:['Set up an accessible virtual clinic','Coordinate a non-clinical appointment desk','Build a community wellness outreach event']},
{id:'legal',name:'LawVerse / Legal Services Network',regulation:'licensed-professional',services:['attorney directory','consultation booking','client intake','document organization','matter tracking','legal education'],training:['legal intake operations','confidentiality basics','document workflow','client service'],realWorldGate:'Legal advice and representation must be provided by appropriately licensed attorneys where required.',streetverseMissions:['Open a legal-intake office','Organize a community legal-information event','Route a simulated matter to a verified professional']},
{id:'real-estate',name:'PropertyVerse',regulation:'registration',services:['listings','virtual tours','rental workflows','property management','maintenance dispatch','investment analysis'],training:['leasing operations','property intake','fair-housing awareness','maintenance coordination'],realWorldGate:'Brokerage, appraisal and other licensed activities require applicable real-world credentials.',streetverseMissions:['Lease a virtual storefront','Coordinate property maintenance','Build a neighborhood housing resource hub']},
{id:'insurance',name:'Insurance Services',regulation:'licensed-professional',services:['quote intake','agent marketplace','claims support','policy education'],training:['insurance intake','customer service','claims documentation'],realWorldGate:'Selling, soliciting or advising on insurance requires applicable licenses/appointments.',streetverseMissions:['Run a risk-awareness booth','Complete a simulated claims-support workflow']},
{id:'accounting',name:'Accounting & Business Services',regulation:'registration',services:['bookkeeping','invoicing','payroll integrations','tax-document organization','business operations'],training:['bookkeeping basics','invoice operations','records management'],realWorldGate:'CPA attest services and regulated tax representation require applicable credentials.',streetverseMissions:['Balance a simulated store ledger','Prepare a business records packet']},
{id:'construction',name:'Construction & Home Services',regulation:'regulated-operator',services:['contractor marketplace','electrical','plumbing','HVAC','landscaping','cleaning','moving','remodeling'],training:['jobsite safety awareness','estimating basics','customer service','dispatch'],realWorldGate:'Trade licensing, permits, insurance and inspections vary by jurisdiction and must be verified.',streetverseMissions:['Repair a simulated storefront','Coordinate a neighborhood maintenance dispatch']},
{id:'transport',name:'Transportation & Logistics',regulation:'regulated-operator',services:['delivery','fleet management','dispatch','warehousing','freight','vehicle sharing'],training:['dispatch','route planning','warehouse operations','customer safety'],realWorldGate:'Driving, commercial transport, insurance and operating authority requirements must be verified.',streetverseMissions:['Complete a delivery route','Dispatch a warehouse transfer','Coordinate a fleet shift']},
{id:'education',name:'TRYAMM Academy & Education',regulation:'open',services:['tutoring','vocational simulation','entrepreneurship','AI skills','music and film training'],training:['instruction support','accessibility','learning operations'],streetverseMissions:['Teach a simulated workshop','Build an accessible learning event']},
{id:'hospitality',name:'Hospitality & Food',regulation:'regulated-operator',services:['restaurants','food trucks','hotels','events','catering','travel services'],training:['food-service operations','guest service','event operations'],realWorldGate:'Food safety, lodging, alcohol and event requirements vary by jurisdiction.',streetverseMissions:['Operate a virtual restaurant shift','Coordinate a city event']},
{id:'beauty',name:'Beauty & Wellness',regulation:'regulated-operator',services:['salons','barbers','nails','wigs and hair supply','cosmetics','mobile beauty'],training:['retail','appointment operations','sanitation awareness','creator commerce'],realWorldGate:'Cosmetology/barbering and related services may require licenses and sanitation compliance.',streetverseMissions:['Open a beauty-supply store','Run a salon retail event','Host a live-shopping showcase']},
{id:'media',name:'Media & Entertainment',regulation:'open',services:['studios','podcasts','TV','music labels','film','photography','live events'],training:['production','broadcast','editing','rights awareness'],streetverseMissions:['Produce a StreetVerse show','Record an artist mission','Broadcast a city event']},
{id:'technology',name:'Technology & AI Services',regulation:'open',services:['AI websites','cybersecurity','AI call centers','software','IT support','AI Cafe services'],training:['AI operations','support','web operations','defensive security awareness'],streetverseMissions:['Launch a client website','Run a simulated support desk','Secure a virtual business']},
{id:'agriculture',name:'Agriculture & Environmental Services',regulation:'regulated-operator',services:['farms','food distribution','recycling','remediation workflows','environmental property'],training:['supply chain','food distribution','environmental records','safety awareness'],realWorldGate:'Environmental, waste, remediation, food and land-use activities require applicable testing, permits and approvals.',streetverseMissions:['Supply YAHAVAH Grocery','Coordinate a farm-to-warehouse route','Complete an environmental records mission']}
];
function emit(){window.dispatchEvent(new CustomEvent('tryamm:business-vertical-network-state',{detail:{schema:'tryamm.business.verticals.v1',verticals:VERTICALS,flow:'CHOOSE INDUSTRY → REGULATION CHECK → TRAIN → BUILD WEBSITE → STAFF → SOURCE → MARKETPLACE/STREETVERSE → OPERATE → ANALYTICS → EXPAND'}}))}
export function installRegulatedBusinessNetworkRuntime(){if(installed||typeof window==='undefined')return;installed=true;queueMicrotask(emit);window.addEventListener('tryamm:business-vertical-select',(e:Event)=>{const id=(e as CustomEvent<any>).detail?.id;const v=VERTICALS.find(x=>x.id===id);if(!v)return;try{localStorage.setItem(KEY,JSON.stringify(v))}catch{};window.dispatchEvent(new CustomEvent('tryamm:ai-cafe-task',{detail:{workstream:'business',title:`Launch ${v.name} business workflow`,priority:'high'}}));window.dispatchEvent(new CustomEvent('tryamm:ai-site-create',{detail:{name:v.name,industry:v.id,city:(e as CustomEvent<any>).detail?.city||'Global'}}));window.dispatchEvent(new CustomEvent('tryamm:business-training-path',{detail:{vertical:v}}));window.dispatchEvent(new CustomEvent('tryamm:streetverse-business-mission-pack',{detail:{verticalId:v.id,missions:v.streetverseMissions}}))});window.addEventListener('tryamm:business-professional-verify',(e:Event)=>{const d=(e as CustomEvent<any>).detail||{};window.dispatchEvent(new CustomEvent('tryamm:business-professional-status',{detail:{verticalId:d.verticalId,verified:!!d.verified,credentialType:d.credentialType||null,jurisdiction:d.jurisdiction||null,note:'Verification records eligibility; it does not itself issue a professional license.'}}))})}
