let installed=false
const WORLD_SAVE='tryamm.streetverse.omniworld.v1'
function emit(name:string,detail:any={}){window.dispatchEvent(new CustomEvent(name,{detail}))}
function text(){return document.body?.innerText||''}
function hasStreetVerse(){return text().includes('STREETVERSE • CINEMATIC OMNI DISTRICT')}
function watchVisibleState(){let last='';const scan=()=>{if(!hasStreetVerse())return;const t=text();if(t===last)return;last=t;if(t.includes('DRIVING'))emit('tryamm:streetverse-transport-state',{mode:'car',source:'visible-world'});if(t.includes('StreetVerse resident '))emit('tryamm:streetverse-npc-reaction',{id:'visible-resident',mood:'friendly',line:'resident dialogue visible',source:'visible-world'});if(t.includes('BUSINESS INTERACTION')||t.includes('Entered All American Marketplace')||t.includes('Entered Creator Studio')||t.includes('Entered Holo Ads')||t.includes('Entered All American Network'))emit('tryamm:streetverse-interior-enter',{source:'visible-world'});if(t.includes(' complete • +')){const missionLine=t.split('\n').find(x=>x.includes(' complete • +'))||'StreetVerse mission';emit('tryamm:streetverse-activity-active',{type:'world-mission',objective:missionLine,source:'visible-world'});queueMicrotask(()=>emit('tryamm:construct:targets',{targets:[{id:'visible-world-mission',kind:'mission',title:missionLine,x:0,z:0}],source:'visible-world'}));setTimeout(()=>emit('tryamm:streetverse-activity-complete',{type:'world-mission',source:'visible-world'}),0);setTimeout(()=>emit('tryamm:streetverse-xp',{xp:100,level:1,amount:100,reason:'visible-world-mission',source:'visible-world'}),0)}};const mo=new MutationObserver(scan);mo.observe(document.documentElement,{subtree:true,childList:true,characterData:true});scan();return()=>mo.disconnect()}
function watchMovement(){let moved=false;const key=(e:KeyboardEvent)=>{if(!hasStreetVerse())return;const k=e.key.toLowerCase();if(!moved&&['w','a','s','d','arrowup','arrowdown','arrowleft','arrowright'].includes(k)){moved=true;emit('tryamm:streetverse-player-move',{moved:true,source:'visible-world-input'})}};window.addEventListener('keydown',key);const pointer=(e:PointerEvent)=>{if(!hasStreetVerse()||moved)return;const label=(e.target as HTMLElement)?.textContent||'';if(['▲','▼','◀','▶'].includes(label.trim())){moved=true;emit('tryamm:streetverse-player-move',{moved:true,source:'visible-world-touch'})}};window.addEventListener('pointerdown',pointer,true);return()=>{window.removeEventListener('keydown',key);window.removeEventListener('pointerdown',pointer,true)}}
function watchSave(){let previous=localStorage.getItem(WORLD_SAVE);const id=window.setInterval(()=>{const current=localStorage.getItem(WORLD_SAVE);if(current&&current!==previous){previous=current;emit('tryamm:streetverse-save-complete',{source:'omniworld-autosave',bytes:current.length})}},1200);return()=>clearInterval(id)}
function watchReel(){const handler=()=>{let reported=false;const mo=new MutationObserver(()=>{if(reported)return;const t=text();if(t.includes('Final render: ready')||t.includes('Production upload verified.')||t.includes('Final Reel rendered.')){reported=true;emit('tryamm:reel-recorded',{source:'media-studio-visible-state'});mo.disconnect()}});mo.observe(document.documentElement,{subtree:true,childList:true,characterData:true});setTimeout(()=>mo.disconnect(),10*60*1000)};window.addEventListener('tryamm:media-studio-open',handler);window.addEventListener('tryamm:media-publish-queued',()=>emit('tryamm:reel-saved',{source:'media-publish-queue'}));return()=>window.removeEventListener('tryamm:media-studio-open',handler)}
export function installStreetVerseProductionLoopBridge(){if(installed||typeof window==='undefined')return;installed=true;const clean=[watchVisibleState(),watchMovement(),watchSave(),watchReel()];window.addEventListener('beforeunload',()=>emit('tryamm:streetverse-milestone-arm-reload'));window.dispatchEvent(new CustomEvent('tryamm:streetverse-production-loop-bridge-ready',{detail:{visibleWorld:true,movement:true,drive:true,talk:true,interior:true,mission:true,waypoint:true,objective:true,xp:true,autosave:true,reel:true,reload:true}}));return()=>clean.forEach(fn=>fn())}