export type GameType='story'|'open-world'|'missions'|'creator'|'business'|'racing'|'sports'|'music'|'community'
export type AvatarIdentity={id:string;displayName:string;faceAssetId?:string;faceImageUrl?:string;consent:boolean;createdAt:number}
export type StreetVerseState={avatar:AvatarIdentity|null;gameType:GameType;level:number;xp:number;reputation:number;city:string;visitedCities:string[];language:string;accessibility:string[]}
export type Job={id:string;businessId:string;title:string;skills:string[];minLevel:number;languages:string[];accessibility:string[];city?:string;remote?:boolean;training?:string[];status:'open'|'matched'|'accepted'|'working'|'qa'|'verified'|'paid'}
const STATE_KEY='tryamm_streetverse_unified_v2',JOBS_KEY='tryamm_streetverse_jobs_v1'
let installed=false
const CITIES=['Chicago','Atlanta','New York','Los Angeles','Houston','Detroit','Miami','London','Lagos','Johannesburg','Tokyo','Mexico City','Toronto','Paris','Accra','Nairobi']
function read<T>(k:string,f:T):T{try{return JSON.parse(localStorage.getItem(k)||'null')||f}catch{return f}}
function write(k:string,v:any){try{localStorage.setItem(k,JSON.stringify(v))}catch{}}
function initial():StreetVerseState{return{avatar:null,gameType:'open-world',level:1,xp:0,reputation:0,city:'Chicago',visitedCities:['Chicago'],language:navigator.language||'en',accessibility:[]}}
function emit(state:StreetVerseState,jobs:Job[]){window.dispatchEvent(new CustomEvent('tryamm:streetverse-unified-state',{detail:{schema:'tryamm.streetverse.unified.v2',state,jobs,cities:CITIES,translation:{mode:'all-languages',source:'auto',target:state.language},flow:'ONE AVATAR → GAME TYPE → EXISTING LEVEL → CITY → LOCAL MISSIONS → CHARACTERS → XP + REPUTATION → NEXT CITY → KEEP PROGRESSION'}}))}
export function installStreetVerseUnifiedProgressionRuntime(){if(installed||typeof window==='undefined')return;installed=true;let state=read(STATE_KEY,initial()),jobs=read<Job[]>(JOBS_KEY,[]);const save=()=>{write(STATE_KEY,state);write(JOBS_KEY,jobs);emit(state,jobs)};queueMicrotask(save)
 window.addEventListener('tryamm:streetverse-unified-request',save)
 window.addEventListener('tryamm:streetverse-avatar-set',(e:Event)=>{const d=(e as CustomEvent<any>).detail||{};if(!d.consent)return;state={...state,avatar:{id:String(d.id||`avatar-${Date.now()}`),displayName:String(d.displayName||'Player'),faceAssetId:d.faceAssetId,faceImageUrl:d.faceImageUrl,consent:true,createdAt:Date.now()}};save()})
 window.addEventListener('tryamm:streetverse-game-type',(e:Event)=>{const gameType=(e as CustomEvent<any>).detail?.gameType as GameType;if(['story','open-world','missions','creator','business','racing','sports','music','community'].includes(gameType))state={...state,gameType};save()})
 window.addEventListener('tryamm:world-location-changed',(e:Event)=>{const city=String((e as CustomEvent<any>).detail?.city||state.city);state={...state,city,visitedCities:Array.from(new Set([...state.visitedCities,city]))};save();window.dispatchEvent(new CustomEvent('tryamm:streetverse-local-missions-request',{detail:{city,level:state.level,gameType:state.gameType}}))})
 window.addEventListener('tryamm:streetverse-reward',(e:Event)=>{const d=(e as CustomEvent<any>).detail||{},xp=state.xp+Math.max(0,Number(d.xp||0)),level=Math.max(state.level,1+Math.floor(xp/1000));state={...state,xp,level,reputation:state.reputation+Number(d.reputation||0)};save()})
 window.addEventListener('tryamm:language-changed',(e:Event)=>{state={...state,language:String((e as CustomEvent<any>).detail?.language||state.language)};save()})
 window.addEventListener('tryamm:accessibility-profile-changed',(e:Event)=>{state={...state,accessibility:[...((e as CustomEvent<any>).detail?.needs||[])]};save()})
 window.addEventListener('tryamm:business-post-job',(e:Event)=>{const d=(e as CustomEvent<any>).detail||{};const job:Job={id:String(d.id||`job-${Date.now()}`),businessId:String(d.businessId||'streetverse-business'),title:String(d.title||'StreetVerse Shift'),skills:d.skills||[],minLevel:Math.max(1,Number(d.minLevel||1)),languages:d.languages?.length?d.languages:['any'],accessibility:d.accessibility||[],city:d.city,remote:Boolean(d.remote),training:d.training||[],status:'open'};jobs=[job,...jobs];save();window.dispatchEvent(new CustomEvent('tryamm:job-match-request',{detail:{job,worker:{level:state.level,language:state.language,accessibility:state.accessibility,city:state.city}}}))})
 window.addEventListener('tryamm:job-status',(e:Event)=>{const d=(e as CustomEvent<any>).detail||{};jobs=jobs.map(j=>j.id===d.id?{...j,status:d.status||j.status}:j);save();if(d.status==='verified')window.dispatchEvent(new CustomEvent('tryamm:streetverse-reward',{detail:{xp:Number(d.xp||250),reputation:Number(d.reputation||10)}}))})
}
