import * as THREE from 'three'
type LineDef={id:string;name:string;color:number;mode:'subway'|'elevated'|'surface';z:number;y:number;length:number}
const LINES:LineDef[]=[{id:'red',name:'RED LINE',color:0xc60c30,mode:'subway',z:-86,y:-5,length:210},{id:'blue',name:'BLUE LINE',color:0x00a1de,mode:'subway',z:-102,y:-6,length:230},{id:'brown',name:'BROWN LINE',color:0x62361b,mode:'elevated',z:-54,y:9,length:190},{id:'green',name:'GREEN LINE',color:0x009b3a,mode:'elevated',z:58,y:9,length:210},{id:'orange',name:'ORANGE LINE',color:0xf9461c,mode:'elevated',z:78,y:8,length:210},{id:'pink',name:'PINK LINE',color:0xe27ea6,mode:'elevated',z:18,y:8,length:190},{id:'purple',name:'PURPLE LINE',color:0x522398,mode:'elevated',z:-70,y:10,length:180},{id:'yellow',name:'YELLOW LINE',color:0xf9e300,mode:'surface',z:-118,y:.7,length:150}]
const mat=(color:number,metal=.35)=>new THREE.MeshStandardMaterial({color,roughness:.58,metalness:metal})
const box=(p:THREE.Object3D,x:number,y:number,z:number,w:number,h:number,d:number,m:THREE.Material)=>{const o=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),m);o.position.set(x,y,z);o.castShadow=true;o.receiveShadow=true;p.add(o);return o}
const label=(p:THREE.Object3D,text:string,x:number,y:number,z:number,color:number)=>{const c=document.createElement('canvas');c.width=512;c.height=96;const g=c.getContext('2d');if(g){g.fillStyle='#111';g.fillRect(0,0,512,96);g.fillStyle='#fff';g.font='900 34px Arial';g.textAlign='center';g.textBaseline='middle';g.fillText(text,256,48);g.strokeStyle=`#${color.toString(16).padStart(6,'0')}`;g.lineWidth=10;g.strokeRect(2,2,508,92)}const t=new THREE.CanvasTexture(c);const m=new THREE.Mesh(new THREE.PlaneGeometry(9,1.7),new THREE.MeshBasicMaterial({map:t,transparent:true}));m.position.set(x,y,z);p.add(m)}
const person=(color:number)=>{const g=new THREE.Group();const skin=mat([0x5b3525,0x7a4d34,0xa86f4b,0xc88c68,0xe0ae89][Math.floor(Math.random()*5)],.05);box(g,0,1.1,0,.55,1.25,.35,mat(color,.05));const h=new THREE.Mesh(new THREE.SphereGeometry(.22,8,8),skin);h.position.y=1.95;g.add(h);return g}
const makeTrain=(color:number)=>{const g=new THREE.Group();g.userData.doorsOpen=false;for(let i=0;i<4;i++){const car=new THREE.Group();car.position.x=i*6;box(car,0,0,0,5.5,3,2.7,mat(0xb8bec4,.55));box(car,0,.1,-1.39,5,.35,.08,mat(color,.25));const dl=box(car,-1.15,0,-1.43,1.05,2.05,.06,mat(0x252a30,.35));const dr=box(car,1.15,0,-1.43,1.05,2.05,.06,mat(0x252a30,.35));dl.userData.doorSide=-1;dr.userData.doorSide=1;g.add(car)}const headL=new THREE.PointLight(0xfff2c2,1.2,14,2);headL.position.set(11.5,.4,-1.1);const headR=headL.clone();headR.position.z=1.1;g.add(headL,headR);const brakeL=new THREE.PointLight(0xff1f2f,.7,8,2);brakeL.position.set(-3,.3,-1.05);const brakeR=brakeL.clone();brakeR.position.z=1.05;g.add(brakeL,brakeR);g.userData.brakeLights=[brakeL,brakeR];return g}
export function addStreetVerseChicagoFullRailNetwork3D(scene:THREE.Scene){
 const root=new THREE.Group();root.name='streetverse-chicago-full-rail-network';scene.add(root)
 const trains:{g:THREE.Group;line:LineDef;phase:number;manual:boolean;doors:boolean;targetX:number|null;speed:number;disabled:boolean;throttle:number;brake:number}[]=[]
 const crowds=new Map<string,THREE.Group[]>(), onboard=new Map<string,THREE.Group[]>()
 LINES.forEach((line,idx)=>{const g=new THREE.Group();root.add(g);if(line.mode==='subway'){box(g,0,line.y,line.z,line.length,7,18,mat(0x25282d,.05));box(g,0,line.y+3.1,line.z,line.length,.35,11,mat(0x3d4248,.45));for(let x=-line.length/2+10;x<line.length/2;x+=28){box(g,x,line.y+1.1,line.z-5.2,18,.5,3.2,mat(0x666a6f,.2));label(g,`${line.name} • SUBWAY`,x,line.y+4.5,line.z-7,line.color)}}else{for(let x=-line.length/2;x<=line.length/2;x+=12)box(g,x,line.y/2,line.z,.6,line.y,.6,mat(0x3d444d,.7));box(g,0,line.y,line.z,line.length,.5,5.5,mat(0x4b5158,.7));for(let x=-line.length/2+18;x<line.length/2;x+=42){box(g,x,line.y+.8,line.z-3,22,.4,4.5,mat(0x666a6f,.3));label(g,line.name,x,line.y+3,line.z-5.4,line.color)}}for(const dz of [-1.2,1.2])box(g,0,line.y+.55,line.z+dz,line.length,.16,.16,mat(0x222,.9));for(let x=-line.length/2+16;x<line.length/2;x+=36){const pole=box(g,x,line.y+2.2,line.z+3.2,.2,4.2,.2,mat(0x222,.7));const signal=new THREE.PointLight(0x21d65b,.8,10,2);signal.position.set(x,line.y+4.2,line.z+3.2);g.add(signal);pole.userData.signal=signal}const train=makeTrain(line.color);train.position.set(-line.length/2+12,line.y+1.9,line.z);root.add(train);trains.push({g:train,line,phase:idx*23,manual:false,doors:false,targetX:null,speed:8,disabled:false,throttle:0,brake:0});const people:THREE.Group[]=[];for(let i=0;i<14;i++){const p=person([0x2f6fb3,0xb84f70,0x4b9a63,0xd48a3d,0x7454b6,0x3ca8a1][i%6]);p.position.set(-line.length/2+20+(i%7)*7,line.y+1.2,line.z-4.4+(i%2)*1.3);root.add(p);people.push(p)}crowds.set(line.id,people);onboard.set(line.id,[])})
 const active=(id?:string)=>trains.find(t=>t.line.id===id)
 const animateCrowd=(lineId:string,trainX:number,boarding:boolean)=>{const ps=crowds.get(lineId)||[];ps.forEach((p,i)=>{p.userData.boarding=boarding;p.userData.baseX=p.position.x;p.userData.targetX=boarding?trainX-6+(i%4)*3:p.position.x+(i%2?7:-7)})}
 const boardVisible=(t:ReturnType<typeof active>)=>{if(!t)return;const ps=crowds.get(t.line.id)||[], riders=onboard.get(t.line.id)||[];while(ps.length&&riders.length<8){const p=ps.shift()!;root.remove(p);p.position.set(-5+(riders.length%4)*3,0.1,(riders.length%2?-.65:.65));p.scale.setScalar(.82);t.g.add(p);riders.push(p)}onboard.set(t.line.id,riders);window.dispatchEvent(new CustomEvent('tryamm:transit-onboard-riders',{detail:{lineId:t.line.id,count:riders.length}}))}
 const evacuateVisible=(t:ReturnType<typeof active>)=>{if(!t)return;const riders=onboard.get(t.line.id)||[], ps=crowds.get(t.line.id)||[];riders.splice(0).forEach((p,i)=>{t.g.remove(p);p.scale.setScalar(1);p.position.set(t.g.position.x-4+i*1.4,t.line.y+1.2,t.line.z-4.5);root.add(p);p.userData.targetX=t.g.position.x+(i%2?14:-14);ps.push(p)});onboard.set(t.line.id,[])}
 const emitState=(t:NonNullable<ReturnType<typeof active>>,extra:any={})=>window.dispatchEvent(new CustomEvent('tryamm:l-train-state',{detail:{lineId:t.line.id,x:t.g.position.x,speed:t.speed,doorsOpen:t.doors,throttle:t.throttle,brake:t.brake,disabled:t.disabled,onboard:(onboard.get(t.line.id)||[]).length,...extra}}))
 const onLine=(e:Event)=>{const d=(e as CustomEvent).detail||{},t=active(d.lineId);if(!t)return;t.manual=true;t.disabled=false;t.doors=false;const count=Math.max(1,Number(d.stopIndex)+1),step=(t.line.length-36)/Math.max(2,count+2);t.targetX=Math.min(t.line.length/2-18,-t.line.length/2+18+step*count);t.speed=0;t.throttle=0;t.brake=1;emitState(t,{station:d.stop})}
 const onControl=(e:Event)=>{const d=(e as CustomEvent).detail||{},t=active(d.lineId);if(!t||t.disabled)return;t.manual=true;t.throttle=Math.max(0,Math.min(1,Number(d.throttle)||0));t.brake=Math.max(0,Math.min(1,Number(d.brake)||0));if(t.doors)t.throttle=0;emitState(t)}
 const onDoors=(e:Event)=>{const d=(e as CustomEvent).detail||{},t=active(d.lineId);if(!t)return;t.manual=true;t.doors=!!d.open;if(t.doors){t.throttle=0;t.brake=1;t.speed=0}else t.brake=Math.max(t.brake,.25);t.g.userData.doorsOpen=t.doors;t.g.traverse(o=>{if(o.userData?.doorSide)o.position.x=t.doors?o.userData.doorSide*.38:0});animateCrowd(t.line.id,t.g.position.x,t.doors);if(t.doors)setTimeout(()=>boardVisible(t),700);emitState(t,{station:d.station})}
 const onAnnouncement=(e:Event)=>{const d=(e as CustomEvent).detail||{};if(typeof d.text!=='string')return;window.dispatchEvent(new CustomEvent('tryamm:transit-announcement-live',{detail:d}));try{if('speechSynthesis'in window){speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(d.text);u.rate=.96;u.pitch=.95;speechSynthesis.speak(u)}}catch{}}
 const onBossStop=()=>{const t=active('red');if(!t)return;t.manual=true;t.disabled=true;t.throttle=0;t.brake=1;t.speed=0;t.targetX=t.g.position.x;emitState(t)}
 const onEvac=()=>{const t=active('red');if(!t)return;t.doors=true;t.g.traverse(o=>{if(o.userData?.doorSide)o.position.x=o.userData.doorSide*.38});evacuateVisible(t);animateCrowd('red',t.g.position.x,false);window.dispatchEvent(new CustomEvent('tryamm:transit-evacuation-active',{detail:{lineId:'red',passengers:(crowds.get('red')||[]).length}}))}
 const onReroute=()=>{const b=active('blue');if(!b)return;b.manual=true;b.disabled=false;b.brake=0;b.throttle=.65;b.targetX=Math.min(b.line.length/2-18,b.g.position.x+42);emitState(b,{rerouted:true})}
 const onRestore=()=>{trains.forEach(t=>{t.disabled=false;t.manual=false;t.doors=false;t.throttle=0;t.brake=0;t.g.traverse(o=>{if(o.userData?.doorSide)o.position.x=0})});window.dispatchEvent(new CustomEvent('tryamm:transit-network-live',{detail:{lines:LINES.length}}))}
 window.addEventListener('tryamm:transit-line-active',onLine);window.addEventListener('tryamm:transit-operator-control',onControl);window.addEventListener('tryamm:l-train-doors',onDoors);window.addEventListener('tryamm:transit-announcement',onAnnouncement);window.addEventListener('tryamm:transit-emergency-stop',onBossStop);window.addEventListener('tryamm:transit-evacuation',onEvac);window.addEventListener('tryamm:transit-reroute',onReroute);window.addEventListener('tryamm:transit-network-restored',onRestore)
 const clock=new THREE.Clock();let raf=0,last=clock.getElapsedTime();const tick=()=>{const now=clock.getElapsedTime(),dt=Math.min(.05,now-last);last=now;trains.forEach(t=>{const brakeLights=t.g.userData.brakeLights as THREE.PointLight[]|undefined;if(brakeLights)brakeLights.forEach(l=>l.intensity=t.brake>0?.9:.15);if(t.disabled)return;if(t.manual){if(!t.doors){const accel=t.throttle*5.4-t.brake*8.5;t.speed=Math.max(0,Math.min(11,t.speed+accel*dt));if(t.targetX!==null){const dx=t.targetX-t.g.position.x;if(Math.abs(dx)<.25&&t.speed<1.2){t.g.position.x=t.targetX;t.speed=0;t.brake=1}else if(t.speed>0)t.g.position.x+=Math.sign(dx)*t.speed*dt}else t.g.position.x+=t.speed*dt}}else{const span=t.line.length-30;t.g.position.x=-span/2+((now*8+t.phase)%span);t.speed=8}});crowds.forEach(ps=>ps.forEach(p=>{if(Number.isFinite(p.userData?.targetX)){const dx=p.userData.targetX-p.position.x;p.position.x+=Math.sign(dx)*Math.min(Math.abs(dx),dt*2.2)}}));raf=requestAnimationFrame(tick)};tick()
 window.dispatchEvent(new CustomEvent('tryamm:streetverse-rail-network-ready',{detail:{lines:LINES.map(l=>({id:l.id,name:l.name,mode:l.mode})),subway:['red','blue'],elevated:['brown','green','orange','pink','purple'],surface:['yellow'],missionControlled:true,visiblePlatformCrowds:true,visibleOnboardRiders:true,bossControlled:true,manualThrottleBrake:true,stationAnnouncements:true,signals:true,trainLights:true}}))
 return {group:root,lines:LINES.length,subwayLines:2,visiblePassengers:Array.from(crowds.values()).reduce((n,p)=>n+p.length,0),dispose:()=>{cancelAnimationFrame(raf);window.removeEventListener('tryamm:transit-line-active',onLine);window.removeEventListener('tryamm:transit-operator-control',onControl);window.removeEventListener('tryamm:l-train-doors',onDoors);window.removeEventListener('tryamm:transit-announcement',onAnnouncement);window.removeEventListener('tryamm:transit-emergency-stop',onBossStop);window.removeEventListener('tryamm:transit-evacuation',onEvac);window.removeEventListener('tryamm:transit-reroute',onReroute);window.removeEventListener('tryamm:transit-network-restored',onRestore);scene.remove(root);root.traverse(o=>{const m=o as THREE.Mesh;m.geometry?.dispose?.();const material=m.material as THREE.Material|THREE.Material[]|undefined;if(Array.isArray(material))material.forEach(x=>x.dispose());else material?.dispose?.()})}}
}
