let installed=false
const ID='tryamm-airport-after-dark'
const KEY='tryamm.streetverse.airport-after-dark.v1'
type Mission={id:string;title:string;zone:'OHARE'|'MIDWAY'|'AFTER_DARK';summary:string;objectives:string[];xp:number;credits:number}
const MISSIONS:Mission[]=[
{id:'ord-blue-arrival',title:"O'Hare Blue Line Arrival",zone:'OHARE',summary:'Meet an arriving traveler, navigate the terminal connection and escort them to the Blue Line.',objectives:['Report at Terminal 2 connection','Meet traveler','Guide through pedestrian connection','Reach Blue Line platform'],xp:420,credits:80},
{id:'ord-ats-link',title:"O'Hare ATS Connector",zone:'OHARE',summary:'Move between Terminal 5 and the Terminal 2 CTA connection using the airport people-mover corridor.',objectives:['Start at Terminal 5','Board ATS checkpoint','Transfer at Terminal 2','Reach CTA connection'],xp:460,credits:90},
{id:'ord-baggage-recovery',title:'Baggage Recovery',zone:'OHARE',summary:'Locate a missing game-world bag and reunite it with its owner.',objectives:['Receive lost-bag report','Search baggage area','Verify claim tag','Return bag to traveler'],xp:380,credits:75},
{id:'ord-night-worker',title:"O'Hare Night Worker Run",zone:'OHARE',summary:'Late-night airport worker transport mission using the 24-hour Blue Line corridor.',objectives:['Pick up airport worker','Reach Blue Line','Complete night transfer','Deliver to safe destination'],xp:500,credits:100},
{id:'mdw-orange-arrival',title:'Midway Orange Arrival',zone:'MIDWAY',summary:'Escort an arriving passenger through the enclosed connection to the Orange Line.',objectives:['Meet passenger in terminal','Find CTA signs','Cross enclosed walkway','Reach Midway Orange Line platform'],xp:400,credits:80},
{id:'mdw-crew-turn',title:'Midway Crew Turn',zone:'MIDWAY',summary:'Move an airline crew from the terminal to downtown on a timed Orange Line mission.',objectives:['Meet crew','Cross terminal walkway','Board Orange Line checkpoint','Reach Loop transfer'],xp:520,credits:105},
{id:'mdw-last-run',title:'Midway Last Run',zone:'MIDWAY',summary:'Complete a late-evening airport transfer before rail service winds down.',objectives:['Accept timed transfer','Reach Midway station','Board departure window','Complete downtown handoff'],xp:560,credits:110},
{id:'after-dark-club-run',title:'Omniverse After Dark: Club Run',zone:'AFTER_DARK',summary:'Night creator mission connecting Chicago After Dark venues, transit and safe rides.',objectives:['Meet creator host','Deliver media package','Check venue security','Complete safe ride handoff'],xp:540,credits:110},
{id:'after-dark-lower-wacker',title:'Omniverse After Dark: Lower Wacker',zone:'AFTER_DARK',summary:'Night courier route from downtown nightlife to Lower Wacker service access.',objectives:['Pick up sealed creator equipment','Enter downtown night corridor','Clear Lower Wacker checkpoint','Deliver to production crew'],xp:610,credits:125},
{id:'after-dark-lakefront',title:'Omniverse After Dark: Lakefront Lights',zone:'AFTER_DARK',summary:'Run a nighttime lakefront creator event with lighting, crowd and transit objectives.',objectives:['Meet lakefront crew','Activate event checkpoints','Handle crowd/transit handoff','Close event safely'],xp:580,credits:120},
]
function active(){const h=location.hash.replace(/^#/,'');return h==='/streetverse'||h==='/city'}
function read(){try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch{return {completed:[]}}}
function write(s:any){try{localStorage.setItem(KEY,JSON.stringify({...s,updatedAt:new Date().toISOString()}))}catch{}}
function emit(name:string,detail:any){window.dispatchEvent(new CustomEvent(name,{detail}))}
function mount(){if(!active()){document.getElementById(ID)?.remove();return}if(document.getElementById(ID))return;let state=read();state.completed=Array.isArray(state.completed)?state.completed:[];const root=document.createElement('div');root.id=ID;root.style.cssText='position:fixed;right:12px;bottom:82px;z-index:2147482600;font-family:Inter,Arial,sans-serif;color:white;pointer-events:auto';const btn=document.createElement('button');btn.textContent='✈️ AIRPORT + 🌙 AFTER DARK';btn.style.cssText='padding:9px 12px;border-radius:999px;border:1px solid #6ba8d8;background:#07131ded;color:#fff;font-size:10px;font-weight:900;cursor:pointer';const panel=document.createElement('div');panel.style.cssText='display:none;margin-top:7px;width:min(92vw,430px);max-height:68vh;overflow:auto;padding:12px;border:1px solid #34556b;border-radius:15px;background:#050b12f4;box-shadow:0 20px 60px #000c';const render=()=>{panel.innerHTML='<b>O’HARE • MIDWAY • OMNIVERSE AFTER DARK</b><div style="font-size:9px;opacity:.65;margin:4px 0 9px">Airport missions + Chicago night-world missions</div>';MISSIONS.forEach(m=>{const done=state.completed.includes(m.id),activeMission=state.missionId===m.id;const c=document.createElement('div');c.style.cssText=`padding:9px;margin:6px 0;border-radius:9px;border:1px solid #33495a;background:${done?'#0d2319':'#0b141d'}`;c.innerHTML=`<b>${done?'✓ ':''}${m.title}</b><br><span style="font-size:9px;opacity:.7">${m.zone} • ${m.summary}</span>${activeMission?`<div style="font-size:9px;color:#8fd8ff;margin-top:5px">${m.objectives[Math.min(state.objective||0,m.objectives.length-1)]}</div>`:''}`;const a=document.createElement('button');a.textContent=activeMission?'COMPLETE OBJECTIVE':'START';a.style.cssText='margin-top:6px;padding:6px 8px;border-radius:7px;border:1px solid #42637a;background:#10202e;color:white;font-size:9px;font-weight:900';a.onclick=()=>{if(!activeMission){state={...state,missionId:m.id,objective:0};write(state);emit('tryamm:airport-after-dark-mission-start',m);render();return}const next=(state.objective||0)+1;if(next>=m.objectives.length){state={...state,missionId:undefined,objective:0,completed:[...new Set([...state.completed,m.id])]};write(state);emit('tryamm:mission-completed',{missionId:m.id,title:m.title,xp:m.xp,holoCredits:m.credits,source:'airport-after-dark'})}else{state={...state,objective:next};write(state)}render()};if(!done||activeMission)c.append(a);panel.append(c)})};btn.onclick=()=>{panel.style.display=panel.style.display==='none'?'block':'none';if(panel.style.display==='block')render()};root.append(btn,panel);document.body.appendChild(root);emit('tryamm:airport-after-dark-ready',{ohare:MISSIONS.filter(m=>m.zone==='OHARE').length,midway:MISSIONS.filter(m=>m.zone==='MIDWAY').length,afterDark:MISSIONS.filter(m=>m.zone==='AFTER_DARK').length})}
export function installStreetVerseAirportAfterDarkRuntime(){if(installed||typeof window==='undefined'||typeof document==='undefined')return;installed=true;const sync=()=>requestAnimationFrame(mount);window.addEventListener('hashchange',sync);window.addEventListener('tryamm:streetverse-enter',sync);if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',sync,{once:true});else sync()}
