import * as THREE from 'three'

type Point={x:number;z:number}
type ZoneKind='store'|'vendor'|'arena'|'portal'|'product'|'checkout'|'live'
type Zone={id:string;kind:ZoneKind;x:number;z:number;radius:number;title:string;eventName?:string;storeId?:string;productId?:string}
type Product={id:string;name:string;price:number;storeId:string;mesh:THREE.Object3D;home:THREE.Vector3;held:boolean}

let installed=false,active=false,raf=0
let root:HTMLDivElement|null=null,renderer:THREE.WebGLRenderer|null=null,scene:THREE.Scene|null=null,camera:THREE.PerspectiveCamera|null=null
let player:Point={x:0,z:58},targetPlayer:Point={x:0,z:58}
let currentZone:Zone|null=null,heldProduct:Product|null=null,pkActive=false,pkLeft=0,pkRight=0
const anim:THREE.Object3D[]=[]
const labels:{el:HTMLDivElement;pos:THREE.Vector3}[]=[]
const zones:Zone[]=[]
const products:Product[]=[]
let interactButton:HTMLButtonElement|null=null,contextPanel:HTMLDivElement|null=null,toast:HTMLDivElement|null=null

function m(color:number,opacity=.9){return new THREE.MeshBasicMaterial({color,transparent:opacity<1,opacity,depthWrite:false,toneMapped:false})}
function b(w:number,h:number,d:number,color:number,opacity=.9){return new THREE.Mesh(new THREE.BoxGeometry(w,h,d),m(color,opacity))}
function dist(a:Point,b:{x:number;z:number}){return Math.hypot(a.x-b.x,a.z-b.z)}
function label(text:string,pos:THREE.Vector3,color='#67e8f9'){
 if(!root)return;const el=document.createElement('div');el.textContent=text;Object.assign(el.style,{position:'fixed',transform:'translate(-50%,-50%)',padding:'6px 9px',border:`1px solid ${color}`,borderRadius:'9px',background:'rgba(3,7,18,.78)',color,font:'700 11px system-ui',letterSpacing:'.06em',boxShadow:`0 0 14px ${color}66`,pointerEvents:'none',whiteSpace:'nowrap',zIndex:'4'});root.appendChild(el);labels.push({el,pos})
}
function addZone(zone:Zone){zones.push(zone)}
function vendor(x:number,z:number,name:string,color:number,id:string){if(!scene)return;const g=new THREE.Group();const body=b(.7,1.4,.45,color,.95);body.position.y=1.05;g.add(body);const head=new THREE.Mesh(new THREE.SphereGeometry(.3,12,10),m(0xb97952,.98));head.position.y=2;g.add(head);g.position.set(x,0,z);scene.add(g);anim.push(g);label(name,new THREE.Vector3(x,2.8,z),'#fcd34d');addZone({id,kind:'vendor',x,z,radius:4,title:name})}
function productProp(storeId:string,id:string,name:string,price:number,x:number,z:number,color:number){if(!scene)return;const g=new THREE.Group();const plinth=b(1.5,.35,1.5,0x111827,.95);plinth.position.y=.2;g.add(plinth);const item=b(.9,1.1,.7,color,.95);item.position.y=.95;g.add(item);g.position.set(x,0,z);scene.add(g);products.push({id,name,price,storeId,mesh:g,home:g.position.clone(),held:false});label(`${name} • $${price.toFixed(2)} demo`,new THREE.Vector3(x,2.2,z),'#a7f3d0');addZone({id:`product:${id}`,kind:'product',x,z,radius:2.5,title:`Inspect ${name}`,storeId,productId:id})}
function store(x:number,z:number,name:string,color:number,storeId:string){if(!scene)return;const g=new THREE.Group();const back=b(10,5,.35,0x111827,.92);back.position.set(0,2.5,-3.3);g.add(back);const left=b(.35,5,7,0x111827,.92);left.position.set(-4.8,2.5,0);g.add(left);const right=b(.35,5,7,0x111827,.92);right.position.set(4.8,2.5,0);g.add(right);const roof=b(10,.3,7,0x111827,.9);roof.position.set(0,5,0);g.add(roof);const floor=b(10,.15,7,0x182133,.96);floor.position.y=.08;g.add(floor);const glassL=b(3.8,3,.14,color,.13);glassL.position.set(-2.7,2.1,3.45);g.add(glassL);const glassR=b(3.8,3,.14,color,.13);glassR.position.set(2.7,2.1,3.45);g.add(glassR);const awning=b(9,.4,1.2,color,.82);awning.position.set(0,4.7,3.8);g.add(awning);const counter=b(5,1.1,1.1,0x273248,.96);counter.position.set(0,.65,-2.2);g.add(counter);const checkout=b(2.2,.18,1.1,color,.88);checkout.position.set(0,1.35,-2.2);g.add(checkout);for(let i=-2;i<=2;i++){const shelf=b(1.2,1.7,.8,0xffffff,.12);shelf.position.set(i*1.45,1.35,1.9);g.add(shelf)}g.position.set(x,0,z);scene.add(g);label(name,new THREE.Vector3(x,6,z),'#fde68a');addZone({id:`store:${storeId}`,kind:'store',x,z:z+3.7,radius:4,title:`Enter ${name}`,storeId});addZone({id:`checkout:${storeId}`,kind:'checkout',x,z:z-2.2,radius:3,title:`Checkout • ${name}`,storeId})
 productProp(storeId,`${storeId}-1`,storeId==='creator'?'Creator Hoodie':storeId==='omni'?'Omni Headset':storeId==='music'?'Performance Mic':'Business Kit',storeId==='creator'?29.99:storeId==='omni'?49.99:storeId==='music'?19.99:39.99,x-2.8,z+1.6,color)
 productProp(storeId,`${storeId}-2`,storeId==='creator'?'Holo Cap':storeId==='omni'?'Holo Display':storeId==='music'?'Studio Pack':'Storefront Pack',storeId==='creator'?14.99:storeId==='omni'?24.99:storeId==='music'?34.99:59.99,x+2.8,z+1.6,color)
}
function portal(x:number,z:number,name:string,color:number,eventName:string,id:string){if(!scene)return;const g=new THREE.Group();const l=b(.45,4,.45,color,.72),r=b(.45,4,.45,color,.72),t=b(4,.45,.45,color,.72);l.position.set(-1.8,2,0);r.position.set(1.8,2,0);t.position.set(0,4,0);g.add(l,r,t);const ring=new THREE.Mesh(new THREE.TorusGeometry(1.45,.1,8,40),m(color,.95));ring.position.y=2.2;g.add(ring);g.position.set(x,0,z);g.userData.eventName=eventName;scene.add(g);anim.push(ring);label(name,new THREE.Vector3(x,4.9,z),'#93c5fd');addZone({id,kind:'portal',x,z,radius:4,title:`Enter ${name}`,eventName})}
function arena(){if(!scene)return;const g=new THREE.Group();const floor=new THREE.Mesh(new THREE.CylinderGeometry(11,11,.5,48),m(0x171a33,.96));floor.position.y=.3;g.add(floor);const rim=new THREE.Mesh(new THREE.TorusGeometry(10.3,.22,8,64),m(0x22d3ee,.88));rim.rotation.x=Math.PI/2;rim.position.y=.65;g.add(rim);const stage=b(8,1,5,0x29264f,.97);stage.position.y=1;g.add(stage);const live=b(11,5,.3,0x060b19,.98);live.position.set(0,7,-4.5);g.add(live);const banner=b(10,.45,.35,0xec4899,.95);banner.position.set(0,5.1,-4.4);g.add(banner);for(const x of [-3.2,3.2]){const podium=b(2,2,2,x<0?0x06b6d4:0xec4899,.85);podium.position.set(x,1.5,0);g.add(podium)}g.position.set(0,0,-8);scene.add(g);label('TRYAMM PK / LIVE ARENA',new THREE.Vector3(0,10,-8),'#f472b6');label('TEAM A  0  :  0  TEAM B',new THREE.Vector3(0,7,-8),'#ffffff');label('LIVE • TAP INTERACT TO START PK',new THREE.Vector3(0,5.8,-8),'#fb7185');anim.push(rim);addZone({id:'pk-arena',kind:'arena',x:0,z:-8,radius:12,title:'TRYAMM PK / LIVE Arena'});addZone({id:'live-screen',kind:'live',x:0,z:-13,radius:6,title:'Watch LIVE'})}
function giftBurst(){if(!scene)return;for(let i=0;i<18;i++){const s=new THREE.Mesh(new THREE.SphereGeometry(.12,8,6),m(i%2?0xff4fc3:0x67e8f9,.9));s.position.set((Math.random()-.5)*6,2+Math.random()*3,-8+(Math.random()-.5)*3);s.userData.baseY=s.position.y;s.userData.phase=Math.random()*6.28;scene.add(s);anim.push(s)}}
function say(message:string){if(!toast)return;toast.textContent=message;toast.style.display='block';clearTimeout((say as any)._t);(say as any)._t=setTimeout(()=>{if(toast)toast.style.display='none'},2600)}
function dispatch(name:string,detail:Record<string,unknown>={}){window.dispatchEvent(new CustomEvent(name,{detail}))}
function setContext(title:string,body:string,actions:{label:string;run:()=>void}[]){if(!contextPanel)return;contextPanel.innerHTML='';const h=document.createElement('div');h.textContent=title;Object.assign(h.style,{fontWeight:'900',fontSize:'15px',color:'#fff'});const p=document.createElement('div');p.textContent=body;Object.assign(p.style,{fontSize:'12px',lineHeight:'1.5',color:'#cbd5e1',marginTop:'6px'});contextPanel.append(h,p);const row=document.createElement('div');Object.assign(row.style,{display:'flex',flexWrap:'wrap',gap:'7px',marginTop:'10px'});for(const a of actions){const bt=document.createElement('button');bt.textContent=a.label;Object.assign(bt.style,{padding:'9px 11px',borderRadius:'10px',border:'1px solid #67e8f9',background:'#0f172a',color:'#fff',fontWeight:'800'});bt.onclick=a.run;row.appendChild(bt)}contextPanel.appendChild(row);contextPanel.style.display='block'}
function hideContext(){if(contextPanel)contextPanel.style.display='none'}
function updateScore(){const score=labels.find(x=>x.el.textContent?.includes('TEAM A'));if(score)score.el.textContent=`TEAM A  ${pkLeft}  :  ${pkRight}  TEAM B`;dispatch('tryamm:pk-score',{left:pkLeft,right:pkRight})}
function pickup(product:Product){if(heldProduct&&heldProduct.id!==product.id){say('Put down the item you are holding first.');return}heldProduct=product;product.held=true;say(`Picked up ${product.name}`);dispatch('tryamm:marketplace-item-picked-up',{productId:product.id,name:product.name,price:product.price,storeId:product.storeId})}
function putDown(){if(!heldProduct)return;heldProduct.held=false;heldProduct.mesh.position.copy(heldProduct.home);dispatch('tryamm:marketplace-item-put-down',{productId:heldProduct.id,name:heldProduct.name});say(`Put down ${heldProduct.name}`);heldProduct=null}
function checkout(storeId:string){if(!heldProduct||heldProduct.storeId!==storeId){say('Pick up an item from this store first.');return}setContext('CHECKOUT SURFACE',`${heldProduct.name} • $${heldProduct.price.toFixed(2)}. Demo checkout only until server payment verification, identity/tax onboarding, refunds, chargebacks and payout controls are live.`,[{label:'DEMO CHECKOUT',run:()=>{dispatch('tryamm:checkout-intent',{mode:'demo',productId:heldProduct?.id,storeId,amountCents:Math.round((heldProduct?.price||0)*100),currency:'USD'});say('Demo checkout recorded • no real money charged');hideContext()}},{label:'PUT DOWN',run:putDown},{label:'CLOSE',run:hideContext}])}
function vendorTalk(zone:Zone){const translated=zone.title.includes('Music')?'Creator: “Ready for a performance PK?” • ES: “¿Listo para un PK de actuación?”':zone.title.includes('Business')?'Creator: “Let me show you today’s featured products.” • FR: “Voici les produits vedettes.”':'Vendor: “Welcome to Creator District. Ask me about LIVE, products, or PK.”';setContext(zone.title,translated,[{label:'WATCH LIVE',run:()=>{dispatch('tryamm:live-open',{source:'streetverse-vendor'});say('LIVE screen opened') }},{label:'START PK',run:startPk},{label:'SHOP',run:()=>say('Walk to a glowing product display and press INTERACT.')},{label:'CLOSE',run:hideContext}])}
function startPk(){pkActive=true;pkLeft=0;pkRight=0;updateScore();dispatch('tryamm:pk-start',{mode:'1v1',arena:'creator-district'});say('PK LIVE started • 1v1 demo match')}
function endPk(){pkActive=false;dispatch('tryamm:pk-end',{left:pkLeft,right:pkRight});dispatch('tryamm:reel-highlight',{kind:'pk-result',left:pkLeft,right:pkRight});say(`PK ended ${pkLeft}-${pkRight} • Reel highlight event created`)}
function arenaAction(){setContext('TRYAMM PK / LIVE ARENA',pkActive?`LIVE PK is running • Team A ${pkLeft} : ${pkRight} Team B`:'Start a visible PK battle, send demo gifts, update the scoreboard, or capture a Reel highlight.',pkActive?[{label:'GIFT TEAM A',run:()=>{pkLeft++;updateScore();giftBurst();dispatch('tryamm:gift-sent',{team:'A',mode:'demo'});say('Demo gift sent to Team A')}},{label:'GIFT TEAM B',run:()=>{pkRight++;updateScore();giftBurst();dispatch('tryamm:gift-sent',{team:'B',mode:'demo'});say('Demo gift sent to Team B')}},{label:'END + REEL',run:endPk},{label:'CLOSE',run:hideContext}]:[{label:'START 1v1 PK',run:startPk},{label:'WATCH LIVE',run:()=>dispatch('tryamm:live-open',{source:'streetverse-arena'})},{label:'CLOSE',run:hideContext}])}
function portalAction(zone:Zone){setContext(zone.title,'Portal is active. Entering dispatches the connected world event and records the transition in StreetVerse.',[{label:'ENTER PORTAL',run:()=>{if(zone.eventName)dispatch(zone.eventName,{source:'streetverse-creator-district'});dispatch('tryamm:world-portal-used',{portalId:zone.id,title:zone.title});say(`Entering ${zone.title}`);hideContext()}},{label:'CLOSE',run:hideContext}])}
function productAction(zone:Zone){const p=products.find(x=>x.id===zone.productId);if(!p)return;setContext(p.name,`$${p.price.toFixed(2)} demo price • Pick it up, inspect it, carry it to the checkout surface, or put it back.`,p.held?[{label:'PUT DOWN',run:()=>{putDown();hideContext()}},{label:'CLOSE',run:hideContext}]:[{label:'PICK UP',run:()=>{pickup(p);hideContext()}},{label:'INSPECT',run:()=>{dispatch('tryamm:marketplace-item-inspected',{productId:p.id,name:p.name});say(`${p.name} inspected • product details opened`)}},{label:'CLOSE',run:hideContext}])}
function interact(){if(!currentZone){say('Walk closer to a store, vendor, product, checkout, arena, LIVE screen or portal.');return}if(currentZone.kind==='product'){productAction(currentZone);return}if(currentZone.kind==='checkout'){checkout(currentZone.storeId||'');return}if(currentZone.kind==='vendor'){vendorTalk(currentZone);return}if(currentZone.kind==='arena'){arenaAction();return}if(currentZone.kind==='live'){dispatch('tryamm:live-open',{source:'streetverse-live-screen'});say('Watching TRYAMM LIVE');return}if(currentZone.kind==='portal'){portalAction(currentZone);return}if(currentZone.kind==='store'){say(`${currentZone.title} • walk through the open front and explore the products inside.`);dispatch('tryamm:store-entered',{storeId:currentZone.storeId,title:currentZone.title});return}}
function hud(){const el=document.createElement('div');el.id='tryamm-visible-creator-controls';Object.assign(el.style,{position:'fixed',right:'14px',bottom:'88px',zIndex:'20006',display:'none',gap:'8px',flexDirection:'column',pointerEvents:'auto'});interactButton=document.createElement('button');interactButton.textContent='✋ INTERACT';Object.assign(interactButton.style,{padding:'12px 14px',borderRadius:'14px',border:'2px solid #fcd34d',background:'rgba(20,16,5,.94)',color:'#fff',fontWeight:'950',boxShadow:'0 0 24px #f59e0b55'});interactButton.onclick=interact;el.appendChild(interactButton);for(const [txt,ev] of [['🥽 QUEST','tryamm:metaquest-open'],['♿ ACCESS','tryamm:accessibility-open'],['🎥 REEL','tryamm:media-studio-open']]){const bt=document.createElement('button');bt.textContent=txt;Object.assign(bt.style,{padding:'10px 12px',borderRadius:'12px',border:'1px solid #67e8f9',background:'rgba(7,13,30,.9)',color:'#fff',fontWeight:'800'});bt.onclick=()=>window.dispatchEvent(new CustomEvent(ev));el.appendChild(bt)}document.body.appendChild(el);contextPanel=document.createElement('div');Object.assign(contextPanel.style,{position:'fixed',left:'50%',bottom:'24px',transform:'translateX(-50%)',zIndex:'20008',display:'none',width:'min(92vw,520px)',padding:'14px',borderRadius:'16px',border:'1px solid #67e8f9',background:'rgba(3,7,18,.96)',boxShadow:'0 20px 70px #000c',pointerEvents:'auto'});document.body.appendChild(contextPanel);toast=document.createElement('div');Object.assign(toast.style,{position:'fixed',left:'50%',top:'18%',transform:'translateX(-50%)',zIndex:'20009',display:'none',padding:'10px 14px',borderRadius:'12px',border:'1px solid #a7f3d0',background:'rgba(5,30,25,.94)',color:'#fff',fontWeight:'900',pointerEvents:'none'});document.body.appendChild(toast);return el}
function build(){root=document.createElement('div');root.id='tryamm-streetverse-creator-district';Object.assign(root.style,{position:'fixed',inset:'0',zIndex:'20003',pointerEvents:'none',display:'none'});document.body.appendChild(root);renderer=new THREE.WebGLRenderer({alpha:true,antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.2));renderer.setClearColor(0,0);renderer.outputColorSpace=THREE.SRGBColorSpace;root.appendChild(renderer.domElement);scene=new THREE.Scene();camera=new THREE.PerspectiveCamera(60,1,.1,700);arena();store(-18,19,'CREATOR MARKET • LIVE SHOP',0xf59e0b,'creator');store(18,19,'OMNI MARKET • PRODUCTS',0x22d3ee,'omni');store(-18,-32,'MUSIC / PERFORMANCE LIVE',0x8b5cf6,'music');store(18,-32,'BUSINESS PK SHOWROOM',0x10b981,'business');vendor(-13,14,'Creator Vendor • captions + translation',0xf59e0b,'vendor-creator');vendor(13,14,'Marketplace Host • LIVE',0x22d3ee,'vendor-market');vendor(-12,-25,'Music Creator • PK',0x8b5cf6,'vendor-music');vendor(12,-25,'Business Creator • PK',0x10b981,'vendor-business');portal(-30,-8,'PROPERTYVERSE PORTAL',0xf59e0b,'tryamm:propertyverse-open','portal-property');portal(30,-8,'SPACEVERSE PORTAL',0x3b82f6,'tryamm:spaceverse-open','portal-space');portal(0,-42,'TIME MACHINE PORTAL',0x8b5cf6,'tryamm:chrono-open','portal-time');giftBurst();for(let i=0;i<16;i++)vendor((Math.random()-.5)*42,34+Math.random()*14,`Pedestrian ${i+1}`,i%2?0x60a5fa:0xf472b6,`ped-${i}`);for(let i=0;i<8;i++){const car=b(2.2,.8,4,i%2?0x22d3ee:0xec4899,.82);car.position.set(-38+i*11,.6,49+(i%2)*6);car.userData.trafficIndex=i;scene.add(car);anim.push(car)}const resize=()=>{if(!renderer||!camera)return;const w=innerWidth,h=Math.max(innerHeight,430);camera.aspect=w/h;camera.updateProjectionMatrix();renderer.setSize(w,h,false)};addEventListener('resize',resize);resize();hud()}
function updateLabels(){if(!camera)return;for(const l of labels){const p=l.pos.clone().project(camera);const visible=p.z>-1&&p.z<1;l.el.style.display=visible?'block':'none';if(visible){l.el.style.left=`${(p.x*.5+.5)*innerWidth}px`;l.el.style.top=`${(-p.y*.5+.5)*innerHeight}px`}}}
function updateProximity(){const near=zones.map(z=>({z,d:dist(player,z)})).filter(x=>x.d<=x.z.radius).sort((a,b)=>a.d-b.d)[0]?.z||null;if(near?.id!==currentZone?.id){currentZone=near;if(interactButton)interactButton.textContent=near?`✋ ${near.kind==='product'?'PICK / INSPECT':near.kind==='checkout'?'CHECKOUT':near.kind==='portal'?'ENTER PORTAL':near.kind==='vendor'?'TALK':near.kind==='arena'?'PK / LIVE':near.kind==='live'?'WATCH LIVE':'ENTER STORE'}`:'✋ INTERACT'}if(heldProduct){heldProduct.mesh.position.set(player.x,1.4,player.z-1.2)}}
function animate(){if(active&&renderer&&scene&&camera){const t=performance.now()/1000;player.x=THREE.MathUtils.lerp(player.x,targetPlayer.x,.08);player.z=THREE.MathUtils.lerp(player.z,targetPlayer.z,.08);camera.position.lerp(new THREE.Vector3(player.x+19,14,player.z+25),.08);camera.lookAt(player.x,2.5,player.z-8);anim.forEach((o,i)=>{if(o.geometry instanceof THREE.TorusGeometry)o.rotation.z=t*.25+i*.03;if((o as any).userData?.baseY!==undefined)o.position.y=(o as any).userData.baseY+Math.sin(t*2+(o as any).userData.phase)*.8;if((o as any).userData?.trafficIndex!==undefined){o.position.x+=Math.sin(t*.55+i)*.012;o.position.z+=Math.cos(t*.31+i)*.006}});updateProximity();renderer.render(scene,camera);updateLabels()}raf=requestAnimationFrame(animate)}
export function installStreetVerseCreatorDistrict3D(){if(installed||typeof window==='undefined')return;installed=true;build();const controls=document.getElementById('tryamm-visible-creator-controls');const start=()=>{active=true;if(root)root.style.display='block';if(controls)controls.style.display='flex'};const stop=()=>{active=false;if(root)root.style.display='none';if(controls)controls.style.display='none';hideContext()};window.addEventListener('tryamm:streetverse-enter',start);window.addEventListener('tryamm:streetverse-exit',stop);window.addEventListener('tryamm:streetverse-player-position',(e:Event)=>{const d=(e as CustomEvent<{x?:number;z?:number}>).detail||{};if(Number.isFinite(d.x)&&Number.isFinite(d.z))targetPlayer={x:Number(d.x),z:Number(d.z)}});window.addEventListener('tryamm:gift-sent',giftBurst);window.addEventListener('tryamm:pk-score',(e:Event)=>{const d=(e as CustomEvent<{left?:number;right?:number}>).detail||{};pkLeft=Number(d.left??pkLeft);pkRight=Number(d.right??pkRight);updateScore()});window.addEventListener('keydown',(e)=>{if(!active)return;if(e.key.toLowerCase()==='e')interact();if(e.key.toLowerCase()==='q')putDown()});window.dispatchEvent(new CustomEvent('tryamm:creator-district-ready',{detail:{pkArena:true,liveScreen:true,walkInStoreInteriors:4,storefronts:4,products:8,pickupPutdown:true,checkoutSurfaces:4,vendorDialog:true,portals:3,portalProximity:true,traffic:8,pedestrians:16,questControl:true,accessibilityControl:true,translatedVendorDialog:true,demoGiftScoring:true,reelHighlightEvents:true}}));animate()}
