type StepId='walk'|'drive'|'talk'|'enter'|'mission'|'waypoint'|'objective'|'xp'|'save'|'reel'|'reload'
type Step={id:StepId;label:string;done:boolean;at?:string;evidence?:string}
type State={version:1;steps:Step[];startedAt:string;updatedAt:string;completedAt?:string;reloadArmed?:boolean;sessionId:string}
const KEY='tryamm_streetverse_playable_milestone_v1';const ORDER:StepId[]=['walk','drive','talk','enter','mission','waypoint','objective','xp','save','reel','reload'];let installed=false
const labels:Record<StepId,string>={walk:'Walk',drive:'Drive',talk:'Talk to resident',enter:'Enter building',mission:'Accept mission',waypoint:'Follow waypoint',objective:'Complete objective',xp:'Earn XP',save:'Save progress',reel:'Record Reel',reload:'Reload and retain progress'}
function now(){return new Date().toISOString()}function sid(){return `sv_${Date.now().toString(36)}_${Math.random().toString(36).slice(2,8)}`}
function fresh():State{return {version:1,steps:ORDER.map(id=>({id,label:labels[id],done:false})),startedAt:now(),updatedAt:now(),sessionId:sid()}}
function read():State{try{const raw=localStorage.getItem(KEY);if(!raw)return fresh();const s=JSON.parse(raw) as State;return {...s,steps:ORDER.map(id=>s.steps?.find(x=>x.id===id)||{id,label:labels[id],done:false})}}catch{return fresh()}}
function write(s:State){s.updatedAt=now();localStorage.setItem(KEY,JSON.stringify(s));publish(s);return s}
function publish(s=read()){const done=s.steps.filter(x=>x.done).length;const complete=done===ORDER.length;window.dispatchEvent(new CustomEvent('tryamm:streetverse-milestone-state',{detail:{...s,done,total:ORDER.length,percent:Math.round(done/ORDER.length*100),complete,next:s.steps.find(x=>!x.done)?.id}}));if(complete&&!s.completedAt){s.completedAt=now();localStorage.setItem(KEY,JSON.stringify(s));window.dispatchEvent(new CustomEvent('tryamm:streetverse-playable-milestone-complete',{detail:{completedAt:s.completedAt,steps:s.steps,defensibleScope:'StreetVerse visible playable production milestone'}}))}}
function mark(id:StepId,evidence:string){const s=read();const idx=ORDER.indexOf(id);const priorOk=idx===0||s.steps.slice(0,idx).every(x=>x.done);if(!priorOk){window.dispatchEvent(new CustomEvent('tryamm:streetverse-milestone-out-of-order',{detail:{attempted:id,next:s.steps.find(x=>!x.done)?.id}}));return s}const step=s.steps[idx];if(!step.done){step.done=true;step.at=now();step.evidence=evidence;write(s)}else publish(s);return s}
function on(name:string,id:StepId,evidence:string){window.addEventListener(name,()=>mark(id,evidence))}
function detectMovement(e:Event){const d=(e as CustomEvent<any>).detail||{};const speed=Math.abs(Number(d.speed||d.velocity||0));if(speed>0||d.moved===true)mark('walk','player movement event')}
function armReload(){const s=read();if(s.steps.find(x=>x.id==='save')?.done&&s.steps.find(x=>x.id==='reel')?.done){s.reloadArmed=true;write(s)}}
export function getStreetVerseMilestoneReport(){const s=read();return {...s,done:s.steps.filter(x=>x.done).length,total:ORDER.length,complete:s.steps.every(x=>x.done)}}
export function resetStreetVerseMilestone(){const s=fresh();write(s);return s}
export function installStreetVersePlayableMilestoneRuntime(){if(installed||typeof window==='undefined')return;installed=true;const existing=read();const previousSession=existing.sessionId;if(existing.reloadArmed&&previousSession){existing.sessionId=sid();existing.reloadArmed=false;write(existing);mark('reload','milestone state retained across page session reload')}else write(existing);window.addEventListener('tryamm:streetverse-player-move',detectMovement);on('tryamm:streetverse-walk','walk','walk interaction');on('tryamm:streetverse-transport-state','drive','vehicle/transport entered');on('tryamm:streetverse-npc-reaction','talk','resident dialogue/reaction');on('tryamm:streetverse-interior-enter','enter','interior entered');on('tryamm:streetverse-activity-active','mission','mission/activity accepted');on('tryamm:construct:targets','waypoint','Construct waypoint target emitted');on('tryamm:streetverse-activity-complete','objective','mission/activity completed');on('tryamm:streetverse-xp','xp','XP state updated');on('tryamm:streetverse-save-complete','save','StreetVerse save confirmed');on('tryamm:reel-saved','reel','Reel saved');on('tryamm:reel-recorded','reel','Reel recording completed');window.addEventListener('tryamm:streetverse-milestone-save',()=>{localStorage.setItem(KEY,JSON.stringify(read()));mark('save','milestone save persisted')});window.addEventListener('tryamm:streetverse-milestone-reel',()=>mark('reel','Reel checkpoint confirmed'));window.addEventListener('tryamm:streetverse-milestone-arm-reload',armReload);window.addEventListener('tryamm:streetverse-milestone-report',()=>publish(read()));window.addEventListener('beforeunload',armReload);queueMicrotask(()=>{publish(read());window.dispatchEvent(new CustomEvent('tryamm:streetverse-playable-milestone-ready',{detail:{orderedChecklist:ORDER,persistent:true,reloadVerification:true}}))})}