let installed=false
const ID='tryamm-chicago-transit-airport-missions'
const KEY='tryamm.chicago.transit-airport-missions.v1'
type Mission={id:string;title:string;area:string;brief:string;steps:string[];xp:number;credits:number}
const MISSIONS:Mission[]=[
{id:'blue-night-watch',title:'Blue Line Night Watch',area:'Blue Line',brief:'Ride the line, observe rider issues, report unsafe conduct, and help keep a car moving safely.',steps:['Board a Blue Line train','Check three rail cars','Report smoking or prohibited sales','Assist a rider who requests help','Reach the next staffed station'],xp:220,credits:120},
{id:'red-rider-assist',title:'Red Line Rider Assist',area:'Red Line',brief:'Handle a busy train with vendors, solicitation, disruptive behavior and riders needing assistance.',steps:['Walk two train cars','Talk with a vendor NPC','Respond to a solicitation complaint','Check on a sleeping rider without harassment','Report a safety incident'],xp:240,credits:130},
{id:'code-of-conduct',title:'Code of Conduct Patrol',area:'CTA Rail',brief:'A public-safety mission focused on de-escalation, reporting and lawful enforcement.',steps:['Identify prohibited smoking','Identify prohibited alcohol use','Document prohibited onboard sales','Call for transit staff/police when needed','Complete incident report'],xp:260,credits:140},
{id:'transit-task-force',title:'Transit Task Force Shift',area:'Red + Blue Lines',brief:'Join fictionalized transit officers on a multi-station safety shift; arrests occur only through NPC law-enforcement logic after an offense is established.',steps:['Brief at station','Ride with patrol NPCs','Respond to a reported offense','De-escalate the scene','Officer NPC resolves citation/removal/arrest outcome'],xp:300,credits:160},
{id:'ord-arrivals',title:'O’Hare Arrival Run',area:'O’Hare / Blue Line',brief:'Meet arriving travelers and move them from airport concourse to the Blue Line and downtown.',steps:['Reach O’Hare terminal concourse','Help traveler find CTA train','Handle baggage assistance event','Board Blue Line','Deliver traveler downtown'],xp:280,credits:150},
{id:'ord-lost-bag',title:'O’Hare Lost Bag',area:'O’Hare',brief:'Trace a missing bag through terminal checkpoints and return it to its owner.',steps:['Take lost-bag report','Check terminal clue','Check ATS/connection clue','Locate bag','Return and close report'],xp:250,credits:135},
{id:'ord-night-shift',title:'O’Hare Night Shift',area:'O’Hare / Blue Line',brief:'Late-night airport-to-city service mission with delayed travelers and a safety call.',steps:['Start at O’Hare station','Assist delayed passenger','Respond to train-car complaint','Transfer traveler safely','Finish downtown'],xp:320,credits:175},
{id:'mdw-orange-run',title:'Midway Orange Run',area:'Midway / Orange Line',brief:'Guide passengers from the terminal walkway to the Orange Line and into the Loop.',steps:['Reach Midway terminal','Guide passengers to station','Board Orange Line','Handle onboard rider event','Arrive Loop'],xp:270,credits:145},
{id:'mdw-crew-turn',title:'Midway Crew Turn',area:'Midway',brief:'Airport operations mission involving passenger assistance, delivery timing and transit connection.',steps:['Pick up operations packet','Make terminal delivery','Assist traveler connection','Reach Orange Line platform','Complete return run'],xp:260,credits:140}
]
const RIDERS=[
{kind:'vendor',examples:['socks','body oils'],interaction:'talk / report prohibited onboard sale'},
{kind:'restricted-goods vendor',examples:['cannabis','cigarettes','alcohol'],interaction:'do not purchase; report prohibited sale/use'},
{kind:'solicitor',examples:['asking riders for money'],interaction:'respond respectfully; report if needed'},
{kind:'sleeping rider',examples:['sleeping or exhausted passenger'],interaction:'welfare check / offer help; do not criminalize homelessness'},
{kind:'commuter',examples:['airport worker','student','tourist','night-shift worker'],interaction:'conversation / directions / assistance'},
{kind:'law enforcement NPC',examples:['CPD transit officer','Cook County transit task-force partner'],interaction:'patrol / de-escalation / lawful enforcement outcome'}]
function active(){const h=location.hash.replace(/^#/,'');return h==='/streetverse'||h==='/city'}
function emit(name:string,detail:any){window.dispatchEvent(new CustomEvent(name,{detail}))}
function read(){try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch{return {}}}
function save(v:any){try{localStorage.setItem(KEY,JSON.stringify(v))}catch{}}
function mount(){if(!active()){document.getElementById(ID)?.remove();return}if(document.getElementById(ID))return;const root=document.createElement('div');root.id=ID;root.style.cssText='position:fixed;right:12px;bottom:58px;z-index:2147482500;pointer-events:auto;font-family:Inter,Arial,sans-serif';const btn=document.createElement('button');btn.textContent='🚆 TRAIN + ✈️ AIRPORT MISSIONS';btn.style.cssText='padding:9px 12px;border-radius:999px;border:1px solid #6aaee8;background:#07131df0;color:#fff;font-size:10px;font-weight:900;cursor:pointer';const panel=document.createElement('div');panel.style.cssText='display:none;margin-top:7px;width:min(92vw,430px);max-height:66vh;overflow:auto;padding:11px;border-radius:15px;border:1px solid #36546a;background:#050b12f5;color:#fff;box-shadow:0 20px 60px #000c';panel.innerHTML=`<b>CHICAGO TRANSIT + AIRPORT LIFE</b><div style="font-size:9px;opacity:.68;margin:4px 0 8px">Red/Blue Line rider-life • safety • O’Hare • Midway • Orange Line</div>${MISSIONS.map(m=>`<button data-m="${m.id}" style="display:block;width:100%;text-align:left;margin:5px 0;padding:8px;border:1px solid #31495b;border-radius:9px;background:#0a131c;color:#fff;cursor:pointer"><b>${m.title}</b> <span style="font-size:9px;color:#9bdcff">${m.area}</span><br><span style="font-size:9px;opacity:.7">${m.brief}</span></button>`).join('')}`;btn.onclick=()=>panel.style.display=panel.style.display==='none'?'block':'none';panel.querySelectorAll('[data-m]').forEach(n=>n.addEventListener('click',()=>{const id=(n as HTMLElement).dataset.m;const m=MISSIONS.find(x=>x.id===id);if(!m)return;const state=read();state.active={id:m.id,step:0,startedAt:new Date().toISOString()};save(state);emit('tryamm:streetverse-mission-start',{missionId:m.id,title:m.title,area:m.area,steps:m.steps,xp:m.xp,credits:m.credits,source:'Chicago transit-airport missions'});emit('tryamm:accessibility-announce',{text:`Mission started: ${m.title}. ${m.steps[0]}`})}));root.append(btn,panel);document.body.appendChild(root);emit('tryamm:streetverse-transit-life-ready',{lines:['Blue Line','Red Line','Orange Line'],airports:['O’Hare','Midway'],riderArchetypes:RIDERS,missions:MISSIONS,designRules:['no player drug/alcohol sales mechanic','no glamorized illegal vending','homeless riders treated as people with welfare/help interactions','law-enforcement outcomes use de-escalation and offense-based NPC logic','fictional gameplay inspired by Chicago transit, not live CTA operations']})}
export function installStreetVerseChicagoTransitAirportMissionsRuntime(){if(installed||typeof window==='undefined'||typeof document==='undefined')return;installed=true;const sync=()=>requestAnimationFrame(mount);window.addEventListener('hashchange',sync);window.addEventListener('tryamm:streetverse-enter',sync);if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',sync,{once:true});else sync()}
