type Cue='enter'|'mission'|'scan'|'route'|'complete'|'danger'|'portal'|'benny'|'ariel'
type AudioState={enabled:boolean;music:boolean;sfx:boolean;voice:boolean;master:number;musicLevel:number;sfxLevel:number;voiceLevel:number}
const KEY='tryamm_living_audio_v1'
let installed=false,ctx:AudioContext|null=null,ambience:OscillatorNode|null=null,ambienceGain:GainNode|null=null
const defaults:AudioState={enabled:true,music:true,sfx:true,voice:true,master:.72,musicLevel:.25,sfxLevel:.7,voiceLevel:.9}
function state():AudioState{try{return {...defaults,...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{return defaults}}
function save(s:AudioState){try{localStorage.setItem(KEY,JSON.stringify(s))}catch{};window.dispatchEvent(new CustomEvent('tryamm:audio-state',{detail:s}))}
function audio(){if(!ctx)ctx=new AudioContext();return ctx}
function tone(freq:number,duration=.12,volume=.1,type:OscillatorType='sine',delay=0){const s=state();if(!s.enabled||!s.sfx)return;const c=audio(),o=c.createOscillator(),g=c.createGain(),t=c.currentTime+delay;o.type=type;o.frequency.setValueAtTime(freq,t);g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(Math.max(.0001,volume*s.master*s.sfxLevel),t+.015);g.gain.exponentialRampToValueAtTime(.0001,t+duration);o.connect(g).connect(c.destination);o.start(t);o.stop(t+duration+.03)}
function cue(kind:Cue){if(kind==='enter'){tone(110,.5,.08,'sine');tone(220,.35,.06,'sine',.08)}if(kind==='mission'){tone(261.63,.14,.13,'triangle');tone(392,.18,.1,'triangle',.13)}if(kind==='scan'){[440,660,880].forEach((f,i)=>tone(f,.1,.08,'sine',i*.07))}if(kind==='route'){tone(523,.08,.07,'triangle');tone(659,.08,.06,'triangle',.09)}if(kind==='complete'){[261.63,392,440,523.25].forEach((f,i)=>tone(f,.22,.12,'triangle',i*.12))}if(kind==='danger'){tone(92,.28,.16,'sawtooth');tone(78,.28,.12,'sawtooth',.22)}if(kind==='portal'){tone(146,.6,.07,'sine');tone(587,.45,.06,'sine',.18)}if(kind==='benny'){tone(740,.06,.05,'sine');tone(980,.08,.04,'sine',.055)}if(kind==='ariel'){tone(196,.12,.06,'triangle');tone(293.66,.15,.05,'triangle',.1)}}
function startAmbience(){const s=state();if(!s.enabled||!s.music||ambience)return;const c=audio();ambience=c.createOscillator();ambienceGain=c.createGain();ambience.type='sine';ambience.frequency.value=55;ambienceGain.gain.value=.008*s.master*s.musicLevel;ambience.connect(ambienceGain).connect(c.destination);ambience.start()}
function stopAmbience(){try{ambience?.stop()}catch{};ambience=null;ambienceGain=null}
function speak(text:string,who:'Benny'|'Ari’el'='Benny'){const s=state();if(!s.enabled||!s.voice||!('speechSynthesis'in window))return;const u=new SpeechSynthesisUtterance(text);u.rate=who==='Benny'?1.04:.94;u.pitch=who==='Benny'?1.05:.86;u.volume=Math.min(1,s.master*s.voiceLevel);speechSynthesis.cancel();speechSynthesis.speak(u);window.dispatchEvent(new CustomEvent('tryamm:audio-caption',{detail:{speaker:who,text}}))}
function unlock(){const c=audio();if(c.state==='suspended')void c.resume();startAmbience();document.removeEventListener('pointerdown',unlock)}
export function installStreetVerseLivingAudioRuntime(){if(installed||typeof window==='undefined')return;installed=true;document.addEventListener('pointerdown',unlock,{once:true});window.addEventListener('tryamm:streetverse-enter',()=>{cue('enter');startAmbience()});window.addEventListener('tryamm:streetverse-exit',stopAmbience);window.addEventListener('tryamm:story-mission-active',(e:Event)=>{const m=(e as CustomEvent<any>).detail?.mission;if(!m)return;cue('mission');speak(`${m.title}. ${m.objective}`,'Benny')});window.addEventListener('tryamm:construct:scan-result',()=>cue('scan'));window.addEventListener('tryamm:construct:route',()=>cue('route'));window.addEventListener('tryamm:story-mission-complete',()=>cue('complete'));window.addEventListener('tryamm:mission-completed',()=>cue('complete'));window.addEventListener('tryamm:benny:utterance',(e:Event)=>{const text=(e as CustomEvent<any>).detail?.text;if(text){cue('benny');speak(String(text),'Benny')}});window.addEventListener('tryamm:ariel:utterance',(e:Event)=>{const text=(e as CustomEvent<any>).detail?.text;if(text){cue('ariel');speak(String(text),'Ari’el')}});window.addEventListener('tryamm:audio-cue',(e:Event)=>{const k=(e as CustomEvent<{cue?:Cue}>).detail?.cue;if(k)cue(k)});window.addEventListener('tryamm:audio-settings',(e:Event)=>save({...state(),...((e as CustomEvent<Partial<AudioState>>).detail||{})}));save(state());window.dispatchEvent(new CustomEvent('tryamm:living-audio-ready',{detail:{adaptive:true,proceduralFallback:true,spatialReady:true,captions:true,userControls:true,iosUnlockOnInteraction:true}}))}
