const WORLD_SAVE='tryamm.streetverse.omniworld.v1'
const MILESTONE='tryamm_streetverse_playable_milestone_v1'
let installed=false,observer:MutationObserver|null=null,lastWorldSave='',missionAccepted=false,xpAwardedFor=''
const mission={id:'market',label:'Marketplace Delivery',x:48,z:-28}
function emit(name:string,detail:any={}){window.dispatchEvent(new CustomEvent(name,{detail}))}
function report(){try{return JSON.parse(localStorage.getItem(MILESTONE)||'{}')}catch{return {}}}
function nextStep(){const s=report();return s?.steps?.find((x:any)=>!x.done)?.id||'complete'}
function worldVisible(){return document.body.textContent?.includes('STREETVERSE • CINEMATIC OMNI DISTRICT')||false}
function ensureGuide(){let el=document.getElementById('sv-completion-guide') as HTMLDivElement|null;if(el||!worldVisible())return;el=document.createElement('div');el.id='sv-completion-guide';Object.assign(el.style,{position:'fixed',right:'14px',bottom:'214px',zIndex:'2147482600',width:'min(310px,78vw)',padding:'10px 12px',borderRadius:'14px',background:'rgba(3,10,18,.9)',border:'1px solid rgba(255,215,92,.65)',color:'#fff',font:'700 11px system-ui',boxShadow:'0 10px 30px rgba(0,0,0,.45)'});document.body.appendChild(el);renderGuide()}
function renderGuide(){const el=document.getElementById('sv-completion-guide');if(!el)return;const n=nextStep();const prompts:Record<string,string>={walk:'Walk with the arrows/WASD.',drive:'Approach a car and tap INTERACT / ENTER.',talk:'Exit, approach a resident and interact.',enter:'Approach a business portal and enter.',mission:'Accept the next mission.',waypoint:'Mission route is being sent to the HUD.',objective:'Follow the waypoint to the glowing mission beacon.',xp:'Objective complete — XP is being verified.',save:'Keep playing briefly while progress saves.',reel:'Tap 🎥 REEL, record/import a clip, then finish the capture.',reload:'Reload StreetVerse once to verify retained progress.',complete:'Playable milestone checklist passed.'};el.innerHTML=`<div style="color:#ffd75c;letter-spacing:.08em">COMPLETION RUN</div><div style="margin-top:5px">Next: <b>${n.toUpperCase()}</b></div><div style="margin-top:4px;opacity:.82">${prompts[n]||''}</div>${n==='mission'?'<button id="sv-accept-mission" style="margin-top:8px;border:1px solid #ffd75c;border-radius:999px;padding:7px 10px;background:#2a1b05;color:#ffe38c;font-weight:900">ACCEPT MARKETPLACE DELIVERY</button>':''}`;document.getElementById('sv-accept-mission')?.addEventListener('click',acceptMission,{once:true})}
function acceptMission(){if(missionAccepted)return;missionAccepted=true;emit('tryamm:streetverse-activity-active',{type:mission.id,label:mission.label,objective:'Travel to the Marketplace Delivery beacon.',checkpoint:0});setTimeout(()=>emit('tryamm:construct:targets',{targets:[{id:`mission-${mission.id}`,kind:'mission',title:mission.label,x:mission.x,z:mission.z}]}),40);renderGuide()}
function scanText(){if(!worldVisible()){document.getElementById('sv-completion-guide')?.remove();return}ensureGuide();const text=document.body.textContent||'',next=nextStep();if(next==='drive'&&text.includes('DRIVING'))emit('tryamm:streetverse-transport-state',{mode:'car',source:'live-world'});if(next==='talk'&&/StreetVerse resident \d+:/.test(text)){emit('tryamm:streetverse-npc-reaction',{id:'live-resident',mood:'friendly',line:'Live resident interaction',action:'talk'});}
if(next==='enter'&&(text.includes('IN BUSINESS')||text.includes('Entered All American')||text.includes('Entered Creator Studio')||text.includes('Entered Holo Ads'))){emit('tryamm:streetverse-interior-enter',{kind:'business',source:'live-world'})}
if(next==='objective'&&/(Marketplace Delivery|Creator Studio Session|Marina Charter|Holo Ads Campaign|All American Network) complete/.test(text)){const match=text.match(/(Marketplace Delivery|Creator Studio Session|Marina Charter|Holo Ads Campaign|All American Network) complete/);const label=match?.[1]||'StreetVerse mission';emit('tryamm:streetverse-activity-complete',{type:label,source:'live-world'});if(xpAwardedFor!==label){xpAwardedFor=label;setTimeout(()=>emit('tryamm:streetverse-xp-gain',{amount:100,reason:`${label} completion`}),50)}}
if(next==='reel'&&text.includes('Capture ready. Add effects, render the final Reel'))emit('tryamm:reel-recorded',{source:'streetverse-media-studio'});renderGuide()}
function watchSave(){const raw=localStorage.getItem(WORLD_SAVE)||'';if(raw&&raw!==lastWorldSave){lastWorldSave=raw;if(nextStep()==='save')emit('tryamm:streetverse-save-complete',{key:WORLD_SAVE,source:'live-world-autosave'})}}
function detectWalk(e:Event){if(!worldVisible()||nextStep()!=='walk')return;if(e instanceof KeyboardEvent){if(['w','a','s','d','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.key))emit('tryamm:streetverse-player-move',{moved:true,source:'live-input'})}else emit('tryamm:streetverse-player-move',{moved:true,source:'live-pointer-input'})}
export function installStreetVerseCompletionBridgeRuntime(){if(installed||typeof window==='undefined')return;installed=true;lastWorldSave=localStorage.getItem(WORLD_SAVE)||'';document.addEventListener('keydown',detectWalk,true);document.addEventListener('pointerdown',e=>{const target=e.target as HTMLElement|null;if(target?.closest?.('#sv-completion-guide'))return;if(target?.textContent&&['▲','▼','◀','▶'].includes(target.textContent.trim()))detectWalk(e)},true);observer=new MutationObserver(scanText);observer.observe(document.body,{subtree:true,childList:true,characterData:true});setInterval(()=>{scanText();watchSave()},900);window.addEventListener('tryamm:streetverse-milestone-state',renderGuide);window.addEventListener('tryamm:media-studio-open',()=>setTimeout(scanText,100));queueMicrotask(()=>{scanText();emit('tryamm:streetverse-completion-bridge-ready',{liveWorldEvidence:true,missionAcceptance:true,autosaveEvidence:true,reelCaptureEvidence:true})})}