import * as THREE from 'three'

const mat=(color:number,emissive=0)=>new THREE.MeshStandardMaterial({color,roughness:.72,metalness:.12,emissive:emissive||color,emissiveIntensity:emissive?0.45:0})
function textTexture(label:string,bg:string,fg:string){const canvas=document.createElement('canvas');canvas.width=768;canvas.height=256;const c=canvas.getContext('2d')!;c.fillStyle=bg;c.fillRect(0,0,768,256);c.fillStyle=fg;c.font='900 58px system-ui,sans-serif';c.textAlign='center';c.textBaseline='middle';c.fillText(label,384,128);const t=new THREE.CanvasTexture(canvas);t.colorSpace=THREE.SRGBColorSpace;return t}
function sign(scene:THREE.Scene,label:string,x:number,y:number,z:number,ry=0,bg='#07131d',fg='#65e9ff'){const tex=textTexture(label,bg,fg);const m=new THREE.Mesh(new THREE.PlaneGeometry(8,2.65),new THREE.MeshBasicMaterial({map:tex,side:THREE.DoubleSide}));m.position.set(x,y,z);m.rotation.y=ry;scene.add(m);return m}
function bench(scene:THREE.Scene,x:number,z:number,ry=0){const g=new THREE.Group();const wood=mat(0x7a5236),metal=mat(0x2d333a);for(const y of [.65,1.05]){const slat=new THREE.Mesh(new THREE.BoxGeometry(3.4,.18,.35),wood);slat.position.y=y;g.add(slat)}for(const sx of [-1.35,1.35]){const leg=new THREE.Mesh(new THREE.BoxGeometry(.18,.75,.5),metal);leg.position.set(sx,.35,0);g.add(leg)}g.position.set(x,0,z);g.rotation.y=ry;scene.add(g)}
function hydrant(scene:THREE.Scene,x:number,z:number){const g=new THREE.Group();const red=mat(0xc9303b);const body=new THREE.Mesh(new THREE.CylinderGeometry(.28,.32,.8,10),red);body.position.y=.4;const cap=new THREE.Mesh(new THREE.SphereGeometry(.3,10,8,0,Math.PI*2,0,Math.PI/2),red);cap.position.y=.82;g.add(body,cap);g.position.set(x,0,z);scene.add(g)}
function shelter(scene:THREE.Scene,x:number,z:number,ry=0){const g=new THREE.Group();const dark=mat(0x30363d),glass=new THREE.MeshStandardMaterial({color:0x8fdfff,transparent:true,opacity:.28,roughness:.2,metalness:.15});const roof=new THREE.Mesh(new THREE.BoxGeometry(5.5,.2,2),dark);roof.position.y=3.1;g.add(roof);for(const sx of [-2.5,2.5]){const post=new THREE.Mesh(new THREE.BoxGeometry(.12,3,.12),dark);post.position.set(sx,1.5,0);g.add(post)}const pane=new THREE.Mesh(new THREE.BoxGeometry(5,.08,2.4),glass);pane.position.set(0,1.6,-.9);pane.rotation.x=Math.PI/2;g.add(pane);g.position.set(x,0,z);g.rotation.y=ry;scene.add(g)}
function mural(scene:THREE.Scene,x:number,y:number,z:number,ry:number,colors:[number,number,number]){const c=document.createElement('canvas');c.width=512;c.height=512;const g=c.getContext('2d')!;const hex=(n:number)=>`#${n.toString(16).padStart(6,'0')}`;g.fillStyle=hex(colors[0]);g.fillRect(0,0,512,512);g.fillStyle=hex(colors[1]);g.beginPath();g.arc(150,210,120,0,Math.PI*2);g.fill();g.fillStyle=hex(colors[2]);g.beginPath();g.moveTo(250,30);g.lineTo(490,250);g.lineTo(270,490);g.closePath();g.fill();g.fillStyle='#fff';g.font='900 56px system-ui';g.fillText('STREETVERSE',42,454);const tex=new THREE.CanvasTexture(c);tex.colorSpace=THREE.SRGBColorSpace;const mesh=new THREE.Mesh(new THREE.PlaneGeometry(7,7),new THREE.MeshBasicMaterial({map:tex,side:THREE.DoubleSide}));mesh.position.set(x,y,z);mesh.rotation.y=ry;scene.add(mesh)}
function raceGate(scene:THREE.Scene,x:number,z:number,ry=0){const g=new THREE.Group();const glow=new THREE.MeshStandardMaterial({color:0xffd34f,emissive:0xff9f1c,emissiveIntensity:.9,roughness:.35});for(const sx of [-3.5,3.5]){const p=new THREE.Mesh(new THREE.BoxGeometry(.35,5,.35),glow);p.position.set(sx,2.5,0);g.add(p)}const top=new THREE.Mesh(new THREE.BoxGeometry(7.35,.45,.45),glow);top.position.y=5;g.add(top);g.position.set(x,0,z);g.rotation.y=ry;scene.add(g)}
function storefront(scene:THREE.Scene,label:string,x:number,z:number,color:number,ry=0){const g=new THREE.Group();const base=new THREE.Mesh(new THREE.BoxGeometry(10,4.8,1.2),mat(0x252d36));base.position.y=2.4;g.add(base);const glass=new THREE.Mesh(new THREE.BoxGeometry(8.4,2.5,.12),new THREE.MeshStandardMaterial({color:0x77c7df,transparent:true,opacity:.5,metalness:.3,roughness:.16}));glass.position.set(0,2.1,.66);g.add(glass);const awning=new THREE.Mesh(new THREE.BoxGeometry(9,.32,2.4),mat(color,true?color:0));awning.position.set(0,4.25,1.15);awning.rotation.x=-.2;g.add(awning);const tex=textTexture(label,'#081018','#ffffff');const name=new THREE.Mesh(new THREE.PlaneGeometry(7,1.3),new THREE.MeshBasicMaterial({map:tex,side:THREE.DoubleSide}));name.position.set(0,3.45,.68);g.add(name);g.position.set(x,0,z);g.rotation.y=ry;scene.add(g)}
function streetSign(scene:THREE.Scene,label:string,x:number,z:number,ry=0){const g=new THREE.Group();const pole=new THREE.Mesh(new THREE.CylinderGeometry(.08,.1,3.2,8),mat(0x444b52));pole.position.y=1.6;g.add(pole);const tex=textTexture(label,'#174f2d','#ffffff');const board=new THREE.Mesh(new THREE.PlaneGeometry(3.6,.95),new THREE.MeshBasicMaterial({map:tex,side:THREE.DoubleSide}));board.position.y=3;g.add(board);g.position.set(x,0,z);g.rotation.y=ry;scene.add(g)}
function detailedCar(scene:THREE.Scene,x:number,z:number,color:number,ry=0){const g=new THREE.Group();const shell=mat(color);const lower=new THREE.Mesh(new THREE.BoxGeometry(5.2,.9,2.25),shell);lower.position.y=.9;g.add(lower);const cabin=new THREE.Mesh(new THREE.BoxGeometry(2.7,.9,1.9),new THREE.MeshStandardMaterial({color:0x8fc5df,metalness:.55,roughness:.2}));cabin.position.set(-.25,1.7,0);g.add(cabin);const bumper=new THREE.Mesh(new THREE.BoxGeometry(.25,.35,2.15),mat(0x20252a));bumper.position.set(2.7,.72,0);g.add(bumper);const rear=bumper.clone();rear.position.x=-2.7;g.add(rear);for(const sx of [-1.65,1.65])for(const sz of [-1.08,1.08]){const wheel=new THREE.Mesh(new THREE.CylinderGeometry(.48,.48,.34,16),mat(0x0f1114));wheel.rotation.x=Math.PI/2;wheel.position.set(sx,.48,sz);g.add(wheel)}for(const zz of [-.72,.72]){const h=new THREE.Mesh(new THREE.BoxGeometry(.09,.28,.38),new THREE.MeshBasicMaterial({color:0xfff2c8}));h.position.set(2.62,1,zz);g.add(h);const t=h.clone();(t.material as THREE.MeshBasicMaterial)=new THREE.MeshBasicMaterial({color:0xff3552});t.position.x=-2.62;g.add(t)}g.position.set(x,0,z);g.rotation.y=ry;scene.add(g)}

export function addStreetVerseOriginalCityArt(scene:THREE.Scene){
 sign(scene,'ALL AMERICAN MARKETPLACE',42,6.5,-18,0,'#07131d','#63edff');sign(scene,'ANIYAH 64 TRACK STUDIO',-42,6.5,-24,0,'#25102f','#ff91ff');sign(scene,'ALL AMERICAN NETWORK',38,7.2,44,Math.PI,'#2c2105','#ffd96b');sign(scene,'CHICAGO AFTER DARK',-38,7.2,44,Math.PI,'#2a071b','#ff63b7');sign(scene,'TRYAMM • ENTER THE WORLD',0,11,-70,0,'#06121c','#8df5ff')
 mural(scene,-69,7,-60,Math.PI/2,[0x16283b,0xff5d8f,0xffd15b]);mural(scene,69,8,60,-Math.PI/2,[0x0e2530,0x43d9c3,0x816dff])
 for(const [x,z,r] of [[-18,-58,0],[18,-58,0],[-18,58,Math.PI],[18,58,Math.PI]] as [number,number,number][])shelter(scene,x,z,r)
 for(const [x,z,r] of [[-22,-20,0],[22,-20,0],[-22,20,Math.PI],[22,20,Math.PI]] as [number,number,number][])bench(scene,x,z,r)
 for(const [x,z] of [[-10,-10],[10,-10],[-10,10],[10,10],[-58,10],[58,-10]] as [number,number][])hydrant(scene,x,z)
 raceGate(scene,0,48,0);raceGate(scene,48,-48,Math.PI/2);raceGate(scene,0,0,0);raceGate(scene,48,48,Math.PI/2)
 storefront(scene,'OMNI CAFE',-24,-70,0x49d7c3);storefront(scene,'HOLO MUSIC',24,-70,0xa36cff);storefront(scene,'CREATOR MARKET',-24,70,0xffc65b,Math.PI);storefront(scene,'STREETVERSE GARAGE',24,70,0x5bc7ff,Math.PI)
 for(const [label,x,z,r] of [['STATE ST',-8,-48,0],['MADISON ST',48,-8,Math.PI/2],['LAKE ST',8,48,Math.PI],['MICHIGAN AVE',-48,8,-Math.PI/2]] as [string,number,number,number][])streetSign(scene,label,x,z,r)
 detailedCar(scene,-60,-58,0x2b7cff,.08);detailedCar(scene,-52,-58,0xff375f,-.04);detailedCar(scene,58,58,0x35d07f,Math.PI+.08);detailedCar(scene,50,58,0xf6c84c,Math.PI-.05)
 window.dispatchEvent(new CustomEvent('tryamm:streetverse-original-city-art-ready',{detail:{businessSigns:5,murals:2,busShelters:4,benches:4,hydrants:6,raceGates:4,storefronts:4,streetSigns:4,showcaseCars:4,originalArt:true}}))
 return {businessSigns:5,murals:2,busShelters:4,benches:4,hydrants:6,raceGates:4,storefronts:4,streetSigns:4,showcaseCars:4,originalArt:true}
}
