let installed=false
const ID='tryamm-chicago-time-machine'
const KEY='tryamm.streetverse.chicago-time-machine.v1'
type Mission={id:string;title:string;era:string;summary:string;objectives:string[];egg:string;xp:number;credits:number}
const MISSIONS:Mission[]=[
{id:'tunnel-1906',title:'1906: Tunnel Company Shift',era:'1906',summary:'Historical-simulation mission inspired by Chicago’s underground freight era. Observe and operate a fictionalized electric freight shift without reproducing restricted modern access.',objectives:['Calibrate Time Machine to 1906','Meet simulated freight dispatcher','Load virtual cargo car','Follow historical-inspired rail markers','Return through temporal checkpoint'],egg:'Miniature electric freight locomotive collectible',xp:980,credits:195},
{id:'loop-1893',title:'1893: World’s Fair Echo',era:'1893',summary:'Explore a stylized educational simulation inspired by Chicago during the Columbian Exposition era and recover archive fragments.',objectives:['Set destination 1893','Find three exposition archive echoes','Interview simulated historical NPC','Recover souvenir fragment','Return to present'],egg:'White City holographic postcard',xp:900,credits:180},
{id:'river-reversal',title:'1900: River Engineering',era:'1900',summary:'Educational engineering puzzle about Chicago’s waterway transformation using a fictional control-room simulation.',objectives:['Enter engineering simulation','Inspect flow model','Solve water-routing puzzle','Stabilize simulated system','Archive engineering record'],egg:'Animated Chicago waterway blueprint',xp:860,credits:170},
{id:'jazz-1920s',title:'1920s: South Side Night',era:'1920s',summary:'Music-history mission through a fictionalized Chicago nightlife district focused on jazz culture, creators and community.',objectives:['Enter 1920s simulation','Meet bandleader NPC','Recover missing sheet music','Complete rhythm challenge','Record archive performance'],egg:'Hidden vintage piano motif',xp:820,credits:165},
{id:'blues-1950s',title:'1950s: Electric Blues Trail',era:'1950s',summary:'Follow a fictional music-history trail celebrating Chicago blues through studios, clubs and neighborhood creator stories.',objectives:['Tune temporal radio','Find studio checkpoint','Complete blues-call-and-response puzzle','Deliver recording reel','Return recording to archive'],egg:'Secret four-note blues variation',xp:850,credits:170},
{id:'house-1980s',title:'1980s: House Music Genesis',era:'1980s',summary:'Music-history simulation inspired by Chicago’s house-music emergence, with a fictional club and DJ mission.',objectives:['Enter 1980s night simulation','Meet DJ NPC','Repair virtual sound system','Build a dance-floor energy meter','Archive the mix'],egg:'Hidden warehouse-style dance room',xp:940,credits:190},
{id:'flood-1992-time',title:'1992: The Loop Flood',era:'1992',summary:'Return to a safe fictionalized simulation of the 1992 freight-tunnel flood and discover clues that change the present-day underground mystery.',objectives:['Enter 1992 simulation','Find simulated breach evidence','Mark high-water route','Recover lost archive case','Return before temporal window closes'],egg:'Present-day wall changes after archive recovery',xp:1050,credits:210},
{id:'future-2046',title:'2046: Future Chicago',era:'2046',summary:'A speculative StreetVerse future—not a prediction—where player choices alter transit, lakefront, neighborhoods and skyline possibilities.',objectives:['Open speculative future portal','Scan three changed districts','Compare future reputation state','Find future Benny message','Choose one future blueprint to archive'],egg:'Future-self silhouette encounter',xp:1200,credits:240},
{id:'time-heist',title:'Temporal Archive Heist',era:'MULTI-ERA',summary:'A fictional puzzle mission jumping between several historical simulations to recover pieces of one Chicago mystery without changing real history.',objectives:['Recover 1906 tunnel key','Recover 1920s music cipher','Recover 1980s frequency code','Unlock present-day archive vault','Solve final chronology puzzle'],egg:'The Chicago Chronokey',xp:1500,credits:300},
]
function active(){const h=location.hash.replace(/^#/,'');return h==='/streetverse'||h==='/city'}
function read(){try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch{return {completed:[],unlocked:false}}}
function save(s:any){try{localStorage.setItem(KEY,JSON.stringify({...s,updatedAt:new Date().toISOString()}))}catch{}}
function emit(name:string,detail:any){window.dispatchEvent(new CustomEvent(name,{detail}))}
function mount(){if(!active()){document.getElementById(ID)?.remove();return}if(document.getElementById(ID))return;let state=read();state.completed=Array.isArray(state.completed)?state.completed:[];const root=document.createElement('div');root.id=ID;root.style.cssText='position:fixed;left:12px;bottom:180px;z-index:2147482550;font-family:Inter,Arial,sans-serif;color:white';const btn=document.createElement('button');btn.textContent='⏳';btn.title='Chicago Time Machine';btn.style.cssText='width:38px;height:38px;border-radius:50%;border:1px solid #8c75b5;background:#100b19ed;color:white;font-size:17px;cursor:pointer';const panel=document.createElement('div');panel.style.cssText='display:none;margin-top:7px;width:min(91vw,430px);max-height:65vh;overflow:auto;padding:12px;border:1px solid #58466f;border-radius:14px;background:#08060df5;box-shadow:0 20px 60px #000d';const render=()=>{panel.innerHTML='<b>⏳ STREETVERSE • CHICAGO TIME MACHINE</b><div style="font-size:9px;opacity:.65;margin:4px 0 9px">Interactive historical and speculative simulations. This is game software—not real time travel.</div>';MISSIONS.forEach(m=>{const done=state.completed.includes(m.id),on=state.missionId===m.id;const c=document.createElement('div');c.style.cssText=`padding:9px;margin:6px 0;border:1px solid ${done?'#5c8a70':'#493b5b'};border-radius:9px;background:${done?'#0b1912':'#100c16'}`;c.innerHTML=`<b>${done?'✓ ':''}${m.title}</b><br><small style="opacity:.55">ERA ${m.era}</small><div style="font-size:9px;opacity:.72;margin-top:3px">${m.summary}</div>${on?`<div style="font-size:9px;color:#cbb7ff;margin-top:5px">${m.objectives[Math.min(state.objective||0,m.objectives.length-1)]}</div>`:''}${done?`<div style="font-size:9px;color:#e9c879;margin-top:4px">🥚 ${m.egg}</div>`:''}`;const a=document.createElement('button');a.textContent=on?'COMPLETE TIME OBJECTIVE':'ENTER ERA';a.style.cssText='margin-top:6px;padding:6px 8px;border-radius:7px;border:1px solid #6b5785;background:#1b1227;color:white;font-size:9px;font-weight:900';a.onclick=()=>{if(!on){state={...state,missionId:m.id,objective:0};save(state);emit('tryamm:time-machine-enter',{...m,mode:'simulation'});render();return}const n=(state.objective||0)+1;if(n>=m.objectives.length){state={...state,missionId:undefined,objective:0,completed:[...new Set([...state.completed,m.id])]};save(state);emit('tryamm:mission-completed',{missionId:m.id,title:m.title,xp:m.xp,holoCredits:m.credits,source:'chicago-time-machine',easterEgg:m.egg});emit('tryamm:easter-egg-found',{id:m.id,name:m.egg,era:m.era})}else{state={...state,objective:n};save(state)}render()};if(!done||on)c.append(a);panel.append(c)})};btn.onclick=()=>{panel.style.display=panel.style.display==='none'?'block':'none';if(panel.style.display==='block')render()};root.append(btn,panel);document.body.appendChild(root);emit('tryamm:chicago-time-machine-ready',{missions:MISSIONS.length,mode:'historical-and-speculative-simulation'})}
export function installStreetVerseChicagoTimeMachineMissionsRuntime(){if(installed||typeof window==='undefined'||typeof document==='undefined')return;installed=true;const sync=()=>requestAnimationFrame(mount);window.addEventListener('hashchange',sync);window.addEventListener('tryamm:streetverse-enter',sync);if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',sync,{once:true});else sync()}
