let installed=false
const ID='tryamm-chicago-justice'
const KEY='tryamm.streetverse.chicago-justice.v1'
type Mission={id:string;title:string;zone:string;summary:string;objectives:string[];xp:number;credits:number;secret?:string}
const MISSIONS:Mission[]=[
{id:'county-court-run',title:'County Court: Case Runner',zone:'COUNTY COURT DISTRICT',summary:'Fictionalized courthouse support mission focused on public-facing legal-process gameplay.',objectives:['Meet legal-aid NPC outside public entrance','Deliver game-world case packet','Find correct public courtroom checkpoint','Return signed receipt'],xp:520,credits:105},
{id:'court-witness',title:'Witness Arrival',zone:'COURT DISTRICT',summary:'Escort a witness through public game-world checkpoints while handling crowds and transportation.',objectives:['Meet witness','Reach public security checkpoint','Find courtroom waiting zone','Complete safe ride handoff'],xp:610,credits:120},
{id:'federal-lockup-visit',title:'Federal Detention: Legal Visit',zone:'FEDERAL JUSTICE DISTRICT',summary:'Fictionalized legal-visit mission; no real facility layout, security procedure or restricted access is reproduced.',objectives:['Meet attorney NPC','Verify fictional visit credential','Reach public visitor checkpoint','Deliver approved legal document','Exit through public checkpoint'],xp:650,credits:130},
{id:'county-jail-reentry',title:'Cook County Reentry',zone:'COUNTY JUSTICE DISTRICT',summary:'Community reentry mission helping a released NPC connect with transportation, documents, work and services.',objectives:['Meet released NPC at game-world public handoff','Recover ID/resource packet','Connect transportation','Visit job/resource center','Complete safe destination handoff'],xp:700,credits:140},
{id:'women-reentry',title:"Women's Reentry Path",zone:'WOMEN’S JUSTICE SERVICES',summary:'Support-focused mission connecting a fictionalized women’s detention/reentry storyline to housing, family, work and community resources.',objectives:['Meet returning resident','Collect resource packet','Connect housing/support NPC','Complete job or training appointment','Reunite at safe community checkpoint'],xp:720,credits:145},
{id:'public-defender-night',title:'Public Defender: Night File',zone:'COURT DISTRICT',summary:'Timed paperwork and witness-coordination mission through public-facing justice locations.',objectives:['Receive case file','Locate witness NPC','Deliver approved documents','Return before hearing timer'],xp:580,credits:115},
{id:'justice-underground-echo',title:'The Sealed Docket',zone:'SECRET / TIME MACHINE',summary:'A fictional mystery linking the justice district to StreetVerse underground and Time Machine systems without mapping any real restricted passage.',objectives:['Find courthouse-history archive clue','Activate temporal echo','Recover simulated historic docket','Return to present','Unlock fictional archive room'],xp:980,credits:195,secret:'Hidden scales-of-justice Chronokey fragment'},
]
function active(){const h=location.hash.replace(/^#/,'');return h==='/streetverse'||h==='/city'}
function read(){try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch{return {completed:[]}}}
function save(s:any){try{localStorage.setItem(KEY,JSON.stringify({...s,updatedAt:new Date().toISOString()}))}catch{}}
function emit(n:string,d:any){window.dispatchEvent(new CustomEvent(n,{detail:d}))}
function mount(){if(!active()){document.getElementById(ID)?.remove();return}if(document.getElementById(ID))return;let state=read();state.completed=Array.isArray(state.completed)?state.completed:[];const root=document.createElement('div');root.id=ID;root.style.cssText='position:fixed;right:12px;bottom:132px;z-index:2147482500;font-family:Inter,Arial,sans-serif;color:white';const btn=document.createElement('button');btn.textContent='⚖️';btn.title='Chicago Justice Missions';btn.style.cssText='width:38px;height:38px;border-radius:50%;border:1px solid #8b8b8b;background:#101216ed;color:white;font-size:17px;cursor:pointer';const panel=document.createElement('div');panel.style.cssText='display:none;margin-top:7px;width:min(91vw,430px);max-height:65vh;overflow:auto;padding:12px;border:1px solid #4e5259;border-radius:14px;background:#080a0df5';const render=()=>{panel.innerHTML='<b>⚖️ STREETVERSE • JUSTICE DISTRICT</b><div style="font-size:9px;opacity:.65;margin:4px 0 9px">Fictionalized public-facing courthouse, detention, legal-aid and reentry gameplay. No restricted real-world layouts or security procedures.</div>';MISSIONS.forEach(m=>{const done=state.completed.includes(m.id),on=state.missionId===m.id;const c=document.createElement('div');c.style.cssText='padding:9px;margin:6px 0;border:1px solid #3e444c;border-radius:9px;background:#0c0f13';c.innerHTML=`<b>${done?'✓ ':''}${m.title}</b><br><small style="opacity:.55">${m.zone}</small><div style="font-size:9px;opacity:.72">${m.summary}</div>${on?`<div style="font-size:9px;color:#b8dcff;margin-top:5px">${m.objectives[Math.min(state.objective||0,m.objectives.length-1)]}</div>`:''}${done&&m.secret?`<div style="font-size:9px;color:#e9c879">🥚 ${m.secret}</div>`:''}`;const a=document.createElement('button');a.textContent=on?'COMPLETE OBJECTIVE':'START';a.style.cssText='margin-top:6px;padding:6px 8px;border-radius:7px;border:1px solid #555;background:#171b20;color:white;font-size:9px;font-weight:900';a.onclick=()=>{if(!on){state={...state,missionId:m.id,objective:0};save(state);emit('tryamm:justice-mission-start',m);render();return}const n=(state.objective||0)+1;if(n>=m.objectives.length){state={...state,missionId:undefined,objective:0,completed:[...new Set([...state.completed,m.id])]};save(state);emit('tryamm:mission-completed',{missionId:m.id,title:m.title,xp:m.xp,holoCredits:m.credits,source:'chicago-justice',easterEgg:m.secret});if(m.secret)emit('tryamm:easter-egg-found',{id:m.id,name:m.secret})}else{state={...state,objective:n};save(state)}render()};if(!done||on)c.append(a);panel.append(c)})};btn.onclick=()=>{panel.style.display=panel.style.display==='none'?'block':'none';if(panel.style.display==='block')render()};root.append(btn,panel);document.body.appendChild(root);emit('tryamm:chicago-justice-ready',{missions:MISSIONS.length,safety:'fictionalized-public-facing-only'})}
export function installStreetVerseChicagoJusticeMissionsRuntime(){if(installed||typeof window==='undefined'||typeof document==='undefined')return;installed=true;const sync=()=>requestAnimationFrame(mount);window.addEventListener('hashchange',sync);window.addEventListener('tryamm:streetverse-enter',sync);if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',sync,{once:true});else sync()}
