export type CareerMissionPhase='briefing'|'training'|'deployment'|'objectives'|'boss'|'extraction'|'verification'|'complete'
export type CareerMission={id:string;branchId:string;title:string;city:string;phase:CareerMissionPhase;objectives:{id:string;label:string;done:boolean}[];boss?:{name:string;kind:'crisis'|'challenge'|'rival-team'|'system-failure';stages:number;stage:number};extraction:{zone:string;secured:boolean;teamReady:boolean};xp:number;reputation:number;employmentCredits:number}
const KEY='tryamm_career_extraction_v1';let installed=false
function read():CareerMission|null{try{return JSON.parse(localStorage.getItem(KEY)||'null')}catch{return null}}function save(m:CareerMission|null){try{m?localStorage.setItem(KEY,JSON.stringify(m)):localStorage.removeItem(KEY)}catch{};window.dispatchEvent(new CustomEvent('tryamm:career-extraction-state',{detail:{schema:'tryamm.career.extraction.v1',mission:m,loop:'CAREER → TRAIN → MISSION → OBJECTIVES → BOSS CHALLENGE → EXTRACTION → VERIFY → XP/REPUTATION → JOB PROGRESSION'}}))}
const objectiveSets:Record<string,string[]>={
 'guardian-maritime':['Check rescue equipment','Locate people in distress','Coordinate safe approach','Complete rescue without unnecessary confrontation'],
 'guardian-naval':['Inspect relief cargo','Plan delivery route','Coordinate team logistics','Deliver humanitarian supplies'],
 'guardian-ground':['Assess community needs','Establish safe relief point','Coordinate transport','Complete ground support objectives'],
 'guardian-air':['Verify weather and route','Coordinate rescue pickup','Maintain safe flight plan','Deliver evacuees/resources safely'],
 'guardian-investigations':['Interview lawful witnesses','Preserve permitted evidence','Identify contradictions','Escalate findings for review'],
 'guardian-county':['Review community call','De-escalate scene','Connect residents to services','Close incident safely'],
 'guardian-fire-ems':['Assess hazard','Guide evacuation','Request appropriate emergency resources','Reach safe accountability point'],
 'guardian-emergency':['Map affected zone','Open resource hub','Coordinate accessibility needs','Complete recovery handoff'],
 'guardian-cyber':['Identify defensive incident','Secure affected accounts','Preserve lawful evidence','Escalate verified indicators'],
 'guardian-sar':['Define search area','Coordinate team sectors','Locate missing person','Reach safe extraction zone'],
 'guardian-transit':['Identify transit hazard','Guide passengers safely','Restore accessible route','Close transit incident'],
 'guardian-wildlife':['Identify environmental risk','Protect public perimeter','Report wildlife/environment condition','Complete stewardship handoff'],
 'guardian-humanitarian':['Assess humanitarian need','Coordinate interpreters/resources','Protect neutral aid route','Complete diplomatic handoff']
}
function make(branchId:string,title:string,city:string):CareerMission{const labels=objectiveSets[branchId]||['Receive assignment','Coordinate team','Complete safe objective','Report outcome'];return{id:`career-${Date.now()}`,branchId,title,city,phase:'briefing',objectives:labels.map((label,i)=>({id:`o${i+1}`,label,done:false})),boss:{name:'Final Incident Command Challenge',kind:'crisis',stages:3,stage:0},extraction:{zone:'Safe Extraction / Handoff Zone',secured:false,teamReady:false},xp:750,reputation:40,employmentCredits:1}}
export function installStreetVerseCareerExtractionRuntime(){if(installed||typeof window==='undefined')return;installed=true;let mission=read();queueMicrotask(()=>save(mission));window.addEventListener('tryamm:guardian-service-career-select',(e:Event)=>{const d=(e as CustomEvent<any>).detail||{};mission=make(String(d.branchId||'guardian-sar'),String(d.title||'Guardian Career Mission'),String(d.city||'Chicago'));save(mission)});window.addEventListener('tryamm:career-mission-phase',(e:Event)=>{if(!mission)return;mission={...mission,phase:(e as CustomEvent<any>).detail?.phase||mission.phase};save(mission)});window.addEventListener('tryamm:career-objective-complete',(e:Event)=>{if(!mission)return;const id=(e as CustomEvent<any>).detail?.id;mission={...mission,phase:'objectives',objectives:mission.objectives.map(o=>o.id===id?{...o,done:true}:o)};if(mission.objectives.every(o=>o.done))mission.phase='boss';save(mission)});window.addEventListener('tryamm:career-boss-stage-complete',()=>{if(!mission?.boss)return;const stage=Math.min(mission.boss.stages,mission.boss.stage+1);mission={...mission,boss:{...mission.boss,stage},phase:stage>=mission.boss.stages?'extraction':'boss'};save(mission)});window.addEventListener('tryamm:career-extraction-update',(e:Event)=>{if(!mission)return;const d=(e as CustomEvent<any>).detail||{};mission={...mission,extraction:{...mission.extraction,...d},phase:'extraction'};if(mission.extraction.secured&&mission.extraction.teamReady)mission.phase='verification';save(mission)});window.addEventListener('tryamm:career-mission-verify',()=>{if(!mission||mission.phase!=='verification')return;mission={...mission,phase:'complete'};save(mission);window.dispatchEvent(new CustomEvent('tryamm:streetverse-reward',{detail:{xp:mission.xp,reputation:mission.reputation}}));window.dispatchEvent(new CustomEvent('tryamm:middleverse-career-credit',{detail:{branchId:mission.branchId,credits:mission.employmentCredits,city:mission.city}}))})}
