type StoryState={chapter:number;basketballWins:number;stubbsMet:boolean;updatedAt:string}
const KEY='tryamm_streetverse_story_mode_v1';let installed=false
const chapters=[
 {id:'first-call',title:'Chapter 1 — The First Call',objective:'Meet Stubbs and learn how StreetVerse missions connect the city.'},
 {id:'court-respect',title:'Chapter 2 — Court Respect',objective:'Win the neighborhood basketball challenge.'},
 {id:'city-builder',title:'Chapter 3 — Build the Block',objective:'Use your mission rewards to unlock the next business/community mission.'}
]
function now(){return new Date().toISOString()}
function read():StoryState{try{return JSON.parse(localStorage.getItem(KEY)||'') as StoryState}catch{return {chapter:0,basketballWins:0,stubbsMet:false,updatedAt:now()}}}
function write(s:StoryState){s.updatedAt=now();localStorage.setItem(KEY,JSON.stringify(s));window.dispatchEvent(new CustomEvent('tryamm:streetverse-story-state',{detail:s}));render();return s}
function emit(name:string,detail:any={}){window.dispatchEvent(new CustomEvent(name,{detail}))}
function streetverseVisible(){return (document.body?.innerText||'').includes('STREETVERSE • CINEMATIC OMNI DISTRICT')}
function ensurePanel(){let el=document.getElementById('sv-story-mode') as HTMLDivElement|null;if(!streetverseVisible()){el?.remove();return null}if(!el){el=document.createElement('div');el.id='sv-story-mode';Object.assign(el.style,{position:'fixed',left:'12px',bottom:'142px',zIndex:'2147482500',width:'min(330px,82vw)',padding:'11px',borderRadius:'16px',background:'rgba(5,8,18,.93)',border:'1px solid rgba(109,213,255,.55)',color:'#fff',font:'700 11px system-ui',boxShadow:'0 12px 30px rgba(0,0,0,.42)'});document.body.appendChild(el)}return el}
function openBasketball(){let modal=document.getElementById('sv-basketball-mission') as HTMLDivElement|null;if(modal)return;const s=read();modal=document.createElement('div');modal.id='sv-basketball-mission';Object.assign(modal.style,{position:'fixed',inset:'0',zIndex:'2147483000',background:'rgba(0,0,0,.78)',display:'grid',placeItems:'center',padding:'18px'});let shots=0,made=0;const card=document.createElement('div');Object.assign(card.style,{width:'min(430px,92vw)',borderRadius:'22px',padding:'18px',background:'#09111d',border:'1px solid #f2a93b',color:'#fff',font:'700 13px system-ui',boxShadow:'0 18px 60px rgba(0,0,0,.55)'});const update=()=>{card.innerHTML=`<div style="color:#f2a93b;letter-spacing:.12em;font-size:10px">STREETVERSE STORY MODE</div><h2 style="margin:7px 0 5px">🏀 Court Respect</h2><div style="opacity:.8">Stubbs: “Earn respect with skill, teamwork and composure. Hit 3 of 5 shots.”</div><div style="font-size:28px;margin:16px 0">${made} / 3 MADE • ${shots} / 5 SHOTS</div><button id="sv-shoot" style="padding:12px 18px;border-radius:999px;border:0;background:#f2a93b;color:#15100a;font-weight:950">SHOOT</button> <button id="sv-court-close" style="padding:12px 18px;border-radius:999px;border:1px solid #61758a;background:#111a26;color:#fff;font-weight:900">EXIT</button>`;card.querySelector('#sv-court-close')?.addEventListener('click',()=>modal?.remove());card.querySelector('#sv-shoot')?.addEventListener('click',()=>{if(shots>=5)return;shots++;const deterministic=(shots===1||shots===3||shots===5);if(deterministic)made++;if(made>=3){emit('tryamm:streetverse-activity-complete',{type:'basketball',label:'Court Respect complete',source:'story-mode'});emit('tryamm:streetverse-xp-gain',{amount:250,reason:'basketball-story-mission'});emit('tryamm:mission-completed',{missionId:'streetverse-court-respect',missionTitle:'Court Respect',title:'Court Respect completed',metadata:{made,shots,storyMode:true}});s.basketballWins+=1;s.chapter=Math.max(s.chapter,2);write(s);card.innerHTML=`<div style="color:#73ff9e;font-weight:950">MISSION COMPLETE</div><h2>🏀 Court Respect</h2><p>${made} shots made. +250 XP.</p><button id="sv-court-done" style="padding:12px 18px;border-radius:999px;border:0;background:#73ff9e;font-weight:950">CONTINUE STORY</button>`;card.querySelector('#sv-court-done')?.addEventListener('click',()=>modal?.remove());return}if(shots>=5){shots=0;made=0}update()})};modal.appendChild(card);document.body.appendChild(modal);emit('tryamm:streetverse-activity-active',{type:'basketball',label:'Court Respect',objective:'Make 3 of 5 shots',source:'story-mode'});emit('tryamm:construct:targets',{targets:[{id:'story-court',kind:'mission',title:'Neighborhood Court',x:-24,z:18}],source:'story-mode'});update()}
function meetStubbs(){const s=read();s.stubbsMet=true;s.chapter=Math.max(s.chapter,1);write(s);emit('tryamm:streetverse-npc-reaction',{id:'stubbs-mentor',mood:'focused',line:'Stubbs: Build skill, build trust, then build the city.',source:'story-mode'});emit('tryamm:streetverse-story-character',{id:'stubbs',name:'Stubbs',role:'Founder / mentor / mission giver',visual:'original-game-avatar-no-likeness',source:'story-mode'})}
function render(){const el=ensurePanel();if(!el)return;const s=read();const ch=chapters[Math.min(s.chapter,chapters.length-1)];el.innerHTML=`<div style="color:#6dd5ff;letter-spacing:.12em;font-size:10px">STORY MODE • STUBBS ARC</div><div style="margin-top:6px;font-size:14px">${ch.title}</div><div style="margin-top:4px;opacity:.76">${ch.objective}</div><div style="margin-top:7px;font-size:10px;opacity:.62">Stubbs: original in-game mentor character • basketball wins ${s.basketballWins}</div><div style="display:flex;gap:7px;flex-wrap:wrap;margin-top:9px">${!s.stubbsMet?'<button id="sv-meet-stubbs">MEET STUBBS</button>':''}<button id="sv-story-basketball">🏀 BASKETBALL MISSION</button></div>`;el.querySelectorAll('button').forEach((b:any)=>Object.assign(b.style,{padding:'8px 10px',borderRadius:'999px',border:'1px solid #6dd5ff',background:'#0b2434',color:'#dff8ff',fontWeight:'950'}));el.querySelector('#sv-meet-stubbs')?.addEventListener('click',meetStubbs);el.querySelector('#sv-story-basketball')?.addEventListener('click',openBasketball)}
export function getStreetVerseStoryState(){return read()}
export function installStreetVerseStoryModeRuntime(){if(installed||typeof window==='undefined')return;installed=true;const mo=new MutationObserver(()=>render());mo.observe(document.documentElement,{subtree:true,childList:true,characterData:true});window.addEventListener('tryamm:streetverse-story-open',render);window.addEventListener('tryamm:streetverse-story-basketball',openBasketball);window.addEventListener('tryamm:streetverse-story-meet-stubbs',meetStubbs);queueMicrotask(()=>{render();emit('tryamm:streetverse-story-ready',{character:'Stubbs',storyMode:true,basketballMission:true,persistent:true})})}
