let installed=false
const WORLD_SAVE='tryamm.streetverse.omniworld.v1'
const MILESTONE='tryamm_streetverse_playable_milestone_v1'
const mission={id:'market',label:'Marketplace Delivery',x:48,z:-28}
function emit(name:string,detail:any={}){window.dispatchEvent(new CustomEvent(name,{detail}))}
function text(){return document.body?.innerText||''}
function hasStreetVerse(){return text().includes('STREETVERSE • CINEMATIC OMNI DISTRICT')}
function milestone(){try{return JSON.parse(localStorage.getItem(MILESTONE)||'{}')}catch{return {}}}
function nextStep(){return milestone()?.steps?.find((x:any)=>!x.done)?.id||'complete'}
function guide(){let el=document.getElementById('sv-production-guide') as HTMLDivElement|null;if(!hasStreetVerse()){el?.remove();return}if(!el){el=document.createElement('div');el.id='sv-production-guide';Object.assign(el.style,{position:'fixed',right:'14px',bottom:'214px',zIndex:'2147482600',width:'min(310px,78vw)',padding:'10px 12px',borderRadius:'14px',background:'rgba(3,10,18,.92)',border:'1px solid rgba(255,215,92,.68)',color:'#fff',font:'700 11px system-ui',boxShadow:'0 10px 30px rgba(0,0,0,.45)'});document.body.appendChild(el)}const n=nextStep();const prompts:Record<string,string>={walk:'Walk with arrows/WASD.',drive:'Approach a car and tap INTERACT / ENTER.',talk:'Exit the car, approach a resident and interact.',enter:'Approach a business portal and enter it.',mission:'Accept Marketplace Delivery.',waypoint:'Route is being sent to Construct and the HUD.',objective:'Travel to the glowing Marketplace Delivery beacon.',xp:'Mission completed. XP verification is next.',save:'Keep playing briefly while autosave is verified.',reel:'Tap 🎥 REEL, capture/import media, then render the Reel.',reload:'Reload the page once to verify saved progress returns.',complete:'StreetVerse playable production loop passed.'};el.innerHTML=`<div style="color:#ffd75c;letter-spacing:.08em">PRODUCTION COMPLETION RUN</div><div style="margin-top:5px">NEXT: <b>${n.toUpperCase()}</b></div><div style="margin-top:4px;opacity:.82">${prompts[n]||''}</div>${n==='mission'?'<button id="sv-accept-production-mission" style="margin-top:8px;border:1px solid #ffd75c;border-radius:999px;padding:7px 10px;background:#2a1b05;color:#ffe38c;font-weight:900">ACCEPT MISSION</button>':''}`;document.getElementById('sv-accept-production-mission')?.addEventListener('click',()=>{emit('tryamm:streetverse-activity-active',{type:mission.id,label:mission.label,objective:'Reach the Marketplace Delivery beacon.',source:'visible-world'});setTimeout(()=>emit('tryamm:construct:targets',{targets:[{id:`mission-${mission.id}`,kind:'mission',title:mission.label,x:mission.x,z:mission.z}],source:'visible-world'}),50)},{once:true})}
function watchVisibleState(){let last='';const scan=()=>{if(!hasStreetVerse()){guide();return}const t=text();if(t===last){guide();return}last=t;const n=nextStep();if(n==='drive'&&t.includes('DRIVING'))emit('tryamm:streetverse-transport-state',{mode:'car',source:'visible-world'});if(n==='talk'&&/StreetVerse resident \d+:/.test(t))emit('tryamm:streetverse-npc-reaction',{id:'visible-resident',mood:'friendly',line:'resident dialogue visible',source:'visible-world'});if(n==='enter'&&(t.includes('BUSINESS INTERACTION')||t.includes('IN BUSINESS')))emit('tryamm:streetverse-interior-enter',{source:'visible-world'});if(n==='objective'&&/(Marketplace Delivery|Creator Studio Session|Marina Charter|Holo Ads Campaign|All American Network) complete • \+/.test(t)){const missionLine=t.split('\n').find(x=>x.includes(' complete • +'))||'StreetVerse mission';emit('tryamm:streetverse-activity-complete',{type:'world-mission',label:missionLine,source:'visible-world'});setTimeout(()=>emit('tryamm:streetverse-xp-gain',{amount:100,reason:'visible-world-mission'}),60)}guide()};const mo=new MutationObserver(scan);mo.observe(document.documentElement,{subtree:true,childList:true,characterData:true});scan();return()=>mo.disconnect()}
function watchMovement(){let moved=false;const key=(e:KeyboardEvent)=>{if(!hasStreetVerse()||moved||nextStep()!=='walk')return;const k=e.key.toLowerCase();if(['w','a','s','d','arrowup','arrowdown','arrowleft','arrowright'].includes(k)){moved=true;emit('tryamm:streetverse-player-move',{moved:true,source:'visible-world-input'})}};window.addEventListener('keydown',key);const pointer=(e:PointerEvent)=>{if(!hasStreetVerse()||moved||nextStep()!=='walk')return;const label=(e.target as HTMLElement)?.textContent||'';if(['▲','▼','◀','▶'].includes(label.trim())){moved=true;emit('tryamm:streetverse-player-move',{moved:true,source:'visible-world-touch'})}};window.addEventListener('pointerdown',pointer,true);return()=>{window.removeEventListener('keydown',key);window.removeEventListener('pointerdown',pointer,true)}}
function watchSave(){let previous=localStorage.getItem(WORLD_SAVE);const id=window.setInterval(()=>{const current=localStorage.getItem(WORLD_SAVE);if(current&&current!==previous){previous=current;if(nextStep()==='save')emit('tryamm:streetverse-save-complete',{source:'omniworld-autosave',bytes:current.length})}guide()},900);return()=>clearInterval(id)}
function watchReel(){const handler=()=>{let reported=false;const mo=new MutationObserver(()=>{if(reported||nextStep()!=='reel')return;const t=text();if(t.includes('Capture ready. Add effects, render the final Reel')||t.includes('Final Reel rendered.')||t.includes('Production upload verified.')){reported=true;emit('tryamm:reel-recorded',{source:'media-studio-visible-state'});emit('tryamm:streetverse-milestone-arm-reload');mo.disconnect()}});mo.observe(document.documentElement,{subtree:true,childList:true,characterData:true});setTimeout(()=>mo.disconnect(),10*60*1000)};window.addEventListener('tryamm:media-studio-open',handler);window.addEventListener('tryamm:media-publish-queued',()=>{if(nextStep()==='reel'){emit('tryamm:reel-saved',{source:'media-publish-queue'});emit('tryamm:streetverse-milestone-arm-reload')}});return()=>window.removeEventListener('tryamm:media-studio-open',handler)}
export function installStreetVerseProductionLoopBridge(){if(installed||typeof window==='undefined')return;installed=true;const clean=[watchVisibleState(),watchMovement(),watchSave(),watchReel()];window.addEventListener('tryamm:streetverse-milestone-state',guide);window.addEventListener('beforeunload',()=>emit('tryamm:streetverse-milestone-arm-reload'));queueMicrotask(()=>{guide();emit('tryamm:streetverse-production-loop-bridge-ready',{visibleWorld:true,orderedEvidence:true,movement:true,drive:true,talk:true,interior:true,explicitMissionAcceptance:true,waypoint:true,objective:true,xp:true,autosave:true,reel:true,reload:true})});return()=>clean.forEach(fn=>fn())}