export type CommerceMissionType='stock-store'|'warehouse-pick'|'cold-chain'|'delivery'|'franchise-launch'|'live-shopping';
export type CommerceMission={id:string;type:CommerceMissionType;city:string;title:string;objectives:string[];xp:number;reputation:number;businessCredits:number};
const KEY='tryamm_streetverse_commerce_world_v1';let installed=false;
const templates:Record<CommerceMissionType,Omit<CommerceMission,'id'|'city'>>={
 'stock-store':{type:'stock-store',title:'Restock the All American Marketplace',objectives:['Review available-to-promise inventory','Choose verified fulfillment rail','Protect margin floor','Confirm store inventory update'],xp:350,reputation:12,businessCredits:1},
 'warehouse-pick':{type:'warehouse-pick',title:'Virtual Warehouse Fulfillment Run',objectives:['Verify SKU/lot','Pick cheapest compliant rail','Prepare order handoff','Confirm inventory timestamp'],xp:400,reputation:14,businessCredits:1},
 'cold-chain':{type:'cold-chain',title:'HoloFridge Cold-Chain Rescue',objectives:['Identify low/expiring item','Source verified replacement','Maintain storage requirement','Confirm fridge inventory update'],xp:450,reputation:16,businessCredits:1},
 'delivery':{type:'delivery',title:'Holo Delivery Route',objectives:['Accept order','Plan accessible route','Complete pickup','Confirm delivery proof'],xp:300,reputation:10,businessCredits:1},
 'franchise-launch':{type:'franchise-launch',title:'Open a New Marketplace Location',objectives:['Select city','Create local website/storefront','Connect warehouse rails','Hire/train local staff'],xp:700,reputation:25,businessCredits:2},
 'live-shopping':{type:'live-shopping',title:'Creator Live Shopping Mission',objectives:['Select in-stock products','Prepare rights-cleared show','Go live','Convert verified orders into fulfillment'],xp:500,reputation:18,businessCredits:1}
};
function emit(missions:CommerceMission[],city:string){window.dispatchEvent(new CustomEvent('tryamm:streetverse-commerce-state',{detail:{schema:'tryamm.streetverse.commerce.v1',city,missions,loop:'STREETVERSE DISCOVERY → STORE → INVENTORY → WAREHOUSE → PAYMENT → PICK/DELIVERY → HOLO FRIDGE/STORE UPDATE → XP/LOYALTY → CREATOR REEL → NEXT CUSTOMER'}}))}
export function installStreetVerseCommerceWorldRuntime(){if(installed||typeof window==='undefined')return;installed=true;let city='Chicago',missions:CommerceMission[]=[];const regenerate=()=>{missions=(Object.keys(templates) as CommerceMissionType[]).map(type=>({id:`${type}-${city.toLowerCase().replace(/\s+/g,'-')}`,city,...templates[type]}));try{localStorage.setItem(KEY,JSON.stringify({city,missions}))}catch{};emit(missions,city)};queueMicrotask(regenerate);window.addEventListener('tryamm:world-location-changed',(e:Event)=>{city=String((e as CustomEvent<any>).detail?.city||city);regenerate()});window.addEventListener('tryamm:streetverse-commerce-request',()=>emit(missions,city));window.addEventListener('tryamm:streetverse-commerce-select',(e:Event)=>{const id=String((e as CustomEvent<any>).detail?.id||'');const mission=missions.find(m=>m.id===id);if(!mission)return;window.dispatchEvent(new CustomEvent('tryamm:streetverse-local-mission-selected',{detail:{...mission,source:'commerce-world'}}));if(mission.type==='stock-store'||mission.type==='warehouse-pick')window.dispatchEvent(new CustomEvent('tryamm:virtual-warehouse-mission',{detail:mission}));if(mission.type==='cold-chain')window.dispatchEvent(new CustomEvent('tryamm:holo-fridge-mission',{detail:mission}));if(mission.type==='delivery')window.dispatchEvent(new CustomEvent('tryamm:holo-delivery-mission',{detail:mission}));if(mission.type==='live-shopping')window.dispatchEvent(new CustomEvent('tryamm:creator-commerce-launch',{detail:{city,missionId:mission.id}}));if(mission.type==='franchise-launch')window.dispatchEvent(new CustomEvent('tryamm:franchise-expansion-request',{detail:{city,missionId:mission.id}}))});window.addEventListener('tryamm:streetverse-commerce-complete',(e:Event)=>{const d=(e as CustomEvent<any>).detail||{};const mission=missions.find(m=>m.id===d.id);if(!mission||!d.verified)return;window.dispatchEvent(new CustomEvent('tryamm:streetverse-reward',{detail:{xp:mission.xp,reputation:mission.reputation}}));window.dispatchEvent(new CustomEvent('tryamm:middleverse-career-credit',{detail:{branchId:'commerce',credits:mission.businessCredits,city}}));window.dispatchEvent(new CustomEvent('tryamm:creator-highlight',{detail:{kind:'commerce-mission-complete',city,mission:mission.title}}))})}
