let installed=false
const KEY='tryamm.streetverse.manhunt-director.v1'
type State={heat:number;chapter:string;resolved:boolean;safeZones:number;publicTrust:number}
const read=():State=>{try{return {...{heat:0,chapter:'freedom',resolved:false,safeZones:3,publicTrust:50},...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{return {heat:0,chapter:'freedom',resolved:false,safeZones:3,publicTrust:50}}}
const save=(s:State)=>{try{localStorage.setItem(KEY,JSON.stringify({...s,updatedAt:new Date().toISOString()}))}catch{}}
const emit=(n:string,d:any)=>window.dispatchEvent(new CustomEvent(n,{detail:d}))
const clamp=(n:number)=>Math.max(0,Math.min(100,n))
function tier(h:number){return h>=90?'MAXIMUM':h>=70?'SEVERE':h>=45?'HIGH':h>=20?'ELEVATED':'LOW'}
export function installStreetVerseManhuntDirectorRuntime(){if(installed||typeof window==='undefined')return;installed=true;let state=read();const publish=(reason:string)=>{const level=tier(state.heat);const fiction=level==='MAXIMUM'?['scripted fictional roadblocks','dense search zones','NPC recognition','limited game safe zones','case-resolution objective']:level==='SEVERE'?['fictional roadblocks','search teams','changed NPC reactions','reduced safe zones']:level==='HIGH'?['patrol pressure','witness calls','district alerts']:level==='ELEVATED'?['extra patrol presence','rumors','select NPC reactions']:['normal city activity'];emit('tryamm:manhunt-state',{...state,level,effects:fiction,reason,safety:'fictional-game-systems-only'});save(state)};window.addEventListener('tryamm:streetverse-choice',(e:any)=>{state.heat=clamp(state.heat+Number(e.detail?.heatDelta||0));state.publicTrust=clamp(state.publicTrust+Number(e.detail?.trustDelta||0));state.safeZones=Math.max(0,3-Math.floor(state.heat/30));publish('choice')});window.addEventListener('tryamm:mission-completed',(e:any)=>{const d=e.detail||{};if(d.source==='chicago-justice'){state.heat=clamp(state.heat-8);state.publicTrust=clamp(state.publicTrust+5)}if(d.missionId==='case-resolution'||d.missionId==='clear-name'||d.missionId==='legal-release'){state.resolved=true;state.heat=0;state.chapter='rebuild';state.safeZones=3}publish('mission')});window.addEventListener('tryamm:manhunt-start',(e:any)=>{state.chapter='manhunt';state.heat=clamp(Number(e.detail?.heat||65));publish('start')});window.addEventListener('tryamm:boss-path',(e:any)=>{state.chapter=String(e.detail?.path||'business-boss');publish('boss-path')});publish('install')}
