import * as THREE from 'three'

type Point={x:number;z:number}
let installed=false,active=false,raf=0
let root:HTMLDivElement|null=null,renderer:THREE.WebGLRenderer|null=null,scene:THREE.Scene|null=null,camera:THREE.PerspectiveCamera|null=null
let player:Point={x:0,z:58},targetPlayer:Point={x:0,z:58}
const anim:THREE.Object3D[]=[]
const labels:{el:HTMLDivElement;pos:THREE.Vector3}[]=[]

function m(color:number,opacity=.9){return new THREE.MeshBasicMaterial({color,transparent:opacity<1,opacity,depthWrite:false,toneMapped:false})}
function b(w:number,h:number,d:number,color:number,opacity=.9){return new THREE.Mesh(new THREE.BoxGeometry(w,h,d),m(color,opacity))}
function label(text:string,pos:THREE.Vector3,color='#67e8f9'){
 if(!root)return;const el=document.createElement('div');el.textContent=text;Object.assign(el.style,{position:'fixed',transform:'translate(-50%,-50%)',padding:'6px 9px',border:`1px solid ${color}`,borderRadius:'9px',background:'rgba(3,7,18,.78)',color,font:'700 11px system-ui',letterSpacing:'.06em',boxShadow:`0 0 14px ${color}66`,pointerEvents:'none',whiteSpace:'nowrap',zIndex:'4'});root.appendChild(el);labels.push({el,pos})
}
function vendor(x:number,z:number,name:string,color:number){if(!scene)return;const g=new THREE.Group();const body=b(.7,1.4,.45,color,.95);body.position.y=1.05;g.add(body);const head=new THREE.Mesh(new THREE.SphereGeometry(.3,12,10),m(0xb97952,.98));head.position.y=2;g.add(head);g.position.set(x,0,z);scene.add(g);anim.push(g);label(name,new THREE.Vector3(x,2.8,z),'#fcd34d')}
function store(x:number,z:number,name:string,color:number){if(!scene)return;const g=new THREE.Group();const base=b(10,5,7,0x111827,.92);base.position.y=2.5;g.add(base);const glass=b(8.7,3,.18,color,.16);glass.position.set(0,2.1,3.55);g.add(glass);const awning=b(9,.4,1.2,color,.82);awning.position.set(0,4.7,3.8);g.add(awning);for(let i=-2;i<=2;i++){const p=b(1.2,1.7,.8,0xffffff,.16);p.position.set(i*1.45,1.35,2.9);g.add(p)}g.position.set(x,0,z);scene.add(g);label(name,new THREE.Vector3(x,6,z),'#fde68a')}
function portal(x:number,z:number,name:string,color:number,eventName:string){if(!scene)return;const g=new THREE.Group();const l=b(.45,4,.45,color,.72),r=b(.45,4,.45,color,.72),t=b(4,.45,.45,color,.72);l.position.set(-1.8,2,0);r.position.set(1.8,2,0);t.position.set(0,4,0);g.add(l,r,t);const ring=new THREE.Mesh(new THREE.TorusGeometry(1.45,.1,8,40),m(color,.95));ring.position.y=2.2;g.add(ring);g.position.set(x,0,z);g.userData.eventName=eventName;scene.add(g);anim.push(ring);label(name,new THREE.Vector3(x,4.9,z),'#93c5fd')}
function arena(){if(!scene)return;const g=new THREE.Group();const floor=new THREE.Mesh(new THREE.CylinderGeometry(11,11,.5,48),m(0x171a33,.96));floor.position.y=.3;g.add(floor);const rim=new THREE.Mesh(new THREE.TorusGeometry(10.3,.22,8,64),m(0x22d3ee,.88));rim.rotation.x=Math.PI/2;rim.position.y=.65;g.add(rim);const stage=b(8,1,5,0x29264f,.97);stage.position.y=1;g.add(stage);const live=b(11,5,.3,0x060b19,.98);live.position.set(0,7,-4.5);g.add(live);const banner=b(10,.45,.35,0xec4899,.95);banner.position.set(0,5.1,-4.4);g.add(banner);for(const x of [-3.2,3.2]){const podium=b(2,2,2,x<0?0x06b6d4:0xec4899,.85);podium.position.set(x,1.5,0);g.add(podium)}g.position.set(0,0,-8);scene.add(g);label('TRYAMM PK / LIVE ARENA',new THREE.Vector3(0,10,-8),'#f472b6');label('TEAM A  0  :  0  TEAM B',new THREE.Vector3(0,7,-8),'#ffffff');anim.push(rim)
}
function giftBurst(){if(!scene)return;for(let i=0;i<18;i++){const s=new THREE.Mesh(new THREE.SphereGeometry(.12,8,6),m(i%2?0xff4fc3:0x67e8f9,.9));s.position.set((Math.random()-.5)*6,2+Math.random()*3,-8+(Math.random()-.5)*3);s.userData.baseY=s.position.y;s.userData.phase=Math.random()*6.28;scene.add(s);anim.push(s)}}
function hud(){const el=document.createElement('div');el.id='tryamm-visible-creator-controls';Object.assign(el.style,{position:'fixed',right:'14px',bottom:'88px',zIndex:'20006',display:'none',gap:'8px',flexDirection:'column',pointerEvents:'auto'});for(const [txt,ev] of [['🥽 QUEST','tryamm:metaquest-open'],['♿ ACCESS','tryamm:accessibility-open'],['🎥 REEL','tryamm:media-studio-open']]){const bt=document.createElement('button');bt.textContent=txt;Object.assign(bt.style,{padding:'10px 12px',borderRadius:'12px',border:'1px solid #67e8f9',background:'rgba(7,13,30,.9)',color:'#fff',fontWeight:'800'});bt.onclick=()=>window.dispatchEvent(new CustomEvent(ev));el.appendChild(bt)}document.body.appendChild(el);return el}
function build(){root=document.createElement('div');root.id='tryamm-streetverse-creator-district';Object.assign(root.style,{position:'fixed',inset:'0',zIndex:'20003',pointerEvents:'none',display:'none'});document.body.appendChild(root);renderer=new THREE.WebGLRenderer({alpha:true,antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.2));renderer.setClearColor(0,0);renderer.outputColorSpace=THREE.SRGBColorSpace;root.appendChild(renderer.domElement);scene=new THREE.Scene();camera=new THREE.PerspectiveCamera(60,1,.1,700);arena();store(-18,19,'CREATOR MARKET • LIVE SHOP',0xf59e0b);store(18,19,'OMNI MARKET • PRODUCTS',0x22d3ee);store(-18,-32,'MUSIC / PERFORMANCE LIVE',0x8b5cf6);store(18,-32,'BUSINESS PK SHOWROOM',0x10b981);vendor(-13,14,'Creator Vendor • captions + translation',0xf59e0b);vendor(13,14,'Marketplace Host • LIVE',0x22d3ee);vendor(-12,-25,'Music Creator • PK',0x8b5cf6);vendor(12,-25,'Business Creator • PK',0x10b981);portal(-30,-8,'PROPERTYVERSE PORTAL',0xf59e0b,'tryamm:propertyverse-open');portal(30,-8,'SPACEVERSE PORTAL',0x3b82f6,'tryamm:spaceverse-open');portal(0,-42,'TIME MACHINE PORTAL',0x8b5cf6,'tryamm:chrono-open');giftBurst();for(let i=0;i<16;i++)vendor((Math.random()-.5)*42,34+Math.random()*14,`Pedestrian ${i+1}`,i%2?0x60a5fa:0xf472b6);for(let i=0;i<8;i++){const car=b(2.2,.8,4,i%2?0x22d3ee:0xec4899,.82);car.position.set(-38+i*11,.6,49+(i%2)*6);scene.add(car);anim.push(car)}const resize=()=>{if(!renderer||!camera)return;const w=innerWidth,h=Math.max(innerHeight,430);camera.aspect=w/h;camera.updateProjectionMatrix();renderer.setSize(w,h,false)};addEventListener('resize',resize);resize();hud()}
function updateLabels(){if(!camera)return;for(const l of labels){const p=l.pos.clone().project(camera);const visible=p.z>-1&&p.z<1;l.el.style.display=visible?'block':'none';if(visible){l.el.style.left=`${(p.x*.5+.5)*innerWidth}px`;l.el.style.top=`${(-p.y*.5+.5)*innerHeight}px`}}}
function animate(){if(active&&renderer&&scene&&camera){const t=performance.now()/1000;player.x=THREE.MathUtils.lerp(player.x,targetPlayer.x,.08);player.z=THREE.MathUtils.lerp(player.z,targetPlayer.z,.08);camera.position.lerp(new THREE.Vector3(player.x+19,14,player.z+25),.08);camera.lookAt(player.x,2.5,player.z-8);anim.forEach((o,i)=>{if(o.geometry instanceof THREE.TorusGeometry)o.rotation.z=t*.25+i*.03;if((o as any).userData?.baseY!==undefined)o.position.y=(o as any).userData.baseY+Math.sin(t*2+(o as any).userData.phase)*.8;if((o as THREE.Group).children?.length===2&&(o as THREE.Group).position.z>30)(o as THREE.Group).position.x+=Math.sin(t*.4+i)*.002});renderer.render(scene,camera);updateLabels()}raf=requestAnimationFrame(animate)}
export function installStreetVerseCreatorDistrict3D(){if(installed||typeof window==='undefined')return;installed=true;build();const controls=document.getElementById('tryamm-visible-creator-controls');const start=()=>{active=true;if(root)root.style.display='block';if(controls)controls.style.display='flex'};const stop=()=>{active=false;if(root)root.style.display='none';if(controls)controls.style.display='none'};window.addEventListener('tryamm:streetverse-enter',start);window.addEventListener('tryamm:streetverse-exit',stop);window.addEventListener('tryamm:streetverse-player-position',(e:Event)=>{const d=(e as CustomEvent<{x?:number;z?:number}>).detail||{};if(Number.isFinite(d.x)&&Number.isFinite(d.z))targetPlayer={x:Number(d.x),z:Number(d.z)}});window.addEventListener('tryamm:gift-sent',giftBurst);window.addEventListener('tryamm:pk-score',(e:Event)=>{const d=(e as CustomEvent<{left?:number;right?:number}>).detail||{};const score=labels.find(x=>x.el.textContent?.includes('TEAM A'));if(score)score.el.textContent=`TEAM A  ${d.left??0}  :  ${d.right??0}  TEAM B`});window.dispatchEvent(new CustomEvent('tryamm:creator-district-ready',{detail:{pkArena:true,liveScreen:true,storefronts:4,vendors:4,portals:3,traffic:8,pedestrians:16,questControl:true,accessibilityControl:true,translatedSpeechBubbleLabels:true}}));animate()}
