export type CharacterGroup='founder'|'security'|'global-security'|'legacy-kids'|'friends'|'artists'|'community'|'circle-park'|'chicago-music'|'chicago-music-history'|'mib-space'
export type MissionType='peacekeeping'|'mentorship'|'rescue'|'creative'|'education'|'community'|'exploration'|'disaster-response'|'cyber-safety'|'event-safety'

export type StreetVerseCharacter={
  id:string
  name:string
  title:string
  group:CharacterGroup
  missionIds:string[]
}

export type StreetVerseMission={
  id:string
  title:string
  description:string
  type:MissionType
  assignedTo:string[]
  rewardXP:number
  repeatable?:boolean
  global?:boolean
  localizesToCity?:boolean
}

export const STREETVERSE_CHARACTERS:StreetVerseCharacter[]=[
  {id:'cash-bae',name:'Cash Bae',title:'BIGO Host / Philadelphia Creator',group:'friends',missionIds:['creator-live-street-session']},
  {id:'stubbs',name:'Stubbs',title:'Founder / Living World Guide',group:'founder',missionIds:['peace-network','mentor-next','world-builder']},
  {id:'al-b',name:'Al B',title:'Security Guardian / Global Commander',group:'security',missionIds:['guardian-watch','safe-passage','conflict-cooldown','global-guardian-network','peace-corridor','missing-person-support','disaster-relief','safe-event-command','anti-trafficking-awareness','cyber-safety-relay']},
  {id:'global-security-force',name:'Global Security Force',title:'Al B Guardian Network',group:'global-security',missionIds:['global-guardian-network','peace-corridor','missing-person-support','disaster-relief','safe-event-command','anti-trafficking-awareness','cyber-safety-relay']},
  {id:'legacy-kids',name:'Legacy Kids',title:'Next Generation Crew',group:'legacy-kids',missionIds:['safe-route','future-builders','community-story']},
  {id:'friends',name:'Friends Crew',title:'Community Allies',group:'friends',missionIds:['neighborhood-help','event-support','welcome-team']},
  {id:'artists',name:'Artist Collective',title:'Creators / Performers',group:'artists',missionIds:['create-not-destroy','open-mic-peace','city-soundtrack']},
  {id:'circle-park-community',name:'Circle Park Community',title:'Chicago Onboarding / Community Legacy',group:'circle-park',missionIds:['circle-park-arrival','circle-park-home','circle-park-meet-neighbors','circle-park-three-verifications','circle-park-community-board','circle-park-og-history','circle-park-peace-choice','circle-park-open-chicago']},
  {id:'chicago-music',name:'Chicago Music Challenge',title:'Rappers / Singers / DJs / Producers',group:'chicago-music',missionIds:['chi-open-mic-qualifier','chi-flow-rhythm','chi-studio-session','chi-city-cypher','chi-holo-headliner']},
  {id:'chicago-music-history',name:'Chicago Music Time Machine',title:'History / Independent Music / Afrofuturism',group:'chicago-music-history',missionIds:['chi-history-sound-map','el-saturn-independent-label','sun-ra-chicago-time-machine','sun-ra-written-word','space-is-the-place-cinema','joyful-noise-documentary','arkestra-lineage','marshall-allen-spaceways','alton-abraham-archive','chi-history-to-future']},
  {id:'brad-markus-space',name:'Brad Markus',title:'MIB / Space Research Ambassador',group:'mib-space',missionIds:['brad-el-saturn-briefing','mib-saturn-signal','mib-space-tech-lab']},
]

export const STREETVERSE_MISSIONS:StreetVerseMission[]=[
  {id:'creator-live-street-session',title:'Go Live in StreetVerse',description:'Join Cash Bae’s Philadelphia creator welcome, prepare a creator activity, and capture an original StreetVerse Reel or LIVE moment.',type:'creative',assignedTo:['cash-bae','artists'],rewardXP:425,repeatable:true},
  {id:'peace-network',title:'Peace Network',description:'Build trust between neighborhoods, connect mentors with youth, and reduce conflict through dialogue and community events.',type:'peacekeeping',assignedTo:['stubbs'],rewardXP:450,repeatable:true},
  {id:'mentor-next',title:'Mentor the Next Generation',description:'Guide younger players through school, business, arts, technology, faith, sports, and life-skills challenges.',type:'mentorship',assignedTo:['stubbs','legacy-kids'],rewardXP:350,repeatable:true},
  {id:'world-builder',title:'Build the Block',description:'Restore a neighborhood space by coordinating local businesses, creators, residents, and services.',type:'community',assignedTo:['stubbs','friends','artists'],rewardXP:500,repeatable:true},
  {id:'guardian-watch',title:'Guardian Watch',description:'Al B leads a nonviolent safety patrol focused on prevention, de-escalation, safe escorts, incident reporting, and protecting community events.',type:'peacekeeping',assignedTo:['al-b','global-security-force'],rewardXP:500,repeatable:true,localizesToCity:true},
  {id:'safe-passage',title:'Safe Passage',description:'Create safe routes for kids and families moving between school, parks, transit, events, and home.',type:'rescue',assignedTo:['al-b','global-security-force','legacy-kids'],rewardXP:400,repeatable:true,localizesToCity:true},
  {id:'conflict-cooldown',title:'Conflict Cooldown',description:'Interrupt escalating disputes with dialogue, trusted adults, mediation, and emergency help when needed.',type:'peacekeeping',assignedTo:['al-b','global-security-force','stubbs','friends'],rewardXP:550,repeatable:true,localizesToCity:true},
  {id:'global-guardian-network',title:'Global Guardian Network',description:'Coordinate vetted local Guardian teams, community partners, accessibility resources, emergency contacts, and safe locations in the current city without vigilantism.',type:'peacekeeping',assignedTo:['al-b','global-security-force'],rewardXP:650,repeatable:true,global:true,localizesToCity:true},
  {id:'peace-corridor',title:'Peace Corridor',description:'Establish a temporary safe movement route during large events or neighborhood tension using de-escalation, trusted partners, medical access, reunification points, and official emergency services.',type:'rescue',assignedTo:['al-b','global-security-force','friends'],rewardXP:625,repeatable:true,global:true,localizesToCity:true},
  {id:'missing-person-support',title:'Missing Person Support',description:'Help organize verified information, community notices, safe search logistics, accessibility needs, and proper reporting to guardians or authorities. Players do not confront suspects or conduct vigilante investigations.',type:'rescue',assignedTo:['al-b','global-security-force','friends'],rewardXP:700,repeatable:true,global:true,localizesToCity:true},
  {id:'disaster-relief',title:'Guardian Disaster Relief',description:'Coordinate shelters, supplies, transportation, accessibility support, welfare checks, communications, and verified emergency resources during storms, fires, floods, outages, earthquakes, or other local emergencies.',type:'disaster-response',assignedTo:['al-b','global-security-force','friends','legacy-kids'],rewardXP:800,repeatable:true,global:true,localizesToCity:true},
  {id:'safe-event-command',title:'Safe Event Command',description:'Plan crowd safety, entrances, reunification points, accessibility routes, medical escalation, lost-child procedures, creator security, and peaceful closing procedures for StreetVerse and network events.',type:'event-safety',assignedTo:['al-b','global-security-force','friends','artists'],rewardXP:600,repeatable:true,global:true,localizesToCity:true},
  {id:'anti-trafficking-awareness',title:'Protect & Report',description:'Teach players to recognize possible exploitation indicators, protect privacy, preserve only lawful evidence, and route concerns to qualified local organizations or authorities. Players never pursue, entrap, or confront suspected traffickers.',type:'education',assignedTo:['al-b','global-security-force'],rewardXP:675,repeatable:true,global:true,localizesToCity:true},
  {id:'cyber-safety-relay',title:'Cyber Safety Relay',description:'Respond to account compromise, impersonation, doxxing, threats, fraud, or unsafe communications by preserving evidence, securing accounts, protecting victims, and escalating to Jacobie Vision, moderators, platforms, or authorities when appropriate.',type:'cyber-safety',assignedTo:['al-b','global-security-force'],rewardXP:575,repeatable:true,global:true,localizesToCity:true},
  {id:'safe-route',title:'Legacy Safe Route',description:'Map safe places, trusted businesses, libraries, schools, clinics, and community centers for younger players.',type:'education',assignedTo:['legacy-kids'],rewardXP:300,repeatable:true},
  {id:'future-builders',title:'Future Builders',description:'Complete learning missions in coding, cybersecurity, media, music, real estate, entrepreneurship, and public service.',type:'education',assignedTo:['legacy-kids'],rewardXP:425,repeatable:true},
  {id:'community-story',title:'Tell Our Story',description:'Interview elders, families, creators, and neighborhood builders and turn their stories into positive StreetVerse content.',type:'creative',assignedTo:['legacy-kids','artists'],rewardXP:325,repeatable:true},
  {id:'neighborhood-help',title:'Neighborhood Help',description:'Respond to community requests such as deliveries, accessibility support, cleanup, event setup, and resource navigation.',type:'community',assignedTo:['friends'],rewardXP:275,repeatable:true},
  {id:'event-support',title:'Community Event Support',description:'Help secure, staff, promote, and clean up peaceful community events.',type:'community',assignedTo:['friends','al-b','global-security-force'],rewardXP:300,repeatable:true},
  {id:'welcome-team',title:'Welcome Team',description:'Meet new players, teach the city systems, and connect them to safe activities, missions, and creator opportunities.',type:'mentorship',assignedTo:['friends'],rewardXP:250,repeatable:true},
  {id:'create-not-destroy',title:'Create, Don’t Destroy',description:'Turn neighborhood conflict into music, film, murals, dance, games, podcasts, and live performances instead of violence.',type:'creative',assignedTo:['artists'],rewardXP:450,repeatable:true},
  {id:'open-mic-peace',title:'Open Mic for Peace',description:'Host a performance event where rival groups compete through art, music, dance, debate, gaming, and storytelling instead of fighting.',type:'creative',assignedTo:['artists','stubbs','al-b','global-security-force'],rewardXP:600,repeatable:true},
  {id:'city-soundtrack',title:'City Soundtrack',description:'Create a location-specific soundtrack and visual reel that reflects the culture of the city you are visiting.',type:'creative',assignedTo:['artists'],rewardXP:375,repeatable:true},
  {id:'circle-park-arrival',title:'Welcome to Circle Park',description:'Enter the Chicago district, learn movement and accessibility controls, locate the community entrance and begin your StreetVerse neighborhood story.',type:'exploration',assignedTo:['circle-park-community','stubbs'],rewardXP:100,repeatable:false,localizesToCity:true},
  {id:'circle-park-home',title:'Find & Claim Your Apartment',description:'Locate an available fictional StreetVerse apartment, inspect the space and claim it as your personal Chicago home base. The claim is in-game only and conveys no real property or tenancy rights.',type:'exploration',assignedTo:['circle-park-community'],rewardXP:200,repeatable:false,localizesToCity:true},
  {id:'circle-park-meet-neighbors',title:'Meet the Neighborhood',description:'Meet fictional residents, discover businesses and community spaces, and build a starter friends list through consensual social interactions.',type:'community',assignedTo:['circle-park-community','friends'],rewardXP:200,repeatable:false,localizesToCity:true},
  {id:'circle-park-three-verifications',title:'Three Friend Verifications',description:'Ask three eligible StreetVerse friends to vouch that they know your in-game identity. Verification is a social trust mechanic, not legal identity verification, and must resist coercion, spam and duplicate accounts.',type:'community',assignedTo:['circle-park-community','friends'],rewardXP:300,repeatable:false,localizesToCity:true},
  {id:'circle-park-community-board',title:'Circle Park Community Board',description:'Complete a community orientation inspired by founder and board roles supplied by the project owner. Named real-person profiles require consent and verified role information before public portrayal.',type:'education',assignedTo:['circle-park-community'],rewardXP:300,repeatable:false,localizesToCity:true},
  {id:'circle-park-og-history',title:'Circle Park OG Stories',description:'Explore sourced neighborhood oral history, music, family, entrepreneurship and community change through archive-style story checkpoints. Separate verified history, attributed memories and fictionalized gameplay.',type:'education',assignedTo:['circle-park-community','artists'],rewardXP:400,repeatable:true,localizesToCity:true},
  {id:'circle-park-peace-choice',title:'Circle Park: Choose the Future',description:'A fictional neighborhood conflict branches into de-escalation, mediation, music, sports, jobs, business and community-building choices. No real gang recruitment, targeting, retaliation or operational instruction is included.',type:'peacekeeping',assignedTo:['circle-park-community','al-b','artists'],rewardXP:500,repeatable:true,localizesToCity:true},
  {id:'circle-park-open-chicago',title:'Open StreetVerse Chicago',description:'Final onboarding chapter: complete the home, friends, trust and community objectives to unlock the wider Chicago mission map, creator circuit, businesses, El Saturn history and other available districts.',type:'exploration',assignedTo:['circle-park-community','stubbs'],rewardXP:600,repeatable:false,localizesToCity:true},
  {id:'chi-open-mic-qualifier',title:'Chicago Open Mic Qualifier',description:'Choose an original or properly licensed beat, build a clean performance set, hit timing targets, and earn enough crowd energy to unlock the Chicago music circuit.',type:'creative',assignedTo:['chicago-music','artists'],rewardXP:300,repeatable:true,localizesToCity:true},
  {id:'chi-flow-rhythm',title:'Windy City Flow Challenge',description:'Complete an original rhythm-and-flow challenge with timing lanes, streaks, breath control, difficulty levels, accessibility assists, and a score based on player performance rather than copying any commercial rhythm game.',type:'creative',assignedTo:['chicago-music'],rewardXP:450,repeatable:true,localizesToCity:true},
  {id:'chi-studio-session',title:'Studio to StreetVerse',description:'Build an original track with a producer, record a performance, clear the required rights metadata, create cover art, and cut a promotional Reel.',type:'creative',assignedTo:['chicago-music','artists'],rewardXP:500,repeatable:true,localizesToCity:true},
  {id:'chi-city-cypher',title:'Chicago City Cypher',description:'Form a four-player crew across rapper, singer, DJ, producer, dancer or creator roles and complete rotating call-and-response, rhythm, collaboration and crowd objectives.',type:'creative',assignedTo:['chicago-music','artists'],rewardXP:650,repeatable:true,localizesToCity:true},
  {id:'chi-holo-headliner',title:'Holo Headliner',description:'Finale mission: qualify through the Chicago circuit, assemble a show, pass rights and safety checks, complete a Holo LIVE performance, capture a Reel, and finish the chapter with a cooperative headliner score.',type:'creative',assignedTo:['chicago-music','artists'],rewardXP:1000,repeatable:true,localizesToCity:true},
  {id:'chi-history-sound-map',title:'Sounds Born in Chicago',description:'Explore sourced Chicago music-history checkpoints and connect artists, neighborhoods, venues, labels and musical movements. Historical claims require provenance before display.',type:'creative',assignedTo:['chicago-music-history','artists'],rewardXP:350,repeatable:true,localizesToCity:true},
  {id:'el-saturn-independent-label',title:'Build It Yourself: El Saturn',description:'Learn how Sun Ra and Alton Abraham built an independent recording and distribution operation in Chicago, then complete an original TRYAMM label challenge covering recording, artwork, promotion, distribution and rights.',type:'creative',assignedTo:['chicago-music-history','chicago-music'],rewardXP:600,repeatable:true,localizesToCity:true},
  {id:'sun-ra-chicago-time-machine',title:'Sun Ra: Chicago to Saturn',description:'Enter a sourced Time Machine chapter about Sun Ra’s Chicago years, the Arkestra, Afrofuturist ideas and independent music-making. Archive facts stay distinct from fictional interactive scenes.',type:'creative',assignedTo:['chicago-music-history'],rewardXP:700,repeatable:true,localizesToCity:true},
  {id:'sun-ra-written-word',title:'Sun Ra: Words from Tomorrow',description:'Explore provenance-backed themes from Sun Ra’s published poetry, prose, broadsheets and lectures, then solve word, philosophy and music puzzles before creating an original future manifesto. Display only licensed excerpts or public-domain material; otherwise summarize and cite.',type:'creative',assignedTo:['chicago-music-history','mib-space'],rewardXP:650,repeatable:true,localizesToCity:true},
  {id:'space-is-the-place-cinema',title:'Space Is the Place: Cinema Mission',description:'Study the documented 1974 film as an Afrofuturist cultural artifact, then enter an original TRYAMM sci-fi mission about music, migration, technology and imagined futures. Film clips, soundtrack, characters and likenesses require rights clearance.',type:'creative',assignedTo:['chicago-music-history','mib-space'],rewardXP:850,repeatable:true,localizesToCity:true},
  {id:'joyful-noise-documentary',title:'A Joyful Noise: Archive Mission',description:'Use sourced documentary metadata, interviews and performance history to reconstruct how the Arkestra worked, rehearsed and performed, then lead an original ensemble challenge. Protected footage and recordings remain rights-gated.',type:'creative',assignedTo:['chicago-music-history','chicago-music'],rewardXP:750,repeatable:true,localizesToCity:true},
  {id:'arkestra-lineage',title:'The Arkestra: Living Lineage',description:'Trace the Arkestra from Sun Ra’s Chicago ensemble through its continuing performance tradition. Build a sourced timeline, identify instruments and stage ideas, then create an original ensemble arrangement inspired by the lesson without copying protected recordings.',type:'creative',assignedTo:['chicago-music-history','chicago-music'],rewardXP:650,repeatable:true,localizesToCity:true},
  {id:'marshall-allen-spaceways',title:'Marshall Allen: Spaceways Forward',description:'Follow Marshall Allen’s documented Arkestra history from the Chicago era forward, explore experimental electronic instrumentation and ensemble leadership, then complete an original future-sound challenge. Current leadership claims must be refreshed from verified sources before display.',type:'creative',assignedTo:['chicago-music-history','mib-space'],rewardXP:800,repeatable:true,localizesToCity:true},
  {id:'alton-abraham-archive',title:'Alton Abraham: Behind the Independent Machine',description:'Follow a provenance-backed archive trail about Alton Abraham as Sun Ra’s friend and business associate, his work with Saturn Records, promotion, distribution, research and Chicago operations; finish by building a modern ethical indie-release plan.',type:'creative',assignedTo:['chicago-music-history'],rewardXP:700,repeatable:true,localizesToCity:true},
  {id:'chi-history-to-future',title:'Chicago History to Future',description:'Finale: combine verified history with an original song, visual, business plan or performance concept that carries a Chicago musical influence into the player’s own future without copying protected recordings or artist likenesses.',type:'creative',assignedTo:['chicago-music-history','chicago-music','artists'],rewardXP:1000,repeatable:true,localizesToCity:true},
  {id:'brad-el-saturn-briefing',title:'Brad Markus: El Saturn Briefing',description:'Research Sun Ra and El Saturn through sourced archive clues, then compare documented history with Brad Markus’s attributed space and contact interpretations. Keep verified history, personal testimony and fictional gameplay visibly separated.',type:'creative',assignedTo:['mib-space','chicago-music-history'],rewardXP:550,repeatable:true,localizesToCity:true},
  {id:'mib-saturn-signal',title:'MIB: Signal from Saturn',description:'A fictional MIB investigation inspired by Afrofuturism: decode a strange signal, inspect evidence, interview fictional witnesses and decide which clues are scientific data, cultural history, testimony or deliberate game fiction.',type:'creative',assignedTo:['mib-space'],rewardXP:750,repeatable:true,localizesToCity:true},
  {id:'mib-space-tech-lab',title:'MIB: Space Age Technology Lab',description:'Build and test fictional future-tech prototypes through safe simulation challenges involving communications, robotics, sensors, navigation, energy efficiency and space-habitat systems; label speculative technology as speculative.',type:'creative',assignedTo:['mib-space'],rewardXP:900,repeatable:true,localizesToCity:true},
]

let installed=false
export function installStreetVerseCharacterMissionRuntime(){
  if(installed||typeof window==='undefined')return
  installed=true
  let city='Chicago'
  let country='United States'
  const publish=()=>window.dispatchEvent(new CustomEvent('tryamm:streetverse-character-registry',{detail:{
    schema:'tryamm.streetverse.characters.v2',
    characters:STREETVERSE_CHARACTERS,
    missions:STREETVERSE_MISSIONS.map(m=>m.localizesToCity?{...m,city,country}:m),
    guardianForce:{commander:'al-b',teamId:'global-security-force',city,country,doctrine:['prevention','de-escalation','rescue','safe-passage','protect-and-report','disaster-response','cyber-safety','event-safety','no-vigilantism'],allLanguages:true},
  }}))
  queueMicrotask(publish)
  window.addEventListener('tryamm:streetverse-character-request',publish)
  window.addEventListener('tryamm:world-location-changed',(e:Event)=>{
    const d=(e as CustomEvent<any>).detail||{}
    city=String(d.city||city)
    country=String(d.country||country)
    publish()
    window.dispatchEvent(new CustomEvent('tryamm:global-guardian-city-team',{detail:{commander:'al-b',teamId:'global-security-force',city,country,allLanguages:true}}))
  })
}
