type WorldState={hour:number;weather:'clear'|'rain'|'storm'|'fog';xp:number;level:number;waypoint?:{x:number;z:number;label?:string};activeJob?:string;districtRep:Record<string,number>;vehicle:{damage:number;drift:number;tuning:number}}
const KEY='tryamm_streetverse_openworld_systems_v1';let installed=false
const defaults=():WorldState=>({hour:20,weather:'clear',xp:0,level:1,districtRep:{},vehicle:{damage:0,drift:0,tuning:0}})
function read():WorldState{try{return {...defaults(),...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{return defaults()}}
function write(s:WorldState){localStorage.setItem(KEY,JSON.stringify(s));window.dispatchEvent(new CustomEvent('tryamm:streetverse-openworld-state',{detail:s}));return s}
function emit(name:string,detail:any){window.dispatchEvent(new CustomEvent(name,{detail}))}
function gainXp(amount:number,reason='activity'){const s=read();s.xp+=Math.max(0,amount);s.level=Math.floor(s.xp/500)+1;write(s);emit('tryamm:streetverse-xp',{xp:s.xp,level:s.level,amount,reason});const unlocks=[{level:2,skill:'double-jump'},{level:4,skill:'air-dash'},{level:6,skill:'focus-aim'},{level:8,skill:'parkour-sprint'}].filter(x=>x.level===s.level);unlocks.forEach(x=>emit('tryamm:streetverse-skill-unlock',x));return s}
function setWaypoint(d:any){const s=read();s.waypoint={x:Number(d?.x||0),z:Number(d?.z||0),label:d?.label};write(s);emit('tryamm:construct:targets',{targets:[{id:'streetverse-waypoint',kind:'route',title:d?.label||'Waypoint',x:s.waypoint.x,z:s.waypoint.z}]})}
function startJob(d:any){const s=read();s.activeJob=String(d?.job||'delivery');write(s);emit('tryamm:streetverse-job-state',{status:'active',job:s.activeJob,objective:d?.objective||'Complete the city job.'})}
function completeJob(d:any){const s=read();const job=s.activeJob||String(d?.job||'job');s.activeJob=undefined;write(s);gainXp(Number(d?.xp||100),job);emit('tryamm:streetverse-job-state',{status:'completed',job,rewardType:'xp-only',cashReward:false})}
function rememberNpc(d:any){const s=read();const district=String(d?.district||'central');s.districtRep[district]=(s.districtRep[district]||0)+Number(d?.delta||1);write(s);emit('tryamm:streetverse-district-state',{district,reputation:s.districtRep[district],memory:d?.memory||'interaction'})}
function updateVehicle(d:any){const s=read();s.vehicle.damage=Math.min(100,Math.max(0,s.vehicle.damage+Number(d?.damage||0)));s.vehicle.drift=Math.min(100,Math.max(0,Number(d?.drift??s.vehicle.drift)));s.vehicle.tuning=Math.min(5,Math.max(0,Number(d?.tuning??s.vehicle.tuning)));write(s);emit('tryamm:streetverse-vehicle-depth',{...s.vehicle,handlingModifier:1+s.vehicle.tuning*.05-damagePenalty(s.vehicle.damage)})}
const damagePenalty=(d:number)=>Math.min(.35,d/300)
function tickWorld(){const s=read();s.hour=(s.hour+.02)%24;const r=Math.random();if(r<.001)s.weather='storm';else if(r<.003)s.weather='rain';else if(r<.004)s.weather='fog';else if(r<.008)s.weather='clear';write(s);emit('tryamm:streetverse-world-time',{hour:s.hour,night:s.hour<6||s.hour>=19});emit('tryamm:streetverse-world-weather',{weather:s.weather,wet:s.weather==='rain'||s.weather==='storm',visibility:s.weather==='fog'?.55:1})}
export function installStreetVerseOpenWorldSystemsRuntime(){if(installed||typeof window==='undefined')return;installed=true;write(read());window.addEventListener('tryamm:streetverse-xp-gain',(e:Event)=>gainXp(Number((e as CustomEvent<any>).detail?.amount||50),(e as CustomEvent<any>).detail?.reason));window.addEventListener('tryamm:streetverse-waypoint-set',(e:Event)=>setWaypoint((e as CustomEvent<any>).detail||{}));window.addEventListener('tryamm:streetverse-job-start',(e:Event)=>startJob((e as CustomEvent<any>).detail||{}));window.addEventListener('tryamm:streetverse-job-complete',(e:Event)=>completeJob((e as CustomEvent<any>).detail||{}));window.addEventListener('tryamm:streetverse-npc-memory',(e:Event)=>rememberNpc((e as CustomEvent<any>).detail||{}));window.addEventListener('tryamm:streetverse-vehicle-update',(e:Event)=>updateVehicle((e as CustomEvent<any>).detail||{}));setInterval(tickWorld,2000);emit('tryamm:streetverse-openworld-systems-ready',{dayNight:true,weather:true,xpSkills:true,waypoints:true,cityJobs:true,npcMemory:true,vehicleDepth:true,source:'original-tryamm-implementation'})}
