type MilestoneStep={id:string;label:string;done:boolean;at?:string;evidence?:string}
type Receipt={id:string;completedAt:string;scope:string;steps:MilestoneStep[];worldSaveVerified:boolean;url:string}
const KEY='tryamm_streetverse_milestone_receipt_v1'
const WORLD_SAVE='tryamm.streetverse.omniworld.v1'
let installed=false
function verifyWorldSave(){try{const raw=localStorage.getItem(WORLD_SAVE);if(!raw)return false;const s=JSON.parse(raw);return Number.isFinite(Number(s.x))&&Number.isFinite(Number(s.z))&&Array.isArray(s.visited)}catch{return false}}
function saveReceipt(detail:any){const steps:Array<MilestoneStep>=Array.isArray(detail?.steps)?detail.steps:[];if(steps.length!==11||!steps.every(x=>x.done)||!verifyWorldSave())return null;const receipt:Receipt={id:`sv_receipt_${Date.now().toString(36)}`,completedAt:String(detail?.completedAt||new Date().toISOString()),scope:String(detail?.defensibleScope||'StreetVerse visible playable production milestone'),steps,worldSaveVerified:true,url:location.href};localStorage.setItem(KEY,JSON.stringify(receipt));show(receipt);window.dispatchEvent(new CustomEvent('tryamm:streetverse-milestone-receipt',{detail:receipt}));return receipt}
function readReceipt():Receipt|null{try{return JSON.parse(localStorage.getItem(KEY)||'null')}catch{return null}}
function show(receipt:Receipt){let el=document.getElementById('sv-milestone-receipt') as HTMLDivElement|null;if(!el){el=document.createElement('div');el.id='sv-milestone-receipt';Object.assign(el.style,{position:'fixed',left:'50%',top:'50%',transform:'translate(-50%,-50%)',zIndex:'2147483000',width:'min(520px,90vw)',maxHeight:'78vh',overflow:'auto',padding:'18px',borderRadius:'20px',background:'rgba(2,10,17,.97)',border:'1px solid #52f2ba',boxShadow:'0 20px 80px #000,0 0 36px rgba(82,242,186,.2)',color:'#fff',font:'700 12px system-ui'});document.body.appendChild(el)}el.innerHTML=`<div style="color:#52f2ba;font-size:11px;letter-spacing:.14em;font-weight:950">STREETVERSE PRODUCTION RECEIPT</div><h2 style="margin:7px 0 4px">11/11 PLAYABLE MILESTONE PASSED</h2><div style="opacity:.72;margin-bottom:10px">${receipt.completedAt} • world save verified</div>${receipt.steps.map((s,i)=>`<div style="display:flex;gap:8px;padding:6px 0;border-top:1px solid #ffffff12"><b style="color:#52f2ba">${i+1}. ✓</b><span><b>${s.label}</b><br><small style="opacity:.68">${s.evidence||'verified'}${s.at?` • ${s.at}`:''}</small></span></div>`).join('')}<button id="sv-receipt-close" style="margin-top:12px;border:1px solid #ffffff44;border-radius:999px;padding:8px 12px;background:#0c2530;color:#fff;font-weight:900">CLOSE RECEIPT</button>`;document.getElementById('sv-receipt-close')?.addEventListener('click',()=>el?.remove(),{once:true})}
export function getStreetVerseMilestoneReceipt(){return readReceipt()}
export function installStreetVerseMilestoneReceiptRuntime(){if(installed||typeof window==='undefined')return;installed=true;window.addEventListener('tryamm:streetverse-playable-milestone-complete',(e:Event)=>saveReceipt((e as CustomEvent<any>).detail));window.addEventListener('tryamm:streetverse-show-milestone-receipt',()=>{const r=readReceipt();if(r)show(r)});const prior=readReceipt();if(prior&&prior.worldSaveVerified)window.dispatchEvent(new CustomEvent('tryamm:streetverse-milestone-receipt-ready',{detail:{receiptId:prior.id,completedAt:prior.completedAt}}))}