type CartItem={id:string;name:string;price:number;storeId:string;qty:number}
type MissionStage='idle'|'accepted'|'shopping'|'checkout'|'bagged'|'assigned'|'delivery'|'handoff'|'complete'
let installed=false
let cart:CartItem[]=[]
let stage:MissionStage='idle'
let hud:HTMLDivElement|null=null
let mission:HTMLDivElement|null=null
const required=['Creator Hoodie','Holo Cap']
function money(n:number){return `$${n.toFixed(2)}`}
function emit(name:string,detail:Record<string,unknown>={}){window.dispatchEvent(new CustomEvent(name,{detail}))}
function total(){return cart.reduce((s,i)=>s+i.price*i.qty,0)}
function save(){try{localStorage.setItem('tryamm_streetverse_cart_v1',JSON.stringify({cart,stage}))}catch{}}
function load(){try{const x=JSON.parse(localStorage.getItem('tryamm_streetverse_cart_v1')||'{}');if(Array.isArray(x.cart))cart=x.cart;if(x.stage)stage=x.stage}catch{}}
function button(label:string,onClick:()=>void){const b=document.createElement('button');b.textContent=label;Object.assign(b.style,{border:'1px solid #4fe3ff77',background:'#0b2433',color:'#fff',borderRadius:'10px',padding:'8px 10px',fontWeight:'900',cursor:'pointer'});b.onclick=onClick;return b}
function render(){if(!hud||!mission)return;hud.innerHTML='';const title=document.createElement('div');title.innerHTML=`<b>🛒 STREETVERSE CART</b><br><span style="font-size:12px;color:#9fb3c8">${cart.reduce((s,i)=>s+i.qty,0)} items • ${money(total())}</span>`;hud.append(title);const list=document.createElement('div');Object.assign(list.style,{marginTop:'8px',display:'grid',gap:'6px'});cart.forEach(i=>{const r=document.createElement('div');r.textContent=`${i.qty}× ${i.name} • ${money(i.price*i.qty)}`;Object.assign(r.style,{fontSize:'12px',color:'#e5f3ff'});r.onclick=()=>{if(i.qty>1)i.qty--;else cart=cart.filter(x=>x.id!==i.id);save();render()};list.append(r)});hud.append(list);const row=document.createElement('div');Object.assign(row.style,{display:'flex',gap:'6px',flexWrap:'wrap',marginTop:'9px'});row.append(button('CLEAR',()=>{cart=[];save();render()}),button('HOLO DELIVERY',()=>emit('tryamm:holo-delivery-open',{source:'streetverse-cart'})));hud.append(row)
 const have=new Set(cart.map(i=>i.name));const found=required.filter(x=>have.has(x)).length;mission.innerHTML='';const h=document.createElement('div');h.innerHTML=`<b>🛍 SHOPPING MISSION</b><br><span style="font-size:12px;color:#9fb3c8">${stage.toUpperCase()} • ${found}/${required.length} order items</span>`;mission.append(h);const steps=document.createElement('div');steps.textContent=`Order: ${required.map(x=>have.has(x)?'✓ ':'○ ').join('')}${required.join(' + ')}`;Object.assign(steps.style,{fontSize:'12px',marginTop:'7px',color:'#dbeafe'});mission.append(steps);const actions=document.createElement('div');Object.assign(actions.style,{display:'flex',gap:'6px',flexWrap:'wrap',marginTop:'9px'});if(stage==='idle'||stage==='complete')actions.append(button('ACCEPT ORDER',()=>{stage='accepted';emit('tryamm:shopping-mission-start',{required});save();render()}));if(['accepted','shopping'].includes(stage))actions.append(button('SHOP',()=>{stage='shopping';save();render()}));if(found===required.length&&['accepted','shopping'].includes(stage))actions.append(button('CHECKOUT',()=>{stage='checkout';emit('tryamm:shopping-checkout-ready',{cart,total:total()});save();render()}));if(stage==='checkout')actions.append(button('BAG + STAGE',()=>{stage='bagged';emit('tryamm:shopping-order-bagged',{cart});save();render()}));if(stage==='bagged')actions.append(button('ASSIGN HOLO DELIVERY',()=>{stage='assigned';emit('tryamm:holo-delivery-order-create',{mode:'demo',items:cart,total:total(),proofRequired:true});emit('tryamm:holo-delivery-open',{source:'streetverse-shopping-mission'});save();render()}));if(stage==='assigned')actions.append(button('START DELIVERY',()=>{stage='delivery';emit('tryamm:shopping-delivery-start',{vehicle:'car',etaMinutes:8});save();render()}));if(stage==='delivery')actions.append(button('CUSTOMER HANDOFF',()=>{stage='handoff';emit('tryamm:shopping-delivery-handoff',{proof:'demo-confirmation'});save();render()}));if(stage==='handoff')actions.append(button('COMPLETE + XP',()=>{stage='complete';emit('tryamm:mission-completed',{missionId:'streetverse-shopping-delivery',title:'Holo Shopping Delivery',rewardXp:250,mode:'demo'});emit('tryamm:shopping-delivery-complete',{items:cart.length,total:total()});cart=[];save();render()}));mission.append(actions)}
function build(){hud=document.createElement('div');mission=document.createElement('div');for(const el of [hud,mission])Object.assign(el!.style,{position:'fixed',zIndex:'20020',width:'min(320px,88vw)',background:'rgba(3,10,20,.94)',border:'1px solid #4fe3ff66',borderRadius:'16px',padding:'12px',color:'#fff',boxShadow:'0 18px 60px #0009',fontFamily:'system-ui',display:'none'});Object.assign(hud.style,{left:'12px',bottom:'86px'});Object.assign(mission.style,{left:'12px',bottom:'230px'});document.body.append(hud,mission);render()}
export function installStreetVerseShoppingDeliveryMissionRuntime(){if(installed||typeof window==='undefined')return;installed=true;load();build();window.addEventListener('tryamm:streetverse-enter',()=>{if(hud)hud.style.display='block';if(mission)mission.style.display='block';render()});window.addEventListener('tryamm:streetverse-exit',()=>{if(hud)hud.style.display='none';if(mission)mission.style.display='none'});window.addEventListener('tryamm:marketplace-item-picked-up',(e:Event)=>{const d=(e as CustomEvent<any>).detail||{};const id=String(d.productId||d.name||Date.now());const hit=cart.find(x=>x.id===id);if(hit)hit.qty++;else cart.push({id,name:String(d.name||'Item'),price:Number(d.price||0),storeId:String(d.storeId||'unknown'),qty:1});if(stage==='accepted')stage='shopping';save();render();emit('tryamm:shopping-cart-changed',{cart,total:total()})});window.addEventListener('tryamm:marketplace-item-put-down',(e:Event)=>{const d=(e as CustomEvent<any>).detail||{};cart=cart.filter(x=>x.id!==String(d.productId||''));save();render()});window.addEventListener('tryamm:checkout-intent',()=>{if(stage==='shopping')stage='checkout';save();render()});window.addEventListener('tryamm:holo-delivery-open',()=>{const click=()=>document.querySelector<HTMLButtonElement>('[aria-label="Open Holo Delivery"]')?.click();queueMicrotask(click)});emit('tryamm:shopping-delivery-runtime-ready',{cart:true,shoppingMission:true,substitutions:'event-ready',bagging:true,staging:true,holoDelivery:true,handoffProof:true,demoRewards:true})}