import * as THREE from 'three'
import type { ConstructState,ConstructTarget } from './StreetVerseWorldAwareConstructRuntime'

let installed=false
let renderer:THREE.WebGLRenderer|null=null
let scene:THREE.Scene|null=null
let camera:THREE.PerspectiveCamera|null=null
let mount:HTMLElement|null=null
let raf=0
let state:ConstructState|null=null
let routeTarget:ConstructTarget|null=null
let scanStart=0
const world=new THREE.Group(),routeGroup=new THREE.Group(),arrowGroup=new THREE.Group(),cardGroup=new THREE.Group(),bennyGroup=new THREE.Group()
let scanRing:THREE.Mesh|null=null

function holoMat(color:number,opacity=.72){return new THREE.MeshBasicMaterial({color,transparent:true,opacity,depthWrite:false,blending:THREE.AdditiveBlending,toneMapped:false})}
function skinHoloMat(){return new THREE.MeshStandardMaterial({color:0x6f3f2d,emissive:0x1c7892,emissiveIntensity:.34,roughness:.58,metalness:.04,transparent:true,opacity:.78,depthWrite:false})}
function lineMat(color:number,opacity=.9){return new THREE.LineBasicMaterial({color,transparent:true,opacity,blending:THREE.AdditiveBlending,toneMapped:false})}
function clearGroup(group:THREE.Group){while(group.children.length){const o=group.children.pop()!;o.traverse(n=>{const m=n as THREE.Mesh;if(m.geometry)m.geometry.dispose();const mat=(m as any).material;if(Array.isArray(mat))mat.forEach(x=>x?.dispose?.());else mat?.dispose?.()})}}
function findMount(){return document.querySelector('[data-streetverse-construct-root]') as HTMLElement|null||document.querySelector('#tryamm-benny-construct-hologram')?.parentElement||document.body}
function ensureRenderer(){if(renderer&&scene&&camera&&mount?.isConnected)return true;mount=findMount();if(!mount)return false;scene=new THREE.Scene();camera=new THREE.PerspectiveCamera(58,1,.1,500);renderer=new THREE.WebGLRenderer({alpha:true,antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.35));renderer.setClearColor(0x000000,0);renderer.domElement.dataset.constructFreeSpace='true';Object.assign(renderer.domElement.style,{position:'fixed',inset:'0',zIndex:'19990',width:'100%',height:'100%',pointerEvents:'none'});document.body.appendChild(renderer.domElement);scene.add(world);world.add(routeGroup,arrowGroup,cardGroup,bennyGroup);const grid=new THREE.GridHelper(240,48,0x46eaff,0x173b55);const mats=Array.isArray(grid.material)?grid.material:[grid.material];mats.forEach(m=>{m.transparent=true;m.opacity=.16});grid.position.y=.04;world.add(grid);for(const scale of [1,1.65]){const ring=new THREE.Mesh(new THREE.RingGeometry(24,24.12,96),holoMat(0x54e8ff,.2));ring.rotation.x=-Math.PI/2;ring.position.y=.06;ring.scale.setScalar(scale);world.add(ring)}buildBenny();return true}
function buildBenny(){
 clearGroup(bennyGroup);const cyan=0x5cecff,purple=0xb687ff,gold=0xffd782,skin=skinHoloMat()
 // Original TRYAMM Black female OmniHost silhouette: warm deep skin, elegant proportions, natural textured hair and Construct couture.
 const torso=new THREE.Mesh(new THREE.CapsuleGeometry(.46,1.25,8,16),new THREE.MeshStandardMaterial({color:0x17142d,emissive:0x165f79,emissiveIntensity:.52,roughness:.32,metalness:.45,transparent:true,opacity:.76,depthWrite:false}));torso.position.y=1.55;torso.scale.set(1,1,.72);bennyGroup.add(torso)
 const neck=new THREE.Mesh(new THREE.CylinderGeometry(.14,.17,.3,12),skin);neck.position.y=2.42;bennyGroup.add(neck)
 const head=new THREE.Mesh(new THREE.SphereGeometry(.4,24,20),skin);head.position.y=2.82;head.scale.set(.88,1.08,.9);bennyGroup.add(head)
 const hairMat=new THREE.MeshStandardMaterial({color:0x151116,emissive:0x421d58,emissiveIntensity:.25,roughness:.82,transparent:true,opacity:.9,depthWrite:false})
 const hair=new THREE.Group();for(let i=0;i<18;i++){const a=(i/18)*Math.PI*2,r=.39+((i%3)*.025),curl=new THREE.Mesh(new THREE.SphereGeometry(.13,10,8),hairMat);curl.position.set(Math.cos(a)*r,2.99+Math.sin(i*1.7)*.09,Math.sin(a)*r*.78);hair.add(curl)};bennyGroup.add(hair)
 const skirt=new THREE.Mesh(new THREE.CylinderGeometry(.46,.68,.95,18,1,true),holoMat(purple,.34));skirt.position.y=.72;bennyGroup.add(skirt)
 for(const x of [-.62,.62]){const arm=new THREE.Mesh(new THREE.CapsuleGeometry(.11,.88,5,10),skin);arm.position.set(x,1.62,0);arm.rotation.z=x>0?-.16:.16;bennyGroup.add(arm)}
 for(const x of [-.22,.22]){const leg=new THREE.Mesh(new THREE.CapsuleGeometry(.13,.9,5,10),holoMat(cyan,.34));leg.position.set(x,.25,0);bennyGroup.add(leg)}
 const collar=new THREE.Mesh(new THREE.TorusGeometry(.37,.035,8,32),holoMat(gold,.82));collar.rotation.x=Math.PI/2;collar.position.y=2.34;bennyGroup.add(collar)
 const halo=new THREE.Mesh(new THREE.TorusGeometry(.64,.035,8,40),holoMat(purple,.82));halo.rotation.x=Math.PI/2;halo.position.y=3.48;bennyGroup.add(halo)
 for(const y of [.18,1.48,2.82]){const ring=new THREE.Mesh(new THREE.TorusGeometry(.72,.025,8,36),holoMat(cyan,.5));ring.rotation.x=Math.PI/2;ring.position.y=y;bennyGroup.add(ring)}
 bennyGroup.userData={name:'Benny',identity:'original TRYAMM Black female holographic OmniHost',presentation:['beautiful','elegant','confident','futuristic','expressive'],physicalProjection:false}
}
function rebuildRoute(){clearGroup(routeGroup);clearGroup(arrowGroup);if(!state?.active||!routeTarget)return;const from=new THREE.Vector3(state.player.x,.09,state.player.z),to=new THREE.Vector3(routeTarget.x,.09,routeTarget.z),points:THREE.Vector3[]=[];const steps=Math.max(8,Math.ceil(from.distanceTo(to)/4));for(let i=0;i<=steps;i++){const t=i/steps,p=from.clone().lerp(to,t);p.y=.09+Math.sin(t*Math.PI)*.05;points.push(p)}routeGroup.add(new THREE.Line(new THREE.BufferGeometry().setFromPoints(points),lineMat(0x48ecff,.95)));for(let i=2;i<points.length-1;i+=3){const p=points[i],dir=points[Math.min(i+1,points.length-1)].clone().sub(p).normalize(),arrow=new THREE.Mesh(new THREE.ConeGeometry(.28,.75,10),holoMat(0x7df8ff,.86));arrow.position.copy(p).add(new THREE.Vector3(0,.35,0));arrow.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),dir);arrowGroup.add(arrow)}const beacon=new THREE.Mesh(new THREE.CylinderGeometry(.18,.7,7,18,1,true),holoMat(0xffd75c,.22));beacon.position.set(to.x,3.5,to.z);arrowGroup.add(beacon);const top=new THREE.Mesh(new THREE.ConeGeometry(.7,1.5,12),holoMat(0xffe778,.78));top.position.set(to.x,7.5,to.z);top.rotation.x=Math.PI;arrowGroup.add(top)}
function makeCard(target:ConstructTarget,index:number){const g=new THREE.Group(),plate=new THREE.Mesh(new THREE.PlaneGeometry(3.8,1.25),holoMat(index%2?0x8b7dff:0x42e7ff,.22));plate.position.y=2.9;g.add(plate);const pin=new THREE.Mesh(new THREE.CylinderGeometry(.025,.025,2.2,6),holoMat(0x9af6ff,.45));pin.position.y=1.55;g.add(pin);const ring=new THREE.Mesh(new THREE.TorusGeometry(.48,.035,8,24),holoMat(0x62efff,.7));ring.rotation.x=Math.PI/2;ring.position.y=.35;g.add(ring);g.position.set(target.x,0,target.z);g.userData.label=target.label;return g}
function rebuildCards(){clearGroup(cardGroup);if(state?.active)state.targets.slice(0,10).forEach((t,i)=>cardGroup.add(makeCard(t,i)))}
function startScan(){scanStart=performance.now();if(!scanRing){scanRing=new THREE.Mesh(new THREE.RingGeometry(1.8,2.05,96),holoMat(0x65efff,.82));scanRing.rotation.x=-Math.PI/2;world.add(scanRing)}}
function animate(){if(!ensureRenderer()){raf=requestAnimationFrame(animate);return}const w=innerWidth,h=innerHeight;camera!.aspect=w/Math.max(1,h);camera!.updateProjectionMatrix();renderer!.setSize(w,h,false);const p=state?.player||{x:0,z:58},now=performance.now();camera!.position.lerp(new THREE.Vector3(p.x+17,13,p.z+22),.08);camera!.lookAt(p.x,1.5,p.z);bennyGroup.position.set(p.x+3,.15+Math.sin(now*.003)*.08,p.z+2.5);bennyGroup.rotation.y=-.35+Math.sin(now*.0014)*.12;bennyGroup.scale.setScalar(1+Math.sin(now*.004)*.012);arrowGroup.children.forEach((o,i)=>{o.position.y+=Math.sin(now*.004+i)*.002});cardGroup.children.forEach((o,i)=>{o.lookAt(camera!.position.x,o.position.y+2.7,camera!.position.z);o.position.y=.15+Math.sin(now*.002+i)*.12});if(scanRing){const age=(now-scanStart)/1000;if(age<1.4&&state?.active){scanRing.visible=true;scanRing.position.set(p.x,.08,p.z);scanRing.scale.setScalar(1+age*13);(scanRing.material as THREE.MeshBasicMaterial).opacity=Math.max(0,.82-age*.58)}else scanRing.visible=false}renderer!.render(scene!,camera!);raf=requestAnimationFrame(animate)}
function onState(next:ConstructState){state=next;if(routeTarget)routeTarget=next.targets.find(t=>t.id===routeTarget!.id)||routeTarget;rebuildCards();rebuildRoute()}
export function installStreetVerseFreeSpaceConstruct3D(){if(installed||typeof window==='undefined')return;installed=true;window.addEventListener('tryamm:construct:state',(e:Event)=>onState((e as CustomEvent<ConstructState>).detail));window.addEventListener('tryamm:construct:route',(e:Event)=>{const d=(e as CustomEvent<{to?:ConstructTarget}>).detail||{};if(d.to){routeTarget=d.to;rebuildRoute()}});window.addEventListener('tryamm:construct:scan-result',()=>startScan());window.addEventListener('tryamm:streetverse-exit',()=>{if(renderer?.domElement)renderer.domElement.style.display='none'});window.addEventListener('tryamm:streetverse-enter',()=>{ensureRenderer();if(renderer?.domElement)renderer.domElement.style.display='block'});ensureRenderer();raf=requestAnimationFrame(animate);window.dispatchEvent(new CustomEvent('tryamm:construct:free-space-3d-ready',{detail:{simulatedFreeSpaceHologram:true,physicalProjection:false,benny:{identity:'original TRYAMM Black female holographic OmniHost',presentation:['beautiful','elegant','confident','futuristic','expressive'],hair:'natural-textured-holographic'},visuals:['depth-layers','floating-panels','world-anchors','translucent-benny','scanning-grid','3d-pointers','vector-pavement-trail','mission-arrows','chronicle-cards','construct-scan-pulse']}}))}
