type Transport='foot'|'car'|'motorcycle'|'boat'|'helicopter'|'subway'|'bus'|'taxi'
type CityLife={transport:Transport;wanted:number;discoveries:string[];garage:string[];photoMode:boolean;graphics:'low'|'balanced'|'high';event?:string;transit?:{line:string;stop:string};streak:number}
const KEY='tryamm_streetverse_city_life_v1';let installed=false
const base=():CityLife=>({transport:'foot',wanted:0,discoveries:[],garage:['street-sedan'],photoMode:false,graphics:'balanced',streak:0})
function read():CityLife{try{return {...base(),...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{return base()}}
function save(s:CityLife){localStorage.setItem(KEY,JSON.stringify(s));window.dispatchEvent(new CustomEvent('tryamm:streetverse-city-life-state',{detail:s}));return s}
function on(name:string,fn:(d:any)=>void){window.addEventListener(name,(e:Event)=>fn((e as CustomEvent<any>).detail||{}))}
function emit(name:string,detail:any){window.dispatchEvent(new CustomEvent(name,{detail}))}
function setTransport(d:any){const s=read();const allowed:Transport[]=['foot','car','motorcycle','boat','helicopter','subway','bus','taxi'];const mode=allowed.includes(d.mode)?d.mode:'foot';s.transport=mode;save(s);emit('tryamm:streetverse-transport-state',{mode,enterable:['car','motorcycle','boat','helicopter','subway','bus','taxi'].includes(mode)})}
function response(d:any){const s=read();s.wanted=Math.max(0,Math.min(5,s.wanted+Number(d.delta||1)));save(s);emit('tryamm:streetverse-response-state',{level:s.wanted,fictional:true,behavior:s.wanted===0?'normal':s.wanted<3?'observe-and-route':'pursuit-gameplay'});if(s.wanted>0)setTimeout(()=>{const n=read();n.wanted=Math.max(0,n.wanted-1);save(n)},15000)}
function discover(d:any){const s=read();const id=String(d.id||d.label||'location');if(!s.discoveries.includes(id)){s.discoveries.push(id);s.streak++;save(s);emit('tryamm:streetverse-xp-gain',{amount:25,reason:'discovery'});emit('tryamm:streetverse-discovery',{id,label:d.label||id,total:s.discoveries.length,streak:s.streak})}}
function garage(d:any){const s=read();const id=String(d.id||'vehicle');if(!s.garage.includes(id))s.garage.push(id);save(s);emit('tryamm:streetverse-garage-state',{vehicles:s.garage,selected:id})}
function transit(d:any){const s=read();s.transit={line:String(d.line||'Loop'),stop:String(d.stop||'Central')};s.transport=(d.mode==='bus'?'bus':d.mode==='taxi'?'taxi':'subway');save(s);emit('tryamm:streetverse-transit-state',{...s.transit,mode:s.transport,status:'boarding'});emit('tryamm:construct:targets',{targets:[{id:'transit-destination',kind:'route',title:String(d.destination||'Next stop'),x:Number(d.x||0),z:Number(d.z||0)}]})}
function settings(d:any){const s=read();if(typeof d.photoMode==='boolean')s.photoMode=d.photoMode;if(['low','balanced','high'].includes(d.graphics))s.graphics=d.graphics;save(s);emit('tryamm:streetverse-render-profile',{photoMode:s.photoMode,graphics:s.graphics,mobileSafe:s.graphics!=='high'})}
function worldEvent(d:any){const s=read();s.event=String(d.event||['street-race','creator-challenge','boat-race','parkour-run','photo-hunt'][Math.floor(Math.random()*5)]);save(s);emit('tryamm:streetverse-world-event-state',{event:s.event,status:'active',cashReward:false,reward:'XP + cosmetics'});emit('tryamm:streetverse-xp-gain',{amount:50,reason:'world-event-joined'})}
export function installStreetVerseCityLifeRuntime(){if(installed||typeof window==='undefined')return;installed=true;save(read());on('tryamm:streetverse-transport-set',setTransport);on('tryamm:streetverse-response-change',response);on('tryamm:streetverse-discover',discover);on('tryamm:streetverse-garage-add',garage);on('tryamm:streetverse-transit-board',transit);on('tryamm:streetverse-settings',settings);on('tryamm:streetverse-world-event-start',worldEvent);emit('tryamm:streetverse-city-life-ready',{motorcycles:true,boats:true,helicopterFramework:true,subway:true,bus:true,taxi:true,fictionalResponseLevels:true,discovery:true,garage:true,photoMode:true,lowGraphics:true,worldEvents:true,gamepadEventReady:true,cashRewards:false})}