type CartItem={id:string;name:string;price:number;storeId:string;qty:number}
type MissionStage='idle'|'accepted'|'shopping'|'checkout'|'bagged'|'assigned'|'delivery'|'handoff'|'complete'
let installed=false,streetverseActive=false,panelOpen=false
let cart:CartItem[]=[]
let stage:MissionStage='idle'
let dock:HTMLButtonElement|null=null,hud:HTMLDivElement|null=null,mission:HTMLDivElement|null=null
const required=['Creator Hoodie','Holo Cap']
function money(n:number){return `$${n.toFixed(2)}`}
function emit(name:string,detail:Record<string,unknown>={}){window.dispatchEvent(new CustomEvent(name,{detail}))}
function total(){return cart.reduce((s,i)=>s+i.price*i.qty,0)}
function save(){try{localStorage.setItem('tryamm_streetverse_cart_v1',JSON.stringify({cart,stage}))}catch{}}
function load(){try{const x=JSON.parse(localStorage.getItem('tryamm_streetverse_cart_v1')||'{}');if(Array.isArray(x.cart))cart=x.cart;if(x.stage)stage=x.stage}catch{}}
function button(label:string,onClick:()=>void){const b=document.createElement('button');b.textContent=label;Object.assign(b.style,{border:'1px solid #4fe3ff77',background:'#0b2433',color:'#fff',borderRadius:'10px',padding:'8px 10px',fontWeight:'900',cursor:'pointer'});b.onclick=onClick;return b}
function syncVisibility(){if(!dock||!hud||!mission)return;dock.style.display=streetverseActive?'block':'none';const show=streetverseActive&&panelOpen;hud.style.display=show?'block':'none';mission.style.display=show?'block':'none';dock.textContent=panelOpen?'✕ SHOP':'🛒 SHOP';dock.setAttribute('aria-expanded',String(panelOpen))}
function render(){if(!hud||!mission||!dock)return;dock.title=`StreetVerse shopping • ${cart.reduce((s,i)=>s+i.qty,0)} items`;hud.innerHTML='';const title=document.createElement('div');title.innerHTML=`<b>🛒 STREETVERSE CART</b><br><span style="font-size:12px;color:#9fb3c8">${cart.reduce((s,i)=>s+i.qty,0)} items • ${money(total())}</span>`;hud.append(title);const list=document.createElement('div');Object.assign(list.style,{marginTop:'8px',display:'grid',gap:'6px',maxHeight:'110px',overflow:'auto'});cart.forEach(i=>{const r=document.createElement('button');r.textContent=`${i.qty}× ${i.name} • ${money(i.price*i.qty)}`;Object.assign(r.style,{fontSize:'12px',color:'#e5f3ff',background:'transparent',border:0,textAlign:'left',padding:'3px 0'});r.onclick=()=>{if(i.qty>1)i.qty--;else cart=cart.filter(x=>x.id!==i.id);save();render()};list.append(r)});hud.append(list);const row=document.createElement('div');Object.assign(row.style,{display:'flex',gap:'6px',flexWrap:'wrap',marginTop:'9px'});row.append(button('CLEAR',()=>{cart=[];save();render()}),button('HOLO DELIVERY',()=>emit('tryamm:holo-delivery-open',{source:'streetverse-cart'})));hud.append(row)
 const have=new Set(cart.map(i=>i.name));const found=required.filter(x=>have.has(x)).length;mission.innerHTML='';const h=document.createElement('div');h.innerHTML=`<b>🛍 SHOPPING MISSION</b><br><span style="font-size:12px;color:#9fb3c8">${stage.toUpperCase()} • ${found}/${required.length} order items</span>`;mission.append(h);const actions=document.createElement('div');Object.assign(actions.style,{display:'flex',gap:'6px',flexWrap:'wrap',marginTop:'9px'});if(stage==='idle'||stage==='complete')actions.append(button('ACCEPT ORDER',()=>{stage='accepted';emit('tryamm:shopping-mission-start',{required});save();render()}));if(['accepted','shopping'].includes(stage))actions.append(button('SHOP',()=>{stage='shopping';save();render()}));if(found===required.length&&['accepted','shopping'].includes(stage))actions.append(button('CHECKOUT',()=>{stage='checkout';emit('tryamm:shopping-checkout-ready',{cart,total:total()});save();render()}));if(stage==='checkout')actions.append(button('BAG + STAGE',()=>{stage='bagged';emit('tryamm:shopping-order-bagged',{cart});save();render()}));if(stage==='bagged')actions.append(button('ASSIGN DELIVERY',()=>{stage='assigned';emit('tryamm:holo-delivery-order-create',{mode:'demo',items:cart,total:total(),proofRequired:true});emit('tryamm:holo-delivery-open',{source:'streetverse-shopping-mission'});save();render()}));if(stage==='assigned')actions.append(button('START DELIVERY',()=>{stage='delivery';emit('tryamm:shopping-delivery-start',{vehicle:'car',etaMinutes:8});save();render()}));if(stage==='delivery')actions.append(button('HANDOFF',()=>{stage='handoff';emit('tryamm:shopping-delivery-handoff',{proof:'demo-confirmation'});save();render()}));if(stage==='handoff')actions.append(button('COMPLETE + XP',()=>{stage='complete';emit('tryamm:mission-completed',{missionId:'streetverse-shopping-delivery',title:'Holo Shopping Delivery',rewardXp:250,mode:'demo'});emit('tryamm:shopping-delivery-complete',{items:cart.length,total:total()});cart=[];save();render()}));mission.append(actions);syncVisibility()}
function build(){dock=document.createElement('button');dock.type='button';dock.setAttribute('aria-label','Open StreetVerse shopping mission');Object.assign(dock.style,{position:'fixed',right:'12px',bottom:'86px',zIndex:'16040',display:'none',border:'1px solid #4fe3ffaa',borderRadius:'999px',padding:'10px 13px',background:'rgba(3,18,30,.94)',color:'#fff',fontWeight:'950',boxShadow:'0 10px 28px #0008',cursor:'pointer',touchAction:'manipulation'});dock.onclick=()=>{panelOpen=!panelOpen;syncVisibility()};hud=document.createElement('div');mission=document.createElement('div');for(const el of [hud,mission])Object.assign(el!.style,{position:'fixed',zIndex:'16035',width:'min(300px,calc(100vw - 24px))',maxHeight:'34vh',overflow:'auto',background:'rgba(3,10,20,.96)',border:'1px solid #4fe3ff66',borderRadius:'14px',padding:'10px',color:'#fff',boxShadow:'0 14px 42px #0009',fontFamily:'system-ui',display:'none',pointerEvents:'auto'});Object.assign(hud.style,{right:'12px',bottom:'132px'});Object.assign(mission.style,{right:'12px',bottom:'min(44vh,330px)'});document.body.append(dock,hud,mission);render()}
export function installStreetVerseShoppingDeliveryMissionRuntime(){if(installed||typeof window==='undefined')return;installed=true;load();build();window.addEventListener('tryamm:streetverse-enter',()=>{streetverseActive=true;panelOpen=false;render()});window.addEventListener('tryamm:streetverse-exit',()=>{streetverseActive=false;panelOpen=false;syncVisibility()});window.addEventListener('tryamm:marketplace-item-picked-up',(e:Event)=>{const d=(e as CustomEvent<any>).detail||{};const id=String(d.productId||d.name||Date.now());const hit=cart.find(x=>x.id===id);if(hit)hit.qty++;else cart.push({id,name:String(d.name||'Item'),price:Number(d.price||0),storeId:String(d.storeId||'unknown'),qty:1});if(stage==='accepted')stage='shopping';save();render();emit('tryamm:shopping-cart-changed',{cart,total:total()})});window.addEventListener('tryamm:marketplace-item-put-down',(e:Event)=>{const d=(e as CustomEvent<any>).detail||{};cart=cart.filter(x=>x.id!==String(d.productId||''));save();render()});window.addEventListener('tryamm:checkout-intent',()=>{if(stage==='shopping')stage='checkout';save();render()});window.addEventListener('tryamm:holo-delivery-open',()=>{queueMicrotask(()=>document.querySelector<HTMLButtonElement>('[aria-label="Open Holo Delivery"]')?.click())});emit('tryamm:shopping-delivery-runtime-ready',{cart:true,shoppingMission:true,compactHud:true,nonBlocking:true,substitutions:'event-ready',bagging:true,staging:true,holoDelivery:true,handoffProof:true,demoRewards:true})}