type ActivityState={active?:string;completed:number;collectibles:string[];shops:Record<string,number>;npcMood:Record<string,string>;lastInteraction?:string}
const KEY='tryamm_streetverse_activity_v1';let installed=false
const base=():ActivityState=>({completed:0,collectibles:[],shops:{},npcMood:{}})
function read():ActivityState{try{return {...base(),...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{return base()}}
function save(s:ActivityState){localStorage.setItem(KEY,JSON.stringify(s));window.dispatchEvent(new CustomEvent('tryamm:streetverse-activity-state',{detail:s}));return s}
function emit(name:string,detail:any){window.dispatchEvent(new CustomEvent(name,{detail}))}
function on(name:string,fn:(d:any)=>void){window.addEventListener(name,(e:Event)=>fn((e as CustomEvent<any>).detail||{}))}
function startActivity(d:any){const s=read();s.active=String(d.type||'delivery');save(s);emit('tryamm:streetverse-activity-active',{type:s.active,objective:d.objective||'Complete the activity',checkpoint:d.checkpoint||0});emit('tryamm:construct:targets',{targets:[{id:`activity-${s.active}`,kind:'mission',title:String(d.label||s.active),x:Number(d.x||0),z:Number(d.z||0)}]})}
function completeActivity(d:any){const s=read();const type=s.active||String(d.type||'activity');s.active=undefined;s.completed++;save(s);emit('tryamm:streetverse-xp-gain',{amount:Number(d.xp||75),reason:type});emit('tryamm:streetverse-activity-complete',{type,total:s.completed,reward:'XP/cosmetics',cashReward:false})}
function interact(d:any){const s=read();const kind=String(d.kind||'city-object');s.lastInteraction=kind;if(kind==='atm')emit('tryamm:streetverse-atm-open',{mode:'wallet-handoff',cashGameplay:false});else if(kind==='payphone')emit('tryamm:streetverse-job-start',{job:'payphone-side-job',objective:'Follow the caller objective.'});else if(kind==='shop'){const id=String(d.id||'shop');s.shops[id]=(s.shops[id]||0)+1;emit('tryamm:streetverse-shop-open',{id,visits:s.shops[id],inventory:d.inventory||['food','cosmetics','vehicle-care']})}else if(kind==='graffiti')emit('tryamm:streetverse-creator-tag',{surfaceId:d.id||'wall',creatorSafe:true});else if(kind==='hydrant')emit('tryamm:streetverse-world-prop',{kind:'hydrant',effect:'water-spray'});save(s)}
function collect(d:any){const s=read();const id=String(d.id||'collectible');if(!s.collectibles.includes(id)){s.collectibles.push(id);save(s);emit('tryamm:streetverse-xp-gain',{amount:Number(d.xp||20),reason:'collectible'});emit('tryamm:streetverse-collectible',{id,total:s.collectibles.length,label:d.label||id})}}
function npcReact(d:any){const s=read();const id=String(d.id||'resident');const mood=String(d.mood||'curious');s.npcMood[id]=mood;save(s);emit('tryamm:streetverse-npc-reaction',{id,mood,line:d.line||'',action:d.action||'observe'});emit('tryamm:streetverse-npc-memory',{district:d.district||'central',delta:Number(d.repDelta||0),memory:`${id}:${mood}`})}
function race(d:any){startActivity({type:d.mode||'street-race',label:d.label||'Street Race',x:d.x,z:d.z,objective:d.objective||'Reach every checkpoint and finish.'});emit('tryamm:streetverse-race-state',{mode:d.mode||'street-race',laps:Number(d.laps||1),checkpoints:Number(d.checkpoints||6),driftBonus:true,vehicleClasses:['car','motorcycle','boat']})}
function rescue(d:any){startActivity({type:'rescue',label:d.label||'Rescue Mission',x:d.x,z:d.z,objective:d.objective||'Reach the resident and bring them to safety.'});emit('tryamm:streetverse-rescue-state',{status:'dispatched',target:d.target||'resident',timer:Number(d.timer||180)})}
function taxi(d:any){startActivity({type:'taxi',label:'Taxi Shift',x:d.x,z:d.z,objective:'Pick up the rider and deliver them to the destination.'});emit('tryamm:streetverse-taxi-state',{fare:'non-cash-demo',passenger:d.passenger||'resident',destination:d.destination||'Downtown'})}
function delivery(d:any){startActivity({type:'delivery',label:'Delivery Run',x:d.x,z:d.z,objective:'Collect the package and reach the drop-off.'});emit('tryamm:streetverse-delivery-state',{package:d.package||'marketplace-order',destination:d.destination||'Business District'})}
export function installStreetVerseActivityRuntime(){if(installed||typeof window==='undefined')return;installed=true;save(read());on('tryamm:streetverse-activity-start',startActivity);on('tryamm:streetverse-activity-complete',completeActivity);on('tryamm:streetverse-city-interact',interact);on('tryamm:streetverse-collect',collect);on('tryamm:streetverse-npc-react',npcReact);on('tryamm:streetverse-race-start',race);on('tryamm:streetverse-rescue-start',rescue);on('tryamm:streetverse-taxi-start',taxi);on('tryamm:streetverse-delivery-start',delivery);emit('tryamm:streetverse-activity-ready',{shops:true,atms:true,payphones:true,graffiti:true,hydrants:true,collectibles:true,npcReactions:true,races:true,rescue:true,taxi:true,delivery:true,cashGameplay:false})}