import {
  BUILDING_RECONSTRUCTION_STAGES,
  validateBuildingPassport,
  type BuildingPassport,
  type BuildingSource,
} from '../game/runtime/holographicBuildingReconstruction'
import {createAssetFactoryJob,type AssetFactoryJob,type AssetKind} from '../data/TryammAssetForge'
import {nearestChicagoGridZone,gameGridCell} from '../data/StreetVerseChicagoBuildGrid'

export type WorldForgeKind='building'|'character'|'vehicle'|'prop'|'environment'
export type WorldForgeTarget='mobile'|'web'|'cinematic'
export type WorldForgeStatus='draft'|'ready-for-assets'|'needs-reference'|'needs-review'|'certified'

export interface WorldForgeReference{
  id:string
  kind:'photo-front'|'photo-back'|'photo-left'|'photo-right'|'photo-top'|'floor-plan'|'blueprint'|'scan'|'measurement'|'concept'
  uri:string
  authorized:boolean
  notes?:string
}

export interface WorldForgeBuildingProgram{
  footprintM:{width:number;depth:number}
  floors:number
  floorHeightM:number
  basement?:boolean
  roof:'flat'|'pitched'|'mixed'
  stairs:'none'|'single'|'multiple'
  elevator:'none'|'passenger'|'freight'|'both'
  plumbing:boolean
  electrical:boolean
  hvac:boolean
  sprinklers:boolean
  rooms?:Array<{id:string;label:string;floor:number;kind:string;accessible?:boolean}>
}

export interface WorldForgeRequest{
  id:string
  name:string
  kind:WorldForgeKind
  target:WorldForgeTarget
  city?:string
  neighborhood?:string
  x?:number
  z?:number
  stylePrompt:string
  references:WorldForgeReference[]
  building?:WorldForgeBuildingProgram
  rigProfile?:'humanoid'|'quadruped'|'vehicle'|'none'
  textureStyle?:string
  collision?:boolean
  navmesh?:boolean
  photorealWrap?:boolean
  rightsConfirmed:boolean
}

export interface CadLevelPlan{
  id:string
  floor:number
  elevationM:number
  heightM:number
  rooms:Array<{id:string;label:string;kind:string;accessible:boolean}>
}

export interface CadUtilityGraph{
  stairs:string[]
  elevators:string[]
  plumbing:string[]
  electrical:string[]
  hvac:string[]
  fireSafety:string[]
}

export interface CadBuildingPlan{
  schema:'tryamm.cad-building.v1'
  footprintM:{width:number;depth:number}
  levels:CadLevelPlan[]
  utilities:CadUtilityGraph
  facade:{
    photorealWrap:boolean
    textureStyle:string
    requiredViews:string[]
    suppliedViews:string[]
  }
  geometry:{
    shell:true
    floors:true
    walls:true
    doors:true
    windows:true
    stairs:boolean
    elevators:boolean
    collision:boolean
    navmesh:boolean
  }
}

export interface WorldForgePlan{
  schema:'tryamm.world-forger.v1'
  id:string
  name:string
  kind:WorldForgeKind
  status:WorldForgeStatus
  target:WorldForgeTarget
  placement?:{
    city:string
    neighborhood?:string
    x:number
    z:number
    gridCell:string
    nearestZone?:string
  }
  cad?:CadBuildingPlan
  buildingPassport?:BuildingPassport
  assetJob:AssetFactoryJob
  pipeline:string[]
  missing:string[]
  warnings:string[]
  authority:{
    autoGenerateDrafts:true
    autoPublish:false
    requiresFounderPreview:true
    requiresRightsEvidence:true
  }
  createdAt:string
}

const PHOTO_VIEW_BY_KIND:Partial<Record<WorldForgeReference['kind'],string>>={
  'photo-front':'front',
  'photo-back':'back',
  'photo-left':'left',
  'photo-right':'right',
  'photo-top':'top',
}

const toBuildingSource=(ref:WorldForgeReference):BuildingSource=>({
  id:ref.id,
  kind:
    ref.kind==='photo-front'?'front-photo':
    ref.kind==='photo-back'?'rear-photo':
    ref.kind==='photo-left'?'left-photo':
    ref.kind==='photo-right'?'right-photo':
    ref.kind==='photo-top'?'aerial-reference':
    ref.kind==='floor-plan'?'floor-plan':
    ref.kind==='blueprint'?'blueprint':
    ref.kind==='scan'?'scan':'measurement',
  uri:ref.uri,
  authorized:ref.authorized,
  notes:ref.notes,
})

function assetKind(kind:WorldForgeKind):AssetKind{
  return kind
}

function buildCad(request:WorldForgeRequest):CadBuildingPlan|undefined{
  if(request.kind!=='building'||!request.building)return undefined
  const b=request.building
  const levels:CadLevelPlan[]=Array.from({length:Math.max(1,b.floors)},(_,index)=>{
    const floor=index+1
    const rooms=(b.rooms||[])
      .filter(room=>room.floor===floor)
      .map(room=>({id:room.id,label:room.label,kind:room.kind,accessible:room.accessible!==false}))
    return{id:`level-${floor}`,floor,elevationM:index*b.floorHeightM,heightM:b.floorHeightM,rooms}
  })
  const suppliedViews=request.references.map(ref=>PHOTO_VIEW_BY_KIND[ref.kind]).filter(Boolean) as string[]
  return{
    schema:'tryamm.cad-building.v1',
    footprintM:{width:b.footprintM.width,depth:b.footprintM.depth},
    levels,
    utilities:{
      stairs:b.stairs==='none'?[]:[b.stairs==='multiple'?'stairs-a':'stairs-main',...(b.stairs==='multiple'?['stairs-b']:[])],
      elevators:b.elevator==='none'?[]:[b.elevator==='both'?'passenger-elevator':'main-elevator',...(b.elevator==='both'?['freight-elevator']:[])],
      plumbing:b.plumbing?['cold-water','hot-water','sanitary-drain','vent-stack']:[],
      electrical:b.electrical?['main-service','lighting','receptacles','life-safety-power']:[],
      hvac:b.hvac?['supply','return','exhaust','controls']:[],
      fireSafety:b.sprinklers?['sprinklers','alarm','egress-lighting']:['alarm','egress-lighting'],
    },
    facade:{
      photorealWrap:Boolean(request.photorealWrap),
      textureStyle:request.textureStyle||'PBR-photoreal',
      requiredViews:['front','back','left','right','top'],
      suppliedViews,
    },
    geometry:{
      shell:true,floors:true,walls:true,doors:true,windows:true,
      stairs:b.stairs!=='none',elevators:b.elevator!=='none',
      collision:request.collision!==false,navmesh:request.navmesh!==false,
    },
  }
}

function makePassport(request:WorldForgeRequest,cad:CadBuildingPlan):BuildingPassport{
  const sources=request.references.map(toBuildingSource)
  return{
    id:request.id,
    name:request.name,
    city:request.city||'Chicago',
    communityArea:request.neighborhood,
    sourceProvenance:sources,
    levels:cad.levels.map(level=>({
      id:level.id,label:`Floor ${level.floor}`,elevationM:level.elevationM,heightM:level.heightM,
      roomIds:level.rooms.map(room=>room.id),
    })),
    behaviors:[
      ...cad.utilities.stairs.map((id,index)=>({id,kind:'stairs' as const,levelId:`level-${Math.min(index+1,cad.levels.length)}`,interactive:true,accessibility:{oneHandOperable:true,visualCueRequired:true}})),
      ...cad.utilities.elevators.map(id=>({id,kind:'elevator' as const,interactive:true,accessibility:{wheelchairReachable:true,oneHandOperable:true,visualCueRequired:true}})),
      ...cad.utilities.plumbing.filter(id=>id==='cold-water'||id==='hot-water').map((id,index)=>({id:`sink-${index+1}`,kind:'sink' as const,interactive:true,accessibility:{wheelchairReachable:true,oneHandOperable:true}})),
      ...cad.levels.flatMap(level=>level.rooms.map(room=>({id:`room-${room.id}`,kind:'mission' as const,roomId:room.id,levelId:level.id,interactive:true,accessibility:{wheelchairReachable:room.accessible,oneHandOperable:true,visualCueRequired:true}}))),
    ],
    behaviorEdges:[],
    reconstruction:{
      geometryConfidence:request.references.some(ref=>ref.kind==='measurement'||ref.kind==='scan')?.86:.62,
      facadeConfidence:cad.facade.suppliedViews.length>=4?.9:cad.facade.suppliedViews.length>=2?.72:.45,
      interiorConfidence:request.references.some(ref=>ref.kind==='floor-plan'||ref.kind==='blueprint')?.88:.5,
      uncertainRegions:[],
    },
    optimization:{
      mobileTriangleBudget:120000,
      desktopTriangleBudget:450000,
      textureBudgetMb:96,
      lodLevels:4,
      streamingCell:request.x!==undefined&&request.z!==undefined?gameGridCell(request.x,request.z):undefined,
    },
    safety:{
      emergencyExitNodeIds:cad.utilities.stairs.length?cad.utilities.stairs:['main-egress'],
      accessibleRouteNodeIds:cad.utilities.elevators.length?cad.utilities.elevators:['accessible-ground-route'],
      adultPrivateZonesRequireVerifiedAdultConsent:true,
    },
  }
}

function pipelineFor(request:WorldForgeRequest){
  if(request.kind==='building')return[
    'INGEST_AUTHORIZED_REFERENCES',
    'CAD_FOOTPRINT_AND_LEVELS',
    'CAD_STRUCTURE_STAIRS_ELEVATORS',
    'CAD_PLUMBING_ELECTRICAL_HVAC_FIRE',
    'GENERATE_ROOMS_DOORS_WINDOWS',
    'PHOTOREAL_FACADE_WRAP',
    'PBR_MATERIALS_AND_UV',
    'MESH_REPAIR_AND_RETROPOLOGY',
    'COLLISION_NAVMESH_ACCESSIBILITY',
    'LOD_COMPRESSION_STREAMING',
    'PLACE_IN_WORLD_GRID',
    'LIVING_WORLD_SEMANTICS',
    'GUARDIAN_QA',
    'FOUNDER_PREVIEW',
  ]
  return[
    'INGEST_AUTHORIZED_REFERENCES',
    'PROMPT_AND_REFERENCE_SPEC',
    'GENERATE_MESH',
    'MESH_REPAIR_AND_RETOPOLOGY',
    'UV_PBR_TEXTURE',
    ...(request.kind==='character'?['RIG_HUMANOID','FACIAL_RIG','RETARGET_ANIMATION']:[]),
    ...(request.kind==='vehicle'?['VEHICLE_RIG','DOORS_WHEELS_LIGHTS','PHYSICS_COLLISION']:[]),
    'LOD_COMPRESSION',
    'RIGHTS_PROVENANCE',
    'PLACE_IN_WORLD',
    'GUARDIAN_QA',
    'FOUNDER_PREVIEW',
  ]
}

export function createWorldForgePlan(request:WorldForgeRequest):WorldForgePlan{
  const missing:string[]=[]
  const warnings:string[]=[]
  if(!request.name.trim())missing.push('name')
  if(!request.stylePrompt.trim())missing.push('stylePrompt')
  if(!request.rightsConfirmed)missing.push('rightsConfirmation')
  if(!request.references.some(ref=>ref.authorized))missing.push('authorizedReference')
  if(request.kind==='building'&&!request.building)missing.push('buildingProgram')

  const cad=buildCad(request)
  let passport:BuildingPassport|undefined
  if(cad){
    passport=makePassport(request,cad)
    missing.push(...validateBuildingPassport(passport).map(error=>`passport:${error}`))
    if(request.photorealWrap){
      const missingViews=cad.facade.requiredViews.filter(view=>!cad.facade.suppliedViews.includes(view))
      if(missingViews.length)warnings.push(`Photoreal wrap missing views: ${missingViews.join(', ')}`)
    }
  }

  const x=Number.isFinite(request.x)?Number(request.x):0
  const z=Number.isFinite(request.z)?Number(request.z):54
  const nearest=request.city?.toLowerCase()==='chicago'||!request.city?nearestChicagoGridZone(x,z):undefined
  const placement=request.city?{
    city:request.city,neighborhood:request.neighborhood,x,z,gridCell:gameGridCell(x,z),nearestZone:nearest?.label,
  }:undefined

  const target=request.target==='cinematic'?'cinematic':request.target==='web'?'web':'mobile'
  const assetJob=createAssetFactoryJob(request.id,assetKind(request.kind),target)
  const status:WorldForgeStatus=missing.length?'needs-reference':'ready-for-assets'

  return{
    schema:'tryamm.world-forger.v1',
    id:request.id,name:request.name,kind:request.kind,status,target:request.target,
    placement,cad,buildingPassport:passport,assetJob,
    pipeline:pipelineFor(request),missing,warnings,
    authority:{autoGenerateDrafts:true,autoPublish:false,requiresFounderPreview:true,requiresRightsEvidence:true},
    createdAt:new Date().toISOString(),
  }
}

export function canStartWorldForge(plan:WorldForgePlan){
  return plan.missing.length===0&&plan.status==='ready-for-assets'
}

export function worldForgeSummary(plan:WorldForgePlan){
  return{
    id:plan.id,name:plan.name,kind:plan.kind,status:plan.status,
    placement:plan.placement,
    stages:plan.pipeline.length,
    missing:plan.missing,
    warnings:plan.warnings,
    cadLevels:plan.cad?.levels.length||0,
    assetStages:plan.assetJob.stages.length,
    autoPublish:false,
  }
}

export const TRYAMM_WORLD_FORGER={
  name:'TRYAMM World Forger',
  purpose:'One orchestration layer connecting authorized references, internal CAD-style planning, holographic reconstruction, Asset Forge, Meshy/native providers, rigging, textures, collision, navigation, LODs and world placement.',
  buildingStages:BUILDING_RECONSTRUCTION_STAGES,
  supportedKinds:['building','character','vehicle','prop','environment'] as const,
  cadMeaning:'Structured game-world CAD/BIM-style scene planning. It does not claim licensed AutoCAD/Revit functionality.',
  cursorRole:'Cursor/Benny/AI may inspect context and propose source/code/build plans; production mutation and publish remain separately gated.',
  photorealRule:'Photo-reference wrapping requires authorized source images and must preserve provenance.',
  physicalConstruction:false,
  autoPublish:false,
} as const
