export type DemandKind='food'|'retail'|'beauty'|'health'|'legal'|'housing'|'transport'|'media'|'technology'|'safety'|'education'|'construction';
export type WorldDemand={id:string;city:string;kind:DemandKind;severity:1|2|3|4|5;source:string;title:string;createdAt:string;expiresAt?:string};
const KEY='tryamm_world_economy_v1';let installed=false;
function load():WorldDemand[]{try{return JSON.parse(localStorage.getItem(KEY)||'[]')}catch{return[]}}
function save(xs:WorldDemand[]){try{localStorage.setItem(KEY,JSON.stringify(xs))}catch{};window.dispatchEvent(new CustomEvent('tryamm:world-economy-state',{detail:{schema:'tryamm.world.economy.v1',demands:xs,loop:'WORLD EVENT → DEMAND → JOBS + SUPPLY + BUSINESS + CREATOR + MISSIONS → VERIFIED COMPLETION → CITY STATE CHANGES'}}))}
function fanout(d:WorldDemand){
 window.dispatchEvent(new CustomEvent('tryamm:ai-cafe-task',{detail:{workstream:'business',title:`Respond to ${d.city} demand: ${d.title}`,priority:d.severity>=4?'critical':'high'}}));
 window.dispatchEvent(new CustomEvent('tryamm:business-post-job',{detail:{businessId:`world-${d.kind}`,title:`${d.city} ${d.kind} response shift`,skills:[d.kind,'customer-service','operations'],minLevel:Math.max(1,d.severity-1),languages:['any'],city:d.city,remote:['technology','media','legal','health'].includes(d.kind),training:[`${d.kind}-operations`]}}));
 window.dispatchEvent(new CustomEvent('tryamm:streetverse-business-mission-pack',{detail:{verticalId:d.kind,city:d.city,missions:[`Stabilize ${d.title}`,`Support ${d.city} customers`, `Verify ${d.kind} response outcome`]}}));
 window.dispatchEvent(new CustomEvent('tryamm:regional-opportunities-request',{detail:{city:d.city,kind:d.kind,demand:d}}));
 if(['food','retail','beauty','construction'].includes(d.kind))window.dispatchEvent(new CustomEvent('tryamm:quantum-sourcing-request',{detail:{business:`${d.city} ${d.kind} response`,industry:d.kind,city:d.city}}));
 if(['food','retail','beauty'].includes(d.kind))window.dispatchEvent(new CustomEvent('tryamm:virtual-warehouse-demand',{detail:d}));
 if(d.kind==='food')window.dispatchEvent(new CustomEvent('tryamm:holo-fridge-community-demand',{detail:d}));
 if(['media','retail','beauty','food','education'].includes(d.kind))window.dispatchEvent(new CustomEvent('tryamm:creator-commerce-launch',{detail:{business:`${d.city} ${d.kind} response`,campaign:d.title,city:d.city}}));
 window.dispatchEvent(new CustomEvent('tryamm:omni-bi-demand-signal',{detail:d}));
}
function create(detail:any):WorldDemand{const severity=Math.max(1,Math.min(5,Number(detail.severity||2))) as 1|2|3|4|5;return{id:String(detail.id||`demand-${Date.now()}-${Math.random().toString(36).slice(2,7)}`),city:String(detail.city||'Chicago'),kind:(detail.kind||'retail') as DemandKind,severity,source:String(detail.source||'living-world'),title:String(detail.title||'Local demand spike'),createdAt:new Date().toISOString(),expiresAt:detail.expiresAt}}
export function installWorldEconomyOrchestratorRuntime(){if(installed||typeof window==='undefined')return;installed=true;let demands=load();queueMicrotask(()=>save(demands));window.addEventListener('tryamm:world-economy-demand',(e:Event)=>{const d=create((e as CustomEvent<any>).detail||{});demands=[d,...demands].slice(0,200);save(demands);fanout(d)});window.addEventListener('tryamm:world-event',(e:Event)=>{const x=(e as CustomEvent<any>).detail||{};const map:Record<string,DemandKind>={festival:'media',storm:'food',blackout:'technology',shortage:'retail',housing:'housing',health:'health',safety:'safety',construction:'construction'};const kind=map[String(x.type||'')]||'retail';window.dispatchEvent(new CustomEvent('tryamm:world-economy-demand',{detail:{city:x.city||'Chicago',kind,severity:x.severity||2,source:'world-event',title:x.title||`${kind} demand from world event`}}))});window.addEventListener('tryamm:world-economy-resolve',(e:Event)=>{const id=(e as CustomEvent<any>).detail?.id;const d=demands.find(x=>x.id===id);if(!d)return;demands=demands.filter(x=>x.id!==id);save(demands);window.dispatchEvent(new CustomEvent('tryamm:streetverse-reward',{detail:{xp:100*d.severity,reputation:5*d.severity}}));window.dispatchEvent(new CustomEvent('tryamm:creator-highlight-marker',{detail:{kind:'economy-resolution',city:d.city,title:d.title,severity:d.severity}}))})}
