export type StreetVersePathId='STREET_LIFE'|'SPY_OPS'|'GLOBAL_SERVICE'|'PARANORMAL_OPS'|'MUSIC'|'BUSINESS'|'INVESTIGATION'|'RACING'|'DELIVERY'|'RESCUE'|'SPORTS'|'SECURITY'|'HOLO'|'AFTER_DARK'
export interface StreetVersePath {id:StreetVersePathId;name:string;lane:'GENERAL'|'ADULT_18_PLUS';summary:string;missionTypes:string[];loadoutTags:string[]}
export const STREETVERSE_PATHS:StreetVersePath[]=[
{id:'STREET_LIFE',name:'Chicago StreetVerse',lane:'GENERAL',summary:'Open-world neighborhood life, relationships, property and connected missions.',missionTypes:['community','story','property','business'],loadoutTags:['streetwear','phone','vehicle','mission-items']},
{id:'SPY_OPS',name:'Spy Ops',lane:'GENERAL',summary:'Original espionage-inspired stealth, disguise, intelligence and extraction missions.',missionTypes:['infiltration','stealth','intel','extraction'],loadoutTags:['fictional-gadgets','disguise','mission-items']},
{id:'GLOBAL_SERVICE',name:'Global Service Missions',lane:'GENERAL',summary:'Fictionalized police, sheriff, federal-investigation, intelligence, maritime-rescue and defense-service mission families localized across seven continents.',missionTypes:['investigation','community-safety','rescue','disaster-response','training','cyber-defense'],loadoutTags:['safety-gear','investigation-kit','rescue-gear','fictional-game-equipment']},
{id:'PARANORMAL_OPS',name:'Black Sky Division',lane:'GENERAL',summary:'Original science-fiction special-agent missions involving anomalies, alien contact, paranormal cases, hidden portals and memory effects.',missionTypes:['anomaly','paranormal-investigation','alien-contact-fiction','portal','extraction'],loadoutTags:['fictional-scanner','holo-visor','portal-beacon','memory-shield','disguise']},
{id:'MUSIC',name:'Music & Entertainment',lane:'GENERAL',summary:'Create, perform, promote and build a creator career.',missionTypes:['studio','performance','promotion','tour'],loadoutTags:['creator-gear','fashion','music-items']},
{id:'BUSINESS',name:'Business',lane:'GENERAL',summary:'Start, operate and grow StreetVerse businesses.',missionTypes:['startup','sales','delivery','expansion'],loadoutTags:['business-goods','vehicle','electronics']},
{id:'INVESTIGATION',name:'Investigation',lane:'GENERAL',summary:'Fictional clue, mystery and case-solving gameplay.',missionTypes:['clues','interview','case-board','resolution'],loadoutTags:['investigation-kit','camera','mission-items']},
{id:'RACING',name:'Racing & Mobility',lane:'GENERAL',summary:'Driving, racing, drifting and mobility progression.',missionTypes:['race','delivery','time-trial','vehicle-career'],loadoutTags:['vehicle','vehicle-parts']},
{id:'DELIVERY',name:'Delivery & Rides',lane:'GENERAL',summary:'Move people and goods through the living city.',missionTypes:['delivery','rides','route','business-service'],loadoutTags:['vehicle','phone','business-goods']},
{id:'RESCUE',name:'Rescue & Community',lane:'GENERAL',summary:'Fictionalized community response, assistance and de-escalation missions.',missionTypes:['assist','rescue-simulation','community'],loadoutTags:['safety-gear','accessibility','mission-items']},
{id:'SPORTS',name:'Sports',lane:'GENERAL',summary:'Athletic careers, tournaments and neighborhood competition.',missionTypes:['training','match','tournament'],loadoutTags:['sports-gear','fashion']},
{id:'SECURITY',name:'Security',lane:'GENERAL',summary:'Fictional protective-service, observation and de-escalation gameplay.',missionTypes:['protect','observe','escort','de-escalate'],loadoutTags:['safety-gear','fictional-game-equipment']},
{id:'HOLO',name:'HoloVerse',lane:'GENERAL',summary:'Spatial missions, Holo Clip experiences and cross-world encounters.',missionTypes:['holo','portal','creator','pk'],loadoutTags:['holo-gear','creator-gear']},
{id:'AFTER_DARK',name:'Omniverse After Dark',lane:'ADULT_18_PLUS',summary:'Age-gated nightlife, music, fashion, social, VIP, mystery and business missions.',missionTypes:['nightlife','concert','fashion','vip','mystery','business'],loadoutTags:['fashion','creator-gear','vehicle']},
]
export const STREETVERSE_PATH_POLICY=Object.freeze({afterDarkMinimumAge:18,ageGateRequired:true,teenLaneSeparated:true,consentControlsRequired:true,privacyControlsRequired:true,adultSexualContentRequired:false,realWorldWeaponCommerceAllowed:false,fictionalGameEquipmentOnly:true,missionConsequencesPersist:true,reputationPersists:true,pathSwitchingAllowed:true,realAgencyAffiliationClaimed:false,realAgencyCredentialsAllowed:false,operationalTacticsAllowed:false})
