export type ServiceMissionFamily='LOCAL_LAW_ENFORCEMENT'|'FEDERAL_INVESTIGATION'|'INTELLIGENCE'|'MARITIME_RESCUE'|'DEFENSE_SERVICE'|'PARANORMAL_SPECIAL_OPS'
export type Continent='AFRICA'|'ANTARCTICA'|'ASIA'|'EUROPE'|'NORTH_AMERICA'|'SOUTH_AMERICA'|'OCEANIA'
export interface ServiceMissionLane {id:string;region:string;continent:Continent;family:ServiceMissionFamily;inspirations:string[];missionTypes:string[];fictionalized:true}
export const STREETVERSE_GLOBAL_SERVICE_LANES:ServiceMissionLane[]=[
{id:'north-america-us',region:'United States',continent:'NORTH_AMERICA',family:'FEDERAL_INVESTIGATION',inspirations:['federal investigators','intelligence analysts','sheriff services','municipal police','maritime rescue','army','navy','air force'],missionTypes:['investigation','missing-person-simulation','cyber-defense','rescue','disaster-response','training'],fictionalized:true},
{id:'north-america-mexico',region:'Mexico',continent:'NORTH_AMERICA',family:'LOCAL_LAW_ENFORCEMENT',inspirations:['Mexican public-safety services','federal investigators','maritime rescue'],missionTypes:['community-safety','investigation','rescue','disaster-response'],fictionalized:true},
{id:'europe-britain',region:'Britain',continent:'EUROPE',family:'INTELLIGENCE',inspirations:['British intelligence-style service','police services'],missionTypes:['espionage-fiction','counterintelligence-fiction','investigation','protective-service'],fictionalized:true},
{id:'africa-network',region:'Africa',continent:'AFRICA',family:'FEDERAL_INVESTIGATION',inspirations:['country-specific police services','special-investigation services','maritime and rescue services'],missionTypes:['investigation','community-safety','rescue','anti-fraud-simulation'],fictionalized:true},
{id:'asia-network',region:'Asia',continent:'ASIA',family:'FEDERAL_INVESTIGATION',inspirations:['country-specific police services','investigative services','maritime rescue'],missionTypes:['investigation','rescue','disaster-response','cyber-defense'],fictionalized:true},
{id:'south-america-network',region:'South America',continent:'SOUTH_AMERICA',family:'FEDERAL_INVESTIGATION',inspirations:['country-specific police services','investigative services','maritime rescue'],missionTypes:['investigation','community-safety','rescue','environmental-protection-simulation'],fictionalized:true},
{id:'oceania-network',region:'Oceania',continent:'OCEANIA',family:'MARITIME_RESCUE',inspirations:['country-specific police services','investigative services','maritime rescue'],missionTypes:['rescue','investigation','disaster-response','maritime-safety'],fictionalized:true},
{id:'antarctica-network',region:'Antarctica',continent:'ANTARCTICA',family:'MARITIME_RESCUE',inspirations:['international research support','search and rescue','environmental response'],missionTypes:['research-rescue','survival-simulation','environmental-response'],fictionalized:true},
]
export const PARANORMAL_SPECIAL_OPS=Object.freeze({id:'PARANORMAL_SPECIAL_OPS',name:'Black Sky Division',description:'Original Men-in-Black-style science-fiction mission lane with secret agents, aliens, paranormal investigations, hidden portals, memory-anomaly effects and futuristic fictional gadgets.',missionTypes:['anomaly-detection','alien-contact-fiction','paranormal-investigation','portal-containment','memory-anomaly','extraction'],loadoutTags:['fictional-scanner','holo-visor','portal-beacon','memory-shield','disguise'],fictionalized:true,notAffiliatedWithRealAgency:true})
export const GLOBAL_SERVICE_POLICY=Object.freeze({gameplayFictionalized:true,noClaimOfAgencyAffiliation:true,noRealAgencyCredentials:true,noImpersonationTools:true,noOperationalTactics:true,noSensitiveFacilityMaps:true,noRealSurveillanceAccess:true,noRealWeaponsCommerce:true,noPlayerDetentionAuthority:true,noPredictiveCrimeScoring:true,emergencyServicesRemainRealWorldEscalation:true,countryLocalizationRequired:true,localLawAndCulturalReviewRequired:true,sevenContinentCoverage:true})
