github.com:
    users:
        jgoldie1:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: jgoldie1
