import { getAuthenticatedUserId, getSupabaseClient } from './supabaseClient'

function sb(){const c=getSupabaseClient(); if(!c) throw new Error('Supabase not configured'); return c}
async function uid(){const id=await getAuthenticatedUserId(); if(!id) throw new Error('Authentication required'); return id}

export async function getIdentity(){const id=await uid();const q=await sb().from('holo_identity_profiles').select('*').eq('user_id',id).maybeSingle();if(q.error)throw q.error;if(q.data)return q.data;const {data,error}=await sb().from('holo_identity_profiles').insert({user_id:id,age_lane:'adult',accessibility:{},permissions:{},credentials:[]}).select('*').single();if(error)throw error;return data}
export async function updateIdentity(patch:Record<string,unknown>){const id=await uid();const allowed=['age_lane','accessibility','permissions','credentials'];const clean=Object.fromEntries(Object.entries(patch).filter(([k])=>allowed.includes(k)));const {data,error}=await sb().from('holo_identity_profiles').upsert({user_id:id,...clean,updated_at:new Date().toISOString()},{onConflict:'user_id'}).select('*').single();if(error)throw error;return data}

export async function getWorkProfile(){const id=await uid();const q=await sb().from('holo_work_profiles').select('*').eq('user_id',id).maybeSingle();if(q.error)throw q.error;if(q.data)return q.data;const {data,error}=await sb().from('holo_work_profiles').insert({user_id:id,skills:{},career_goals:[],availability:{}}).select('*').single();if(error)throw error;return data}
export async function listWorkTasks(){const id=await uid();const {data,error}=await sb().from('holo_work_tasks').select('*').eq('user_id',id).order('created_at',{ascending:false});if(error)throw error;return data??[]}
export async function createWorkTask(taskType:string,title:string,source='workforce',payload:Record<string,unknown>={}){const id=await uid();const {data,error}=await sb().from('holo_work_tasks').insert({user_id:id,task_type:taskType,title,source,payload}).select('*').single();if(error)throw error;return data}
export async function completeWorkTask(id:string,score?:number){const user=await uid();const {data,error}=await sb().from('holo_work_tasks').update({status:'completed',score:score??null,completed_at:new Date().toISOString()}).eq('id',id).eq('user_id',user).select('*').single();if(error)throw error;return data}

export async function getWellnessProfile(){const id=await uid();const q=await sb().from('holo_wellness_profiles').select('*').eq('user_id',id).maybeSingle();if(q.error)throw q.error;if(q.data)return q.data;const {data,error}=await sb().from('holo_wellness_profiles').insert({user_id:id,goals:[],preferences:{},disclaimer_acknowledged:false}).select('*').single();if(error)throw error;return data}
export async function logWellnessSession(activityType:string,durationMinutes:number,intensity='moderate',notes=''){const id=await uid();const wellnessScore=Math.max(0,Math.min(100,durationMinutes*2));const {data,error}=await sb().from('holo_wellness_sessions').insert({user_id:id,activity_type:activityType,duration_minutes:durationMinutes,intensity,notes,wellness_score:wellnessScore}).select('*').single();if(error)throw error;return data}

export async function listCourses(){const {data,error}=await sb().from('holo_courses').select('*').eq('status','published').order('title');if(error)throw error;return data??[]}
export async function listEnrollments(){const id=await uid();const {data,error}=await sb().from('holo_course_enrollments').select('*,holo_courses(*)').eq('user_id',id).order('updated_at',{ascending:false});if(error)throw error;return data??[]}
export async function enroll(courseId:string){const id=await uid();const {data,error}=await sb().from('holo_course_enrollments').upsert({user_id:id,course_id:courseId,status:'enrolled',progress:0,updated_at:new Date().toISOString()},{onConflict:'user_id,course_id'}).select('*').single();if(error)throw error;return data}
export async function updateLearning(courseId:string,progress:number){const id=await uid();const p=Math.max(0,Math.min(100,progress));const status=p>=100?'completed':'active';const credential=p>=100?{earned:true,completed_at:new Date().toISOString()}:{};const {data,error}=await sb().from('holo_course_enrollments').upsert({user_id:id,course_id:courseId,progress:p,status,credential,updated_at:new Date().toISOString()},{onConflict:'user_id,course_id'}).select('*').single();if(error)throw error;return data}

export async function listCreatorProjects(){const id=await uid();const {data,error}=await sb().from('holo_creator_projects').select('*').eq('owner_id',id).order('updated_at',{ascending:false});if(error)throw error;return data??[]}
export async function createCreatorProject(projectType:string,title:string){const id=await uid();const {data,error}=await sb().from('holo_creator_projects').insert({owner_id:id,project_type:projectType,title,status:'draft',data:{}}).select('*').single();if(error)throw error;return data}
export async function updateCreatorProject(id:string,patch:Record<string,unknown>){const owner=await uid();const allowed=['title','status','data'];const clean=Object.fromEntries(Object.entries(patch).filter(([k])=>allowed.includes(k)));const {data,error}=await sb().from('holo_creator_projects').update({...clean,updated_at:new Date().toISOString()}).eq('id',id).eq('owner_id',owner).select('*').single();if(error)throw error;return data}

export async function recordMetric(metricKey:string,value=1,scope='platform',dimensions:Record<string,unknown>={}){const id=await getAuthenticatedUserId();const {data,error}=await sb().from('holo_metric_events').insert({user_id:id,metric_key:metricKey,scope,value,dimensions}).select('*').single();if(error)throw error;return data}
export async function analyticsSummary(){const id=await uid();const {data,error}=await sb().from('holo_metric_events').select('metric_key,scope,value,created_at').eq('user_id',id).order('created_at',{ascending:false}).limit(500);if(error)throw error;const totals:Record<string,number>={};for(const row of data??[])totals[row.metric_key]=(totals[row.metric_key]??0)+Number(row.value??0);return {events:data??[],totals}}

export async function listPaymentIntents(){const id=await uid();const {data,error}=await sb().from('holo_payment_intents').select('*').eq('user_id',id).order('created_at',{ascending:false});if(error)throw error;return data??[]}

export const wellnessNotice='Holo Health/Fitness provides general wellness and fitness education only. It does not diagnose, treat, prescribe, or replace licensed medical care.'
