export type CareerLevel={id:string;name:string;modules:string[];simulation:string;portfolio:string[];credential:string}
export type CareerPathway={id:string;name:string;purpose:string;levels:CareerLevel[];opportunityTargets:string[];guardrails:string[]}

export const AAU_CAREER_SIMULATION_PATHWAYS:CareerPathway[]=[
 {id:'aviation-ops',name:'Aviation Operations Academy',purpose:'Prepare learners for aviation operations careers through simulation and career exploration without representing AAU simulation as FAA certification.',levels:[
  {id:'av-100',name:'Aviation Foundations',modules:['airport systems','weather','communications','human factors'],simulation:'airport operations orientation',portfolio:['safety brief','airport systems map'],credential:'AAU Aviation Foundations badge'},
  {id:'av-200',name:'Dispatch & Ramp Operations',modules:['dispatch planning','NOTAM/weather reading','ramp safety','irregular operations'],simulation:'weather-diversion and ramp-turn scenario',portfolio:['dispatch plan','incident debrief'],credential:'AAU Aviation Operations badge'},
  {id:'av-300',name:'UAS & Remote Operations',modules:['mission planning','airspace awareness','inspection workflow','crew coordination'],simulation:'supervised drone mission planner',portfolio:['mission risk assessment','flight-operation plan'],credential:'AAU UAS Career Prep badge'},
  {id:'av-400',name:'Integrated Airport Lab',modules:['ATC coordination concepts','airport ops','dispatch','emergency response'],simulation:'multi-role airport disruption lab',portfolio:['team performance record','career-readiness capstone'],credential:'AAU Aviation Capstone'},
 ],opportunityTargets:['airport operations trainee','airline operations support','dispatch assistant','UAS operations pathway'],guardrails:['simulation only','no real ATC clearance','current official certification requirements must be verified externally']},
 {id:'logistics-dispatch',name:'Logistics, Freight & Dispatch Academy',purpose:'Train routing, fleet, load, warehouse and exception-management skills using the TRYAMM logistics economy.',levels:[
  {id:'lg-100',name:'Supply Chain Foundations',modules:['orders','inventory','routes','modes','customer service'],simulation:'regional delivery planner',portfolio:['route plan','service KPI review'],credential:'AAU Logistics Foundations badge'},
  {id:'lg-200',name:'Dispatch Operations',modules:['load matching','driver communication','ETA management','hours/risk awareness'],simulation:'multi-load dispatch shift',portfolio:['dispatch board','exception log'],credential:'AAU Dispatch Operations badge'},
  {id:'lg-300',name:'Freight & Intermodal',modules:['truck','rail','air','port','last mile'],simulation:'interstate disruption recovery',portfolio:['intermodal plan','cost/service comparison'],credential:'AAU Freight Operations badge'},
  {id:'lg-400',name:'Logistics Business Lab',modules:['pricing','customer acquisition','unit economics','compliance awareness'],simulation:'operate a virtual dispatch/logistics company',portfolio:['business model','P&L simulation'],credential:'AAU Logistics Capstone'},
 ],opportunityTargets:['dispatcher','logistics coordinator','fleet operations','warehouse/fulfillment','entrepreneurship'],guardrails:['no representation of licensure','safety/compliance rules override game scoring']},
 {id:'emergency-comms',name:'Emergency Communications & Response Academy',purpose:'Build calm communication, triage concepts and multi-agency coordination through non-operational simulation.',levels:[
  {id:'er-100',name:'Call Intake Foundations',modules:['active listening','location confirmation','priority concepts','accessibility communication'],simulation:'simulated non-live intake desk',portfolio:['call-quality reflection'],credential:'AAU Emergency Communications Foundations'},
  {id:'er-200',name:'Dispatch Coordination',modules:['resource selection concepts','radio discipline','status tracking','escalation'],simulation:'multi-unit simulated dispatch',portfolio:['dispatch timeline','after-action review'],credential:'AAU Dispatch Coordination badge'},
  {id:'er-300',name:'Complex Incident Lab',modules:['multi-agency coordination','weather/disaster','public information','stress management'],simulation:'city incident command simulation',portfolio:['incident board','team debrief'],credential:'AAU Emergency Operations badge'},
  {id:'er-400',name:'Resilience Capstone',modules:['continuity','accessibility','leadership','ethics'],simulation:'regional outage/disaster exercise',portfolio:['continuity plan'],credential:'AAU Emergency Communications Capstone'},
 ],opportunityTargets:['emergency communications trainee','public-safety support','operations center support'],guardrails:['never replace 911/emergency services','never issue operational emergency instructions as authority','training scenarios clearly labeled']},
 {id:'jacobie-cyber',name:'Jacobie Vision Cybersecurity Academy',purpose:'Create job-ready cybersecurity evidence using safe sandbox labs tied to TRYAMM identity, device and fraud systems.',levels:[
  {id:'cy-100',name:'Cyber Foundations',modules:['CIA triad','identity','device trust','phishing','network basics'],simulation:'safe SOC orientation',portfolio:['security checklist'],credential:'Jacobie Vision Foundations badge'},
  {id:'cy-200',name:'SOC Analyst Lab',modules:['alert triage','logs','ticketing','false positives','escalation'],simulation:'sandbox SOC queue',portfolio:['incident tickets','triage notes'],credential:'Jacobie Vision SOC badge'},
  {id:'cy-300',name:'Zero Trust & Mobile Security',modules:['passkeys/MFA','RBAC/RLS','SIM-swap risk','secrets','PQC migration concepts'],simulation:'secure a fictional TRYAMM tenant',portfolio:['zero-trust plan'],credential:'Jacobie Vision Zero Trust badge'},
  {id:'cy-400',name:'Incident Response Capstone',modules:['containment','evidence','recovery','postmortem','communications'],simulation:'controlled breach exercise',portfolio:['incident report','recovery plan'],credential:'Jacobie Vision Cyber Capstone'},
 ],opportunityTargets:['SOC analyst trainee','help desk/security','identity operations','security internship'],guardrails:['sandbox only','no credential theft','no malware deployment','defensive learning focus']},
 {id:'media-creator',name:'Music, Film, Broadcast & Creator Academy',purpose:'Turn TRYAMM creator tools into a portfolio-to-work pathway.',levels:[
  {id:'md-100',name:'Creator Foundations',modules:['story','camera','audio','editing','rights basics'],simulation:'produce a 30-second rights-safe reel',portfolio:['reel','credits sheet'],credential:'AAU Creator Foundations'},
  {id:'md-200',name:'Aniyah 64-Track Studio',modules:['recording','editing','mixing','session management','sample registry'],simulation:'produce an original song session',portfolio:['session file','rights/splits sheet'],credential:'AAU Studio Production badge'},
  {id:'md-300',name:'Movie Box & LIVE Production',modules:['storyboard','camera blocking','Lottie 2.0','LIVE direction','spatial audio'],simulation:'produce a multi-scene show/music video',portfolio:['movie/reel master','production log'],credential:'AAU Film/LIVE Production badge'},
  {id:'md-400',name:'All American Network Capstone',modules:['programming','distribution','audience','sponsorship','analytics'],simulation:'launch a rights-cleared channel/event package',portfolio:['show package','analytics review'],credential:'AAU Media Capstone'},
 ],opportunityTargets:['production assistant','audio assistant','editor','creator agency','broadcast/live production'],guardrails:['rights/provenance required','no uncleared sample/media release','paid promotion labeled']},
 {id:'trades-digital-twin',name:'Skilled Trades & Digital Twin Academy',purpose:'Use SpaceOS room scanning and digital twins for career exploration and pre-apprenticeship simulation.',levels:[
  {id:'tr-100',name:'Measurement & Site Safety',modules:['measurement','PPE concepts','hazard awareness','plans'],simulation:'room measurement lab',portfolio:['measurement sheet'],credential:'AAU Trades Foundations'},
  {id:'tr-200',name:'Digital Twin Build',modules:['3D room scan','doors/windows/no-go zones','materials','estimating'],simulation:'build a room digital twin',portfolio:['digital twin','estimate'],credential:'AAU Digital Twin badge'},
  {id:'tr-300',name:'CAD/Manufacturing Workflow',modules:['parametric design','STL/STEP','tolerance concepts','QA'],simulation:'produce a safe non-structural component design',portfolio:['CAD export','QA checklist'],credential:'AAU CAD Workflow badge'},
  {id:'tr-400',name:'Project Capstone',modules:['scope','schedule','procurement','customer communication'],simulation:'manage a virtual renovation project',portfolio:['project book'],credential:'AAU Trades Capstone'},
 ],opportunityTargets:['pre-apprenticeship','CAD assistant','estimating assistant','project coordinator'],guardrails:['no structural/safety certification claim','licensed trade work remains licensed trade work','manufacturing gated by safety review']},
 {id:'health-admin',name:'Healthcare Administration & Patient Access Academy',purpose:'Prepare learners for non-clinical healthcare administration, scheduling, navigation and call-center roles.',levels:[
  {id:'ha-100',name:'Patient Access Foundations',modules:['scheduling','customer service','privacy basics','accessibility'],simulation:'appointment navigation desk',portfolio:['service workflow'],credential:'AAU Patient Access Foundations'},
  {id:'ha-200',name:'Insurance & Revenue Cycle Concepts',modules:['eligibility concepts','authorizations','claims lifecycle','billing communication'],simulation:'non-clinical case-routing lab',portfolio:['workflow map'],credential:'AAU Healthcare Admin badge'},
  {id:'ha-300',name:'OmniCare Service Operations',modules:['call routing','case tracking','escalation','quality'],simulation:'AI-assisted service center with human handoff',portfolio:['quality scorecard'],credential:'AAU Service Operations badge'},
  {id:'ha-400',name:'Healthcare Operations Capstone',modules:['capacity','service recovery','analytics','privacy'],simulation:'clinic access improvement project',portfolio:['operations improvement plan'],credential:'AAU Healthcare Admin Capstone'},
 ],opportunityTargets:['patient access','scheduler','call center','revenue cycle support','healthcare operations'],guardrails:['non-clinical only','no diagnosis/treatment','privacy and human escalation required']},
 {id:'entrepreneurship',name:'Entrepreneurship, Marketplace & Franchise Academy',purpose:'Teach learners to create and operate small businesses using All American Marketplace and TRYAMM tools.',levels:[
  {id:'en-100',name:'Business Foundations',modules:['customer','offer','cost','price','basic bookkeeping'],simulation:'launch a virtual storefront',portfolio:['business one-pager'],credential:'AAU Entrepreneurship Foundations'},
  {id:'en-200',name:'Marketplace Operations',modules:['catalog','customer service','inventory','promotion','analytics'],simulation:'operate a Marketplace storefront',portfolio:['store metrics'],credential:'AAU Marketplace Operator badge'},
  {id:'en-300',name:'Agency & Franchise Operations',modules:['recruiting','training','territory','unit economics','compliance awareness'],simulation:'run a virtual agency/franchise location',portfolio:['operations manual draft'],credential:'AAU Agency/Franchise badge'},
  {id:'en-400',name:'Capital & Growth Capstone',modules:['cash flow','funding readiness','contracts','hiring','expansion'],simulation:'12-month business-growth scenario',portfolio:['growth plan','forecast'],credential:'AAU Entrepreneurship Capstone'},
 ],opportunityTargets:['self-employment','marketplace seller','agency operator','franchise/dealer pathway','business operations'],guardrails:['no guaranteed income','regulated businesses remain gated','financial projections labeled as simulations']},
]

export const AAU_CAREER_RUNTIME = {
 path:'DISCOVER → ENROLL → LEARNING PASSPORT → STUDENT JARVIS → LESSON → IMMERSIVE SIMULATION → ASSESSMENT → SAVE/REJOIN → PORTFOLIO EVIDENCE → AAU BADGE/CREDENTIAL → OPPORTUNITY MATCH → HUMAN ADVISOR/EMPLOYER/OFFICIAL CERTIFICATION PATH',
 integrations:['Learning Passport','Student Jarvis','Reality Lab','HoloArena','GameVerse','StreetVerse','Movie Box','Aniyah 64-Track','Jacobie Vision','SpaceOS','Marketplace','AI Call Center'],
 credentialTruth:'AAU badges document completed AAU learning evidence. They do not automatically equal government licensure, professional certification, college accreditation or employer acceptance unless separately approved.',
 accessibility:'Every pathway inherits the Accessibility Passport; simulations must offer supported alternatives such as seated mode, captions, voice controls, extended time and non-VR equivalents where practical.',
}
