const crypto=require('crypto');

const REGIONS={US:{locale:'en-US',currency:'USD',hreflang:'en-us'},NG:{locale:'en-NG',currency:'NGN',hreflang:'en-ng'},GH:{locale:'en-GH',currency:'GHS',hreflang:'en-gh'},KE:{locale:'en-KE',currency:'KES',hreflang:'en-ke'},ZA:{locale:'en-ZA',currency:'ZAR',hreflang:'en-za'},JP:{locale:'ja-JP',currency:'JPY',hreflang:'ja-jp'},KR:{locale:'ko-KR',currency:'KRW',hreflang:'ko-kr'},CN:{locale:'zh-CN',currency:'CNY',hreflang:'zh-cn'},IN:{locale:'en-IN',currency:'INR',hreflang:'en-in'},GB:{locale:'en-GB',currency:'GBP',hreflang:'en-gb'},AT:{locale:'de-AT',currency:'EUR',hreflang:'de-at'},JM:{locale:'en-JM',currency:'JMD',hreflang:'en-jm'}};
const PAGE_TYPES=['home','creator','music','video','drama','academy','marketplace','game','product','article','showcase','regional'];
function slug(value){return String(value||'').toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,80)||'page';}
function canonical(base,path){return `${String(base||'https://tryamm.online').replace(/\/$/,'')}/${String(path||'').replace(/^\//,'')}`;}
function pageMeta(input={}){const country=String(input.country||'US').toUpperCase();const region=REGIONS[country]||REGIONS.US;const title=String(input.title||'TryAMM — Create, Stream, Sell and Grow').slice(0,60);const description=String(input.description||'TryAMM is an all-in-one creator, streaming, marketplace, music, gaming and education platform.').slice(0,160);const path=input.path||`${slug(input.type||'page')}/${slug(input.title||'tryamm')}`;const url=canonical(input.baseUrl,path);return{title,description,url,canonical:url,locale:region.locale,hreflang:region.hreflang,country,robots:input.index===false?'noindex,nofollow':'index,follow,max-image-preview:large',openGraph:{type:input.ogType||'website',title,description,url,image:input.image||canonical(input.baseUrl,'images/og-default.png'),siteName:'TryAMM'},twitter:{card:'summary_large_image',title,description,image:input.image||canonical(input.baseUrl,'images/og-default.png')},jsonLd:structuredData({...input,title,description,url})};}
function structuredData(input={}){const type=String(input.type||'home');const common={'@context':'https://schema.org',name:input.title,url:input.url,description:input.description};if(type==='product')return{...common,'@type':'Product',image:input.image?[input.image]:undefined,offers:{'@type':'Offer',priceCurrency:input.currency||'USD',price:String(input.price||0),availability:input.inStock===false?'https://schema.org/OutOfStock':'https://schema.org/InStock',url:input.url}};if(type==='course'||type==='academy')return{...common,'@type':'Course',provider:{'@type':'Organization',name:'All American Marketplace Streaming Academy',sameAs:'https://tryamm.online'}};if(type==='music')return{...common,'@type':'MusicRecording',byArtist:{'@type':'MusicGroup',name:input.creator||'Independent Creator'}};if(type==='video'||type==='drama')return{...common,'@type':'VideoObject',thumbnailUrl:input.image?[input.image]:undefined,uploadDate:input.uploadDate||new Date().toISOString()};if(type==='article')return{...common,'@type':'Article',headline:input.title,datePublished:input.publishedAt||new Date().toISOString()};return{...common,'@type':'WebSite',potentialAction:{'@type':'SearchAction',target:`${input.url.replace(/\/$/,'')}/search?q={search_term_string}`,'query-input':'required name=search_term_string'}};}
function backlinkOpportunity(input={}){return{id:crypto.randomUUID(),targetUrl:canonical(input.baseUrl,input.targetPath),sourceDomain:String(input.sourceDomain||''),contactName:String(input.contactName||''),contactEmail:String(input.contactEmail||''),category:String(input.category||'creator-media'),region:String(input.region||'global'),authorityScore:Math.max(0,Math.min(100,Number(input.authorityScore)||0)),relevanceScore:Math.max(0,Math.min(100,Number(input.relevanceScore)||0)),status:'prospect',anchorText:String(input.anchorText||'TryAMM creator platform'),relationshipType:String(input.relationshipType||'editorial'),createdAt:new Date().toISOString()};}
function auditPage(input={}){const issues=[];const title=String(input.title||'');const description=String(input.description||'');if(!title)issues.push('Missing title');else if(title.length>60)issues.push('Title longer than 60 characters');if(!description)issues.push('Missing description');else if(description.length>160)issues.push('Description longer than 160 characters');if(!input.canonical)issues.push('Missing canonical URL');if(!input.h1)issues.push('Missing H1');if(Number(input.wordCount||0)<250)issues.push('Thin content under 250 words');if(!input.imageAltCoverage||Number(input.imageAltCoverage)<.9)issues.push('Image alt coverage below 90%');if(input.mobileFriendly===false)issues.push('Page is not mobile friendly');if(Number(input.lcpMs||0)>2500)issues.push('LCP slower than 2.5 seconds');if(Number(input.inpMs||0)>200)issues.push('INP slower than 200ms');if(Number(input.cls||0)>.1)issues.push('CLS above 0.1');return{score:Math.max(0,100-issues.length*10),issues,passed:issues.length===0};}
function sitemap(urls=[]){const body=urls.map(item=>`  <url><loc>${item.loc}</loc>${item.lastmod?`<lastmod>${item.lastmod}</lastmod>`:''}${item.changefreq?`<changefreq>${item.changefreq}</changefreq>`:''}${item.priority!==undefined?`<priority>${item.priority}</priority>`:''}</url>`).join('\n');return`<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${body}\n</urlset>`;}
module.exports={REGIONS,PAGE_TYPES,pageMeta,structuredData,backlinkOpportunity,auditPage,sitemap,canonical,slug};