const express=require('express');
const seo=require('./advanced-seo');
const supabaseService=require('./supabase');
const router=express.Router();
async function auth(req,res,next){if(!supabaseService.configured())return res.status(503).json({error:'Supabase is not configured.'});return supabaseService.requireUser(req,res,next);}
router.get('/regions',(req,res)=>res.json(seo.REGIONS));
router.post('/preview',(req,res)=>res.json(seo.pageMeta({...req.body,baseUrl:process.env.PUBLIC_APP_URL||'https://tryamm.online'})));
router.post('/audit',(req,res)=>res.json(seo.auditPage(req.body||{})));
router.get('/sitemap.xml',async(req,res,next)=>{try{const base=process.env.PUBLIC_APP_URL||'https://tryamm.online';const staticPaths=['','platform.html','holo.html','workstation.html','immersive-marketplace.html','growth-dashboard.html','memory-control.html','africa-commerce.html','yogihoo.html','openworld.html','seo-console.html'];let urls=staticPaths.map(path=>({loc:seo.canonical(base,path),changefreq:path?'weekly':'daily',priority:path?0.7:1}));if(supabaseService.configured()){const {data}=await supabaseService.admin().from('content_items').select('id,type,title,updated_at,status').eq('status','published').limit(5000);urls=urls.concat((data||[]).map(item=>({loc:seo.canonical(base,`${seo.slug(item.type)}/${seo.slug(item.title)}-${item.id}`),lastmod:item.updated_at,changefreq:'weekly',priority:.8})));}res.type('application/xml').send(seo.sitemap(urls));}catch(error){next(error);}});
router.get('/robots.txt',(req,res)=>{const base=process.env.PUBLIC_APP_URL||'https://tryamm.online';res.type('text/plain').send(`User-agent: *\nAllow: /\nDisallow: /api/\nDisallow: /admin/\nSitemap: ${seo.canonical(base,'api/memory/seo/sitemap.xml')}\n`);});
router.use(auth);
router.post('/pages',async(req,res,next)=>{try{const meta=seo.pageMeta({...req.body,baseUrl:process.env.PUBLIC_APP_URL||'https://tryamm.online'});const {data,error}=await supabaseService.admin().from('seo_pages').upsert({owner_id:req.user.id,path:req.body.path||new URL(meta.url).pathname,title:meta.title,description:meta.description,canonical_url:meta.canonical,country:meta.country,locale:meta.locale,robots:meta.robots,json_ld:meta.jsonLd,open_graph:meta.openGraph,twitter_card:meta.twitter,status:req.body.status||'draft'},{onConflict:'owner_id,path'}).select().single();if(error)throw error;res.status(201).json(data);}catch(error){next(error);}});
router.get('/pages',async(req,res,next)=>{try{const {data,error}=await supabaseService.admin().from('seo_pages').select('*').eq('owner_id',req.user.id).order('updated_at',{ascending:false});if(error)throw error;res.json(data);}catch(error){next(error);}});
router.post('/backlinks',async(req,res,next)=>{try{const item=seo.backlinkOpportunity({...req.body,baseUrl:process.env.PUBLIC_APP_URL||'https://tryamm.online'});const {data,error}=await supabaseService.admin().from('backlink_opportunities').insert({owner_id:req.user.id,target_url:item.targetUrl,source_domain:item.sourceDomain,contact_name:item.contactName,contact_email:item.contactEmail,category:item.category,region:item.region,authority_score:item.authorityScore,relevance_score:item.relevanceScore,status:item.status,anchor_text:item.anchorText,relationship_type:item.relationshipType}).select().single();if(error)throw error;res.status(201).json(data);}catch(error){next(error);}});
router.get('/backlinks',async(req,res,next)=>{try{const {data,error}=await supabaseService.admin().from('backlink_opportunities').select('*').eq('owner_id',req.user.id).order('created_at',{ascending:false});if(error)throw error;res.json(data);}catch(error){next(error);}});
router.patch('/backlinks/:id',async(req,res,next)=>{try{const allowed={};for(const key of ['status','contact_name','contact_email','authority_score','relevance_score','anchor_text','notes','earned_url'])if(req.body[key]!==undefined)allowed[key]=req.body[key];const {data,error}=await supabaseService.admin().from('backlink_opportunities').update(allowed).eq('id',req.params.id).eq('owner_id',req.user.id).select().single();if(error)throw error;res.json(data);}catch(error){next(error);}});
router.get('/dashboard',async(req,res,next)=>{try{const client=supabaseService.admin();const [{data:pages,error:pErr},{data:links,error:lErr}]=await Promise.all([client.from('seo_pages').select('*').eq('owner_id',req.user.id),client.from('backlink_opportunities').select('*').eq('owner_id',req.user.id)]);if(pErr||lErr)throw pErr||lErr;const earned=(links||[]).filter(x=>x.status==='earned');res.json({pages:(pages||[]).length,indexablePages:(pages||[]).filter(x=>String(x.robots||'').startsWith('index')).length,backlinkProspects:(links||[]).length,earnedBacklinks:earned.length,averageAuthority:earned.length?Math.round(earned.reduce((s,x)=>s+Number(x.authority_score||0),0)/earned.length):0,regionalCoverage:[...new Set((links||[]).map(x=>x.region).filter(Boolean))]});}catch(error){next(error);}});
module.exports={router};