const crypto=require('crypto');
function uid(prefix){return `${prefix}_${Date.now()}_${crypto.randomBytes(4).toString('hex')}`;}
function clean(value,max=240){return String(value||'').trim().slice(0,max);}
function requireFields(input,fields){for(const field of fields){if(!clean(input[field]))throw new Error(`${field} is required.`);}}
function onboarding(input={}){requireFields(input,['legalName','email','country','role']);const role=clean(input.role).toLowerCase();if(!['driver','courier'].includes(role))throw new Error('Role must be driver or courier.');return{id:uid(role),role,legalName:clean(input.legalName),email:clean(input.email),phone:clean(input.phone),country:clean(input.country).toUpperCase(),city:clean(input.city),status:'pending-review',identity:{status:'pending',provider:process.env.IDENTITY_PROVIDER||'mock'},backgroundCheck:{status:'not-started',provider:process.env.BACKGROUND_CHECK_PROVIDER||'mock'},license:{status:'pending',numberMasked:clean(input.licenseNumber).replace(/.(?=.{4})/g,'*'),expiresAt:clean(input.licenseExpiresAt)},insurance:{status:'pending',provider:clean(input.insuranceProvider),expiresAt:clean(input.insuranceExpiresAt)},vehicle:role==='driver'?{make:clean(input.vehicleMake),model:clean(input.vehicleModel),year:Number(input.vehicleYear)||null,plateMasked:clean(input.plate).replace(/.(?=.{3})/g,'*')} : null,training:{safety:false,accessibility:false,platform:false},createdAt:new Date().toISOString()};}
function complianceGate(profile={}){const reasons=[];if(profile.identity?.status!=='verified')reasons.push('identity');if(profile.backgroundCheck?.status!=='clear')reasons.push('background-check');if(profile.license?.status!=='verified')reasons.push('license');if(profile.insurance?.status!=='verified')reasons.push('insurance');if(!profile.training?.safety)reasons.push('safety-training');return{eligible:reasons.length===0,reasons};}
function dispatchOffer(input={}){requireFields(input,['requestId','workerId','pickup','dropoff']);return{id:uid('offer'),requestId:clean(input.requestId),workerId:clean(input.workerId),pickup:clean(input.pickup),dropoff:clean(input.dropoff),distanceKm:Number(input.distanceKm)||0,estimatedMinutes:Number(input.estimatedMinutes)||0,estimatedEarnings:Number(input.estimatedEarnings)||0,currency:clean(input.currency||'USD').toUpperCase(),status:'offered',expiresAt:new Date(Date.now()+30000).toISOString(),createdAt:new Date().toISOString()};}
function tripEvent(input={}){requireFields(input,['tripId','type']);const allowed=['accepted','arrived-pickup','started','arrived-dropoff','completed','cancelled','sos','location'];if(!allowed.includes(clean(input.type)))throw new Error('Unsupported trip event.');return{id:uid('event'),tripId:clean(input.tripId),type:clean(input.type),latitude:Number.isFinite(Number(input.latitude))?Number(input.latitude):null,longitude:Number.isFinite(Number(input.longitude))?Number(input.longitude):null,note:clean(input.note,500),createdAt:new Date().toISOString()};}
function safetyIncident(input={}){requireFields(input,['tripId','reporterId','category']);return{id:uid('incident'),tripId:clean(input.tripId),reporterId:clean(input.reporterId),category:clean(input.category),severity:clean(input.severity||'medium'),description:clean(input.description,1000),status:'open',emergencyServicesContacted:Boolean(input.emergencyServicesContacted),createdAt:new Date().toISOString()};}
module.exports={onboarding,complianceGate,dispatchOffer,tripEvent,safetyIncident};