'use strict';
const crypto=require('crypto');
const id=p=>`${p}_${crypto.randomBytes(8).toString('hex')}`;
const clean=(v,m=1000)=>String(v??'').replace(/\s+/g,' ').trim().slice(0,m);
function hold(input={}){if(!clean(input.provider,120))throw new Error('provider_required');return {id:id('hold'),provider:clean(input.provider,120),providerReference:clean(input.providerReference,240)||null,transactionId:clean(input.transactionId,160),amount:Math.max(0,Number(input.amount)||0),currency:clean(input.currency,3).toUpperCase()||'USD',reason:clean(input.reason,500),status:'requested',custody:'provider',tryammCustody:false,releaseConditions:Array.isArray(input.releaseConditions)?input.releaseConditions.map(x=>clean(x,300)).filter(Boolean):[],authorizedBy:clean(input.authorizedBy,160)||null,createdAt:new Date().toISOString()};}
function reserve(input={}){return {id:id('reserve'),provider:clean(input.provider,120),merchantId:clean(input.merchantId,160),basisPoints:Math.max(0,Math.min(10000,Number(input.basisPoints)||0)),maxAmount:Math.max(0,Number(input.maxAmount)||0),reason:clean(input.reason,500),status:'proposed',requiresProviderSupport:true,requiresMerchantTerms:true};}
function claim(input={}){return {id:id('claim'),caseId:clean(input.caseId,160),claimType:clean(input.claimType,100),policyOrProtectionRef:clean(input.policyOrProtectionRef,240)||null,provider:clean(input.provider,160)||null,amountClaimed:Math.max(0,Number(input.amountClaimed)||0),currency:clean(input.currency,3).toUpperCase()||'USD',incidentAt:clean(input.incidentAt,40)||null,evidenceRefs:Array.isArray(input.evidenceRefs)?input.evidenceRefs.slice(0,100):[],status:'draft',submittedExternally:false,createdAt:new Date().toISOString()};}
function releaseGate({holdRecord,caseRecord,providerStatus,authorizedHuman=false}={}){const disputeOpen=caseRecord&&['open','appealed'].includes(caseRecord.status);const providerReady=['releasable','approved'].includes(providerStatus);const allowed=!!holdRecord&&!disputeOpen&&providerReady&&authorizedHuman;return {holdId:holdRecord?.id||null,allowed,requiresAuthorizedHuman:true,requiresProviderExecution:true,tryammMovesFundsDirectly:false,reasons:[!holdRecord&&'hold_missing',disputeOpen&&'dispute_open',!providerReady&&'provider_not_ready',!authorizedHuman&&'human_authorization_missing'].filter(Boolean)};}
function settlementInstruction({holdRecord,destinationRef,amount,authorizedHuman=false}={}){if(!authorizedHuman)throw new Error('human_authorization_required');return {instructionId:id('settle'),provider:holdRecord?.provider||null,providerReference:holdRecord?.providerReference||null,destinationRef:clean(destinationRef,240),amount:Math.max(0,Number(amount)||0),currency:holdRecord?.currency||'USD',mode:'PROVIDER_EXECUTION_ONLY',tryammCustody:false,createdAt:new Date().toISOString()};}
module.exports={hold,reserve,claim,releaseGate,settlementInstruction};
