'use strict';
const crypto=require('crypto');
const id=p=>`${p}_${crypto.randomBytes(8).toString('hex')}`;
const clean=(v,m=500)=>String(v??'').replace(/\s+/g,' ').trim().slice(0,m);
const TYPES=new Set(['license','registration','permit','certification','insurance','bond','background-check','inspection','tax-registration','professional-credential','other']);
function credential(input={}){if(!clean(input.ownerId,160))throw new Error('owner_required');if(!clean(input.name,200))throw new Error('name_required');return {id:input.id||id('cred'),ownerId:clean(input.ownerId,160),ownerType:clean(input.ownerType,80)||'business',type:TYPES.has(input.type)?input.type:'other',name:clean(input.name,200),issuer:clean(input.issuer,200)||null,jurisdiction:clean(input.jurisdiction,120)||null,numberLast4:clean(input.numberLast4,4)||null,issuedAt:clean(input.issuedAt,40)||null,expiresAt:clean(input.expiresAt,40)||null,status:clean(input.status,40)||'pending',verifiedAt:clean(input.verifiedAt,40)||null,evidenceRefs:Array.isArray(input.evidenceRefs)?input.evidenceRefs.slice(0,100):[],capabilities:Array.isArray(input.capabilities)?input.capabilities.map(x=>clean(x,100)).filter(Boolean):[],sensitiveValuesStored:false};}
function insurance(input={}){const c=credential({...input,type:'insurance'});return {...c,carrier:clean(input.carrier,200)||null,policyLast4:clean(input.policyLast4,4)||null,coverageTypes:Array.isArray(input.coverageTypes)?input.coverageTypes.map(x=>clean(x,100)).filter(Boolean):[],limits:input.limits&&typeof input.limits==='object'?input.limits:{},additionalInsuredRequired:input.additionalInsuredRequired===true};}
function daysUntil(v,now=new Date()){if(!v)return null;const d=new Date(v);return Number.isNaN(d.getTime())?null:Math.ceil((d-now)/86400000);}
function status(item,now=new Date()){const days=daysUntil(item.expiresAt,now);if(item.status==='rejected'||item.status==='revoked')return {state:item.status,usable:false,daysRemaining:days};if(item.status!=='verified'||!item.verifiedAt)return {state:'unverified',usable:false,daysRemaining:days};if(days!==null&&days<0)return {state:'expired',usable:false,daysRemaining:days};if(days!==null&&days<=30)return {state:'expiring',usable:true,daysRemaining:days};return {state:'active',usable:true,daysRemaining:days};}
function capabilityGate({credentials=[],capability,ownerId,now=new Date()}={}){const relevant=credentials.filter(c=>(!ownerId||c.ownerId===ownerId)&&c.capabilities.includes(capability));const evaluated=relevant.map(c=>({...c,health:status(c,now)}));return {capability:clean(capability,100),ownerId:clean(ownerId,160),allowed:evaluated.length>0&&evaluated.every(c=>c.health.usable),credentials:evaluated.map(c=>({id:c.id,name:c.name,type:c.type,jurisdiction:c.jurisdiction,expiresAt:c.expiresAt,health:c.health})),reason:evaluated.length===0?'required_credential_missing':evaluated.some(c=>!c.health.usable)?'credential_not_usable':'verified'};}
function reminders(credentials=[],now=new Date()){return credentials.map(c=>({id:c.id,name:c.name,ownerId:c.ownerId,...status(c,now),expiresAt:c.expiresAt})).filter(x=>['expiring','expired','unverified','rejected','revoked'].includes(x.state)).sort((a,b)=>(a.daysRemaining??1e9)-(b.daysRemaining??1e9));}
module.exports={TYPES,credential,insurance,daysUntil,status,capabilityGate,reminders};
