'use strict';
const faith=require('./faith-calendar');
const clean=(v,m=1000)=>String(v??'').trim().slice(0,m);
module.exports=function registerFaithRoutes({app,auth,getStore,saveStore}){
  function ensure(){const s=getStore();s.faithPreferences||={};s.faithMoonEvents||=[];s.faithCommunityEvents||=[];s.faithStudyCards||=[];return s;}
  app.get('/api/faith/profile',auth,(req,res)=>{const s=ensure(),prefs=faith.normalizePrefs(s.faithPreferences[req.user.id]||{});res.json({identityLane:'Judah / Israelite faith community',preferences:prefs,principles:{voluntary:true,noRequiredBeliefForGeneralPlatformUse:true,commercialFeaturesSeparateFromWorship:true}})});
  app.put('/api/faith/profile',auth,async(req,res)=>{const s=ensure(),prefs=faith.normalizePrefs(req.body||{});s.faithPreferences[req.user.id]=prefs;await saveStore();res.json({preferences:prefs})});
  app.get('/api/faith/calendar',auth,(req,res)=>{const s=ensure(),prefs=faith.normalizePrefs(s.faithPreferences[req.user.id]||{}),sabbath=faith.nextWeeklySabbath(new Date(),prefs);const moons=s.faithMoonEvents.filter(x=>!prefs.communityId||x.communityId===prefs.communityId).slice(-24);res.json({sabbath,newMoons:moons,preferences:prefs,calendarNotice:'Sabbath and New Moon methods can differ among communities. Astronomical sunset/crescent timing should come from a verified astronomy source before being labeled exact.'})});
  app.post('/api/faith/new-moon',auth,async(req,res)=>{const s=ensure(),event={...faith.moonEvent(req.body),communityId:clean(req.body.communityId,160)||null,createdBy:req.user.id};s.faithMoonEvents.push(event);s.faithMoonEvents=s.faithMoonEvents.slice(-500);await saveStore();res.status(201).json({event})});
  app.get('/api/faith/observance',auth,(req,res)=>{const s=ensure(),prefs=faith.normalizePrefs(s.faithPreferences[req.user.id]||{}),sabbath=faith.nextWeeklySabbath(new Date(),prefs);const moon=s.faithMoonEvents.find(x=>new Date(x.startsAt)<=new Date()&&(!x.endsAt||new Date(x.endsAt)>new Date()));res.json(faith.observanceState({now:new Date(),sabbath,newMoon:moon,prefs}))});
  app.get('/api/faith/study',auth,(_req,res)=>res.json({cards:ensure().faithStudyCards||[],supportedCollections:['Tanakh / Hebrew Bible','New Testament','Ethiopian canon references','Apocrypha / Deuterocanon','Historical and academic commentary'],notice:'Study resources should distinguish scripture text, interpretation, tradition, and historical scholarship.'}));
  app.post('/api/faith/study',auth,async(req,res)=>{const s=ensure(),card={id:`study_${Date.now()}`,createdBy:req.user.id,...faith.studyCard(req.body),createdAt:new Date().toISOString()};s.faithStudyCards.push(card);s.faithStudyCards=s.faithStudyCards.slice(-1000);await saveStore();res.status(201).json({card})});
  app.get('/api/faith/community-events',auth,(req,res)=>res.json({events:ensure().faithCommunityEvents.filter(e=>!e.private||e.createdBy===req.user.id)}));
  app.post('/api/faith/community-events',auth,async(req,res)=>{const s=ensure(),event={id:`faith_evt_${Date.now()}`,title:clean(req.body.title,200),description:clean(req.body.description,2000),startsAt:clean(req.body.startsAt,60),endsAt:clean(req.body.endsAt,60)||null,type:clean(req.body.type,80)||'study',private:req.body.private===true,createdBy:req.user.id,createdAt:new Date().toISOString()};if(!event.title||!event.startsAt)return res.status(400).json({error:'title and startsAt required'});s.faithCommunityEvents.push(event);await saveStore();res.status(201).json({event})});
};
