'use strict';
const inv=require('./inventory-intelligence');
module.exports=function registerInventoryRoutes({app,auth,admin,getStore}){
 function state(){const s=getStore();s.marketplaceProducts||=[];s.marketplaceOrders||=[];s.marketplaceMerchants||=[];s.inventoryPolicies||={};return s;}
 function merchantFor(userId,s){return s.marketplaceMerchants.find(m=>m.userId===userId);}
 function metrics(s,days=30){const cutoff=Date.now()-days*86400000,out={};for(const o of s.marketplaceOrders){if(!['paid','fulfilled','shipped','delivered'].includes(o.status))continue;const at=Date.parse(o.paidAt||o.createdAt||0);if(!Number.isFinite(at)||at<cutoff)continue;const r=out[o.productId]||={units:0};r.units+=Math.max(0,Number(o.quantity)||0);out[o.productId]=r;}return Object.fromEntries(Object.entries(out).map(([k,v])=>[k,{avgDailyUnits:Number((v.units/days).toFixed(3))}]));}
 app.get('/api/marketplace/inventory/alerts',auth,(req,res)=>{const s=state(),m=merchantFor(req.user.id,s);if(!m)return res.status(404).json({error:'Merchant application required'});const products=s.marketplaceProducts.filter(p=>p.merchantId===m.id);const all=products.map(p=>inv.analyzeProduct(p,metrics(s)[p.id]||{},s.inventoryPolicies[p.id]||{}));res.json({alerts:all.filter(x=>x.state!=='healthy'&&x.state!=='not-applicable'),summary:inv.portfolioSummary(all),source:'marketplace operational projection',note:'Production reorder automation must use persistent inventory events and verified supplier/warehouse availability.'});});
 app.put('/api/marketplace/products/:productId/inventory-policy',auth,async(req,res)=>{const s=state(),m=merchantFor(req.user.id,s),p=m&&s.marketplaceProducts.find(x=>x.id===req.params.productId&&x.merchantId===m.id);if(!p)return res.status(404).json({error:'Product not found'});s.inventoryPolicies[p.id]=inv.policy(req.body);res.json({productId:p.id,policy:s.inventoryPolicies[p.id]});});
 app.get('/api/admin/inventory/alerts',auth,admin,(_req,res)=>{const s=state(),m=metrics(s),all=s.marketplaceProducts.map(p=>inv.analyzeProduct(p,m[p.id]||{},s.inventoryPolicies[p.id]||{}));res.json({alerts:all.filter(x=>x.state!=='healthy'&&x.state!=='not-applicable'),summary:inv.portfolioSummary(all)});});
};
