'use strict';
const readiness=require('./platform-readiness');
const providers=require('./provider-registry');
const tx=require('./transaction-core');
const clean=(v,m=500)=>String(v??'').trim().slice(0,m);
module.exports=function registerOperations({app,auth,admin,getStore,saveStore}){
 function ops(){const s=getStore();s.operationalEvidence||={providers:{},release:{migrationsApplied:false,oauthProvidersTested:false,stripeWebhookVerified:false,turnConnectivityTested:false,marketplaceUsesPersistentDb:false,holoUsesPersistentDb:false,regulatedFeaturesApproved:false,e2ePassed:false,observabilityConfigured:false,backupRestoreTested:false,securityScansPassed:false,rateLimitsVerified:false,wafVerified:false,incidentDrillPassed:false,secretsRotationTested:false,legacySessionMigrationComplete:false},history:[]};
  const defaults={migrationsApplied:false,oauthProvidersTested:false,stripeWebhookVerified:false,turnConnectivityTested:false,marketplaceUsesPersistentDb:false,holoUsesPersistentDb:false,regulatedFeaturesApproved:false,e2ePassed:false,observabilityConfigured:false,backupRestoreTested:false,securityScansPassed:false,rateLimitsVerified:false,wafVerified:false,incidentDrillPassed:false,secretsRotationTested:false,legacySessionMigrationComplete:false};
  s.operationalEvidence.providers||={};s.operationalEvidence.release={...defaults,...(s.operationalEvidence.release||{})};s.operationalEvidence.history||=[];return s.operationalEvidence;}
 app.get('/api/admin/operations/readiness',auth,admin,(_req,res)=>{const o=ops(),providerStatus=providers.registry(process.env,o.providers),release=readiness.deploymentTruth({...o.release,marketplaceUsesPersistentDb:o.release.marketplaceUsesPersistentDb&&tx.configured()});res.json({release,providers:providerStatus,transactionCore:{configured:tx.configured(),requiredInProduction:true},rules:{libraryOnlyIsNotProduction:true,providerConfiguredIsNotVerified:true,greenRequiresEvidence:true,securityEvidenceRequired:true}})});
 app.post('/api/admin/operations/evidence',auth,admin,async(req,res)=>{const o=ops(),kind=clean(req.body.kind,40),key=clean(req.body.key,120);if(!['release','provider'].includes(kind)||!key)return res.status(400).json({error:'kind and key are required'});const now=new Date().toISOString();if(kind==='release'){const allowed=new Set(Object.keys(o.release));if(!allowed.has(key))return res.status(400).json({error:'Unknown release evidence key'});o.release[key]=req.body.value===true;}else{o.providers[key]={...(o.providers[key]||{}),liveTested:req.body.liveTested===true,contractApproved:req.body.contractApproved===true,webhookVerified:req.body.webhookVerified===true,lastVerifiedAt:now};}o.history.push({kind,key,actor:req.user.id,at:now,value:req.body.value===true||undefined});o.history=o.history.slice(-500);await saveStore();res.json({ok:true,recordedAt:now})});
 app.get('/api/admin/operations/providers',auth,admin,(_req,res)=>res.json({providers:providers.registry(process.env,ops().providers)}));
};
