'use strict';

const crypto=require('crypto');
const dns=require('dns').promises;
const net=require('net');

const UA='TRYAMMBot/0.1 (+https://tryamm.online/bot)';
const MAX_BYTES=2*1024*1024;
const ROBOTS_TTL=12*60*60*1000;
const robotsCache=new Map();
const hostNextFetch=new Map();

function sha(v){return crypto.createHash('sha256').update(String(v||'')).digest('hex');}
function privateIp(ip){if(net.isIP(ip)===4){const p=ip.split('.').map(Number);return p[0]===10||p[0]===127||(p[0]===169&&p[1]===254)||(p[0]===172&&p[1]>=16&&p[1]<=31)||(p[0]===192&&p[1]===168);}if(net.isIP(ip)===6)return ip==='::1'||ip.startsWith('fc')||ip.startsWith('fd')||ip.startsWith('fe80:');return true;}
async function safeUrl(raw){const u=new URL(raw);if(!['http:','https:'].includes(u.protocol))throw new Error('unsupported_protocol');if(u.username||u.password)throw new Error('userinfo_not_allowed');const answers=await dns.lookup(u.hostname,{all:true});if(!answers.length||answers.some(x=>privateIp(x.address)))throw new Error('private_or_unresolved_host');return u;}
function parseRobots(text,product='TRYAMMBot'){const lines=String(text||'').split(/\r?\n/),groups=[];let agents=[],rules=[];const flush=()=>{if(agents.length)groups.push({agents:[...agents],rules:[...rules]});agents=[];rules=[];};for(const raw of lines){const line=raw.replace(/#.*$/,'').trim();if(!line)continue;const i=line.indexOf(':');if(i<0)continue;const k=line.slice(0,i).trim().toLowerCase(),v=line.slice(i+1).trim();if(k==='user-agent'){if(rules.length)flush();agents.push(v.toLowerCase());}else if((k==='allow'||k==='disallow')&&agents.length)rules.push({type:k,path:v});}flush();const p=product.toLowerCase();let matched=groups.filter(g=>g.agents.includes(p));if(!matched.length)matched=groups.filter(g=>g.agents.includes('*'));return matched.flatMap(g=>g.rules);}
function allowedByRules(u,rules){const path=u.pathname+(u.search||'');let best=null;for(const r of rules){if(!r.path)continue;if(path.startsWith(r.path)&&(!best||r.path.length>best.path.length||(r.path.length===best.path.length&&r.type==='allow')))best=r;}return !best||best.type==='allow';}
async function robotsFor(u){const key=u.origin,hit=robotsCache.get(key);if(hit&&Date.now()-hit.at<ROBOTS_TTL)return hit.rules;let rules=[];try{const r=await fetch(new URL('/robots.txt',u.origin),{headers:{'user-agent':UA},redirect:'follow',signal:AbortSignal.timeout(7000)});if(r.status>=500)throw new Error('robots_unreachable');if(r.ok)rules=parseRobots((await r.text()).slice(0,512*1024));}catch(e){if(String(e.message).includes('robots_unreachable'))rules=[{type:'disallow',path:'/'}];else rules=[{type:'disallow',path:'/'}];}robotsCache.set(key,{at:Date.now(),rules});return rules;}
async function politeness(host,delayMs=1200){const now=Date.now(),next=hostNextFetch.get(host)||0;if(next>now)await new Promise(r=>setTimeout(r,next-now));hostNextFetch.set(host,Date.now()+delayMs);}
function stripHtml(html){return String(html||'').replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi,' ').replace(/<style\b[^>]*>[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/&nbsp;/g,' ').replace(/&amp;/g,'&').replace(/\s+/g,' ').trim();}
function links(html,base){const out=[];for(const m of String(html||'').matchAll(/href=["']([^"'#]+)["']/gi)){try{const u=new URL(m[1],base);if(['http:','https:'].includes(u.protocol))out.push(u.href);}catch{}}return [...new Set(out)].slice(0,250);}
async function crawlOne(raw,{delayMs=1200}={}){const u=await safeUrl(raw),rules=await robotsFor(u);if(!allowedByRules(u,rules))return{url:u.href,status:'blocked_by_robots'};await politeness(u.hostname,delayMs);const r=await fetch(u,{headers:{'user-agent':UA,'accept':'text/html,application/xhtml+xml,text/plain;q=0.9'},redirect:'follow',signal:AbortSignal.timeout(12000)});const type=r.headers.get('content-type')||'';if(!r.ok)return{url:u.href,status:'http_error',httpStatus:r.status};if(!/(text\/html|application\/xhtml\+xml|text\/plain)/i.test(type))return{url:u.href,status:'unsupported_content',contentType:type};const declared=Number(r.headers.get('content-length')||0);if(declared>MAX_BYTES)return{url:u.href,status:'too_large'};const body=(await r.text()).slice(0,MAX_BYTES);const title=(body.match(/<title[^>]*>([\s\S]*?)<\/title>/i)||[])[1]||u.hostname;const text=stripHtml(body).slice(0,100000);return{url:u.href,canonicalUrl:u.href,host:u.hostname,status:'fetched',httpStatus:r.status,title:stripHtml(title).slice(0,300),text,contentHash:sha(text),fetchedAt:new Date().toISOString(),outLinks:links(body,u.href)};}
function indexDocument(doc){if(doc.status!=='fetched')return null;return{id:sha(doc.canonicalUrl).slice(0,24),url:doc.canonicalUrl,host:doc.host,title:doc.title,text:doc.text,contentHash:doc.contentHash,fetchedAt:doc.fetchedAt,sourceType:'quantum_index',sourceLabel:'QUANTUM INDEX',score:52};}
module.exports={UA,parseRobots,allowedByRules,crawlOne,indexDocument,safeUrl};
