'use strict';
const crypto=require('crypto');
const clean=(v,m=500)=>String(v??'').replace(/\s+/g,' ').trim().slice(0,m);
const id=p=>`${p}_${crypto.randomBytes(8).toString('hex')}`;
const LEVELS=new Set(['federal','state','county','city','international','contractual']);
function requirement(input={}){if(!clean(input.name,200))throw new Error('name_required');return {id:input.id||id('req'),name:clean(input.name,200),domain:clean(input.domain,80)||'general',jurisdiction:clean(input.jurisdiction,120)||'unknown',level:LEVELS.has(input.level)?input.level:'state',authority:clean(input.authority,200)||null,sourceUrl:clean(input.sourceUrl,2000)||null,effectiveDate:clean(input.effectiveDate,40)||null,expiresAt:clean(input.expiresAt,40)||null,renewalDays:Number(input.renewalDays)||null,requiredFor:Array.isArray(input.requiredFor)?input.requiredFor.map(x=>clean(x,100)).filter(Boolean):[],blocksFeature:input.blocksFeature===true,evidenceRefs:Array.isArray(input.evidenceRefs)?input.evidenceRefs.slice(0,100):[],status:clean(input.status,40)||'unverified',lastVerifiedAt:clean(input.lastVerifiedAt,40)||null};}
function buildGraph(items=[]){const reqs=items.map(x=>requirement(x));const byDomain={},byJurisdiction={};for(const r of reqs){(byDomain[r.domain]??=[]).push(r.id);(byJurisdiction[r.jurisdiction]??=[]).push(r.id);}return {protocol:'tryamm-regulatory-graph/1.0',requirements:reqs,byDomain,byJurisdiction,generatedAt:new Date().toISOString()};}
function daysUntil(date,now=new Date()){if(!date)return null;const d=new Date(date);if(Number.isNaN(d.getTime()))return null;return Math.ceil((d-now)/86400000);}
function calendar(graph={},now=new Date()){return (graph.requirements||[]).map(r=>{const days=daysUntil(r.expiresAt,now);let urgency='none';if(days!==null)urgency=days<0?'expired':days<=7?'critical':days<=30?'high':days<=90?'medium':'low';return {requirementId:r.id,name:r.name,domain:r.domain,jurisdiction:r.jurisdiction,expiresAt:r.expiresAt,daysRemaining:days,urgency,blocksFeature:r.blocksFeature,featureBlocked:r.blocksFeature&&(days!==null&&days<0)};}).sort((a,b)=>(a.daysRemaining??1e9)-(b.daysRemaining??1e9));}
function launchGate({graph,domain,jurisdictions=[],feature}={}){const relevant=(graph?.requirements||[]).filter(r=>r.domain===domain&&(jurisdictions.length===0||jurisdictions.includes(r.jurisdiction))&&(r.requiredFor.length===0||r.requiredFor.includes(feature)));const blockers=relevant.filter(r=>r.blocksFeature&&(['expired','missing','rejected','unverified'].includes(r.status)||!r.lastVerifiedAt));return {feature:clean(feature,120),domain,jurisdictions,allowed:blockers.length===0,blockers:blockers.map(r=>({id:r.id,name:r.name,jurisdiction:r.jurisdiction,status:r.status,authority:r.authority,sourceUrl:r.sourceUrl})),checkedAt:new Date().toISOString(),note:'Automated compliance gate; verify current law and professional/licensing requirements before regulated launch.'};}
module.exports={LEVELS,requirement,buildGraph,daysUntil,calendar,launchGate};
