'use strict';
const sec=require('./security-guardian');
module.exports=function registerSecurity({app,auth,admin,getStore,saveStore}){
 function state(){const s=getStore();s.securityEvents||=[];s.securityEvidence||={dependencyScan:false,secretScan:false,sast:false,dast:false,redTeam:false,backupRestore:false,incidentDrill:false,sessionMigration:false,rateLimitsVerified:false,wafVerified:false};return s;}
 app.use('/api',sec.harden,sec.sensitiveWrite,sec.rateLimit({scope:'api',limit:Number(process.env.API_RATE_LIMIT||180),windowMs:60000}));
 app.use('/api/auth',sec.rateLimit({scope:'auth',limit:Number(process.env.AUTH_RATE_LIMIT||20),windowMs:60000}));
 app.use('/api/marketplace/checkout',sec.rateLimit({scope:'checkout',limit:Number(process.env.CHECKOUT_RATE_LIMIT||30),windowMs:60000}));
 app.get('/api/admin/security/posture',auth,admin,(req,res)=>{const s=state();const required=Object.entries(s.securityEvidence);const missing=required.filter(([,v])=>v!==true).map(([k])=>k);res.json({status:missing.length?'HARDENING_REQUIRED':'VERIFIED',evidence:s.securityEvidence,missing,recentEvents:s.securityEvents.slice(-100).reverse(),teams:{red:'authorized adversarial testing only',blue:'detection response hardening',purple:'red-blue remediation validation',green:'privacy safety resilience compliance and recovery'},rules:{leastPrivilege:true,noSecretsInBrowser:true,noRawSensitiveIdentityData:true,highImpactAiRequiresApproval:true,productionGreenRequiresEvidence:true}});});
 app.post('/api/admin/security/evidence',auth,admin,async(req,res)=>{const s=state(),key=String(req.body.key||'');if(!(key in s.securityEvidence))return res.status(400).json({error:'Unknown security evidence key'});s.securityEvidence[key]=req.body.value===true;s.securityEvents.push(sec.securityEvent({type:'security.evidence.updated',severity:'info',actorId:req.user.id,requestId:req.requestId,target:key,details:{value:s.securityEvidence[key]}}));s.securityEvents=s.securityEvents.slice(-1000);await saveStore();res.json({ok:true,key,value:s.securityEvidence[key]});});
 app.post('/api/security/report',auth,async(req,res)=>{const s=state(),event=sec.securityEvent({type:'user.security.report',severity:'medium',actorId:req.user.id,requestId:req.requestId,target:req.body.target,details:{category:req.body.category,description:req.body.description}});s.securityEvents.push(event);s.securityEvents=s.securityEvents.slice(-1000);await saveStore();res.status(201).json({accepted:true,reference:event.id});});
};
