'use strict';
const crypto=require('crypto');
const db=require('./supabase-rest');
const env=n=>String(process.env[n]||'').trim();
function configured(){return db.configured()&&!!env('SECURITY_VAULT_KEY');}
function key(){const raw=env('SECURITY_VAULT_KEY');if(!raw)throw new Error('security_vault_key_missing');return crypto.createHash('sha256').update(raw).digest();}
function encrypt(plaintext){const iv=crypto.randomBytes(12),cipher=crypto.createCipheriv('aes-256-gcm',key(),iv);const enc=Buffer.concat([cipher.update(String(plaintext),'utf8'),cipher.final()]);return {ciphertext:enc.toString('base64url'),iv:iv.toString('base64url'),tag:cipher.getAuthTag().toString('base64url')};}
function decryptFields(record,prefix='totp_secret'){const ct=record?.[`${prefix}_ciphertext`],iv=record?.[`${prefix}_iv`],tag=record?.[`${prefix}_tag`];if(!ct||!iv||!tag)return null;const decipher=crypto.createDecipheriv('aes-256-gcm',key(),Buffer.from(iv,'base64url'));decipher.setAuthTag(Buffer.from(tag,'base64url'));return Buffer.concat([decipher.update(Buffer.from(ct,'base64url')),decipher.final()]).toString('utf8');}
async function getMfa(userId){const rows=await db.select('security_mfa_profiles',`user_id=eq.${encodeURIComponent(userId)}&limit=1`);return rows?.[0]||null;}
async function upsertMfa(userId,row){const existing=await getMfa(userId),payload={...row,user_id:userId,updated_at:new Date().toISOString()};return existing?db.update('security_mfa_profiles',`user_id=eq.${encodeURIComponent(userId)}`,payload):db.insert('security_mfa_profiles',[payload]);}
async function savePendingTotp(userId,secret){const enc=encrypt(secret);return upsertMfa(userId,{pending_totp_secret_ciphertext:enc.ciphertext,pending_totp_secret_iv:enc.iv,pending_totp_secret_tag:enc.tag});}
async function getPendingTotp(userId){const p=await getMfa(userId);return decryptFields(p,'pending_totp_secret');}
async function saveMfa({userId,enabled,methods=[],totpSecret,recoveryCodeHashes=[]}){const enc=totpSecret?encrypt(totpSecret):null;return upsertMfa(userId,{enabled:!!enabled,methods,recovery_code_hashes:recoveryCodeHashes,pending_totp_secret_ciphertext:null,pending_totp_secret_iv:null,pending_totp_secret_tag:null,...(enc?{totp_secret_ciphertext:enc.ciphertext,totp_secret_iv:enc.iv,totp_secret_tag:enc.tag}:{})});}
async function getTotpSecret(userId){const p=await getMfa(userId);return decryptFields(p,'totp_secret');}
async function saveStepUp(record){return db.insert('security_stepup_challenges',[{id:record.id,token_hash:record.tokenHash,user_id:record.userId,session_id:record.sessionId,action:record.action,method:record.method,created_at:new Date(record.createdAt).toISOString(),expires_at:new Date(record.expiresAt).toISOString(),used_at:record.usedAt?new Date(record.usedAt).toISOString():null}]);}
async function consumeStepUp({tokenHash,userId,sessionId,action}){const rows=await db.select('security_stepup_challenges',`token_hash=eq.${encodeURIComponent(tokenHash)}&user_id=eq.${encodeURIComponent(userId)}&session_id=eq.${encodeURIComponent(sessionId)}&action=eq.${encodeURIComponent(action)}&used_at=is.null&expires_at=gt.${encodeURIComponent(new Date().toISOString())}&limit=1`);const r=rows?.[0];if(!r)return null;await db.update('security_stepup_challenges',`id=eq.${encodeURIComponent(r.id)}&used_at=is.null`,{used_at:new Date().toISOString()});return r;}
async function getAccountState(userId){const rows=await db.select('security_account_state',`user_id=eq.${encodeURIComponent(userId)}&limit=1`);return rows?.[0]||null;}
async function setAccountState(userId,patch={}){const existing=await getAccountState(userId),row={...patch,user_id:userId,updated_at:new Date().toISOString()};return existing?db.update('security_account_state',`user_id=eq.${encodeURIComponent(userId)}`,row):db.insert('security_account_state',[row]);}
async function audit({userId=null,actorId=null,sessionId=null,eventType,severity='info',requestId=null,metadata={}}){return db.insert('security_audit_events',[{user_id:userId,actor_id:actorId,session_id:sessionId,event_type:eventType,severity,request_id:requestId,metadata}]);}
module.exports={configured,encrypt,decryptFields,getMfa,savePendingTotp,getPendingTotp,saveMfa,getTotpSecret,saveStepUp,consumeStepUp,getAccountState,setAccountState,audit};
