'use strict';
const clean=(v,m=300)=>String(v??'').replace(/\s+/g,' ').trim().slice(0,m);
const SIGNALS=new Set(['account-takeover','payment-fraud','chargeback','counterfeit','late-fulfillment','non-delivery','warehouse-error','driver-incident','contractor-dispute','seller-dispute','supplier-defect','tracking-mismatch','identity-mismatch','policy-violation','positive-fulfillment','positive-resolution']);
const PROHIBITED=['race','color','religion','sex','gender','sexual_orientation','national_origin','disability','familial_status','genetic_information','political_affiliation'];
function signal(input={}){if(!SIGNALS.has(input.type))throw new Error('unsupported_signal');return {type:input.type,subjectId:clean(input.subjectId,160),source:clean(input.source,160),eventId:clean(input.eventId,160)||null,severity:Math.max(0,Math.min(100,Number(input.severity)||0)),confidence:Math.max(0,Math.min(1,Number(input.confidence)||0)),occurredAt:clean(input.occurredAt,40)||new Date().toISOString(),resolved:input.resolved===true,evidenceRefs:Array.isArray(input.evidenceRefs)?input.evidenceRefs.slice(0,50):[],appealable:input.appealable!==false};}
function score(signals=[]){let risk=0,positive=0;for(const s of signals){const weight=(s.severity||0)*(s.confidence||0)*(s.resolved?.35:1);if(s.type.startsWith('positive-'))positive+=weight;else risk+=weight;}const value=Math.max(0,Math.min(100,50+(positive/20)-(risk/20)));return {trustScore:Number(value.toFixed(1)),riskBand:value>=80?'low':value>=60?'guarded':value>=40?'elevated':'high',signalCount:signals.length,explainable:true,notCreditScore:true};}
function decision({signals=[],action='general',highImpact=false}={}){const s=score(signals);let mode='allow';if(s.riskBand==='high')mode=highImpact?'human-review':'step-up';else if(s.riskBand==='elevated')mode='step-up';return {action:clean(action,120),mode,score:s,automaticAdverseDecisionAllowed:!highImpact,requiresHumanReview:highImpact&&mode!=='allow',protections:{protectedCharacteristicsExcluded:true,regulatedCreditUse:false,appealRequired:mode!=='allow'}};}
function validateFeatures(features={}){const keys=Object.keys(features).map(x=>x.toLowerCase());const bad=keys.filter(k=>PROHIBITED.some(p=>k.includes(p)));return {allowed:bad.length===0,rejectedFeatures:bad};}
function passport({subjectId,trustCredential,signals=[]}={}){const s=score(signals);return {subjectId:clean(subjectId,160),credentialLevel:trustCredential?.level||'none',verifiedClaims:trustCredential?.claims||[],trustScore:s.trustScore,riskBand:s.riskBand,updatedAt:new Date().toISOString(),publicView:{credentialLevel:trustCredential?.level||'none',verifiedClaims:trustCredential?.claims||[],performanceBand:s.riskBand==='low'?'strong':s.riskBand==='guarded'?'established':'review'},privateRiskDetailsRestricted:true};}
module.exports={SIGNALS,PROHIBITED,signal,score,decision,validateFeatures,passport};
