'use strict';
const crypto=require('crypto');
const clean=(v,m=500)=>String(v??'').replace(/\s+/g,' ').trim().slice(0,m);
const id=p=>`${p}_${crypto.randomBytes(8).toString('hex')}`;
const CHECKS=new Set(['identity','business','beneficial-owner','sanctions','watchlist','document','bank-account','address','driver','contractor','supplier','factory','warehouse','professional-license','age','tax']);
function request(input={}){if(!clean(input.subjectId,160))throw new Error('subject_required');const checks=(input.checks||[]).filter(x=>CHECKS.has(x));if(!checks.length)throw new Error('checks_required');return {id:id('verify'),subjectId:clean(input.subjectId,160),subjectType:clean(input.subjectType,80)||'person',checks:[...new Set(checks)],provider:clean(input.provider,120)||'unassigned',jurisdictions:Array.isArray(input.jurisdictions)?input.jurisdictions.map(x=>clean(x,80)).filter(Boolean):[],purpose:clean(input.purpose,300),consentRequired:input.consentRequired!==false,consentRecorded:input.consentRecorded===true,status:'pending',rawSensitiveDataStored:false,createdAt:new Date().toISOString()};}
function result(input={}){return {requestId:clean(input.requestId,160),subjectId:clean(input.subjectId,160),provider:clean(input.provider,120),status:['verified','failed','review','expired'].includes(input.status)?input.status:'review',checks:Array.isArray(input.checks)?input.checks.map(c=>({type:clean(c.type,80),status:clean(c.status,40),reasonCode:clean(c.reasonCode,120)||null,verifiedAt:clean(c.verifiedAt,40)||null,expiresAt:clean(c.expiresAt,40)||null})):[],providerReference:clean(input.providerReference,200)||null,evidenceToken:clean(input.evidenceToken,500)||null,rawDocument:null,rawSsn:null,rawBankCredentials:null};}
function trustCredential(input={}){if(!clean(input.subjectId,160))throw new Error('subject_required');return {id:id('trust'),subjectId:clean(input.subjectId,160),subjectType:clean(input.subjectType,80)||'business',level:['basic','verified','enhanced'].includes(input.level)?input.level:'basic',claims:Array.isArray(input.claims)?input.claims.map(x=>clean(x,120)).filter(Boolean):[],issuer:clean(input.issuer,160)||'TRYAMM Trust Network',issuedAt:new Date().toISOString(),expiresAt:clean(input.expiresAt,40)||null,revocable:true,status:'active',portableToken:clean(input.portableToken,1000)||null};}
function capabilityDecision({credential,requiredClaims=[]}={}){if(!credential||credential.status!=='active')return {allowed:false,reason:'trust_credential_inactive'};const missing=requiredClaims.filter(x=>!credential.claims.includes(x));return {allowed:missing.length===0,reason:missing.length?'missing_verified_claims':'verified',missing};}
function privacyReceipt(input={}){return {id:id('privacy'),subjectId:clean(input.subjectId,160),purpose:clean(input.purpose,300),dataCategories:Array.isArray(input.dataCategories)?input.dataCategories.map(x=>clean(x,100)).filter(Boolean):[],provider:clean(input.provider,120),retentionPolicy:clean(input.retentionPolicy,300),consentBasis:clean(input.consentBasis,120),createdAt:new Date().toISOString(),rule:'Store provider tokens/statuses where possible; do not propagate raw SSNs, bank credentials or identity documents across TRYAMM services.'};}
module.exports={CHECKS,request,result,trustCredential,capabilityDecision,privacyReceipt};
