'use strict';
const crypto=require('crypto');
const clean=(v,m=500)=>String(v??'').replace(/\s+/g,' ').trim().slice(0,m);
const clamp=(n,a,b)=>Math.max(a,Math.min(b,Number(n)||0));
const id=p=>`${p}_${crypto.randomBytes(8).toString('hex')}`;
const CAPABILITIES=new Set(['storage','pick-pack','b2c','b2b','returns','cross-dock','cold','oversize','kitting','labeling','international']);
function normalizeWarehouse(input={}){return {id:input.id||id('wh'),provider:clean(input.provider||'direct',80),externalId:clean(input.externalId,120)||null,name:clean(input.name,140),country:clean(input.country||'US',2).toUpperCase(),region:clean(input.region,80),city:clean(input.city,100),postalCode:clean(input.postalCode,20),capabilities:(Array.isArray(input.capabilities)?input.capabilities:[]).map(x=>clean(x,30)).filter(x=>CAPABILITIES.has(x)),verified:input.verified===true,active:input.active!==false,pricing:{storagePerUnitMonth:clamp(input.storagePerUnitMonth,0,1e6),pickPackPerOrder:clamp(input.pickPackPerOrder,0,1e6),receivingPerUnit:clamp(input.receivingPerUnit,0,1e6)},sla:{shipHours:clamp(input.shipHours||24,1,240),accuracyPct:clamp(input.accuracyPct||99,0,100)}}}
function quoteWarehouse({warehouse,units=1,months=1,orders=0,receivingUnits=0,platformFeeBps=500}={}){const w=normalizeWarehouse(warehouse);const storage=w.pricing.storagePerUnitMonth*clamp(units,0,1e9)*clamp(months,0,120);const fulfillment=w.pricing.pickPackPerOrder*clamp(orders,0,1e9);const receiving=w.pricing.receivingPerUnit*clamp(receivingUnits,0,1e9);const providerSubtotal=Math.round((storage+fulfillment+receiving)*100)/100;const feeBps=clamp(platformFeeBps,0,2500);const platformFee=Math.round(providerSubtotal*feeBps)/10000;return {warehouseId:w.id,providerSubtotal:Number(providerSubtotal.toFixed(2)),platformFee:Number(platformFee.toFixed(2)),total:Number((providerSubtotal+platformFee).toFixed(2)),platformFeeBps:feeBps,feeDisclosure:`TRYAMM orchestration fee ${(feeBps/100).toFixed(2)}%`,currency:'USD'}}
function rankWarehouses(rows=[],requirements={}){const required=new Set(requirements.capabilities||[]);return rows.map(normalizeWarehouse).filter(w=>w.active&&w.verified&&[...required].every(c=>w.capabilities.includes(c))).map(w=>{let score=100;score-=Math.min(40,w.pricing.pickPackPerOrder*2);score-=Math.min(25,w.pricing.storagePerUnitMonth/10);score+=Math.min(20,(w.sla.accuracyPct-95)*4);score-=Math.min(15,w.sla.shipHours/8);if(requirements.country&&w.country===requirements.country)score+=10;return {...w,score:Number(score.toFixed(2))}}).sort((a,b)=>b.score-a.score)}
function createWarehouseBooking({merchantId,warehouseId,quote,termsAccepted=false}={}){if(!merchantId||!warehouseId)throw new Error('merchant_and_warehouse_required');if(!termsAccepted)throw new Error('warehouse_terms_required');return {id:id('whb'),merchantId,warehouseId,quote,status:'pending_provider_confirmation',termsAccepted:true,createdAt:new Date().toISOString()}}
module.exports={CAPABILITIES,normalizeWarehouse,quoteWarehouse,rankWarehouses,createWarehouseBooking};
