'use strict';
const crypto=require('crypto');
const db=require('./supabase-rest');
const step=require('./step-up-security');
const vault=require('./security-vault');
const clean=(v,m=500)=>String(v??'').trim().slice(0,m);
const CHALLENGE_TTL_MS=5*60*1000;
const RP_NAME=process.env.WEBAUTHN_RP_NAME||'TRYAMM';
function relyingParty(){const configuredOrigin=clean(process.env.WEBAUTHN_ORIGIN,1000);const appUrl=clean(process.env.APP_URL,1000);const origin=(configuredOrigin||appUrl).replace(/\/$/,'');if(!origin)throw Object.assign(new Error('webauthn_origin_missing'),{code:'WEBAUTHN_ORIGIN_MISSING'});const u=new URL(origin);const rpID=clean(process.env.WEBAUTHN_RP_ID,255)||u.hostname;return {origin,rpID};}
function encodeBytes(v){return Buffer.from(v).toString('base64url');}
function decodeBytes(v){return new Uint8Array(Buffer.from(String(v||''),'base64url'));}
async function simple(){return import('@simplewebauthn/server');}
async function passkeys(userId){return (await db.select('security_passkeys',`user_id=eq.${encodeURIComponent(userId)}&revoked_at=is.null&order=created_at.asc`))||[];}
async function saveChallenge({userId,sessionId,purpose,challenge}){await db.insert('security_webauthn_challenges',[{user_id:userId,session_id:sessionId,purpose,challenge,expires_at:new Date(Date.now()+CHALLENGE_TTL_MS).toISOString()}]);}
async function consumeChallenge({userId,sessionId,purpose}){const rows=await db.select('security_webauthn_challenges',`user_id=eq.${encodeURIComponent(userId)}&session_id=eq.${encodeURIComponent(sessionId)}&purpose=eq.${encodeURIComponent(purpose)}&used_at=is.null&expires_at=gt.${encodeURIComponent(new Date().toISOString())}&order=created_at.desc&limit=1`);const row=rows?.[0];if(!row)return null;await db.update('security_webauthn_challenges',`id=eq.${encodeURIComponent(row.id)}&used_at=is.null`,{used_at:new Date().toISOString()});return row;}
module.exports=function registerWebAuthn({app,auth}){
 function requireReady(res){if(!db.configured())return res.status(503).json({error:'Passkey database unavailable',code:'WEBAUTHN_DB_REQUIRED'});try{return relyingParty()}catch(e){res.status(503).json({error:'Passkey relying-party configuration incomplete',code:e.code||'WEBAUTHN_CONFIG_REQUIRED'});return null;}}
 app.get('/api/security/passkeys',auth,async(req,res)=>{const rp=requireReady(res);if(!rp)return;const rows=await passkeys(req.user.id);res.json({passkeys:rows.map(x=>({id:x.credential_id,label:x.label,transports:x.transports||[],deviceType:x.device_type,backedUp:!!x.backed_up,createdAt:x.created_at,lastUsedAt:x.last_used_at})),rpID:rp.rpID});});
 app.post('/api/security/passkeys/register/options',auth,async(req,res)=>{const rp=requireReady(res);if(!rp)return;const sw=await simple(),existing=await passkeys(req.user.id);const userID=crypto.createHash('sha256').update(req.user.id).digest().subarray(0,32);const options=await sw.generateRegistrationOptions({rpName:RP_NAME,rpID:rp.rpID,userName:req.user.email,userDisplayName:req.user.displayName||req.user.email,userID,attestationType:'none',excludeCredentials:existing.map(p=>({id:p.credential_id,transports:p.transports||[]})),authenticatorSelection:{residentKey:'preferred',userVerification:'required'},supportedAlgorithmIDs:[-7,-257]});await saveChallenge({userId:req.user.id,sessionId:req.session.id,purpose:'registration',challenge:options.challenge});res.json(options);});
 app.post('/api/security/passkeys/register/verify',auth,async(req,res)=>{const rp=requireReady(res);if(!rp)return;const challenge=await consumeChallenge({userId:req.user.id,sessionId:req.session.id,purpose:'registration'});if(!challenge)return res.status(400).json({verified:false,error:'Passkey challenge expired or already used'});const sw=await simple();let verification;try{verification=await sw.verifyRegistrationResponse({response:req.body.response||req.body,expectedChallenge:challenge.challenge,expectedOrigin:rp.origin,expectedRPID:rp.rpID,requireUserVerification:true});}catch(e){return res.status(400).json({verified:false,error:'Passkey registration verification failed'});}if(!verification.verified||!verification.registrationInfo)return res.status(400).json({verified:false});const info=verification.registrationInfo,c=info.credential;await db.insert('security_passkeys',[{credential_id:c.id,user_id:req.user.id,webauthn_user_id:encodeBytes(crypto.createHash('sha256').update(req.user.id).digest().subarray(0,32)),public_key_b64:encodeBytes(c.publicKey),counter:c.counter||0,transports:c.transports||[],device_type:info.credentialDeviceType||null,backed_up:!!info.credentialBackedUp,label:clean(req.body.label,120)||'Passkey'}]);const profile=await vault.getMfa(req.user.id).catch(()=>null);if(vault.configured()){const secret=profile?.totp_secret_ciphertext?await vault.getTotpSecret(req.user.id):null;await vault.saveMfa({userId:req.user.id,enabled:true,methods:[...new Set([...(profile?.methods||[]),'passkey'])],totpSecret:secret||undefined,recoveryCodeHashes:profile?.recovery_code_hashes||[]});await vault.audit({userId:req.user.id,actorId:req.user.id,sessionId:req.session.id,eventType:'passkey.registered',severity:'info',requestId:req.id,metadata:{credentialId:c.id}}).catch(()=>{});}res.json({verified:true,credentialId:c.id});});
 app.post('/api/security/passkeys/auth/options',auth,async(req,res)=>{const rp=requireReady(res);if(!rp)return;const existing=await passkeys(req.user.id);if(!existing.length)return res.status(409).json({error:'No active passkeys enrolled'});const action=clean(req.body.action,120);if(!action)return res.status(400).json({error:'action required'});const sw=await simple();const options=await sw.generateAuthenticationOptions({rpID:rp.rpID,allowCredentials:existing.map(p=>({id:p.credential_id,transports:p.transports||[]})),userVerification:'required'});await saveChallenge({userId:req.user.id,sessionId:req.session.id,purpose:'step-up',challenge:`${action}:${options.challenge}`});res.json({...options,action});});
 app.post('/api/security/passkeys/auth/verify',auth,async(req,res)=>{const rp=requireReady(res);if(!rp)return;const action=clean(req.body.action,120),response=req.body.response;if(!action||!response?.id)return res.status(400).json({verified:false,error:'action and response required'});const challengeRow=await consumeChallenge({userId:req.user.id,sessionId:req.session.id,purpose:'step-up'});if(!challengeRow)return res.status(400).json({verified:false,error:'Passkey challenge expired or already used'});const prefix=`${action}:`;if(!challengeRow.challenge.startsWith(prefix))return res.status(400).json({verified:false,error:'Passkey challenge scope mismatch'});const expectedChallenge=challengeRow.challenge.slice(prefix.length),rows=await db.select('security_passkeys',`credential_id=eq.${encodeURIComponent(response.id)}&user_id=eq.${encodeURIComponent(req.user.id)}&revoked_at=is.null&limit=1`),pk=rows?.[0];if(!pk)return res.status(404).json({verified:false,error:'Passkey not found'});const sw=await simple();let verification;try{verification=await sw.verifyAuthenticationResponse({response,expectedChallenge,expectedOrigin:rp.origin,expectedRPID:rp.rpID,requireUserVerification:true,credential:{id:pk.credential_id,publicKey:decodeBytes(pk.public_key_b64),counter:Number(pk.counter)||0,transports:pk.transports||[]}});}catch(e){return res.status(401).json({verified:false,error:'Passkey authentication verification failed'});}if(!verification.verified)return res.status(401).json({verified:false});await db.update('security_passkeys',`credential_id=eq.${encodeURIComponent(pk.credential_id)}`,{counter:verification.authenticationInfo.newCounter,last_used_at:new Date().toISOString()});const issued=step.issue({userId:req.user.id,sessionId:req.session.id,action,method:'passkey'});if(vault.configured())await vault.saveStepUp(issued.record);else return res.status(503).json({verified:false,error:'Security vault required for passkey step-up'});await vault.audit({userId:req.user.id,actorId:req.user.id,sessionId:req.session.id,eventType:'passkey.step_up',severity:'info',requestId:req.id,metadata:{action,credentialId:pk.credential_id}}).catch(()=>{});res.json({verified:true,action,stepUpToken:issued.token,expiresAt:issued.record.expiresAt});});
 app.delete('/api/security/passkeys/:credentialId',auth,async(req,res)=>{const rp=requireReady(res);if(!rp)return;const id=clean(req.params.credentialId,1000);const rows=await db.select('security_passkeys',`credential_id=eq.${encodeURIComponent(id)}&user_id=eq.${encodeURIComponent(req.user.id)}&revoked_at=is.null&limit=1`);if(!rows?.[0])return res.status(404).json({error:'Passkey not found'});await db.update('security_passkeys',`credential_id=eq.${encodeURIComponent(id)}`,{revoked_at:new Date().toISOString()});await vault.audit({userId:req.user.id,actorId:req.user.id,sessionId:req.session.id,eventType:'passkey.revoked',severity:'warning',requestId:req.id,metadata:{credentialId:id}}).catch(()=>{});res.json({ok:true,revoked:true});});
};
