export type FieldServiceLane={id:string;label:string;qualification:string[];aviationGate:boolean;deliverables:string[]}
export const FIELD_SERVICE_LANES:FieldServiceLane[]=[
 {id:'real-estate-imaging',label:'Real Estate Imaging',qualification:['property-media training','privacy/property-access rules','equipment competency'],aviationGate:false,deliverables:['photo set','360/3D tour','floor-plan inputs','property media package']},
 {id:'construction-inspection',label:'Construction Inspection Imaging',qualification:['site-safety training','scope/checklist training','client authorization'],aviationGate:false,deliverables:['progress imagery','defect evidence package','before/after record','inspection report inputs']},
 {id:'agriculture',label:'Agriculture Imaging & Monitoring',qualification:['farm access authorization','crop/field workflow training','equipment competency'],aviationGate:false,deliverables:['field imagery','crop-condition observations','mapping inputs','season comparison']},
 {id:'environment',label:'Environmental Monitoring',qualification:['site/access training','evidence-chain training','client/regulatory scope'],aviationGate:false,deliverables:['geotagged observations','time-series imagery','incident evidence','monitoring report inputs']},
 {id:'media',label:'Media / Movie Production',qualification:['production safety','rights/releases','camera workflow'],aviationGate:false,deliverables:['cinematic footage','location scans','B-roll','Movie Box source package']},
 {id:'holoarena-events',label:'HoloArena Event Capture',qualification:['venue operator training','crowd/privacy rules','equipment safety'],aviationGate:false,deliverables:['event highlights','spectator capture','replay package','sponsor media package']},
 {id:'disaster-assessment',label:'Disaster Assessment Imaging',qualification:['incident-command awareness','do-not-enter rules','evidence handling','safety PPE training'],aviationGate:false,deliverables:['damage imagery','priority-area observations','time-stamped evidence','assessment package']},
 {id:'delivery-aviation',label:'Approved Delivery Operations',qualification:['operator qualification','aircraft/platform training','route/weather training','applicable aviation approvals'],aviationGate:true,deliverables:['verified pickup','route telemetry','proof of delivery','exception report']},
]
export const FIELD_SERVICE_FUNNEL=['SEARCH/DISCOVERY','LANDING PAGE','AI HELP','TRAIN/QUALIFY','REGISTER/VERIFY','GET JOB OR START BUSINESS','PROVIDE SERVICE','MARKETPLACE','PAYMENT/LEDGER','REPUTATION','WORLD MEMORY','EXPAND INTO GAME/HOLOVERSE/OMNIVERSE/QUANTUMVERSE'] as const
export const PROVIDER_PROFILE={roles:['worker','independent-provider','business-owner','agency','franchise-partner'],checks:['identity when required','business verification when applicable','training/credential state','insurance where required','equipment capability','service territory','background/site requirements when applicable'],truth:'Verification unlocks only services the provider is actually qualified and authorized to perform.'} as const
export const JOB_RUNTIME=['LEAD/JOB CREATED','SCOPE','CLIENT AUTHORIZATION','PROVIDER MATCH','QUALIFICATION CHECK','SCHEDULE','CHECK IN','SAFETY GATE','CAPTURE/SERVICE','EVIDENCE UPLOAD','QUALITY REVIEW','CLIENT ACCEPTANCE','INVOICE','PAYMENT','PAYOUT','REPUTATION','WORLD MEMORY'] as const
export const AVIATION_TRUTH='Delivery or aerial operations remain disabled until the applicable operator, aircraft, airspace, insurance, local/site and aviation requirements are satisfied. The app must never imply that software approval equals aviation approval.'
export const QUANTUM_FIELD_AI={name:'Quantum Field Assistant',functions:['convert customer need into service scope','recommend qualified lane','flag missing permissions/credentials','generate checklists','quality-control submitted evidence','route jobs by distance/skills/availability','surface safety stop conditions','prepare invoice/evidence package','suggest next training/business step'],rule:'AI can assist decisions but cannot fabricate inspection findings, qualifications, regulatory approval, client acceptance or completed work.'} as const
