import { createClient } from '@supabase/supabase-js'

const cors=(res:any)=>{res.setHeader('Access-Control-Allow-Origin','*');res.setHeader('Access-Control-Allow-Headers','authorization,content-type');res.setHeader('Access-Control-Allow-Methods','POST,GET,OPTIONS')}
const clean=(v:unknown,max=256)=>String(v??'').trim().slice(0,max)
function clients(req:any){
 const url=process.env.SUPABASE_URL||process.env.VITE_SUPABASE_URL, anon=process.env.SUPABASE_ANON_KEY||process.env.VITE_SUPABASE_ANON_KEY, service=process.env.SUPABASE_SERVICE_ROLE_KEY
 if(!url||!anon||!service)return null
 const token=String(req.headers.authorization||'').replace(/^Bearer\s+/i,'')
 const user=createClient(url,anon,{global:{headers:{Authorization:`Bearer ${token}`}}})
 const admin=createClient(url,service,{auth:{persistSession:false}})
 return {user,admin}
}
async function requireTrusted(req:any,res:any){const c=clients(req);if(!c){res.status(503).json({error:'Payout provider/database server configuration missing'});return null}const {data,error}=await c.user.auth.getUser();if(error||!data.user){res.status(401).json({error:'Authenticated session required'});return null}const trusted=(process.env.TRYAMM_PAYOUT_REVIEWER_USER_IDS||'').split(',').map(x=>x.trim()).filter(Boolean);if(!trusted.includes(data.user.id)){res.status(403).json({error:'Trusted payout reviewer required'});return null}return {...c,actor:data.user}}
export default async function handler(req:any,res:any){cors(res);if(req.method==='OPTIONS')return res.status(204).end();const action=clean(req.query?.action,48)
 if(action==='health'&&req.method==='GET')return res.status(200).json({ok:true,providerConfigured:Boolean(process.env.TRYAMM_PAYOUT_PROVIDER),reviewersConfigured:Boolean(process.env.TRYAMM_PAYOUT_REVIEWER_USER_IDS)})
 const ctx=await requireTrusted(req,res);if(!ctx)return;const {admin,actor}=ctx
 if(action==='approve-game-prize'&&req.method==='POST'){const id=clean(req.body?.payoutId,128);if(!id)return res.status(400).json({error:'payoutId required'});const {data,error}=await admin.from('game_prize_payouts').update({state:'approved',updated_at:new Date().toISOString(),gate_evidence:{...(req.body?.gateEvidence||{}),approvedBy:actor.id,approvedAt:new Date().toISOString()}}).eq('id',id).eq('state','pending').select().maybeSingle();if(error)return res.status(500).json({error:error.message});if(!data)return res.status(409).json({error:'Payout not pending or not found'});return res.status(200).json({ok:true,payout:data})}
 if(action==='approve-service-share'&&req.method==='POST'){const id=clean(req.body?.allocationId,128);if(!id)return res.status(400).json({error:'allocationId required'});const {data,error}=await admin.from('service_share_allocations').update({state:'approved',updated_at:new Date().toISOString(),gate_evidence:{...(req.body?.gateEvidence||{}),approvedBy:actor.id,approvedAt:new Date().toISOString()}}).eq('id',id).eq('state','pending').select().maybeSingle();if(error)return res.status(500).json({error:error.message});if(!data)return res.status(409).json({error:'Allocation not pending or not found'});return res.status(200).json({ok:true,allocation:data})}
 if(action==='mark-submitted'&&req.method==='POST'){const kind=clean(req.body?.kind,24),id=clean(req.body?.id,128),providerRef=clean(req.body?.providerRef,256);if(!['game-prize','service-share'].includes(kind)||!id||!providerRef)return res.status(400).json({error:'kind,id,providerRef required'});const table=kind==='game-prize'?'game_prize_payouts':'service_share_allocations';const {data,error}=await admin.from(table).update({state:'submitted',provider_ref:providerRef,updated_at:new Date().toISOString()}).eq('id',id).eq('state','approved').select().maybeSingle();if(error)return res.status(500).json({error:error.message});if(!data)return res.status(409).json({error:'Record not approved or not found'});return res.status(200).json({ok:true,record:data})}
 if(action==='settle'&&req.method==='POST'){const kind=clean(req.body?.kind,24),id=clean(req.body?.id,128),finalState=clean(req.body?.state,16);if(!['game-prize','service-share'].includes(kind)||!['paid','failed','reversed'].includes(finalState)||!id)return res.status(400).json({error:'kind,id,state required'});const table=kind==='game-prize'?'game_prize_payouts':'service_share_allocations';const {data,error}=await admin.from(table).update({state:finalState,updated_at:new Date().toISOString()}).eq('id',id).in('state',['submitted','paid']).select().maybeSingle();if(error)return res.status(500).json({error:error.message});if(!data)return res.status(409).json({error:'Record not in settlement state'});return res.status(200).json({ok:true,record:data})}
 return res.status(404).json({error:'Unknown payout action'})
}
