export type CreatorAssetKind='SKIN'|'OUTFIT'|'SHOES'|'JEWELRY'|'VEHICLE_DESIGN'|'VEHICLE_PART'|'FURNITURE'|'PROPERTY_CUSTOMIZATION'|'COLLECTIBLE'|'CREATOR_GEAR'
export type FulfillmentKind='VIRTUAL_ONLY'|'PHYSICAL_ONLY'|'DIGITAL_TWIN'
export type ListingState='DRAFT'|'REVIEW'|'PUBLISHED'|'SUSPENDED'|'SOLD_OUT'
export interface CreatorAsset {id:string;creatorId:string;businessId?:string;name:string;kind:CreatorAssetKind;fulfillment:FulfillmentKind;rightsEvidenceRefs:string[];digitalPassportId:string;limitedDrop?:{editionSize:number;editionNumber?:number};rarity?:'COMMON'|'RARE'|'EPIC'|'LEGENDARY';compatibleSurfaces:string[]}
export interface CreatorListing {id:string;assetId:string;sellerId:string;state:ListingState;priceMinor:number;currency:string;quantity:number;marketplaces:('STREETVERSE_CREATOR_MARKET'|'ALL_AMERICAN_MARKETPLACE'|'LIVE_COMMERCE'|'REELS_COMMERCE')[];serverVerified:boolean}
export interface RevenueParticipant {kind:'CREATOR'|'BUSINESS'|'AGENT'|'TRYAMM';id:string;shareBps:number}
export interface RevenuePlan {listingId:string;participants:RevenueParticipant[];serverVerified:boolean;settlementProviderRequired:boolean}
export const CREATOR_MARKETPLACE_FLOW=['CREATE','PREVIEW','RIGHTS_CHECK','DIGITAL_PASSPORT','PUBLISH','MARKETPLACE','SERVER_VERIFIED_PURCHASE','INVENTORY_TRANSFER','LEDGER_SPLIT','PAYABLE_BALANCE'] as const
export const CREATOR_MARKETPLACE_SURFACES=['BENNY_CONSTRUCT','HOLOSTYLE','AI_TWIN_PREVIEW','STREETVERSE_CREATOR_MARKET','ALL_AMERICAN_MARKETPLACE','LIVE_PRODUCT_TAG','REEL_PRODUCT_TAG','PLAYER_VAULT','BUSINESS_INVENTORY','VIRTUAL_WAREHOUSE','CREATOR_LEDGER'] as const
export const CREATOR_MARKETPLACE_POLICY=Object.freeze({creatorOwnsAuthoredAssetByDefault:true,rightsEvidenceRequiredBeforePublish:true,clientMayPublishWithoutServerReview:false,clientMayMintAuthoritativeInventory:false,clientMaySettlePurchase:false,clientMayCreatePayableBalance:false,serverAuthoritativeOwnership:true,serverAuthoritativeListing:true,serverAuthoritativeRevenueSplit:true,settlementProviderRequired:true,physicalAndVirtualFulfillmentDistinct:true,digitalTwinSupported:true,limitedDropsSupported:true,giftingSupported:true,tradeInSupported:true,creatorProvenancePersists:true,percentageSplitsMustBeConfiguredNotInvented:true,realWorldWeaponCommerceAllowed:false})
export function validateRevenuePlan(plan:RevenuePlan){const total=plan.participants.reduce((n,p)=>n+p.shareBps,0);return plan.serverVerified&&plan.settlementProviderRequired&&plan.participants.length>0&&total===10000&&plan.participants.every(p=>p.shareBps>0)}
export function canPublishCreatorListing(asset:CreatorAsset,listing:CreatorListing){return listing.assetId===asset.id&&asset.rightsEvidenceRefs.length>0&&Boolean(asset.digitalPassportId)&&listing.serverVerified&&listing.state==='PUBLISHED'&&listing.priceMinor>=0&&listing.quantity>0}
