const express=require('express')

function createArchiveHistoryRouter({supabase}){
 const router=express.Router()
 async function requireUser(req,res,next){const a=req.headers.authorization||'';const t=a.startsWith('Bearer ')?a.slice(7):'';if(!t)return res.status(401).json({error:'Authentication required'});const {data,error}=await supabase.auth.getUser(t);if(error||!data?.user)return res.status(401).json({error:'Invalid session'});req.user=data.user;next()}
 const validUrl=(value)=>{try{const u=new URL(value);return ['http:','https:'].includes(u.protocol)}catch{return false}}
 router.get('/availability',requireUser,async(req,res)=>{try{const url=String(req.query.url||'');const timestamp=req.query.timestamp?String(req.query.timestamp):'';if(!validUrl(url))return res.status(400).json({error:'Valid http(s) url required'});const q=new URLSearchParams({url});if(timestamp)q.set('timestamp',timestamp);const r=await fetch(`https://archive.org/wayback/available?${q}`,{headers:{'User-Agent':'TRYAMM-HoloGPT/1.0'}});const data=await r.json();if(!r.ok)throw new Error(`Wayback availability failed (${r.status})`);const snap=data?.archived_snapshots?.closest||null;let evidence=null;if(snap){const {data:row}=await supabase.from('archive_evidence').insert({user_id:req.user.id,url,lookup_type:'wayback_availability',requested_timestamp:timestamp||null,archive_timestamp:snap.timestamp||null,archive_url:snap.url||null,status_code:String(snap.status||''),provenance:{provider:'Internet Archive Wayback Machine',api:'Availability JSON API'}}).select('*').single();evidence=row||null}res.json({url,snapshot:snap,evidence,source:'Internet Archive Wayback Machine'})}catch(e){res.status(502).json({error:e.message})}})
 router.get('/captures',requireUser,async(req,res)=>{try{const url=String(req.query.url||'');if(!validUrl(url))return res.status(400).json({error:'Valid http(s) url required'});const limit=Math.min(Math.max(Number(req.query.limit||25),1),100);const q=new URLSearchParams({url,output:'json',fl:'timestamp,original,statuscode,mimetype,digest',filter:'statuscode:200',limit:String(limit)});if(req.query.from)q.set('from',String(req.query.from));if(req.query.to)q.set('to',String(req.query.to));const r=await fetch(`https://web.archive.org/cdx/search/cdx?${q}`,{headers:{'User-Agent':'TRYAMM-HoloGPT/1.0'}});const json=await r.json();if(!r.ok)throw new Error(`Wayback CDX failed (${r.status})`);const [header,...rows]=Array.isArray(json)?json:[];const captures=rows.map(row=>Object.fromEntries(header.map((h,i)=>[h,row[i]]))).map(x=>({...x,archive_url:`https://web.archive.org/web/${x.timestamp}/${x.original}`}));res.json({url,captures,source:'Internet Archive Wayback CDX API'})}catch(e){res.status(502).json({error:e.message})}})
 router.post('/compare',requireUser,async(req,res)=>{try{const url=String(req.body?.url||'');const left=String(req.body?.leftTimestamp||'');const right=String(req.body?.rightTimestamp||'');if(!validUrl(url)||!/^\d{4,14}$/.test(left)||!/^\d{4,14}$/.test(right))return res.status(400).json({error:'url and two Wayback timestamps are required'});const archiveUrl=t=>`https://web.archive.org/web/${t}id_/${url}`;const fetchText=async t=>{const r=await fetch(archiveUrl(t),{headers:{'User-Agent':'TRYAMM-HoloGPT/1.0'}});if(!r.ok)throw new Error(`Archived snapshot ${t} failed (${r.status})`);return (await r.text()).slice(0,500000)};const [a,b]=await Promise.all([fetchText(left),fetchText(right)]);const normalize=s=>s.replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim();const at=normalize(a),bt=normalize(b);const comparison={leftLength:at.length,rightLength:bt.length,changed:at!==bt,leftPreview:at.slice(0,4000),rightPreview:bt.slice(0,4000),note:'HoloGPT should summarize differences from these archived snapshots and label them as historical evidence.'};const {data:row}=await supabase.from('archive_comparisons').insert({user_id:req.user.id,url,left_timestamp:left,right_timestamp:right,left_archive_url:archiveUrl(left),right_archive_url:archiveUrl(right),comparison}).select('*').single();res.json({comparison,evidence:row,source:'Internet Archive Wayback Machine'})}catch(e){res.status(502).json({error:e.message})}})
 router.get('/item/:identifier',requireUser,async(req,res)=>{try{const id=encodeURIComponent(req.params.identifier);const r=await fetch(`https://archive.org/metadata/${id}`,{headers:{'User-Agent':'TRYAMM-HoloGPT/1.0'}});const data=await r.json();if(!r.ok)throw new Error(`Internet Archive metadata failed (${r.status})`);res.json({identifier:req.params.identifier,metadata:data?.metadata||{},files:(data?.files||[]).slice(0,250),source:'Internet Archive Metadata API'})}catch(e){res.status(502).json({error:e.message})}})
 router.get('/hologpt-context',requireUser,async(req,res)=>{try{const url=String(req.query.url||'');if(!validUrl(url))return res.status(400).json({error:'Valid url required'});const q=new URLSearchParams({url});const r=await fetch(`https://archive.org/wayback/available?${q}`,{headers:{'User-Agent':'TRYAMM-HoloGPT/1.0'}});const data=await r.json();const snap=data?.archived_snapshots?.closest||null;res.json({tool:'archive_history',currentUrl:url,archivedSnapshot:snap,usageRules:['Treat archived pages as historical evidence, not necessarily current truth.','Preserve archive timestamp and original URL in provenance.','Compare against current trustworthy sources when answering current questions.','Do not claim a page existed at a date unless the returned snapshot supports it.']})}catch(e){res.status(502).json({error:e.message})}})
 return router
}
module.exports={createArchiveHistoryRouter}
