const express=require('express')

function createDispatchRouter({supabase}){
 const router=express.Router()
 async function requireUser(req,res,next){const a=req.headers.authorization||'';const t=a.startsWith('Bearer ')?a.slice(7):'';if(!t)return res.status(401).json({error:'Authentication required'});const {data,error}=await supabase.auth.getUser(t);if(error||!data?.user)return res.status(401).json({error:'Invalid session'});req.user=data.user;next()}
 async function companyOwned(userId,id){const {data}=await supabase.from('dispatch_companies').select('id').eq('id',id).eq('owner_user_id',userId).maybeSingle();return data}
 router.get('/status',requireUser,async(req,res)=>{const {data,error}=await supabase.from('dispatch_companies').select('*').eq('owner_user_id',req.user.id).order('created_at',{ascending:false});if(error)return res.status(500).json({error:error.message});res.json({service:'OmniDispatch OS',companies:data||[],capabilities:['freight','box_truck','cargo_van','hotshot','courier','moving','vehicle_delivery','local_delivery','future_autonomous']})})
 router.post('/companies',requireUser,async(req,res)=>{try{const name=String(req.body?.name||'').trim();if(!name)return res.status(400).json({error:'name required'});const {data,error}=await supabase.from('dispatch_companies').insert({owner_user_id:req.user.id,name,authority_type:req.body?.authorityType||null,authority_number:req.body?.authorityNumber||null}).select('*').single();if(error)throw error;res.status(201).json({company:data})}catch(e){res.status(500).json({error:e.message})}})
 router.post('/drivers',requireUser,async(req,res)=>{try{if(!await companyOwned(req.user.id,req.body?.companyId))return res.status(403).json({error:'Company access denied'});const {data,error}=await supabase.from('dispatch_drivers').insert({company_id:req.body.companyId,user_id:req.body.userId||null,display_name:String(req.body?.displayName||'').trim(),phone:req.body?.phone||null,license_state:req.body?.licenseState||null,license_class:req.body?.licenseClass||null,skills:req.body?.skills||[],languages:req.body?.languages||[]}).select('*').single();if(error)throw error;res.status(201).json({driver:data})}catch(e){res.status(500).json({error:e.message})}})
 router.post('/vehicles',requireUser,async(req,res)=>{try{if(!await companyOwned(req.user.id,req.body?.companyId))return res.status(403).json({error:'Company access denied'});const {data,error}=await supabase.from('dispatch_vehicles').insert({company_id:req.body.companyId,owner_user_id:req.user.id,vehicle_type:req.body.vehicleType,vin_hash:req.body.vinHash||null,plate_state:req.body.plateState||null,plate_last4:req.body.plateLast4||null,make:req.body.make||null,model:req.body.model||null,model_year:req.body.modelYear||null,capacity:req.body.capacity||{}}).select('*').single();if(error)throw error;res.status(201).json({vehicle:data})}catch(e){res.status(500).json({error:e.message})}})
 router.post('/customers',requireUser,async(req,res)=>{try{if(!await companyOwned(req.user.id,req.body?.companyId))return res.status(403).json({error:'Company access denied'});const {data,error}=await supabase.from('dispatch_customers').insert({company_id:req.body.companyId,name:req.body.name,customer_type:req.body.customerType||'shipper',contact:req.body.contact||{},billing_terms:req.body.billingTerms||null}).select('*').single();if(error)throw error;res.status(201).json({customer:data})}catch(e){res.status(500).json({error:e.message})}})
 router.get('/jobs',requireUser,async(req,res)=>{try{let q=supabase.from('dispatch_jobs').select('*').order('created_at',{ascending:false}).limit(100);if(req.query.companyId){if(!await companyOwned(req.user.id,req.query.companyId))return res.status(403).json({error:'Company access denied'});q=q.eq('company_id',req.query.companyId)}else{const {data:cs}=await supabase.from('dispatch_companies').select('id').eq('owner_user_id',req.user.id);q=q.in('company_id',(cs||[]).map(x=>x.id))}const {data,error}=await q;if(error)throw error;res.json({jobs:data||[]})}catch(e){res.status(500).json({error:e.message})}})
 router.post('/jobs',requireUser,async(req,res)=>{try{if(!await companyOwned(req.user.id,req.body?.companyId))return res.status(403).json({error:'Company access denied'});const {data,error}=await supabase.from('dispatch_jobs').insert({company_id:req.body.companyId,customer_id:req.body.customerId||null,job_type:req.body.jobType,reference_number:req.body.referenceNumber||null,pickup:req.body.pickup||{},dropoff:req.body.dropoff||{},cargo:req.body.cargo||{},pickup_window:req.body.pickupWindow||{},delivery_window:req.body.deliveryWindow||{},quoted_amount_cents:Number(req.body.quotedAmountCents||0),currency:req.body.currency||'USD',created_by_user_id:req.user.id}).select('*').single();if(error)throw error;res.status(201).json({job:data})}catch(e){res.status(500).json({error:e.message})}})
 router.post('/jobs/:id/recommend',requireUser,async(req,res)=>{try{const {data:job}=await supabase.from('dispatch_jobs').select('*').eq('id',req.params.id).maybeSingle();if(!job||!await companyOwned(req.user.id,job.company_id))return res.status(404).json({error:'Job not found'});const [{data:drivers},{data:vehicles}]=await Promise.all([supabase.from('dispatch_drivers').select('*').eq('company_id',job.company_id).eq('eligibility_status','eligible').eq('availability_status','available'),supabase.from('dispatch_vehicles').select('*').eq('company_id',job.company_id).eq('eligibility_status','eligible').eq('availability_status','available').eq('insurance_status','verified')]);const recommendation={drivers:drivers||[],vehicles:vehicles||[],note:'AI/dispatcher may rank these candidates using route, capacity, deadhead, hours, skills and cost. Final assignment remains human-approved.'};res.json({job,recommendation})}catch(e){res.status(500).json({error:e.message})}})
 router.post('/jobs/:id/assign',requireUser,async(req,res)=>{try{const {data:job}=await supabase.from('dispatch_jobs').select('*').eq('id',req.params.id).maybeSingle();if(!job||!await companyOwned(req.user.id,job.company_id))return res.status(404).json({error:'Job not found'});const [{data:driver},{data:vehicle}]=await Promise.all([supabase.from('dispatch_drivers').select('*').eq('id',req.body.driverId).eq('company_id',job.company_id).maybeSingle(),supabase.from('dispatch_vehicles').select('*').eq('id',req.body.vehicleId).eq('company_id',job.company_id).maybeSingle()]);if(!driver||driver.eligibility_status!=='eligible')return res.status(409).json({error:'Driver not eligible'});if(!vehicle||vehicle.eligibility_status!=='eligible'||vehicle.insurance_status!=='verified')return res.status(409).json({error:'Vehicle/insurance not eligible'});const {data,error}=await supabase.from('dispatch_assignments').insert({job_id:job.id,driver_id:driver.id,vehicle_id:vehicle.id,assigned_by_user_id:req.user.id,assignment_source:req.body.assignmentSource==='ai_recommended'?'ai_recommended':'human',recommendation:req.body.recommendation||{}}).select('*').single();if(error)throw error;await supabase.from('dispatch_jobs').update({status:'assigned',updated_at:new Date().toISOString()}).eq('id',job.id);res.status(201).json({assignment:data})}catch(e){res.status(500).json({error:e.message})}})
 router.post('/jobs/:id/status',requireUser,async(req,res)=>{try{const allowed=['booked','assigned','en_route_pickup','at_pickup','in_transit','at_dropoff','delivered','invoiced','settled','cancelled','blocked'];if(!allowed.includes(req.body?.status))return res.status(400).json({error:'Invalid status'});const {data:job}=await supabase.from('dispatch_jobs').select('*').eq('id',req.params.id).maybeSingle();if(!job||!await companyOwned(req.user.id,job.company_id))return res.status(404).json({error:'Job not found'});await supabase.from('dispatch_status_events').insert({job_id:job.id,actor_user_id:req.user.id,event_type:req.body.status,location:req.body.location||{},metadata:req.body.metadata||{}});const {data,error}=await supabase.from('dispatch_jobs').update({status:req.body.status,updated_at:new Date().toISOString()}).eq('id',job.id).select('*').single();if(error)throw error;res.json({job:data})}catch(e){res.status(500).json({error:e.message})}})
 router.post('/jobs/:id/financial-event',requireUser,async(req,res)=>{try{const {data:job}=await supabase.from('dispatch_jobs').select('*').eq('id',req.params.id).maybeSingle();if(!job||!await companyOwned(req.user.id,job.company_id))return res.status(404).json({error:'Job not found'});const {data,error}=await supabase.from('dispatch_financial_events').insert({job_id:job.id,event_type:req.body.eventType,amount_cents:Number(req.body.amountCents||0),currency:req.body.currency||'USD',status:'pending',requires_approval:true}).select('*').single();if(error)throw error;res.status(201).json({financialEvent:data,note:'Money movement is pending approval and processor execution.'})}catch(e){res.status(500).json({error:e.message})}})
 return router
}
module.exports={createDispatchRouter}
