const express=require('express')

function createOperationsRouter({supabase}){
 const router=express.Router()
 async function requireUser(req,res,next){const auth=req.headers.authorization||'';const token=auth.startsWith('Bearer ')?auth.slice(7):'';if(!token)return res.status(401).json({error:'Authentication required'});const {data,error}=await supabase.auth.getUser(token);if(error||!data?.user)return res.status(401).json({error:'Invalid session'});req.user=data.user;next()}
 const riskLevels=['green','yellow','orange','red']
 router.get('/workflows',requireUser,async(req,res)=>{try{const {data,error}=await supabase.from('ops_workflows').select('*').eq('owner_user_id',req.user.id).order('created_at',{ascending:false}).limit(100);if(error)throw error;res.json({workflows:data||[]})}catch(e){res.status(500).json({error:e.message})}})
 router.post('/workflows',requireUser,async(req,res)=>{try{const domain=String(req.body?.domain||'').trim();const workflowType=String(req.body?.workflowType||'').trim();if(!domain||!workflowType)return res.status(400).json({error:'domain and workflowType are required'});const risk=riskLevels.includes(String(req.body?.riskBand||'green'))?String(req.body.riskBand):'green';const requiresApproval=Boolean(req.body?.requiresApproval)||['orange','red'].includes(risk);const {data,error}=await supabase.from('ops_workflows').insert({owner_user_id:req.user.id,domain,workflow_type:workflowType,risk_band:risk,requires_approval:requiresApproval,input:req.body?.input||{}}).select('*').single();if(error)throw error;await supabase.from('ops_audit_events').insert({user_id:req.user.id,domain,event_type:'WORKFLOW_CREATED',entity_type:'ops_workflow',entity_id:data.id,risk_band:risk,payload:{workflowType,requiresApproval}});res.status(201).json({workflow:data})}catch(e){res.status(500).json({error:e.message})}})
 router.post('/workflows/:id/approve',requireUser,async(req,res)=>{try{const {data:w,error:werr}=await supabase.from('ops_workflows').select('*').eq('id',req.params.id).eq('owner_user_id',req.user.id).maybeSingle();if(werr)throw werr;if(!w)return res.status(404).json({error:'Workflow not found'});const {data,error}=await supabase.from('ops_workflows').update({approved_by:req.user.id,approved_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',w.id).select('*').single();if(error)throw error;await supabase.from('ops_audit_events').insert({user_id:req.user.id,domain:w.domain,event_type:'WORKFLOW_APPROVED',entity_type:'ops_workflow',entity_id:w.id,risk_band:w.risk_band});res.json({workflow:data})}catch(e){res.status(500).json({error:e.message})}})
 router.post('/audit',requireUser,async(req,res)=>{try{const domain=String(req.body?.domain||'other');const eventType=String(req.body?.eventType||'').trim();if(!eventType)return res.status(400).json({error:'eventType required'});const {data,error}=await supabase.from('ops_audit_events').insert({user_id:req.user.id,domain,event_type:eventType,entity_type:req.body?.entityType||null,entity_id:req.body?.entityId?String(req.body.entityId):null,risk_band:riskLevels.includes(req.body?.riskBand)?req.body.riskBand:'green',payload:req.body?.payload||{}}).select('*').single();if(error)throw error;res.status(201).json({event:data})}catch(e){res.status(500).json({error:e.message})}})
 return router
}
module.exports={createOperationsRouter}
