const express=require('express')

function createSportsVerseRouter({supabase}){
 const router=express.Router()
 async function requireUser(req,res,next){const a=req.headers.authorization||'';const t=a.startsWith('Bearer ')?a.slice(7):'';if(!t)return res.status(401).json({error:'Authentication required'});const {data,error}=await supabase.auth.getUser(t);if(error||!data?.user)return res.status(401).json({error:'Invalid session'});req.user=data.user;next()}
 router.get('/events',requireUser,async(req,res)=>{try{let q=supabase.from('sports_events').select('*').order('starts_at',{ascending:true}).limit(100);if(req.query.sport)q=q.eq('sport',String(req.query.sport));if(req.query.league)q=q.eq('league',String(req.query.league));const {data,error}=await q;if(error)throw error;res.json({events:data||[]})}catch(e){res.status(500).json({error:e.message})}})
 router.post('/experts/profile',requireUser,async(req,res)=>{try{const {data,error}=await supabase.from('sports_experts').upsert({user_id:req.user.id,display_name:String(req.body?.displayName||'').trim(),bio:req.body?.bio||null},{onConflict:'user_id'}).select('*').single();if(error)throw error;res.json({expert:data})}catch(e){res.status(500).json({error:e.message})}})
 router.get('/experts/me/record',requireUser,async(req,res)=>{try{const {data:expert}=await supabase.from('sports_experts').select('*').eq('user_id',req.user.id).maybeSingle();if(!expert)return res.json({expert:null,record:{wins:0,losses:0,pushes:0,pending:0}});const {data:picks,error}=await supabase.from('sports_picks').select('result').eq('expert_id',expert.id);if(error)throw error;const record={wins:0,losses:0,pushes:0,pending:0};for(const p of picks||[]){if(p.result==='win')record.wins++;else if(p.result==='loss')record.losses++;else if(p.result==='push')record.pushes++;else record.pending++}res.json({expert,record,total:(picks||[]).length})}catch(e){res.status(500).json({error:e.message})}})
 router.post('/picks',requireUser,async(req,res)=>{try{const {data:expert}=await supabase.from('sports_experts').select('*').eq('user_id',req.user.id).maybeSingle();if(!expert)return res.status(409).json({error:'Create an expert profile first'});const {data:event}=await supabase.from('sports_events').select('*').eq('id',req.body.eventId).maybeSingle();if(!event)return res.status(404).json({error:'Sports event not found'});if(event.starts_at&&new Date(event.starts_at).getTime()<=Date.now())return res.status(409).json({error:'Picks must be locked before event start'});const {data,error}=await supabase.from('sports_picks').insert({expert_id:expert.id,event_id:event.id,pick_type:req.body.pickType,selection:req.body.selection,line_snapshot:req.body.lineSnapshot||{},confidence:req.body.confidence||null,rationale:req.body.rationale||null,locked_at:new Date().toISOString()}).select('*').single();if(error)throw error;res.status(201).json({pick:data,note:'Prediction only. This API does not place wagers or move money.'})}catch(e){res.status(500).json({error:e.message})}})
 router.get('/picks/feed',requireUser,async(req,res)=>{try{const {data,error}=await supabase.from('sports_picks').select('*,sports_experts(display_name,verification_status),sports_events(sport,league,home_name,away_name,starts_at,status,score)').is('deleted_at',null).order('locked_at',{ascending:false}).limit(100);if(error)throw error;res.json({picks:data||[]})}catch(e){res.status(500).json({error:e.message})}})
 router.post('/ai-predictions',requireUser,async(req,res)=>{try{const {data:event}=await supabase.from('sports_events').select('*').eq('id',req.body.eventId).maybeSingle();if(!event)return res.status(404).json({error:'Event not found'});const {data,error}=await supabase.from('sports_ai_predictions').insert({event_id:event.id,model_name:req.body.modelName||'Stubbs AI/HoloGPT',prediction:req.body.prediction||{},confidence:req.body.confidence||null,evidence:req.body.evidence||[]}).select('*').single();if(error)throw error;res.status(201).json({prediction:data,disclaimer:'AI sports predictions are uncertain analysis, not guaranteed outcomes.'})}catch(e){res.status(500).json({error:e.message})}})
 router.post('/rooms',requireUser,async(req,res)=>{try{const {data,error}=await supabase.from('sports_live_rooms').insert({event_id:req.body.eventId||null,host_user_id:req.user.id,title:String(req.body.title||'SportsVerse LIVE').slice(0,160),live_room_ref:req.body.liveRoomRef||null}).select('*').single();if(error)throw error;res.status(201).json({room:data})}catch(e){res.status(500).json({error:e.message})}})
 router.get('/consensus/:eventId',requireUser,async(req,res)=>{try{const [{data:picks},{data:ai}]=await Promise.all([supabase.from('sports_picks').select('selection,result,confidence').eq('event_id',req.params.eventId).is('deleted_at',null),supabase.from('sports_ai_predictions').select('*').eq('event_id',req.params.eventId).order('created_at',{ascending:false}).limit(10)]);const counts={};for(const p of picks||[])counts[p.selection]=(counts[p.selection]||0)+1;res.json({expertConsensus:counts,expertPickCount:(picks||[]).length,aiPredictions:ai||[],wageringExecution:false})}catch(e){res.status(500).json({error:e.message})}})
 return router
}
module.exports={createSportsVerseRouter}
