import { useEffect, useState } from 'react'
import { advanceCafeOrder, getCafeMenu, placeSimulatedCafeOrder, type CafeMenuItem } from '../services/pressCafeOperations'
import { getCafeTwin } from '../services/advancedWorlds'
import { isSupabaseConfigured } from '../services/supabaseClient'

interface Props{onClose:()=>void}
export default function AICafeRestaurant({onClose}:Props){
 const [menu,setMenu]=useState<CafeMenuItem[]>([]),[cafe,setCafe]=useState<any>(null),[cart,setCart]=useState<CafeMenuItem[]>([]),[order,setOrder]=useState<any>(null),[message,setMessage]=useState(''),[busy,setBusy]=useState(false)
 useEffect(()=>{if(!isSupabaseConfigured())return;Promise.all([getCafeMenu(),getCafeTwin()]).then(([m,c])=>{setMenu(m);setCafe(c.cafe)}).catch(e=>setMessage(e instanceof Error?e.message:String(e)))},[])
 const total=cart.reduce((n,x)=>n+Number(x.price),0)
 const btn:React.CSSProperties={background:'#21180f',border:'1px solid #ffd16677',color:'#ffd166',borderRadius:8,padding:'8px 11px',fontFamily:'monospace',cursor:'pointer'},box:React.CSSProperties={background:'#0b0a12',border:'1px solid #3a3024',borderRadius:12,padding:12}
 async function place(){if(!cafe||!cart.length)return;setBusy(true);try{const o=await placeSimulatedCafeOrder(cafe.id,cart);setOrder(o);setCart([]);setMessage('Simulation order placed. No real payment was charged.')}catch(e){setMessage(e instanceof Error?e.message:String(e))}finally{setBusy(false)}}
 async function next(status:'preparing'|'ready'|'completed'){if(!order)return;setBusy(true);try{const o=await advanceCafeOrder(order.id,status);setOrder(o);setMessage(`Order is now ${status}.`)}finally{setBusy(false)}}
 return <div style={{position:'fixed',inset:0,zIndex:10070,background:'rgba(10,7,5,.99)',color:'#fff',fontFamily:'monospace',overflowY:'auto'}}><div style={{maxWidth:1050,margin:'0 auto',padding:16}}><div style={{display:'flex',gap:12,alignItems:'center'}}><button style={btn} onClick={onClose}>← Back</button><div><h2 style={{margin:0,color:'#ffd166'}}>AI Café • Free Market Coffee • Earth Kitchen</h2><div style={{fontSize:10,color:'#8d8174'}}>Digital restaurant twin + workforce operations simulator</div></div></div>{message&&<div style={{...box,marginTop:12,borderColor:'#ffd16655'}}>{message}</div>}<div style={{display:'grid',gridTemplateColumns:'2fr 1fr',gap:12,marginTop:14}}><section><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(220px,1fr))',gap:9}}>{menu.map(i=><article key={i.id} style={box}><b>{i.name}</b><div style={{fontSize:10,color:'#ffd166'}}>{i.category} • ${Number(i.price).toFixed(2)}</div><p style={{fontSize:11,color:'#aaa'}}>{i.description}</p><button style={btn} onClick={()=>setCart(c=>[...c,i])}>Add to simulated order</button></article>)}</div></section><aside style={box}><h3>Order</h3>{cart.map((i,n)=><div key={`${i.id}-${n}`} style={{fontSize:11,marginBottom:5}}>{i.name} <span style={{float:'right'}}>${Number(i.price).toFixed(2)}</span></div>)}<hr style={{borderColor:'#332b22'}}/><b>Total <span style={{float:'right'}}>${total.toFixed(2)}</span></b><button disabled={busy||!cart.length} style={{...btn,width:'100%',marginTop:10}} onClick={place}>Place Simulation Order</button>{order&&<div style={{marginTop:12}}><b>Order status: {order.status}</b><div style={{display:'grid',gap:6,marginTop:7}}>{order.status==='placed'&&<button style={btn} onClick={()=>next('preparing')}>Kitchen: Start Preparing</button>}{order.status==='preparing'&&<button style={btn} onClick={()=>next('ready')}>Kitchen: Mark Ready</button>}{order.status==='ready'&&<button style={btn} onClick={()=>next('completed')}>Complete Pickup</button>}</div></div>}<p style={{fontSize:9,color:'#777',marginTop:14}}>This flow is deliberately simulation-only. Real café POS/payment and food-safety operations require licensed local implementation and physical-store controls.</p></aside></div></div></div>
}
