import { useEffect, useState } from 'react'
import { getSupabaseClient } from '../services/supabaseClient'

const enabled=()=>import.meta.env.VITE_ALL_AMERICAN_UNIVERSITY_ENABLED==='true'

type CatalogItem={id:string;code?:string;name?:string;title?:string;level?:string;school?:string;opportunity_type?:string;description?:string}
export default function AllAmericanUniversityLauncher(){
 const [open,setOpen]=useState(false)
 if(!enabled())return null
 return <><button aria-label="Open All American University" onClick={()=>setOpen(true)} style={{position:'fixed',right:12,bottom:166,zIndex:9001,border:'1px solid #e8b94488',borderRadius:999,padding:'10px 14px',background:'#1d1608',color:'#fff',fontWeight:900,cursor:'pointer'}}>🎓 ALL AMERICAN UNIVERSITY</button>{open&&<UniversityHub onClose={()=>setOpen(false)}/>}</>
}
function UniversityHub({onClose}:{onClose:()=>void}){
 const [programs,setPrograms]=useState<CatalogItem[]>([]),[courses,setCourses]=useState<CatalogItem[]>([]),[opps,setOpps]=useState<CatalogItem[]>([]),[student,setStudent]=useState<any>(null),[status,setStatus]=useState('Loading university runtime…')
 useEffect(()=>{let alive=true;(async()=>{const sb=getSupabaseClient();if(!sb){setStatus('Supabase is not configured. University catalog runtime is unavailable.');return}try{const [{data:p},{data:c},{data:o},{data:{user}}]=await Promise.all([sb.from('university_programs').select('id,code,name,level,school,description').eq('active',true).limit(24),sb.from('university_courses').select('id,code,title,level,school,description').eq('active',true).limit(24),sb.from('university_opportunities').select('id,title,opportunity_type,description').eq('active',true).limit(24),sb.auth.getUser()]);if(!alive)return;setPrograms(p||[]);setCourses(c||[]);setOpps(o||[]);if(user){const {data:s}=await sb.from('university_students').select('id,student_number,education_stage,program_code,academic_status,expected_completion').eq('user_id',user.id).maybeSingle();if(alive)setStudent(s)}setStatus('University runtime connected.')}catch(e:any){if(alive)setStatus(e?.message||'University runtime load failed')}})();return()=>{alive=false}},[])
 const pillars=['Pre-K → K-5 → Middle → High School','Trade + Certificate + Associate','Bachelor → Master → Doctorate/Professional','Immersive labs + GameVerse learning missions','Library + archive research + creator portfolio','Internships + apprenticeships + jobs + research','Accessibility accommodations + guardian controls','HBCU partnership network + Black excellence programs']
 return <div role="dialog" aria-label="All American University" style={{position:'fixed',inset:0,zIndex:12300,overflowY:'auto',background:'radial-gradient(circle at top,#17213a,#050711 58%,#020205)',color:'#fff',padding:18}}><div style={{maxWidth:1200,margin:'0 auto'}}><header style={{display:'flex',justifyContent:'space-between',gap:12}}><div><div style={{fontSize:10,color:'#4fe3ff',fontWeight:900,letterSpacing:3}}>TRYAMM • ALL AMERICAN UNIVERSITY & ACADEMY</div><h1 style={{margin:'6px 0'}}>Learn → Build → Work → Create → Own → Teach</h1><p style={{color:'#aab8ca'}}>One education passport connecting classroom learning, immersive exhibits, GameVerse missions, portfolios, jobs and next-generation mentorship.</p></div><button onClick={onClose} aria-label="Close All American University" style={close}>×</button></header><section style={panel}><b>{status}</b>{student?<p style={muted}>Student: {student.student_number||'profile'} • {student.education_stage} • {student.academic_status} • program {student.program_code||'not selected'}</p>:<p style={muted}>Sign in and create a student profile to persist enrollment, credentials, portfolio and opportunities.</p>}</section><section style={panel}><h2>Full education pathway</h2><div style={grid}>{pillars.map(x=><article key={x} style={card}>{x}</article>)}</div></section><section style={panel}><h2>Programs</h2><div style={grid}>{programs.length?programs.map(x=><article key={x.id} style={card}><b>{x.code} • {x.name}</b><small>{x.level} • {x.school}</small><p style={muted}>{x.description}</p></article>):<p style={muted}>No active catalog rows returned yet.</p>}</div></section><section style={panel}><h2>Courses + immersive mission bridge</h2><div style={grid}>{courses.slice(0,12).map(x=><article key={x.id} style={card}><b>{x.code} • {x.title}</b><small>{x.level} • {x.school}</small><button onClick={()=>window.dispatchEvent(new CustomEvent('tryamm:middleverse-open',{detail:{source:'all-american-university',course:x.code}}))}>SEND TO IMMERSIVE / GAME MISSION</button></article>)}</div></section><section style={panel}><h2>Opportunity engine</h2><div style={grid}>{opps.slice(0,12).map(x=><article key={x.id} style={card}><b>{x.title}</b><small>{x.opportunity_type}</small><p style={muted}>{x.description}</p></article>)}</div></section><section style={panel}><h2>Accreditation truth</h2><p style={muted}>Software can deliver curriculum, records and learning experiences, but accredited degrees, professional licensure and official HBCU designation require the applicable external institutional/regulatory approvals. The app must never imply those approvals before they exist.</p></section></div></div>
}
const panel={border:'1px solid #284158',borderRadius:18,padding:16,margin:'14px 0',background:'#08111b'} as const
const grid={display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(220px,1fr))',gap:10} as const
const card={border:'1px solid #26394d',borderRadius:14,padding:13,background:'#0a1420',display:'grid',gap:7} as const
const muted={color:'#aab8ca',lineHeight:1.5} as const
const close={width:44,height:44,borderRadius:'50%',border:'1px solid #4a5e73',background:'#0b1320',color:'#fff',fontSize:22} as const
