import {useEffect,useState} from 'react'
import {ASSET_FORGE_CONTRACT,BUILD_AGENTS,DEFAULT_BUILD_QUEUE} from '../agents/buildSwarm'
const panel:React.CSSProperties={padding:14,border:'1px solid #294055',borderRadius:16,background:'#08121c'}
const btn:React.CSSProperties={border:'1px solid #4fe3ff77',borderRadius:11,padding:'10px 13px',background:'#0b1a27',color:'#fff',fontWeight:900,cursor:'pointer'}
export default function BuildSwarmControl(){
 const[open,setOpen]=useState(false)
 useEffect(()=>{(window as any).__showBuildSwarm=()=>setOpen(true);return()=>{delete (window as any).__showBuildSwarm}},[])
 if(!open)return null
 return <div role="dialog" aria-modal="true" aria-label="AI Cafe Build Swarm" style={{position:'fixed',inset:0,zIndex:13600,background:'rgba(1,3,9,.98)',color:'#fff',overflow:'auto'}}><div style={{maxWidth:1180,margin:'0 auto',padding:18}}><header style={{display:'flex',justifyContent:'space-between',gap:12}}><div><div style={{color:'#4fe3ff',fontSize:10,fontWeight:950,letterSpacing:3}}>AI CAFE MULTITASKING DEVELOPMENT</div><h1 style={{margin:'4px 0'}}>Build Swarm + HoloForge / GLE</h1><p style={{color:'#aebdca',maxWidth:820}}>One coordinator divides work into independent lanes, reuses shared contracts, and requires Guardian QA before anything is called GREEN. This screen is a build manifest/control surface; it does not silently run background coding jobs.</p></div><button onClick={()=>setOpen(false)} style={btn}>Close</button></header><section style={{...panel,marginTop:14}}><h2>Parallel specialist lanes</h2><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(240px,1fr))',gap:9}}>{BUILD_AGENTS.map(a=><article key={a.id} style={{...panel,background:'#0b1722'}}><b>{a.name}</b><p style={{color:'#9fb3c6',fontSize:11}}>{a.mission}</p></article>)}</div></section><section style={{...panel,marginTop:12}}><h2>Canonical build queue</h2><div style={{display:'grid',gap:8}}>{DEFAULT_BUILD_QUEUE.map(t=><div key={t.id} style={{...panel,background:'#0b1722'}}><div style={{display:'flex',justifyContent:'space-between',gap:8}}><b>{t.title}</b><span style={{color:t.status==='blocked'?'#ffb86b':t.status==='ready'?'#78ffb4':'#9fb3c6'}}>{t.status.toUpperCase()}</span></div><div style={{fontSize:11,color:'#9fb3c6',marginTop:5}}>Output: {t.output}</div><div style={{fontSize:10,color:'#71889b'}}>Proof: {t.verification}</div></div>)}</div></section><section style={{...panel,marginTop:12}}><h2>Global Asset Generator contract</h2><p style={{color:'#9fb3c6'}}>GLB/glTF is the portable master asset lane for the web world; adapters then prepare the same source asset for Unity, Unreal and Godot instead of recreating every object four times.</p><div style={{display:'flex',gap:7,flexWrap:'wrap'}}>{ASSET_FORGE_CONTRACT.map(x=><span key={x} style={{...panel,background:'#0b1722',fontSize:10}}>{x}</span>)}</div></section><section style={{...panel,marginTop:12}}><h2>Asset families to forge once and reuse everywhere</h2><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(210px,1fr))',gap:8}}>{['Chicago/StreetVerse building kit','Bodega + YAHAVAH store kit','Beauty supply + salon kit','Restaurant/nightclub interiors','Roads/traffic/signage','NPC wardrobe/body variants','Cars/bikes/delivery vehicles','Birds/fish/insects/dogs/wildlife','Food/grocery product props','Cold Vault/Holo Fridge props','Furniture/housing props','Creator stages/studios'].map(x=><div key={x} style={{...panel,background:'#0b1722'}}>{x}</div>)}</div></section></div></div>
}