import {useState} from 'react'
import {getAccessToken} from '../services/supabaseClient'

const API=(import.meta as any).env?.VITE_API_URL??''
type FaceGift={id:string;label:string;icon:string;effect:string;credits:number;cue:string}
const GIFTS:FaceGift[]=[
  {id:'face-holo',label:'Holo Me',icon:'🙂',effect:'Your authorized face appears as a cyan/gold hologram burst',credits:100,cue:'face'},
  {id:'face-crown',label:'Crown Me',icon:'👑',effect:'Your face rises inside a holographic royal crown',credits:250,cue:'facecrown'},
  {id:'face-kiss',label:'Kiss Face',icon:'💋',effect:'Your face sends a playful holographic kiss reaction',credits:150,cue:'facekiss'},
  {id:'face-hug',label:'Hug Face',icon:'🤗',effect:'Your face appears inside a warm holographic hug aura',credits:150,cue:'facehug'},
  {id:'face-lion',label:'Judah Face',icon:'🦁',effect:'Your face transitions into a stylized Judah lion hologram',credits:500,cue:'facelion'},
  {id:'face-avatar',label:'Avatar Me',icon:'🧑‍🚀',effect:'Your face becomes a creator avatar card for AR/VR rooms',credits:400,cue:'faceavatar'},
]

export default function FaceGiftStudio({recipientId='live-host'}:{recipientId?:string}){
  const [gift,setGift]=useState(GIFTS[0]);const [faceAssetUrl,setFaceAssetUrl]=useState('');const [consent,setConsent]=useState(false);const [mode,setMode]=useState<'screen'|'ar'|'vr'>('screen');const [message,setMessage]=useState('Use only your own face or a face you have permission to use.');const [busy,setBusy]=useState(false)
  async function send(){setBusy(true);try{const token=await getAccessToken();if(!token)throw new Error('Sign in before sending a Face Gift.');const r=await fetch(`${API}/api/gifts/intent`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({giftType:gift.id,recipientId,amountMinor:gift.credits,spatialMode:mode,musicCue:gift.cue,faceAssetUrl,faceConsent:consent})});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data?.error||`Face Gift failed (${r.status})`);window.dispatchEvent(new CustomEvent('tryamm:holo-gift',{detail:{...data.intent,effect:gift.effect,collection:'FACE GIFTS'}}));setMessage(`${gift.label} fired in ${mode.toUpperCase()} mode. Face consent was recorded for this gift intent.`)}catch(e){setMessage(e instanceof Error?e.message:'Face Gift failed.')}finally{setBusy(false)}}
  return <section style={{border:'1px solid #3c4564',borderRadius:20,background:'#08111be8',padding:14,color:'#fff'}}><div style={{fontSize:10,letterSpacing:2.4,color:'#4fe3ff',fontWeight:950}}>FACE GIFT STUDIO • CONSENT REQUIRED</div><input value={faceAssetUrl} onChange={e=>setFaceAssetUrl(e.target.value)} placeholder="Authorized face image URL" style={{width:'100%',boxSizing:'border-box',marginTop:10,padding:10,borderRadius:10,border:'1px solid #2b4050',background:'#03080e',color:'#fff'}}/><label style={{display:'flex',gap:8,alignItems:'flex-start',fontSize:10,color:'#b7c4cd',marginTop:9}}><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/> I own this face image or have permission from the person shown to use it as a gift.</label><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(125px,1fr))',gap:7,marginTop:10}}>{GIFTS.map(g=><button key={g.id} onClick={()=>setGift(g)} style={{padding:10,borderRadius:12,border:`1px solid ${gift.id===g.id?'#4fe3ff':'#2a3948'}`,background:gift.id===g.id?'#0b2938':'#071019',color:'#fff',cursor:'pointer'}}><div style={{fontSize:26}}>{g.icon}</div><div style={{fontSize:10,fontWeight:900}}>{g.label}</div><div style={{fontSize:8,color:'#8fa1ad',marginTop:3}}>{g.effect}</div><div style={{fontSize:8,color:'#e8b944',marginTop:4}}>{g.credits} credits</div></button>)}</div><div style={{display:'flex',gap:7,marginTop:10}}>{(['screen','ar','vr'] as const).map(m=><button key={m} onClick={()=>setMode(m)} style={{flex:1,padding:8,borderRadius:10,border:`1px solid ${mode===m?'#4fe3ff':'#2b3e4d'}`,background:mode===m?'#0b2938':'#071019',color:'#fff',fontWeight:900,cursor:'pointer'}}>{m.toUpperCase()}</button>)}</div><button disabled={busy||!consent||!faceAssetUrl.trim()} onClick={send} style={{width:'100%',marginTop:10,padding:12,borderRadius:12,border:'1px solid #4fe3ff88',background:'linear-gradient(135deg,#0c3343,#2a1f35)',color:'#fff',fontWeight:950,cursor:'pointer',opacity:busy||!consent||!faceAssetUrl.trim()?.55:1}}>{busy?'SENDING…':`SEND ${gift.icon} ${gift.label}`}</button><div style={{fontSize:10,color:'#a6b5bf',lineHeight:1.5,marginTop:8}}>{message}</div></section>
}
