import {useEffect,useMemo,useState} from 'react'

type FridgeItem={id:string;name:string;qty:number;unit:string;reorderAt:number;category:string;expiresInDays:number}
type ProteinPack={id:string;name:string;audience:string;contents:string[];targetBudget:number;subscription:boolean}
const seed:FridgeItem[]=[
{id:'eggs',name:'Eggs',qty:12,unit:'count',reorderAt:6,category:'protein',expiresInDays:14},
{id:'milk',name:'Plant-based milk',qty:2,unit:'cartons',reorderAt:1,category:'dairy-alt',expiresInDays:8},
{id:'greens',name:'Leafy greens',qty:2,unit:'bags',reorderAt:1,category:'produce',expiresInDays:4},
{id:'rice',name:'Brown rice',qty:1,unit:'bag',reorderAt:1,category:'grain',expiresInDays:90},
{id:'beans',name:'Black beans',qty:4,unit:'cans',reorderAt:2,category:'pantry',expiresInDays:365},
{id:'chicken',name:'Chicken portions',qty:6,unit:'lb',reorderAt:2,category:'cold-protein',expiresInDays:4},
]
const packs:ProteinPack[]=[
{id:'family-chicken',name:'Family Chicken Box',audience:'Families',contents:['Chicken breasts/thighs','Drumsticks/wings','Freezer-ready portions'],targetBudget:49,subscription:true},
{id:'family-mixed',name:'Family Mixed Protein Box',audience:'Families',contents:['Chicken','Ground beef/turkey','Fish or local substitute'],targetBudget:79,subscription:true},
{id:'seafood',name:'Seafood Box',audience:'Families',contents:['Fish fillets','Shrimp or seasonal local seafood','Freezer-ready packs'],targetBudget:99,subscription:true},
{id:'beef',name:'Beef Freezer Box',audience:'Families',contents:['Ground beef','Roast/stew cuts','Steak/value cuts'],targetBudget:149,subscription:true},
{id:'sabbath',name:'Sabbath Meal Box',audience:'Families / community',contents:['Protein','Fresh vegetables','Rice/grain','Beans','Meal ingredients'],targetBudget:69,subscription:true},
{id:'restaurant',name:'Restaurant Bulk Protein Box',audience:'Restaurants / bodegas / markets',contents:['Bulk case protein','Lot/temperature records','Receiving documentation'],targetBudget:299,subscription:false},
]
const panel:React.CSSProperties={padding:14,border:'1px solid #294055',borderRadius:16,background:'#08121c'}
const btn:React.CSSProperties={border:'1px solid #4fe3ff77',borderRadius:11,padding:'10px 13px',background:'#0b1a27',color:'#fff',fontWeight:900,cursor:'pointer'}
export default function HoloFridge(){
 const[open,setOpen]=useState(false);const[items,setItems]=useState(seed);const[budget,setBudget]=useState(75);const[localFirst,setLocalFirst]=useState(true);const[selectedPack,setSelectedPack]=useState<string|null>(null)
 useEffect(()=>{(window as any).__showHoloFridge=()=>setOpen(true);(window as any).__showHoloColdVault=()=>setOpen(true);return()=>{delete (window as any).__showHoloFridge;delete (window as any).__showHoloColdVault}},[])
 const needs=useMemo(()=>items.filter(i=>i.qty<=i.reorderAt||i.expiresInDays<=3),[items])
 const mealIdeas=useMemo(()=>['Rice + beans + greens bowl','Vegetable stir-fry','Protein breakfast','Pantry soup'].slice(0,Math.max(1,Math.min(4,items.length))),[items])
 if(!open)return null
 return <div role="dialog" aria-modal="true" aria-label="Holo Fridge" style={{position:'fixed',inset:0,zIndex:13400,background:'rgba(1,3,9,.97)',color:'#fff',overflow:'auto'}}><div style={{maxWidth:1100,margin:'0 auto',padding:18}}><header style={{display:'flex',justifyContent:'space-between',gap:12}}><div><div style={{color:'#4fe3ff',fontSize:10,fontWeight:950,letterSpacing:3}}>HOME INVENTORY + HOLO COLD VAULT</div><h1 style={{margin:'4px 0'}}>Holo Fridge</h1><p style={{color:'#aebdca',maxWidth:820}}>Household inventory, freezer rotation, local-first cold-chain sourcing, meal planning and replenishment connected to YAHAVAH Grocery, Holo Coupon, Holo Delivery and the Global Virtual Warehouse.</p></div><button onClick={()=>setOpen(false)} style={btn}>Close</button></header>
<section style={{...panel,marginTop:14}}><h2>Household inventory + freezer</h2><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(210px,1fr))',gap:9}}>{items.map(i=><div key={i.id} style={{...panel,background:'#0b1722'}}><b>{i.name}</b><div>{i.qty} {i.unit}</div><div style={{fontSize:11,color:i.expiresInDays<=3?'#ffca7a':'#9fb3c6'}}>Freshness/use-by signal: {i.expiresInDays} days</div><div style={{display:'flex',gap:6,marginTop:8}}><button style={btn} onClick={()=>setItems(xs=>xs.map(x=>x.id===i.id?{...x,qty:Math.max(0,x.qty-1)}:x))}>Use 1</button><button style={btn} onClick={()=>setItems(xs=>xs.map(x=>x.id===i.id?{...x,qty:x.qty+1}:x))}>+1</button></div></div>)}</div></section>
<section style={{...panel,marginTop:12}}><h2>Local-First Price Shield</h2><label style={{display:'flex',gap:8,alignItems:'center'}}><input type="checkbox" checked={localFirst} onChange={e=>setLocalFirst(e.target.checked)}/> Prefer local/regional U.S. supply when safety, quality, availability and floor-margin rules are satisfied</label><p style={{color:'#aebdca',lineHeight:1.55}}>LOCAL BUTCHER / FARM → REFRIGERATED DISTRIBUTOR → GROCERY PARTNER → COLD 3PL → VERIFIED INVENTORY → LOWEST SAFE LANDED COST → DELIVERY. Imported supply is not automatically rejected, but duty/tariff/freight must be included. If a verified local substitute is safer or cheaper after landed cost, it wins.</p></section>
<section style={{...panel,marginTop:12}}><h2>Special freezer packages</h2><p style={{fontSize:11,color:'#8fa4b6'}}>Displayed amounts are TARGET BUDGETS, not guaranteed public prices. A package becomes sellable only after verified local/wholesale inventory produces a compliant floor price at or below the target, or the customer accepts the verified higher quote.</p><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(240px,1fr))',gap:9}}>{packs.map(p=><button key={p.id} onClick={()=>setSelectedPack(p.id)} style={{...panel,textAlign:'left',cursor:'pointer',background:selectedPack===p.id?'#10263a':'#0b1722',color:'#fff'}}><b>{p.name}</b><div style={{color:'#e8b944',fontWeight:950}}>Target budget: ${p.targetBudget}</div><div style={{fontSize:11,color:'#9fb3c6'}}>{p.audience}</div><ul>{p.contents.map(x=><li key={x}>{x}</li>)}</ul><div style={{fontSize:10,color:'#7f94a6'}}>{p.subscription?'Eligible for customer-approved subscription/reorder':'Quote/PO based'}</div></button>)}</div>{selectedPack&&<div style={{marginTop:10,display:'flex',gap:8,flexWrap:'wrap'}}><button style={btn} onClick={()=>{(window as any).__showVirtualWarehouse?.()}}>Compare verified suppliers</button><button style={btn} onClick={()=>{(window as any).__showYahavahGrocery?.()}}>Open YAHAVAH Grocery</button><button style={btn} onClick={()=>{(window as any).__showHoloDelivery?.()}}>Plan cold delivery</button></div>}</section>
<section style={{...panel,marginTop:12}}><h2>Smart replenishment</h2><label>Weekly grocery budget $ <input type="number" min="0" value={budget} onChange={e=>setBudget(Math.max(0,Number(e.target.value)||0))}/></label><p style={{color:'#aebdca'}}>Reorder candidates: {needs.length?needs.map(n=>n.name).join(', '):'Nothing urgent'}</p><button style={btn} onClick={()=>{(window as any).__showYahavahGrocery?.()}}>Build cheapest healthy basket</button> <button style={btn} onClick={()=>{(window as any).__showVirtualWarehouse?.()}}>Compare fulfillment rails</button></section>
<section style={{...panel,marginTop:12}}><h2>Restaurant / bodega / market cold vault</h2><p style={{color:'#aebdca'}}>PAR LEVELS → SALES → LOW STOCK → PREPARE PURCHASE ORDER → VERIFIED SUPPLIER → COLD-CHAIN DISPATCH → TEMPERATURE/LOT RECEIVING LOG → INVENTORY UPDATED. Automatic charging stays behind an approved recurring-purchase or merchant purchasing policy.</p></section>
<section style={{...panel,marginTop:12}}><h2>Meal ideas from what is already at home</h2><div style={{display:'flex',gap:8,flexWrap:'wrap'}}>{mealIdeas.map(x=><span key={x} style={{...panel,background:'#0b1722'}}>{x}</span>)}</div><p style={{fontSize:11,color:'#7f94a6'}}>Holo Fridge should never make medical or nutrition-treatment claims. Dietary preferences, allergies and accessibility needs can guide shopping, but health decisions stay with the user and qualified professionals where appropriate.</p></section>
<section style={{...panel,marginTop:12}}><b>COLD-CHAIN LOOP</b><div style={{marginTop:8,color:'#aebdca'}}>VERIFIED LOT → CUT/WEIGHT → PACK/USE-BY → STORAGE REQUIREMENT → AVAILABLE-TO-PROMISE → CUSTOMER ORDER → GUARDIAN PAYMENT → COLD PICK/PACK → REFRIGERATED/INSULATED DELIVERY → TRACKING → DELIVERY PROOF → HOLO FRIDGE UPDATED → CONSUMPTION/EXPIRATION → MEAL SUGGESTION → REORDER.</div></section></div></div>
}