import {useEffect,useMemo,useState} from 'react'

type FridgeItem={id:string;name:string;qty:number;unit:string;reorderAt:number;category:string;expiresInDays:number}
const seed:FridgeItem[]=[
{id:'eggs',name:'Eggs',qty:12,unit:'count',reorderAt:6,category:'protein',expiresInDays:14},
{id:'milk',name:'Plant-based milk',qty:2,unit:'cartons',reorderAt:1,category:'dairy-alt',expiresInDays:8},
{id:'greens',name:'Leafy greens',qty:2,unit:'bags',reorderAt:1,category:'produce',expiresInDays:4},
{id:'rice',name:'Brown rice',qty:1,unit:'bag',reorderAt:1,category:'grain',expiresInDays:90},
{id:'beans',name:'Black beans',qty:4,unit:'cans',reorderAt:2,category:'pantry',expiresInDays:365},
]
const panel:React.CSSProperties={padding:14,border:'1px solid #294055',borderRadius:16,background:'#08121c'}
const btn:React.CSSProperties={border:'1px solid #4fe3ff77',borderRadius:11,padding:'10px 13px',background:'#0b1a27',color:'#fff',fontWeight:900,cursor:'pointer'}
export default function HoloFridge(){
 const[open,setOpen]=useState(false);const[items,setItems]=useState(seed);const[budget,setBudget]=useState(75)
 useEffect(()=>{(window as any).__showHoloFridge=()=>setOpen(true);return()=>{delete (window as any).__showHoloFridge}},[])
 const needs=useMemo(()=>items.filter(i=>i.qty<=i.reorderAt||i.expiresInDays<=3),[items])
 const mealIdeas=useMemo(()=>['Rice + beans + greens bowl','Vegetable stir-fry','Protein breakfast','Pantry soup'].slice(0,Math.max(1,Math.min(4,items.length))),[items])
 if(!open)return null
 return <div role="dialog" aria-modal="true" aria-label="Holo Fridge" style={{position:'fixed',inset:0,zIndex:13400,background:'rgba(1,3,9,.97)',color:'#fff',overflow:'auto'}}><div style={{maxWidth:1050,margin:'0 auto',padding:18}}><header style={{display:'flex',justifyContent:'space-between',gap:12}}><div><div style={{color:'#4fe3ff',fontSize:10,fontWeight:950,letterSpacing:3}}>HOME INVENTORY → HEALTHY BASKET → VERIFIED ORDER</div><h1 style={{margin:'4px 0'}}>Holo Fridge</h1><p style={{color:'#aebdca',maxWidth:780}}>A household inventory, meal-planning and replenishment layer that connects YAHAVAH Grocery, Holo Coupon, Holo Delivery and the Global Virtual Warehouse.</p></div><button onClick={()=>setOpen(false)} style={btn}>Close</button></header><section style={{...panel,marginTop:14}}><h2>Household inventory</h2><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(210px,1fr))',gap:9}}>{items.map(i=><div key={i.id} style={{...panel,background:'#0b1722'}}><b>{i.name}</b><div>{i.qty} {i.unit}</div><div style={{fontSize:11,color:i.expiresInDays<=3?'#ffca7a':'#9fb3c6'}}>Freshness: {i.expiresInDays} days</div><div style={{display:'flex',gap:6,marginTop:8}}><button style={btn} onClick={()=>setItems(xs=>xs.map(x=>x.id===i.id?{...x,qty:Math.max(0,x.qty-1)}:x))}>Use 1</button><button style={btn} onClick={()=>setItems(xs=>xs.map(x=>x.id===i.id?{...x,qty:x.qty+1}:x))}>+1</button></div></div>)}</div></section><section style={{...panel,marginTop:12}}><h2>Smart replenishment</h2><label>Weekly grocery budget $ <input type="number" min="0" value={budget} onChange={e=>setBudget(Math.max(0,Number(e.target.value)||0))}/></label><p style={{color:'#aebdca'}}>Reorder candidates: {needs.length?needs.map(n=>n.name).join(', '):'Nothing urgent'}</p><button style={btn} onClick={()=>{(window as any).__showYahavahGrocery?.()}}>Build cheapest healthy basket</button> <button style={btn} onClick={()=>{(window as any).__showVirtualWarehouse?.()}}>Compare fulfillment rails</button></section><section style={{...panel,marginTop:12}}><h2>Meal ideas from what is already at home</h2><div style={{display:'flex',gap:8,flexWrap:'wrap'}}>{mealIdeas.map(x=><span key={x} style={{...panel,background:'#0b1722'}}>{x}</span>)}</div><p style={{fontSize:11,color:'#7f94a6'}}>Holo Fridge should never make medical or nutrition-treatment claims. Dietary preferences, allergies and accessibility needs can guide shopping, but health decisions stay with the user and qualified professionals where appropriate.</p></section><section style={{...panel,marginTop:12}}><b>LOOP</b><div style={{marginTop:8,color:'#aebdca'}}>SCAN/ADD → INVENTORY → CONSUMPTION → LOW/EXPIRING → MEAL PLAN → YAHAVAH BASKET → VIRTUAL WAREHOUSE → HOLO COUPON → GUARDIAN → PAYMENT → DELIVERY → FRIDGE UPDATED.</div></section></div></div>
}