import { useEffect, useState } from 'react'
import { createAdCampaign, createHoloBuilderProject, createHoloDelivery, createLogisticsJob, holoSearch, listHoloversePortals, prepareTranslation, reportHoloSafetyEvent, requestHoloRide, type HoloSearchDocument, type HoloversePortal } from '../services/holoServices'
import { isSupabaseConfigured } from '../services/supabaseClient'

interface Props{onClose:()=>void}
type Tab='search'|'ride'|'delivery'|'logistics'|'advertise'|'lingo'|'guardian'|'builder'|'holoverse'
const tabs:Record<Tab,string>={search:'🔎 Holo Search',ride:'🚘 Holo Ride',delivery:'📦 Holo Delivery',logistics:'🚛 Holo Logistics',advertise:'📣 Holo Advertise',lingo:'🌐 Holo Lingo',guardian:'🛡 Holo Guardian',builder:'🧰 Holo Builder',holoverse:'🌀 Holoverse'}

export default function HoloServicesHub({onClose}:Props){
 const [tab,setTab]=useState<Tab>('search'),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[q,setQ]=useState(''),[results,setResults]=useState<HoloSearchDocument[]>([]),[portals,setPortals]=useState<HoloversePortal[]>([])
 const [a,setA]=useState('AI Café Chicago'),[b,setB]=useState('Creator District'),[text,setText]=useState('Welcome to TryAMM'),[locale,setLocale]=useState('es'),[campaign,setCampaign]=useState('Living Worlds Launch'),[builderTitle,setBuilderTitle]=useState('My Holo Experience')
 useEffect(()=>{if(isSupabaseConfigured())listHoloversePortals().then(setPortals).catch(()=>{})},[])
 const btn:React.CSSProperties={background:'#0e2340',border:'1px solid #52e5ff66',color:'#a9f2ff',borderRadius:8,padding:'8px 11px',cursor:'pointer',fontFamily:'monospace'},box:React.CSSProperties={background:'#06101f',border:'1px solid #213b56',borderRadius:12,padding:12},input:React.CSSProperties={width:'100%',background:'#020812',color:'#fff',border:'1px solid #33566f',borderRadius:8,padding:10,fontFamily:'monospace'}
 async function run(fn:()=>Promise<unknown>,success:string){setBusy(true);setMessage('');try{await fn();setMessage(success)}catch(e){setMessage(e instanceof Error?e.message:String(e))}finally{setBusy(false)}}
 return <div style={{position:'fixed',inset:0,zIndex:10090,background:'rgba(1,5,14,.99)',color:'#eefaff',fontFamily:'monospace',overflowY:'auto'}}><div style={{maxWidth:1120,margin:'0 auto',padding:16}}><div style={{display:'flex',gap:12,alignItems:'center'}}><button style={btn} onClick={onClose}>← Back</button><div><h2 style={{margin:0,color:'#52e5ff'}}>HOLO SERVICES CONTROL CENTER</h2><div style={{fontSize:10,color:'#66849a'}}>Search • Mobility • Delivery • Logistics • Advertising • Translation • Safety • Building • Holoverse</div></div></div>{message&&<div style={{...box,marginTop:10,borderColor:'#52e5ff55'}}>{message}</div>}<div style={{display:'flex',gap:6,flexWrap:'wrap',margin:'12px 0'}}>{(Object.keys(tabs) as Tab[]).map(t=><button key={t} style={{...btn,background:t===tab?'#154a5a':'#0e2340'}} onClick={()=>setTab(t)}>{tabs[t]}</button>)}</div>

 {tab==='search'&&<section style={box}><h3>Holo Search</h3><p style={{fontSize:11,color:'#89a5b9'}}>Universal discovery across TryAMM worlds, services, businesses, creators, books, games, learning and eventually geospatial results.</p><input style={input} value={q} onChange={e=>setQ(e.target.value)} placeholder="Search TryAMM..."/><button style={{...btn,marginTop:8}} disabled={busy} onClick={async()=>{setBusy(true);try{setResults(await holoSearch(q))}catch(e){setMessage(e instanceof Error?e.message:String(e))}finally{setBusy(false)}}}>Search</button><div style={{display:'grid',gap:7,marginTop:10}}>{results.map(r=><article style={box} key={r.id}><b>{r.title}</b><div style={{fontSize:10,color:'#52e5ff'}}>{r.source_type} {r.world_slug?`• ${r.world_slug}`:''}</div><p style={{fontSize:11,color:'#aaa'}}>{r.description}</p></article>)}</div></section>}

 {tab==='ride'&&<section style={box}><h3>Holo Ride</h3><p style={{fontSize:11,color:'#89a5b9'}}>Rideshare request/dispatch foundation. Current flow is simulation-only until driver onboarding, maps, insurance, local transportation compliance and live payments are connected.</p><input style={input} value={a} onChange={e=>setA(e.target.value)} placeholder="Pickup"/><br/><br/><input style={input} value={b} onChange={e=>setB(e.target.value)} placeholder="Dropoff"/><button style={{...btn,marginTop:8}} disabled={busy} onClick={()=>run(()=>requestHoloRide(a,b),'Holo Ride simulation request created.')}>Request Ride</button></section>}

 {tab==='delivery'&&<section style={box}><h3>Holo Delivery</h3><p style={{fontSize:11,color:'#89a5b9'}}>Food, marketplace and local-business courier workflow, separated from freight logistics.</p><input style={input} value={a} onChange={e=>setA(e.target.value)} placeholder="Merchant / pickup"/><br/><br/><input style={input} value={b} onChange={e=>setB(e.target.value)} placeholder="Customer / dropoff"/><button style={{...btn,marginTop:8}} disabled={busy} onClick={()=>run(()=>createHoloDelivery('ai-cafe',a,b),'Holo Delivery simulation order created.')}>Create Delivery</button></section>}

 {tab==='logistics'&&<section style={box}><h3>Holo Logistics</h3><p style={{fontSize:11,color:'#89a5b9'}}>Freight, dispatch, warehouse and route-state foundation connected to Workforce training.</p><input style={input} value={a} onChange={e=>setA(e.target.value)} placeholder="Origin"/><br/><br/><input style={input} value={b} onChange={e=>setB(e.target.value)} placeholder="Destination"/><button style={{...btn,marginTop:8}} disabled={busy} onClick={()=>run(()=>createLogisticsJob(a,b),'Holo Logistics freight simulation planned.')}>Plan Freight Job</button></section>}

 {tab==='advertise'&&<section style={box}><h3>Holo Advertise</h3><p style={{fontSize:11,color:'#89a5b9'}}>One campaign model for feed ads, creator/live placements, in-world placements and future AR/holographic inventory. Drafts start with $0 spend so nothing can charge automatically.</p><input style={input} value={campaign} onChange={e=>setCampaign(e.target.value)}/><button style={{...btn,marginTop:8}} disabled={busy} onClick={()=>run(()=>createAdCampaign(campaign),'Draft Holo Advertise campaign created with no spend.')}>Create Draft Campaign</button></section>}

 {tab==='lingo'&&<section style={box}><h3>Holo Lingo</h3><p style={{fontSize:11,color:'#89a5b9'}}>Translation job foundation. Legal, medical, financial and emergency text is automatically held for human review.</p><textarea style={{...input,minHeight:100}} value={text} onChange={e=>setText(e.target.value)}/><input style={{...input,marginTop:8}} value={locale} onChange={e=>setLocale(e.target.value)} placeholder="Target locale e.g. es, fr, am, he"/><button style={{...btn,marginTop:8}} disabled={busy} onClick={()=>run(()=>prepareTranslation(text,locale),'Translation job prepared. High-risk text will require review.')}>Prepare Translation</button></section>}

 {tab==='guardian'&&<section style={box}><h3>Holo Guardian + Holo Access</h3><p style={{fontSize:11,color:'#89a5b9'}}>Guardian is the shared safety/reporting layer. Holo Access remains the platform-wide accessibility profile already connected to the app, with this hub serving as its discovery/control surface.</p><button style={btn} disabled={busy} onClick={()=>run(()=>reportHoloSafetyEvent('user-report','medium',{note:'Test report from Holo Services Hub'}),'Safety event recorded for review.')}>Create Test Safety Report</button><div style={{fontSize:10,color:'#7591a5',marginTop:9}}>Production moderation still needs staffed escalation, youth safety policy enforcement, incident SLAs and jurisdiction-specific procedures.</div></section>}

 {tab==='builder'&&<section style={box}><h3>Holo Builder</h3><p style={{fontSize:11,color:'#89a5b9'}}>Creator foundation for worlds, apps, storefronts, ads, experiences, workflows and agents.</p><input style={input} value={builderTitle} onChange={e=>setBuilderTitle(e.target.value)}/><div style={{display:'flex',gap:6,flexWrap:'wrap',marginTop:8}}>{(['world','app','storefront','ad','experience','workflow','agent'] as const).map(t=><button style={btn} disabled={busy} key={t} onClick={()=>run(()=>createHoloBuilderProject(builderTitle,t),`${t} builder project created.`)}>{t}</button>)}</div></section>}

 {tab==='holoverse'&&<section style={box}><h3>Holoverse Portal Registry</h3><p style={{fontSize:11,color:'#89a5b9'}}>The Holoverse is the gateway joining worlds and Holo services rather than another disconnected app.</p><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(220px,1fr))',gap:8}}>{portals.map(p=><article style={box} key={p.id}><b>{p.name}</b><div style={{fontSize:10,color:'#52e5ff'}}>{p.destination_type} • {p.age_lane}</div><p style={{fontSize:10,color:'#8299a9'}}>destination: {p.destination_key}</p></article>)}</div></section>}
 </div></div>
}
