import { useEffect } from 'react'
import { useGameStore } from '../game/state/useGameStore'

type Props={onClose:()=>void}
type Status='LIVE'|'BETA'|'SANDBOX'|'GATED'
type Launch={icon:string;label:string;description:string;status:Status;open:()=>void}

const invoke=(fn:string)=>{const target=(window as any)[fn];if(typeof target==='function'){target();return true}return false}
const event=(name:string,detail:Record<string,unknown>={})=>window.dispatchEvent(new CustomEvent(name,{detail:{source:'holoverse',...detail}}))

export default function HoloverseHub({onClose}:Props){
  useEffect(()=>{const esc=(e:KeyboardEvent)=>{if(e.key==='Escape')onClose()};window.addEventListener('keydown',esc);return()=>window.removeEventListener('keydown',esc)},[onClose])
  const setScreen=useGameStore(s=>s.setScreen)
  const launches:Launch[]=[
    {icon:'◈',label:'HoloGPT',description:'Unified TRYAMM assistant across worlds and services.',status:'LIVE',open:()=>{if(!invoke('__showHoloGPT'))event('tryamm:open-hologpt')}},
    {icon:'🏙',label:'StreetVerse',description:'Playable living world, missions, businesses, creator commerce and mobility.',status:'BETA',open:()=>{window.location.href='/streetverse'}},
    {icon:'📦',label:'Holo Delivery',description:'Food, packages, local commerce, tracking, proof and logistics handoff.',status:'BETA',open:()=>{if(!invoke('__showHoloDelivery'))event('tryamm:holo-delivery-open')}},
    {icon:'🚘',label:'Holo Ride + Drone',description:'Ride share, car share, delivery, recovery and provider-gated drone/air workflows.',status:'GATED',open:()=>{window.location.href='/holo-ride-share'}},
    {icon:'◈',label:'Holographic Gallery',description:'3D products, art, music, Reels, exhibits and shoppable holographic showrooms.',status:'BETA',open:()=>{if(!invoke('__showHoloGallery'))window.location.href='/holo-gallery'}},
    {icon:'🛍',label:'Holo Marketplace',description:'All American Marketplace with secure checkout and creator commerce.',status:'BETA',open:()=>{if(!invoke('__showHoloMarketplace'))setScreen('marketplace')}},
    {icon:'🧊',label:'Holo Fridge',description:'Home inventory, cold vault, replenishment and verified supplier fulfillment.',status:'BETA',open:()=>{if(!invoke('__showHoloFridge'))window.location.href='/holo-fridge'}},
    {icon:'🧪',label:'Holo Labs',description:'AR/VR, Holo Core, services, immersive worlds, media and sandbox experimentation.',status:'SANDBOX',open:()=>{if(!invoke('__showHoloLab'))window.location.href='/holo-lab'}},
    {icon:'✦',label:'Holo Services',description:'Search, Ride, Delivery, Logistics, Advertising, Lingo, Guardian and Builder.',status:'BETA',open:()=>{if(!invoke('__showHoloServices'))event('tryamm:open-holo-services')}},
    {icon:'◎',label:'Holo Core',description:'Work, wellness, education, creator, analytics, identity and Holo Pay controls.',status:'BETA',open:()=>{if(!invoke('__showHoloCore'))event('tryamm:open-holo-core')}},
    {icon:'♫',label:'Holo Music',description:'Rights-aware music across StreetVerse, vehicles, LIVE, stores and creator media.',status:'BETA',open:()=>{window.location.href='/holo-music'}},
    {icon:'🎬',label:'Holo Drama',description:'Multi-scene stories connected to Reels, products, music and network publishing.',status:'BETA',open:()=>{window.location.href='/holo-drama'}},
    {icon:'👗',label:'Holo Style',description:'Fashion, virtual try-on and creator/store commerce.',status:'BETA',open:()=>{if(!invoke('__showHoloStyle'))event('tryamm:open-holo-style')}},
    {icon:'📱',label:'Holo FON',description:'TRYAMM Connect communications and network control plane.',status:'BETA',open:()=>{if(!invoke('__showHoloFon'))invoke('__showTryAMMConnect')}},
    {icon:'🩺',label:'Holo Care',description:'OmniCare/Holo Care service surface; regulated clinical functions remain provider-gated.',status:'GATED',open:()=>{window.location.href='/omnicare-360'}},
    {icon:'▣',label:'Holo TV + Network',description:'All American Network, Free TV and creator programming.',status:'BETA',open:()=>{window.location.href='/network'}},
    {icon:'🎞',label:'Holo Reels',description:'Capture, edit, publish and connect world moments to creator commerce.',status:'BETA',open:()=>event('tryamm:media-studio-open',{source:'holoverse'})},
    {icon:'📣',label:'Holo Ads',description:'Feed, creator, LIVE, in-world and future AR/holographic advertising drafts.',status:'BETA',open:()=>{if(!invoke('__showHoloServices'))event('tryamm:open-holo-services',{tab:'advertise'})}},
    {icon:'🔭',label:'Quantum Zoom',description:'Inspect connected world information across micro and macro scales.',status:'BETA',open:()=>{if(!invoke('__showQuantumZoom'))event('tryamm:open-quantum-zoom')}},
    {icon:'⏳',label:'Quantum Time',description:'Explore provenance-aware historical and simulated states.',status:'BETA',open:()=>{if(!invoke('__showAdvancedWorlds'))event('tryamm:open-advanced-worlds')}},
    {icon:'🧬',label:'Quantum Sandbox',description:'Experiment without changing authoritative production state.',status:'SANDBOX',open:()=>{if(!invoke('__showQuantumEngine'))event('tryamm:open-quantum-engine')}},
    {icon:'📡',label:'Quantum Network',description:'TRYAMM Connect and network control plane.',status:'BETA',open:()=>{if(!invoke('__showTryAMMConnect'))event('tryamm:open-connect')}},
    {icon:'✦',label:'Command Nexus',description:'Inspect controls, telemetry and readiness across TRYAMM.',status:'BETA',open:()=>{if(!invoke('__showCommandNexus'))event('tryamm:open-command-nexus')}},
  ]  const open=(item:Launch)=>{onClose();setTimeout(item.open,0)}
  return <div role="dialog" aria-label="Holoverse" style={{position:'fixed',inset:0,zIndex:11000,overflowY:'auto',background:'radial-gradient(circle at 50% 0%,#0b3540 0,#08091a 38%,#02030a 78%)',color:'#fff',fontFamily:'Inter,system-ui,sans-serif'}}><div style={{maxWidth:1050,margin:'0 auto',padding:'24px 16px 80px'}}><header style={{display:'flex',alignItems:'center',gap:14,marginBottom:22}}><div style={{flex:1}}><div style={{fontSize:10,letterSpacing:4,color:'#4fe3ff',fontWeight:900}}>TRYAMM · UNIFIED EXPERIENCE</div><h1 style={{margin:'5px 0',fontSize:'clamp(28px,6vw,54px)'}}>HOLOVERSE</h1><div style={{color:'#a9c4d0',maxWidth:720,lineHeight:1.55}}>One operating layer for worlds, mobility, delivery, galleries, creator media, commerce, AI, communications, services and infrastructure.</div></div><button onClick={onClose} aria-label="Close Holoverse" style={{width:44,height:44,borderRadius:'50%',border:'1px solid #4fe3ff66',background:'#07121d',color:'#fff',fontSize:22,cursor:'pointer'}}>×</button></header><div style={{padding:14,border:'1px solid #4fe3ff44',borderRadius:16,background:'#4fe3ff0b',marginBottom:16,lineHeight:1.55,fontSize:12}}><b style={{color:'#78ffb4'}}>CONNECTED HOLOVERSE.</b> Launchers now use real routes, real game realms, existing TRYAMM controls, and event fallbacks instead of dead global function names.</div><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(220px,1fr))',gap:12}}>{launches.map(item=><button key={item.label} onClick={()=>open(item)} style={{minHeight:150,textAlign:'left',padding:16,border:'1px solid #17364a',borderRadius:18,background:'linear-gradient(145deg,#07131e,#0b0b18)',color:'#fff',cursor:'pointer',boxShadow:'0 14px 38px #0006'}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center'}}><span style={{fontSize:28}}>{item.icon}</span><span style={{fontSize:9,fontWeight:950,color:item.status==='LIVE'?'#78ffb4':item.status==='GATED'?'#ff9f7a':item.status==='SANDBOX'?'#c8a6ff':'#e8b944'}}>{item.status}</span></div><div style={{fontSize:16,fontWeight:950,marginTop:15}}>{item.label}</div><div style={{fontSize:11,color:'#91a8b5',lineHeight:1.45,marginTop:7}}>{item.description}</div></button>)}</div><div style={{marginTop:18,fontFamily:'monospace',fontSize:10,color:'#718897'}}>BETA PATH · SIGN IN → PASSPORT → STREETVERSE → MOVE/PLAY → ZOOM → TIME → SANDBOX → POCKET DIMENSION → HOLOGPT → MISSION → XP → REEL → COMMERCE → LEDGER</div></div></div>
}
