import { useEffect, useRef, useState } from 'react'
import { useGameStore } from '../game/state/useGameStore'
import { getAuthenticatedUserId, isSupabaseConfigured } from '../services/supabaseClient'
import HoloGPTAssistant from './HoloGPTAssistant'
import HoloDirectLaunchBridge from './HoloDirectLaunchBridge'
import HoloMusicStreaming from './HoloMusicStreaming'
import CommandNexusControlPlane from './CommandNexusControlPlane'
import XRCommandGateway from './XRCommandGateway'
import HoloLabGateway from './HoloLabGateway'
import BookClubCenter from './BookClubCenter'
import LivingStoryMissionCenter from './LivingStoryMissionCenter'
import MovieStudioCenter from './MovieStudioCenter'
import MiddleverseAIHub from './MiddleverseAIHub'
import RouteCoordinator from '../navigation/RouteCoordinator'
import { enterWorld, getActiveWorldSession, getOrCreateWorldProfile, listWorlds, saveWorldSessionState, type WorldRecord, type WorldSession } from '../services/livingWorlds'
function screenForWorld(world: WorldRecord): string | undefined { const value=world.metadata?.screen; return typeof value==='string'?value:undefined }
export default function LivingWorldsBridge(){
 const screen=useGameStore(s=>s.screen),player=useGameStore(s=>s.player),sessionRef=useRef<WorldSession|null>(null),worldsRef=useRef<WorldRecord[]>([]),readyRef=useRef(false)
 const[showNexusV2,setShowNexusV2]=useState(false),[showHoloMusic,setShowHoloMusic]=useState(false),[showXR,setShowXR]=useState(false),[showHoloLab,setShowHoloLab]=useState(false),[showBookClub,setShowBookClub]=useState(false),[showLivingStory,setShowLivingStory]=useState(false),[showMovieStudio,setShowMovieStudio]=useState(false),[showMiddleverseAI,setShowMiddleverseAI]=useState(false)
 const signedIn=screen!=='intro'&&screen!=='login'
 useEffect(()=>{const openNexus=()=>setShowNexusV2(true),openMusic=()=>setShowHoloMusic(true),openXR=()=>setShowXR(true),openLab=()=>setShowHoloLab(true),openBookClub=()=>setShowBookClub(true),openLivingStory=()=>setShowLivingStory(true),openMovieStudio=()=>setShowMovieStudio(true),openMiddleverseAI=()=>setShowMiddleverseAI(true);Object.assign(window,{__showCommandNexusV2:openNexus,__showHoloMusic:openMusic,__showXR:openXR,__showHoloLab:openLab,__showBookClub:openBookClub,__showLivingStory:openLivingStory,__showMovieStudio:openMovieStudio,__showMiddleverseWorkstation:openMiddleverseAI,__showMiddleverseAI:openMiddleverseAI});const events=[['tryamm:open-command-nexus-v2',openNexus],['tryamm:open-holo-music',openMusic],['tryamm:open-xr',openXR],['tryamm:open-holo-lab',openLab],['tryamm:open-book-club',openBookClub],['tryamm:open-living-story',openLivingStory],['tryamm:open-movie-studio',openMovieStudio],['tryamm:open-middleverse-ai',openMiddleverseAI]] as const;events.forEach(([e,f])=>window.addEventListener(e,f));return()=>events.forEach(([e,f])=>window.removeEventListener(e,f))},[])
 useEffect(()=>{if(!signedIn){readyRef.current=false;sessionRef.current=null;return}let cancelled=false;(async()=>{if(!isSupabaseConfigured())return;const userId=await getAuthenticatedUserId();if(!userId)return;try{await getOrCreateWorldProfile({avatar_name:player.name||'Traveler',level:player.level,xp:player.xp,reputation:player.rep,skills:{faith:player.faith}});const[worlds,active]=await Promise.all([listWorlds(),getActiveWorldSession()]);if(cancelled)return;worldsRef.current=worlds;sessionRef.current=active;readyRef.current=true;const persistedScreen=active?.state?.screen,valid=['city','sports','marketplace','music','faith','blockchain'];if(typeof persistedScreen==='string'&&valid.includes(persistedScreen)&&persistedScreen!==useGameStore.getState().screen)useGameStore.getState().setScreen(persistedScreen as any)}catch(error){console.warn('[LivingWorlds] bootstrap skipped:',error)}})();return()=>{cancelled=true}// eslint-disable-next-line react-hooks/exhaustive-deps
 },[signedIn])
 useEffect(()=>{if(!signedIn||!readyRef.current)return;let cancelled=false;(async()=>{try{const worlds=worldsRef.current,target=worlds.find(w=>screenForWorld(w)===screen)||worlds.find(w=>w.slug==='my-world');if(!target||cancelled)return;const state={screen,player:{level:player.level,xp:player.xp,reputation:player.rep,faith:player.faith,activeVehicle:player.activeVehicle},savedAt:new Date().toISOString()};if(sessionRef.current?.world_id===target.id)await saveWorldSessionState(sessionRef.current.id,state);else sessionRef.current=await enterWorld(target,state)}catch(error){console.warn('[LivingWorlds] persistence skipped:',error)}})();return()=>{cancelled=true}},[signedIn,screen,player.level,player.xp,player.rep,player.faith,player.activeVehicle])
 return <><RouteCoordinator/><HoloGPTAssistant/><HoloDirectLaunchBridge/>{signedIn&&<><button aria-label="Open Living Story Missions" onClick={()=>setShowLivingStory(true)}>★ MISSIONS</button><button aria-label="Open AR VR Mixed Reality" onClick={()=>setShowXR(true)}>XR · AR/VR</button><button aria-label="Open Movie Studio" onClick={()=>setShowMovieStudio(true)}>🎬 MOVIE</button><button aria-label="Open Middleverse AI" onClick={()=>setShowMiddleverseAI(true)}>∞ MIDDLEVERSE AI</button></>}{showNexusV2&&<CommandNexusControlPlane onClose={()=>setShowNexusV2(false)}/>} {showHoloMusic&&<HoloMusicStreaming onClose={()=>setShowHoloMusic(false)}/>} {showXR&&<XRCommandGateway onClose={()=>setShowXR(false)}/>} {showHoloLab&&<HoloLabGateway onClose={()=>setShowHoloLab(false)}/>} {showBookClub&&<BookClubCenter onClose={()=>setShowBookClub(false)}/>} {showLivingStory&&<LivingStoryMissionCenter onClose={()=>setShowLivingStory(false)}/>} {showMovieStudio&&<MovieStudioCenter onClose={()=>setShowMovieStudio(false)}/>} {showMiddleverseAI&&<MiddleverseAIHub onClose={()=>setShowMiddleverseAI(false)}/>}</>
}
