import { ChangeEvent, useEffect, useMemo, useRef, useState } from 'react'
import { getAccessToken } from '../services/supabaseClient'

type Destination='reel'|'omnibox'|'all-american-network'|'servants-of-christ-network'|'creator-profile'
type Draft={id:string;title:string;caption:string;destinations:Destination[];createdAt:string;source:string;status:'draft'|'queued';mediaId?:string;jobId?:string}

const DRAFT_KEY='tryamm.media-studio.drafts.v2'
const DESTINATIONS:{id:Destination;label:string}[]=[
  {id:'reel',label:'TRYAMM Reels'},
  {id:'omnibox',label:'Omni Box'},
  {id:'all-american-network',label:'All American Network'},
  {id:'servants-of-christ-network',label:'Servants of Christ Network'},
  {id:'creator-profile',label:'Creator Profile'},
]
const API=(import.meta as any).env?.VITE_API_URL??''

function readDrafts():Draft[]{try{return JSON.parse(localStorage.getItem(DRAFT_KEY)||'[]')}catch{return []}}
async function apiJson(path:string,token:string,options:RequestInit={}){
  const response=await fetch(`${API}${path}`,{...options,headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`,...(options.headers||{})}})
  const data=await response.json().catch(()=>({}))
  if(!response.ok)throw new Error(data?.error||`TRYAMM media request failed (${response.status})`)
  return data
}
function waitFor(video:HTMLVideoElement,event:string){return new Promise<void>((resolve,reject)=>{const done=()=>{cleanup();resolve()},fail=()=>{cleanup();reject(new Error('Media could not be loaded for rendering.'))},cleanup=()=>{video.removeEventListener(event,done);video.removeEventListener('error',fail)};video.addEventListener(event,done,{once:true});video.addEventListener('error',fail,{once:true})})}
function outputMime(){const candidates=['video/mp4;codecs=h264,aac','video/mp4','video/webm;codecs=vp9','video/webm'];return candidates.find(type=>typeof MediaRecorder!=='undefined'&&MediaRecorder.isTypeSupported(type))||''}
function drawBackground(ctx:CanvasRenderingContext2D,w:number,h:number,background:'city'|'gold'|'void'){
  const gradient=ctx.createLinearGradient(0,0,w,h)
  if(background==='gold'){gradient.addColorStop(0,'#f0c95c');gradient.addColorStop(.5,'#73480b');gradient.addColorStop(1,'#160d03')}
  else if(background==='city'){gradient.addColorStop(0,'#061e2c');gradient.addColorStop(.55,'#17233e');gradient.addColorStop(1,'#321532')}
  else{gradient.addColorStop(0,'#182a3b');gradient.addColorStop(.7,'#02050b');gradient.addColorStop(1,'#000')}
  ctx.fillStyle=gradient;ctx.fillRect(0,0,w,h)
}
function drawContain(ctx:CanvasRenderingContext2D,source:CanvasImageSource,sw:number,sh:number,w:number,h:number){const scale=Math.min(w/sw,h/sh),dw=sw*scale,dh=sh*scale,dx=(w-dw)/2,dy=(h-dh)/2;ctx.drawImage(source,dx,dy,dw,dh)}
function drawOverlay(ctx:CanvasRenderingContext2D,w:number,h:number,sticker:string,caption:string,phase=0){
  ctx.save();ctx.textAlign='center';ctx.textBaseline='middle';ctx.font='72px system-ui';ctx.shadowColor='rgba(0,0,0,.8)';ctx.shadowBlur=20;ctx.fillText(sticker,w*.82,h*.16+Math.sin(phase)*8);ctx.restore()
  const text=(caption||'Made in TRYAMM').trim();ctx.save();ctx.font='700 32px system-ui';ctx.textAlign='center';ctx.textBaseline='bottom';const max=w-80,words=text.split(/\s+/);let line='',lines:string[]=[];for(const word of words){const test=line?`${line} ${word}`:word;if(ctx.measureText(test).width>max&&line){lines.push(line);line=word}else line=test}if(line)lines.push(line);lines=lines.slice(-3);const blockH=lines.length*42+28;ctx.fillStyle='rgba(0,0,0,.58)';ctx.fillRect(20,h-blockH-20,w-40,blockH);ctx.fillStyle='#fff';ctx.shadowColor='#000';ctx.shadowBlur=8;lines.forEach((value,index)=>ctx.fillText(value,w/2,h-42-(lines.length-1-index)*42));ctx.restore()
}

export default function MediaStudioLauncher(){
  const [open,setOpen]=useState(false)
  const [tab,setTab]=useState<'capture'|'compose'|'green'|'publish'>('capture')
  const [title,setTitle]=useState('StreetVerse Highlight')
  const [caption,setCaption]=useState('First Drop • Made inside TRYAMM')
  const [destinations,setDestinations]=useState<Destination[]>(['reel','omnibox','creator-profile'])
  const [mediaUrl,setMediaUrl]=useState('')
  const [mediaKind,setMediaKind]=useState<'video'|'image'>('video')
  const [mediaBlob,setMediaBlob]=useState<Blob|null>(null)
  const [mediaFileName,setMediaFileName]=useState('streetverse-highlight.webm')
  const [renderedBlob,setRenderedBlob]=useState<Blob|null>(null)
  const [renderedFileName,setRenderedFileName]=useState('streetverse-final.mp4')
  const [recording,setRecording]=useState(false)
  const [rendering,setRendering]=useState(false)
  const [publishing,setPublishing]=useState(false)
  const [message,setMessage]=useState('Capture gameplay, upload media, add effects, render the final Reel, then save it to your phone or publish it.')
  const [chromaEnabled,setChromaEnabled]=useState(false)
  const [threshold,setThreshold]=useState(90)
  const [background,setBackground]=useState<'city'|'gold'|'void'>('city')
  const [sticker,setSticker]=useState('🔥')
  const [drafts,setDrafts]=useState<Draft[]>(()=>readDrafts())
  const recorderRef=useRef<MediaRecorder|null>(null)
  const chunksRef=useRef<Blob[]>([])
  const sourceVideoRef=useRef<HTMLVideoElement|null>(null)
  const canvasRef=useRef<HTMLCanvasElement|null>(null)

  useEffect(()=>{const openStudio=(event:Event)=>{const detail=(event as CustomEvent<{source?:string}>).detail;if(detail?.source==='streetverse'){setTitle('StreetVerse: First Drop Highlight');setCaption('Mission moment captured in StreetVerse • #TRYAMM #StreetVerse')}setOpen(true);setTab('capture')};(window as any).__showMediaStudio=()=>setOpen(true);window.addEventListener('tryamm:media-studio-open',openStudio);return()=>{window.removeEventListener('tryamm:media-studio-open',openStudio);delete (window as any).__showMediaStudio}},[])
  useEffect(()=>{if(!chromaEnabled||!mediaUrl||mediaKind!=='video')return;let raf=0;const draw=()=>{const video=sourceVideoRef.current,canvas=canvasRef.current;if(video&&canvas&&video.readyState>=2){const ctx=canvas.getContext('2d',{willReadFrequently:true});if(ctx){const w=canvas.width=640,h=canvas.height=360;ctx.drawImage(video,0,0,w,h);const frame=ctx.getImageData(0,0,w,h),d=frame.data;for(let i=0;i<d.length;i+=4){const r=d[i],g=d[i+1],b=d[i+2];if(g-Math.max(r,b)>threshold)d[i+3]=0}ctx.putImageData(frame,0,0)}}raf=requestAnimationFrame(draw)};raf=requestAnimationFrame(draw);return()=>cancelAnimationFrame(raf)},[chromaEnabled,mediaUrl,mediaKind,threshold])

  const bgStyle=useMemo(()=>background==='city'?'linear-gradient(135deg,#061e2c,#17233e 55%,#321532)':background==='gold'?'radial-gradient(circle at 50% 25%,#ffe58a,#8a5b11 50%,#160d03)':'radial-gradient(circle at 50% 20%,#182a3b,#02050b 65%)',[background])

  function loadBlob(blob:Blob,name:string){if(mediaUrl.startsWith('blob:'))URL.revokeObjectURL(mediaUrl);const url=URL.createObjectURL(blob);setMediaBlob(blob);setRenderedBlob(null);setMediaFileName(name);setMediaUrl(url);setMediaKind(blob.type.startsWith('image/')?'image':'video');setTab('compose')}
  async function startCapture(){try{if(!navigator.mediaDevices?.getDisplayMedia||typeof MediaRecorder==='undefined'){setMessage('This browser cannot capture the screen directly. On iPhone, use Control Center Screen Recording, then upload the saved clip here.');return}const stream=await navigator.mediaDevices.getDisplayMedia({video:true,audio:true}),recorder=new MediaRecorder(stream);recorderRef.current=recorder;chunksRef.current=[];recorder.ondataavailable=e=>{if(e.data.size)chunksRef.current.push(e.data)};recorder.onstop=()=>{const type=recorder.mimeType||'video/webm',blob=new Blob(chunksRef.current,{type});loadBlob(blob,`streetverse-${Date.now()}.${type.includes('mp4')?'mp4':'webm'}`);setRecording(false);stream.getTracks().forEach(t=>t.stop());setMessage('Capture ready. Add effects, render the final Reel, then save it to your phone.')};stream.getVideoTracks()[0]?.addEventListener('ended',()=>{if(recorder.state!=='inactive')recorder.stop()});recorder.start(500);setRecording(true);setMessage('Recording your selected screen/window. Stop when the highlight is finished.')}catch(error){setMessage(error instanceof Error?error.message:'Capture was cancelled.')}}
  function stopCapture(){const recorder=recorderRef.current;if(recorder&&recorder.state!=='inactive')recorder.stop()}
  function uploadMedia(event:ChangeEvent<HTMLInputElement>){const file=event.target.files?.[0];if(!file)return;loadBlob(file,file.name);setMessage(`${file.name} loaded. Add effects, then tap RENDER FINAL REEL.`)}
  function toggleDestination(id:Destination){setDestinations(current=>current.includes(id)?current.filter(x=>x!==id):[...current,id])}

  async function renderFinal(){
    if(!mediaBlob||!mediaUrl){setMessage('Add or capture media before rendering.');return}
    setRendering(true);setMessage('Rendering your final StreetVerse Reel with caption, sticker and background effects…')
    try{
      const w=720,h=1280,canvas=document.createElement('canvas');canvas.width=w;canvas.height=h;const ctx=canvas.getContext('2d',{willReadFrequently:true});if(!ctx)throw new Error('Canvas rendering is unavailable in this browser.')
      if(mediaKind==='image'){
        const image=new Image();image.src=mediaUrl;await new Promise<void>((resolve,reject)=>{image.onload=()=>resolve();image.onerror=()=>reject(new Error('Image could not be rendered.'))});drawBackground(ctx,w,h,background);drawContain(ctx,image,image.naturalWidth||w,image.naturalHeight||h,w,h);drawOverlay(ctx,w,h,sticker,caption);const blob=await new Promise<Blob>((resolve,reject)=>canvas.toBlob(value=>value?resolve(value):reject(new Error('Image export failed.')),'image/png'));setRenderedBlob(blob);setRenderedFileName(`tryamm-${Date.now()}.png`);setMessage('Final image rendered. Tap SAVE TO PHONE to open the phone share/save sheet.');return
      }
      const streamFactory=(canvas as HTMLCanvasElement & {captureStream?:(fps?:number)=>MediaStream}).captureStream;if(!streamFactory||typeof MediaRecorder==='undefined')throw new Error('This browser cannot render edited video in-page. You can still use SAVE ORIGINAL TO PHONE, or open TRYAMM in a browser with canvas video export support.')
      const video=document.createElement('video');video.src=mediaUrl;video.muted=true;video.playsInline=true;video.preload='auto';if(video.readyState<1)await waitFor(video,'loadedmetadata');const duration=Number.isFinite(video.duration)&&video.duration>0?video.duration:30;const renderStream=streamFactory.call(canvas,30);const capture=(video as HTMLVideoElement & {captureStream?:()=>MediaStream}).captureStream?.();capture?.getAudioTracks().forEach(track=>renderStream.addTrack(track));const mime=outputMime(),recorder=mime?new MediaRecorder(renderStream,{mimeType:mime,videoBitsPerSecond:5_000_000}):new MediaRecorder(renderStream,{videoBitsPerSecond:5_000_000}),chunks:BlobPart[]=[];recorder.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};const stopped=new Promise<void>((resolve,reject)=>{recorder.onstop=()=>resolve();recorder.onerror=()=>reject(new Error('Final video encoder failed.'))});recorder.start(500);video.currentTime=0;await video.play();const temp=document.createElement('canvas');temp.width=w;temp.height=h;const tctx=temp.getContext('2d',{willReadFrequently:true});if(!tctx)throw new Error('Video effects canvas is unavailable.');const started=performance.now();await new Promise<void>(resolve=>{const frame=()=>{drawBackground(ctx,w,h,background);const sw=video.videoWidth||w,sh=video.videoHeight||h;if(chromaEnabled){tctx.clearRect(0,0,w,h);drawContain(tctx,video,sw,sh,w,h);const img=tctx.getImageData(0,0,w,h),d=img.data;for(let i=0;i<d.length;i+=4){const r=d[i],g=d[i+1],b=d[i+2];if(g-Math.max(r,b)>threshold)d[i+3]=0}tctx.putImageData(img,0,0);ctx.drawImage(temp,0,0)}else drawContain(ctx,video,sw,sh,w,h);drawOverlay(ctx,w,h,sticker,caption,(performance.now()-started)/280);if(video.ended||video.currentTime>=duration-.05)return resolve();requestAnimationFrame(frame)};requestAnimationFrame(frame)});video.pause();if(recorder.state!=='inactive')recorder.stop();await stopped;renderStream.getTracks().forEach(track=>track.stop());const finalType=recorder.mimeType||mime||'video/webm',blob=new Blob(chunks,{type:finalType});if(!blob.size)throw new Error('The final render produced an empty file.');setRenderedBlob(blob);setRenderedFileName(`tryamm-streetverse-${Date.now()}.${finalType.includes('mp4')?'mp4':'webm'}`);setMessage(capture?.getAudioTracks().length?'Final Reel rendered with supported source audio. Tap SAVE TO PHONE.':'Final Reel rendered. This browser did not expose source audio to the renderer, so the exported Reel may be silent. Tap SAVE TO PHONE.')
    }catch(error){setMessage(error instanceof Error?error.message:'Final render failed.')}
    finally{setRendering(false)}
  }

  async function saveToPhone(){
    const blob=renderedBlob||mediaBlob;if(!blob){setMessage('Add media first.');return}const name=renderedBlob?renderedFileName:mediaFileName,file=new File([blob],name,{type:blob.type||'application/octet-stream'}),nav=navigator as Navigator & {canShare?:(data:ShareData)=>boolean}
    try{if(navigator.share&&(!nav.canShare||nav.canShare({files:[file]}))){await navigator.share({files:[file],title:title||'TRYAMM StreetVerse Reel',text:'Made in TRYAMM'});setMessage('Phone share/save sheet opened. On iPhone choose Save Video for a movie or Save to Files.');return}}catch(error){if(error instanceof DOMException&&error.name==='AbortError'){setMessage('Save/share was cancelled.');return}}
    const url=URL.createObjectURL(blob),anchor=document.createElement('a');anchor.href=url;anchor.download=name;anchor.rel='noopener';document.body.appendChild(anchor);anchor.click();anchor.remove();setTimeout(()=>URL.revokeObjectURL(url),30_000);setMessage('Download started. Check your browser Downloads or Files app.')
  }

  async function publishProduction(){
    const publishBlob=renderedBlob||mediaBlob,publishName=renderedBlob?renderedFileName:mediaFileName;if(!publishBlob){setMessage('Add or capture media before publishing.');return}if(!destinations.length){setMessage('Choose at least one publishing destination.');return}setPublishing(true)
    try{const token=await getAccessToken();if(!token)throw new Error('Secure cloud sign-in is required before a Reel or Omni Box release can be published.');setMessage('1/4 Creating secure production upload…');const intent=await apiJson('/api/media/upload-intent',token,{method:'POST',body:JSON.stringify({fileName:publishName,contentType:publishBlob.type||'video/webm',sizeBytes:publishBlob.size,title:title.trim()||'Untitled TRYAMM Media',caption,composition:{chromaEnabled,threshold,background,sticker,rendered:Boolean(renderedBlob)}})});setMessage('2/4 Uploading media to private TRYAMM creator storage…');const uploadResponse=await fetch(intent.upload.url,{method:'PUT',headers:{'Content-Type':publishBlob.type||'video/webm','cache-control':'3600','x-upsert':'false'},body:publishBlob});if(!uploadResponse.ok){const text=await uploadResponse.text();throw new Error(`Media upload failed (${uploadResponse.status}) ${text.slice(0,160)}`)}setMessage('3/4 Verifying the stored asset and media-processing state…');await apiJson('/api/media/upload-complete',token,{method:'POST',body:JSON.stringify({mediaId:intent.media.id})});setMessage('4/4 Queuing Reel / Omni Box delivery…');const released=await apiJson('/api/media/publish',token,{method:'POST',body:JSON.stringify({mediaId:intent.media.id,destinations})});const draft:Draft={id:`media_${Date.now()}`,title:title.trim()||'Untitled TRYAMM Media',caption:caption.trim(),destinations,createdAt:new Date().toISOString(),source:'media-studio-production',status:'queued',mediaId:intent.media.id,jobId:released.job?.id};const next=[draft,...drafts].slice(0,30);setDrafts(next);localStorage.setItem(DRAFT_KEY,JSON.stringify(next));window.dispatchEvent(new CustomEvent('tryamm:media-publish-queued',{detail:draft}));setMessage(`Production upload verified. ${destinations.join(', ')} publishing job ${released.job?.id||''} is queued for moderation/delivery.`);setTab('publish')}catch(error){setMessage(error instanceof Error?error.message:'Production publishing failed.')}finally{setPublishing(false)}
  }

  if(!open)return <button type="button" onClick={()=>setOpen(true)} aria-label="Open TRYAMM Reel and Omni Box studio" style={{position:'fixed',right:12,bottom:74,zIndex:8994,border:'1px solid #e8b94499',borderRadius:999,padding:'10px 14px',background:'linear-gradient(135deg,#21170a,#191020)',color:'#ffe08a',fontSize:10,fontWeight:950,letterSpacing:1,cursor:'pointer'}}>🎬 CREATE REEL</button>

  return <div role="dialog" aria-label="TRYAMM Media Studio" style={{position:'fixed',inset:0,zIndex:15000,background:'#02050bf5',color:'#fff',overflow:'auto',fontFamily:'Inter,system-ui,sans-serif'}}><div style={{maxWidth:1100,margin:'0 auto',padding:'18px 14px 80px'}}><header style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:14,marginBottom:14}}><div><div style={{fontSize:10,fontWeight:950,letterSpacing:3,color:'#4FE3FF'}}>TRYAMM CREATOR MEDIA • PHONE EXPORT ENABLED</div><h1 style={{margin:'5px 0 0'}}>Reel Composer + Omni Box Studio</h1></div><button onClick={()=>setOpen(false)} aria-label="Close media studio" style={roundButton}>×</button></header><nav style={{display:'flex',gap:8,flexWrap:'wrap',marginBottom:14}}>{(['capture','compose','green','publish'] as const).map(x=><button key={x} onClick={()=>setTab(x)} style={{...chip,background:tab===x?'#13364a':'#0a121d',color:tab===x?'#4FE3FF':'#b7c4d1'}}>{x==='green'?'GREEN SCREEN':x.toUpperCase()}</button>)}</nav><div style={{display:'grid',gridTemplateColumns:'minmax(0,1fr) 320px',gap:14}} className="media-grid"><section style={{border:'1px solid #29445d',borderRadius:20,background:'#07101a',padding:14,minHeight:460}}>
    {tab==='capture'&&<div style={{display:'grid',gap:14}}><h2 style={{margin:0}}>StreetVerse Clip Capture</h2><p style={muted}>Record a game window or upload an existing MP4, WebM, GIF, JPEG, PNG or WebP. On iPhone, use Control Center Screen Recording while playing StreetVerse, then upload that saved clip here.</p><div style={{display:'flex',gap:10,flexWrap:'wrap'}}>{!recording?<button onClick={startCapture} style={primary}>● START SCREEN CAPTURE</button>:<button onClick={stopCapture} style={{...primary,background:'#8f2237'}}>■ STOP CAPTURE</button>}<label style={{...secondary,cursor:'pointer'}}>UPLOAD CLIP / GIF / IMAGE<input type="file" accept="video/mp4,video/webm,image/jpeg,image/png,image/webp,image/gif,.gif" onChange={uploadMedia} style={{display:'none'}}/></label></div><div style={notice}>Play → Record → Import → Compose → Render Final → Save to Phone → Optional Reel / Omni Box publish.</div></div>}
    {tab==='compose'&&<div style={{display:'grid',gap:12}}><h2 style={{margin:0}}>Reel Composer</h2><div style={{position:'relative',minHeight:330,borderRadius:18,overflow:'hidden',display:'grid',placeItems:'center',background:bgStyle,border:'1px solid #2d455b'}}>{mediaUrl?(mediaKind==='video'?<video ref={sourceVideoRef} src={mediaUrl} controls loop playsInline style={{maxWidth:'100%',maxHeight:420,opacity:chromaEnabled?0:1}}/>:<img src={mediaUrl} alt="Uploaded creator media" style={{maxWidth:'100%',maxHeight:420}}/>):<div style={muted}>Capture or upload media to begin.</div>}{chromaEnabled&&mediaKind==='video'&&<canvas ref={canvasRef} style={{position:'absolute',inset:0,width:'100%',height:'100%',objectFit:'contain'}}/>}<div aria-label="animated sticker layer" style={{position:'absolute',right:'9%',top:'10%',fontSize:58,filter:'drop-shadow(0 8px 18px #000)',animation:'tryammSticker 1.2s ease-in-out infinite alternate'}}>{sticker}</div><div style={{position:'absolute',left:16,bottom:14,right:16,fontWeight:950,textShadow:'0 2px 10px #000'}}>{caption}</div></div><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:10}}><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Title" style={input}/><input value={caption} onChange={e=>setCaption(e.target.value)} placeholder="Caption" style={input}/></div><div style={{display:'flex',gap:8,flexWrap:'wrap'}}>{['🔥','👑','🎮','🎤','✨','🦁','🙏'].map(x=><button key={x} onClick={()=>setSticker(x)} style={chip}>{x}</button>)}<button onClick={()=>setTab('green')} style={secondary}>GREEN SCREEN</button><button disabled={rendering||!mediaBlob} onClick={renderFinal} style={{...primary,opacity:(rendering||!mediaBlob)?0.55:1}}>{rendering?'RENDERING…':'RENDER FINAL REEL'}</button><button disabled={!mediaBlob} onClick={saveToPhone} style={{...secondary,opacity:!mediaBlob?0.55:1}}>⬇ SAVE TO PHONE</button><button onClick={()=>setTab('publish')} style={secondary}>PUBLISH OPTIONS</button></div></div>}
    {tab==='green'&&<div style={{display:'grid',gap:14}}><h2 style={{margin:0}}>Green Screen / Background Replacement</h2><p style={muted}>Chroma-key preview removes green-dominant pixels. RENDER FINAL REEL burns the selected background, sticker and caption into the exported file when the browser supports in-page video rendering.</p><label style={{display:'flex',gap:10,alignItems:'center'}}><input type="checkbox" checked={chromaEnabled} onChange={e=>setChromaEnabled(e.target.checked)}/> Enable chroma key</label><label>Green threshold: {threshold}<input type="range" min="25" max="180" value={threshold} onChange={e=>setThreshold(Number(e.target.value))} style={{width:'100%'}}/></label><div style={{display:'flex',gap:8,flexWrap:'wrap'}}>{(['city','gold','void'] as const).map(x=><button key={x} onClick={()=>setBackground(x)} style={{...chip,outline:background===x?'2px solid #4FE3FF':'none'}}>{x.toUpperCase()} BACKGROUND</button>)}</div><button onClick={()=>setTab('compose')} style={primary}>BACK TO COMPOSER</button></div>}
    {tab==='publish'&&<div style={{display:'grid',gap:14}}><h2 style={{margin:0}}>Save + Omni Box Publishing</h2><p style={muted}>Save the final edit locally first, or publish the rendered output directly to private TRYAMM creator storage and durable destination jobs.</p><div style={{display:'flex',gap:8,flexWrap:'wrap'}}><button disabled={rendering||!mediaBlob} onClick={renderFinal} style={{...secondary,opacity:(rendering||!mediaBlob)?0.55:1}}>{rendering?'RENDERING…':'RENDER FINAL'}</button><button disabled={!mediaBlob} onClick={saveToPhone} style={{...primary,opacity:!mediaBlob?0.55:1}}>⬇ SAVE TO PHONE / FILES</button></div><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(190px,1fr))',gap:8}}>{DESTINATIONS.map(d=><label key={d.id} style={{display:'flex',gap:9,padding:12,border:'1px solid #2d455b',borderRadius:12,background:'#09131f'}}><input type="checkbox" checked={destinations.includes(d.id)} onChange={()=>toggleDestination(d.id)}/>{d.label}</label>)}</div><button disabled={publishing} onClick={publishProduction} style={{...primary,opacity:publishing?0.6:1}}>{publishing?'PUBLISHING…':'UPLOAD + QUEUE REEL / OMNI BOX RELEASE'}</button><div style={notice}>Publishing uses the rendered final file when available; otherwise it uses the imported/captured source. Phone saving never requires a TRYAMM publish.</div></div>}
  </section><aside style={{display:'grid',gap:10,alignContent:'start'}}><div style={panel}><b>PHONE CREATOR LOOP</b><div style={muted}>StreetVerse → iPhone Screen Recording → Import → Effects → Render → Save Video/Files → Share/Post → Omni Box</div></div><div style={panel}><b>EXPORT STATUS</b><div style={{fontSize:11,lineHeight:1.7,marginTop:8}}>Source loaded: {mediaBlob?'yes':'no'}<br/>Final render: {renderedBlob?'ready':'not rendered'}<br/>Save/share: Web Share + download fallback<br/>Private creator storage: connected<br/>Omni Box queue: connected</div></div><div style={panel}><b>RECENT RELEASES</b><div style={{fontSize:11,color:'#9fb2c8',marginTop:8}}>{drafts.length?drafts.slice(0,5).map(d=><div key={d.id} style={{padding:'8px 0',borderBottom:'1px solid #1d2c3b'}}>{d.title}<br/><span style={{fontSize:9}}>{d.destinations.join(' • ')}{d.jobId?` • ${d.jobId.slice(0,12)}`:''}</span></div>):'No production releases queued yet.'}</div></div><div aria-live="polite" style={notice}>{message}</div></aside></div></div><style>{`@media(max-width:820px){.media-grid{grid-template-columns:1fr!important}} @keyframes tryammSticker{from{transform:translateY(0) rotate(-3deg) scale(1)}to{transform:translateY(-10px) rotate(3deg) scale(1.08)}}`}</style></div>
}

const roundButton:React.CSSProperties={width:44,height:44,borderRadius:'50%',border:'1px solid #3d536c',background:'#0c1520',color:'#fff',fontSize:22}
const chip:React.CSSProperties={border:'1px solid #31485e',borderRadius:999,padding:'9px 12px',background:'#0b1520',color:'#fff',fontSize:10,fontWeight:900}
const primary:React.CSSProperties={border:0,borderRadius:12,padding:'12px 14px',background:'linear-gradient(135deg,#4FE3FF,#7398ff)',color:'#04111a',fontWeight:950}
const secondary:React.CSSProperties={border:'1px solid #3b536b',borderRadius:12,padding:'11px 13px',background:'#101a25',color:'#fff',fontWeight:900,fontSize:11}
const input:React.CSSProperties={border:'1px solid #33495e',borderRadius:11,padding:11,background:'#07101a',color:'#fff'}
const muted:React.CSSProperties={fontSize:12,color:'#9fb2c8',lineHeight:1.6}
const panel:React.CSSProperties={padding:14,border:'1px solid #294058',borderRadius:16,background:'#08111c'}
const notice:React.CSSProperties={padding:12,border:'1px solid #3b3652',borderRadius:13,background:'#100d19',fontSize:11,color:'#c5c8d7',lineHeight:1.55}
