import { useEffect, useMemo, useRef, useState } from 'react'

type Scene={id:string;name:string;world:string;shot:string;notes:string;createdAt:string;clipUrl?:string}
type Project={id:string;title:string;scenes:Scene[];updatedAt:string}
const PROJECT_KEY='tryamm.movie.project.v1'

function loadProject():Project{try{const raw=localStorage.getItem(PROJECT_KEY);if(raw)return JSON.parse(raw)}catch{};return{id:'movie-1',title:'My TRYAMM Movie',scenes:[],updatedAt:new Date().toISOString()}}
function saveProject(project:Project){localStorage.setItem(PROJECT_KEY,JSON.stringify({...project,updatedAt:new Date().toISOString()}))}

export default function MovieMakerHub(){
 const [open,setOpen]=useState(false),[project,setProject]=useState<Project>(()=>loadProject()),[world,setWorld]=useState('StreetVerse Chicago'),[shot,setShot]=useState('Wide establishing shot'),[notes,setNotes]=useState(''),[recording,setRecording]=useState(false),[clipUrl,setClipUrl]=useState<string|null>(null),[status,setStatus]=useState('READY')
 const recorderRef=useRef<MediaRecorder|null>(null),streamRef=useRef<MediaStream|null>(null),chunksRef=useRef<Blob[]>([])
 useEffect(()=>{const show=()=>{setProject(loadProject());setOpen(true)};window.addEventListener('tryamm:movie-studio-open',show);return()=>window.removeEventListener('tryamm:movie-studio-open',show)},[])
 const scenes=project.scenes
 const canRecord=typeof navigator!=='undefined'&&!!navigator.mediaDevices&&typeof MediaRecorder!=='undefined'
 const startRecording=async()=>{try{const display=await navigator.mediaDevices.getDisplayMedia({video:true,audio:true});let combined=display;try{const mic=await navigator.mediaDevices.getUserMedia({audio:true});combined=new MediaStream([...display.getVideoTracks(),...display.getAudioTracks(),...mic.getAudioTracks()])}catch{};streamRef.current=combined;chunksRef.current=[];const mime=MediaRecorder.isTypeSupported('video/webm;codecs=vp9,opus')?'video/webm;codecs=vp9,opus':'video/webm';const recorder=new MediaRecorder(combined,{mimeType:mime});recorder.ondataavailable=e=>{if(e.data.size)chunksRef.current.push(e.data)};recorder.onstop=()=>{const blob=new Blob(chunksRef.current,{type:mime});const url=URL.createObjectURL(blob);setClipUrl(url);setStatus('TAKE READY — DOWNLOAD OR ADD SCENE');streamRef.current?.getTracks().forEach(t=>t.stop())};recorder.start(250);recorderRef.current=recorder;setRecording(true);setStatus('RECORDING GAME/CAMERA TAKE')}catch(error){setStatus(error instanceof Error?error.message:'Screen/camera permission denied')}}
 const stopRecording=()=>{recorderRef.current?.stop();setRecording(false)}
 const addScene=()=>{const scene:Scene={id:crypto.randomUUID?.()||String(Date.now()),name:`Scene ${scenes.length+1}`,world,shot,notes,createdAt:new Date().toISOString(),clipUrl:clipUrl||undefined};const next={...project,scenes:[...scenes,scene],updatedAt:new Date().toISOString()};setProject(next);saveProject(next);setNotes('');setStatus('SCENE SAVED TO PROJECT METADATA')}
 const removeScene=(id:string)=>{const next={...project,scenes:scenes.filter(x=>x.id!==id),updatedAt:new Date().toISOString()};setProject(next);saveProject(next)}
 const exportProject=()=>{const payload=JSON.stringify({...project,exportedAt:new Date().toISOString()},null,2);const url=URL.createObjectURL(new Blob([payload],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`${project.title.replace(/[^a-z0-9]+/gi,'-').toLowerCase()||'tryamm-movie'}-project.json`;a.click();URL.revokeObjectURL(url)}
 const openTool=(name:string)=>{const fn=(window as any)[name];if(typeof fn==='function')fn()}
 const timeline=useMemo(()=>scenes.map((s,i)=>({...s,index:i+1})),[scenes])
 if(!open)return null
 return <div role="dialog" aria-modal="true" aria-label="TRYAMM Movie Studio" style={{position:'fixed',inset:0,zIndex:12220,background:'radial-gradient(circle at top,#29132d,#05070c 55%,#020204)',color:'#fff',overflowY:'auto',padding:16,fontFamily:'Inter,system-ui,sans-serif'}}><div style={{maxWidth:1180,margin:'0 auto'}}>
  <header style={{display:'flex',justifyContent:'space-between',gap:12,alignItems:'center'}}><div><div style={{fontSize:10,color:'#ff79d7',letterSpacing:3,fontWeight:900}}>TRYAMM CREATOR WORLD • MOVIE MODE</div><h1 style={{margin:'6px 0'}}>CREATE A MOVIE</h1><p style={{color:'#aab6c8'}}>Choose a world, direct a scene, record gameplay/camera, add audio/FX, save the project and export the take.</p></div><button aria-label="Close Movie Studio" onClick={()=>setOpen(false)} style={close}>×</button></header>
  <section style={panel}><h2>1. Movie project</h2><input aria-label="Movie title" value={project.title} onChange={e=>{const next={...project,title:e.target.value};setProject(next);saveProject(next)}} style={input}/><div style={grid}><label>WORLD / SET<select value={world} onChange={e=>setWorld(e.target.value)} style={input}><option>StreetVerse Chicago</option><option>Hollywood / Creator World</option><option>StarVerse Stage</option><option>Holoverse</option><option>SpaceVerse Cockpit</option><option>AR Camera Set</option><option>VR / Mixed Reality Set</option></select></label><label>CAMERA SHOT<select value={shot} onChange={e=>setShot(e.target.value)} style={input}><option>Wide establishing shot</option><option>Medium dialogue shot</option><option>Close-up</option><option>POV / first person</option><option>Tracking shot</option><option>Drone / overhead</option><option>360 immersive shot</option></select></label></div><textarea aria-label="Scene direction" value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Scene direction, dialogue, blocking, lighting, characters..." style={{...input,minHeight:100,marginTop:10}}/></section>
  <section style={panel}><h2>2. Camera / AR / VR / MR / audio</h2><div style={buttons}><button style={action} onClick={()=>openTool('__showImmersiveWorlds')}>🥽 AR • VR • MIXED REALITY</button><button style={action} onClick={()=>openTool('__showProAudio')}>🎚 PRO AUDIO</button><button style={action} onClick={()=>openTool('__showStreamStudioFX')}>✨ CAMERA / STREAM FX</button><button style={action} onClick={()=>window.dispatchEvent(new CustomEvent('tryamm:streetverse-mission-open'))}>🎬 SCRIPT / MISSION DIRECTOR</button></div><p style={{color:'#94a3b8'}}>Hardware AR/VR/MR still requires a compatible device/browser. The studio keeps the same movie project regardless of the set you enter.</p></section>
  <section style={panel}><h2>3. Record a take</h2><div style={buttons}><button disabled={!canRecord||recording} onClick={startRecording} style={action}>● RECORD SCREEN / GAME + OPTIONAL MIC</button><button disabled={!recording} onClick={stopRecording} style={action}>■ STOP TAKE</button><button onClick={addScene} style={action}>＋ ADD SCENE TO TIMELINE</button></div><p><b>STATUS:</b> {status}</p>{clipUrl&&<p><a href={clipUrl} download={`${project.title.replace(/[^a-z0-9]+/gi,'-')}-take.webm`} style={{color:'#74e8ff'}}>DOWNLOAD CURRENT TAKE (.webm)</a></p>}</section>
  <section style={panel}><h2>4. Timeline</h2>{timeline.length===0?<p style={{color:'#94a3b8'}}>No scenes yet. Record or describe a scene, then add it.</p>:timeline.map(s=><article key={s.id} style={{border:'1px solid #303747',borderRadius:14,padding:12,margin:'8px 0',background:'#0b0f17'}}><div style={{display:'flex',justifyContent:'space-between',gap:10}}><b>{s.index}. {s.name} — {s.world}</b><button onClick={()=>removeScene(s.id)} style={small}>REMOVE</button></div><div style={{color:'#ffcfef',fontSize:11,marginTop:6}}>{s.shot}</div><p style={{color:'#aab6c8'}}>{s.notes||'No direction notes.'}</p></article>)}</section>
  <section style={panel}><h2>5. Save / reopen / export</h2><div style={buttons}><button onClick={()=>{saveProject(project);setStatus('PROJECT SAVED LOCALLY')}} style={action}>💾 SAVE PROJECT</button><button onClick={()=>{setProject(loadProject());setStatus('PROJECT REOPENED')}} style={action}>↻ REOPEN PROJECT</button><button onClick={exportProject} style={action}>⬇ EXPORT PROJECT FILE</button></div><p style={{color:'#94a3b8'}}>Video takes can be downloaded as WebM immediately. Project metadata is saved locally tonight; server/cloud media persistence remains a production integration gate.</p></section>
 </div></div>
}
const panel={border:'1px solid #4b294d',borderRadius:18,padding:16,margin:'14px 0',background:'#0b0d13'} as const
const grid={display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(220px,1fr))',gap:10} as const
const buttons={display:'flex',gap:9,flexWrap:'wrap'} as const
const action={minHeight:44,borderRadius:11,border:'1px solid #ff79d7',background:'#291127',color:'#fff',padding:'0 14px',fontWeight:900,cursor:'pointer'} as const
const input={boxSizing:'border-box' as const,width:'100%',borderRadius:10,border:'1px solid #394050',background:'#080b12',color:'#fff',padding:'11px 12px'} as const
const close={width:44,height:44,borderRadius:'50%',border:'1px solid #5a425c',background:'#11131b',color:'#fff',fontSize:22} as const
const small={border:'1px solid #61384d',borderRadius:8,background:'#180b12',color:'#ff9bbf',fontSize:9,padding:'4px 7px'} as const