import {useEffect,useState} from 'react'

type Mode='bodega'|'mompop'|'amazon'|'worlds'
const box:React.CSSProperties={padding:14,border:'1px solid #294055',borderRadius:16,background:'#08121c'}
const btn:React.CSSProperties={border:'1px solid #4fe3ff77',borderRadius:11,padding:'10px 13px',background:'#0b1a27',color:'#fff',fontWeight:900,cursor:'pointer'}

export default function NeighborhoodCommerceNetwork(){
 const[open,setOpen]=useState(false);const[mode,setMode]=useState<Mode>('bodega')
 useEffect(()=>{const show=(m?:Mode)=>{if(m)setMode(m);setOpen(true)};(window as any).__showBodegaNetwork=()=>show('bodega');(window as any).__showMomPopNetwork=()=>show('mompop');(window as any).__showAmazonRail=()=>show('amazon');(window as any).__showWorldCommerce=()=>show('worlds');return()=>{delete (window as any).__showBodegaNetwork;delete (window as any).__showMomPopNetwork;delete (window as any).__showAmazonRail;delete (window as any).__showWorldCommerce}},[])
 if(!open)return null
 const workflows={
  bodega:['Choose NYC neighborhood','Map local demand','Select Krasdale/Jetro/approved supplier lane','Build 500-1500 SKU starter set','Add fresh/healthy essentials','Set margin floors','Enable pickup + local delivery','Add Holo Coupon','Publish digital twin into StreetVerse'],
  mompop:['Register independent store','Connect verified supplier catalog','Import current inventory','Create TRYAMM storefront','Enable Holo Concierge search','Add local delivery/pickup','Add creator LIVE commerce','Automate reorder from sales velocity','Offer loyalty + coupon campaigns'],
  amazon:['Keep TRYAMM as customer-facing storefront','Compare self-fulfillment vs Amazon MCF/FBA costs','Send eligible inventory to selected fulfillment rail','Route off-Amazon TRYAMM orders to MCF only when profitable','Keep TRYAMM wallet/loyalty/content/customer relationship','Recalculate landed cost after storage/fulfillment/referral fees','Fail over to local courier or supplier-direct fulfillment when cheaper'],
  worlds:['StreetVerse neighborhood storefront','My World personal shopping district','Middleverse AI intent routing','Metaverse shared merchant districts','Multiverse cross-world discovery','Kingdom market and community commerce','One cart + wallet + loyalty across worlds','Physical fulfillment after Guardian authorization','Verified delivery feeds XP/loyalty back to the world']
 } as const
 return <div role="dialog" aria-modal="true" style={{position:'fixed',inset:0,zIndex:13200,background:'rgba(1,3,9,.96)',color:'#fff',overflow:'auto'}}><div style={{maxWidth:1050,margin:'0 auto',padding:18}}><header style={{display:'flex',justifyContent:'space-between',gap:12}}><div><div style={{color:'#4fe3ff',fontSize:10,fontWeight:950,letterSpacing:3}}>SUPPLY PLUG GLOBAL</div><h1 style={{margin:'4px 0'}}>Neighborhood Commerce Network</h1></div><button onClick={()=>setOpen(false)} style={btn}>Close</button></header><div style={{display:'flex',gap:8,flexWrap:'wrap',margin:'14px 0'}}>{([['bodega','NYC Bodega-in-a-Box'],['mompop','Mom & Pop Network'],['amazon','Amazon Fulfillment Rail'],['worlds','World Commerce']] as [Mode,string][]).map(([m,l])=><button key={m} onClick={()=>setMode(m)} style={{...btn,background:mode===m?'#12354a':'#09131d'}}>{l}</button>)}</div><section style={box}><h2>{mode==='bodega'?'Bodega-in-a-Box':mode==='mompop'?'Independent Store Network':mode==='amazon'?'Amazon as an optional fulfillment rail':'Shop across TRYAMM worlds'}</h2><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(220px,1fr))',gap:9}}>{workflows[mode].map((x,i)=><div key={x} style={{...box,background:'#0b1722'}}><b>{i+1}. {x}</b></div>)}</div></section><section style={{...box,marginTop:12}}><b>ECONOMIC RULE</b><div style={{marginTop:8,color:'#aebdca',lineHeight:1.55}}>VERIFIED WHOLESALE → FREIGHT/DUTY → PICK/PACK → PLATFORM/PAYMENT FEES → RETURNS/SPOILAGE → FULFILLMENT → REQUIRED PROFIT → MAP/POLICY CHECK → RETAIL PRICE. Every rail competes on total landed cost; TRYAMM selects the cheapest compliant route that protects the required margin.</div></section></div></div>
}
