import { useEffect, useState } from 'react'
import { getOmniWearProfile, listOmniWearDevices, registerOmniWearDevice, setOmniWearConnection, startOmniWearSession, stopOmniWearSession, updateOmniWearProfile, type OmniWearDevice, type OmniWearDeviceType, type OmniWearProfile } from '../services/omniWear'

interface Props{onClose:()=>void}
const TYPES:OmniWearDeviceType[]=['watch','band','ring','glasses','clothing','glove','vest','suit','mobility','sensor','other']

export default function OmniWearCenter({onClose}:Props){
 const [devices,setDevices]=useState<OmniWearDevice[]>([]),[profile,setProfile]=useState<OmniWearProfile|null>(null),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[name,setName]=useState('OmniWear Device'),[type,setType]=useState<OmniWearDeviceType>('band'),[sessionId,setSessionId]=useState<string|null>(null)
 async function load(){try{const [d,p]=await Promise.all([listOmniWearDevices(),getOmniWearProfile()]);setDevices(d);setProfile(p)}catch(e){setMessage(e instanceof Error?e.message:String(e))}}
 useEffect(()=>{load()},[])
 const box:React.CSSProperties={background:'#08131b',border:'1px solid #214154',borderRadius:14,padding:12},btn:React.CSSProperties={background:'#0e2631',border:'1px solid #4fe3ff66',color:'#bff6ff',borderRadius:9,padding:'9px 11px',cursor:'pointer',fontFamily:'monospace'}
 async function add(){setBusy(true);try{await registerOmniWearDevice(name,type,{haptics:true,accessibility:true,xr:type==='glasses'||type==='glove'||type==='vest'||type==='suit'});await load();setMessage('Device profile created. Hardware pairing still requires a supported adapter/browser bridge.')}catch(e){setMessage(e instanceof Error?e.message:String(e))}finally{setBusy(false)}}
 return <div style={{position:'fixed',inset:0,zIndex:10080,background:'rgba(1,7,13,.99)',color:'#eefcff',fontFamily:'monospace',overflowY:'auto'}}><div style={{maxWidth:1080,margin:'0 auto',padding:16}}>
  <div style={{display:'flex',gap:12,alignItems:'center'}}><button style={btn} onClick={onClose}>← Back</button><div><h2 style={{margin:0,color:'#4fe3ff'}}>OmniWear</h2><div style={{fontSize:10,color:'#7898a5'}}>Noninvasive wearable platform • accessibility • haptics • XR • device sessions</div></div></div>
  <div style={{...box,marginTop:14,borderColor:'#e8b94466'}}><b style={{color:'#e8b944'}}>Safety boundary</b><div style={{fontSize:11,color:'#a8bbc4',marginTop:6}}>Consumer sensing, accessibility, gaming, navigation, haptics and XR can use this platform. Diagnosis, treatment, neuromuscular stimulation or rehabilitation claims remain blocked until separately validated and authorized.</div></div>
  {message&&<div style={{...box,marginTop:12}}>{message}</div>}
  <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(280px,1fr))',gap:12,marginTop:12}}>
   <section style={box}><h3>Register Wearable</h3><input value={name} onChange={e=>setName(e.target.value)} style={{width:'100%',boxSizing:'border-box',padding:9,borderRadius:8,border:'1px solid #294a58',background:'#061018',color:'#fff'}}/><select value={type} onChange={e=>setType(e.target.value as OmniWearDeviceType)} style={{width:'100%',marginTop:8,padding:9,borderRadius:8,background:'#061018',color:'#fff',border:'1px solid #294a58'}}>{TYPES.map(t=><option key={t}>{t}</option>)}</select><button style={{...btn,marginTop:8}} disabled={busy} onClick={add}>Add Device Profile</button></section>
   <section style={box}><h3>Privacy + Consent</h3>{profile&&<><div style={{fontSize:11,color:'#a8bbc4'}}>Mode: {profile.privacy_mode}</div><label style={{display:'block',marginTop:8}}><input type="checkbox" checked={Boolean(profile.consent.telemetry)} onChange={async e=>{const next={...profile.consent,telemetry:e.target.checked};setProfile(await updateOmniWearProfile({consent:next}))}}/> Share device telemetry</label><label style={{display:'block',marginTop:8}}><input type="checkbox" checked={Boolean(profile.consent.analytics)} onChange={async e=>{const next={...profile.consent,analytics:e.target.checked};setProfile(await updateOmniWearProfile({consent:next}))}}/> Product analytics</label></>}</section>
  </div>
  <h3 style={{marginTop:18}}>My Wearables</h3><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(280px,1fr))',gap:10}}>{devices.map(d=><div key={d.id} style={box}><div style={{display:'flex',justifyContent:'space-between'}}><b>{d.device_name}</b><span style={{fontSize:10,color:d.connection_state==='connected'?'#78ffb4':'#e8b944'}}>{d.connection_state}</span></div><div style={{fontSize:10,color:'#8ea6b0',marginTop:5}}>{d.device_type} • battery {d.battery_percent??'—'}%</div><div style={{display:'flex',gap:7,flexWrap:'wrap',marginTop:9}}><button style={btn} onClick={async()=>{await setOmniWearConnection(d.id,d.connection_state==='connected'?'disconnected':'connected');await load()}}>{d.connection_state==='connected'?'Disconnect':'Simulate Pair'}</button><button style={btn} onClick={async()=>{const s=await startOmniWearSession(d.id,'accessibility');setSessionId(s.id);setMessage('Accessibility session started.')}}>Accessibility Session</button><button style={btn} onClick={async()=>{const s=await startOmniWearSession(d.id,'xr');setSessionId(s.id);setMessage('XR wearable session started.')}}>XR Session</button></div></div>)}{!devices.length&&<div style={{...box,color:'#8198a2'}}>No OmniWear device profiles yet.</div>}</div>
  {sessionId&&<button style={{...btn,marginTop:14,borderColor:'#ff8a8a88',color:'#ffb0b0'}} onClick={async()=>{await stopOmniWearSession(sessionId);setSessionId(null);setMessage('Wearable session stopped safely.')}}>Stop Active Session</button>}
 </div></div>
}
