import { useEffect,useMemo,useState } from 'react'
import { joinPKBackchannel,leavePKBackchannel,listPKMessages,sendPKMessage,subscribePKMessages,type PKBackchannelMessage,type PKChannel,type PKRole,type PKTeam } from '../services/pkBackchannel'

export default function PKBackchannelPanel({roomId,displayName,host=false}:{roomId:string;displayName:string;host?:boolean}){
 const [open,setOpen]=useState(false),[joined,setJoined]=useState(false),[team,setTeam]=useState<PKTeam>(host?'host':'alpha'),[role,setRole]=useState<PKRole>(host?'host':'player'),[channel,setChannel]=useState<PKChannel>(host?'hosts':'team-alpha'),[messages,setMessages]=useState<PKBackchannelMessage[]>([]),[draft,setDraft]=useState(''),[error,setError]=useState('')
 const allowed=useMemo<PKChannel[]>(()=>role==='moderator'?['team-alpha','team-beta','hosts','moderators']:role==='host'||role==='captain'?[team==='beta'?'team-beta':'team-alpha','hosts']:[team==='beta'?'team-beta':'team-alpha'],[team,role])
 useEffect(()=>{if(!allowed.includes(channel))setChannel(allowed[0])},[allowed,channel])
 useEffect(()=>{if(!joined)return;let stop=()=>{};listPKMessages(roomId,channel).then(setMessages).catch(e=>setError(e.message));try{stop=subscribePKMessages(roomId,channel,m=>setMessages(old=>old.some(x=>x.id===m.id)?old:[...old,m].slice(-100)))}catch(e:any){setError(e.message)}return stop},[joined,roomId,channel])
 const join=async()=>{setError('');try{await joinPKBackchannel({roomId,team,role,displayName});setJoined(true)}catch(e:any){setError(e.message)} }
 const send=async()=>{setError('');try{await sendPKMessage(roomId,channel,draft);setDraft('')}catch(e:any){setError(e.message)}}
 const leave=async()=>{try{await leavePKBackchannel(roomId)}finally{setJoined(false);setMessages([])}}
 return <div style={{marginTop:12,border:'1px solid rgba(79,227,255,.35)',borderRadius:14,padding:10,background:'rgba(3,12,24,.86)'}}><button type="button" aria-label="Open PK backchannel" onClick={()=>setOpen(v=>!v)} style={button}>🎧 PK BACKCHANNEL {open?'▲':'▼'}</button>{open&&<div><p style={muted}>Private internal communication for PK teammates. Public viewers do not receive these messages. Blocking/reporting rules still apply.</p>{!joined?<><div style={row}><select aria-label="PK team" value={team} onChange={e=>setTeam(e.target.value as PKTeam)} style={input}><option value="alpha">Team Alpha</option><option value="beta">Team Beta</option>{host&&<option value="host">Host team</option>}</select><select aria-label="PK role" value={role} onChange={e=>setRole(e.target.value as PKRole)} style={input}><option value="player">Player</option><option value="captain">Captain</option>{host&&<option value="host">Host</option>}</select><button onClick={join} style={button}>JOIN INTERNAL COMMS</button></div></>:<><div style={row}>{allowed.map(c=><button key={c} onClick={()=>setChannel(c)} style={{...chip,...(channel===c?active:{})}}>{c.toUpperCase()}</button>)}<button onClick={leave} style={danger}>LEAVE</button></div><div aria-live="polite" style={{maxHeight:190,overflowY:'auto',padding:'8px 0'}}>{messages.length?messages.map(m=><div key={m.id} style={{padding:'7px 9px',margin:'5px 0',borderRadius:9,background:'#0b1627'}}><small>{new Date(m.created_at).toLocaleTimeString()}</small><div>{m.body}</div></div>):<p style={muted}>No internal messages yet.</p>}</div><div style={row}><input aria-label="PK internal message" value={draft} maxLength={500} onChange={e=>setDraft(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')void send()}} placeholder="Talk to your PK team…" style={{...input,flex:1}}/><button onClick={()=>void send()} disabled={!draft.trim()} style={button}>SEND</button></div></>}{error&&<div role="alert" style={{color:'#ff9b9b',marginTop:8}}>{error}</div>}</div>}</div>
}
const row={display:'flex',gap:8,flexWrap:'wrap' as const,alignItems:'center',marginTop:8}
const button={padding:'9px 11px',borderRadius:10,border:'1px solid #4fe3ff',background:'#0b2333',color:'#fff',fontWeight:900,cursor:'pointer'} as const
const input={padding:'9px 10px',borderRadius:9,border:'1px solid rgba(255,255,255,.18)',background:'#071020',color:'#fff'} as const
const chip={...button,fontSize:10,border:'1px solid rgba(255,255,255,.18)',background:'#111827'} as const
const active={border:'1px solid #4fe3ff',background:'#123145'} as const
const danger={...button,border:'1px solid #ff7070',background:'#351111'} as const
const muted={fontSize:12,color:'#aab8c8',lineHeight:1.5} as const
