import {useEffect,useState} from 'react'
import {TRY_ON_PIPELINE,type TryOnMode} from '../commerce/productTryOn'

const panel:React.CSSProperties={padding:14,border:'1px solid #294055',borderRadius:16,background:'#08121c'}
const btn:React.CSSProperties={border:'1px solid #4fe3ff77',borderRadius:11,padding:'10px 13px',background:'#0b1a27',color:'#fff',fontWeight:900,cursor:'pointer'}
const modes:TryOnMode[]=['avatar-3d','camera-ar','photo-preview','room-preview','streetverse']

export default function ProductTryOnHub(){
 const[open,setOpen]=useState(false);const[mode,setMode]=useState<TryOnMode>('avatar-3d');const[consent,setConsent]=useState(false)
 useEffect(()=>{(window as any).__showProductTryOn=()=>setOpen(true);return()=>{delete (window as any).__showProductTryOn}},[])
 if(!open)return null
 return <div role="dialog" aria-modal="true" aria-label="Product Try-On" style={{position:'fixed',inset:0,zIndex:13600,background:'rgba(1,3,9,.97)',color:'#fff',overflow:'auto'}}><div style={{maxWidth:980,margin:'0 auto',padding:18}}><header style={{display:'flex',justifyContent:'space-between',gap:12}}><div><div style={{color:'#4fe3ff',fontSize:10,fontWeight:950,letterSpacing:3}}>REAL PRODUCT → DIGITAL TWIN → TRY → BUY</div><h1 style={{margin:'4px 0'}}>TRYAMM Product Try-On</h1><p style={{color:'#aebdca'}}>Preview wigs, hair, makeup, nails, clothing, shoes, jewelry, accessories and home products using the same product twin that can appear in StreetVerse, creator videos and the AI storefront.</p></div><button style={btn} onClick={()=>setOpen(false)}>Close</button></header><section style={{...panel,marginTop:14}}><h2>Choose preview mode</h2><div style={{display:'flex',gap:8,flexWrap:'wrap'}}>{modes.map(m=><button key={m} style={{...btn,borderColor:mode===m?'#e8b944':'#4fe3ff77'}} onClick={()=>setMode(m)}>{m}</button>)}</div><label style={{display:'block',marginTop:12}}><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/> I consent to use of my selected camera/photo/avatar input for this preview session.</label></section><section style={{...panel,marginTop:12}}><h2>Preview contract</h2><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(190px,1fr))',gap:8}}>{TRY_ON_PIPELINE.map((x,i)=><div key={x} style={{...panel,background:'#0b1722'}}><b>{i+1}. {x}</b></div>)}</div></section><section style={{...panel,marginTop:12}}><h2>Commerce connection</h2><p style={{color:'#aebdca',lineHeight:1.6}}>TRY-ON → SELECT VARIANT → SAVE LOOK → CREATOR REEL / STREETVERSE VIEW → HOLO COUPON → CART → GUARDIAN → PAYMENT → VIRTUAL WAREHOUSE → DELIVERY/PICKUP → CREATOR/MERCHANT ATTRIBUTION.</p><button disabled={!consent} style={{...btn,opacity:consent?1:.45}} onClick={()=>{(window as any).__showAllAmericanBeauty?.()}}>Open eligible products</button></section><p style={{fontSize:10,color:'#7f94a6'}}>Camera/photo try-on must remain opt-in. Preview is visual guidance, not a guarantee of exact physical fit, shade, texture or sizing.</p></div></div>
}
