import { useMemo,useState } from 'react'
import { QUANTUM_NETWORK_CAPABILITIES,QUANTUM_NETWORK_PROFILE,QUANTUM_WIFI_POLICY,evaluateQuantumNetwork,type QuantumNetworkMode } from '../services/quantumNetworkSecurity'

export default function QuantumNetworkCenter(){
 const [open,setOpen]=useState(false),[mode,setMode]=useState<QuantumNetworkMode>('observe'),[trusted,setTrusted]=useState(true)
 const result=useMemo(()=>evaluateQuantumNetwork({mode,vpnProviderConfigured:false,nativeAdapterAvailable:false,trustedNetwork:trusted,pqcProviderAvailable:false}),[mode,trusted])
 return <><button type="button" aria-label="Open Quantum Network Center" onClick={()=>setOpen(true)} style={{position:'fixed',right:12,bottom:226,zIndex:8998,border:'1px solid #9b7cff88',borderRadius:999,background:'linear-gradient(135deg,#17102e,#071d2a)',color:'#fff',padding:'10px 14px',fontFamily:'monospace',fontSize:10,fontWeight:900}}>🛡️ QUANTUM NETWORK</button>{open&&<div role="dialog" aria-modal="true" aria-label="Quantum Network Center" style={{position:'fixed',inset:0,zIndex:10150,overflowY:'auto',background:'radial-gradient(circle at top,#201440,#05070d 58%,#020204)',color:'#fff',padding:16}}><div style={{maxWidth:1080,margin:'0 auto'}}><header style={{display:'flex',justifyContent:'space-between',gap:12,alignItems:'center'}}><div><div style={{fontSize:10,color:'#b9a7ff',letterSpacing:3,fontWeight:900}}>TRYAMM • POST-QUANTUM-READY NETWORK SECURITY</div><h1>Quantum VPN + Quantum WiFi</h1><p style={muted}>{QUANTUM_NETWORK_PROFILE.description}</p></div><button aria-label="Close" onClick={()=>setOpen(false)} style={close}>×</button></header><section style={panel}><h2>Security mode</h2><div style={row}>{(['off','observe','provider-gated','active'] as QuantumNetworkMode[]).map(x=><button key={x} onClick={()=>setMode(x)} style={{...action,...(mode===x?active:{})}}>{x.toUpperCase()}</button>)}</div><label style={{display:'flex',gap:8,marginTop:14}}><input type="checkbox" checked={trusted} onChange={e=>setTrusted(e.target.checked)}/> Mark current network as trusted for this simulation</label><p style={{...muted,color:result.ok?'#8effb9':'#ffd38e'}}>{result.recommendation}</p>{result.blockers.length>0&&<ul>{result.blockers.map(x=><li key={x}>{x}</li>)}</ul>}</section><section style={panel}><h2>Capabilities</h2><div style={grid}>{QUANTUM_NETWORK_CAPABILITIES.map(c=><article key={c.id} style={card}><b>{c.label}</b><div style={{fontSize:10,color:'#b9a7ff',margin:'6px 0'}}>{c.status.toUpperCase()}</div><p style={muted}>{c.detail}</p></article>)}</div></section><section style={panel}><h2>Cryptography target</h2><p style={muted}>Key establishment: {QUANTUM_NETWORK_PROFILE.standards.keyEstablishment}. Signatures: {QUANTUM_NETWORK_PROFILE.standards.signatures}. Alternate signatures: {QUANTUM_NETWORK_PROFILE.standards.alternateSignatures}.</p><p style={muted}>The app does not implement these primitives by hand. A production tunnel must use an audited native/provider implementation.</p></section><section style={panel}><h2>Quantum WiFi policy</h2><ul>{QUANTUM_WIFI_POLICY.map(x=><li key={x}>{x}</li>)}</ul></section></div></div>}</>
}
const panel={border:'1px solid #392c5c',borderRadius:18,padding:16,margin:'14px 0',background:'#0b0c14'} as const
const card={border:'1px solid #2d3140',borderRadius:14,padding:12,background:'#0e111b'} as const
const grid={display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(220px,1fr))',gap:10} as const
const row={display:'flex',gap:8,flexWrap:'wrap' as const} as const
const action={minHeight:40,borderRadius:10,border:'1px solid #7966a8',background:'#19142a',color:'#fff',padding:'0 12px',fontWeight:900,cursor:'pointer'} as const
const active={border:'1px solid #c1b2ff',background:'#392864'} as const
const close={width:44,height:44,borderRadius:'50%',border:'1px solid #615875',background:'#11131b',color:'#fff',fontSize:22} as const
const muted={color:'#aab8c8',lineHeight:1.6} as const
