import {useState} from 'react'
import {DRONE_OS,SERVICES_WORK_COMMERCE} from '../services/ServicesWorkCommercePlatform'
export default function ServicesWorkCommerceHub(){const[open,setOpen]=useState(false);if(!open)return <button onClick={()=>setOpen(true)} style={fab}>🧭 SERVICES • WORK • COMMERCE</button>;return <div role="dialog" aria-label="Services Work Commerce" style={overlay}><div style={box}><button onClick={()=>setOpen(false)} style={close}>×</button><h1>SERVICES • WORK • COMMERCE</h1><p>One doorway into property, mobility, work, education and regulated service pathways.</p><h2>Property + housing</h2><div style={grid}>{SERVICES_WORK_COMMERCE.property.map(x=><article style={card} key={x.id}><b>{x.name}</b><small>{x.gate}</small><p>{x.features.join(' • ')}</p></article>)}</div><h2>Mobility + services</h2><p>{SERVICES_WORK_COMMERCE.mobility.join(' • ')}</p><h2>Work + education</h2><p>{SERVICES_WORK_COMMERCE.work.join(' • ')}</p><p>{SERVICES_WORK_COMMERCE.education.join(' • ')}</p><h2>🚁 Drone Academy + Drone OS</h2><p>{DRONE_OS.careerPath}</p><div style={grid}>{DRONE_OS.training.map(x=><article style={card} key={x}>{x}</article>)}</div><h3>Registration path</h3><p>{DRONE_OS.registrationPath.join(' → ')}</p><p style={{color:'#ffcf66'}}>{DRONE_OS.hardStops.join(' • ')}</p><h2>Connected worlds</h2><p>{SERVICES_WORK_COMMERCE.worlds.join(' • ')}</p></div></div>}
const fab={position:'fixed',right:14,bottom:142,zIndex:11900,border:'1px solid #4FE3FF',borderRadius:999,padding:'11px 14px',background:'#07111c',color:'#fff',fontWeight:900} as const
const overlay={position:'fixed',inset:0,zIndex:12500,overflowY:'auto',background:'rgba(2,5,12,.96)',color:'#fff',padding:18} as const
const box={maxWidth:1100,margin:'0 auto',position:'relative'} as const
const close={position:'sticky',top:10,float:'right',width:44,height:44,borderRadius:'50%',background:'#111',color:'#fff',border:'1px solid #555'} as const
const grid={display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(220px,1fr))',gap:10} as const
const card={border:'1px solid #27445e',background:'#091421',padding:12,borderRadius:14,display:'grid',gap:6} as const
