import { useEffect, useRef, useState } from 'react'
import { canUseSpeechRecognition, signLanguageApi, startSpeechRecognition, type SignCapabilities, type SignLanguageCode, type SignOutputMode, type SignTranslation } from '../accessibility/signLanguage'

const LANGS: Array<{code:SignLanguageCode;label:string}>=[{code:'asl',label:'ASL'},{code:'bsl',label:'BSL'},{code:'lsf',label:'LSF'},{code:'dgs',label:'DGS'},{code:'auslan',label:'Auslan'},{code:'isl',label:'ISL'},{code:'jls',label:'JSL'}]
export default function SignLanguageHub({onClose}:{onClose:()=>void}){
 const [language,setLanguage]=useState<SignLanguageCode>('asl'); const [mode,setMode]=useState<SignOutputMode>('gloss'); const [text,setText]=useState('Welcome to TryAMM. Sign language is a first-class language here.'); const [result,setResult]=useState<SignTranslation|null>(null); const [caps,setCaps]=useState<SignCapabilities|null>(null); const [error,setError]=useState(''); const [busy,setBusy]=useState(false); const [listening,setListening]=useState(false); const stopRef=useRef<null|(()=>void)>(null)
 useEffect(()=>{signLanguageApi.capabilities().then(setCaps).catch(()=>setCaps(null));return()=>stopRef.current?.()},[])
 async function translate(next=text){if(!next.trim())return;setBusy(true);setError('');try{setResult(await signLanguageApi.translate({text:next,signLanguage:language,mode}))}catch(e:any){setError(e.message||'Translation failed')}finally{setBusy(false)}}
 function speech(){if(listening){stopRef.current?.();setListening(false);return}if(!canUseSpeechRecognition()){setError('Speech recognition is not available in this browser.');return}setListening(true);stopRef.current=startSpeechRecognition(t=>{setText(t);void translate(t)},()=>setListening(false),m=>{setError(m);setListening(false)})}
 return <div role="dialog" aria-modal="true" aria-label="Sign Language Hub" style={{position:'absolute',inset:0,overflowY:'auto',background:'linear-gradient(180deg,#050816,#0d1230)',color:'#fff',padding:24,fontFamily:'system-ui,sans-serif'}}>
  <div style={{maxWidth:1000,margin:'0 auto'}}><div style={{display:'flex',justifyContent:'space-between',gap:16}}><div><div style={{fontSize:12,letterSpacing:2,opacity:.7}}>TRYAMM ACCESSIBILITY</div><h1 style={{margin:'6px 0'}}>Sign Language Hub</h1><p style={{opacity:.75}}>Speech ⇄ text ⇄ sign with captions and avatar-ready output.</p></div><button onClick={onClose} aria-label="Close" style={{width:44,height:44,borderRadius:12,border:0,fontSize:28}}>×</button></div>
  <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(280px,1fr))',gap:16}}>
   <section style={card}><h2>Speak or type</h2><textarea value={text} onChange={e=>setText(e.target.value)} rows={6} style={{width:'100%',boxSizing:'border-box',borderRadius:12,padding:12,background:'#080d22',color:'#fff',border:'1px solid #ffffff33'}}/><div style={{display:'flex',gap:8,flexWrap:'wrap',marginTop:10}}><button onClick={speech} style={button}>{listening?'Stop listening':'🎙 Live speech'}</button><button onClick={()=>void translate()} disabled={busy} style={button}>{busy?'Translating…':'Translate'}</button></div><div style={{display:'flex',gap:8,marginTop:10}}><select value={language} onChange={e=>setLanguage(e.target.value as SignLanguageCode)} style={select}>{LANGS.map(x=><option key={x.code} value={x.code}>{x.label}</option>)}</select><select value={mode} onChange={e=>setMode(e.target.value as SignOutputMode)} style={select}><option value="gloss">Gloss</option><option value="fingerspell">Fingerspell</option><option value="avatar">Avatar queue</option></select></div></section>
   <section style={card}><h2>Sign output</h2>{result?<><div style={{fontSize:12,opacity:.7}}>{result.signLanguage.toUpperCase()} · {result.provider}</div><div style={{fontSize:24,fontWeight:800,lineHeight:1.5,marginTop:12}}>{result.gloss.join(' · ')}</div>{result.fingerspelling&&<div style={{marginTop:12,fontFamily:'monospace'}}>{result.fingerspelling.map(w=>w.join(' ')).join(' / ')}</div>}{result.avatarSequence&&<div style={{marginTop:12}}>Avatar queue: {result.avatarSequence.map(x=>x.token).join(' → ')}</div>}{result.warnings?.map(w=><p key={w} style={{fontSize:13,opacity:.65}}>{w}</p>)}</>:<p style={{opacity:.6}}>Translation appears here.</p>}</section>
   <section style={card}><h2>System status</h2><p>Text → sign: ✅</p><p>Live captions: ✅</p><p>Offline fingerspelling fallback: ✅</p><p>Sign recognition provider: {caps?.providerConfigured?'✅ configured':'◻️ provider required'}</p><p style={{opacity:.65,fontSize:13}}>No production-grade sign-recognition accuracy is claimed until a validated provider/model is connected and tested with Deaf/native-signing users.</p></section>
  </div>{error&&<div role="alert" style={{marginTop:16,padding:12,border:'1px solid #ff666688',borderRadius:12,background:'#ff444422'}}>{error}</div>}</div>
 </div>
}
const card={background:'#ffffff10',border:'1px solid #ffffff20',borderRadius:18,padding:18} as const
const button={border:'1px solid #ffffff44',background:'#ffffff18',color:'#fff',borderRadius:10,padding:'10px 14px',cursor:'pointer',fontWeight:700} as const
const select={flex:1,minWidth:120,background:'#080d22',color:'#fff',border:'1px solid #ffffff33',borderRadius:10,padding:10} as const
