import {useEffect,useRef} from 'react'
import * as THREE from 'three'

type OpponentEvent={id?:string;name?:string;progress?:number}
const ROUTE=[{x:0,z:48},{x:48,z:-48},{x:0,z:0},{x:48,z:48},{x:0,z:48}]
const COLORS=[0xff4f6d,0x55d9ff,0xffce55]
const NAMES=['NOVA','SOUTH LOOP','LAKEFRONT']
function racer(color:number){const g=new THREE.Group();const body=new THREE.Mesh(new THREE.BoxGeometry(4.6,1.05,2),new THREE.MeshStandardMaterial({color,metalness:.55,roughness:.3}));body.position.y=1;g.add(body);const cabin=new THREE.Mesh(new THREE.BoxGeometry(2.2,.72,1.7),new THREE.MeshStandardMaterial({color:0x86c9e8,metalness:.45,roughness:.18}));cabin.position.set(-.25,1.72,0);g.add(cabin);for(const x of [-1.45,1.45])for(const z of [-1,1]){const w=new THREE.Mesh(new THREE.CylinderGeometry(.4,.4,.28,10),new THREE.MeshStandardMaterial({color:0x111111,roughness:.9}));w.rotation.x=Math.PI/2;w.position.set(x,.5,z*.98);g.add(w)}return g}
function routePoint(progress:number,lane:number){const pct=Math.max(0,Math.min(100,progress))/100*(ROUTE.length-1);const i=Math.min(ROUTE.length-2,Math.floor(pct)),t=pct-i;const a=ROUTE[i],b=ROUTE[i+1];let x=THREE.MathUtils.lerp(a.x,b.x,t),z=THREE.MathUtils.lerp(a.z,b.z,t);const dx=b.x-a.x,dz=b.z-a.z,len=Math.hypot(dx,dz)||1;x+=(-dz/len)*lane;z+=(dx/len)*lane;return{x,z,heading:Math.atan2(-dz,dx)}}
export default function StreetVerseAIRacerLayer(){const mount=useRef<HTMLDivElement|null>(null);useEffect(()=>{const root=mount.current;if(!root)return;const scene=new THREE.Scene();const camera=new THREE.PerspectiveCamera(58,1,.1,300);camera.position.set(0,72,92);camera.lookAt(0,0,0);const renderer=new THREE.WebGLRenderer({alpha:true,antialias:false,powerPreference:'high-performance'});renderer.setClearColor(0,0);renderer.setPixelRatio(Math.min(devicePixelRatio,1.25));root.appendChild(renderer.domElement);scene.add(new THREE.HemisphereLight(0xcdefff,0x111827,2.3));const sun=new THREE.DirectionalLight(0xffffff,2.4);sun.position.set(25,55,30);scene.add(sun);const cars=NAMES.map((name,i)=>{const g=racer(COLORS[i]);g.visible=false;g.userData={name,progress:0};scene.add(g);return g});let active=false;const onStart=()=>{active=true;cars.forEach((c,i)=>{c.visible=true;c.userData.progress=0;const p=routePoint(0,(i-1)*3.2);c.position.set(p.x,.2,p.z);c.rotation.y=p.heading})};const onOpp=(e:Event)=>{const d=(e as CustomEvent<OpponentEvent>).detail||{};const idx=NAMES.indexOf(String(d.name||'').toUpperCase());if(idx<0)return;const c=cars[idx];c.visible=true;c.userData.progress=Number(d.progress)||0};const onEnd=()=>{active=false;cars.forEach(c=>c.visible=false)};addEventListener('tryamm:streetverse-ai-opponents-start',onStart);addEventListener('tryamm:streetverse-ai-opponent',onOpp);addEventListener('tryamm:streetverse-mission-complete',onEnd);addEventListener('tryamm:streetverse-scene-close',onEnd);const resize=()=>{const w=root.clientWidth||innerWidth,h=root.clientHeight||innerHeight;camera.aspect=w/h;camera.updateProjectionMatrix();renderer.setSize(w,h,false)};const ro=new ResizeObserver(resize);ro.observe(root);resize();let raf=0;const target=new THREE.Vector3();const tick=()=>{if(active)cars.forEach((c,i)=>{const p=routePoint(Number(c.userData.progress)||0,(i-1)*3.2);target.set(p.x,.2,p.z);c.position.lerp(target,.12);c.rotation.y=THREE.MathUtils.lerp(c.rotation.y,p.heading,.12);dispatchEvent(new CustomEvent('tryamm:streetverse-ai-world-position',{detail:{name:c.userData.name,x:c.position.x,z:c.position.z,progress:c.userData.progress}}))});renderer.render(scene,camera);raf=requestAnimationFrame(tick)};tick();return()=>{cancelAnimationFrame(raf);ro.disconnect();removeEventListener('tryamm:streetverse-ai-opponents-start',onStart);removeEventListener('tryamm:streetverse-ai-opponent',onOpp);removeEventListener('tryamm:streetverse-mission-complete',onEnd);removeEventListener('tryamm:streetverse-scene-close',onEnd);renderer.dispose();renderer.domElement.remove()}},[]);return <div ref={mount} aria-hidden="true" style={{position:'fixed',inset:0,zIndex:16992,pointerEvents:'none'}}/>}
