import { useEffect, useMemo, useState } from 'react'

type Mission={id:string;branchId:string;title:string;city:string;phase:string;objectives:{id:string;label:string;done:boolean}[];boss?:{name:string;stages:number;stage:number};extraction:{zone:string;secured:boolean;teamReady:boolean};xp:number;reputation:number}
type ServiceState={branches?:any[];city?:string}
export default function StreetVerseCareerHUD(){
 const [mission,setMission]=useState<Mission|null>(null),[service,setService]=useState<ServiceState>({}),[dispatch,setDispatch]=useState<any[]>([]),[promotion,setPromotion]=useState<any|null>(null)
 useEffect(()=>{const onMission=(e:Event)=>{const m=(e as CustomEvent<any>).detail?.mission||null;setMission(m);if(m?.phase==='complete')setPromotion({title:'CAREER PROMOTION REVIEW',xp:m.xp,reputation:m.reputation,branchId:m.branchId})},onService=(e:Event)=>setService((e as CustomEvent<any>).detail||{}),onDispatch=(e:Event)=>setDispatch(d=>[(e as CustomEvent<any>).detail,...d].slice(0,5));window.addEventListener('tryamm:career-extraction-state',onMission);window.addEventListener('tryamm:guardian-service-state',onService);window.addEventListener('tryamm:guardian-dispatch-call',onDispatch);window.dispatchEvent(new Event('tryamm:guardian-service-request'));window.dispatchEvent(new Event('tryamm:career-extraction-request'));return()=>{window.removeEventListener('tryamm:career-extraction-state',onMission);window.removeEventListener('tryamm:guardian-service-state',onService);window.removeEventListener('tryamm:guardian-dispatch-call',onDispatch)}},[])
 const pct=useMemo(()=>mission?Math.round((mission.objectives.filter(o=>o.done).length/Math.max(1,mission.objectives.length))*100):0,[mission])
 return <div style={{position:'fixed',right:12,bottom:12,zIndex:9050,width:340,maxHeight:'70vh',overflow:'auto',background:'#061018ee',color:'#fff',border:'1px solid #355',borderRadius:14,padding:12,fontFamily:'Inter,system-ui'}}>
  <div style={{fontWeight:900,color:'#4fe3ff'}}>AL B DISPATCH / CAREER HUD</div>
  <div style={{fontSize:11,color:'#9fb2c4',marginBottom:8}}>City: {service.city||mission?.city||'Chicago'} · fictional TRYAMM public-service gameplay</div>
  {dispatch.length>0&&<div style={{marginBottom:10}}>{dispatch.map((d,i)=><div key={i} style={{padding:'6px 8px',background:'#0d1b27',borderRadius:8,marginBottom:5}}><b>{d.priority||'STANDARD'}:</b> {d.title||'New dispatch'}<div style={{fontSize:11,color:'#9fb2c4'}}>{d.city||service.city||'Local'} · {d.branchId||'Guardian Network'}</div></div>)}</div>}
  {!mission&&<div style={{fontSize:12,color:'#9fb2c4'}}>Choose a Guardian service branch to begin a dispatch-driven career mission.</div>}
  {mission&&<><h3 style={{margin:'8px 0 4px'}}>{mission.title}</h3><div style={{fontSize:12}}>Phase: <b>{mission.phase.toUpperCase()}</b> · Progress {pct}%</div><div style={{height:6,background:'#16232e',borderRadius:6,margin:'6px 0 10px'}}><div style={{height:'100%',width:`${pct}%`,background:'#4fe3ff',borderRadius:6}}/></div>
   <div style={{fontWeight:800,marginBottom:4}}>Mission Objectives</div>{mission.objectives.map(o=><label key={o.id} style={{display:'block',fontSize:12,padding:'4px 0'}}><input type="checkbox" checked={o.done} onChange={()=>!o.done&&window.dispatchEvent(new CustomEvent('tryamm:career-objective-complete',{detail:{id:o.id}}))}/> {o.label}</label>)}
   {mission.boss&&mission.phase==='boss'&&<div style={{marginTop:10,padding:10,border:'1px solid #644',borderRadius:10,background:'#1b0e12'}}><b>BOSS CHALLENGE: {mission.boss.name}</b><div style={{fontSize:12}}>Stage {mission.boss.stage}/{mission.boss.stages}</div><button onClick={()=>window.dispatchEvent(new Event('tryamm:career-boss-stage-complete'))} style={{marginTop:6}}>COMPLETE SAFE STAGE</button></div>}
   {mission.phase==='extraction'&&<div style={{marginTop:10,padding:10,border:'1px solid #465',borderRadius:10}}><b>EXTRACTION ZONE</b><div style={{fontSize:12}}>{mission.extraction.zone}</div><button onClick={()=>window.dispatchEvent(new CustomEvent('tryamm:career-extraction-update',{detail:{secured:true}}))}>SECURE ZONE</button> <button onClick={()=>window.dispatchEvent(new CustomEvent('tryamm:career-extraction-update',{detail:{teamReady:true}}))}>TEAM READY</button></div>}
   {mission.phase==='verification'&&<div style={{marginTop:10}}><button onClick={()=>window.dispatchEvent(new Event('tryamm:career-mission-verify'))}>SUBMIT AFTER-ACTION REPORT + VERIFY</button></div>}
  </>}
  {promotion&&<div style={{marginTop:10,padding:10,border:'1px solid #8a6',borderRadius:10,background:'#101b0e'}}><b>{promotion.title}</b><div style={{fontSize:12}}>+{promotion.xp} XP · +{promotion.reputation} reputation</div><button onClick={()=>setPromotion(null)} style={{marginTop:6}}>CONTINUE CAREER</button></div>}
 </div>
}
