import {useEffect,useMemo,useState} from 'react'
type TrainState={lineId:string;speed:number;distanceToStation:number;doorsOpen:boolean;disabled:boolean;throttle:number;brake:number;station?:string;onboard?:number}
type NetworkState='NORMAL'|'EMERGENCY STOP'|'EVACUATION'|'REROUTE'|'RESTORING'
export default function StreetVerseTransitSafetyDirector(){const [train,setTrain]=useState<TrainState|null>(null),[network,setNetwork]=useState<NetworkState>('NORMAL'),[signal,setSignal]=useState<'GREEN'|'YELLOW'|'RED'>('GREEN')
 useEffect(()=>{const onState=(e:Event)=>{const d=(e as CustomEvent).detail||{};if(!d.lineId)return;const next:TrainState={lineId:String(d.lineId),speed:Number(d.speed)||0,distanceToStation:Number.isFinite(d.distanceToStation)?Number(d.distanceToStation):999,doorsOpen:!!d.doorsOpen,disabled:!!d.disabled,throttle:Number(d.throttle)||0,brake:Number(d.brake)||0,station:d.station,onboard:Number(d.onboard)||0};setTrain(next);const s=next.disabled||next.doorsOpen?'RED':next.distanceToStation<9||next.speed>8.5?'YELLOW':'GREEN';setSignal(s);window.dispatchEvent(new CustomEvent('tryamm:transit-signal-state',{detail:{lineId:next.lineId,signal:s,distance:next.distanceToStation,speed:next.speed}}));if(s==='RED'&&next.speed>.15)window.dispatchEvent(new CustomEvent('tryamm:transit-operator-control',{detail:{lineId:next.lineId,throttle:0,brake:1,reason:'signal-red-interlock'}}));else if(s==='YELLOW'&&next.speed>5.5)window.dispatchEvent(new CustomEvent('tryamm:transit-operator-control',{detail:{lineId:next.lineId,throttle:0,brake:.55,reason:'signal-yellow-speed-control'}}))}
 const emergency=()=>setNetwork('EMERGENCY STOP'),evac=()=>setNetwork('EVACUATION'),reroute=()=>setNetwork('REROUTE'),restore=()=>{setNetwork('RESTORING');setTimeout(()=>setNetwork('NORMAL'),1200)}
 window.addEventListener('tryamm:l-train-state',onState);window.addEventListener('tryamm:transit-emergency-stop',emergency);window.addEventListener('tryamm:transit-evacuation',evac);window.addEventListener('tryamm:transit-reroute',reroute);window.addEventListener('tryamm:transit-network-restored',restore);return()=>{window.removeEventListener('tryamm:l-train-state',onState);window.removeEventListener('tryamm:transit-emergency-stop',emergency);window.removeEventListener('tryamm:transit-evacuation',evac);window.removeEventListener('tryamm:transit-reroute',reroute);window.removeEventListener('tryamm:transit-network-restored',restore)}} ,[])
 const status=useMemo(()=>train?`${train.lineId.toUpperCase()} • ${train.speed.toFixed(1)} SPD • ${Math.round(train.distanceToStation)}m TO ${train.station||'STOP'}`:'WAITING FOR TRAIN STATE',[train])
 return <div style={{position:'fixed',right:12,top:430,zIndex:12003,width:260,padding:'9px 10px',borderRadius:11,background:'rgba(5,10,16,.9)',color:'#fff',fontFamily:'system-ui',fontSize:11,pointerEvents:'none'}}><b>🚦 TRANSIT SAFETY DIRECTOR</b><div style={{marginTop:4}}>SIGNAL • <strong>{signal}</strong> • NETWORK • <strong>{network}</strong></div><div style={{opacity:.76,marginTop:3}}>{status}</div><div style={{opacity:.62,marginTop:3}}>RED enforces full brake. YELLOW limits approach speed. Boss recovery state follows the live rail events.</div></div>}
