import { ChangeEvent, useEffect, useState } from 'react'

type UnifiedState={state?:any;jobs?:any[];cities?:string[];translation?:any}
type CharacterRegistry={missions?:any[];guardianForce?:any}
const TYPES=['open-world','story','missions','creator','business','racing','sports','music','community']
export default function StreetVerseLifeHub(){
 const [open,setOpen]=useState(false),[snapshot,setSnapshot]=useState<UnifiedState>({}),[registry,setRegistry]=useState<CharacterRegistry>({}),[name,setName]=useState('My StreetVerse Avatar'),[face,setFace]=useState(''),[consent,setConsent]=useState(false)
 useEffect(()=>{const onState=(e:Event)=>setSnapshot((e as CustomEvent<UnifiedState>).detail||{}),onRegistry=(e:Event)=>setRegistry((e as CustomEvent<CharacterRegistry>).detail||{}),show=()=>{setOpen(true);window.dispatchEvent(new Event('tryamm:streetverse-unified-request'));window.dispatchEvent(new Event('tryamm:streetverse-character-request'))};window.addEventListener('tryamm:streetverse-unified-state',onState);window.addEventListener('tryamm:streetverse-character-registry',onRegistry);window.addEventListener('tryamm:streetverse-life-hub-open',show);window.dispatchEvent(new Event('tryamm:streetverse-unified-request'));window.dispatchEvent(new Event('tryamm:streetverse-character-request'));return()=>{window.removeEventListener('tryamm:streetverse-unified-state',onState);window.removeEventListener('tryamm:streetverse-character-registry',onRegistry);window.removeEventListener('tryamm:streetverse-life-hub-open',show)}},[])
 function pickFace(e:ChangeEvent<HTMLInputElement>){const f=e.target.files?.[0];if(!f)return;if(face.startsWith('blob:'))URL.revokeObjectURL(face);setFace(URL.createObjectURL(f))}
 const s=snapshot.state||{},cities=snapshot.cities||[],jobs=snapshot.jobs||[],guardianMissions=(registry.missions||[]).filter((m:any)=>m.assignedTo?.includes('al-b')||m.assignedTo?.includes('global-security-force'))
 const btn:React.CSSProperties={padding:'10px 12px',borderRadius:10,border:'1px solid #4fe3ff55',background:'#102333',color:'#fff',fontWeight:800,cursor:'pointer'}
 if(!window.location.pathname.startsWith('/streetverse'))return null
 return <><button onClick={()=>{setOpen(true);window.dispatchEvent(new Event('tryamm:streetverse-unified-request'));window.dispatchEvent(new Event('tryamm:streetverse-character-request'))}} style={{position:'fixed',left:12,bottom:72,zIndex:9003,...btn}}>🌍 STREETVERSE LIFE</button>{open&&<div style={{position:'fixed',inset:0,zIndex:11000,background:'#030711f4',color:'#fff',overflow:'auto',fontFamily:'Inter,system-ui'}}><div style={{maxWidth:1100,margin:'0 auto',padding:20}}><div style={{display:'flex',justifyContent:'space-between',gap:10}}><div><div style={{color:'#4fe3ff',fontWeight:900}}>STREETVERSE LIVING WORLD</div><h1 style={{margin:'4px 0'}}>One Avatar. One Life. Every City.</h1></div><button onClick={()=>setOpen(false)} style={btn}>CLOSE</button></div>
 <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(250px,1fr))',gap:12,marginTop:16}}>
  <section style={{background:'#09121d',padding:14,borderRadius:16,border:'1px solid #25384a'}}><h3>Avatar + Face</h3>{face&&<img src={face} alt="Avatar face preview" style={{width:96,height:96,borderRadius:'50%',objectFit:'cover'}}/>}<input value={name} onChange={e=>setName(e.target.value)} style={{width:'100%',boxSizing:'border-box',padding:9,margin:'8px 0',background:'#050a10',color:'#fff',border:'1px solid #334',borderRadius:8}}/><input type="file" accept="image/*" onChange={pickFace}/><label style={{display:'block',margin:'9px 0',fontSize:12}}><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/> I consent to use this image for my game avatar.</label><button disabled={!consent} onClick={()=>window.dispatchEvent(new CustomEvent('tryamm:streetverse-avatar-set',{detail:{displayName:name,faceImageUrl:face,consent}}))} style={btn}>SAVE AVATAR</button></section>
  <section style={{background:'#09121d',padding:14,borderRadius:16,border:'1px solid #25384a'}}><h3>Progression</h3><div>Level <b>{s.level||1}</b></div><div>XP <b>{s.xp||0}</b></div><div>Reputation <b>{s.reputation||0}</b></div><div>City <b>{s.city||'Chicago'}</b></div><div>Language <b>{s.language||navigator.language}</b></div><div style={{fontSize:12,color:'#9fb2c4',marginTop:8}}>Progression follows you across cities, missions, jobs, creator work and businesses.</div></section>
  <section style={{background:'#09121d',padding:14,borderRadius:16,border:'1px solid #25384a'}}><h3>Choose Game Type</h3><div style={{display:'flex',gap:6,flexWrap:'wrap'}}>{TYPES.map(t=><button key={t} onClick={()=>window.dispatchEvent(new CustomEvent('tryamm:streetverse-game-type',{detail:{gameType:t}}))} style={{...btn,background:s.gameType===t?'#164564':'#102333'}}>{t.toUpperCase()}</button>)}</div></section>
  <section style={{background:'#09121d',padding:14,borderRadius:16,border:'1px solid #25384a'}}><h3>Travel the World</h3><select value={s.city||'Chicago'} onChange={e=>window.dispatchEvent(new CustomEvent('tryamm:streetverse-city-travel',{detail:{city:e.target.value}}))} style={{width:'100%',padding:10,background:'#07101a',color:'#fff',border:'1px solid #345',borderRadius:8}}>{cities.map(c=><option key={c}>{c}</option>)}</select><div style={{fontSize:12,color:'#9fb2c4',marginTop:8}}>Travel loads the full city/country profile, local culture, districts, creator opportunities and Guardian mission focus while keeping your avatar, level, XP and reputation.</div></section>
  <section style={{background:'#09121d',padding:14,borderRadius:16,border:'1px solid #25384a'}}><h3>All Languages</h3><input value={s.language||''} placeholder="Language code, e.g. en, es, fr, ar, ja" onChange={e=>window.dispatchEvent(new CustomEvent('tryamm:language-changed',{detail:{language:e.target.value}}))} style={{width:'100%',boxSizing:'border-box',padding:10,background:'#07101a',color:'#fff',border:'1px solid #345',borderRadius:8}}/><div style={{fontSize:12,color:'#9fb2c4',marginTop:8}}>Translation runtime is configured for automatic source language and selected target language.</div></section>
  <section style={{background:'#09121d',padding:14,borderRadius:16,border:'1px solid #25384a'}}><h3>Jobs + Shifts</h3><div>{jobs.length?jobs.slice(0,8).map(j=><div key={j.id} style={{padding:'7px 0',borderBottom:'1px solid #233'}}><b>{j.title}</b><div style={{fontSize:11,color:'#9fb2c4'}}>{j.status} · min level {j.minLevel} · {j.remote?'remote':j.city||'local'}</div></div>):<div style={{color:'#9fb2c4'}}>Businesses can post jobs and AI matches workers by skills, level, language, accessibility and location.</div>}</div></section>
 </div></div></div>}</>
}
