import {Component,lazy,Suspense,useEffect,useMemo,useState,type ReactNode} from 'react'
import StreetVerseSafeWorld from './StreetVerseSafeWorld'
import StreetVerseWeatherSync from './StreetVerseWeatherSync'
import StreetVerseMobileGameShell from './StreetVerseMobileGameShell'

const StreetVerseMobileWorld=lazy(()=>import('./StreetVerseMobileWorld'))
const StreetVerseLivingWorld=lazy(()=>import('./StreetVerseLivingWorld'))

function isMobileDevice(){if(typeof navigator==='undefined')return false;return /iPhone|iPad|iPod|Android/i.test(navigator.userAgent||'')}
function hasUsableWebGL(){if(typeof document==='undefined')return false;try{const canvas=document.createElement('canvas');return !!(canvas.getContext('webgl2')||canvas.getContext('webgl')||canvas.getContext('experimental-webgl'))}catch{return false}}
export function shouldUseStreetVerseSafeMode(){if(typeof navigator==='undefined'||typeof window==='undefined')return false;const ua=navigator.userAgent||'';const appleMobile=/iPhone|iPad|iPod/i.test(ua);const memory=Number((navigator as Navigator & {deviceMemory?:number}).deviceMemory||0);const cores=Number(navigator.hardwareConcurrency||0);const narrow=Math.min(window.innerWidth||9999,window.innerHeight||9999)<=480;const constrained=(memory>0&&memory<=4)||(cores>0&&cores<=4);if(!hasUsableWebGL())return true;return !appleMobile&&narrow&&constrained}
class StreetVerseWorldBoundary extends Component<{onClose:()=>void;children:ReactNode},{failed:boolean}>{state={failed:false};static getDerivedStateFromError(){return {failed:true}};componentDidCatch(error:unknown){console.error('[StreetVerse] 3D world failed; keeping safe city visible',error)};render(){return this.state.failed?<StreetVerseSafeWorld onClose={this.props.onClose}/>:this.props.children}}
function MobileLoading(){return <div aria-label="StreetVerse 3D loading" style={{position:'fixed',inset:0,zIndex:14990,display:'grid',placeItems:'center',background:'#07101d',color:'#fff',fontFamily:'system-ui',fontWeight:900}}>STREETVERSE • STARTING 3D…</div>}
function MobileRuntimeGuard({onClose,children}:{onClose:()=>void;children:ReactNode}){const [safeFallback,setSafeFallback]=useState(false);useEffect(()=>{if(safeFallback||typeof window==='undefined')return;let healthy=false,lastHeartbeat=performance.now(),failed=false;const report=(state:'healthy'|'fallback',reason:string)=>window.dispatchEvent(new CustomEvent('tryamm:streetverse-runtime-health',{detail:{state,reason,mode:state==='fallback'?'mobile-safe':'mobile-lite',selfHealing:true,at:new Date().toISOString()}}));const markHealthy=()=>{healthy=true;lastHeartbeat=performance.now()};const fail=(reason:string)=>{if(failed||document.visibilityState==='hidden')return;failed=true;report('fallback',reason);window.dispatchEvent(new CustomEvent('tryamm:toast',{detail:{message:'StreetVerse 3D recovery activated • safe city is keeping gameplay available.'}}));setSafeFallback(true)};const onReady=(event:Event)=>{const detail=(event as CustomEvent<Record<string,unknown>>).detail||{};if(detail.mode==='mobile-lite'&&detail.canvas===true&&detail.htmlCity!==true){markHealthy();report('healthy','world-ready')}};const onPosition=(event:Event)=>{const detail=(event as CustomEvent<Record<string,unknown>>).detail||{};if(detail.mobileLite===true&&detail.htmlCity!==true&&detail.mobileSafeMode!==true)markHealthy()};const onContextLost=(event:Event)=>{const target=event.target as HTMLElement|null;if(target?.tagName==='CANVAS'){if('preventDefault' in event)event.preventDefault();fail('webgl-context-lost')}};window.addEventListener('tryamm:streetverse-world-ready',onReady);window.addEventListener('tryamm:streetverse-player-position',onPosition);window.addEventListener('webglcontextlost',onContextLost,true);const bootTimer=window.setTimeout(()=>{if(!healthy)report('healthy','mobile-boot-grace')},20000);const stallTimer=window.setInterval(()=>{if(healthy&&document.visibilityState==='visible'&&performance.now()-lastHeartbeat>30000)report('healthy','mobile-heartbeat-delayed')},5000);return()=>{window.clearTimeout(bootTimer);window.clearInterval(stallTimer);window.removeEventListener('tryamm:streetverse-world-ready',onReady);window.removeEventListener('tryamm:streetverse-player-position',onPosition);window.removeEventListener('webglcontextlost',onContextLost,true)}},[safeFallback]);if(safeFallback)return <><div style={{position:'fixed',top:64,left:12,zIndex:40010,padding:'7px 9px',borderRadius:10,background:'#5b1111ee',color:'#fff',fontFamily:'system-ui',fontSize:10,fontWeight:950}}>SAFE FALLBACK</div><StreetVerseSafeWorld onClose={onClose}/></>;return <><div style={{position:'fixed',top:64,left:12,zIndex:40010,padding:'7px 9px',borderRadius:10,background:'#063b2bee',color:'#fff',fontFamily:'system-ui',fontSize:10,fontWeight:950}}>3D MOBILE</div>{children}</>}
export default function StreetVersePlayableWorld({onClose}:{onClose:()=>void}){
 const safe=useMemo(shouldUseStreetVerseSafeMode,[])
 const mobile=useMemo(isMobileDevice,[])
 if(safe)return <><StreetVerseWeatherSync/><StreetVerseSafeWorld onClose={onClose}/><StreetVerseMobileGameShell onClose={onClose}/></>
 if(mobile)return <><StreetVerseWeatherSync/><StreetVerseWorldBoundary onClose={onClose}><MobileRuntimeGuard onClose={onClose}><Suspense fallback={<MobileLoading/>}><StreetVerseMobileWorld onClose={onClose}/></Suspense></MobileRuntimeGuard></StreetVerseWorldBoundary></>
 return <><StreetVerseWeatherSync/><StreetVerseWorldBoundary onClose={onClose}><Suspense fallback={<MobileLoading/>}><StreetVerseLivingWorld onClose={onClose}/></Suspense></StreetVerseWorldBoundary></>
}