import {useEffect,useState} from 'react'
type Line={id:string;name:string;mode:string;stops:string[];xp:number}
const LINES:Line[]=[{id:'red',name:'RED LINE',mode:'SUBWAY + ELEVATED',stops:['95TH','ROOSEVELT','JACKSON','LAKE','FULLERTON','HOWARD'],xp:360},{id:'blue',name:'BLUE LINE',mode:'SUBWAY + EXPRESSWAY',stops:["O'HARE",'LOGAN SQUARE','CLARK/LAKE','MONROE','UIC-HALSTED','FOREST PARK'],xp:380},{id:'brown',name:'BROWN LINE',mode:'ELEVATED',stops:['KIMBALL','WESTERN','BELMONT','CHICAGO','WASHINGTON/WELLS'],xp:300},{id:'green',name:'GREEN LINE',mode:'ELEVATED + SURFACE',stops:['HARLEM','ASHLAND','CLARK/LAKE','ROOSEVELT','GARFIELD','63RD'],xp:330},{id:'orange',name:'ORANGE LINE',mode:'ELEVATED',stops:['MIDWAY','PULASKI','HALSTED','ROOSEVELT','WASHINGTON/WELLS'],xp:320},{id:'pink',name:'PINK LINE',mode:'ELEVATED',stops:['54TH/CERMAK','KEDZIE','POLK','CLINTON','WASHINGTON/WELLS'],xp:300},{id:'purple',name:'PURPLE LINE',mode:'ELEVATED',stops:['LINDEN','DAVIS','HOWARD','BELMONT','CHICAGO','LOOP'],xp:340},{id:'yellow',name:'YELLOW LINE',mode:'SURFACE',stops:['DEMPSTER-SKOKIE','OAKTON-SKOKIE','HOWARD'],xp:240}]
export default function StreetVerseTransitLineMissionSelector(){const [line,setLine]=useState<Line|null>(null),[stop,setStop]=useState(0),[riders,setRiders]=useState(0),[doors,setDoors]=useState(false),[throttle,setThrottle]=useState(0),[brake,setBrake]=useState(1),[speed,setSpeed]=useState(0),[distance,setDistance]=useState(Infinity),[disabled,setDisabled]=useState(false)
 useEffect(()=>{if(!line)return;window.dispatchEvent(new CustomEvent('tryamm:transit-line-active',{detail:{lineId:line.id,lineName:line.name,stop:line.stops[stop],stopIndex:stop}}));window.dispatchEvent(new CustomEvent('tryamm:transit-announcement',{detail:{lineId:line.id,text:`${line.name}. Next stop ${line.stops[stop]}.`}}))},[line,stop])
 useEffect(()=>{const f=(e:Event)=>{const d=(e as CustomEvent).detail||{};if(line&&d.lineId===line.id){if(Number.isFinite(d.speed))setSpeed(Number(d.speed));if(Number.isFinite(d.distanceToStation))setDistance(Number(d.distanceToStation));setDisabled(!!d.disabled)}};window.addEventListener('tryamm:l-train-state',f);return()=>window.removeEventListener('tryamm:l-train-state',f)},[line])
 const control=(t:number,b:number)=>{if(!line||disabled)return;setThrottle(t);setBrake(b);window.dispatchEvent(new CustomEvent('tryamm:transit-operator-control',{detail:{lineId:line.id,throttle:t,brake:b}}))}
 const start=(l:Line)=>{setLine(l);setStop(0);setRiders(0);setDoors(false);setThrottle(0);setBrake(1);setSpeed(0);setDistance(Infinity);setDisabled(false);window.dispatchEvent(new CustomEvent('tryamm:streetverse-mission-start',{detail:{missionId:`transit-${l.id}-operator`,label:`${l.name} Operator`,financialReward:false}}))}
 const serviceStop=()=>{if(!line||disabled)return;if(!doors){if(speed>.8||distance>3.5){window.dispatchEvent(new CustomEvent('tryamm:transit-announcement',{detail:{lineId:line.id,text:speed>.8?'Reduce speed and stop before opening doors.':'Pull fully into the station before opening doors.'}}));return}control(0,1);setDoors(true);window.dispatchEvent(new CustomEvent('tryamm:l-train-doors',{detail:{open:true,lineId:line.id,station:line.stops[stop]}}));window.dispatchEvent(new CustomEvent('tryamm:transit-announcement',{detail:{lineId:line.id,text:`Doors open at ${line.stops[stop]}. Please allow passengers to exit before boarding.`}}));setRiders(v=>Math.max(0,v-(stop%3))+4+(stop%4));return}setDoors(false);window.dispatchEvent(new CustomEvent('tryamm:l-train-doors',{detail:{open:false,lineId:line.id,station:line.stops[stop]}}));window.dispatchEvent(new CustomEvent('tryamm:transit-announcement',{detail:{lineId:line.id,text:'Doors closing. Please stand clear.'}}));control(.55,0);if(stop===line.stops.length-1){window.dispatchEvent(new CustomEvent('tryamm:streetverse-mission-complete',{detail:{missionId:`transit-${line.id}-operator`,label:`${line.name} Operator`,xp:line.xp,financialReward:false,progressState:{line:line.id,passengers:riders,stations:line.stops.length}}}));setLine(null)}else setStop(v=>v+1)}
 if(!line)return <div style={{position:'fixed',right:12,top:132,zIndex:12004,width:230,padding:10,borderRadius:12,background:'rgba(4,10,18,.92)',color:'#fff',fontFamily:'system-ui',fontSize:11}}><b>🚇 TRANSIT ROUTES</b><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:5,marginTop:7}}>{LINES.map(l=><button key={l.id} onClick={()=>start(l)}>{l.name.replace(' LINE','')}</button>)}</div></div>
 const safe=speed<=.8&&distance<=3.5&&!disabled
 return <div style={{position:'fixed',right:12,top:132,zIndex:12004,width:278,padding:11,borderRadius:12,background:'rgba(4,10,18,.94)',color:'#fff',fontFamily:'system-ui',fontSize:12}}><b>🚇 {line.name} OPERATOR</b><div>{line.mode}</div><div style={{marginTop:6}}>STOP {stop+1}/{line.stops.length} • {line.stops[stop]}</div><div>Passengers • {riders} • Speed {speed.toFixed(1)}</div><div>Station distance • {Number.isFinite(distance)?distance.toFixed(1):'—'} {disabled?'• SERVICE DISABLED':safe?'• DOOR ZONE':''}</div><div style={{marginTop:7,display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:5}}><button disabled={doors||disabled} onClick={()=>control(.35,0)}>POWER 1</button><button disabled={doors||disabled} onClick={()=>control(.7,0)}>POWER 2</button><button disabled={doors||disabled} onClick={()=>control(1,0)}>POWER 3</button><button disabled={disabled} onClick={()=>control(0,.35)}>BRAKE 1</button><button disabled={disabled} onClick={()=>control(0,.7)}>BRAKE 2</button><button disabled={disabled} onClick={()=>control(0,1)}>FULL BRAKE</button></div><div style={{opacity:.72,marginTop:6}}>{disabled?'Emergency control has disabled this train.':doors?'Boarding/alighting. Close doors when clear.':safe?'Train is safely stopped in the station door zone.':'Manual throttle/brake active. Stop inside the station door zone.'}</div><button disabled={disabled||(!doors&&!safe)} onClick={serviceStop} style={{marginTop:7}}>{doors?'CLOSE DOORS • DEPART':'STOP • OPEN DOORS'}</button></div>}
