import {useEffect,useRef,useState} from 'react'

type Telemetry={entered?:boolean;speed?:number;signedSpeed?:number;throttle?:number;brake?:number;steer?:number;x?:number;z?:number;slipAngle?:number;lateralSpeed?:number;handbrake?:boolean;burnout?:boolean;wheelspin?:boolean;yawRate?:number}
type Collision={speed?:number;kind?:string;x?:number;z?:number}
type Opponent={id:string;name:string,progress:number,speed:number}
const DAMAGE_KEY='tryamm.streetverse.vehicle-condition.v1'
const ADV_KEY='tryamm.streetverse.advanced-driving.v1'
function loadDamage(){try{return Math.max(0,Math.min(100,Number(localStorage.getItem(DAMAGE_KEY)||100)||100))}catch{return 100}}
function loadMode(){try{return JSON.parse(localStorage.getItem(ADV_KEY)||'{}')?.vehicle||'CAR'}catch{return 'CAR'}}
const btn:React.CSSProperties={border:'1px solid #64ddff77',borderRadius:999,padding:'7px 10px',background:'#0b1723',color:'#fff',fontSize:9,fontWeight:950,cursor:'pointer'}
export default function StreetVerseAdvancedDrivingSystems(){
 const [driving,setDriving]=useState(false),[speed,setSpeed]=useState(0),[condition,setCondition]=useState(loadDamage),[vehicle,setVehicle]=useState<'CAR'|'MOTORCYCLE'>(loadMode),[response,setResponse]=useState('CLEAR'),[opponents,setOpponents]=useState<Opponent[]>([]),[race,setRace]=useState(false),[drift,setDrift]=useState(0),[combo,setCombo]=useState(1),[burnout,setBurnout]=useState(0),[donut,setDonut]=useState(0),[perf,setPerf]=useState('FULL'),[technique,setTechnique]=useState('GRIP')
 const telemetry=useRef<Telemetry>({}),raceStart=useRef(0),oppTick=useRef(0),lastT=useRef(0),spinMemory=useRef({sign:0,turns:0})
 useEffect(()=>{const low=((navigator as any).deviceMemory&&Number((navigator as any).deviceMemory)<=4)||(navigator.hardwareConcurrency&&navigator.hardwareConcurrency<=4)||matchMedia('(pointer:coarse)').matches&&innerWidth<700;setPerf(low?'PERFORMANCE':'FULL');dispatchEvent(new CustomEvent('tryamm:streetverse-performance',{detail:{mode:low?'performance':'quality',source:'advanced-driving'}}))
  const onVehicle=(e:Event)=>{const d=(e as CustomEvent).detail||{};setDriving(Boolean(d.entered));if(!d.entered){setDrift(0);setCombo(1);setBurnout(0);setDonut(0);setTechnique('GRIP');spinMemory.current={sign:0,turns:0}}}
  const onTelemetry=(e:Event)=>{const d=(e as CustomEvent<Telemetry>).detail||{};telemetry.current=d;setDriving(Boolean(d.entered));setSpeed(Number(d.speed)||0);const now=performance.now(),dt=Math.max(.016,Math.min(.08,lastT.current?(now-lastT.current)/1000:.016));lastT.current=now
   const v=Math.abs(Number(d.speed)||0),slip=Math.abs(Number(d.slipAngle)||0),lat=Math.abs(Number(d.lateralSpeed)||0),steer=Math.abs(Number(d.steer)||0),yaw=Number(d.yawRate)||0,handbrake=Boolean(d.handbrake),burn=Boolean(d.burnout||d.wheelspin)
   const driftActive=v>10&&slip>8&&lat>1.2
   if(driftActive){const quality=Math.min(2.2,(slip/28)+(lat/10)+(handbrake?.25:0));setTechnique(handbrake?'HANDBRAKE DRIFT':'DRIFT');setCombo(c=>Math.min(8,c+dt*(.28+quality*.16)));setDrift(s=>{const n=s+(v*(slip/18)*quality*dt*5*Math.max(1,combo));dispatchEvent(new CustomEvent('tryamm:streetverse-drift-score',{detail:{score:Math.round(n),combo,slipAngle:slip,lateralSpeed:lat,speed:v,handbrake,physics:'lateral-slip'}}));return n})}else if(!burn){setCombo(c=>Math.max(1,c-dt*.9));if(v>4)setTechnique('GRIP')}
   if(burn&&v<8){setTechnique('BURNOUT');setBurnout(s=>{const n=s+dt*(18+Math.max(0,Number(d.throttle)||0)*34);dispatchEvent(new CustomEvent('tryamm:streetverse-burnout-score',{detail:{score:Math.round(n),speed:v,throttle:d.throttle}}));return n})}
   const yawSign=Math.sign(yaw);if(v<14&&slip>12&&Math.abs(yaw)>.45){if(spinMemory.current.sign&&yawSign!==spinMemory.current.sign)spinMemory.current.turns*=.92;spinMemory.current.sign=yawSign;spinMemory.current.turns+=Math.abs(yaw)*dt;setTechnique('DONUT');if(spinMemory.current.turns>Math.PI*1.6){spinMemory.current.turns-=Math.PI*1.6;setDonut(s=>{const n=s+1;dispatchEvent(new CustomEvent('tryamm:streetverse-donut-score',{detail:{donuts:n,slipAngle:slip,yawRate:yaw}}));return n})}}else spinMemory.current.turns=Math.max(0,spinMemory.current.turns-dt*.8)
  }
  const onCollision=(e:Event)=>{const d=(e as CustomEvent<Collision>).detail||{},impact=Math.abs(Number(d.speed)||0),loss=Math.max(4,Math.min(28,impact*.7));setCondition(c=>{const n=Math.max(0,c-loss);try{localStorage.setItem(DAMAGE_KEY,String(n))}catch{}dispatchEvent(new CustomEvent('tryamm:streetverse-vehicle-damage',{detail:{condition:n,impact,kind:d.kind||'impact'}}));return n});if(impact>18){setResponse('EMERGENCY RESPONDING');dispatchEvent(new CustomEvent('tryamm:streetverse-emergency-response',{detail:{kind:'traffic-response',severity:impact>28?'high':'medium',x:d.x,z:d.z,services:['traffic-unit',impact>25?'medical':'road-assist']}}));setTimeout(()=>setResponse('CLEAR'),7000)}}
  const onMission=(e:Event)=>{const d=(e as CustomEvent).detail||{};setRace(true);raceStart.current=performance.now();setOpponents([{id:'nova',name:'NOVA',progress:0,speed:26},{id:'south',name:'SOUTH LOOP',progress:0,speed:24},{id:'lake',name:'LAKEFRONT',progress:0,speed:22}]);dispatchEvent(new CustomEvent('tryamm:streetverse-ai-opponents-start',{detail:{mission:d.id||d.label||'streetverse-mission',count:3,physics:'traction-aware'}}))}
  const onComplete=()=>{setRace(false);setOpponents([])}
  addEventListener('tryamm:streetverse-vehicle-controlled',onVehicle);addEventListener('tryamm:streetverse-drive-telemetry',onTelemetry);addEventListener('tryamm:streetverse-vehicle-collision',onCollision);addEventListener('tryamm:streetverse-mission-start',onMission);addEventListener('tryamm:streetverse-mission-expansion-start',onMission);addEventListener('tryamm:streetverse-mission-complete',onComplete)
  const id=setInterval(()=>{if(!race)return;const now=performance.now();if(now-oppTick.current<180)return;oppTick.current=now;setOpponents(list=>list.map((o,i)=>{const variance=1+Math.sin(now*.001+i*2)*.09;const next=Math.min(100,o.progress+(o.speed*variance)*.018);dispatchEvent(new CustomEvent('tryamm:streetverse-ai-opponent',{detail:{...o,progress:next,traction:1-(Math.sin(now*.0017+i)*.08)}}));return {...o,progress:next}}))},180)
  return()=>{clearInterval(id);removeEventListener('tryamm:streetverse-vehicle-controlled',onVehicle);removeEventListener('tryamm:streetverse-drive-telemetry',onTelemetry);removeEventListener('tryamm:streetverse-vehicle-collision',onCollision);removeEventListener('tryamm:streetverse-mission-start',onMission);removeEventListener('tryamm:streetverse-mission-expansion-start',onMission);removeEventListener('tryamm:streetverse-mission-complete',onComplete)}
 },[race,combo])
 const chooseVehicle=(v:'CAR'|'MOTORCYCLE')=>{setVehicle(v);try{localStorage.setItem(ADV_KEY,JSON.stringify({vehicle:v,updatedAt:new Date().toISOString()}))}catch{}dispatchEvent(new CustomEvent('tryamm:streetverse-vehicle-class-select',{detail:{vehicle:v,controlProfile:v==='MOTORCYCLE'?{steerGain:1.18,maxSpeed:43,lean:true}:{steerGain:1,maxSpeed:38,lean:false}}}))}
 const repair=()=>{if(speed>2)return;setCondition(100);try{localStorage.setItem(DAMAGE_KEY,'100')}catch{}dispatchEvent(new CustomEvent('tryamm:streetverse-vehicle-repaired',{detail:{condition:100,source:'service-bay'}}));setResponse('SERVICE COMPLETE');setTimeout(()=>setResponse('CLEAR'),2600)}
 return <div style={{position:'fixed',right:10,top:112,zIndex:16996,width:'min(88vw,300px)',padding:10,borderRadius:14,background:'#030914e8',border:'1px solid #63dcff55',color:'#fff',fontFamily:'system-ui',pointerEvents:'auto'}}><div style={{fontSize:9,fontWeight:950,color:'#70e8ff',letterSpacing:1}}>ADVANCED DRIVE • {perf}</div><div style={{display:'flex',justifyContent:'space-between',gap:8,marginTop:5,fontSize:11,fontWeight:900}}><span>{vehicle} • {driving?'ACTIVE':'READY'}</span><span>{Math.round(speed)} MPH</span></div><div style={{marginTop:5,fontSize:10,color:condition<35?'#ff7777':'#b8c8d6'}}>CONDITION {Math.round(condition)}% • {response}</div><div style={{marginTop:4,fontSize:10,color:'#ffd76b'}}>{technique} • DRIFT {Math.round(drift)} • x{combo.toFixed(1)}</div><div style={{marginTop:3,fontSize:9,color:'#ffb66c'}}>BURNOUT {Math.round(burnout)} • DONUTS {donut}</div>{race&&<div style={{marginTop:6,fontSize:9,color:'#d5e6f3'}}>AI GRID • {opponents.map(o=>`${o.name} ${Math.round(o.progress)}%`).join(' • ')}</div>}<div style={{display:'flex',gap:5,flexWrap:'wrap',marginTop:8}}><button style={btn} onClick={()=>chooseVehicle('CAR')}>CAR</button><button style={btn} onClick={()=>chooseVehicle('MOTORCYCLE')}>🏍 MOTORCYCLE</button><button style={{...btn,opacity:speed<=2?1:.45}} disabled={speed>2} onClick={repair}>🔧 REPAIR</button></div><div style={{marginTop:7,fontSize:8,color:'#8298aa',lineHeight:1.35}}>Real slip-angle drift chains • burnout/donut scoring • AI race telemetry • collision damage • repair/service • emergency-response events. Paid rewards remain server-authoritative.</div></div>
}
