import {useEffect,useRef} from 'react'

type Telemetry={entered?:boolean;speed?:number;signedSpeed?:number;throttle?:number;brake?:number;steer?:number}
export default function StreetVerseVehicleEffects(){
 const canvasRef=useRef<HTMLCanvasElement|null>(null)
 const state=useRef({entered:false,speed:0,throttle:0,brake:0,steer:0,lastThrottle:0,backfireUntil:0,skid:0})
 useEffect(()=>{const canvas=canvasRef.current;if(!canvas)return;const ctx=canvas.getContext('2d');if(!ctx)return;let raf=0,audio:AudioContext|null=null,skidOsc:OscillatorNode|null=null,skidGain:GainNode|null=null,noise:AudioBufferSourceNode|null=null,noiseGain:GainNode|null=null
  const ensureAudio=()=>{if(audio)return audio;audio=new AudioContext();return audio}
  const startSkid=()=>{const a=ensureAudio();if(skidOsc)return;skidOsc=a.createOscillator();skidGain=a.createGain();skidOsc.type='sawtooth';skidOsc.frequency.value=1150;skidGain.gain.value=.0001;skidOsc.connect(skidGain).connect(a.destination);skidOsc.start();const buffer=a.createBuffer(1,a.sampleRate*.4,a.sampleRate),data=buffer.getChannelData(0);for(let i=0;i<data.length;i++)data[i]=(Math.random()*2-1)*(1-i/data.length);noise=a.createBufferSource();noiseGain=a.createGain();noise.buffer=buffer;noise.loop=true;noiseGain.gain.value=.0001;noise.connect(noiseGain).connect(a.destination);noise.start()}
  const stopSkid=()=>{try{skidOsc?.stop();noise?.stop()}catch{}skidOsc=null;skidGain=null;noise=null;noiseGain=null}
  const onT=(e:Event)=>{const d=(e as CustomEvent<Telemetry>).detail||{},s=state.current;s.entered=Boolean(d.entered);s.speed=Math.abs(Number(d.speed)||0);s.throttle=Math.max(0,Math.min(1,Number(d.throttle)||0));s.brake=Math.max(0,Math.min(1,Number(d.brake)||0));s.steer=Math.max(-1,Math.min(1,Number(d.steer)||0));const skid=Math.max(s.brake>.45?s.brake:0,Math.abs(s.steer)>.58&&s.speed>16?Math.abs(s.steer):0);s.skid=skid;if(s.lastThrottle>.82&&s.throttle<.22&&s.speed>18)s.backfireUntil=performance.now()+180;s.lastThrottle=s.throttle;if(s.entered&&skid>.15){startSkid();if(audio?.state==='suspended')audio.resume();const level=Math.min(.09,.015+skid*.06);if(skidGain)skidGain.gain.setTargetAtTime(level,audio!.currentTime,.03);if(noiseGain)noiseGain.gain.setTargetAtTime(level*.55,audio!.currentTime,.03);if(skidOsc)skidOsc.frequency.setTargetAtTime(920+s.speed*9,audio!.currentTime,.04)}else if(skidGain&&audio){skidGain.gain.setTargetAtTime(.0001,audio.currentTime,.05);if(noiseGain)noiseGain.gain.setTargetAtTime(.0001,audio.currentTime,.05)}}
  addEventListener('tryamm:streetverse-drive-telemetry',onT)
  const particles:Array<{x:number;y:number;vx:number;vy:number;r:number;a:number}>=[];let last=performance.now();const draw=()=>{const now=performance.now(),dt=Math.min(.033,(now-last)/1000);last=now;const w=innerWidth,h=innerHeight,dpr=Math.min(devicePixelRatio,1.35);if(canvas.width!==Math.floor(w*dpr)||canvas.height!==Math.floor(h*dpr)){canvas.width=Math.floor(w*dpr);canvas.height=Math.floor(h*dpr);canvas.style.width=w+'px';canvas.style.height=h+'px';ctx.setTransform(dpr,0,0,dpr,0,0)}ctx.clearRect(0,0,w,h);const s=state.current;if(s.entered&&s.skid>.18&&s.speed>9){const count=s.skid>.7?3:1;for(let k=0;k<count;k++){for(const sx of [-1,1])particles.push({x:w*.5+sx*(44+Math.random()*8),y:h*.78+Math.random()*8,vx:sx*(8+Math.random()*15),vy:-20-Math.random()*25,r:9+Math.random()*12,a:.32+Math.random()*.18})}}for(let i=particles.length-1;i>=0;i--){const p=particles[i];p.x+=p.vx*dt;p.y+=p.vy*dt;p.r+=18*dt;p.a-=.35*dt;if(p.a<=0){particles.splice(i,1);continue}ctx.beginPath();ctx.fillStyle=`rgba(210,220,225,${p.a})`;ctx.arc(p.x,p.y,p.r,0,Math.PI*2);ctx.fill()}if(s.entered&&now<s.backfireUntil){const cx=w*.5-55,cy=h*.76;const len=22+Math.random()*18;ctx.save();ctx.translate(cx,cy);ctx.rotate(.12);const grad=ctx.createLinearGradient(0,0,-len,0);grad.addColorStop(0,'rgba(255,245,180,.95)');grad.addColorStop(.35,'rgba(255,135,25,.92)');grad.addColorStop(1,'rgba(70,150,255,0)');ctx.fillStyle=grad;ctx.beginPath();ctx.moveTo(0,-5);ctx.lineTo(-len,0);ctx.lineTo(0,5);ctx.closePath();ctx.fill();ctx.restore()}raf=requestAnimationFrame(draw)};draw();return()=>{cancelAnimationFrame(raf);removeEventListener('tryamm:streetverse-drive-telemetry',onT);stopSkid();audio?.close()}
 },[])
 return <canvas ref={canvasRef} aria-hidden="true" style={{position:'fixed',inset:0,zIndex:16994,pointerEvents:'none'}}/>
}
