import { useEffect, useMemo, useRef, useState } from 'react'

type Pos={x:number;z:number;character?:string}
type TargetKind='resident'|'spirit'|'business'|'vehicle'|'mission'|'basketball'
type Target={id:string;kind:TargetKind;label:string;copy:string;x:number;z:number;action:string}
const PROGRESS_KEY='tryamm.streetverse.living-layer.v4'
const TARGETS:Target[]=[
{id:'studio',kind:'business',label:'Aniyah 64 Track Studio',copy:'Recording sessions, creator missions and Reel moments are active here.',x:-42,z:-30,action:'ENTER STUDIO'},
{id:'market',kind:'business',label:'All American Marketplace',copy:'Shop, sell and discover StreetVerse businesses from this district.',x:42,z:-24,action:'OPEN MARKET'},
{id:'network',kind:'business',label:'All American Network',copy:'Broadcast and creator publishing hub connected to TRYAMM LIVE.',x:38,z:38,action:'OPEN NETWORK'},
{id:'after-dark',kind:'business',label:'Chicago After Dark',copy:'Nightlife district mission hub with creator and social events.',x:-38,z:38,action:'ENTER DISTRICT'},
{id:'vehicle-01',kind:'vehicle',label:'StreetVerse Vehicle',copy:'A nearby procedural vehicle is ready for player control.',x:0,z:48,action:'ENTER VEHICLE'},
{id:'resident-01',kind:'resident',label:'Chicago Resident',copy:'Resident awareness is active. Talk, receive local hints, and discover nearby missions.',x:0,z:18,action:'TALK'},
{id:'spirit-01',kind:'spirit',label:'AI Spirit',copy:'A holographic guide can surface world hints, mission context and creator routes.',x:12,z:30,action:'ASK SPIRIT'},
{id:'court-south-loop',kind:'basketball',label:'South Loop Holo Court',copy:'Street basketball connected to GameVerse.',x:-24,z:18,action:'OPEN COURT'},
{id:'court-lakefront',kind:'basketball',label:'Lakefront Lights',copy:'Street basketball connected to GameVerse.',x:62,z:46,action:'OPEN COURT'}]
const residentLines=['Welcome to StreetVerse. The city reacts to where you go now.','Try the Marketplace or Creator Studio — both have district missions nearby.','Traffic is live. Use the crosswalks and watch the signal cycle.','Your Reel button can capture the StreetVerse canvas when the browser supports it.','Explore the glowing checkpoints to complete District 01.']
const spiritLines=['AI Spirit online. I can point you toward missions, creator businesses and GameVerse activities.','The main StreetVerse world is procedural-first. Missing external assets cannot block play.','Try a business portal, basketball court, vehicle interaction or Reel capture next.']
function loadProgress(){try{return JSON.parse(localStorage.getItem(PROGRESS_KEY)||'{}') as {visited?:string[];talks?:number;spiritTalks?:number;vehicleEntered?:boolean;courts?:string[]}}catch{return {}}}
function nearestTarget(pos:Pos|null){if(!pos)return null;let best:{target:Target;distance:number}|null=null;for(const target of TARGETS){const distance=Math.hypot(pos.x-target.x,pos.z-target.z);if(!best||distance<best.distance)best={target,distance}}return best&&best.distance<15?best:null}
export default function StreetVerseLivingLayer(){
 const initial=loadProgress(),[pos,setPos]=useState<Pos|null>(null),[message,setMessage]=useState('CITY AWARENESS ONLINE'),[interaction,setInteraction]=useState(''),[quality,setQuality]=useState<'BALANCED'|'PERFORMANCE'>('BALANCED'),[visited,setVisited]=useState<string[]>(initial.visited||[]),[talks,setTalks]=useState(initial.talks||0),[spiritTalks,setSpiritTalks]=useState(initial.spiritTalks||0),[courts,setCourts]=useState<string[]>(initial.courts||[]),[vehicleEntered,setVehicleEntered]=useState(Boolean(initial.vehicleEntered));const lastNear=useRef(''),near=useMemo(()=>nearestTarget(pos),[pos]),completed=visited.length
 useEffect(()=>{try{localStorage.setItem(PROGRESS_KEY,JSON.stringify({visited,talks,spiritTalks,courts,vehicleEntered,updatedAt:new Date().toISOString()}))}catch{}},[visited,talks,spiritTalks,courts,vehicleEntered])
 useEffect(()=>{const mobile=/iPhone|iPad|iPod|Android/i.test(navigator.userAgent),lowThreads=(navigator.hardwareConcurrency||8)<=4;if(mobile||lowThreads)setQuality('PERFORMANCE');const onPos=(e:Event)=>{const d=(e as CustomEvent<Pos>).detail;if(Number.isFinite(d?.x)&&Number.isFinite(d?.z))setPos(d)};const onCaptured=()=>setMessage('REEL CAPTURED • READY TO SHARE');window.addEventListener('tryamm:streetverse-player-position',onPos);window.addEventListener('tryamm:streetverse-reel-captured',onCaptured);return()=>{window.removeEventListener('tryamm:streetverse-player-position',onPos);window.removeEventListener('tryamm:streetverse-reel-captured',onCaptured)}},[])
 useEffect(()=>{document.documentElement.dataset.streetverseQuality=quality.toLowerCase();window.dispatchEvent(new CustomEvent('tryamm:streetverse-performance',{detail:{mode:quality.toLowerCase()}}))},[quality])
 useEffect(()=>{const id=near?.target.id||'';if(id&&id!==lastNear.current){lastNear.current=id;setMessage(`${near?.target.kind.toUpperCase()} NEARBY • ${near?.target.label}`);window.dispatchEvent(new CustomEvent('tryamm:streetverse-proximity',{detail:{...near?.target,distance:near?.distance}}))}if(!id)lastNear.current=''},[near])
 const openReel=()=>{setMessage('REEL CREATOR • STREETVERSE HIGHLIGHT');window.dispatchEvent(new CustomEvent('tryamm:media-studio-open',{detail:{source:'streetverse',title:'StreetVerse Highlight',caption:'Captured in StreetVerse • #TRYAMM #StreetVerse'}}));window.dispatchEvent(new CustomEvent('tryamm:streetverse-reel-open',{detail:{x:pos?.x,z:pos?.z}}))}
 const drive=(throttle:number,brake:number,steer:number)=>{if(!vehicleEntered)return;window.dispatchEvent(new CustomEvent('tryamm:streetverse-drive-input',{detail:{throttle,brake,steer,source:'living-layer-v4'}}));window.dispatchEvent(new CustomEvent('tryamm:streetverse-drive-telemetry',{detail:{throttle,brake,steer,speed:throttle*18}}))}
 const horn=()=>{if(vehicleEntered)window.dispatchEvent(new CustomEvent('tryamm:streetverse-horn',{detail:{source:'living-layer-v4'}}))}
 function interact(){if(!near){setInteraction('Move closer to a resident, AI Spirit, vehicle, business, mission marker, or basketball court.');return}const {target}=near;if(target.kind==='resident'){const next=residentLines[talks%residentLines.length];setTalks(v=>v+1);setInteraction(`${target.label}: ${next}`);window.dispatchEvent(new CustomEvent('tryamm:streetverse-resident-talk',{detail:{label:target.label,text:next,talkNumber:talks+1}}));return}if(target.kind==='spirit'){const next=spiritLines[spiritTalks%spiritLines.length];setSpiritTalks(v=>v+1);setInteraction(`${target.label}: ${next}`);window.dispatchEvent(new CustomEvent('tryamm:streetverse-ai-spirit',{detail:{id:target.id,label:target.label,text:next}}));return}if(target.kind==='business'){setVisited(c=>c.includes(target.id)?c:[...c,target.id]);setInteraction(`${target.label}: ${target.copy}`);window.dispatchEvent(new CustomEvent('tryamm:streetverse-location-visited',{detail:{id:target.id,label:target.label}}));return}if(target.kind==='basketball'){setCourts(c=>c.includes(target.id)?c:[...c,target.id]);setInteraction(`${target.label}: basketball activity ready.`);window.dispatchEvent(new CustomEvent('tryamm:basketball-open',{detail:{court:target.id,source:'streetverse'}}));return}if(target.kind==='vehicle'){const next=!vehicleEntered;setVehicleEntered(next);setInteraction(next?'VEHICLE MODE • WASD/arrows/touch/gamepad drive • H horn • E exit.':'ON FOOT • vehicle released.');setMessage(next?'DRIVING CONTROL REQUESTED':'CITY AWARENESS ONLINE');window.dispatchEvent(new CustomEvent('tryamm:streetverse-vehicle-interact',{detail:{x:pos?.x,z:pos?.z,entered:next,source:'living-layer-v4'}}))}}
 useEffect(()=>{const onKey=(e:KeyboardEvent)=>{if(e.repeat)return;const k=e.key.toLowerCase();if(k==='e'){e.preventDefault();interact()}if(k==='r'){e.preventDefault();openReel()}if(vehicleEntered&&k==='h'){e.preventDefault();horn()}};const onDriveKey=(e:KeyboardEvent)=>{if(!vehicleEntered)return;const k=e.key.toLowerCase();if(['w','arrowup'].includes(k))drive(1,0,0);if(['s','arrowdown'].includes(k))drive(0,1,0);if(['a','arrowleft'].includes(k))drive(.35,0,-1);if(['d','arrowright'].includes(k))drive(.35,0,1);if(k===' ')drive(0,1,0)};const stop=()=>vehicleEntered&&drive(0,0,0);window.addEventListener('keydown',onKey);window.addEventListener('keydown',onDriveKey);window.addEventListener('keyup',stop);return()=>{window.removeEventListener('keydown',onKey);window.removeEventListener('keydown',onDriveKey);window.removeEventListener('keyup',stop)}},[vehicleEntered,near,talks,spiritTalks,pos])
 return <><div style={{position:'fixed',left:12,bottom:88,zIndex:16991,display:'grid',gap:6,pointerEvents:'none',fontFamily:'system-ui,sans-serif'}}><div style={{padding:'7px 9px',borderRadius:999,background:'#04121ddd',border:'1px solid #4fe3ff66',color:'#bdf7ff',fontSize:9,fontWeight:900}}>CITY AI • {quality} • {vehicleEntered?'VEHICLE CONTROL':'ON FOOT'}</div><div style={{padding:'7px 9px',borderRadius:999,background:'#07101ddd',border:'1px solid #e8b94455',color:'#ffe49b',fontSize:9,fontWeight:900}}>DISTRICT 01 • {completed}/4 LOCATIONS • {talks} TALKS • {courts.length} COURTS</div>{near&&<div style={{maxWidth:260,padding:'9px 10px',borderRadius:12,background:'#050b13ee',border:'1px solid #e8b94477',color:'#fff',fontSize:10,lineHeight:1.4}}><b>{near.target.kind.toUpperCase()} • {near.target.label}</b><br/><span style={{opacity:.72}}>{near.distance.toFixed(1)}m away • E / INTERACT</span></div>}</div><div style={{position:'fixed',right:14,bottom:18,zIndex:16992,display:'grid',gap:7,width:'min(88vw,310px)',fontFamily:'system-ui,sans-serif'}}><div role="status" style={{padding:'8px 10px',borderRadius:10,background:'#050b13dd',border:'1px solid #4fe3ff44',color:'#bdf7ff',fontSize:9,fontWeight:900}}>{message}</div>{interaction&&<div role="status" style={{padding:'10px 11px',borderRadius:12,background:'#07101eee',border:'1px solid #4fe3ff55',color:'#dffaff',fontSize:11,lineHeight:1.45}}>{interaction}</div>}<div style={{display:'flex',gap:7,justifyContent:'flex-end',flexWrap:'wrap'}}>{vehicleEntered&&<button onClick={horn} style={buttonStyle}>📣 HORN</button>}<button onClick={()=>setQuality(v=>v==='BALANCED'?'PERFORMANCE':'BALANCED')} style={buttonStyle}>{quality}</button><button onClick={openReel} style={buttonStyle}>🎥 REEL</button><button onClick={interact} style={buttonStyle}>{vehicleEntered?'EXIT VEHICLE':near?.target.action||'INTERACT'}</button></div></div></>}
const buttonStyle:React.CSSProperties={minHeight:44,padding:'0 12px',borderRadius:999,border:'1px solid #4fe3ff77',background:'#071725ee',color:'#fff',fontSize:10,fontWeight:950,cursor:'pointer'}
