// Auto-extracted from StreetVerseGeoSpawnBridge: the full non-safe StreetVerse
// overlay/mission/multiplayer stack. Loaded LAZILY so that none of this code
// (nor the three.js it transitively imports) sits in the initial StreetVerse
// route chunk. On constrained iOS 16 Safari the safe-mode HTML city renders
// from a three-free chunk; these overlays only download when full mode runs.
import type {ReactElement} from 'react'
import StreetVerseNextLevelHUD from './StreetVerseNextLevelHUD'
import StreetVerseLiveBuildBadge from './StreetVerseLiveBuildBadge'
import StreetVerseRealtimePresence from './StreetVerseRealtimePresence'
import StreetVerseNearbyPlayers from './StreetVerseNearbyPlayers'
import StreetVerseRemotePlayerMarkers from './StreetVerseRemotePlayerMarkers'
import StreetVersePlayerInteractions from './StreetVersePlayerInteractions'
import StreetVerseSharedWorldAvatars from './StreetVerseSharedWorldAvatars'
import StreetVerseNativeRemotePlayers from './StreetVerseNativeRemotePlayers'
import StreetVerseWorldEvents from './StreetVerseWorldEvents'
import StreetVerseCoopSync from './StreetVerseCoopSync'
import StreetVerseRaceSessionSync from './StreetVerseRaceSessionSync'
import StreetVerseRaceCountdownSync from './StreetVerseRaceCountdownSync'
import StreetVerseCrewPersistence from './StreetVerseCrewPersistence'
import StreetVersePartyBeacon from './StreetVersePartyBeacon'
import StreetVerseRiggedPlayerFallback from './StreetVerseRiggedPlayerFallback'
import StreetVerseLivingLayer from './StreetVerseLivingLayer'
import StreetVerseSoundEngine from './StreetVerseSoundEngine'
import StreetVerseDriveStatus from './StreetVerseDriveStatus'
import StreetVerseGamepadBridge from './StreetVerseGamepadBridge'
import StreetVerseTouchDriveControls from './StreetVerseTouchDriveControls'
import StreetVerseDriveMission from './StreetVerseDriveMission'
import StreetVerseRaceMissionGiver from './StreetVerseRaceMissionGiver'
import StreetVerseRaceNavigator from './StreetVerseRaceNavigator'
import StreetVerseMissionExpansion from './StreetVerseMissionExpansion'
import StreetVerseAdvancedDrivingSystems from './StreetVerseAdvancedDrivingSystems'
import StreetVerseVehicleEffects from './StreetVerseVehicleEffects'
import StreetVerseSceneTransition from './StreetVerseSceneTransition'
import StreetVerseAIRacerLayer from './StreetVerseAIRacerLayer'
import StreetVerseMotorcycleSystems from './StreetVerseMotorcycleSystems'
import StreetVersePowersportsGarage from './StreetVersePowersportsGarage'
import StreetVerseNativePowersportAdapter from './StreetVerseNativePowersportAdapter'
import StreetVerseProgressSync from './StreetVerseProgressSync'
import StreetVerseGameplayStateCoordinator from './StreetVerseGameplayStateCoordinator'
import StreetVerseStarMissions from './StreetVerseStarMissions'
import StreetVerseDialogueHUD from './StreetVerseDialogueHUD'
import StreetVerseStarMissionEncounterLayer from './StreetVerseStarMissionEncounterLayer'
import StreetVerseAmbientLife from './StreetVerseAmbientLife'
import StreetVerseEmergencyLighting from './StreetVerseEmergencyLighting'
import StreetVerseCityReaction from './StreetVerseCityReaction'
import StreetVerseEmergencyIncidentLifecycle from './StreetVerseEmergencyIncidentLifecycle'
import StreetVerseLawEnforcementComms from './StreetVerseLawEnforcementComms'
import StreetVerseRoadblockController from './StreetVerseRoadblockController'
import StreetVerseResponderStaging from './StreetVerseResponderStaging'
import StreetVerseResponderNPCController from './StreetVerseResponderNPCController'
import StreetVersePursuitController from './StreetVersePursuitController'
import StreetVerseChicagoActivityDirector from './StreetVerseChicagoActivityDirector'
import StreetVerseChicagoStorefronts from './StreetVerseChicagoStorefronts'
import StreetVerseChicagoInteriors from './StreetVerseChicagoInteriors'
import StreetVerseShoppingCore from './StreetVerseShoppingCore'
import StreetVerseLOperatorMission from './StreetVerseLOperatorMission'
import StreetVerseCityMissionPack from './StreetVerseCityMissionPack'
import StreetVerseTransitBossMission from './StreetVerseTransitBossMission'
import StreetVerseTransitLineMissionSelector from './StreetVerseTransitLineMissionSelector'
import StreetVerseTransitSafetyDirector from './StreetVerseTransitSafetyDirector'

type Mapped={x:number;z:number;label:string}|undefined

export default function StreetVerseFullWorldOverlays({onClose,mapped}:{onClose:()=>void;mapped:Mapped}):ReactElement{
  return <><StreetVerseLiveBuildBadge/><StreetVerseRealtimePresence/><StreetVerseNearbyPlayers/><StreetVerseRemotePlayerMarkers/><StreetVersePlayerInteractions/><StreetVerseSharedWorldAvatars/><StreetVerseNativeRemotePlayers/><StreetVerseWorldEvents/><StreetVerseCoopSync/><StreetVerseRaceSessionSync/><StreetVerseRaceCountdownSync/><StreetVerseCrewPersistence/><StreetVersePartyBeacon/><StreetVerseRiggedPlayerFallback/><StreetVerseLivingLayer/><StreetVerseSoundEngine/><StreetVerseAmbientLife/><StreetVerseEmergencyLighting/><StreetVerseCityReaction/><StreetVerseEmergencyIncidentLifecycle/><StreetVerseLawEnforcementComms/><StreetVerseRoadblockController/><StreetVerseResponderStaging/><StreetVerseResponderNPCController/><StreetVersePursuitController/><StreetVerseProgressSync/><StreetVerseGameplayStateCoordinator/><StreetVerseStarMissions/><StreetVerseDialogueHUD/><StreetVerseStarMissionEncounterLayer/><StreetVerseDriveStatus/><StreetVerseGamepadBridge/><StreetVerseTouchDriveControls/><StreetVerseDriveMission/><StreetVerseRaceMissionGiver/><StreetVerseRaceNavigator/><StreetVerseMissionExpansion/><StreetVerseChicagoActivityDirector/><StreetVerseChicagoStorefronts/><StreetVerseChicagoInteriors/><StreetVerseShoppingCore/><StreetVerseLOperatorMission/><StreetVerseTransitLineMissionSelector/><StreetVerseTransitSafetyDirector/><StreetVerseCityMissionPack/><StreetVerseTransitBossMission/><StreetVerseAdvancedDrivingSystems/><StreetVerseVehicleEffects/><StreetVerseAIRacerLayer/><StreetVerseMotorcycleSystems/><StreetVersePowersportsGarage/><StreetVerseNativePowersportAdapter/><StreetVerseSceneTransition onClose={onClose}/><StreetVerseNextLevelHUD district={mapped?.label?`CHICAGO • ${mapped.label.toUpperCase()}`:'CHICAGO • DISTRICT 01'} assetStatus="WORLD ACTIVE • SAFE MOBILE PLAY + STAR ENCOUNTERS + STAR MISSIONS + DIALOGUE HUD + PERSISTENT GAMEPLAY + TRANSIT SAFETY + ALL-LINE MISSIONS + TRANSIT BOSS + FULL RAIL/SUBWAY + CITY MISSIONS + PASSENGERS + SHOPPING + MULTIPLAYER + SERVER XP + RESPONDERS"/>{mapped&&<div style={{position:'fixed',left:12,bottom:12,zIndex:16995,maxWidth:300,padding:'10px 12px',borderRadius:12,background:'rgba(3,12,20,.84)',border:'1px solid #62b8ff77',color:'#fff',fontFamily:'system-ui',fontSize:12}}><strong>CHICAGO NAV SPAWN</strong><br/>{mapped.label}<br/><span style={{opacity:.75}}>Selected from Twin World • real-world destination mapped into the playable district.</span></div>}</>
}
