import {useEffect,useRef} from 'react'

type Telemetry={entered?:boolean;speed?:number;signedSpeed?:number;throttle?:number;brake?:number;steer?:number}
export default function StreetVerseVehicleEffects(){
 const canvasRef=useRef<HTMLCanvasElement|null>(null)
 const state=useRef({entered:false,speed:0,throttle:0,brake:0,steer:0,lastThrottle:0,backfireUntil:0,skid:0,burnout:0,launchUntil:0})
 useEffect(()=>{const canvas=canvasRef.current;if(!canvas)return;const ctx=canvas.getContext('2d');if(!ctx)return;const low=((navigator as any).deviceMemory&&Number((navigator as any).deviceMemory)<=4)||(navigator.hardwareConcurrency&&navigator.hardwareConcurrency<=4)||matchMedia('(pointer:coarse)').matches&&innerWidth<700;let raf=0,audio:AudioContext|null=null,skidOsc:OscillatorNode|null=null,skidGain:GainNode|null=null,noise:AudioBufferSourceNode|null=null,noiseGain:GainNode|null=null
  const ensureAudio=()=>{if(audio)return audio;audio=new AudioContext();return audio}
  const startSkid=()=>{const a=ensureAudio();if(skidOsc)return;skidOsc=a.createOscillator();skidGain=a.createGain();skidOsc.type='sawtooth';skidOsc.frequency.value=1150;skidGain.gain.value=.0001;skidOsc.connect(skidGain).connect(a.destination);skidOsc.start();const buffer=a.createBuffer(1,a.sampleRate*.4,a.sampleRate),data=buffer.getChannelData(0);for(let i=0;i<data.length;i++)data[i]=(Math.random()*2-1)*(1-i/data.length);noise=a.createBufferSource();noiseGain=a.createGain();noise.buffer=buffer;noise.loop=true;noiseGain.gain.value=.0001;noise.connect(noiseGain).connect(a.destination);noise.start()}
  const stopSkid=()=>{try{skidOsc?.stop();noise?.stop()}catch{}skidOsc=null;skidGain=null;noise=null;noiseGain=null}
  const onT=(e:Event)=>{const d=(e as CustomEvent<Telemetry>).detail||{},s=state.current;s.entered=Boolean(d.entered);const priorSpeed=s.speed;s.speed=Math.abs(Number(d.speed)||0);s.throttle=Math.max(0,Math.min(1,Number(d.throttle)||0));s.brake=Math.max(0,Math.min(1,Number(d.brake)||0));s.steer=Math.max(-1,Math.min(1,Number(d.steer)||0));s.burnout=s.entered&&s.throttle>.82&&s.brake>.42&&s.speed<8?Math.min(1,(s.throttle+s.brake)/1.5):0;const skid=Math.max(s.burnout,s.brake>.45&&s.speed>8?s.brake:0,Math.abs(s.steer)>.58&&s.speed>16?Math.abs(s.steer):0);s.skid=skid;if(s.lastThrottle>.82&&s.throttle<.22&&s.speed>18)s.backfireUntil=performance.now()+220;if(priorSpeed<4&&s.speed>10&&s.throttle>.75)s.launchUntil=performance.now()+500;s.lastThrottle=s.throttle;if(s.entered&&skid>.12){startSkid();if(audio?.state==='suspended')audio.resume();const level=Math.min(.12,.02+skid*.08+(s.burnout?0.02:0));if(skidGain)skidGain.gain.setTargetAtTime(level,audio!.currentTime,.025);if(noiseGain)noiseGain.gain.setTargetAtTime(level*.65,audio!.currentTime,.025);if(skidOsc)skidOsc.frequency.setTargetAtTime((s.burnout?760:920)+s.speed*10,audio!.currentTime,.035)}else if(skidGain&&audio){skidGain.gain.setTargetAtTime(.0001,audio.currentTime,.05);if(noiseGain)noiseGain.gain.setTargetAtTime(.0001,audio.currentTime,.05)}if(s.burnout>.5)dispatchEvent(new CustomEvent('tryamm:streetverse-burnout',{detail:{intensity:s.burnout,speed:s.speed}}))}
  addEventListener('tryamm:streetverse-drive-telemetry',onT)
  const particles:Array<{x:number;y:number;vx:number;vy:number;r:number;a:number,dark?:boolean}>=[],marks:Array<{x:number;y:number;a:number,w:number}>=[];let last=performance.now(),markTick=0;const draw=()=>{const now=performance.now(),dt=Math.min(.033,(now-last)/1000);last=now;const w=innerWidth,h=innerHeight,dpr=Math.min(devicePixelRatio,low?1:1.35);if(canvas.width!==Math.floor(w*dpr)||canvas.height!==Math.floor(h*dpr)){canvas.width=Math.floor(w*dpr);canvas.height=Math.floor(h*dpr);canvas.style.width=w+'px';canvas.style.height=h+'px';ctx.setTransform(dpr,0,0,dpr,0,0)}ctx.clearRect(0,0,w,h);const s=state.current;const activeSmoke=s.entered&&((s.skid>.18&&s.speed>7)||s.burnout>.25||now<s.launchUntil);if(activeSmoke){const intensity=Math.max(s.skid,s.burnout,now<s.launchUntil?.55:0),count=low?1:Math.max(1,Math.round(1+intensity*3));for(let k=0;k<count;k++)for(const sx of [-1,1])particles.push({x:w*.5+sx*(42+Math.random()*10),y:h*.79+Math.random()*10,vx:sx*(7+Math.random()*18),vy:-18-Math.random()*30,r:8+Math.random()*14,a:.28+Math.random()*.24,dark:s.burnout>.45&&Math.random()>.45});if(now-markTick>75&&(s.burnout>.25||s.skid>.55)){markTick=now;for(const sx of [-1,1])marks.push({x:w*.5+sx*40,y:h*.825,a:.32,w:3+Math.random()*2})}}
   for(let i=marks.length-1;i>=0;i--){const m=marks[i];m.a-=.08*dt;if(m.a<=0){marks.splice(i,1);continue}ctx.fillStyle=`rgba(18,18,20,${m.a})`;ctx.fillRect(m.x-m.w/2,m.y,m.w,18)}
   for(let i=particles.length-1;i>=0;i--){const p=particles[i];p.x+=p.vx*dt;p.y+=p.vy*dt;p.r+=20*dt;p.a-=.34*dt;if(p.a<=0){particles.splice(i,1);continue}ctx.beginPath();ctx.fillStyle=p.dark?`rgba(95,95,95,${p.a*.85})`:`rgba(215,222,226,${p.a})`;ctx.arc(p.x,p.y,p.r,0,Math.PI*2);ctx.fill()}
   if(s.entered&&now<s.backfireUntil){for(let burst=0;burst<(low?1:2);burst++){const cx=w*.5-55-burst*4,cy=h*.76+burst*2,len=24+Math.random()*22;ctx.save();ctx.translate(cx,cy);ctx.rotate(.12);const grad=ctx.createLinearGradient(0,0,-len,0);grad.addColorStop(0,'rgba(255,250,195,.98)');grad.addColorStop(.28,'rgba(255,155,30,.96)');grad.addColorStop(.62,'rgba(80,150,255,.75)');grad.addColorStop(1,'rgba(70,150,255,0)');ctx.fillStyle=grad;ctx.beginPath();ctx.moveTo(0,-6);ctx.lineTo(-len,0);ctx.lineTo(0,6);ctx.closePath();ctx.fill();ctx.restore()}}
   raf=requestAnimationFrame(draw)};draw();return()=>{cancelAnimationFrame(raf);removeEventListener('tryamm:streetverse-drive-telemetry',onT);stopSkid();audio?.close()}
 },[])
 return <canvas ref={canvasRef} aria-hidden="true" style={{position:'fixed',inset:0,zIndex:16994,pointerEvents:'none'}}/>
}
