import { useEffect, useRef, useState } from 'react'

declare global { interface Window { Cesium?: any; CESIUM_BASE_URL?: string } }
const CESIUM_VERSION='1.138'
const CESIUM_BASE=`https://cdn.jsdelivr.net/npm/cesium@${CESIUM_VERSION}/Build/Cesium/`
const CHICAGO={id:'chicago',label:'CHICAGO',city:'Chicago',country:'USA',lon:-87.6298,lat:41.8781,height:2100}
const DESTINATION_KEY='tryamm.streetverse.planet-destination.v2'
const CHICAGO_PLACES=[
 {id:'loop',label:'THE LOOP',city:'Chicago',country:'USA',lon:-87.6298,lat:41.8781,height:1500},
 {id:'millennium',label:'MILLENNIUM PARK',city:'Chicago',country:'USA',lon:-87.6226,lat:41.8826,height:900},
 {id:'lakefront',label:'LAKEFRONT',city:'Chicago',country:'USA',lon:-87.6079,lat:41.8840,height:1200},
 {id:'river',label:'CHICAGO RIVER',city:'Chicago',country:'USA',lon:-87.6267,lat:41.8883,height:900},
 {id:'south',label:'SOUTH SIDE',city:'Chicago',country:'USA',lon:-87.6244,lat:41.7943,height:1800},
 {id:'west',label:'WEST SIDE',city:'Chicago',country:'USA',lon:-87.7000,lat:41.8810,height:2200},
 {id:'north',label:'NORTH SIDE',city:'Chicago',country:'USA',lon:-87.6533,lat:41.9400,height:2200},
 {id:'ohare',label:"O'HARE",city:'Chicago',country:'USA',lon:-87.9073,lat:41.9742,height:3000},
 {id:'midway',label:'MIDWAY',city:'Chicago',country:'USA',lon:-87.7522,lat:41.7868,height:2600},
]
const PLANET_PLACES=[
 CHICAGO,
 {id:'greenville',label:'GREENVILLE',city:'Greenville',country:'USA',lon:-89.4131,lat:38.8923,height:180000},
 {id:'st-louis',label:'ST. LOUIS',city:'St. Louis',country:'USA',lon:-90.1994,lat:38.6270,height:180000},
 {id:'detroit',label:'DETROIT',city:'Detroit',country:'USA',lon:-83.0458,lat:42.3314,height:180000},
 {id:'atlanta',label:'ATLANTA',city:'Atlanta',country:'USA',lon:-84.3880,lat:33.7490,height:180000},
 {id:'las-vegas',label:'LAS VEGAS',city:'Las Vegas',country:'USA',lon:-115.1398,lat:36.1699,height:180000},
 {id:'los-angeles',label:'LOS ANGELES',city:'Los Angeles',country:'USA',lon:-118.2437,lat:34.0522,height:180000},
 {id:'new-york',label:'NEW YORK',city:'New York',country:'USA',lon:-74.0060,lat:40.7128,height:180000},
 {id:'lagos',label:'LAGOS',city:'Lagos',country:'Nigeria',lon:3.3792,lat:6.5244,height:220000},
 {id:'abuja',label:'ABUJA',city:'Abuja',country:'Nigeria',lon:7.3986,lat:9.0765,height:220000},
 {id:'accra',label:'ACCRA',city:'Accra',country:'Ghana',lon:-0.1870,lat:5.6037,height:220000},
 {id:'nairobi',label:'NAIROBI',city:'Nairobi',country:'Kenya',lon:36.8219,lat:-1.2921,height:220000},
 {id:'johannesburg',label:'JOHANNESBURG',city:'Johannesburg',country:'South Africa',lon:28.0473,lat:-26.2041,height:220000},
 {id:'london',label:'LONDON',city:'London',country:'UK',lon:-0.1276,lat:51.5072,height:220000},
 {id:'tokyo',label:'TOKYO',city:'Tokyo',country:'Japan',lon:139.6917,lat:35.6895,height:220000},
]
const LAYERS=[
 {id:'present',label:'PRESENT TWIN',description:'Current geography and licensed/reference map data.'},
 {id:'past',label:'PAST',description:'Documented historical reconstruction only where sources support it.'},
 {id:'future',label:'FUTURE',description:'TRYAMM simulation of possible future city and planet states.'},
 {id:'business',label:'BUSINESS',description:'Businesses, properties, jobs, marketplace and digital twins.'},
 {id:'sports',label:'SPORTS',description:'SportsVerse venues, leagues, racing and competitions.'},
 {id:'faith',label:'FAITH',description:'Faith World, Ethiopian Bible and source-labeled historical experiences.'},
 {id:'supply',label:'SUPPLY CHAIN',description:'Producer-to-customer trade, logistics and Global Trade overlays.'},
 {id:'after-dark',label:'AFTER DARK',description:'Age-aware nighttime economy, events, transport and creator activity.'},
]
type Place=(typeof PLANET_PLACES)[number]|(typeof CHICAGO_PLACES)[number]
type Props={onClose?:()=>void}
function loadCesium(){if(window.Cesium)return Promise.resolve(window.Cesium);window.CESIUM_BASE_URL=CESIUM_BASE;if(!document.querySelector('link[data-streetverse-cesium]')){const l=document.createElement('link');l.rel='stylesheet';l.href=`${CESIUM_BASE}Widgets/widgets.css`;l.dataset.streetverseCesium='1';document.head.appendChild(l)}return new Promise<any>((resolve,reject)=>{const e=document.querySelector<HTMLScriptElement>('script[data-streetverse-cesium]');if(e){e.addEventListener('load',()=>resolve(window.Cesium),{once:true});e.addEventListener('error',reject,{once:true});return}const s=document.createElement('script');s.src=`${CESIUM_BASE}Cesium.js`;s.async=true;s.dataset.streetverseCesium='1';s.onload=()=>resolve(window.Cesium);s.onerror=()=>reject(new Error('CesiumJS failed to load'));document.head.appendChild(s)})}
export default function StreetVerseTwinWorld({onClose}:Props){const host=useRef<HTMLDivElement|null>(null),viewerRef=useRef<any>(null);const[status,setStatus]=useState('Starting Planet Clone…'),[provider,setProvider]=useState('REAL EARTH • STREET MAP'),[selected,setSelected]=useState('CHICAGO'),[scope,setScope]=useState<'chicago'|'planet'>('planet'),[activeLayer,setActiveLayer]=useState('present');
 useEffect(()=>{let viewer:any,cancelled=false;(async()=>{try{const C=await loadCesium();if(cancelled||!host.current||!C)return;const googleKey=String(import.meta.env.VITE_GOOGLE_MAP_TILES_API_KEY||'').trim();viewer=new C.Viewer(host.current,{animation:false,timeline:false,baseLayerPicker:false,sceneModePicker:true,homeButton:true,fullscreenButton:true,navigationHelpButton:false,infoBox:false,selectionIndicator:false,geocoder:false,globe:googleKey?false:undefined,imageryProvider:googleKey?false:new C.OpenStreetMapImageryProvider({url:'https://tile.openstreetmap.org/',credit:'© OpenStreetMap contributors'}),terrainProvider:googleKey?undefined:new C.EllipsoidTerrainProvider()});viewerRef.current=viewer;viewer.scene.skyAtmosphere.show=true;if(viewer.scene.globe)viewer.scene.globe.depthTestAgainstTerrain=true;if(googleKey){try{C.GoogleMaps.defaultApiKey=googleKey;const tileset=await C.createGooglePhotorealistic3DTileset({key:googleKey,onlyUsingWithGoogleGeocoder:true},{showCreditsOnScreen:true,maximumScreenSpaceError:10});if(!cancelled){viewer.scene.primitives.add(tileset);setProvider('GOOGLE PHOTOREALISTIC 3D TILES')}}catch(err){console.error('[PlanetClone] Google tiles failed',err);setProvider('REAL EARTH FALLBACK • STREET MAP')}}
 const fly=(p:Place,duration=0)=>viewer.camera.flyTo({destination:C.Cartesian3.fromDegrees(p.lon,p.lat,p.height),orientation:{heading:C.Math.toRadians(18),pitch:C.Math.toRadians(-48),roll:0},duration});fly({...CHICAGO,height:1500000});PLANET_PLACES.forEach(p=>viewer.entities.add({name:`${p.city}, ${p.country}`,position:C.Cartesian3.fromDegrees(p.lon,p.lat,35),point:{pixelSize:9,color:C.Color.GOLD,outlineColor:C.Color.BLACK,outlineWidth:2},label:{text:p.label,font:'700 13px sans-serif',pixelOffset:new C.Cartesian2(0,-18),fillColor:C.Color.WHITE,showBackground:true,backgroundColor:new C.Color(0,0,0,.64),distanceDisplayCondition:new C.DistanceDisplayCondition(0,9000000)}}));CHICAGO_PLACES.forEach(p=>viewer.entities.add({name:p.label,position:C.Cartesian3.fromDegrees(p.lon,p.lat,35),point:{pixelSize:7,color:C.Color.CYAN,outlineColor:C.Color.BLACK,outlineWidth:2},label:{text:p.label,font:'700 12px sans-serif',pixelOffset:new C.Cartesian2(0,-16),fillColor:C.Color.WHITE,showBackground:true,backgroundColor:new C.Color(0,0,0,.58),distanceDisplayCondition:new C.DistanceDisplayCondition(0,22000)}}));setStatus(googleKey?'Planet Clone online • licensed photorealistic tiles can anchor TRYAMM world layers.':'Planet Clone online • real Earth street geography is active with TRYAMM simulation layers.');window.dispatchEvent(new CustomEvent('tryamm:planet-clone-ready',{detail:{city:'Chicago',lat:CHICAGO.lat,lon:CHICAGO.lon,provider:googleKey?'google-photorealistic-3d':'osm-street-map',earthScale:true,navigation:true,layers:LAYERS.map(x=>x.id),planetPlaces:PLANET_PLACES.length,simulationBoundary:true}}))}catch(err){console.error('[PlanetClone]',err);setStatus('Planet Clone could not initialize on this device/browser.')}})();return()=>{cancelled=true;viewerRef.current=null;try{viewer?.destroy?.()}catch{}}},[])
 const go=(p:Place)=>{const C=window.Cesium,v=viewerRef.current;if(!C||!v)return;setSelected(p.label);try{localStorage.setItem(DESTINATION_KEY,JSON.stringify({...p,layer:activeLayer,scope,selectedAt:new Date().toISOString()}))}catch{};v.camera.flyTo({destination:C.Cartesian3.fromDegrees(p.lon,p.lat,p.height),orientation:{heading:C.Math.toRadians(18),pitch:C.Math.toRadians(-48),roll:0},duration:1.2});setStatus(`${p.label} selected • ${LAYERS.find(x=>x.id===activeLayer)?.label}. OPEN GAME WORLD carries this destination into StreetVerse.`);window.dispatchEvent(new CustomEvent('tryamm:planet-clone-navigate',{detail:{...p,layer:activeLayer,scope,simulationBoundary:true}}));window.dispatchEvent(new CustomEvent('tryamm:twin-world-navigate',{detail:{...p,layer:activeLayer,city:p.city,country:p.country}}))}
 const chooseLayer=(id:string)=>{setActiveLayer(id);const layer=LAYERS.find(x=>x.id===id);setStatus(`${layer?.label} layer active • ${layer?.description}`);window.dispatchEvent(new CustomEvent('tryamm:planet-clone-layer',{detail:{layer:id,label:layer?.label,simulationBoundary:id!=='present'}}))}
 const toggleScope=()=>{const C=window.Cesium,v=viewerRef.current;const next=scope==='planet'?'chicago':'planet';setScope(next);if(C&&v)v.camera.flyTo({destination:C.Cartesian3.fromDegrees(CHICAGO.lon,CHICAGO.lat,next==='planet'?1500000:18000),duration:1.1});setSelected(next==='planet'?'CHICAGO':'THE LOOP');setStatus(next==='planet'?'PLANET MODE • move between global TRYAMM expansion nodes.':'CHICAGO MODE • inspect local districts and launch the playable city.')}
 const locate=()=>{if(!navigator.geolocation){setStatus('Location is unavailable on this browser.');return}setStatus('Finding your position…');navigator.geolocation.getCurrentPosition(pos=>{const C=window.Cesium,v=viewerRef.current;if(!C||!v)return;const {latitude:lat,longitude:lon}=pos.coords;v.camera.flyTo({destination:C.Cartesian3.fromDegrees(lon,lat,900),duration:1.2});setSelected('MY LOCATION');setStatus('Your location is centered. Planet Clone uses location only after browser permission.');window.dispatchEvent(new CustomEvent('tryamm:planet-clone-user-location',{detail:{lat,lon,accuracy:pos.coords.accuracy}}))},()=>setStatus('Location permission was not granted.'),{enableHighAccuracy:false,timeout:8000,maximumAge:60000})}
 const places=scope==='planet'?PLANET_PLACES:CHICAGO_PLACES
 return <div style={{position:'fixed',inset:0,zIndex:17000,background:'#02060a',color:'#fff',fontFamily:'system-ui,sans-serif'}}><div ref={host} style={{position:'absolute',inset:0}} aria-label="TRYAMM Planet Clone real Earth digital twin and simulation map"/><div style={{position:'absolute',left:12,top:12,zIndex:3,maxWidth:520,maxHeight:'84vh',overflowY:'auto',padding:'12px 14px',borderRadius:14,background:'rgba(2,8,14,.9)',border:'1px solid rgba(255,215,92,.5)',backdropFilter:'blur(10px)'}}><div style={{fontWeight:1000,letterSpacing:'.08em'}}>🌎 TRYAMM • PLANET CLONE</div><div style={{marginTop:4,fontSize:12,fontWeight:800,color:'#ffd75c'}}>{provider} • {scope.toUpperCase()} • {selected}</div><div style={{marginTop:7,fontSize:12,lineHeight:1.35,color:'#d8e5ee'}}>{status}</div><div style={{marginTop:10,fontSize:10,fontWeight:950,letterSpacing:1.2,color:'#89e8ff'}}>WORLD LAYERS</div><div style={{display:'flex',gap:6,marginTop:6,flexWrap:'wrap'}}>{LAYERS.map(layer=><button key={layer.id} onClick={()=>chooseLayer(layer.id)} style={{...buttonStyle,borderColor:activeLayer===layer.id?'#ffd75c':'#ffffff33',color:activeLayer===layer.id?'#ffd75c':'#fff'}}>{layer.label}</button>)}</div><div style={{marginTop:10,fontSize:10,fontWeight:950,letterSpacing:1.2,color:'#89e8ff'}}>{scope==='planet'?'PLANET NODES':'CHICAGO NODES'}</div><div style={{display:'flex',gap:6,marginTop:6,flexWrap:'wrap'}}>{places.map(p=><button key={p.id} onClick={()=>go(p)} style={buttonStyle}>{p.label}</button>)}</div><div style={{display:'flex',gap:8,marginTop:10,flexWrap:'wrap'}}><button onClick={toggleScope} style={buttonStyle}>{scope==='planet'?'⌂ CHICAGO MODE':'🌎 PLANET MODE'}</button><button onClick={locate} style={buttonStyle}>◎ MY LOCATION</button><button onClick={()=>window.location.assign('/streetverse')} style={buttonStyle}>OPEN GAME WORLD</button><button onClick={()=>window.location.assign('/global-trade')} style={buttonStyle}>GLOBAL TRADE</button><button onClick={()=>window.location.assign('/ethiopian-bible')} style={buttonStyle}>FAITH WORLD</button><button onClick={()=>onClose?onClose():window.location.assign('/')} style={buttonStyle}>HOME</button></div></div><div style={{position:'absolute',right:12,bottom:30,zIndex:3,padding:'8px 10px',borderRadius:10,background:'rgba(0,0,0,.74)',fontSize:11,maxWidth:390}}>Planet Clone = real-world geospatial navigation plus TRYAMM-created simulation layers. PRESENT uses licensed/reference geography; PAST requires documented sources; FUTURE is simulation. Google imagery is used only with an authorized Map Tiles key and required attribution. Browser location is opt-in.</div></div>}
const buttonStyle:React.CSSProperties={border:'1px solid #ffffff33',background:'#111b24',color:'#fff',borderRadius:999,padding:'7px 9px',fontWeight:900,cursor:'pointer',fontSize:10}
