import {useEffect,useRef,useState} from 'react'

type Pos={x:number;z:number;vehicle?:boolean}
type Pursuit={active:boolean;level:number;phase:'idle'|'locate'|'stop-attempt'|'pursuit'|'roadblock'|'handoff'|'resolved';x:number;z:number;speed:number;elapsed:number;agency:'police'|'sheriff'|'fbi'}

export default function StreetVersePursuitController(){
 const player=useRef<Pos>({x:0,z:0}),speed=useRef(0),started=useRef(0),lastEscalation=useRef(0),stopSince=useRef(0),timer=useRef<number|undefined>(undefined)
 const [state,setState]=useState<Pursuit|null>(null)
 useEffect(()=>{
  const emit=(s:Pursuit)=>{setState(s);window.dispatchEvent(new CustomEvent('tryamm:streetverse-pursuit-state',{detail:s}))}
  const clear=()=>{if(timer.current)clearInterval(timer.current);timer.current=undefined;stopSince.current=0;started.current=0;lastEscalation.current=0;emit({active:false,level:0,phase:'resolved',x:player.current.x,z:player.current.z,speed:speed.current,elapsed:0,agency:'police'});window.dispatchEvent(new CustomEvent('tryamm:streetverse-emergency-resolved',{detail:{kind:'police',x:player.current.x,z:player.current.z}}))}
  const start=(severity=2)=>{if(timer.current)return;started.current=performance.now();lastEscalation.current=started.current;let level=Math.max(1,Math.min(5,severity));let agency:'police'|'sheriff'|'fbi'='police';window.dispatchEvent(new CustomEvent('tryamm:streetverse-law-radio',{detail:{agency:'POLICE',status:'ATTEMPT TRAFFIC STOP',x:player.current.x,z:player.current.z}}));window.dispatchEvent(new CustomEvent('tryamm:streetverse-emergency-response',{detail:{kind:'police',agency:'police',x:player.current.x,z:player.current.z,severity:level}}));timer.current=window.setInterval(()=>{const now=performance.now(),elapsed=(now-started.current)/1000,spd=Math.abs(speed.current);let phase:Pursuit['phase']=elapsed<4?'locate':spd<3?'stop-attempt':'pursuit';if(spd<2){if(!stopSince.current)stopSince.current=now;if(now-stopSince.current>4500){clear();return}}else stopSince.current=0;if(elapsed>18&&level<3){level=3;agency='sheriff';phase='roadblock';lastEscalation.current=now;window.dispatchEvent(new CustomEvent('tryamm:streetverse-law-radio',{detail:{agency:'SHERIFF',status:'BACKUP / INTERCEPT',x:player.current.x,z:player.current.z}}));window.dispatchEvent(new CustomEvent('tryamm:streetverse-roadblock-request',{detail:{kind:'sheriff',agency:'sheriff',x:player.current.x,z:player.current.z,radius:28,level}}));window.dispatchEvent(new CustomEvent('tryamm:streetverse-emergency-response',{detail:{kind:'sheriff',agency:'sheriff',x:player.current.x,z:player.current.z,severity:level}}))}if(elapsed>38&&level<5){level=5;agency='fbi';phase='handoff';lastEscalation.current=now;window.dispatchEvent(new CustomEvent('tryamm:streetverse-federal-dispatch',{detail:{kind:'fbi',agency:'fbi',x:player.current.x,z:player.current.z,severity:level,reason:'special-mission-handoff'}}));window.dispatchEvent(new CustomEvent('tryamm:streetverse-federal-handoff',{detail:{kind:'fbi',x:player.current.x,z:player.current.z,classification:'SPECIAL MISSION HANDOFF'}}))}window.dispatchEvent(new CustomEvent('tryamm:streetverse-pursuit-target',{detail:{x:player.current.x,z:player.current.z,speed:spd,level,agency,phase}}));emit({active:true,level,phase,x:player.current.x,z:player.current.z,speed:spd,elapsed,agency})},350)}
  const onPlayer=(e:Event)=>{const d=(e as CustomEvent<any>).detail||{};player.current={x:Number(d.x||0),z:Number(d.z||0),vehicle:!!d.vehicle}}
  const onDrive=(e:Event)=>{const d=(e as CustomEvent<any>).detail||{};speed.current=Number(d.speed||d.signedSpeed||0)}
  const onRace=()=>start(2)
  const onStart=(e:Event)=>start(Math.max(1,Number((e as CustomEvent<any>).detail?.severity||2)))
  const onClear=()=>clear()
  addEventListener('tryamm:streetverse-player-position',onPlayer);addEventListener('tryamm:streetverse-drive-telemetry',onDrive);addEventListener('tryamm:streetverse-ai-opponents-start',onRace);addEventListener('tryamm:streetverse-pursuit-start',onStart);addEventListener('tryamm:streetverse-pursuit-clear',onClear)
  return()=>{if(timer.current)clearInterval(timer.current);removeEventListener('tryamm:streetverse-player-position',onPlayer);removeEventListener('tryamm:streetverse-drive-telemetry',onDrive);removeEventListener('tryamm:streetverse-ai-opponents-start',onRace);removeEventListener('tryamm:streetverse-pursuit-start',onStart);removeEventListener('tryamm:streetverse-pursuit-clear',onClear)}
 },[])
 if(!state?.active)return null
 return <div style={{position:'fixed',left:12,bottom:112,zIndex:16982,padding:'8px 10px',borderRadius:12,background:'rgba(5,8,14,.9)',border:'1px solid rgba(82,151,255,.48)',color:'#fff',fontFamily:'system-ui',pointerEvents:'none'}}><div style={{fontSize:9,fontWeight:950,color:'#7db4ff'}}>PURSUIT • LEVEL {state.level}</div><div style={{fontSize:11,fontWeight:900,marginTop:2}}>{state.agency.toUpperCase()} • {state.phase.replace('-',' ').toUpperCase()}</div><div style={{fontSize:8,opacity:.72}}>TARGET SPEED {Math.round(state.speed)} • STOP & HOLD TO RESOLVE</div></div>
}
