import {useEffect,useMemo,useState} from 'react'

type Product={id:string;name:string;store:string;price:number;category:string}
type CartLine=Product&{qty:number}
type Order={id:string;lines:CartLine[];total:number;fulfillment:'pickup'|'delivery';status:string;createdAt:string}
const PRODUCTS:Product[]=[
{id:'loop-tee',name:'Chicago StreetVerse Tee',store:'Loop Courier Hub',price:28,category:'Apparel'},
{id:'loop-bag',name:'Creator Transit Bag',store:'Loop Courier Hub',price:42,category:'Accessories'},
{id:'river-kit',name:'Creator Reel Kit',store:'Riverwalk Creator Studio',price:35,category:'Creator'},
{id:'park-print',name:'Chicago World Art Print',store:'Millennium Event Pavilion',price:24,category:'Art'},
{id:'south-meal',name:'South Side Meal Pack',store:'79th Street Market',price:18,category:'Food'},
{id:'west-maker',name:'Maker Starter Pack',store:'Madison Maker Hub',price:39,category:'Maker'},
{id:'north-merch',name:'North Side Creator Merch',store:'North Side Creator Venue',price:32,category:'Creator'}]
const CART_KEY='tryamm.shopping.cart.v1',ORDER_KEY='tryamm.shopping.orders.v1'
export default function StreetVerseShoppingCore(){
 const [open,setOpen]=useState(false),[store,setStore]=useState('All American Marketplace'),[fulfillment,setFulfillment]=useState<'pickup'|'delivery'>('pickup')
 const [cart,setCart]=useState<CartLine[]>(()=>{try{return JSON.parse(localStorage.getItem(CART_KEY)||'[]')}catch{return[]}})
 const [orders,setOrders]=useState<Order[]>(()=>{try{return JSON.parse(localStorage.getItem(ORDER_KEY)||'[]')}catch{return[]}})
 useEffect(()=>{const enter=(e:Event)=>{const d=(e as CustomEvent).detail||{};if(d.label){setStore(d.label);setOpen(true)}};const launch=()=>setOpen(true);window.addEventListener('tryamm:chicago-storefront-near',enter);window.addEventListener('tryamm:shopping-open',launch);return()=>{window.removeEventListener('tryamm:chicago-storefront-near',enter);window.removeEventListener('tryamm:shopping-open',launch)}},[])
 useEffect(()=>{localStorage.setItem(CART_KEY,JSON.stringify(cart))},[cart]);useEffect(()=>{localStorage.setItem(ORDER_KEY,JSON.stringify(orders))},[orders])
 const visible=useMemo(()=>{const exact=PRODUCTS.filter(p=>p.store===store);return exact.length?exact:PRODUCTS},[store]);const total=cart.reduce((s,l)=>s+l.price*l.qty,0)
 const add=(p:Product)=>setCart(c=>{const found=c.find(x=>x.id===p.id);return found?c.map(x=>x.id===p.id?{...x,qty:x.qty+1}:x):[...c,{...p,qty:1}]})
 const checkout=()=>{if(!cart.length)return;const order:Order={id:'AMM-'+Date.now().toString(36).toUpperCase(),lines:cart,total,fulfillment,status:fulfillment==='pickup'?'READY FOR STORE CONFIRMATION':'DELIVERY REQUESTED',createdAt:new Date().toISOString()};setOrders(o=>[order,...o].slice(0,12));setCart([]);window.dispatchEvent(new CustomEvent('tryamm:shopping-order-created',{detail:{...order,paymentStatus:'NOT_CHARGED',paymentProvider:null}}))}
 return <><button onClick={()=>setOpen(true)} style={{position:'fixed',right:12,top:92,zIndex:60,border:0,borderRadius:10,padding:'9px 12px',fontWeight:900}}>SHOP • {cart.reduce((s,l)=>s+l.qty,0)}</button>{open&&<div style={{position:'fixed',inset:0,zIndex:19000,background:'rgba(2,6,12,.78)',display:'grid',placeItems:'center',fontFamily:'system-ui',color:'#fff'}}><div style={{width:'min(760px,94vw)',maxHeight:'86vh',overflow:'auto',background:'#07111c',border:'1px solid #48b6ff77',borderRadius:18,padding:18}}><div style={{display:'flex',justifyContent:'space-between',gap:12}}><div><b style={{fontSize:20}}>ALL AMERICAN MARKETPLACE</b><div style={{opacity:.7}}>{store} • StreetVerse Shopping</div></div><button onClick={()=>setOpen(false)}>CLOSE</button></div><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(170px,1fr))',gap:10,marginTop:16}}>{visible.map(p=><div key={p.id} style={{padding:12,border:'1px solid #ffffff22',borderRadius:12,background:'#0b1b2a'}}><b>{p.name}</b><div style={{opacity:.65,fontSize:12}}>{p.category}</div><div style={{fontSize:18,fontWeight:900,margin:'8px 0'}}>${p.price.toFixed(2)}</div><button onClick={()=>add(p)}>ADD TO CART</button></div>)}</div><div style={{marginTop:18,paddingTop:14,borderTop:'1px solid #ffffff22'}}><b>CART • ${total.toFixed(2)}</b><div style={{fontSize:12,opacity:.75,margin:'5px 0'}}>{cart.map(x=>`${x.qty}× ${x.name}`).join(' • ')||'Cart is empty'}</div><label><input type="radio" checked={fulfillment==='pickup'} onChange={()=>setFulfillment('pickup')}/> Store pickup</label> <label style={{marginLeft:12}}><input type="radio" checked={fulfillment==='delivery'} onChange={()=>setFulfillment('delivery')}/> Delivery</label><button disabled={!cart.length} onClick={checkout} style={{display:'block',width:'100%',marginTop:10,padding:11,fontWeight:900}}>CREATE ORDER • PAYMENT NOT CHARGED</button><div style={{fontSize:11,opacity:.6,marginTop:6}}>Checkout currently creates an order record only. Live Stripe, Paystack, Flutterwave and other payment rails remain disabled until merchant credentials, KYC/KYB, server webhooks, idempotency and reconciliation are verified.</div></div>{orders[0]&&<div style={{marginTop:14,padding:10,borderRadius:10,background:'#0c2533'}}><b>OMNI BOX ORDER</b><div>{orders[0].id} • {orders[0].status} • ${orders[0].total.toFixed(2)}</div></div>}</div></div>}</>}
