import { useEffect, useMemo, useState } from 'react'

type Pos={x:number;z:number}
type Mission={id:string;label:string;type:'SPRINT'|'DELIVERY'|'DRIFT';xp:number;targets:{label:string;x:number;z:number}[];dialogue:string[]}
type SyncedProgress={xp?:number}
type ChoiceId='A'|'B'|'C'|'D'
type MissionChoice={id:ChoiceId;label:string;approach:string;xpDelta:number;reputationDelta:number;worldEffect:string}
const XP_KEY='tryamm.streetverse.xp.v1'
const CHOICES:MissionChoice[]=[
 {id:'A',label:'ACTION',approach:'Act now: take the direct objective and accept the immediate risk/reward.',xpDelta:25,reputationDelta:0,worldEffect:'direct'},
 {id:'B',label:'PLAN',approach:'Use a tactical route: gather context, choose equipment or reposition before acting.',xpDelta:15,reputationDelta:2,worldEffect:'tactical'},
 {id:'C',label:'SOCIAL',approach:'Talk, negotiate, recruit, help or use a business/community relationship to change the situation.',xpDelta:20,reputationDelta:3,worldEffect:'relationship'},
 {id:'D',label:'WILDCARD',approach:'Choose the alternate StreetVerse solution: Omni/Sparrow assist, accessibility route, creative objective or discovered world option.',xpDelta:20,reputationDelta:2,worldEffect:'alternate'},
]
const MISSIONS:Mission[]=[
 {id:'loop-sprint',label:'Loop Sprint',type:'SPRINT',xp:180,targets:[{label:'State Street',x:0,z:48},{label:'River Cut',x:0,z:0},{label:'North Gate',x:0,z:-48}],dialogue:['You want a clean run? Keep it straight through the Loop.','Traffic is live. Read the lights and pick your line.']},
 {id:'market-delivery',label:'Marketplace Rush',type:'DELIVERY',xp:220,targets:[{label:'Pickup • Omni Cafe',x:-24,z:-70},{label:'Drop • All American Marketplace',x:42,z:-24}],dialogue:['Marketplace has a rush order. Get it there without wrecking the car.','Fast is good. Clean is better.']},
 {id:'west-drift',label:'West Side Drift Line',type:'DRIFT',xp:260,targets:[{label:'Drift Entry',x:-48,z:48},{label:'Drift Mid',x:-48,z:0},{label:'Drift Exit',x:-48,z:-48}],dialogue:['Hold the line through the west corridor.','Use brake and steering together—make the car rotate, then catch it.']},
]
function loadXp(){try{return Number(localStorage.getItem(XP_KEY)||0)||0}catch{return 0}}
export default function StreetVerseMissionExpansion(){
 const [driving,setDriving]=useState(false),[pos,setPos]=useState<Pos|null>(null),[selected,setSelected]=useState(0),[active,setActive]=useState(false),[step,setStep]=useState(0),[xp,setXp]=useState(loadXp),[message,setMessage]=useState('Choose a mission.'),[choice,setChoice]=useState<MissionChoice|null>(null)
 const mission=MISSIONS[selected],target=mission.targets[step]
 const distance=useMemo(()=>pos&&target?Math.hypot(pos.x-target.x,pos.z-target.z):Infinity,[pos,target])
 useEffect(()=>{const onProgress=(e:Event)=>{const value=Number((e as CustomEvent<SyncedProgress>).detail?.xp);if(Number.isFinite(value)&&value>=0)setXp(value)};addEventListener('tryamm:streetverse-progress-loaded',onProgress);addEventListener('tryamm:streetverse-progress-synced',onProgress);return()=>{removeEventListener('tryamm:streetverse-progress-loaded',onProgress);removeEventListener('tryamm:streetverse-progress-synced',onProgress)}},[])
 useEffect(()=>{const p=(e:Event)=>{const d=(e as CustomEvent<Pos>).detail;if(Number.isFinite(d?.x)&&Number.isFinite(d?.z))setPos(d)};const v=(e:Event)=>setDriving(Boolean((e as CustomEvent<{entered?:boolean}>).detail?.entered));addEventListener('tryamm:streetverse-player-position',p);addEventListener('tryamm:streetverse-vehicle-controlled',v);return()=>{removeEventListener('tryamm:streetverse-player-position',p);removeEventListener('tryamm:streetverse-vehicle-controlled',v)}},[])
 useEffect(()=>{if(!active||!driving||distance>8)return;if(step<mission.targets.length-1){setStep(step+1);setMessage(`Checkpoint clear • ${mission.targets[step+1].label}`);dispatchEvent(new CustomEvent('tryamm:streetverse-drive-sound',{detail:{kind:'checkpoint'}}));return}const bonus=choice?.xpDelta||0,total=xp+mission.xp+bonus;setXp(total);setActive(false);setStep(0);setMessage(`${mission.label} complete • +${mission.xp+bonus} XP • Path ${choice?.id||'—'}`);try{localStorage.setItem(XP_KEY,String(total))}catch{}dispatchEvent(new CustomEvent('tryamm:streetverse-xp-earned',{detail:{source:'mission-expansion',mission:mission.label,xp:mission.xp+bonus,totalXp:total,choice:choice?.id||null,reputationDelta:choice?.reputationDelta||0}}));dispatchEvent(new CustomEvent('tryamm:streetverse-mission-complete',{detail:{id:mission.id,label:mission.label,xp:mission.xp+bonus,choice:choice?.id||null,reputationDelta:choice?.reputationDelta||0,worldEffect:choice?.worldEffect||null,financialReward:false}}));dispatchEvent(new CustomEvent('tryamm:streetverse-drive-sound',{detail:{kind:'mission-complete'}}))},[active,driving,distance,step,mission,xp])
 const start=()=>{if(!driving){setMessage('Enter a vehicle first.');return}if(!choice){setMessage('Choose A, B, C or D before starting.');return}setActive(true);setStep(0);setMessage(mission.dialogue[0]);dispatchEvent(new CustomEvent('tryamm:streetverse-mission-start',{detail:{id:mission.id,label:mission.label,type:mission.type,choice:choice.id,approach:choice.approach,worldEffect:choice.worldEffect}}));dispatchEvent(new CustomEvent('tryamm:streetverse-race-target',{detail:{...mission.targets[0],mission:mission.label}}))}
 useEffect(()=>{if(active&&target)dispatchEvent(new CustomEvent('tryamm:streetverse-race-target',{detail:{...target,mission:mission.label}}))},[active,target,mission.label])
 return <div style={{position:'fixed',right:12,top:210,zIndex:16996,width:'min(86vw,300px)',padding:10,borderRadius:14,background:'#071019e8',border:'1px solid #66e2ff55',color:'#fff',fontFamily:'system-ui'}}><div style={{fontSize:9,fontWeight:950,color:'#67e6ff',letterSpacing:1}}>STREETVERSE MISSIONS</div><div style={{display:'flex',gap:5,marginTop:7,flexWrap:'wrap'}}>{MISSIONS.map((m,i)=><button key={m.id} disabled={active} onClick={()=>{setSelected(i);setMessage(m.dialogue[0])}} style={{...btn,opacity:selected===i?1:.65}}>{m.type}</button>)}</div><div style={{marginTop:8,fontSize:12,fontWeight:900}}>{mission.label}</div><div style={{marginTop:7,fontSize:9,fontWeight:950,color:'#ffd36b',letterSpacing:1}}>CHOOSE YOUR PATH • A / B / C / D</div><div style={{display:'grid',gridTemplateColumns:'repeat(4,1fr)',gap:5,marginTop:5}}>{CHOICES.map(o=><button key={o.id} disabled={active} aria-pressed={choice?.id===o.id} onClick={()=>{setChoice(o);setMessage(`Path ${o.id} • ${o.approach}`);dispatchEvent(new CustomEvent('tryamm:streetverse-mission-choice',{detail:{missionId:mission.id,choice:o.id,label:o.label,approach:o.approach,xpDelta:o.xpDelta,reputationDelta:o.reputationDelta,worldEffect:o.worldEffect}}))}} style={{...btn,minHeight:42,background:choice?.id===o.id?'#174a5e':'#111a24'}}><b>{o.id}</b><br/><span style={{fontSize:8}}>{o.label}</span></button>)}</div><div style={{fontSize:10,opacity:.78,marginTop:3}}>{message}</div><div style={{fontSize:10,marginTop:4}}>{active?`${target.label} • ${Number.isFinite(distance)?distance.toFixed(0):'--'}m`:`Reward ${mission.xp} XP • Total ${xp}`}</div><div style={{display:'flex',gap:6,marginTop:8}}><button onClick={start} disabled={active} style={btn}>{driving?'START':'NEED CAR'}</button>{active&&<button onClick={()=>{setActive(false);setStep(0);setMessage('Mission cancelled.')}} style={btn}>CANCEL</button>}<button onClick={()=>setMessage(mission.dialogue[(mission.dialogue.indexOf(message)+1)%mission.dialogue.length]||mission.dialogue[0])} style={btn}>TALK</button></div></div>
}
const btn:React.CSSProperties={minHeight:34,padding:'0 9px',borderRadius:999,border:'1px solid #6de6ff66',background:'#111a24',color:'#fff',fontSize:9,fontWeight:900,cursor:'pointer'}
