import { useEffect,useMemo,useState } from 'react'

type Dispatch={id:string;city:string;title:string;priority:string;branchId:string;roles:string[];vehicle:string;equipment:string[]}
type Mission={id:string;title:string;phase:string;objectives:{id:string;label:string;done:boolean}[];boss?:{name:string;stages:number;stage:number};extraction?:{zone:string;secured:boolean;teamReady:boolean};xp?:number;reputation?:number}
type Career={branch?:{id:string;title:string};rank?:string;credits?:number}

export default function StreetVerseMissionWorldBridge(){
 const [dispatch,setDispatch]=useState<Dispatch|null>(null),[mission,setMission]=useState<Mission|null>(null),[career,setCareer]=useState<Career|null>(null),[seconds,setSeconds]=useState(0),[visible,setVisible]=useState(false)
 useEffect(()=>{const d=(e:Event)=>{const x=(e as CustomEvent<any>).detail||{};setDispatch(x.call||x);setVisible(Boolean(x.call||x.id));if(x.call||x.id)window.dispatchEvent(new CustomEvent('tryamm:city-world-object-spawn',{detail:{kind:'dispatch-marker',call:x.call||x}}))},m=(e:Event)=>{const x=(e as CustomEvent<any>).detail?.mission||(e as CustomEvent<any>).detail||null;setMission(x);if(x?.phase==='extraction')setSeconds(90);if(x)window.dispatchEvent(new CustomEvent('tryamm:city-world-object-spawn',{detail:{kind:'mission-state',mission:x}}))},c=(e:Event)=>setCareer((e as CustomEvent<any>).detail||null);window.addEventListener('tryamm:dynamic-dispatch-state',d);window.addEventListener('tryamm:career-extraction-state',m);window.addEventListener('tryamm:guardian-service-career-state',c);window.dispatchEvent(new Event('tryamm:global-travel-request'));return()=>{window.removeEventListener('tryamm:dynamic-dispatch-state',d);window.removeEventListener('tryamm:career-extraction-state',m);window.removeEventListener('tryamm:guardian-service-career-state',c)}},[])
 useEffect(()=>{if(seconds<=0)return;const t=setInterval(()=>setSeconds(s=>Math.max(0,s-1)),1000);return()=>clearInterval(t)},[seconds])
 const done=mission?.objectives?.filter(o=>o.done).length||0,total=mission?.objectives?.length||0
 const next=useMemo(()=>mission?.objectives?.find(o=>!o.done),[mission])
 if(!visible&&!mission)return null
 const panel:React.CSSProperties={position:'fixed',zIndex:9050,right:12,top:78,width:'min(340px,calc(100vw - 24px))',background:'#04101bea',border:'1px solid #4fe3ff66',borderRadius:16,color:'#fff',padding:12,boxShadow:'0 18px 50px #0009',fontFamily:'Inter,system-ui'}
 const chip:React.CSSProperties={fontSize:10,padding:'4px 7px',border:'1px solid #35506b',borderRadius:999,background:'#0b1a27'}
 return <aside style={panel} aria-label="StreetVerse active mission world HUD"><div style={{display:'flex',justifyContent:'space-between',gap:10}}><div><div style={{fontSize:10,color:'#4fe3ff',fontWeight:950,letterSpacing:1.6}}>AL B DISPATCH · WORLD HUD</div><strong>{dispatch?.title||mission?.title||'Active Mission'}</strong></div><button onClick={()=>setVisible(false)} style={{border:0,background:'transparent',color:'#9fb2c4',fontSize:18,cursor:'pointer'}}>×</button></div>
 {dispatch&&<><div style={{display:'flex',gap:5,flexWrap:'wrap',marginTop:9}}><span style={chip}>{dispatch.priority?.toUpperCase()}</span><span style={chip}>📍 {dispatch.city}</span><span style={chip}>🚙 {dispatch.vehicle}</span></div><div style={{marginTop:9,fontSize:11,color:'#b9c9d8'}}><b>Squad:</b> {dispatch.roles?.join(' · ')}</div><div style={{marginTop:5,fontSize:11,color:'#b9c9d8'}}><b>Loadout:</b> {dispatch.equipment?.join(' · ')}</div><button onClick={()=>{setVisible(true);window.dispatchEvent(new CustomEvent('tryamm:career-mission-phase',{detail:{phase:'deployment'}}));window.dispatchEvent(new CustomEvent('tryamm:city-navigation-target',{detail:{type:'mission',city:dispatch.city,dispatchId:dispatch.id}}))}} style={primary}>SET GPS / DEPLOY</button></>}
 {mission&&<section style={{marginTop:10,borderTop:'1px solid #234',paddingTop:9}}><div style={{display:'flex',justifyContent:'space-between',fontSize:11}}><b>Mission phase</b><span>{mission.phase?.toUpperCase()}</span></div><div style={{height:5,background:'#12202c',borderRadius:9,overflow:'hidden',margin:'6px 0 8px'}}><div style={{height:'100%',width:`${total?Math.round(done/total*100):0}%`,background:'#4fe3ff'}}/></div><div style={{fontSize:11,color:'#aabaca'}}>{done}/{total} objectives complete</div>{next&&<button onClick={()=>window.dispatchEvent(new CustomEvent('tryamm:career-objective-complete',{detail:{id:next.id}}))} style={secondary}>✓ {next.label}</button>}
 {mission.phase==='boss'&&mission.boss&&<div style={{marginTop:9,padding:9,border:'1px solid #e8b94455',borderRadius:10,background:'#1b1408'}}><b>⚡ {mission.boss.name}</b><div style={{fontSize:11,marginTop:4}}>Stage {mission.boss.stage}/{mission.boss.stages}</div><button onClick={()=>window.dispatchEvent(new Event('tryamm:career-boss-stage-complete'))} style={primary}>COMPLETE BOSS STAGE</button></div>}
 {mission.phase==='extraction'&&<div style={{marginTop:9,padding:9,border:'1px solid #78ffb455',borderRadius:10,background:'#071b13'}}><b>🟢 EXTRACTION ZONE</b><div style={{fontSize:20,fontWeight:950,margin:'4px 0'}}>{seconds}s</div><div style={{fontSize:11}}>{mission.extraction?.zone||'Safe Handoff Zone'}</div><div style={{display:'flex',gap:6,marginTop:7}}><button onClick={()=>window.dispatchEvent(new CustomEvent('tryamm:career-extraction-update',{detail:{secured:true}}))} style={secondary}>SECURE ZONE</button><button onClick={()=>window.dispatchEvent(new CustomEvent('tryamm:career-extraction-update',{detail:{teamReady:true}}))} style={secondary}>TEAM READY</button></div></div>}
 {mission.phase==='verification'&&<button onClick={()=>window.dispatchEvent(new Event('tryamm:career-mission-verify'))} style={primary}>SUBMIT AFTER-ACTION / VERIFY</button>}
 {mission.phase==='complete'&&<div style={{marginTop:9,padding:10,border:'1px solid #78ffb455',borderRadius:10}}><b>MISSION COMPLETE</b><div style={{fontSize:11,marginTop:4}}>+{mission.xp||0} XP · +{mission.reputation||0} reputation</div><button onClick={()=>window.dispatchEvent(new CustomEvent('tryamm:creator-highlight-marker',{detail:{source:'streetverse-career',kind:'after-action',autoReel:true,at:Date.now()}}))} style={secondary}>🎬 CREATE MISSION REEL</button><button onClick={()=>window.dispatchEvent(new Event('tryamm:guardian-promotion-review'))} style={primary}>🏅 PROMOTION REVIEW</button></div>}
 </section>}
 {career&&<div style={{fontSize:10,color:'#7890a5',marginTop:9}}>Career: {career.branch?.title||'Guardian'} · Rank {career.rank||'Recruit'} · Credits {career.credits||0}</div>}
 </aside>
}
const primary:React.CSSProperties={width:'100%',marginTop:8,padding:'9px 10px',border:0,borderRadius:10,background:'linear-gradient(135deg,#4fe3ff,#78ffb4)',color:'#041019',fontWeight:950,cursor:'pointer'}
const secondary:React.CSSProperties={marginTop:7,padding:'8px 9px',border:'1px solid #35506b',borderRadius:9,background:'#0c1a27',color:'#fff',fontWeight:800,cursor:'pointer'}
