import {useEffect,useRef,useState} from 'react'

type Telemetry={entered?:boolean;speed?:number;signedSpeed?:number;throttle?:number;brake?:number;steer?:number;x?:number;z?:number}
type Collision={speed?:number;kind?:string;x?:number;z?:number}
type Opponent={id:string;name:string,progress:number,speed:number}
const DAMAGE_KEY='tryamm.streetverse.vehicle-condition.v1'
const ADV_KEY='tryamm.streetverse.advanced-driving.v1'
function loadDamage(){try{return Math.max(0,Math.min(100,Number(localStorage.getItem(DAMAGE_KEY)||100)||100))}catch{return 100}}
function loadMode(){try{return JSON.parse(localStorage.getItem(ADV_KEY)||'{}')?.vehicle||'CAR'}catch{return 'CAR'}}
const btn:React.CSSProperties={border:'1px solid #64ddff77',borderRadius:999,padding:'7px 10px',background:'#0b1723',color:'#fff',fontSize:9,fontWeight:950,cursor:'pointer'}
export default function StreetVerseAdvancedDrivingSystems(){
 const [driving,setDriving]=useState(false),[speed,setSpeed]=useState(0),[condition,setCondition]=useState(loadDamage),[vehicle,setVehicle]=useState<'CAR'|'MOTORCYCLE'>(loadMode),[response,setResponse]=useState('CLEAR'),[opponents,setOpponents]=useState<Opponent[]>([]),[race,setRace]=useState(false),[drift,setDrift]=useState(0),[combo,setCombo]=useState(1),[perf,setPerf]=useState('FULL')
 const telemetry=useRef<Telemetry>({}),last=useRef({x:0,z:0,t:0,angle:0}),raceStart=useRef(0),oppTick=useRef(0)
 useEffect(()=>{const low=((navigator as any).deviceMemory&&Number((navigator as any).deviceMemory)<=4)||(navigator.hardwareConcurrency&&navigator.hardwareConcurrency<=4)||matchMedia('(pointer:coarse)').matches&&innerWidth<700;setPerf(low?'PERFORMANCE':'FULL');dispatchEvent(new CustomEvent('tryamm:streetverse-performance',{detail:{mode:low?'performance':'quality',source:'advanced-driving'}}))
  const onVehicle=(e:Event)=>{const d=(e as CustomEvent).detail||{};setDriving(Boolean(d.entered));if(!d.entered){setDrift(0);setCombo(1)}}
  const onTelemetry=(e:Event)=>{const d=(e as CustomEvent<Telemetry>).detail||{};telemetry.current=d;setDriving(Boolean(d.entered));setSpeed(Number(d.speed)||0);const now=performance.now(),p=last.current;if(Number.isFinite(d.x)&&Number.isFinite(d.z)&&p.t){const dx=Number(d.x)-p.x,dz=Number(d.z)-p.z,dist=Math.hypot(dx,dz),dt=Math.max(.016,(now-p.t)/1000);if(dist>.04){const travel=Math.atan2(-dz,dx);const steer=Math.abs(Number(d.steer)||0),v=Math.abs(Number(d.signedSpeed)||Number(d.speed)||0);/* current world has no independent lateral velocity; this is a conservative drift-intent score until lateral-slip physics lands */const intensity=Math.max(0,(v-12)/22)*Math.max(0,(steer-.45)/.55);if(intensity>.08){setCombo(c=>Math.min(5,c+.015));setDrift(s=>{const n=s+intensity*v*dt*8*Math.max(1,combo);dispatchEvent(new CustomEvent('tryamm:streetverse-drift-score',{detail:{score:Math.round(n),combo,intensity,physics:'intent-until-lateral-slip'}}));return n})}else if(steer<.25)setCombo(1);p.angle=travel}}last.current={x:Number(d.x)||0,z:Number(d.z)||0,t:now,angle:p.angle}}
  const onCollision=(e:Event)=>{const d=(e as CustomEvent<Collision>).detail||{},impact=Math.abs(Number(d.speed)||0),loss=Math.max(4,Math.min(28,impact*.7));setCondition(c=>{const n=Math.max(0,c-loss);try{localStorage.setItem(DAMAGE_KEY,String(n))}catch{}dispatchEvent(new CustomEvent('tryamm:streetverse-vehicle-damage',{detail:{condition:n,impact,kind:d.kind||'impact'}}));return n});if(impact>18){setResponse('EMERGENCY RESPONDING');dispatchEvent(new CustomEvent('tryamm:streetverse-emergency-response',{detail:{kind:'traffic-response',severity:impact>28?'high':'medium',x:d.x,z:d.z,services:['traffic-unit',impact>25?'medical':'road-assist']}}));setTimeout(()=>setResponse('CLEAR'),7000)}}
  const onMission=(e:Event)=>{const d=(e as CustomEvent).detail||{};setRace(true);raceStart.current=performance.now();setOpponents([{id:'nova',name:'NOVA',progress:0,speed:26},{id:'south',name:'SOUTH LOOP',progress:0,speed:24},{id:'lake',name:'LAKEFRONT',progress:0,speed:22}]);dispatchEvent(new CustomEvent('tryamm:streetverse-ai-opponents-start',{detail:{mission:d.id||d.label||'streetverse-mission',count:3}}))}
  const onComplete=()=>{setRace(false);setOpponents([])}
  addEventListener('tryamm:streetverse-vehicle-controlled',onVehicle);addEventListener('tryamm:streetverse-drive-telemetry',onTelemetry);addEventListener('tryamm:streetverse-vehicle-collision',onCollision);addEventListener('tryamm:streetverse-mission-start',onMission);addEventListener('tryamm:streetverse-mission-expansion-start',onMission);addEventListener('tryamm:streetverse-mission-complete',onComplete)
  const id=setInterval(()=>{if(!race)return;const now=performance.now();if(now-oppTick.current<180)return;oppTick.current=now;setOpponents(list=>list.map((o,i)=>{const variance=1+Math.sin(now*.001+i*2)*.09;const next=Math.min(100,o.progress+(o.speed*variance)*.018);dispatchEvent(new CustomEvent('tryamm:streetverse-ai-opponent',{detail:{...o,progress:next}}));return {...o,progress:next}}))},180)
  return()=>{clearInterval(id);removeEventListener('tryamm:streetverse-vehicle-controlled',onVehicle);removeEventListener('tryamm:streetverse-drive-telemetry',onTelemetry);removeEventListener('tryamm:streetverse-vehicle-collision',onCollision);removeEventListener('tryamm:streetverse-mission-start',onMission);removeEventListener('tryamm:streetverse-mission-expansion-start',onMission);removeEventListener('tryamm:streetverse-mission-complete',onComplete)}
 },[race,combo])
 const chooseVehicle=(v:'CAR'|'MOTORCYCLE')=>{setVehicle(v);try{localStorage.setItem(ADV_KEY,JSON.stringify({vehicle:v,updatedAt:new Date().toISOString()}))}catch{}dispatchEvent(new CustomEvent('tryamm:streetverse-vehicle-class-select',{detail:{vehicle:v,controlProfile:v==='MOTORCYCLE'?{steerGain:1.18,maxSpeed:43,lean:true}:{steerGain:1,maxSpeed:38,lean:false}}}))}
 const repair=()=>{if(speed>2)return;setCondition(100);try{localStorage.setItem(DAMAGE_KEY,'100')}catch{}dispatchEvent(new CustomEvent('tryamm:streetverse-vehicle-repaired',{detail:{condition:100,source:'service-bay'}}));setResponse('SERVICE COMPLETE');setTimeout(()=>setResponse('CLEAR'),2600)}
 return <div style={{position:'fixed',right:10,top:112,zIndex:16996,width:'min(88vw,286px)',padding:10,borderRadius:14,background:'#030914e8',border:'1px solid #63dcff55',color:'#fff',fontFamily:'system-ui',pointerEvents:'auto'}}><div style={{fontSize:9,fontWeight:950,color:'#70e8ff',letterSpacing:1}}>ADVANCED DRIVE • {perf}</div><div style={{display:'flex',justifyContent:'space-between',gap:8,marginTop:5,fontSize:11,fontWeight:900}}><span>{vehicle} • {driving?'ACTIVE':'READY'}</span><span>{Math.round(speed)} MPH</span></div><div style={{marginTop:5,fontSize:10,color:condition<35?'#ff7777':'#b8c8d6'}}>CONDITION {Math.round(condition)}% • {response}</div><div style={{marginTop:4,fontSize:10,color:'#ffd76b'}}>DRIFT {Math.round(drift)} • x{combo.toFixed(1)}</div>{race&&<div style={{marginTop:6,fontSize:9,color:'#d5e6f3'}}>AI GRID • {opponents.map(o=>`${o.name} ${Math.round(o.progress)}%`).join(' • ')}</div>}<div style={{display:'flex',gap:5,flexWrap:'wrap',marginTop:8}}><button style={btn} onClick={()=>chooseVehicle('CAR')}>CAR</button><button style={btn} onClick={()=>chooseVehicle('MOTORCYCLE')}>🏍 MOTORCYCLE</button><button style={{...btn,opacity:speed<=2?1:.45}} disabled={speed>2} onClick={repair}>🔧 REPAIR</button></div><div style={{marginTop:7,fontSize:8,color:'#8298aa',lineHeight:1.35}}>AI opponent race telemetry • collision damage • repair/service • emergency-response events • motorcycle control profile. Paid rewards remain server-authoritative.</div></div>
}
