import {useEffect,useRef,useState} from 'react'
import * as THREE from 'three'
import {createMobileResidentPopulation,disposeMobileResidentPopulation,tickMobileResidentPopulation} from '../runtime/StreetVerseMobileLivingCityRuntime'
import {createStreetVerseWeatherRenderer,weatherBadge,type StreetVerseWeatherState} from '../runtime/StreetVerseWeatherRuntime'
import useStreetVerseMobileShellMounted from '../hooks/useStreetVerseMobileShellMounted'

const SAVE_KEY='tryamm.streetverse.living.v1'
const clamp=(v:number)=>THREE.MathUtils.clamp(v,-82,82)

export default function StreetVerseMobileWorld({onClose}:{onClose:()=>void}){
 const mountRef=useRef<HTMLDivElement|null>(null)
 const input=useRef({up:false,down:false,left:false,right:false})
 const [status,setStatus]=useState('MOBILE CITY • STARTING')
 const [message,setMessage]=useState('StreetVerse Mobile Mode • lightweight Chicago renderer')
 const [weatherStatus,setWeatherStatus]=useState('WEATHER • CONNECTING')
 const shellControls=useStreetVerseMobileShellMounted()
 useEffect(()=>{
  const mount=mountRef.current;if(!mount)return
  let renderer:THREE.WebGLRenderer
  try{renderer=new THREE.WebGLRenderer({antialias:false,powerPreference:'default',alpha:false})}catch(err){setStatus('WEBGL UNAVAILABLE');setMessage('This browser could not start the 3D renderer. Close other tabs and reload StreetVerse.');return}
  renderer.setPixelRatio(1);renderer.shadowMap.enabled=false;mount.appendChild(renderer.domElement)
  const scene=new THREE.Scene();scene.background=new THREE.Color(0x07101d);scene.fog=new THREE.Fog(0x07101d,75,210)
  const camera=new THREE.PerspectiveCamera(62,1,.1,320);camera.position.set(0,16,24)
  const hemi=new THREE.HemisphereLight(0xb9e7ff,0x151822,2.2);scene.add(hemi);const sun=new THREE.DirectionalLight(0xffdfbc,1.8);sun.position.set(35,55,20);scene.add(sun)
  const weatherRenderer=createStreetVerseWeatherRenderer(scene,hemi,sun,{mobile:true,radius:88})
  let weatherDriveMultiplier=1
  const applyWeather=(state:StreetVerseWeatherState)=>{weatherRenderer.apply(state);weatherDriveMultiplier=weatherRenderer.getVisual().trafficSpeedMultiplier;setWeatherStatus('WEATHER • '+weatherBadge(state))}
  const onWeather=(event:Event)=>applyWeather((event as CustomEvent<StreetVerseWeatherState>).detail)
  addEventListener('tryamm:streetverse-weather-state',onWeather)
  try{const cached=JSON.parse(localStorage.getItem('tryamm.streetverse.weather.v1')||'null') as StreetVerseWeatherState|null;if(cached)applyWeather(cached)}catch{}
  const mat=(c:number)=>new THREE.MeshLambertMaterial({color:c})
  const ground=new THREE.Mesh(new THREE.PlaneGeometry(190,190),mat(0x18221d));ground.rotation.x=-Math.PI/2;scene.add(ground)
  const roadMat=mat(0x20242c),walkMat=mat(0x6b7075)
  for(const v of [-48,0,48]){const r1=new THREE.Mesh(new THREE.BoxGeometry(190,.08,14),roadMat);r1.position.set(0,.04,v);scene.add(r1);const r2=new THREE.Mesh(new THREE.BoxGeometry(14,.08,190),roadMat);r2.position.set(v,.04,0);scene.add(r2);for(const d of [-9,9]){const w1=new THREE.Mesh(new THREE.BoxGeometry(190,.12,3),walkMat);w1.position.set(0,.08,v+d);scene.add(w1);const w2=new THREE.Mesh(new THREE.BoxGeometry(3,.12,190),walkMat);w2.position.set(v+d,.08,0);scene.add(w2)}}
  const colors=[0x24425b,0x41345a,0x31513f,0x5c4032,0x31566b,0x56354e]
  const blocks=[[-70,-70],[-70,-25],[-70,25],[-70,70],[-25,-70],[-25,-25],[-25,25],[-25,70],[25,-70],[25,-25],[25,25],[25,70],[70,-70],[70,-25],[70,25],[70,70]]
  blocks.forEach(([x,z],i)=>{const h=10+(i*7)%22,b=new THREE.Mesh(new THREE.BoxGeometry(15+(i%3)*2,h,15+((i+1)%3)*2),mat(colors[i%colors.length]));b.position.set(x,h/2,z);scene.add(b)})
  const streetTreePositions:[number,number][]=[[-57,-57],[-57,-39],[-57,-9],[-57,9],[-57,39],[-57,57],[-39,-57],[-9,-57],[9,-57],[39,-57],[57,-57],[57,-39],[57,-9],[57,9],[57,39],[57,57],[-39,57],[-9,57],[9,57],[39,57],[-39,-9],[-9,-39],[39,9],[9,39]]
  const treeTrunkGeometry=new THREE.CylinderGeometry(.18,.25,2.2,5),treeCrownGeometry=new THREE.ConeGeometry(1.2,2.8,7)
  const streetTreeTrunks=new THREE.InstancedMesh(treeTrunkGeometry,mat(0x6a4a2e),streetTreePositions.length),streetTreeCrowns=new THREE.InstancedMesh(treeCrownGeometry,mat(0x2f6b42),streetTreePositions.length)
  const treeMatrix=new THREE.Object3D();streetTreePositions.forEach(([x,z],i)=>{const scale=.86+(i%5)*.055;treeMatrix.position.set(x,1.1,z);treeMatrix.rotation.y=(i%8)*.36;treeMatrix.scale.set(scale,scale,scale);treeMatrix.updateMatrix();streetTreeTrunks.setMatrixAt(i,treeMatrix.matrix);treeMatrix.position.set(x,3.05,z);treeMatrix.rotation.y=(i%7)*.41;treeMatrix.scale.set(scale,scale,scale);treeMatrix.updateMatrix();streetTreeCrowns.setMatrixAt(i,treeMatrix.matrix)});streetTreeTrunks.instanceMatrix.needsUpdate=true;streetTreeCrowns.instanceMatrix.needsUpdate=true;streetTreeTrunks.name='streetverse-mobile-tree-trunks';streetTreeCrowns.name='streetverse-mobile-tree-crowns';scene.add(streetTreeTrunks,streetTreeCrowns)
  const river=new THREE.Mesh(new THREE.PlaneGeometry(150,15),new THREE.MeshLambertMaterial({color:0x194e71}));river.rotation.x=-Math.PI/2;river.rotation.z=.08;river.position.set(0,.06,-18);scene.add(river)
  const rail=new THREE.Mesh(new THREE.BoxGeometry(176,.45,2.2),mat(0x4a4e55));rail.position.set(0,6,-35);scene.add(rail);for(let x=-78;x<=78;x+=13){const p=new THREE.Mesh(new THREE.BoxGeometry(.55,6,.55),mat(0x34383d));p.position.set(x,3,-35);scene.add(p)}
  const train=new THREE.Mesh(new THREE.BoxGeometry(13,2.4,2.8),mat(0xd9dde0));train.position.set(-70,7.3,-35);scene.add(train)
  const avatar=new THREE.Group();const body=new THREE.Mesh(new THREE.CapsuleGeometry(.8,1.8,3,8),mat(0x55e4ff));body.position.y=1.8;avatar.add(body);const head=new THREE.Mesh(new THREE.SphereGeometry(.58,10,8),mat(0xc98e67));head.position.y=3.55;avatar.add(head)
  let saved:any={};try{saved=JSON.parse(localStorage.getItem(SAVE_KEY)||'{}')}catch{}avatar.position.set(Number(saved.x??0),0,Number(saved.z??54));scene.add(avatar)
  const missionDefs=[{id:'studio',x:-42,z:-30,c:0xb96cff},{id:'market',x:42,z:-24,c:0x5be7ff},{id:'river',x:38,z:38,c:0xffc95b},{id:'stage',x:-38,z:38,c:0xff4f9a}] as const;missionDefs.forEach(m=>{const beacon=new THREE.Mesh(new THREE.CylinderGeometry(.8,.8,7,10),new THREE.MeshBasicMaterial({color:m.c,transparent:true,opacity:.55}));beacon.position.set(m.x,3.5,m.z);scene.add(beacon)})
  const reachedMissionCheckpoints=new Set<string>()
  const checkMissionProximity=(x:number,z:number)=>{for(const mission of missionDefs){if(reachedMissionCheckpoints.has(mission.id))continue;if(Math.hypot(mission.x-x,mission.z-z)<=7){reachedMissionCheckpoints.add(mission.id);window.dispatchEvent(new CustomEvent('tryamm:streetverse-checkpoint',{detail:{checkpoint:mission.id,id:mission.id,x,z,mobileLite:true,mobileSafeMode:false,htmlCity:false}}));setMessage(`Mission checkpoint reached • ${mission.id.toUpperCase()} • ${reachedMissionCheckpoints.size}/${missionDefs.length}`)}}}
  const cars:THREE.Mesh[]=[];for(let i=0;i<8;i++){const car=new THREE.Mesh(new THREE.BoxGeometry(4.3,1.1,2),mat([0xd94141,0x4288ff,0xd9bd48,0xe8e8e8][i%4]));car.position.set(-75+i*19,.7,i%2?-45:45);scene.add(car);cars.push(car)}
  const starterCar=new THREE.Mesh(new THREE.BoxGeometry(4.6,1.2,2.1),mat(0x36a9e8));starterCar.position.set(6,.75,50);starterCar.userData.playerDrivable=true;scene.add(starterCar);cars.push(starterCar)
  const residents=createMobileResidentPopulation(scene)
  window.dispatchEvent(new CustomEvent('tryamm:streetverse-resident-population-ready',{detail:{mode:'mobile-lite',residentCount:residents.length,lightweight:true}}))
  let activeCar:THREE.Mesh|null=null,driveHeading=0
  const nearestCar=()=>{let car:THREE.Mesh|null=null,distance=Infinity;for(const candidate of cars){if(candidate===activeCar)continue;const d=Math.hypot(candidate.position.x-avatar.position.x,candidate.position.z-avatar.position.z);if(d<distance){distance=d;car=candidate}}return{car,distance}}
  const enterVehicle=()=>{if(activeCar)return;const nearest=nearestCar();const car=nearest.car;if(!car||nearest.distance>20){setMessage('No drivable vehicle close enough. Move nearer to a car and tap ENTER VEHICLE again.');window.dispatchEvent(new CustomEvent('tryamm:streetverse-vehicle-denied',{detail:{reason:'too-far',distance:nearest.distance,mobileLite:true}}));return}activeCar=car;car.userData.userDriven=true;driveHeading=car.rotation.y;body.visible=false;head.visible=false;avatar.position.set(car.position.x,0,car.position.z);setStatus('MOBILE CITY • DRIVING');setMessage('Vehicle control active • W/S or throttle/brake to move • A/D or steer to turn • EXIT VEHICLE returns to walking.');window.dispatchEvent(new CustomEvent('tryamm:streetverse-vehicle-controlled',{detail:{entered:true,mobileLite:true,x:car.position.x,z:car.position.z,vehicleType:'car'}}))}
  const exitVehicle=()=>{if(!activeCar)return;const car=activeCar;avatar.position.set(clamp(car.position.x+Math.sin(driveHeading)*3.5),0,clamp(car.position.z+Math.cos(driveHeading)*3.5));body.visible=true;head.visible=true;activeCar=null;setStatus('MOBILE CITY • PLAYABLE');setMessage('Exited vehicle • walking controls restored. Your car stays parked for re-entry.');window.dispatchEvent(new CustomEvent('tryamm:streetverse-vehicle-controlled',{detail:{entered:false,mobileLite:true,x:avatar.position.x,z:avatar.position.z,vehicleType:'car'}}))}
  const onInteract=(e:Event)=>{const d=(e as CustomEvent<{entered?:boolean}>).detail||{};if(d.entered===false)exitVehicle();else if(d.entered===true)enterVehicle();else activeCar?exitVehicle():enterVehicle()};addEventListener('tryamm:streetverse-vehicle-interact',onInteract)
  const resize=()=>{const w=mount.clientWidth||innerWidth,h=mount.clientHeight||innerHeight;renderer.setSize(w,h,false);camera.aspect=w/Math.max(1,h);camera.updateProjectionMatrix()};resize();addEventListener('resize',resize)
  const key=(e:KeyboardEvent,v:boolean)=>{const k=e.key.toLowerCase();if(k==='w'||k==='arrowup')input.current.up=v;if(k==='s'||k==='arrowdown')input.current.down=v;if(k==='a'||k==='arrowleft')input.current.left=v;if(k==='d'||k==='arrowright')input.current.right=v;if(v&&k==='e'&&!e.repeat){e.preventDefault();activeCar?exitVehicle():enterVehicle()}};const kd=(e:KeyboardEvent)=>key(e,true),ku=(e:KeyboardEvent)=>key(e,false);addEventListener('keydown',kd);addEventListener('keyup',ku)
  const onTouch=(e:Event)=>{const d=(e as CustomEvent<any>).detail||{};input.current.up=Number(d.throttle||0)>.05;input.current.down=Number(d.brake||0)>.05;input.current.left=Number(d.steer||0)<-.1;input.current.right=Number(d.steer||0)>.1;if(d.exit)exitVehicle()};addEventListener('tryamm:streetverse-vehicle-input',onTouch)
  let last=performance.now(),raf=0,saveAt=0
  const tick=(now:number)=>{const dt=Math.min(.05,(now-last)/1000);last=now;const moving=input.current.up||input.current.down||input.current.left||input.current.right;if(activeCar){const throttle=(input.current.up?1:0)-(input.current.down?1:0),steer=(input.current.right?1:0)-(input.current.left?1:0);if(throttle){driveHeading+=steer*1.85*dt*(throttle<0?-1:1);const speed=throttle*20*weatherDriveMultiplier;activeCar.rotation.y=driveHeading;activeCar.position.x=clamp(activeCar.position.x+Math.cos(driveHeading)*speed*dt);activeCar.position.z=clamp(activeCar.position.z-Math.sin(driveHeading)*speed*dt)}avatar.position.set(activeCar.position.x,0,activeCar.position.z);checkMissionProximity(avatar.position.x,avatar.position.z)}else{const s=11*dt;if(input.current.up)avatar.position.z-=s;if(input.current.down)avatar.position.z+=s;if(input.current.left)avatar.position.x-=s;if(input.current.right)avatar.position.x+=s;avatar.position.x=clamp(avatar.position.x);avatar.position.z=clamp(avatar.position.z);checkMissionProximity(avatar.position.x,avatar.position.z)}const focus=activeCar||avatar;camera.position.lerp(new THREE.Vector3(focus.position.x,16,focus.position.z+24),.12);camera.lookAt(focus.position.x,2,focus.position.z-5);train.position.x=-82+((now*.018)%164);cars.forEach((c,i)=>{if(c===activeCar||c.userData.playerDrivable||c.userData.userDriven)return;c.position.x=-82+((now*.012+i*23)%164)});tickMobileResidentPopulation(residents,now);const weatherVisual=weatherRenderer.getVisual();sun.intensity=1.8*weatherVisual.lightMultiplier;hemi.intensity=2.2*weatherVisual.lightMultiplier;weatherRenderer.tick(dt,focus.position);renderer.render(scene,camera);window.dispatchEvent(new CustomEvent('tryamm:streetverse-player-position',{detail:{x:avatar.position.x,z:avatar.position.z,speed:moving?(activeCar?20:11):0,mobileLite:true,vehicle:!!activeCar,vehicleType:activeCar?'car':undefined}}));if(now-saveAt>1200){saveAt=now;try{const old=JSON.parse(localStorage.getItem(SAVE_KEY)||'{}');localStorage.setItem(SAVE_KEY,JSON.stringify({...old,x:avatar.position.x,z:avatar.position.z,updatedAt:new Date().toISOString(),mobileLite:true,vehicle:!!activeCar}))}catch{}}raf=requestAnimationFrame(tick)};raf=requestAnimationFrame(tick);setStatus('MOBILE CITY • LIVING + PLAYABLE');setMessage(`${residents.length} moving residents • ${cars.length} vehicles • ${streetTreePositions.length} street trees • ${blocks.length} city blocks • ${missionDefs.length} missions.`);window.dispatchEvent(new CustomEvent('tryamm:streetverse-world-ready',{detail:{mode:'mobile-lite',canvas:true,drivableVehicles:true,residentCount:residents.length,vehicleCount:cars.length,treeCount:streetTreePositions.length,cityBlockCount:blocks.length,missionCount:missionDefs.length,livingCity:true,visibleCityParity:'lightweight'}}))
  return()=>{cancelAnimationFrame(raf);removeEventListener('resize',resize);removeEventListener('keydown',kd);removeEventListener('keyup',ku);removeEventListener('tryamm:streetverse-vehicle-input',onTouch);removeEventListener('tryamm:streetverse-vehicle-interact',onInteract);removeEventListener('tryamm:streetverse-weather-state',onWeather);weatherRenderer.dispose();disposeMobileResidentPopulation(residents);treeTrunkGeometry.dispose();treeCrownGeometry.dispose();(streetTreeTrunks.material as THREE.Material).dispose();(streetTreeCrowns.material as THREE.Material).dispose();renderer.dispose();renderer.domElement.remove()}
 },[])
 return <div ref={mountRef} data-streetverse-world-root="true" style={{position:'fixed',inset:0,background:'#07101d',overflow:'hidden'}}>{!shellControls&&<div aria-label="StreetVerse movement controls" style={{position:'fixed',left:'max(12px, env(safe-area-inset-left))',bottom:'max(18px, env(safe-area-inset-bottom))',zIndex:30000,width:166,height:150,pointerEvents:'none',font:'900 22px system-ui'}}>{[['↑','up',54,0],['←','left',0,52],['→','right',108,52],['↓','down',54,104]].map(([label,dir,left,top])=><button key={String(dir)} aria-label={`Move ${dir}`} onPointerDown={e=>{e.preventDefault();input.current[dir as 'up'|'down'|'left'|'right']=true}} onPointerUp={()=>{input.current[dir as 'up'|'down'|'left'|'right']=false}} onPointerCancel={()=>{input.current[dir as 'up'|'down'|'left'|'right']=false}} onPointerLeave={()=>{input.current[dir as 'up'|'down'|'left'|'right']=false}} style={{position:'absolute',left:Number(left),top:Number(top),width:58,height:48,pointerEvents:'auto',touchAction:'none',borderRadius:14,border:'2px solid #8ff3ff',background:'rgba(2,18,28,.88)',color:'#fff',font:'900 24px system-ui'}}>{label}</button>)}</div>}<div style={{position:'fixed',left:'max(8px, env(safe-area-inset-left))',top:'max(8px, env(safe-area-inset-top))',zIndex:17020,display:'flex',gap:6,alignItems:'center',pointerEvents:'none',font:'800 10px system-ui'}}><div style={{padding:'6px 8px',borderRadius:999,background:'rgba(3,12,20,.72)',border:'1px solid #5be7ff66',color:'#fff'}}>{status.replace('MOBILE CITY • ','')}</div><div aria-live="polite" style={{padding:'6px 8px',borderRadius:999,background:'rgba(3,12,20,.72)',border:'1px solid #5be7ff66',color:'#9ee8ff'}}>{weatherStatus}</div><button aria-label="Exit StreetVerse" onClick={onClose} style={{pointerEvents:'auto',minWidth:44,minHeight:44,borderRadius:999,border:'1px solid #ffffff33',background:'rgba(18,25,35,.78)',color:'#fff',fontWeight:900}}>×</button></div><div aria-live="polite" style={{position:'fixed',left:8,right:8,top:'max(58px, calc(env(safe-area-inset-top) + 50px))',zIndex:17010,textAlign:'center',pointerEvents:'none',color:'#dffaff',font:'700 10px system-ui',textShadow:'0 1px 4px #000'}}>{message.includes('No drivable')?message:''}</div></div>
}
