import {useEffect,useRef,useState} from 'react'

type Emergency='police'|'ambulance'|'fire'|null
export default function StreetVerseEmergencyLighting(){
 const [kind,setKind]=useState<Emergency>(null),[flash,setFlash]=useState(false),[preempt,setPreempt]=useState(false),[highBeam,setHighBeam]=useState(false)
 const timer=useRef<number|undefined>(undefined)
 useEffect(()=>{const activate=(next:Exclude<Emergency,null>)=>{setKind(next);setPreempt(true);setHighBeam(true);clearTimeout(timer.current);timer.current=window.setTimeout(()=>{setKind(null);setPreempt(false);setHighBeam(false)},12000)};const onEmergency=(e:Event)=>{const d=(e as CustomEvent<any>).detail||{};const raw=String(d.type||d.kind||d.service||'police').toLowerCase();activate(raw.includes('ambul')?'ambulance':raw.includes('fire')?'fire':'police')};const onCollision=(e:Event)=>{const d=(e as CustomEvent<any>).detail||{};if(Number(d.impact||d.severity||d.speed||0)>8)activate('ambulance')};const onRace=()=>activate('police');const onFire=()=>activate('fire');const onPolice=()=>activate('police');addEventListener('tryamm:streetverse-emergency-response',onEmergency);addEventListener('tryamm:streetverse-collision',onCollision);addEventListener('tryamm:streetverse-vehicle-collision',onCollision);addEventListener('tryamm:streetverse-ai-opponents-start',onRace);addEventListener('tryamm:streetverse-fire-response',onFire);addEventListener('tryamm:streetverse-police-response',onPolice);return()=>{clearTimeout(timer.current);removeEventListener('tryamm:streetverse-emergency-response',onEmergency);removeEventListener('tryamm:streetverse-collision',onCollision);removeEventListener('tryamm:streetverse-vehicle-collision',onCollision);removeEventListener('tryamm:streetverse-ai-opponents-start',onRace);removeEventListener('tryamm:streetverse-fire-response',onFire);removeEventListener('tryamm:streetverse-police-response',onPolice)}},[])
 useEffect(()=>{if(!kind){setFlash(false);return}const t=window.setInterval(()=>setFlash(v=>!v),105);return()=>clearInterval(t)},[kind])
 useEffect(()=>{if(!kind)return;const t=window.setInterval(()=>setHighBeam(v=>!v),280);return()=>clearInterval(t)},[kind])
 useEffect(()=>{if(!kind)return;window.dispatchEvent(new CustomEvent('tryamm:streetverse-traffic-preemption',{detail:{active:true,emergency:kind,intersectionSignal:'red-cross-traffic',emergencyLane:'priority',highBeams:true,strobes:true,flashToPass:true,clearRoute:true}}));window.dispatchEvent(new CustomEvent('tryamm:streetverse-signal-override',{detail:{active:true,mode:'emergency-preemption',crossTraffic:'red',approachLane:'green',emergency:kind}}));return()=>{window.dispatchEvent(new CustomEvent('tryamm:streetverse-traffic-preemption',{detail:{active:false,emergency:kind}}));window.dispatchEvent(new CustomEvent('tryamm:streetverse-signal-override',{detail:{active:false,mode:'normal'}}))}},[kind])
 if(!kind)return null
 const left=kind==='fire'?'#ff2b18':kind==='ambulance'?'#ff2a2a':'#ff2438',right=kind==='fire'?'#ffd43b':kind==='ambulance'?'#ffffff':'#2474ff'
 return <div aria-label={`${kind} emergency lights active`} style={{position:'fixed',inset:0,zIndex:16980,pointerEvents:'none',boxShadow:`inset ${flash?'118px':'38px'} 0 150px ${left}55,inset -${flash?'38px':'118px'} 0 150px ${right}55`,transition:'box-shadow 55ms linear'}}>
  <div style={{position:'absolute',top:12,left:'50%',transform:'translateX(-50%)',display:'flex',gap:4,padding:'5px 7px',borderRadius:8,background:'#05080ddd',border:'1px solid #ffffff33'}}><i style={{width:48,height:12,borderRadius:4,background:flash?left:'#401016',boxShadow:flash?`0 0 36px ${left}`:'none'}}/><i style={{width:48,height:12,borderRadius:4,background:flash?'#162343':right,boxShadow:flash?'none':`0 0 36px ${right}`}}/></div>
  <div style={{position:'absolute',left:'50%',bottom:54,transform:'translateX(-50%)',width:highBeam?390:225,height:highBeam?130:78,borderRadius:'50%',background:'radial-gradient(ellipse,rgba(255,255,235,.72),rgba(255,255,225,0) 70%)',filter:'blur(5px)',transition:'all 90ms linear'}}/>
  <div style={{position:'absolute',left:'18%',bottom:'24%',width:'28%',height:'34%',background:`radial-gradient(ellipse at bottom,${left}66,transparent 70%)`,opacity:flash?.72:.12,transform:'rotate(-7deg)'}}/>
  <div style={{position:'absolute',right:'18%',bottom:'24%',width:'28%',height:'34%',background:`radial-gradient(ellipse at bottom,${right}66,transparent 70%)`,opacity:flash?.12:.72,transform:'rotate(7deg)'}}/>
  {preempt&&<div style={{position:'absolute',top:39,left:'50%',transform:'translateX(-50%)',padding:'4px 8px',borderRadius:7,background:'#190808dd',border:'1px solid #ff3a3a66',color:'#fff',font:'800 9px system-ui',letterSpacing:.7}}>EMERGENCY PRIORITY • FLICK HIGH BEAMS • STROBES • CROSS TRAFFIC RED • CLEAR ROUTE</div>}
 </div>
}
