import {useEffect} from 'react'
import * as THREE from 'three'
import {subscribeStreetVerseScene} from '../game/streetverseSceneRegistry'

type Store={id:string;label:string;district:string;x:number;z:number;color:number;accent:number;kind:string}
const stores:Store[]=[
{id:'loop-courier',label:'LOOP EXPRESS HUB',district:'THE LOOP',x:0,z:18,color:0x3b4652,accent:0xf0b429,kind:'DELIVERY'},
{id:'riverwalk-creator',label:'RIVERWALK CREATOR STUDIO',district:'CHICAGO RIVER',x:18,z:10,color:0x274c77,accent:0x62c8ff,kind:'CREATOR'},
{id:'millennium-event',label:'MILLENNIUM EVENT PAVILION',district:'LAKEFRONT',x:48,z:100,color:0x4d5966,accent:0xd8f3ff,kind:'SOCIAL'},
{id:'south-market',label:'79TH STREET MARKET',district:'SOUTH SIDE',x:-12,z:111,color:0x6d3c2f,accent:0xf3c969,kind:'JOB'},
{id:'west-maker',label:'MADISON MAKER HUB',district:'WEST SIDE',x:-64,z:-7,color:0x5b3f62,accent:0xc58cff,kind:'JOB'},
{id:'north-night',label:'NORTH SIDE CREATOR VENUE',district:'NORTH SIDE',x:18,z:-69,color:0x252b3d,accent:0xff5db1,kind:'CREATOR'},
]
const mat=(c:number,e=0,ei=0)=>new THREE.MeshStandardMaterial({color:c,roughness:.62,metalness:.18,emissive:new THREE.Color(e),emissiveIntensity:ei})
function signSprite(text:string){const c=document.createElement('canvas');c.width=768;c.height=128;const x=c.getContext('2d')!;x.fillStyle='rgba(5,12,20,.94)';x.fillRect(0,0,c.width,c.height);x.strokeStyle='#ffffff';x.lineWidth=4;x.strokeRect(4,4,c.width-8,c.height-8);x.fillStyle='#fff';x.font='900 42px Arial';x.textAlign='center';x.textBaseline='middle';x.fillText(text,384,64);const tex=new THREE.CanvasTexture(c);const s=new THREE.Sprite(new THREE.SpriteMaterial({map:tex,transparent:true}));s.scale.set(11,1.85,1);return s}
function buildStore(s:Store){const g=new THREE.Group();g.name=`streetverse-store-${s.id}`;g.position.set(s.x,0,s.z);const shell=new THREE.Mesh(new THREE.BoxGeometry(12,7,9),mat(s.color));shell.position.y=3.5;shell.castShadow=shell.receiveShadow=true;g.add(shell);const front=new THREE.Mesh(new THREE.BoxGeometry(8,3.3,.18),mat(0x6b8798));front.position.set(0,2.4,-4.58);g.add(front);const door=new THREE.Mesh(new THREE.BoxGeometry(2.2,3.2,.22),mat(s.accent,s.accent,.45));door.position.set(0,1.7,-4.7);g.add(door);const awning=new THREE.Mesh(new THREE.BoxGeometry(9,.45,1.3),mat(s.accent,s.accent,.2));awning.position.set(0,4.7,-4.85);g.add(awning);const sign=signSprite(s.label);sign.position.set(0,6.6,-4.9);g.add(sign);const marker=new THREE.Mesh(new THREE.TorusGeometry(1.5,.12,8,24),mat(s.accent,s.accent,1.3));marker.rotation.x=Math.PI/2;marker.position.set(0,.12,-6.2);g.add(marker);g.userData.store=s;return g}
export default function StreetVerseChicagoStorefronts(){useEffect(()=>{let group:THREE.Group|null=null;let scene:THREE.Scene|null=null;let near='';const mount=(handle:ReturnType<typeof import('../game/streetverseSceneRegistry')['getStreetVerseScene']>)=>{if(group&&scene)scene.remove(group);group=null;scene=null;if(!handle)return;scene=handle.scene;group=new THREE.Group();group.name='streetverse-chicago-mission-storefronts';stores.forEach(s=>group!.add(buildStore(s)));scene.add(group);window.dispatchEvent(new CustomEvent('tryamm:chicago-storefronts-ready',{detail:{count:stores.length,native:true}}))};const unsubscribe=subscribeStreetVerseScene(mount);const onPos=(e:Event)=>{const d=(e as CustomEvent).detail||{};if(!Number.isFinite(d.x)||!Number.isFinite(d.z))return;const closest=stores.map(s=>({...s,distance:Math.hypot(d.x-s.x,d.z-s.z)})).sort((a,b)=>a.distance-b.distance)[0];if(closest&&closest.distance<=10&&near!==closest.id){near=closest.id;window.dispatchEvent(new CustomEvent('tryamm:chicago-storefront-near',{detail:{id:closest.id,label:closest.label,district:closest.district,kind:closest.kind,distance:closest.distance}}))}else if(closest&&closest.distance>14&&near){near=''}};window.addEventListener('tryamm:streetverse-player-position',onPos);return()=>{unsubscribe();window.removeEventListener('tryamm:streetverse-player-position',onPos);if(group&&scene)scene.remove(group)}},[]);return null}
