import { useEffect, useMemo, useState } from 'react'
import { applyConnectivityRole, createHoloFonLine, listConnectivityMarkets, listConnectivityProviders, listMyHoloFonLines, listMyQuantumEmail, reserveQuantumEmail, type HoloFonLine, type Market, type Provider, type QuantumEmail } from '../services/tryammConnect'
import ConnectivityOptimizerPanel from './ConnectivityOptimizerPanel'
import QuantumNetworkTelemetryPanel from './QuantumNetworkTelemetryPanel'

interface Props{onClose:()=>void}
type NetworkView='overview'|'access'|'identity'|'providers'
export default function TryAMMConnectCenter({onClose}:Props){
 const [providers,setProviders]=useState<Provider[]>([]),[markets,setMarkets]=useState<Market[]>([]),[lines,setLines]=useState<HoloFonLine[]>([]),[emails,setEmails]=useState<QuantumEmail[]>([]),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[handle,setHandle]=useState(''),[market,setMarket]=useState('US'),[role,setRole]=useState('dealer'),[view,setView]=useState<NetworkView>('overview')
 async function load(){try{const [p,m,l,e]=await Promise.all([listConnectivityProviders(),listConnectivityMarkets(),listMyHoloFonLines(),listMyQuantumEmail()]);setProviders(p);setMarkets(m);setLines(l);setEmails(e)}catch(e){setMessage(e instanceof Error?e.message:String(e))}}
 useEffect(()=>{load()},[])
 const connectedProviders=useMemo(()=>providers.filter(p=>p.integration_status==='connected').length,[providers]),liveMarkets=useMemo(()=>markets.filter(m=>m.status==='live').length,[markets])
 const box:React.CSSProperties={background:'linear-gradient(155deg,#071723,#061019)',border:'1px solid #21415a',borderRadius:16,padding:14,boxShadow:'0 14px 36px #0005'},btn:React.CSSProperties={background:'#0d2633',border:'1px solid #4fe3ff66',color:'#bff6ff',borderRadius:10,padding:'10px 12px',cursor:'pointer',fontFamily:'monospace',fontWeight:800},tab=(active:boolean):React.CSSProperties=>({...btn,background:active?'linear-gradient(135deg,#12384b,#1b2144)':'#07131d',borderColor:active?'#4fe3ff':'#21415a',color:active?'#fff':'#8fb3c4'})
 return <div style={{position:'fixed',inset:0,zIndex:10090,background:'radial-gradient(circle at 50% 0,#0a2940 0,#02060f 48%)',color:'#eefcff',fontFamily:'monospace',overflowY:'auto'}}><div style={{maxWidth:1180,margin:'0 auto',padding:'max(16px,env(safe-area-inset-top)) 16px 40px'}}><header style={{display:'flex',gap:12,alignItems:'center',justifyContent:'space-between',flexWrap:'wrap'}}><div style={{display:'flex',gap:12,alignItems:'center'}}><button style={btn} onClick={onClose}>← Back</button><div><div style={{fontSize:10,color:'#78ffb4',letterSpacing:2,fontWeight:900}}>QUANTUM NETWORK</div><h2 style={{margin:'2px 0',color:'#4fe3ff'}}>TRYAMM Connect • Network OS</h2><div style={{fontSize:10,color:'#8aa9b9'}}>Identity • discovery • device trust • mesh • edge/cache • HoloGPT • Time • Wallet • CTV • access routing</div></div></div></header>
 <section style={{...box,marginTop:14,borderColor:'#4fe3ff55'}}><div style={{fontSize:10,color:'#4fe3ff',fontWeight:900,letterSpacing:2}}>YOUR INTERNET LAYER</div><h1 style={{margin:'6px 0 8px',fontSize:'clamp(24px,5vw,44px)',lineHeight:1}}>One identity. Every TRYAMM service. Best approved connection.</h1><div style={{maxWidth:820,fontSize:11,color:'#b7cad5',lineHeight:1.7}}>Quantum Network connects URA identity, trusted devices, service discovery, HoloGPT, StreetVerse, Quantum Time, Pocket Dimensions, Holo Ads/CTV, Wallet and commerce. Physical carrier, spectrum, fiber and satellite operations remain separately gated until contracted and verified.</div><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(150px,1fr))',gap:9,marginTop:14}}>{[['DEVICE',typeof navigator!=='undefined'&&navigator.onLine?'ONLINE':'OFFLINE'],['PROVIDERS',`${connectedProviders}/${providers.length} CONNECTED`],['MARKETS',`${liveMarkets}/${markets.length} LIVE`],['HOLO FON',`${lines.length} PROFILES`],['QUANTUM ID',`${emails.length} RESERVED`]].map(([a,b])=><div key={a} style={{...box,padding:11}}><div style={{fontSize:8,color:'#7595a7'}}>{a}</div><div style={{marginTop:6,fontSize:12,fontWeight:900,color:'#78ffb4'}}>{b}</div></div>)}</div></section>
 <nav style={{display:'grid',gridTemplateColumns:'repeat(4,minmax(0,1fr))',gap:8,marginTop:12}}>{([['overview','Network'],['access','Access'],['identity','Identity'],['providers','Readiness']] as const).map(([k,l])=><button key={k} style={tab(view===k)} onClick={()=>setView(k)}>{l}</button>)}</nav>
 {message&&<div role="status" style={{...box,marginTop:12}}>{message}</div>}
 {view==='overview'&&<><QuantumNetworkTelemetryPanel/><section style={{marginTop:14}}><h3>Service mesh + revenue fabric</h3><div style={{...box,color:'#b9cad6',lineHeight:1.85,fontSize:11}}>URA ID → TRUSTED DEVICE → QUANTUM DNS → ENCRYPTED MESH → EDGE / CACHE → HOLOGPT ROUTER → STREETVERSE / QUANTUM TIME / POCKET DIMENSIONS → HOLO ADS / CTV → MARKETPLACE → WALLET / LEDGER<br/><br/>ACCESS ROUTER → APPROVED WIFI / INTERNET / FIXED WIRELESS / FIBER / CELLULAR / SATELLITE → HEALTH POLICY → LOW-RISK FAILOVER</div></section><ConnectivityOptimizerPanel providers={providers} markets={markets}/></>}
 {view==='access'&&<div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(280px,1fr))',gap:12,marginTop:14}}><section style={box}><h3>Holo Fon access</h3>{lines.map(x=><div key={x.id}><b>{x.nickname}</b><div style={{fontSize:10,color:'#8fa6b4'}}>{x.status} • eSIM {x.esim_status}</div></div>)}<button style={{...btn,marginTop:10}} disabled={busy} onClick={async()=>{setBusy(true);try{await createHoloFonLine('personal');await load()}finally{setBusy(false)}}}>+ Create Holo Fon Profile</button></section><section style={box}><h3>Dealer + jobs network</h3><select value={market} onChange={e=>setMarket(e.target.value)} style={{width:'100%',padding:9,background:'#04101a',color:'#fff'}}>{markets.map(m=><option key={m.market_code}>{m.market_code}</option>)}</select><select value={role} onChange={e=>setRole(e.target.value)} style={{width:'100%',marginTop:8,padding:9,background:'#04101a',color:'#fff'}}>{['dealer','installer','support','repair','enterprise-sales','accessibility-specialist'].map(r=><option key={r}>{r}</option>)}</select><button style={{...btn,marginTop:8}} onClick={async()=>{setBusy(true);try{await applyConnectivityRole(market,role);setMessage('Interest submitted; availability remains readiness-gated.')}finally{setBusy(false)}}}>Apply</button></section></div>}
 {view==='identity'&&<section style={{...box,marginTop:14}}><h3>Quantum Email + URA identity</h3>{emails.map(x=><div key={x.id}><b>{x.handle}@{x.domain}</b><div style={{fontSize:10,color:'#8fa6b4'}}>{x.security_mode} • {x.status}</div></div>)}<input value={handle} onChange={e=>setHandle(e.target.value)} placeholder="yourname" aria-label="Quantum Email handle" style={{width:'100%',marginTop:10,padding:9,background:'#04101a',color:'#fff'}}/><button style={{...btn,marginTop:8}} disabled={busy||!handle.trim()} onClick={async()=>{setBusy(true);try{await reserveQuantumEmail(handle);setHandle('');await load()}finally{setBusy(false)}}}>Reserve @tryamm.online Identity</button></section>}
 {view==='providers'&&<><h3 style={{marginTop:18}}>Provider readiness</h3><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(260px,1fr))',gap:10}}>{providers.map(p=><div key={p.provider_key} style={box}><b>{p.name}</b><span style={{float:'right',fontSize:9,color:p.integration_status==='connected'?'#78ffb4':'#e8b944'}}>{p.integration_status}</span><div style={{fontSize:10,color:'#8fa6b4',marginTop:7}}>{p.capabilities.join(' • ')}</div></div>)}</div></>}
 <div style={{...box,marginTop:14,borderColor:'#e8b94466',fontSize:10,color:'#a8bbc4',lineHeight:1.6}}><b style={{color:'#e8b944'}}>Production boundary:</b> licensed spectrum, carrier voice/data, number porting, eSIM provisioning, physical fiber/radio sites, satellite capacity, real CTV spend and real-money settlement are not marked live without verified providers, credentials, contracts and production evidence.</div></div></div>
}
