import { useEffect, useMemo, useState } from 'react'
import { applyConnectivityRole, createHoloFonLine, listConnectivityMarkets, listConnectivityProviders, listMyHoloFonLines, listMyQuantumEmail, reserveQuantumEmail, type HoloFonLine, type Market, type Provider, type QuantumEmail } from '../services/tryammConnect'
import ConnectivityOptimizerPanel from './ConnectivityOptimizerPanel'

interface Props{onClose:()=>void}
type NetworkView='overview'|'access'|'identity'|'providers'

export default function TryAMMConnectCenter({onClose}:Props){
 const [providers,setProviders]=useState<Provider[]>([]),[markets,setMarkets]=useState<Market[]>([]),[lines,setLines]=useState<HoloFonLine[]>([]),[emails,setEmails]=useState<QuantumEmail[]>([]),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[handle,setHandle]=useState(''),[market,setMarket]=useState('US'),[role,setRole]=useState('dealer'),[view,setView]=useState<NetworkView>('overview')
 async function load(){try{const [p,m,l,e]=await Promise.all([listConnectivityProviders(),listConnectivityMarkets(),listMyHoloFonLines(),listMyQuantumEmail()]);setProviders(p);setMarkets(m);setLines(l);setEmails(e)}catch(e){setMessage(e instanceof Error?e.message:String(e))}}
 useEffect(()=>{load()},[])
 const connectedProviders=useMemo(()=>providers.filter(p=>p.integration_status==='connected').length,[providers])
 const liveMarkets=useMemo(()=>markets.filter(m=>m.status==='live').length,[markets])
 const box:React.CSSProperties={background:'linear-gradient(155deg,#071723,#061019)',border:'1px solid #21415a',borderRadius:16,padding:14,boxShadow:'0 14px 36px #0005'}
 const btn:React.CSSProperties={background:'#0d2633',border:'1px solid #4fe3ff66',color:'#bff6ff',borderRadius:10,padding:'10px 12px',cursor:'pointer',fontFamily:'monospace',fontWeight:800}
 const tab=(active:boolean):React.CSSProperties=>({...btn,background:active?'linear-gradient(135deg,#12384b,#1b2144)':'#07131d',borderColor:active?'#4fe3ff':'#21415a',color:active?'#fff':'#8fb3c4'})
 const status=(ready:boolean)=>({fontSize:9,fontWeight:900,color:ready?'#78ffb4':'#e8b944',letterSpacing:1})
 return <div style={{position:'fixed',inset:0,zIndex:10090,background:'radial-gradient(circle at 50% 0,#0a2940 0,#02060f 48%)',color:'#eefcff',fontFamily:'monospace',overflowY:'auto'}}><div style={{maxWidth:1180,margin:'0 auto',padding:'max(16px,env(safe-area-inset-top)) 16px 40px'}}>
  <header style={{display:'flex',gap:12,alignItems:'center',justifyContent:'space-between',flexWrap:'wrap'}}><div style={{display:'flex',gap:12,alignItems:'center'}}><button style={btn} onClick={onClose}>← Back</button><div><div style={{fontSize:10,color:'#78ffb4',letterSpacing:2,fontWeight:900}}>QUANTUM NETWORK</div><h2 style={{margin:'2px 0',color:'#4fe3ff'}}>TRYAMM Connect • Network OS</h2><div style={{fontSize:10,color:'#8aa9b9'}}>Identity • service discovery • access orchestration • provider routing • Holo Fon • Quantum Email</div></div></div><div style={{display:'flex',gap:8,alignItems:'center'}}><span style={status(navigator.onLine)}>● {navigator.onLine?'DEVICE ONLINE':'DEVICE OFFLINE'}</span></div></header>

  <section style={{...box,marginTop:14,borderColor:'#4fe3ff55'}}><div style={{display:'flex',justifyContent:'space-between',gap:12,flexWrap:'wrap'}}><div><div style={{fontSize:10,color:'#4fe3ff',fontWeight:900,letterSpacing:2}}>YOUR INTERNET LAYER</div><h1 style={{margin:'6px 0 8px',fontSize:'clamp(24px,5vw,44px)',lineHeight:1}}>One identity. Every TRYAMM service. Best approved connection.</h1><div style={{maxWidth:760,fontSize:11,color:'#b7cad5',lineHeight:1.7}}>Quantum Network is the software network overlay that connects URA identity, HoloGPT, StreetVerse, Quantum Time, Pocket Dimensions, Wallet, Marketplace, Live and Holo Fon. It can route across approved internet, Wi-Fi, fixed wireless, cellular and satellite providers without claiming ownership of infrastructure that has not been deployed.</div></div></div>
   <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(150px,1fr))',gap:9,marginTop:14}}>{[
    ['DEVICE',navigator.onLine?'READY':'OFFLINE',navigator.onLine],['PROVIDERS',`${connectedProviders}/${providers.length} CONNECTED`,connectedProviders>0],['MARKETS',`${liveMarkets}/${markets.length} LIVE`,liveMarkets>0],['HOLO FON',`${lines.length} PROFILE${lines.length===1?'':'S'}`,lines.length>0],['QUANTUM ID',`${emails.length} RESERVED`,emails.length>0]
   ].map(([label,value,ready])=><div key={String(label)} style={{...box,padding:11}}><div style={{fontSize:8,color:'#7595a7',letterSpacing:1}}>{label}</div><div style={{marginTop:6,fontSize:12,fontWeight:900,color:ready?'#78ffb4':'#e8b944'}}>{value}</div></div>)}</div>
  </section>

  <nav aria-label="Quantum Network sections" style={{display:'grid',gridTemplateColumns:'repeat(4,minmax(0,1fr))',gap:8,marginTop:12}}>{([['overview','Network'],['access','Access'],['identity','Identity'],['providers','Readiness']] as const).map(([key,label])=><button key={key} style={tab(view===key)} onClick={()=>setView(key)}>{label}</button>)}</nav>

  <div style={{...box,marginTop:12,borderColor:'#e8b94466'}}><b style={{color:'#e8b944'}}>Production boundary</b><div style={{fontSize:11,color:'#a8bbc4',marginTop:6,lineHeight:1.6}}>TRYAMM can own the customer software, identity, accessibility, AI, encrypted application traffic and orchestration layer. Voice/SMS/data, number porting, eSIM activation, satellite service, Lifeline reimbursement, licensed spectrum, fiber and physical radio infrastructure remain gated until the required provider contracts, licenses and deployment evidence are verified.</div></div>
  {message&&<div role="status" style={{...box,marginTop:12,borderColor:'#4fe3ff66'}}>{message}</div>}

  {view==='overview'&&<>
   <section style={{marginTop:14}}><h3>Quantum Network service mesh</h3><div style={{...box,color:'#b9cad6',lineHeight:1.8,fontSize:11}}>URA IDENTITY → QUANTUM NETWORK → HOLOGPT → STREETVERSE → QUANTUM ZOOM → QUANTUM TIME → POCKET DIMENSIONS → LIVE / MUSIC / TV → MARKETPLACE → WALLET / LEDGER<br/><br/>DEVICE → WIFI / INTERNET → APPROVED CELLULAR / FIXED WIRELESS → APPROVED SATELLITE FALLBACK → POLICY ROUTER → SERVICE HEALTH → LOW-RISK FAILOVER</div></section>
   <section style={{marginTop:14}}><h3>Network layers</h3><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(220px,1fr))',gap:10}}>{[
    ['1 • Identity','URA identity, device trust and permissions.'],['2 • Discovery','Find TRYAMM apps, worlds, APIs and user-authorized services.'],['3 • Routing','Choose an approved available access path based on health and policy.'],['4 • Security','Authenticated sessions, encryption, abuse controls and audit evidence.'],['5 • Persistence','Keep Pocket Dimensions, messages, world state and transactions synchronized.'],['6 • Economy','Connect Holo Credit usage, Wallet commerce and verified settlement without mixing ledger classes.']
   ].map(([title,text])=><article key={title} style={box}><b style={{color:'#4fe3ff'}}>{title}</b><div style={{fontSize:10,color:'#9fb5c1',lineHeight:1.55,marginTop:7}}>{text}</div></article>)}</div></section>
   <ConnectivityOptimizerPanel providers={providers} markets={markets}/>
  </>}

  {view==='access'&&<div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(280px,1fr))',gap:12,marginTop:14}}>
   <section style={box}><h3>Holo Fon access</h3>{lines.length===0&&<div style={{fontSize:10,color:'#8199a7'}}>No Holo Fon profile yet.</div>}{lines.map(x=><div key={x.id} style={{padding:'9px 0',borderBottom:'1px solid #183041'}}><b>{x.nickname}</b><div style={{fontSize:10,color:'#8fa6b4'}}>{x.line_type} • {x.status} • eSIM {x.esim_status}</div></div>)}<button style={{...btn,marginTop:10}} disabled={busy} onClick={async()=>{setBusy(true);try{await createHoloFonLine('personal');await load();setMessage('Holo Fon profile created. Real carrier provisioning remains gated.')}finally{setBusy(false)}}}>+ Create Holo Fon Profile</button></section>
   <section style={box}><h3>Dealer + jobs network</h3><select aria-label="Connectivity market" value={market} onChange={e=>setMarket(e.target.value)} style={{width:'100%',padding:9,borderRadius:8,background:'#04101a',color:'#fff',border:'1px solid #294a58'}}>{markets.map(m=><option key={m.market_code} value={m.market_code}>{m.market_name}</option>)}</select><select aria-label="Connectivity role" value={role} onChange={e=>setRole(e.target.value)} style={{width:'100%',marginTop:8,padding:9,borderRadius:8,background:'#04101a',color:'#fff',border:'1px solid #294a58'}}>{['dealer','installer','support','repair','enterprise-sales','accessibility-specialist'].map(r=><option key={r}>{r}</option>)}</select><button style={{...btn,marginTop:8}} disabled={busy} onClick={async()=>{setBusy(true);try{await applyConnectivityRole(market,role);setMessage('Interest submitted. Approval and work availability depend on market/provider readiness.')}finally{setBusy(false)}}}>Apply for Connectivity Role</button></section>
  </div>}

  {view==='identity'&&<div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(280px,1fr))',gap:12,marginTop:14}}>
   <section style={box}><h3>Quantum Email identity</h3>{emails.length===0&&<div style={{fontSize:10,color:'#8199a7'}}>Reserve a TRYAMM identity for the application network.</div>}{emails.map(x=><div key={x.id} style={{padding:'9px 0',borderBottom:'1px solid #183041'}}><b>{x.handle}@{x.domain}</b><div style={{fontSize:10,color:'#8fa6b4'}}>{x.security_mode} • {x.status} • HoloGPT assist {x.hologpt_assist?'on':'off'}</div></div>)}<input aria-label="Quantum Email handle" value={handle} onChange={e=>setHandle(e.target.value)} placeholder="yourname" style={{width:'100%',boxSizing:'border-box',marginTop:10,padding:9,borderRadius:8,border:'1px solid #294a58',background:'#04101a',color:'#fff'}}/><button style={{...btn,marginTop:8}} disabled={busy||!handle.trim()} onClick={async()=>{setBusy(true);try{await reserveQuantumEmail(handle);setHandle('');await load();setMessage('Quantum Email identity reserved. Mail transport remains gated until a verified provider is connected.')}finally{setBusy(false)}}}>Reserve @tryamm.online Identity</button></section>
   <section style={box}><h3>Identity promise</h3><div style={{fontSize:11,color:'#a9bec9',lineHeight:1.7}}>Use one authorized identity across HoloGPT, StreetVerse, Quantum Time, Pocket Dimensions and commerce. Network identity is not a carrier phone number, bank account or government identity. Each regulated function remains separately verified.</div></section>
  </div>}

  {view==='providers'&&<>
   <h3 style={{marginTop:18}}>Provider readiness</h3><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(260px,1fr))',gap:10}}>{providers.map(p=><div key={p.provider_key} style={box}><div style={{display:'flex',justifyContent:'space-between',gap:8}}><b>{p.name}</b><span style={{fontSize:9,color:p.integration_status==='connected'?'#78ffb4':'#e8b944'}}>{p.integration_status}</span></div><div style={{fontSize:10,color:'#8fa6b4',marginTop:6}}>{p.provider_type} • {p.service_regions.join(', ')}</div><div style={{fontSize:10,color:'#b4c4cf',marginTop:7}}>{p.capabilities.join(' • ')}</div></div>)}</div>
   <h3 style={{marginTop:18}}>Market readiness</h3><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(260px,1fr))',gap:10}}>{markets.map(m=><div key={m.market_code} style={box}><b>{m.market_name}</b><span style={{float:'right',fontSize:9,color:m.status==='live'?'#78ffb4':'#e8b944'}}>{m.status}</span><div style={{fontSize:10,color:'#8fa6b4',marginTop:7}}>Wi-Fi {m.wifi?'✓':'—'} • Voice {m.mobile_voice?'✓':'gated'} • Data {m.mobile_data?'✓':'gated'} • eSIM {m.esim?'✓':'gated'} • Satellite {m.satellite_ntn?'✓':'gated'}</div><div style={{fontSize:10,color:'#aebdc7',marginTop:7,lineHeight:1.5}}>{m.regulatory_notes}</div></div>)}</div>
  </>}
 </div></div>
}
