import { useEffect, useState } from 'react'
import { applyConnectivityRole, createHoloFonLine, listConnectivityMarkets, listConnectivityProviders, listMyHoloFonLines, listMyQuantumEmail, reserveQuantumEmail, type HoloFonLine, type Market, type Provider, type QuantumEmail } from '../services/tryammConnect'

interface Props{onClose:()=>void}
export default function TryAMMConnectCenter({onClose}:Props){
 const [providers,setProviders]=useState<Provider[]>([]),[markets,setMarkets]=useState<Market[]>([]),[lines,setLines]=useState<HoloFonLine[]>([]),[emails,setEmails]=useState<QuantumEmail[]>([]),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[handle,setHandle]=useState(''),[market,setMarket]=useState('US'),[role,setRole]=useState('dealer')
 async function load(){try{const [p,m,l,e]=await Promise.all([listConnectivityProviders(),listConnectivityMarkets(),listMyHoloFonLines(),listMyQuantumEmail()]);setProviders(p);setMarkets(m);setLines(l);setEmails(e)}catch(e){setMessage(e instanceof Error?e.message:String(e))}}
 useEffect(()=>{load()},[])
 const box:React.CSSProperties={background:'#07131d',border:'1px solid #21415a',borderRadius:14,padding:13},btn:React.CSSProperties={background:'#0d2633',border:'1px solid #4fe3ff66',color:'#bff6ff',borderRadius:9,padding:'9px 11px',cursor:'pointer',fontFamily:'monospace'}
 return <div style={{position:'fixed',inset:0,zIndex:10090,background:'rgba(2,6,15,.99)',color:'#eefcff',fontFamily:'monospace',overflowY:'auto'}}><div style={{maxWidth:1180,margin:'0 auto',padding:16}}>
  <div style={{display:'flex',gap:12,alignItems:'center'}}><button style={btn} onClick={onClose}>← Back</button><div><h2 style={{margin:0,color:'#4fe3ff'}}>TRYAMM Connect • Holo Fon</h2><div style={{fontSize:10,color:'#8aa9b9'}}>Multi-carrier control plane • eSIM-ready architecture • Wi-Fi/fixed wireless • satellite/NTN fallback • Quantum Email • dealer/jobs</div></div></div>
  <div style={{...box,marginTop:14,borderColor:'#e8b94466'}}><b style={{color:'#e8b944'}}>Production boundary</b><div style={{fontSize:11,color:'#a8bbc4',marginTop:6}}>TRYAMM owns the customer software, identity, accessibility, AI and orchestration layer. Voice/SMS/data, number porting, eSIM activation, satellite service, Lifeline reimbursement and licensed spectrum remain disabled until an authorized provider/market contract is verified.</div></div>
  {message&&<div style={{...box,marginTop:12}}>{message}</div>}
  <section style={{marginTop:14}}><h3>Connectivity flywheel</h3><div style={{...box,color:'#b9cad6',lineHeight:1.7,fontSize:11}}>CUSTOMER → HOLO FON → CONNECTIVITY → QUANTUM EMAIL → HOLOGPT → TRYAMM APPS → MUSIC / TV / GAMES / MARKETPLACE → OMNIWEAR → PAYMENTS → CREATOR / BUSINESS REVENUE → LOCAL DEALERS / JOBS → MORE CUSTOMERS<br/><br/>MULTI-CARRIER WHOLESALE → BEST AVAILABLE APPROVED NETWORK → eSIM → WIFI / FIXED WIRELESS → SATELLITE FALLBACK → QUANTUM NETWORK CONTROL PLANE → COMMAND NEXUS HEALTH → AUTOMATIC LOW-RISK FAILOVER</div></section>
  <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(280px,1fr))',gap:12,marginTop:14}}>
   <section style={box}><h3>Holo Fon lines</h3>{lines.map(x=><div key={x.id} style={{padding:'9px 0',borderBottom:'1px solid #183041'}}><b>{x.nickname}</b><div style={{fontSize:10,color:'#8fa6b4'}}>{x.line_type} • {x.status} • eSIM {x.esim_status}</div></div>)}<button style={{...btn,marginTop:10}} disabled={busy} onClick={async()=>{setBusy(true);try{await createHoloFonLine('personal');await load();setMessage('Holo Fon profile created. Real carrier provisioning remains gated.')}finally{setBusy(false)}}}>+ Create Holo Fon Profile</button></section>
   <section style={box}><h3>Quantum Email</h3>{emails.map(x=><div key={x.id} style={{padding:'9px 0',borderBottom:'1px solid #183041'}}><b>{x.handle}@{x.domain}</b><div style={{fontSize:10,color:'#8fa6b4'}}>{x.security_mode} • {x.status} • HoloGPT assist {x.hologpt_assist?'on':'off'}</div></div>)}<input aria-label="Quantum Email handle" value={handle} onChange={e=>setHandle(e.target.value)} placeholder="yourname" style={{width:'100%',boxSizing:'border-box',marginTop:10,padding:9,borderRadius:8,border:'1px solid #294a58',background:'#04101a',color:'#fff'}}/><button style={{...btn,marginTop:8}} disabled={busy||!handle.trim()} onClick={async()=>{setBusy(true);try{await reserveQuantumEmail(handle);setHandle('');await load();setMessage('Quantum Email identity reserved. Mail transport remains gated until a verified provider is connected.')}finally{setBusy(false)}}}>Reserve @tryamm.online Identity</button></section>
   <section style={box}><h3>Dealer + jobs network</h3><select value={market} onChange={e=>setMarket(e.target.value)} style={{width:'100%',padding:9,borderRadius:8,background:'#04101a',color:'#fff',border:'1px solid #294a58'}}>{markets.map(m=><option key={m.market_code} value={m.market_code}>{m.market_name}</option>)}</select><select value={role} onChange={e=>setRole(e.target.value)} style={{width:'100%',marginTop:8,padding:9,borderRadius:8,background:'#04101a',color:'#fff',border:'1px solid #294a58'}}>{['dealer','installer','support','repair','enterprise-sales','accessibility-specialist'].map(r=><option key={r}>{r}</option>)}</select><button style={{...btn,marginTop:8}} onClick={async()=>{setBusy(true);try{await applyConnectivityRole(market,role);setMessage('Interest submitted. Approval and work availability depend on market/provider readiness.')}finally{setBusy(false)}}}>Apply for Connectivity Role</button></section>
  </div>
  <h3 style={{marginTop:18}}>Provider readiness</h3><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(260px,1fr))',gap:10}}>{providers.map(p=><div key={p.provider_key} style={box}><div style={{display:'flex',justifyContent:'space-between',gap:8}}><b>{p.name}</b><span style={{fontSize:9,color:p.integration_status==='connected'?'#78ffb4':'#e8b944'}}>{p.integration_status}</span></div><div style={{fontSize:10,color:'#8fa6b4',marginTop:6}}>{p.provider_type} • {p.service_regions.join(', ')}</div><div style={{fontSize:10,color:'#b4c4cf',marginTop:7}}>{p.capabilities.join(' • ')}</div></div>)}</div>
  <h3 style={{marginTop:18}}>Market readiness</h3><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(260px,1fr))',gap:10}}>{markets.map(m=><div key={m.market_code} style={box}><b>{m.market_name}</b><span style={{float:'right',fontSize:9,color:m.status==='live'?'#78ffb4':'#e8b944'}}>{m.status}</span><div style={{fontSize:10,color:'#8fa6b4',marginTop:7}}>Wi-Fi {m.wifi?'✓':'—'} • Voice {m.mobile_voice?'✓':'gated'} • Data {m.mobile_data?'✓':'gated'} • eSIM {m.esim?'✓':'gated'} • Satellite {m.satellite_ntn?'✓':'gated'}</div><div style={{fontSize:10,color:'#aebdc7',marginTop:7,lineHeight:1.5}}>{m.regulatory_notes}</div></div>)}</div>
 </div></div>
}
