import { useEffect, useMemo, useState } from 'react'

type Lane='grocery'|'beauty'|'business'
type Cost={wholesale:number;freight:number;pickPack:number;payment:number;spoilage:number;delivery:number;margin:number}
type Product={name:string;category:string;target:number;margin:string;source:string;note?:string}

const grocery:Product[]=[
{name:'Rice 5 lb',category:'Pantry',target:6.99,margin:'22–30%',source:'Verified grocery wholesaler'},
{name:'Dry beans 2 lb',category:'Pantry',target:3.99,margin:'25–35%',source:'Verified grocery wholesaler'},
{name:'Oats 42 oz',category:'Breakfast',target:5.99,margin:'25–35%',source:'Verified grocery wholesaler'},
{name:'Frozen vegetables 12–16 oz',category:'Frozen',target:2.49,margin:'25–35%',source:'Verified cold-chain supplier'},
{name:'Frozen fruit 16 oz',category:'Frozen',target:4.99,margin:'25–35%',source:'Verified cold-chain supplier'},
{name:'Whole-grain pasta',category:'Pantry',target:2.49,margin:'25–35%',source:'Verified grocery wholesaler'},
{name:'Low-sodium canned vegetables',category:'Pantry',target:1.49,margin:'25–35%',source:'Verified grocery wholesaler'},
{name:'Plant-based milk 64 oz',category:'Dairy alternative',target:4.49,margin:'25–35%',source:'Verified cold-chain supplier'},
{name:'Healthy cooking oil',category:'Pantry',target:8.99,margin:'20–30%',source:'Verified grocery wholesaler'},
{name:'Family healthy staple box',category:'Food supplies',target:39.99,margin:'18–25%',source:'Multi-supplier'},
{name:'Emergency pantry supply box',category:'Food supplies',target:59.99,margin:'15–24%',source:'Verified shelf-stable suppliers',note:'Shelf-stable food and household rotation guidance.'},
{name:'Local grass-fed beef box',category:'Local beef',target:99,margin:'18–30%',source:'Eatwild discovery / verified U.S. farm / inspected processor'},
{name:'Pasture-raised chicken box',category:'Local poultry',target:69,margin:'18–30%',source:'Eatwild discovery / verified U.S. farm / inspected processor'},
{name:'Local pork box',category:'Local pork',target:79,margin:'18–30%',source:'Eatwild discovery / verified U.S. farm / inspected processor'},
{name:'Local lamb or goat box',category:'Local meat',target:109,margin:'18–30%',source:'Eatwild discovery / verified U.S. farm / inspected processor'},
{name:'Pasture-raised eggs',category:'Eggs',target:6.99,margin:'20–35%',source:'Verified local farm / regional distributor'},
{name:'Local dairy bundle',category:'Dairy',target:24.99,margin:'18–30%',source:'Verified local dairy / regional distributor'},
{name:'CSA produce box',category:'Fresh produce',target:34.99,margin:'15–28%',source:'Verified U.S. farm / CSA / farmers market'},
{name:'Local honey + pantry bundle',category:'Local pantry',target:29.99,margin:'25–40%',source:'Verified U.S. producer / cooperative'},
{name:'Wild-caught fish selection',category:'Eat Wild Food',target:18.99,margin:'18–28%',source:'Licensed seafood supplier',note:'Commercially supplied, traceable and legally harvested products only.'},
{name:'Cultivated specialty mushrooms',category:'Eat Wild Food',target:8.99,margin:'22–32%',source:'Verified farm / licensed food seller',note:'No unknown wild mushroom identification or safety claims.'},
{name:'Seasonal berry preserve',category:'Eat Wild Food',target:9.99,margin:'25–35%',source:'Licensed food producer',note:'Commercially prepared product; source and ingredient records required.'}]
const beauty:Product[]=[
{name:'Synthetic everyday wig',category:'Wigs',target:29.99,margin:'40–55%',source:'Verified beauty wholesaler'},
{name:'Premium synthetic wig',category:'Wigs',target:49.99,margin:'40–55%',source:'Verified beauty wholesaler'},
{name:'Human-hair bundle',category:'Hair',target:69.99,margin:'35–50%',source:'Verified beauty wholesaler'},
{name:'3-bundle hair deal',category:'Hair bundle',target:179.99,margin:'30–45%',source:'Verified beauty wholesaler'},
{name:'Braiding hair pack',category:'Braiding',target:6.99,margin:'35–50%',source:'Verified beauty wholesaler'},
{name:'Closure / frontal',category:'Hair',target:79.99,margin:'35–50%',source:'Verified beauty wholesaler'},
{name:'Lash multipack',category:'Lashes',target:9.99,margin:'45–60%',source:'Verified beauty wholesaler'},
{name:'Lip / makeup item',category:'Makeup',target:7.99,margin:'40–55%',source:'Verified beauty wholesaler'},
{name:'Nail starter kit',category:'Nails',target:39.99,margin:'35–50%',source:'Verified beauty wholesaler'},
{name:'Salon / beauty starter box',category:'Business bundle',target:299,margin:'25–40%',source:'Multi-supplier'}]
const startup=[
{title:'Nail Tech Starter',price:'$299',detail:'Core nail tools, tips, gel/acrylic starter assortment, sanitation/storage basics and retail add-ons.'},
{title:'Beauty Seller Starter',price:'$499',detail:'Fast-moving beauty assortment, TRYAMM storefront setup and live-commerce routing.'},
{title:'Grocery Micro-Market',price:'$1,499+',detail:'Shelf-stable staples, food-supply catalog, storefront, pickup/delivery setup and warehouse routing. Inventory varies by verified quote.'},
{title:'YAHAVAH Food Seller',price:'Quote',detail:'Merchant storefront connected to LIVE/PK product pins, verified inventory, Holo Fridge replenishment and delivery.'},
{title:'Local Farm & Meat Market',price:'Quote-based',detail:'Verified local/regional sourcing for inspected meat/poultry, eggs, dairy, produce, honey and CSA bundles with cold-chain and origin gates.'}]
function initialRoute(){const p=window.location.pathname.replace(/\/$/,'');if(p==='/yahavah-grocery'||p==='/yahavah-food')return{open:true,lane:'grocery' as Lane,coupon:false,wild:false};if(p==='/eat-wild-food')return{open:true,lane:'grocery' as Lane,coupon:false,wild:true};if(p==='/beauty-supply'||p==='/all-american-beauty')return{open:true,lane:'beauty' as Lane,coupon:false,wild:false};if(p==='/supply-plug'||p==='/supply-plug-global')return{open:true,lane:'business' as Lane,coupon:false,wild:false};if(p==='/holo-coupon')return{open:true,lane:'grocery' as Lane,coupon:true,wild:false};return{open:false,lane:'grocery' as Lane,coupon:false,wild:false}}
export default function UnifiedCommerceHub(){
 const route=initialRoute();const[open,setOpen]=useState(route.open);const[lane,setLane]=useState<Lane>(route.lane);const[coupon,setCoupon]=useState(route.coupon);const[wildOnly,setWildOnly]=useState(route.wild);const[cost,setCost]=useState<Cost>({wholesale:40,freight:4,pickPack:3,payment:2,spoilage:1,delivery:6,margin:8})
 useEffect(()=>{const show=(target?:Lane)=>{if(target)setLane(target);setWildOnly(false);setOpen(true)};(window as any).__showYahavahGrocery=()=>show('grocery');(window as any).__showYahavahFood=()=>show('grocery');(window as any).__showEatWildFood=()=>{setLane('grocery');setWildOnly(true);setOpen(true)};(window as any).__showAllAmericanBeauty=()=>show('beauty');(window as any).__showSupplyPlug=()=>show('business');(window as any).__showHoloCoupon=()=>{setCoupon(true);setOpen(true)};return()=>{delete(window as any).__showYahavahGrocery;delete(window as any).__showYahavahFood;delete(window as any).__showEatWildFood;delete(window as any).__showAllAmericanBeauty;delete(window as any).__showSupplyPlug;delete(window as any).__showHoloCoupon}},[])
 const floor=useMemo(()=>Object.values(cost).reduce((a,b)=>a+Number(b||0),0),[cost]);const products=lane==='grocery'?(wildOnly?grocery.filter(p=>p.category==='Eat Wild Food'):grocery):beauty
 const close=()=>{setOpen(false);if(['/yahavah-grocery','/yahavah-food','/eat-wild-food','/beauty-supply','/all-american-beauty','/supply-plug','/supply-plug-global','/holo-coupon'].includes(window.location.pathname.replace(/\/$/,'')))window.location.href='/'}
 const openLive=()=>{(window as any).__showLive?.();window.dispatchEvent(new CustomEvent('tryamm:live-commerce-open',{detail:{source:'yahavah-food',mode:'live-pk-storefront'}}))}
 if(!open)return null
 return <div role="dialog" aria-modal="true" aria-label="TRYAMM Living Commerce" style={{position:'fixed',inset:0,zIndex:23050,background:'rgba(2,4,10,.97)',color:'#fff',overflow:'auto'}}><div style={{maxWidth:1180,margin:'0 auto',padding:18}}>
 <header style={{display:'flex',justifyContent:'space-between',gap:12,alignItems:'center'}}><div><div style={{color:'#4FE3FF',fontSize:10,fontWeight:900,letterSpacing:3}}>TRYAMM LIVING COMMERCE · YAHAVAH FOOD · SUPPLY PLUG GLOBAL</div><h1 style={{margin:'5px 0'}}>YAHAVAH Grocery • Eat Wild Food • All American Beauty</h1><div style={{color:'#9fb3c6',fontSize:11}}>Target prices are launch guardrails. Sellable inventory requires verified source, landed cost, applicable food controls and server-authoritative inventory/payment state.</div></div><button onClick={close} style={btn}>Close</button></header>
 <div style={{display:'flex',gap:8,flexWrap:'wrap',margin:'14px 0'}}><button onClick={()=>{setLane('grocery');setWildOnly(false)}} style={btn}>YAHAVAH Food</button><button onClick={()=>{setLane('grocery');setWildOnly(true)}} style={btn}>Eat Wild Food</button><button onClick={()=>{setLane('beauty');setWildOnly(false)}} style={btn}>Beauty Supply</button><button onClick={()=>{setLane('business');setWildOnly(false)}} style={btn}>Start Your Business</button><button onClick={openLive} style={btn}>Open LIVE / PK storefront</button><button onClick={()=>setCoupon(v=>!v)} style={btn}>✦ Holo Coupon</button><a href="/stores" style={{...btn,textDecoration:'none',display:'inline-flex',alignItems:'center'}}>Store Network</a></div>
 {coupon&&<section style={panel}><h2>Holo Coupon Wallet</h2><p>Coupons never bypass the safe floor; discounts require an attributable funding source.</p></section>}
 {lane!=='business'?<><section style={panel}><h2>{wildOnly?'Eat Wild Food · verified-source catalog':lane==='grocery'?'YAHAVAH Food + local American farm catalog':'Beauty launch catalog'}</h2>{lane==='grocery'&&<p style={{color:'#b9d9c4'}}>Eatwild is used as a discovery lane. Actual products remain held until supplier identity, origin, applicable inspection/processing, labeling, inventory and cold-chain evidence are verified.</p>}<div style={{overflowX:'auto'}}><table style={{width:'100%',borderCollapse:'collapse',fontSize:12}}><thead><tr>{['Product','Category','Target retail','Margin','Supplier lane','Safety/source note'].map(x=><th key={x} style={th}>{x}</th>)}</tr></thead><tbody>{products.map(p=><tr key={p.name}><td style={td}><b>{p.name}</b></td><td style={td}>{p.category}</td><td style={td}>${p.target.toFixed(2)}</td><td style={td}>{p.margin}</td><td style={td}>{p.source}</td><td style={td}>{p.note||'Verified supplier controls apply.'}</td></tr>)}</tbody></table></div></section><section style={panel}><h2>Dynamic floor-price engine</h2><p>WHOLESALE + FREIGHT + PICK/PACK + PAYMENT FEE + SPOILAGE + DELIVERY + REQUIRED MARGIN = FLOOR PRICE.</p><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(150px,1fr))',gap:8}}>{Object.entries(cost).map(([k,v])=><label key={k} style={card}>{k}<input type="number" value={v} onChange={e=>setCost(c=>({...c,[k]:Number(e.target.value)||0}))} style={input}/></label>)}</div><div style={{marginTop:12,fontSize:22,fontWeight:950,color:'#E8B944'}}>SAFE FLOOR: ${floor.toFixed(2)}</div></section></>:<section style={panel}><h2>Supply Plug Global · Business-in-a-Box</h2><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(230px,1fr))',gap:8}}>{startup.map(x=><div key={x.title} style={card}><h3>{x.title}</h3><b>{x.price}</b><p>{x.detail}</p></div>)}</div></section>}
 <section style={panel}><b>YAHAVAH FOOD LOOP</b><div style={{marginTop:8,color:'#9fb3c6'}}>VERIFIED FARM / SUPPLIER → PRODUCT PASSPORT → LANDED COST → VIRTUAL WAREHOUSE → YAHAVAH / EAT WILD STOREFRONT → LIVE/PK PRODUCT PIN → SERVER-AUTHORIZED ORDER → PICK/PACK + COLD CHAIN → HOLO DELIVERY/PICKUP → PROOF → AUTHORITATIVE INVENTORY DECREMENT → HOLO FRIDGE → REORDER. Storehouse allocations remain separately accounted from seller revenue.</div></section>
 </div></div>
}
const panel:React.CSSProperties={marginTop:12,padding:16,border:'1px solid #20374a',borderRadius:18,background:'#07111c'};const card:React.CSSProperties={padding:12,border:'1px solid #26394a',borderRadius:12,background:'#0a1521',fontSize:12};const btn:React.CSSProperties={border:'1px solid #4FE3FF77',borderRadius:10,padding:'10px 13px',background:'#0b1a27',color:'#fff',fontWeight:900,cursor:'pointer',minHeight:44};const input:React.CSSProperties={display:'block',width:'100%',boxSizing:'border-box',marginTop:7,padding:8,borderRadius:8,border:'1px solid #345',background:'#030914',color:'#fff',minHeight:44};const th:React.CSSProperties={textAlign:'left',padding:10,borderBottom:'1px solid #345',color:'#4FE3FF'};const td:React.CSSProperties={padding:10,borderBottom:'1px solid #172938',verticalAlign:'top'}