import {useEffect,useMemo,useState} from 'react'

type Rail={id:string;name:string;region:string;stock:number;unit:number;freight:number;pick:number;fees:number;returns:number;delivery:number;days:number;verified:boolean}
const rails:Rail[]=[
{id:'local',name:'Local / Mom & Pop Supplier',region:'Local',stock:42,unit:12,freight:1.2,pick:2,fees:1.1,returns:.6,delivery:4,days:1,verified:true},
{id:'direct',name:'Supplier Direct',region:'National',stock:240,unit:10.8,freight:2.2,pick:1.2,fees:1.1,returns:.6,delivery:5.5,days:3,verified:true},
{id:'mcf',name:'Amazon MCF / 3PL Rail',region:'National',stock:100,unit:11.2,freight:0,pick:5.4,fees:1.1,returns:.8,delivery:0,days:2,verified:true},
{id:'global',name:'Global Approved Supplier',region:'International',stock:600,unit:8.9,freight:3.4,pick:1.1,fees:1.1,returns:.8,delivery:5.5,days:7,verified:false},
]
const card:React.CSSProperties={padding:14,border:'1px solid #294055',borderRadius:16,background:'#08121c'}
const btn:React.CSSProperties={border:'1px solid #4fe3ff77',borderRadius:11,padding:'10px 13px',background:'#0b1a27',color:'#fff',fontWeight:900,cursor:'pointer'}
export default function VirtualWarehouseNetwork(){
 const[open,setOpen]=useState(false);const[qty,setQty]=useState(1);const[margin,setMargin]=useState(5)
 useEffect(()=>{(window as any).__showVirtualWarehouse=()=>setOpen(true);return()=>{delete (window as any).__showVirtualWarehouse}},[])
 const ranked=useMemo(()=>rails.map(r=>({...r,landed:r.unit+r.freight+r.pick+r.fees+r.returns+r.delivery,floor:r.unit+r.freight+r.pick+r.fees+r.returns+r.delivery+margin})).filter(r=>r.stock>=qty&&r.verified).sort((a,b)=>a.landed-b.landed),[qty,margin])
 if(!open)return null
 return <div role="dialog" aria-modal="true" aria-label="TRYAMM Virtual Warehouse" style={{position:'fixed',inset:0,zIndex:13300,background:'rgba(1,3,9,.97)',color:'#fff',overflow:'auto'}}><div style={{maxWidth:1100,margin:'0 auto',padding:18}}><header style={{display:'flex',justifyContent:'space-between',gap:12}}><div><div style={{color:'#4fe3ff',fontSize:10,fontWeight:950,letterSpacing:3}}>NO SINGLE WAREHOUSE REQUIRED</div><h1 style={{margin:'4px 0'}}>TRYAMM Global Virtual Warehouse</h1><p style={{color:'#aebdca',maxWidth:760}}>One searchable inventory graph across verified wholesalers, mom-and-pop stores, bodegas, farms, beauty distributors, supplier-direct catalogs and approved 3PL/fulfillment rails. TRYAMM owns the orchestration and customer experience; inventory may remain with the supplier until ordered.</p></div><button onClick={()=>setOpen(false)} style={btn}>Close</button></header><section style={{...card,marginTop:14}}><h2>Smart fulfillment quote</h2><div style={{display:'flex',gap:12,flexWrap:'wrap'}}><label>Quantity <input type="number" min="1" value={qty} onChange={e=>setQty(Math.max(1,Number(e.target.value)||1))}/></label><label>Required profit / unit $ <input type="number" min="0" value={margin} onChange={e=>setMargin(Math.max(0,Number(e.target.value)||0))}/></label></div><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(220px,1fr))',gap:9,marginTop:12}}>{ranked.map((r,i)=><div key={r.id} style={{...card,background:'#0b1722'}}><b>{i===0?'BEST VERIFIED RAIL — ':''}{r.name}</b><div>{r.region} • {r.days} day estimate</div><div>Available: {r.stock}</div><div>Landed: ${r.landed.toFixed(2)} / unit</div><div style={{color:'#e8b944',fontWeight:900}}>Floor: ${r.floor.toFixed(2)} / unit</div></div>)}</div></section><section style={{...card,marginTop:12}}><h2>Virtual warehouse contract</h2><p style={{color:'#aebdca',lineHeight:1.6}}>SUPPLIER ID → VERIFIED SKU/GTIN → AUTHENTICITY/COMPLIANCE → REGION → AVAILABLE-TO-PROMISE STOCK → WHOLESALE COST → MOQ → LEAD TIME → MAP/POLICY → FULFILLMENT CAPABILITY → RETURN TERMS → INVENTORY TIMESTAMP. Never advertise inventory as available when the supplier feed is stale or unverified.</p></section><section style={{...card,marginTop:12}}><h2>World commerce</h2><p style={{color:'#aebdca',lineHeight:1.6}}>StreetVerse / My World / Middleverse / Metaverse / Multiverse / Kingdom → product discovery → Virtual Warehouse availability → Holo Coupon → cart → Guardian authorization → payment → cheapest compliant fulfillment rail → delivery proof → wallet/XP/loyalty → Reel/Live commerce → next customer.</p></section></div></div>
}