export type SignLanguageCode = 'asl' | 'bsl' | 'lsf' | 'dgs' | 'auslan' | 'isl' | 'jls'
export type SignOutputMode = 'gloss' | 'fingerspell' | 'avatar'
export interface SignCapabilities { version:string; providerConfigured:boolean; supportedSignLanguages:SignLanguageCode[]; modes:SignOutputMode[]; features:{textToSign:boolean;speechToSign:boolean;signToText:boolean;signToSpeech:boolean;liveCaptions:boolean;offlineFingerspelling:boolean;avatarReady:boolean} }
export interface SignTranslation { input:string; signLanguage:SignLanguageCode; mode:SignOutputMode; gloss:string[]; fingerspelling?:string[][]; avatarSequence?:Array<{token:string;clip?:string;durationMs?:number}>; provider:'configured'|'local-fallback'; warnings?:string[] }
const env=(import.meta as any).env||{}
const API_BASE=(env.VITE_SIGN_API_URL||env.VITE_API_URL||'').replace(/\/$/,'')
async function api<T>(path:string,init?:RequestInit):Promise<T>{const res=await fetch(`${API_BASE}${path}`,{...init,headers:{'Content-Type':'application/json',...(init?.headers||{})}});const body=await res.json().catch(()=>({}));if(!res.ok)throw new Error(body.error||body.message||`Request failed (${res.status})`);return body as T}
export const signLanguageApi={capabilities:()=>api<SignCapabilities>('/api/accessibility/sign/capabilities'),translate:(payload:{text:string;signLanguage?:SignLanguageCode;mode?:SignOutputMode})=>api<SignTranslation>('/api/accessibility/sign/translate',{method:'POST',body:JSON.stringify(payload)}),recognize:(payload:{signLanguage?:SignLanguageCode;landmarks?:unknown[];videoUrl?:string})=>api<{text:string;confidence:number;provider:string}>('/api/accessibility/sign/recognize',{method:'POST',body:JSON.stringify(payload)})}
export function canUseSpeechRecognition(){return typeof window!=='undefined'&&Boolean((window as any).SpeechRecognition||(window as any).webkitSpeechRecognition)}
export function startSpeechRecognition(onText:(text:string)=>void,onEnd:()=>void,onError:(message:string)=>void){const Recognition=(window as any).SpeechRecognition||(window as any).webkitSpeechRecognition;if(!Recognition)throw new Error('Speech recognition is not available in this browser.');const recognition=new Recognition();recognition.continuous=true;recognition.interimResults=true;recognition.lang='en-US';recognition.onresult=(event:any)=>{let text='';for(let i=event.resultIndex;i<event.results.length;i+=1)text+=event.results[i][0].transcript;onText(text.trim())};recognition.onerror=(event:any)=>onError(event.error||'Speech recognition failed');recognition.onend=onEnd;recognition.start();return()=>recognition.stop()}
