insert into university_programs(code,name,level,school,description,credential_type,accreditation_status,regulatory_notes,active,metadata)
values('ATC-PREP','ATC Career Preparation & Simulation','certificate','School of Aviation & Transportation','Career preparation, communication discipline and simulation for air-traffic-control concepts.','career-preparation-certificate','not_accredited','Educational preparation only. Does not confer FAA certification, academy admission, employment eligibility, medical qualification, or controller authority.',true,'{"simulation_only":true,"official_path_required":true}'::jsonb)
on conflict(code) do update set name=excluded.name,description=excluded.description,regulatory_notes=excluded.regulatory_notes,active=true,metadata=excluded.metadata;

insert into university_courses(code,title,description,school,level,credit_hours,delivery_modes,syllabus,active) values
('ATC-101','Airspace Foundations','Airport layout, airspace, runway/taxiway concepts, weather basics, phraseology and human factors.','School of Aviation & Transportation','career-prep',0,array['online','immersive','simulation'],'{"sim":"single-airport ground/tower orientation","ai_instructor":"AAU ATC AI Instructor"}'::jsonb,true),
('ATC-201','Tower Operations','Ground/local-control concepts, arrivals/departures, readback discipline, priority handling and supervised scenarios.','School of Aviation & Transportation','career-prep',0,array['online','immersive','simulation'],'{"sim":"multi-aircraft tower traffic","simulation_only":true}'::jsonb,true),
('ATC-301','Approach & Departure','Radar picture, sequencing, vector concepts, altitude/speed planning and handoffs.','School of Aviation & Transportation','career-prep',0,array['online','immersive','simulation'],'{"sim":"terminal-area sequencing","simulation_only":true}'::jsonb,true),
('ATC-401','High-Density Scenario Lab','Weather disruptions, equipment outages, priority handling, team coordination and debrief.','School of Aviation & Transportation','career-prep',0,array['immersive','simulation'],'{"sim":"complex supervised scenario lab","simulation_only":true}'::jsonb,true)
on conflict(code) do update set title=excluded.title,description=excluded.description,delivery_modes=excluded.delivery_modes,syllabus=excluded.syllabus,active=true;
