-- All American University starter runtime catalog.
-- These are TRYAMM learning/practicum experiences, not accredited-credit promises.

insert into public.university_courses(code,title,description,school,level,credit_hours,prerequisites,minimum_age_lane,delivery_modes,syllabus,active)
values
('AAU-AI-101','AI & Intelligent Systems Foundations','Build practical AI literacy, model evaluation habits, prompt/tool safety and evidence-based project skills.','School of AI, Computing & Robotics','intro',0,'{}','teen-adult',array['online','immersive'],jsonb_build_object('modules',array['AI literacy','data and evidence','model limits','tool safety','original project'],'credential_truth','non-accredited TRYAMM learning experience'),true),
('AAU-CYBER-101','Jacobie Vision Cybersecurity Foundations','Learn zero trust, passkeys/MFA, device trust, phishing defense, account takeover prevention, incident reporting and ethical cybersecurity practice.','School of AI, Computing & Robotics','intro',0,'{}','teen-adult',array['online','lab','immersive'],jsonb_build_object('modules',array['zero trust','identity security','device trust','fraud signals','incident response'],'brand','Jacobie Vision Cybersecurity','credential_truth','non-accredited TRYAMM learning experience'),true),
('AAU-GAME-101','GameVerse Living Worlds Studio','Design playable missions, stateful choices, World Memory, NPC behavior, accessibility, multiplayer loops and release-proof contracts.','School of AI, Computing & Robotics','project',0,'{}','teen-adult',array['online','gameverse','immersive'],jsonb_build_object('modules',array['mission design','world state','multiplayer','accessibility','testing'],'bridge','GameVerse/StreetVerse'),true),
('AAU-IMM-101','Immersive Museum & XR Experience Design','Turn evidence, archives and original creative work into rights-safe interactive exhibits, AR/VR/MR scenes and educational missions.','School of Professional Studies','project',0,'{}','teen-adult',array['online','immersive','xr'],jsonb_build_object('modules',array['evidence classes','spatial storytelling','XR interaction','rights/provenance','visitor accessibility'],'bridge','Immersive Library'),true),
('AAU-CREATOR-101','Creator Media, Reels & Movie Studio','Plan, shoot, edit, publish and evaluate original short-form video, LIVE replays and movie scenes with rights and provenance controls.','School of Professional Studies','certificate-prep',0,'{}','teen-adult',array['online','studio','gameverse'],jsonb_build_object('modules',array['storyboard','camera language','audio','editing','publishing','rights']),true),
('AAU-BIZ-101','Creator Entrepreneurship & Marketplace','Build a lawful creator or small-business model using storefronts, customer service, pricing, promotion, records and evidence-backed revenue tracking.','School of Professional Studies','intro',0,'{}','teen-adult',array['online','marketplace'],jsonb_build_object('modules',array['business model','pricing','storefront','customer acquisition','ledger basics','compliance truth']),true),
('AAU-MOBILE-101','Wireless, MVNO & Connectivity Foundations','Understand mobile networks, Wi-Fi, 5G, MVNO wholesale models, eSIM, NTN/satellite concepts, network telemetry and provider/compliance gates.','School of Trades & Workforce','technical',0,'{}','adult',array['online','lab'],jsonb_build_object('modules',array['radio/network basics','MVNO model','eSIM','Wi-Fi/5G','NTN','telecom compliance'],'brand','TRYAMM Mobile / All American Mobile'),true),
('AAU-ACCESS-101','Accessible Product & Game Design','Design interfaces, games, education and creator tools for keyboard, voice, captions, screen readers, mobility differences and cognitive accessibility.','School of Professional Studies','intro',0,'{}','teen-adult',array['online','lab','immersive'],jsonb_build_object('modules',array['inclusive UX','keyboard','captions','screen readers','voice control','testing with evidence']),true),
('AAU-ARCHIVE-101','Archive Research, Evidence & World Memory','Research primary sources, distinguish fact from interpretation and family memory, preserve provenance, and transform verified history into original learning experiences.','All American Academy','project',0,'{}','middle-adult',array['online','library','immersive'],jsonb_build_object('modules',array['primary sources','fact vs interpretation','family memory','provenance','mission creation'],'bridge','Immersive Library / World Memory'),true),
('AAU-K12-DISC-101','Discovery Lab: Build Your World','Age-appropriate project learning through science, art, storytelling, digital citizenship and guided world-building.','All American Academy','k12',0,'{}','youth',array['online','guided','immersive'],jsonb_build_object('modules',array['discovery','making','storytelling','digital citizenship','team project'],'guardian_managed',true),true),
('AAU-TRADE-DIG-101','Digital Operations & Technical Support','Practice customer support, device setup, troubleshooting, ticket documentation, safety escalation and workplace communication.','School of Trades & Workforce','trade',0,'{}','teen-adult',array['online','lab','work-simulation'],jsonb_build_object('modules',array['support workflow','device setup','troubleshooting','documentation','escalation','workplace communication']),true),
('AAU-FINLIT-101','Financial Literacy for Creators & Families','Learn budgeting, cash-flow basics, taxes/records awareness, fraud avoidance, savings goals and the difference between virtual rewards and real payable earnings.','School of Professional Studies','intro',0,'{}','teen-adult',array['online','family'],jsonb_build_object('modules',array['budgeting','cash flow','records','fraud avoidance','savings','virtual vs payable value']),true)
on conflict (code) do update set
 title=excluded.title, description=excluded.description, school=excluded.school, level=excluded.level,
 delivery_modes=excluded.delivery_modes, syllabus=excluded.syllabus, active=true;

insert into public.university_opportunities(title,opportunity_type,description,requirements,active)
select v.title,v.kind,v.description,v.requirements,true
from (values
 ('TRYAMM Creator Studio Practicum','practicum','Create an original rights-safe reel or short movie, document the production process, and publish it to an approved TRYAMM portfolio.',jsonb_build_object('internal',true,'paid',false,'note','Learning practicum; not an employment offer')),
 ('GameVerse Mission Design Lab','practicum','Build and test a small mission with objectives, choice consequences, accessibility checks and a replayable proof path.',jsonb_build_object('internal',true,'paid',false,'note','Learning practicum; not an employment offer')),
 ('Immersive Library Research Fellowship Simulation','research-practicum','Research a source, classify evidence, build an original immersive interpretation, and preserve citations/provenance.',jsonb_build_object('internal',true,'paid',false,'note','Simulated/internal research experience; not an external fellowship award')),
 ('Jacobie Vision Security Lab','security-practicum','Complete defensive account-security, phishing-awareness, device-trust and incident-response exercises in a controlled learning environment.',jsonb_build_object('internal',true,'paid',false,'defensive_only',true,'note','Training lab; not employment or professional certification')),
 ('All American Marketplace Business Builder','entrepreneurship-practicum','Create a mock storefront, pricing plan, customer journey, support policy and evidence-backed unit-economics worksheet.',jsonb_build_object('internal',true,'paid',false,'note','Learning practicum; no guaranteed business income')),
 ('TRYAMM Mobile Dealer Readiness Simulation','workforce-practicum','Practice plan explanation, device compatibility, eSIM onboarding, privacy and escalation workflows without activating real carrier service.',jsonb_build_object('internal',true,'paid',false,'provider_gate',true,'note','Simulation only until an approved carrier/dealer relationship exists')),
 ('Accessibility QA Crew','quality-practicum','Test a TRYAMM experience with keyboard, captions, reduced-motion, screen-reader and mobility-accessibility checks and submit evidence.',jsonb_build_object('internal',true,'paid',false,'note','Learning/QA practicum; not an employment offer')),
 ('Family & Youth Digital Citizenship Project','guided-project','Create a guardian-aware family media or learning project covering privacy, respectful participation, scams and healthy platform use.',jsonb_build_object('internal',true,'paid',false,'guardian_managed',true))
) as v(title,kind,description,requirements)
where not exists (select 1 from public.university_opportunities u where u.title=v.title);
