create table if not exists public.omni_passports(
 id uuid primary key default gen_random_uuid(),owner_user_id uuid not null,asset_type text not null,category text not null,title text not null,brand text,model text,serial_or_identifier text,verification_level text not null default 'identity',verification_status text not null default 'pending',risk_score numeric,evidence_refs jsonb not null default '[]'::jsonb,condition_report jsonb not null default '{}'::jsonb,metadata jsonb not null default '{}'::jsonb,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.omniride_vehicles(
 id uuid primary key default gen_random_uuid(),owner_user_id uuid not null,omni_passport_id uuid references public.omni_passports(id),vin text unique,plate_region text,year int,make text,model text,vehicle_class text,verification_status text not null default 'pending',safety_status text not null default 'pending',mileage bigint,listing_status text not null default 'draft',created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.omniride_driver_eligibility(
 user_id uuid primary key,status text not null default 'pending',license_region text,license_class text,approved_vehicle_classes text[] not null default '{}',provider_ref text,reviewed_at timestamptz,expires_at timestamptz,metadata jsonb not null default '{}'::jsonb);
create table if not exists public.omniride_coverage_eligibility(
 id uuid primary key default gen_random_uuid(),vehicle_id uuid not null references public.omniride_vehicles(id) on delete cascade,region text not null,status text not null default 'pending',liability_ref text,physical_damage_ref text,coverage_ref text,starts_at timestamptz,expires_at timestamptz,metadata jsonb not null default '{}'::jsonb,unique(vehicle_id,region,coverage_ref));
create table if not exists public.omniride_jurisdiction_rules(
 id uuid primary key default gen_random_uuid(),region text not null,version text not null,booking_allowed boolean not null default false,requirements jsonb not null default '{}'::jsonb,source_refs jsonb not null default '[]'::jsonb,effective_at timestamptz not null,expires_at timestamptz,active boolean not null default false,reviewed_by text,unique(region,version));
create table if not exists public.omniride_airport_rules(
 id uuid primary key default gen_random_uuid(),airport_code text not null,region text,pickup_allowed boolean not null default false,dropoff_allowed boolean not null default false,fee_rules jsonb not null default '{}'::jsonb,requirements jsonb not null default '{}'::jsonb,source_refs jsonb not null default '[]'::jsonb,effective_at timestamptz not null,expires_at timestamptz,active boolean not null default false,unique(airport_code,effective_at));
create table if not exists public.omniride_booking_gate_events(
 id uuid primary key default gen_random_uuid(),vehicle_id uuid not null,driver_user_id uuid not null,start_region text not null,airport_code text,allowed boolean not null,decision_code text not null,failed_checks text[] not null default '{}',created_at timestamptz not null default now());
create table if not exists public.omniride_inspections(
 id uuid primary key default gen_random_uuid(),vehicle_id uuid not null references public.omniride_vehicles(id) on delete cascade,trip_id uuid,inspection_type text not null check(inspection_type in('onboarding','pre_trip','post_trip','claim')),media_refs jsonb not null default '[]'::jsonb,odometer bigint,fuel_or_charge numeric,observations jsonb not null default '{}'::jsonb,ai_findings jsonb not null default '{}'::jsonb,human_review_status text not null default 'not_required',created_at timestamptz not null default now());
create table if not exists public.omniride_claims(
 id uuid primary key default gen_random_uuid(),vehicle_id uuid not null references public.omniride_vehicles(id),trip_id uuid,opened_by_user_id uuid not null,incident_type text not null,status text not null default 'open',evidence_refs jsonb not null default '[]'::jsonb,pre_inspection_id uuid references public.omniride_inspections(id),post_inspection_id uuid references public.omniride_inspections(id),coverage_ref text,adjuster_ref text,resolution jsonb,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create index if not exists omni_passports_owner_idx on public.omni_passports(owner_user_id,created_at desc);
create index if not exists omniride_vehicle_owner_idx on public.omniride_vehicles(owner_user_id,created_at desc);
create index if not exists omniride_gate_created_idx on public.omniride_booking_gate_events(created_at desc);
