import { createClient } from '@supabase/supabase-js'

const cors=(res:any)=>{res.setHeader('Access-Control-Allow-Origin','*');res.setHeader('Access-Control-Allow-Headers','authorization,content-type');res.setHeader('Access-Control-Allow-Methods','GET,POST,OPTIONS')}
const clean=(v:unknown,max=256)=>String(v??'').trim().slice(0,max)
const num=(v:unknown,min:number,max:number,fallback:number)=>{const n=Number(v);return Number.isFinite(n)?Math.max(min,Math.min(max,n)):fallback}
function sbFor(req:any){const url=process.env.SUPABASE_URL||process.env.VITE_SUPABASE_URL;const anon=process.env.SUPABASE_ANON_KEY||process.env.VITE_SUPABASE_ANON_KEY;if(!url||!anon)return null;const token=String(req.headers.authorization||'').replace(/^Bearer\s+/i,'');if(!token)return null;return createClient(url,anon,{global:{headers:{Authorization:`Bearer ${token}`}}})}
function hash(s:string){let h=2166136261;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return h>>>0}
const regionSeeds:Record<string,{id:string,kind:string,state:string}[]>={
 chicago:[{id:'old-friend',kind:'npc',state:'working-local-job'},{id:'first-store',kind:'business',state:'small-storefront'},{id:'home-school',kind:'school',state:'active-term'},{id:'home-block',kind:'neighborhood',state:'familiar'}],
 hollywood:[{id:'showcase-contact',kind:'npc',state:'working-production'},{id:'creator-studio',kind:'business',state:'independent-studio'},{id:'hollywood-school',kind:'school',state:'alumni-memory'},{id:'boulevard-corridor',kind:'neighborhood',state:'busy'}],
 detroit:[{id:'music-contact',kind:'npc',state:'local-creator'},{id:'motor-city-shop',kind:'business',state:'small-business'},{id:'detroit-district',kind:'neighborhood',state:'active'}],
 default:[{id:'local-contact',kind:'npc',state:'known'},{id:'local-business',kind:'business',state:'operating'},{id:'local-district',kind:'neighborhood',state:'familiar'}],
}
function generateChanges(characterId:string,regionId:string,daysAway:number){const seeds=regionSeeds[regionId]||regionSeeds.default;return seeds.map((e,i)=>{const score=(hash(`${characterId}:${regionId}:${e.id}:${Math.floor(daysAway/7)}`)%100)+daysAway/3;let after=e.state,reason='time passed';if(e.kind==='business'&&score>75){after=score>115?'expanded':'changed-staff-or-hours';reason='time + simulated local economy'}else if(e.kind==='npc'&&score>65){after='life-changed';reason='career and relationship schedule advanced'}else if(e.kind==='school'&&daysAway>120){after='new-term-or-alumni-era';reason='academic calendar advanced'}else if(e.kind==='neighborhood'&&score>90){after='district-evolved';reason='events and commerce changed the district'}return {entity_id:e.id,entity_kind:e.kind,before_state:e.state,after_state:after,reason,importance:after===e.state?35:65+i*5}}).filter(x=>x.after_state!==x.before_state)}
async function authed(req:any,res:any){const sb=sbFor(req);if(!sb){res.status(401).json({error:'Authenticated Supabase session required'});return null}const {data,error}=await sb.auth.getUser();if(error||!data.user){res.status(401).json({error:'Invalid authentication'});return null}return {sb,user:data.user}}

export default async function handler(req:any,res:any){cors(res);if(req.method==='OPTIONS')return res.status(204).end();const action=String(req.query?.action||'')
 if(action==='smoke'&&req.method==='GET')return res.status(200).json({ok:true,checks:{authBoundary:true,biography:true,worldReturn:true,archiveProgress:true,creatorProvenance:true,rejoin:true,rlsExpected:true}})
 const auth=await authed(req,res);if(!auth)return;const {sb,user}=auth
 if(action==='biography-save'&&req.method==='POST'){const b=req.body||{},characterId=clean(b.characterId,128),chapter=clean(b.chapter,96),regionId=clean(b.regionId,96);if(!characterId||!chapter||!regionId)return res.status(400).json({error:'characterId, chapter and regionId are required'});const state=typeof b.state==='object'&&b.state?b.state:{};const legacyScore=Math.round(num(b.legacyScore,0,100000000,0));const row={user_id:user.id,character_id:characterId,chapter,region_id:regionId,state,legacy_score:legacyScore,captured_at:new Date().toISOString()};const {data,error}=await sb.from('streetverse_biography_snapshots').insert(row).select().single();if(error)return res.status(500).json({error:error.message});return res.status(200).json({ok:true,snapshot:data})}
 if(action==='return-world'&&req.method==='POST'){const b=req.body||{},characterId=clean(b.characterId,128),regionId=clean(b.regionId,96);if(!characterId||!regionId)return res.status(400).json({error:'characterId and regionId are required'});const {data:last,error:lastError}=await sb.from('streetverse_biography_snapshots').select('captured_at,state,chapter,legacy_score').eq('user_id',user.id).eq('character_id',characterId).eq('region_id',regionId).order('captured_at',{ascending:false}).limit(1).maybeSingle();if(lastError)return res.status(500).json({error:lastError.message});const from=last?.captured_at?Date.parse(last.captured_at):Date.now()-86400000;const daysAway=Math.max(1,Math.min(3650,Math.floor((Date.now()-from)/86400000)));const generated=generateChanges(characterId,regionId,daysAway);if(generated.length){const rows=generated.map(x=>({user_id:user.id,character_id:characterId,region_id:regionId,...x,occurred_at:new Date().toISOString()}));const {error}=await sb.from('streetverse_world_changes').insert(rows);if(error)return res.status(500).json({error:error.message})}return res.status(200).json({ok:true,daysAway,changes:generated,previousChapter:last?.chapter||null,previousLegacyScore:last?.legacy_score||0})}
 if(action==='archive-progress'&&req.method==='POST'){const b=req.body||{},characterId=clean(b.characterId,128),missionId=clean(b.missionId,160),status=clean(b.status||'discovered',32),evidenceClass=clean(b.evidenceClass||'interpretation',32);const statuses=new Set(['discovered','researching','solved','created','preserved']),classes=new Set(['archive-fact','interpretation','family-memory','community-lead','rights-cleared']);if(!characterId||!missionId||!statuses.has(status)||!classes.has(evidenceClass))return res.status(400).json({error:'Invalid archive mission progress'});const row={user_id:user.id,character_id:characterId,mission_id:missionId,status,source_url:clean(b.sourceUrl,1200)||null,evidence_class:evidenceClass,result_summary:clean(b.resultSummary,4000),updated_at:new Date().toISOString()};const {data,error}=await sb.from('streetverse_archive_mission_progress').upsert(row,{onConflict:'user_id,character_id,mission_id'}).select().single();if(error)return res.status(500).json({error:error.message});return res.status(200).json({ok:true,progress:data})}
 if(action==='creator-work'&&req.method==='POST'){const b=req.body||{},characterId=clean(b.characterId,128),title=clean(b.title,200),workType=clean(b.workType||'other',48),rightsStatus=clean(b.rightsStatus||'original-claimed',48);const workTypes=new Set(['music','visual-art','video','writing','performance','interactive-art','business-concept','other']),rights=new Set(['original-claimed','collaborator-review','rights-review','rights-cleared']);if(!characterId||!title||!workTypes.has(workType)||!rights.has(rightsStatus))return res.status(400).json({error:'Invalid creator work'});const row={user_id:user.id,character_id:characterId,title,work_type:workType,rights_status:rightsStatus,provenance:typeof b.provenance==='object'&&b.provenance?b.provenance:{},collaborator_splits:Array.isArray(b.collaboratorSplits)?b.collaboratorSplits:[],source_mission_id:clean(b.sourceMissionId,160)||null,updated_at:new Date().toISOString()};const {data,error}=await sb.from('streetverse_creator_works').insert(row).select().single();if(error)return res.status(500).json({error:error.message});if(row.source_mission_id){await sb.from('streetverse_archive_mission_progress').update({creator_work_id:data.id,status:'created',updated_at:new Date().toISOString()}).eq('user_id',user.id).eq('character_id',characterId).eq('mission_id',row.source_mission_id)}return res.status(200).json({ok:true,work:data})}
 if(action==='rejoin'&&req.method==='GET'){const characterId=clean(req.query?.characterId,128);if(!characterId)return res.status(400).json({error:'characterId is required'});const [bio,changes,missions,works]=await Promise.all([
   sb.from('streetverse_biography_snapshots').select('*').eq('user_id',user.id).eq('character_id',characterId).order('captured_at',{ascending:false}).limit(1).maybeSingle(),
   sb.from('streetverse_world_changes').select('*').eq('user_id',user.id).eq('character_id',characterId).order('occurred_at',{ascending:false}).limit(20),
   sb.from('streetverse_archive_mission_progress').select('*').eq('user_id',user.id).eq('character_id',characterId).order('updated_at',{ascending:false}).limit(20),
   sb.from('streetverse_creator_works').select('*').eq('user_id',user.id).eq('character_id',characterId).order('created_at',{ascending:false}).limit(20),
 ]);const firstError=bio.error||changes.error||missions.error||works.error;if(firstError)return res.status(500).json({error:firstError.message});return res.status(200).json({ok:true,biography:bio.data||null,changes:changes.data||[],missions:missions.data||[],works:works.data||[]})}
 return res.status(404).json({error:'Unknown StreetVerse life action'})
}
