export type MunicipalDepartment='sanitation'|'water'|'streets'|'transit'|'parks'|'buildings'|'public-health'|'fire-ems'|'311-services'|'fleet'|'environment'
export type MunicipalJob={id:string;department:MunicipalDepartment;title:string;lane:'npc'|'player'|'business';skills:string[];missionExamples:string[]}

export const MUNICIPAL_JOBS:MunicipalJob[]=[
{id:'waste-driver',department:'sanitation',title:'Waste Collection Driver',lane:'player',skills:['route','vehicle','safety'],missionExamples:['complete collection route','service missed pickup']},
{id:'recycling-tech',department:'sanitation',title:'Recycling & Recovery Technician',lane:'player',skills:['sorting','recovery'],missionExamples:['recover recyclables','clear overflow']},
{id:'sanitation-dispatch',department:'sanitation',title:'Sanitation Dispatcher',lane:'player',skills:['dispatch','routing'],missionExamples:['assign crews','reroute around closure']},
{id:'water-tech',department:'water',title:'Water Systems Technician',lane:'player',skills:['inspection','repair'],missionExamples:['investigate simulated leak','restore service']},
{id:'street-crew',department:'streets',title:'Street Maintenance Crew',lane:'player',skills:['repair','traffic-safety'],missionExamples:['repair road','clear snow or debris']},
{id:'transit-operator',department:'transit',title:'Transit Operator',lane:'player',skills:['driving','schedule'],missionExamples:['run route','assist riders']},
{id:'parks-worker',department:'parks',title:'Parks & Grounds Worker',lane:'player',skills:['landscape','maintenance'],missionExamples:['maintain park','plant trees']},
{id:'building-inspector',department:'buildings',title:'Building Inspector',lane:'player',skills:['inspection','code'],missionExamples:['inspect virtual commercial space','document repair needs']},
{id:'311-agent',department:'311-services',title:'City Service Agent',lane:'player',skills:['service','dispatch'],missionExamples:['triage service request','send correct department']},
{id:'fleet-mechanic',department:'fleet',title:'Municipal Fleet Mechanic',lane:'player',skills:['vehicle-repair','diagnostics'],missionExamples:['repair collection truck','service city fleet']},
]

export type WasteNode={id:string;kind:'residential'|'commercial'|'public';capacity:number;fill:number;recycling:number;compost:number}
export const CIRCLE_PARK_WASTE:WasteNode={id:'chi-circle-park-waste',kind:'residential',capacity:100,fill:0,recycling:0,compost:0}

export function municipalMissionPressure(node:WasteNode){
 const ratio=node.capacity?node.fill/node.capacity:0
 return ratio>=.9?'urgent':ratio>=.65?'service-due':'normal'
}

export const MUNICIPAL_SIMULATION_RULES=[
 'Waste is generated by simulated population and businesses, not real resident tracking.',
 'Collection routes affect cleanliness, traffic, jobs, missions and operating cost.',
 'Recycling and recovery reduce landfill load and can feed the simulated materials economy.',
 '311-style requests create dispatchable missions without representing TRYAMM as the City of Chicago.',
 'Player municipal roles are gameplay unless a real employer separately offers an actual job.',
 'Sensitive real-world infrastructure and emergency/security details are excluded.'
] as const
