export const STREETVERSE_RP_BENCHMARK = {
  status: 'experimental',
  sourcePolicy: 'public-patterns-only-no-third-party-assets',
  differentiation: [
    'persistent-resident-simulation',
    'role-state-gameplay',
    'server-authoritative-economy',
    'creator-native-capture',
    'player-operated-businesses',
    'mobility-delivery',
    'sports-events',
    'fictional-investigation-stories',
    'first-responder-training-simulations',
    'mobile-safe-accessibility-parity',
    'cross-district-event-fabric',
    'world-state-director',
    'verified-quality-gates',
  ],
  premiumDistrictGates: {
    collisionCertified: true,
    navigationCertified: true,
    noUnreachableMissionMarkers: true,
    noSpawnInsideGeometry: true,
    desktopE2E: true,
    mobileE2E: true,
    performanceBudgetRequired: true,
    accessibilityRequired: true,
    rollbackRequired: true,
  },
  hydeParkPilot: [
    'pedestrian-road-nav-graphs',
    'collision-traversal-certification',
    'resident-schedules',
    'interactive-interior-shells',
    'creator-business-civic-venues',
    'transit-activity-hooks',
    'world-director',
    'event-aware-crowd-traffic',
    'role-variant-mission-director',
    'reel-highlight-loop',
  ],
  communitySystems: [
    'proximity-conversation',
    'consent-aware-interactions',
    'emotes',
    'party-family-agency-groups',
    'player-run-businesses',
    'community-events',
    'reputation',
    'neighborhood-affinity',
    'creator-shows',
    'moderation-anti-griefing',
  ],
} as const
