export type WorldClass='un-member'|'un-observer'|'territory'|'associated-state'|'special-region'|'disputed-or-limited-recognition'|'research-region';
export type TravelMode='walk'|'bike'|'car'|'bus'|'metro'|'rail'|'high-speed-rail'|'plane'|'boat'|'ferry'|'river'|'holo-portal';
export interface LivingEarthEntry {id:string;name:string;continent:string;worldClass:WorldClass;parent?:string;travel:TravelMode[];systems:string[];status:'registry'|'hub-seeded'|'playable';}
const standardTravel:TravelMode[]=['walk','bike','car','bus','rail','plane','boat','holo-portal'];
const coreSystems=['copy-smart-npc','dynamic-secret-missions','teen-takeover','sports','creator-careers','businesses-properties','omni-player','holo-gpt','quantum-beat','multiplayer','cloud-save','accessibility','translation'];
const members=`Afghanistan|Albania|Algeria|Andorra|Angola|Antigua and Barbuda|Argentina|Armenia|Australia|Austria|Azerbaijan|Bahamas|Bahrain|Bangladesh|Barbados|Belarus|Belgium|Belize|Benin|Bhutan|Bolivia|Bosnia and Herzegovina|Botswana|Brazil|Brunei|Bulgaria|Burkina Faso|Burundi|Cabo Verde|Cambodia|Cameroon|Canada|Central African Republic|Chad|Chile|China|Colombia|Comoros|Republic of the Congo|Costa Rica|Cote d'Ivoire|Croatia|Cuba|Cyprus|Czechia|North Korea|Democratic Republic of the Congo|Denmark|Djibouti|Dominica|Dominican Republic|Ecuador|Egypt|El Salvador|Equatorial Guinea|Eritrea|Estonia|Eswatini|Ethiopia|Fiji|Finland|France|Gabon|Gambia|Georgia|Germany|Ghana|Greece|Grenada|Guatemala|Guinea|Guinea-Bissau|Guyana|Haiti|Honduras|Hungary|Iceland|India|Indonesia|Iran|Iraq|Ireland|Israel|Italy|Jamaica|Japan|Jordan|Kazakhstan|Kenya|Kiribati|Kuwait|Kyrgyzstan|Laos|Latvia|Lebanon|Lesotho|Liberia|Libya|Liechtenstein|Lithuania|Luxembourg|Madagascar|Malawi|Malaysia|Maldives|Mali|Malta|Marshall Islands|Mauritania|Mauritius|Mexico|Micronesia|Monaco|Mongolia|Montenegro|Morocco|Mozambique|Myanmar|Namibia|Nauru|Nepal|Netherlands|New Zealand|Nicaragua|Niger|Nigeria|North Macedonia|Norway|Oman|Pakistan|Palau|Panama|Papua New Guinea|Paraguay|Peru|Philippines|Poland|Portugal|Qatar|South Korea|Moldova|Romania|Russia|Rwanda|Saint Kitts and Nevis|Saint Lucia|Saint Vincent and the Grenadines|Samoa|San Marino|Sao Tome and Principe|Saudi Arabia|Senegal|Serbia|Seychelles|Sierra Leone|Singapore|Slovakia|Slovenia|Solomon Islands|Somalia|South Africa|South Sudan|Spain|Sri Lanka|Sudan|Suriname|Sweden|Switzerland|Syria|Tajikistan|Thailand|Timor-Leste|Togo|Tonga|Trinidad and Tobago|Tunisia|Türkiye|Turkmenistan|Tuvalu|Uganda|Ukraine|United Arab Emirates|United Kingdom|Tanzania|United States|Uruguay|Uzbekistan|Vanuatu|Venezuela|Vietnam|Yemen|Zambia|Zimbabwe`.split('|');
const continentByCountry:Record<string,string>={};
const groups:Record<string,string[]>= {
 Africa:`Algeria|Angola|Benin|Botswana|Burkina Faso|Burundi|Cabo Verde|Cameroon|Central African Republic|Chad|Comoros|Republic of the Congo|Cote d'Ivoire|Democratic Republic of the Congo|Djibouti|Egypt|Equatorial Guinea|Eritrea|Eswatini|Ethiopia|Gabon|Gambia|Ghana|Guinea|Guinea-Bissau|Kenya|Lesotho|Liberia|Libya|Madagascar|Malawi|Mali|Mauritania|Mauritius|Morocco|Mozambique|Namibia|Niger|Nigeria|Rwanda|Sao Tome and Principe|Senegal|Seychelles|Sierra Leone|Somalia|South Africa|South Sudan|Sudan|Tanzania|Togo|Tunisia|Uganda|Zambia|Zimbabwe`.split('|'),
 Asia:`Afghanistan|Armenia|Azerbaijan|Bahrain|Bangladesh|Bhutan|Brunei|Cambodia|China|Cyprus|Georgia|India|Indonesia|Iran|Iraq|Israel|Japan|Jordan|Kazakhstan|Kuwait|Kyrgyzstan|Laos|Lebanon|Malaysia|Maldives|Mongolia|Myanmar|Nepal|North Korea|Oman|Pakistan|Philippines|Qatar|Saudi Arabia|Singapore|South Korea|Sri Lanka|Syria|Tajikistan|Thailand|Timor-Leste|Türkiye|Turkmenistan|United Arab Emirates|Uzbekistan|Vietnam|Yemen`.split('|'),
 Europe:`Albania|Andorra|Austria|Belarus|Belgium|Bosnia and Herzegovina|Bulgaria|Croatia|Czechia|Denmark|Estonia|Finland|France|Germany|Greece|Hungary|Iceland|Ireland|Italy|Latvia|Liechtenstein|Lithuania|Luxembourg|Malta|Moldova|Monaco|Montenegro|Netherlands|North Macedonia|Norway|Poland|Portugal|Romania|Russia|San Marino|Serbia|Slovakia|Slovenia|Spain|Sweden|Switzerland|Ukraine|United Kingdom`.split('|'),
 'North America':`Antigua and Barbuda|Bahamas|Barbados|Belize|Canada|Costa Rica|Cuba|Dominica|Dominican Republic|El Salvador|Grenada|Guatemala|Haiti|Honduras|Jamaica|Mexico|Nicaragua|Panama|Saint Kitts and Nevis|Saint Lucia|Saint Vincent and the Grenadines|Trinidad and Tobago|United States`.split('|'),
 'South America':`Argentina|Bolivia|Brazil|Chile|Colombia|Ecuador|Guyana|Paraguay|Peru|Suriname|Uruguay|Venezuela`.split('|'),
 Oceania:`Australia|Fiji|Kiribati|Marshall Islands|Micronesia|Nauru|New Zealand|Palau|Papua New Guinea|Samoa|Solomon Islands|Tonga|Tuvalu|Vanuatu`.split('|')
};
for(const [continent,names] of Object.entries(groups)) for(const name of names) if(!continentByCountry[name]) continentByCountry[name]=continent;
export const UN_MEMBER_WORLDS:LivingEarthEntry[]=members.map(name=>({id:`country-${name.toLowerCase().replace(/[^a-z0-9]+/g,'-')}`,name,continent:continentByCountry[name]||'Transcontinental',worldClass:'un-member',travel:standardTravel,systems:coreSystems,status:'registry'}));
export const GLOBAL_SPECIAL_WORLDS:LivingEarthEntry[]=[
 {id:'observer-holy-see',name:'Holy See / Vatican City',continent:'Europe',worldClass:'un-observer',travel:['walk','bus','rail','holo-portal'],systems:coreSystems,status:'registry'},
 {id:'observer-palestine',name:'State of Palestine',continent:'Asia',worldClass:'un-observer',travel:['walk','car','bus','holo-portal'],systems:coreSystems,status:'registry'},
 {id:'associated-cook-islands',name:'Cook Islands',continent:'Oceania',worldClass:'associated-state',travel:['plane','boat','holo-portal'],systems:coreSystems,status:'registry'},
 {id:'associated-niue',name:'Niue',continent:'Oceania',worldClass:'associated-state',travel:['plane','boat','holo-portal'],systems:coreSystems,status:'registry'},
 {id:'special-taiwan',name:'Taiwan',continent:'Asia',worldClass:'disputed-or-limited-recognition',travel:['metro','high-speed-rail','plane','boat','holo-portal'],systems:coreSystems,status:'hub-seeded'},
 {id:'special-kosovo',name:'Kosovo',continent:'Europe',worldClass:'disputed-or-limited-recognition',travel:['car','bus','rail','plane','holo-portal'],systems:coreSystems,status:'registry'},
 {id:'special-western-sahara',name:'Western Sahara',continent:'Africa',worldClass:'disputed-or-limited-recognition',travel:['car','plane','holo-portal'],systems:coreSystems,status:'registry'},
 {id:'research-antarctica',name:'Antarctica',continent:'Antarctica',worldClass:'research-region',travel:['plane','boat','holo-portal'],systems:['research-expeditions','science','weather-survival-fiction','accessibility','translation','cloud-save'],status:'registry'}
];
export const TERRITORY_FRAMEWORK={enabled:true,policy:'Territories/dependencies and special administrative regions are separate destination records linked to a parent jurisdiction; geopolitical labels remain data-driven and configurable.',examples:['Puerto Rico','U.S. Virgin Islands','Guam','American Samoa','Northern Mariana Islands','Greenland','Faroe Islands','Bermuda','Cayman Islands','British Virgin Islands','Turks and Caicos Islands','Anguilla','Montserrat','Gibraltar','Guadeloupe','Martinique','French Guiana','Reunion','Mayotte','French Polynesia','New Caledonia','Aruba','Curacao','Sint Maarten','Bonaire','Saba','Sint Eustatius','Hong Kong','Macao']};
export const LIVING_EARTH={version:'1.0.0',scope:'whole-globe',baseline:{unMembers:193,unObservers:2},worlds:[...UN_MEMBER_WORLDS,...GLOBAL_SPECIAL_WORLDS],territoryFramework:TERRITORY_FRAMEWORK,engines:['unreal','unity','godot','web-holo'],streaming:'region->country/territory->city->district->interior',persistence:['avatar','xp','inventory','entitlements','businesses','properties','sports-career','creator-career','missions','secrets','npc-relationships','accessibility','language','teen-safety'],rules:['No destination is considered playable merely because it exists in the registry.','Local content requires researched cultural and geographic data before production.','Real-world active conflicts are not converted into entertainment missions.','Disputed-status labels remain configurable data rather than gameplay advocacy.','Holo Portal is fictional in-game travel; conventional transport remains available.']};
export function auditLivingEarth(){const names=new Set(UN_MEMBER_WORLDS.map(x=>x.name));return {expectedMembers:193,registeredMembers:names.size,duplicateFree:names.size===UN_MEMBER_WORLDS.length,wholeGlobeRegistryReady:names.size===193,territoryFrameworkReady:TERRITORY_FRAMEWORK.enabled};}
