export type VerticalId='gameverse'|'immersive'|'university'|'mobile'|'marketplace'|'live'|'creator'|'property'|'accessibility'|'call-center'
export type CTA={label:string;action:string;kind:'primary'|'secondary'|'help'}
export type VerticalLanding={id:VerticalId;name:string;headline:string;problem:string;promise:string;benefits:string[];proof:string[];primaryCTA:CTA;secondaryCTA:CTA;helpCTA:CTA}

export const VERTICAL_LANDINGS:VerticalLanding[]=[
 {id:'gameverse',name:'GameVerse / StreetVerse',headline:'Enter a living world that remembers you.',problem:'Players need a clear path from discovery to play, creation and return.',promise:'One TRYAMM Passport connects character, missions, World Memory, movie tools and multiplayer progression.',benefits:['Create/claim character','Enter StreetVerse','World Memory','Movie/reel creation','LIVE/PK and multiplayer'],proof:['8/8 browser proof on core release slice','checkpoint + mission contracts','shared Passport architecture'],primaryCTA:{label:'PLAY NOW',action:'tryamm:gameverse-open',kind:'primary'},secondaryCTA:{label:'CREATE A MOVIE',action:'tryamm:movie-studio-open',kind:'secondary'},helpCTA:{label:'ASK TRYAMM AI',action:'tryamm:callcenter-open',kind:'help'}},
 {id:'immersive',name:'Immersive Library / Reality Lab',headline:'Research history. Enter it. Create what comes next.',problem:'Museums and archives can become passive instead of participatory.',promise:'Evidence becomes holographic reconstruction, playable missions, original creation, provenance and World Memory.',benefits:['Immersive exhibits','Archive missions','Evidence classification','Original art/music creation','Legacy/education loop'],proof:['14-experience Chicago World Museum wing','archive-to-creator mission engine','Reality Lab accessibility + multiplayer proof'],primaryCTA:{label:'ENTER IMMERSIVE',action:'tryamm:immersive-open',kind:'primary'},secondaryCTA:{label:'OPEN REALITY LAB',action:'tryamm:realitylab-open',kind:'secondary'},helpCTA:{label:'ASK A CURATOR AI',action:'tryamm:callcenter-open',kind:'help'}},
 {id:'university',name:'All American University & Academy',headline:'Learn → build skills → create proof → reach opportunity.',problem:'Education, career support and portfolio proof are usually fragmented.',promise:'A connected student journey from Pre-K/adult learning through courses, labs, credentials, portfolio and opportunity.',benefits:['Learning Passport','Student AI/Jarvis','Courses + assignments','Labs + accessibility','Internships/jobs/opportunities'],proof:['University data model','student/faculty/course/credential/lab tables','learning + opportunity services'],primaryCTA:{label:'EXPLORE UNIVERSITY',action:'tryamm:university-open',kind:'primary'},secondaryCTA:{label:'FIND A PROGRAM',action:'tryamm:university-programs',kind:'secondary'},helpCTA:{label:'TALK TO STUDENT AI',action:'tryamm:callcenter-open',kind:'help'}},
 {id:'mobile',name:'TRYAMM Mobile / All American Mobile',headline:'Wireless service connected to the TRYAMM ecosystem.',problem:'Wireless, creator tools, family plans and support live in separate systems.',promise:'A dual-brand MVNO-ready experience with family/agency lanes, Jacobie Vision security and HoloFon readiness.',benefits:['Family/business plans','Agency/franchise lane','Quantum connection engine','Jacobie Vision security','HoloFon roadmap'],proof:['feature-gated mobile control center','agency persistence + RLS','carrier/provider gates preserved'],primaryCTA:{label:'EXPLORE MOBILE',action:'tryamm:mobile-open',kind:'primary'},secondaryCTA:{label:'START AN AGENCY',action:'tryamm:agency-open',kind:'secondary'},helpCTA:{label:'WIRELESS HELP',action:'tryamm:callcenter-open',kind:'help'}},
 {id:'marketplace',name:'All American Marketplace',headline:'Discover, buy, sell, hire and build.',problem:'Creators, businesses and customers need one commerce surface.',promise:'Connect storefronts, services, creator campaigns, jobs and eligible transactions under one identity.',benefits:['Storefronts','Creator campaigns','Jobs/recruiting','Business discovery','Analytics'],proof:['commerce OS foundations','marketplace launcher','payout/ledger architecture'],primaryCTA:{label:'OPEN MARKETPLACE',action:'tryamm:marketplace-open',kind:'primary'},secondaryCTA:{label:'CLAIM A BUSINESS',action:'tryamm:business-claim-open',kind:'secondary'},helpCTA:{label:'BUSINESS HELP',action:'tryamm:callcenter-open',kind:'help'}},
 {id:'live',name:'TRYAMM LIVE',headline:'Go live, collaborate, PK and build an audience.',problem:'Creators need LIVE plus safe private team coordination.',promise:'LIVE/PK, internal backchannel, moderation, recording and creator-growth tools in one system.',benefits:['LIVE rooms','PK','private team comms','moderation','replay/creator workflow'],proof:['authenticated LIVE token path','PK backchannel RLS','protected-call safety architecture'],primaryCTA:{label:'GO LIVE',action:'tryamm:live-open',kind:'primary'},secondaryCTA:{label:'JOIN AGENCY',action:'tryamm:agency-open',kind:'secondary'},helpCTA:{label:'CREATOR SUPPORT',action:'tryamm:callcenter-open',kind:'help'}},
 {id:'creator',name:'Creator Economy',headline:'Create → grow → verify → earn.',problem:'Creators need transparent progress and multiple ways to build a business.',promise:'Quota Coach, Beans, rebates, agency tools, movies/reels, marketplace and mobile campaigns with verified ledgers.',benefits:['Bean Vault','Quota Coach','Creator tiers','Agency tools','verified reward eligibility'],proof:['creator growth engine','agency attribution','money-safety pipeline'],primaryCTA:{label:'START CREATING',action:'tryamm:movie-studio-open',kind:'primary'},secondaryCTA:{label:'START AN AGENCY',action:'tryamm:agency-open',kind:'secondary'},helpCTA:{label:'CREATOR COACH',action:'tryamm:callcenter-open',kind:'help'}},
 {id:'property',name:'Property / Housing',headline:'Find, evaluate, apply and build responsibly.',problem:'Housing and property workflows require clearer eligibility, documents and risk disclosures.',promise:'A rights-aware property pathway with verified listings, applications, environmental gates and support.',benefits:['Housing search','applications','verified property data','environmental-property lane','business/property education'],proof:['housing architecture','environmental landfill safeguards','marketplace integration'],primaryCTA:{label:'EXPLORE PROPERTY',action:'tryamm:property-open',kind:'primary'},secondaryCTA:{label:'GET HELP',action:'tryamm:callcenter-open',kind:'secondary'},helpCTA:{label:'HOUSING SUPPORT',action:'tryamm:callcenter-open',kind:'help'}},
 {id:'accessibility',name:'Omni Access',headline:'TRYAMM adapts to the person using it.',problem:'Most apps make accessibility a setting page instead of a platform contract.',promise:'Voice, one-handed, reduced-motion, high-contrast, sign-language and accessibility-passport support across experiences.',benefits:['Accessibility Passport','one-handed UI','reduced motion','sign language','assistive navigation'],proof:['accessibility components','Reality Lab accessibility proof','shared accessibility contracts'],primaryCTA:{label:'OPEN OMNI ACCESS',action:'tryamm:accessibility-open',kind:'primary'},secondaryCTA:{label:'SET MY ACCESS NEEDS',action:'tryamm:accessibility-open',kind:'secondary'},helpCTA:{label:'ACCESSIBILITY HELP',action:'tryamm:callcenter-open',kind:'help'}},
 {id:'call-center',name:'TRYAMM AI Call Center',headline:'Get help without getting trapped in a loop.',problem:'Automated support often repeats itself and blocks escalation.',promise:'Intent routing, loop detection, human escape routes, context-preserving escalation and consent-aware follow-up.',benefits:['anti-loop guardian','human/callback escape','context handoff','vertical routing','CRM attribution'],proof:['loop policy contract','escalation triggers','no forced repetition design'],primaryCTA:{label:'TALK TO TRYAMM',action:'tryamm:callcenter-open',kind:'primary'},secondaryCTA:{label:'REQUEST CALLBACK',action:'tryamm:callback-open',kind:'secondary'},helpCTA:{label:'START OVER',action:'tryamm:callcenter-reset',kind:'help'}},
]

export const CONVERSION_CONTRACT=['headline','problem','promise','benefits','proof/trust','primary CTA','secondary CTA','AI/help CTA','lead attribution','follow-up consent'] as const
export const CONVERSION_TRUTH='A landing page may optimize clarity and conversion, but it must not manufacture testimonials, guaranteed results, fake urgency, fake scarcity, fake savings, fake accreditation, fake earnings or unavailable provider capabilities.'
