export type Fulfillment='in_game_preview'|'pickup'|'local_delivery'|'shipping'
export interface PhysicalStorefront{ id:string; name:string; districtId:string; physicalLocationVerified:boolean; address?:string; hoursVerified:boolean; inventorySource:'pos'|'manual'|'provider'; taxConfigured:boolean; foodSafetyVerified:boolean; fulfillment:Fulfillment[]; liveInWorld:boolean }
export interface GroceryItem{ sku:string; name:string; category:'produce'|'pantry'|'beverage'|'frozen'|'household'|'prepared_food'|'other'; priceCents:number; currency:'USD'; stock:number; ageRestricted:false; taxable:boolean; fulfillment:Fulfillment[]; physicalInventoryRequired:true }
export interface StoreOrder{ orderId:string; userId:string; items:{sku:string;qty:number}[]; subtotalCents:number; taxCents:number; deliveryCents:number; totalCents:number; providerReceiptId:string; fulfillment:Exclude<Fulfillment,'in_game_preview'>; status:'pending'|'paid'|'preparing'|'ready'|'out_for_delivery'|'completed'|'refunded'|'cancelled' }
export const YAHAVAH_GROCERY:PhysicalStorefront={id:'yahavah-grocery-01',name:'YAHAVAH Grocery',districtId:'streetverse_district_01',physicalLocationVerified:false,hoursVerified:false,inventorySource:'manual',taxConfigured:false,foodSafetyVerified:false,fulfillment:['in_game_preview'],liveInWorld:true}
export const STORE_GAMEPLAY=['walk_into_store','browse_shelves','inspect_products','npc_mpc_staff','creator_popups','community_missions','basket_to_checkout','pickup_counter','delivery_dispatch','world_pulse_stock_and_crowd_reactions'] as const
export const LAUNCH_GATES=['verify_legal_business_operator','verify_physical_address_or_mark_digital_only','verify_required_food_retail_licenses','configure_sales_tax','connect_real_inventory_or_pos','connect_payment_provider','configure_refunds_and_substitutions','configure_pickup_delivery_zones','run_sandbox_order','run_real_staff_fulfillment_test','privacy_and_security_review'] as const
export function canAcceptRealOrders(s:PhysicalStorefront){return s.physicalLocationVerified&&s.hoursVerified&&s.taxConfigured&&s.foodSafetyVerified&&s.fulfillment.some(f=>f!=='in_game_preview')}
export const HYBRID_FLOW='STREETVERSE STORE → DIGITAL SHELF → REAL INVENTORY CHECK → CART → MONEY ENGINE/PAYMENT PROVIDER → TAX → ORDER → PHYSICAL PICK/PACK → PICKUP/DELIVERY/SHIP → RECEIPT → FOUNDER REVENUE COCKPIT' as const
